### PR TITLE
Not edit library PubSubClient.

### PR DESCRIPTION
**Pull request by Sergey-SRG**
That would not edit library PubSubClient for each project.

### CODE REVIEW

**Comment by arendst** [comment]
Serge, tried it a year ago. Might work with platformio but pls verify it works  with Arduino ide as that always failed.

**Comment by Sergey-SRG** [comment]
Works perfectly with Arduino ide.

**Comment by ascillato** [comment]
This is exactly as #1634.

The code works on Arduino IDE

**Comment by Sergey-SRG** [comment]
A more practical solution, it is better to accept it #1634

**Comment by Sergey-SRG** [comment]
#1634

**Review by ascillato — APPROVED** [review]
As in #1634 and #1657, this approach is good so as not to modify another libraries.

If you want, can be added also a warning to the user like:

```
// Max message size calculated by PubSubClient is (MQTT_MAX_PACKET_SIZE < 5 + 2 + strlen(topic) + plength)
#if (MQTT_MAX_PACKET_SIZE -TOPSZ -7) < MIN_MESSZ  // If the max message size is too small, throw a warning at compile time. See PubSubClient.cpp line 359
  #warning "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increasing it to 1000"
  #undef MQTT_MAX_PACKET_SIZE
  #define MQTT_MAX_PACKET_SIZE 1000
#endif
```

**Comment by ascillato** [comment]
There is also a small typo error on a comment on this file (_sonoff.ino_) Line 28:

#include "sonoff.h"                         // **Enumaration** used in user_config.h

and should be

#include "sonoff.h"                         // **Enumeration** used in user_config.h

**Pull request closed without merging**
