### PR TITLE
Ufsys

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

language files change sd card to UFS
directory listig -> scroll view

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
I think we have to rethink this ufs stuff Unless it already works this way).

What I want is this on ESP32:
- As every ESP32 has a filesystem partition, either LittleFS OR FFat it needs to be the primary filesystem to store future settings.
- Any connected SD card must be an ADDITIONAL filesystem and should not take over the embedded partiton filesystem. If it does take over it ruins any settings stored on the embedded partition.

On ESP8266 I can live with your current SD-Card usage.

Can you verify this is the case already and if not we have to make it this way.

**Comment by gemu2015** [comment]
since only very few people will use sd cards i see no conflict for the time being.  simply do not define USE_SDCARD
i can think about how to have an extra filesystem in this case for the future.

**Comment by gemu2015** [comment]
ok checked it.  its easy to accomplish.  i need a day or 2 to implement this.

**Comment by gemu2015** [comment]
ok is already implemented in commit.  
a new FS pointer *ffsp holds a pointer to Flashfile in any case. (nullptr if not found) even when sd card found
ufsp points to the global file system including sd.
the only thing is that currently ufsp points to global directory. if an SD card found the directory shows the SD card not the flash. the flash is hidden in this case.
i may easily switch between the 2 if wanted.

**Comment by arendst** [comment]
Just keep it this way.

I will move the zigbee settings to the new ffsp pointer.

Thx.

**Pull request merged**
