### PR TITLE
Berry Zigbee integration for received messages

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

**Experimental Feature**

Berry mapping for Zigbee.

Provides the ability to register handlers that are called whenever a Zigbee message is received. There are currently 3 handlers called at various steps; each handler can modify the received data at will.

- `frame_received` called when a new Zigbee frame is received. Zigbee packet is decoded but payload (ZCL) is raw bytes
- `attributes_raw` called when ZCL attributes have been decoded (raw values) but before any post-processing is done
- `attributes_refined` called after all attribute processing is done (especially converting to attributes names) but before the message is published as a Tasmota MQTT message

Handler takes 4 arguments `def frame_received(event_type, frame, attr_list, shortaddr)`:
- `event_type` (string) name of the event (`frame_received`, `attributes_raw` or `attributes_refined`)
- `frame` (instance of `zigbee.zcl_frame`) contains the raw ZCL frame (can be modified with care)
- `attr_list` (instance of `zigbee.zcl_attribute_list` or `nil`) contains the list of attributes or commands, or `nil` for `frame_received` since attributes are not yet decoded
- `shortaddr` (int) source short address (16 bits) of the device that sent the message. You can use `zigbee[shortaddr]` to retrieve the device definition

Example of code:
``` berry
import zigbee
class zb_debug
  def frame_received(event_type, frame, attr_list, shortaddr)
    print("frame_received:", frame)
  end
  def attributes_refined(event_type, frame, attr_list, shortaddr)
    print("attributes_refined:", attr_list)
  end
  def attributes_raw(event_type, frame, attr_list, shortaddr)
    print("attributes_raw:", attr_list)
  end
end
var zd = zb_debug()
zigbee.add_handler(zd)
```

Example, when receiving the following message (power consumption from Blitzwolf SHP15):
```
20:17:22.268 ZIG: {"ZbZNPReceived":"44810000040BEF340101001500520DBE00000F18040105050021F3000B0500290100DC491C"}
20:17:22.269 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0B04","srcaddr":"0x34EF","srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":21,"securityuse":0,"seqnumber":0,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":4,"cmdid":"0x01","payload":"05050021F3000B0500290100"}}
20:17:22.313 ZIG: ZbZCLRawReceived: {"0x34EF":{"0B04/0505":243,"0B04/050B":1,"Endpoint":1,"LinkQuality":21}}
20:17:22.767 MQT: tele/tasmota/ZBBridge/SENSOR = {"ZbReceived":{"0x34EF":{"Device":"0x34EF","Name":"Plug_Mac","RMSVoltage":243,"ActivePower":1,"Endpoint":1,"LinkQuality":21}}}
```

Below is the output from the Berry handlers:
```
frame_received: {'cluster_specific': 0, 'cmd': 1, 'shortaddr': 13551, 'payload': bytes('05050021F3000B0500290100'), 'manuf': 0, 'transactseq_set': 0, 'transactseq': 4, 'groupaddr': 0, 'direct': 0, 'cluster': 2820, 'payload_ptr': <ptr: 0x3ffb47e4>, 'dstendpoint': 1, 'shortaddr_hex': '0x34EF', 'need_response': 0}

attributes_raw: {"0B04/0505":243,"0B04/050B":1,"Endpoint":1,"LinkQuality":21}

attributes_refined: {"RMSVoltage":243,"(RMSVoltage)":"0B04/0505","ActivePower":1,"(ActivePower)":"0B04/050B","Endpoint":1,"LinkQuality":21}
```

The above packet is a response to a an attribute read command, with a raw payload of `'05050021F3000B0500290100'`. When decoded to raw ZCL, it shows `"0B04/0505":243,"0B04/050B":1` which decodes to `"RMSVoltage":243,"ActivePower":1`. The string output shows `"(RMSVoltage)":"0B04/0505"` to indicate that `RMSVoltage` is a synonym for `0B04/0505`.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.4.1
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by mipurel** [comment]
When I run example code, I get this output from the Berry console:

```
frame_received: {'cluster_specific': 0, 'cmd': 10, 'shortaddr': 2652, 'payload': bytes('210020C8'), 'manuf': 0, 'transactseq_set': 0, 'transactseq': 206, 'groupaddr': 0, 'direct': 0, 'cluster': 1, 'payload_ptr': <ptr: 0x3ffdf2e4>, 'dstendpoint': 1, 'shortaddr_hex': '0x0A5C', 'need_response': 0}
attributes_raw: BRY: Exception'attribute_error' - 'int' value has no method 'tojson'
attributes_refined: BRY: Exception'attribute_error' - 'real' value has no method 'tojson'
frame_received: {'cluster_specific': 0, 'cmd': 10, 'shortaddr': 2652, 'payload': bytes('0000297009'), 'manuf': 0, 'transactseq_set': 0, 'transactseq': 207, 'groupaddr': 0, 'direct': 0, 'cluster': 1026, 'payload_ptr': <ptr: 0x3ffb5d50>, 'dstendpoint': 1, 'shortaddr_hex': '0x0A5C', 'need_response': 1}
attributes_raw: BRY: Exception'attribute_error' - 'int' value has no method 'tojson'
attributes_refined: BRY: Exception'attribute_error' - 'real' value has no method 'tojson'
frame_received: {'cluster_specific': 0, 'cmd': 10, 'shortaddr': 2652, 'payload': bytes('000021FD13'), 'manuf': 0, 'transactseq_set': 0, 'transactseq': 208, 'groupaddr': 0, 'direct': 0, 'cluster': 1029, 'payload_ptr': <ptr: 0x3ffb5d50>, 'dstendpoint': 1, 'shortaddr_hex': '0x0A5C', 'need_response': 1}
attributes_raw: BRY: Exception'attribute_error' - 'int' value has no method 'tojson'
attributes_refined: BRY: Exception'attribute_error' - 'real' value has no method 'tojson'
```
Is something missing in the example code?

**Comment by s-hadinger** [comment]
This is outdated. Documentation is there https://tasmota.github.io/docs/Berry/#zigbee

**Comment by sfromis** [comment]
That docs does not make it clear how to use those `frame_received`, `attributes_raw` and `attributes_refined`.  No mention of add_handler, or what arguments the callback methods are now getting.

**Comment by s-hadinger** [comment]
True. It's mostly incomplete for now. The main reason is that nobody had any needs for it until now. 

What are you trying to achieve?

**Comment by mipurel** [comment]
@sfromis is right, proper information in the docs is needed. It's hard to trace the way from embedded Berry code libraries. The log is from the temperature and humidity sensor but  I am trying to add handler for Aqara Magic Cube on ZigbeeBridgePro.  Z2Tv1 plugin and rules are not enough so I want to achieve this in Berry. I know @s-hadinger is very busy implementing Matter, expanding Berry capabilities in Tasmota I admire his work for the community.

**Comment by sfromis** [comment]
I found that current argument to the debug callbacks are `(event_type, frame, attr_list, shortaddr)`, with `attr_list` being `nil` for `frame_received`, and printing the `zcl_attribute_list` instance gives messages like
`BRY: Exception> 'attribute_error' - 'int' value has no method 'tojson'`
Saw no issues printing the `zcl_frame` instances, and shortaddr is just an int.

**Comment by sfromis** [comment]
My expectation was that the intended setup for adding further attribute parsing would be to code a callback for `attributes_raw` (or maybe `attributes_refined`) to loop through available attributes, to update specific ones to a similar format as the default parsing. But how is that supposed to be done?

**Pull request merged**
