### PR TITLE
Merge sleep command

### PR DESCRIPTION
**Pull request by andrethomas**
Merge the sleep command to be used for both normal and dynamic sleep modes.

Upgrade from a previous version will cause sleep to be set to 50 with dynamic sleep enabled.

Sleep mode can be changed using SetOption60 (0 = Dynamic Sleep, 1 = Normal Sleep)

The SetOption36 command is deprecated in favour of this method.

### CODE REVIEW

**Comment by andrethomas** [comment]
Thx, that was a quick merge :)

**Comment by arendst** [comment]
Yes. I'm cleaning it up a bit and will merge shortly.

**Comment by arendst** [comment]
Done.

**Comment by andrethomas** [comment]
Thanks :)

**Pull request merged**
