### PR TITLE
ESP32 port with minimal changes

### PR DESCRIPTION
**Pull request by joerg555**
## ESP port with minimal changes
This is my esp32 port, i try to make only minimal changes to the original source code from Theo Arends.

Sorry, i branch master because i have problems with development.
Please try it and tell me your things

Here are the main things i have done 

- in "lib_extra_dirs" i have libesp32 directory for things missing in ESP32 framework
- my "ESP32-to-ESP8266-compat" has all files that are not available in ESP32
  so you dont have to change the source code and i write code to get the informations from ESP32
- all librarys that are not compatibel i add to lib_ignore
- all code that is not for ESP32 i put in "#ifdef ESP8266" the define is from espessif platform
- all code for ESP32 is in "#ifdef ESP32"
- changed SerialConfig variable  from uint8_t to SerialConfig
- changed "HTTP_HEADER" to "HTTP_HEADER1", in ESP32 its an enum
- for ip adress 0 i used IPAddress(0,0,0,0)
- Special ESP.xxx call i change to ESP_xxx (ESP_rtcUserMemoryWrite, ...) and write macros for ESP8266
- because ESP32 has only WEMOS 32 modul, i exclude all code like this:
  "if (SONOFF_xxx == Settings.module)" in "#ifdef ESP8266"
- variable "sleep" i changed to "ssleep" because of standard library sleep(..) function
- all esp32 stuff is in support_esp32.ino
- in tasmota.ino i include "tasmota_compat.h"
- in tasmota_template.h i use ifdef and tasmota_templESP32.h
- defines for sensors that currently don't work, i undef in tasmota_templESP32.h
- no warnig in "xdrv_20_hue.ino" thats the only warning i had 

## Build info 
copy platformio_override_esp32.ini to platformio_override.ini an select your imagetype

stay at home, have fun and keep good

Jörg

### CODE REVIEW

**Comment by s-hadinger** [comment]
Wow.  Impressive work. I believe this should be a fork, not a PR to merge onto Tasmota

**Comment by ascillato** [comment]
@joerg555 

There are conflicting files, can you solve them?

Also, your PR try to delete some files that are not related to esp32 like _**updateDocs.sh**_


@s-hadinger 

> I believe this should be a fork, not a PR to merge onto Tasmota

why?

**Comment by ascillato** [comment]
@joerg555

Hi, if I try to see your changes from your fork (master_esp32 branch) compared to Tasmota master branch, is easy to follow them, but from your master to development it can't be followed. Too many changes.

Are you able to remake this PR but from development branch to development branch?

Your changes are just 6 commits modifying 55 files, but in this PR there are 171 commits and 84 modified files.

As it is, this PR can't be merged because it deletes the new changes from master to actual development version.

**Comment by Jason2866** [comment]
GREAT WORK!!

I have the same opinion as @s-hadinger . It is a fork (on another SDK platform).
These two platforms should not be mixed together. Tasmota is highly optimized for ESP8266 and intervenes deeply in the system-specific features of this platform. Therefore no merge and continue the project as a fork or independent branch.

**Comment by s-hadinger** [comment]
To be clear, this is definitely great work. But mixing both in the same branch creates lots of problems. First you make the code harder to maintain, second any change in the development branch may break the ESP32 part. I think it's better to have a fork (or a separate branch), this way you can regularly merge and test.

**Comment by Jason2866** [comment]
I get a compile error:
```
In file included from /workspace/Tasmota/tasmota/tasmota.ino:55:0:
libesp32/ESP32-to-ESP8266-compat/src/ESP8266httpUpdate.h:4:24: fatal error: httpUpdate.h: No such file or directory
```

**Comment by sfromis** [comment]
A major raison d'être for Tasmota is the ability to put alternative, more DIY friendly firmware on commercial IoT devices, like switches, lights and so on. Makes me wonder about two things. Are there many such commercial IoT devices with ESP32 out there? What would be the plan for being able to say "this thingie has ESP32, let's flash Tasmota, 1, 2, 3, done"?

I've got the Yeelight Meteorite lamp with ESP32. Being able to easily flash that would make this fork (?) more interesting to me. OTOH, the lamp has already got a reasonably nice UDP/JSON API, so I'm happy with it as it is now, not really gaining much from being able to Tasmotize it, other than getting it "into the fold".

Also, with the Arm-based chips now steamrolling into the IoT field, I'm not very optimistic of the chances of ESP32 gaining wide adoption, except possibly in devices more complex than the target realm of Tasmota.

**Comment by arendst** [comment]
Thx for the works you've done!

As a succesful compile depends on synergy between ESP8266 tasmota development and ESP32 I also suggest to make a seperate branch for this. Once all is ironed out it might be incorporated with the current Tasmota.

**Comment by joerg555** [comment]
Thanks for your reply,

i have the problem, that the development branch is not in sync with 
master branch.

Now i have new *development_esp32* branch with my ESP32 port.

i check now to get exact the same byte code for ESP8266, when i finish i 
can make a PR for development branch

Questions:

- what is your workflow to come from development to master


MfG Jörg Schüler-Maroldt
Baade-GmbH
(0511)2621949 (0175)5439138

Am 09.04.2020 um 09:30 schrieb s-hadinger:

**Comment by arendst** [comment]
Workflow is from development to pre-release. Changing versions in version.h, changelog and releasenotes and then merge in master.

Releases are made from master.

**Comment by arendst** [comment]
BTW development can be months out of sync with master (pre-release) depending on release dates.

**Comment by kugelkopf123** [comment]
@sfromis 
I am in complete agreement with you on this, as far as consumer electronics are concerned. 
However, this port also has many advantages. Of course, these are more likely to be found among hobbyists. 
This makes it possible to query a lot more sensors with one device. There are two complete HW Serials. 
The example of the SML driver: The polling of two electricity meters, gas and water meters, ebus heating and the control of the heat circulation pump via DS18x20 would be possible with one device. 

Or the control of the garden irrigation,>moisture sensor, weather data acquisition, UV sensor and shutter control in one device.

Apart from the larger number of GPIOs, there will certainly be projects in the future that can benefit from the higher performance and perhaps also from the co-processor.

**Comment by effelle** [comment]
Nice job @joerg555!
I'm too in favour of a fork instead of a complete merge. 
Waiting to finally kill the two esp32 with ESPHome I have in my house.

**Comment by joerg555** [comment]
Now i have nwe pull request for development branch

**Pull request closed without merging**
