### PR TITLE
Add SensorFilter Library

### PR DESCRIPTION
**Pull request by andrethomas**
Add SensorFilter library for Median and Average use.

A use case for Median is demonstrated by the change made in xsns_26_lm75ad.ino

**Usage for SensorFilter_Median**
``` 
 SensorFilter_Median MyMedian(x,y);  // where x = number of elements e.g. 9 and y the index which will be used e.g. 5
 newvalue = MyMedian.NewMedian(z);   // where z is the new value to be added to the sorted array to determine the median - new median is returned by the function
```
**Usage for SensorFilter_Average**
```
 SensorFilter_Average myAverage(x);  // where x = number of elements over which average will be calculated
 newvalue = myAverage.NewAverage(y); // where y is the new number to be added to the array on which average will be based - new average is returned by the function
```

### CODE REVIEW

**Comment by rasti70** [comment]
Thank you

Can you please show an example how to implement this routine for power measurement ?
I assume it must go somewhere in sonoff\xdrv_03_energy.ino but I have no clue how.

**Comment by andrethomas** [comment]
I'm guessing **_if_** Theo implements it will most likely be there, or perhaps device specific (e.g. xnrg_01_hlw8012) but I honestly have no clue... you'd have to wait for him to decide if, where and how he wants it :)

**Comment by arendst** [comment]
Pls hold your horses...

the way the HLW8012 driver works is that if enough power is used, like say >10W, it takes ten probes and provides the average to the user by simply adding all measurements and divide by ten. This way no additional RAM is used to store intermediate results. Works great on all but SHP6.

For the SHP6 this works great for Voltage; It's very stable. For both power and current it does not provide stable results.

Power is measured constantly from a dedicated power pin which provides a PWM pulse where it's pulse width is a measure of power. For some reason this single pin provides unstable data on the SHP6.

Current is measured alternated from another single pin with voltage. The code switches between current and voltage measurement every 10 probes taking into account the time it takes the chip to provide "stable" info. This works fine for all but SHP6. Apparently the SHP6 is not stable once switches to current measurement. It needs further analysis of samples when it can provide stable Current measurements.

Considering the tiny SHP housing and the fact that all is connected to AC this is a nice task for rubberman.

So to go forward 
- the SHP6 current measurement will need further analysis before deciding the signal is stable. This is a better approach then starting to uses average or median right now.
- the SHP6 power measurement is a different ballgame and having some kind of probe scanner could make life easier.

**Comment by andrethomas** [comment]
Does rubberman still have his rubber underpants? :)

Wish I had an SHP to debug it from a hardware perspective.

**Comment by andrethomas** [comment]
Mother of cow... I only now see what the thing looks like.

image

**Comment by arendst** [comment]
Right! If we can get it stable it's a great small device.

Let's continue here #4727

**Pull request closed without merging**
