### PR TITLE
BLE on ESP32 Xdrv 47 ble esp32 - a generic driver

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:
Introducing xdrv_47_BLE_ESP32.
This PR is for COMMENT and discussion - it should not be merged in it's current state.
I believe there is room for web UI support, and scan results -> MQTT (although this could be a separate driver - that's kind of the point).

Introduces a generic ESP32 BLE 'driver' designed to be used by other device drivers so that BLE can be used by multiple 'drivers' at once.

### The issue:
There are two BLE related xSns drivers - iBeacon (xsns_52) and a Sensor driver (xsns_62) which can be built in to support native ESP32 BLE.  These two drivers conflict, and cannot be used together.
At the moment, adding a BLE sensor would involve creating additional detailed functionality inside the xsns_62 driver for each device which we wished to support, or adding an additional driver.
I believe the style of the suggested generic driver will allow people to use existing sensors (and other BLE devices requiring read/write/notify access) with Tasmota without additional development within Tasmota.
It also allows 'popular' devices to have a specific driver within Tasmota, but sharing the BLE, and not conflicting.

### xdrv_46 provides:
1/ generic BLE scanning, catching advertisments with data, and calling registered callbacks.
2/ generic BLE 'operations'.
an operation can be setup through an API call, and provide a callback on success or failure.
Operations can also be setup and executed via commands, resulting in MQTT output on success or failure.
callbacks can be registered to 'hear' all operations.
3/ callbacks can be registered to see scan results at the end of a scan.

### Example modified drivers:
xsns_52_ibeacon.ino and xsns_62_MI_ESP32.ino are disabled by USE_BLE_ESP32

In their place, these are enabled:
xsns_52_ibeacon_BLE_ESP32.ino and xsns_62_MI_ESP32_BLE_ESP32.ino 
These have been adjusted to instead of using the NimBLE stack directly, to subscribe to services provided by xdrv_47_BLE_ESP32.

I believe I have included all the features required for the two sensor drivers that we have.

### use:
xdrv_47 is enabled via 
USE_BLE_ESP32 and ESP32
To use it, you must 'setoption115 1'.
It currently logs all adverts with extra data at LOG_LEVEL_DEBUG_MORE, and is fairly verbose about actions at LOG_LEVEL_DEBUG.
To enable xsns_52_ibeacon_BLE_ESP32 as well, add USE_IBEACON_ESP32
To enable xsns_62_MI_ESP32_BLE_ESP32 as well, add USE_IBEACON_ESP32

### documentation
I have added a lot of comments at the top about usage, and some examples are at the bottom of the main file.
It's a little unusual, as have added a .h file - this may no longer be required as I moved it from an xsns file to an xdrv file (so it gets included early?).
Will be happy to add/update documentation after discussion.

### Personal motivation:
I have both temp/humidity sensors and EQ-3 BLE radiator valves spread around a house.
I wanted an ESP32 based device which could act as a WIFI to BLE bridge working with both types of device.
Using the commands on the generic driver, I can read/write/notify against the EQ3 valves, and also hear the temp/humidity (once xsns_62 is updated).
I did not want to add all the bulk of an 'EQ3 driver' to Tasmota, preferring the heavy lifting of the variety of BLE command sets to be dealt with in something like Node Red.

### Requests:
I have prepared the xdrv_46 driver based on requirements gathered from xsns62, xsns52, and from my own EQ3 BLE requirements.  
This will not be a complete set of requirements to be able to read/write any BLE device completely generically, but is probably a fairly good start.
We probably can't create a generic driver which would deal with ALL BLE devices, but it would be really good to get verification that the driver is able to talk to some other devices other than the EQ3 devices.
Scan results are currently not published - there is a lot of information in the debug logs to work with, but I believe that scan results should be published - thoughts on this appreciated (e.g. should you have to ask for them, should they be a web UI feature, etc.).
E.g. thoughts on blocking devices in busy areas would be appreciated.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Dont get me wrong, this are just my personal thoughts.
I dont see a real benefit. If i understand it correct it adds code to read maybe?! somemore devices.
Why should this be done? A half supported device has no benefit. It will generate "only" entrys in issue section.
My suggestion only adding code for a real use case / device. All other code is just littering Tasmota.

**Comment by btsimonh** [comment]
Hi Jason,
the benefits:
1/ a common way to create sensor drivers which can co-exist and use BLE.  (e.g. MI and iBeacon now co-exist).
2/ it copes with a number of BLE failure modes gracefully. (3 weeks of logging, 150Mbytes of log data).
3/ Allows developers to hear and access devices not supported directly.  If these become popular, it's then very easy to make them part of Tasmota.  i.e. it prevents bloat in Tasmota.
4/ BLE is evil.  This driver brings all that 'evil' into one maintainable place.  One 'task', one thread, less risk, more maintainable.  Hopefully some of the evil will go away as we ride the IDF version up.
5/ You are correct, it does not 'support' a specific device or use case - hence why it is a xdrv, not an xsns.  It's not really intended to be used directly by end users.  But all of it's features ARE used by the MI driver, and so all are required for 'general' BLE.
br, simon.

**Comment by btsimonh** [comment]
would it help If I added an EQ3 radiator valve driver as a use case?
s

**Comment by btsimonh** [comment]
@Jason2866 - pls see
https://github.com/btsimonh/Tasmota/tree/xdrv_48_EQ3_ESP32

This adds a functional EQ3 TRV valve driver on top of the PR; as a demonstration of how a driver can be built on top easily.
EQ3 control comes up multiple times in the forum, so I am not alone in this desire.
And of course, this works along side the MI driver and the iBeacon driver - so you can sense the room temp and control the valve at the same time from the same Tasmota device.

Of course, because there has been no feedback about other BLE devices, I can't confirm that the same will be the case for other desired drivers.  But it xdrv_47 does support everything required for all the MI reading that requires connection, plus all required for EQ3, so there will be many other devices it will support.

br,
Simon

**Comment by blakadder** [comment]
Good approach to utilise BLE as a singular device a not treat is as different devices depending on the use as it is currently

**Comment by Jason2866** [comment]
Mhh, since ESP32 flash and ram is not such a rare good as for the ESP82XX why not merging 
(after release 9.2)? Let us see how BLE stuff goes with this changes.

**Comment by Staars** [comment]
Yes, I think this could be done after the next release.

**Comment by btsimonh** [comment]
:).  If anyone fancies trying to drag us up to a later IDF, I'd be happy to run more long term tests to see if the BLE gets better.  (a few web related things complain?).
I am considering if NimBLE is the right thing for us, both in memory use and because we don't need anything other than ESP32.  But h2zero has been **very** supportive....

**Comment by Jason2866** [comment]
NimBLE will be the way for Tasmota. Every other solution needs to much flash and memory.

**Comment by btsimonh** [comment]
@Jason2866  tentatively agree... but thinking it may be good to disconnect the drivers that use the BLE from needing to know it's NimBLE behind it.  e.g. making functions on the BLE driver which get the bits currently got from NimBLEAdvertisedDevice in advertisment callbacks, and have the pointer supplied in the callback opaque.  Just to future-proof us.
Thoughts?

**Comment by btsimonh** [comment]
need help with sensors..  have reports of a crash on sensors which need a connection.  Need someone who has the sensors to debug?
Latest push is more stable ref scanning....

**Comment by btsimonh** [comment]
failing because of BG language!

**Comment by btsimonh** [comment]
keep holding - improvements coming - have a 'partner in crime' and receiving more sensors in a few days, so don't add until we are done.
thanks,
simon

**Comment by btsimonh** [comment]
issing a new one over latest development branch

**Pull request closed without merging**
