### PR TITLE
File UI changes

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:

The manage file UI does not handle folders very well.  With a few simple changes, it's a little more logical.

Remove recursion into folders on Manage Files.
Recursion may be enabled with UFILESYS_RECURSEFOLDERS_GUI.  

On Edit of a file, Save and Manage btuttons return to the folder containg the file being edited.  

On delete file, UI returns to the folder that the deleted file was in.

Newfile is now put in in the current folder, and returns to current folder on save or manage button.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.10
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Is this PR suppose to support folders in the GUI?

If I create and edit a new file called ''/theo/newfile.txt`` it shows an invalid filename page:
```
11:34:12.355-114/07 UFS: UfsEditor GET
11:34:12.366-114/06 UFS: UfsEditor: file=//newfile.txt, ffs_type=3, TfsFileExist=0
11:34:25.276-117/08 UFS: UfsEditor: file upload
11:34:25.278-117/08 UFS: UfsEditor: file '/theo/newfile.txt'
11:34:25.298-116/08 UFS: UfsEditor: 400: invalid file name '/theo/newfile.txt'
```

I also cannot see the impact of removing default behaviour now needing a define UFILESYS_RECURSEFOLDERS_GUI

**Comment by btsimonh** [comment]
@arendst - did you type the folder name, or create new file inside an existing folder?
I get your result if I change the folder name in the newfile text control - this should probably not be allowed, but that would be a more significant change.

The non-recursion means that when you display (e.g. the root folder), you won't see files inside other folders - with hyphens in front.  You have always been able to click on a folder to navigate to it's contents anyway, so I was not sure of the purpose of recursing in.

P.s. I'm seeing sporadic failure to download of a file on esp32  - I think the task based download is somewhat broken in that if the initial web handler closes the connection before the file is sent by the task, I see 'page sent no data', but a retry often succeeds.  It could be that my webcam task is keeping things quite busy, hence making the situation worse.

**Comment by arendst** [comment]
> I'm seeing sporadic failure to download of a file on esp32

Seen it too since the start so don't bother.

> did you type the folder name, or create new file inside an existing folder

Using the GUI I clicked Creat and Edit file. Then changed the filename from /newfile.txt to /theo/newfile.txt and clicked save.

**Comment by btsimonh** [comment]
back now.  Having a play with creating the folder, even if you edit the name.  There will be little protection against being silly, but I'll report on if it works or not.

**Comment by btsimonh** [comment]
@arendst -
I have  done some more work on this today.
1/ you can now modify the folder in newfile - just beware there is no checking, but it will create the folder(s).  e.g. /a/b/c/newfile.txt will create /a then /a/b then /a/b/c if they don't exist. 
2/ I have added delete of folders (will only work if empty) - new feature.
3/ newfile/delete return to the expected (?) folder.
4/ temporarily disabled ESP32 'Download task' - added comment on an idea to fix it, but it IS currently unreliable and broken.
5/ enable folder listing of HUGE folders to be aborted (check the client is still connected for each new file entry sent).  Use the 'X' in the browser to halt the transfer, then the back button.  - Saves waiting for 5 minutes for the folder listing to populate on a massive number of files.
6/ added a `p` containing the current folder, if not `/`.

Tested on ESP32Cam with SD card.
I can't think of any further improvements :).  So please give a try, and let me know.
I've not compared code/mem sizes.  As this is esp8266 and esp32, we should check.  But there is not much additional code, and indeed some de-duplication.

br, Simon

**Comment by btsimonh** [comment]
Apologies, this PR also mistakenly includes the static file serving changes (separate PR).  They won't be enabled, but would be better as a separate PR as they merit more detailed discussion.  Also apparently not working in my build.  Should I remove from this PR?

**Comment by arendst** [comment]
Let's merge and see what happens ;-)

**Pull request merged**
