### PR TITLE
[New Feature] Add command `SwitchText` to change switches names in JSON

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

New feature introduce a new command `SwitchText` to replace the default "Switch*n*" name in the JSON messages by a custom meaningful text. Usefull when "Switch" inputs are used as general purpose digital input sensor (such door state, battery charging status...)
The command and associated code is inserted only if `USE_SWITCHTEXT` is defined.
When `USE_SWITCHTEXT` is not defined the only impact is 8 (`MAX_SWITCHES`) zero-length strings are reserved
into `Settings.text_pool`.
When a binary with `USE_SWITCHTEXT` is loaded for the 1st time, each `SET_SWITCH_TXT<n>` text setting is a zero-length
string. The JSON messages then use the default "Switch*n*" name.
Once `SwitchText<n>`has been used to defined a name, it is saved in the settings and further JSON messages will use
the custom name.
If a binary without `USE_SWITCHTEXT` is loaded after some `SwitchText<n>` have been defined, they remains as-is in the
text setting pool and JSON messages revert to legacy "Switch*n*" names.
`SwitchText` command syntax is similar to the `StateText` command:
- `SwitchText` : returns all 8 `SwitchText` values
- `SwitchText<x>` : returns the matching `SwitchText`value (where *\<x\>* is a number between 1 and 8)
- `SwitchText<x> <text>` : defines *\<text\>* as the new name for "Switch*x*"

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.5
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
A little demo of the JSON when using this feature with 8 switches defined :
```
20:08:23 MQT: tele/dev-4119/SENSOR = {"Time":"2020-10-31T20:08:23+01:00","Charging":"ON","Charged":"ON","FrontDoorOpen":"ON","RearDoorOpen":"ON","FridgeDoorOpen":"ON","FreezerDorrOpen":"ON","GarageDoorOpen":"ON","YetAnotherStupidSwitchText":"OFF"}
```

**Comment by arendst** [comment]
Nice thx. Will soon merge after my chk

**Comment by arendst** [comment]
Thx. Implemented my way.

**Comment by barbudor** [comment]
Thanks @arendst 
Was the main reason for doing "your way" being that I didn't make the changes in the most appropriate place ?
Regards

**Comment by arendst** [comment]
You almost had the most appropriate way ;-) but there were a few functions not needed. Also by consolidating the name decision in one function made both status and rule code less explosive.

Thx for your idea.

**Pull request closed without merging**
