### PR TITLE
Add support for Sonoff L1

### LINKED ISSUE #4935: Sonoff L1 LED Controller
Hello,

I have succesfully automated most functions in my home using Tasmota and the 4CH PRO R2 Sonoff modules. (Thanks for all the great work programming and documenting Tasmota BTW!) 
Now, I would like to add a few LED strips.

It might be that I am overlooking but is the Sonoff L1 LED Strip Controller not in the supported devices list? (see: https://www.banggood.com/Sonoff-L1-Smart-2M-5M-SMD5050-RGB-LED-Strip-LightWiFi-ControllerPower-Supply-Work-With-Alexa-DC12V-p-1396771.html?rmmds=search&ID=4775844707&cur_warehouse=CN )

I can see in the supported devices lists, some other LED controllers are supported from other vendors, but, as I found Sonoff to be quite reliable I wanted to stick with their hardware.

thanks!

### PR DESCRIPTION
**Pull request by reef-actor**
## Description:

**Related issue (if applicable):** fixes #4935

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by reef-actor** [comment]
Maybe hold off on this for now, color stat's are not being published when changing color with the remote as I thought they would.

**Comment by davidelang** [comment]
even if this doesn't reflect changes made directly via the remote, adding the ability to control this through MQTT is a big step forward.

Is there another reason to not include this support?

**Comment by reef-actor** [comment]
Some more updates to add some more functionality.
Currently working:
Set power, color & brightness via MQTT
MQTT update when IR controller is used to change color or power

Known issues:
No MQTT update when IR controller is used to change brightness

If anyone is available to test that the PS16DZ dimmer is still ok that would be reassuring.

The HomeAssistant config I am using

```
- platform: mqtt
  name: 'RGB strip'
  command_topic: 'cmnd/rgbstrip/POWER'
  state_topic: 'stat/rgbstrip/POWER'
  payload_on: 'ON'
  payload_off: 'OFF'

  rgb_command_topic: 'cmnd/rgbstrip/COLOR'
  rgb_command_template: '{{ "%02x%02x%02x" | format(red, green, blue)}}'
  rgb_state_topic: 'stat/rgbstrip/RESULT'
  rgb_value_template: '{% if value_json.Color is defined %}{{ value_json.Color[0:2]|int(base=16) }},{{ value_json.Color[2:4]|int(base=16) }},{{ value_json.Color[4:6]|int(base=16) }}{% else %}{{ states.light.rgb_strip.attributes.rgb_color|join(",") }}{% endif %}'

  availability_topic: 'tele/rgbstrip/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
```

**Comment by mprins** [comment]
@stale up

**Comment by reef-actor** [comment]
I have created a new PR #6002 for this

**Pull request closed without merging**
