### PR TITLE
ported range_extender to ESP-IDF v5

### PR DESCRIPTION
**Pull request by pharaocurt**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.7
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by pharaocurt** [comment]
ported xdrv_58_range_extender to work with current ESP-IDF v5.
i had do add new #define USE_WIFI_RANGE_EXTENDER_PORTADD, which must not be defined for correct linking, else an undefined reference error will occur: ip_portmap_add. This function is defined in lwip/lwip_napt.h, but only compiled with defined option IP_NAPT_PORTMAP on generation of arduino-esp32 library. Therefore it is currently not possible to add a portmap to enable access of a port from main network on the range extended network without added route to extended network at main gateway.
If arduino-esp32 library will be enhanced by IP_NAPT_PORTMAP, my changes with USE_WIFI_RANGE_EXTENDER_PORTADD can be removed, but this feature could not be verified currently.

**Comment by pharaocurt** [comment]
ported xdrv_58_range_extender.ino to ESP-IDF v5. Tested to work correctly on ESP32 with and without NAPT, but prevoius full features could not be reached.
I had to add definition #define USE_WIFI_RANGE_EXTENDER_PORTADD, which must not be defined for final correct linking, else:
undefined reference to `ip_portmap_add'. This function is defined in "lwip/lwip_napt.h", but only compiled and available with option IP_NAPT_PORTMAP, which seems beeing undefined in tasmotas arduino-esp32 library. With enhanced arduino-esp32 library, the #ifdef USE_WIFI_RANGE_EXTENDER_PORTADD and #endif can be removed to include full previous functionallity, but this is currently untested.

**Comment by sfromis** [comment]
Were you trying to fix the pending issue about the Range Extender failing compile?
https://github.com/arendst/Tasmota/issues/21200

**Comment by pharaocurt** [comment]
Yes, i think the Range Extender failing compile can be solved (with the limitation i mentioned above) by these few changes in my try range_extender branch. But i fail in creation of a correct pull request.

**Pull request closed without merging**
