### PR TITLE
Domoticz RSSI and Battery Quality

### PR DESCRIPTION
**Pull request by 0n3-70uch**
Hello,

I added support for Battery and RSSI quality in Domoticz. 

RSSI range: 0% to 10% (12 means disable RSSI in Domoticz)
Battery range: 0% to 200% (255 means disable Battery in Domoticz)

Battery 0%: ESP 2.6V (minimum operating voltage is 2.5)
Battery 100%: ESP 3.6V (maximum operating voltage is 3.6)
Battery 101% to 200%: ESP over 3.6V (means over maximum operating voltage)

**How to use:**
Enable `DomoticzStatusUpdate`

Greetings Fabi

quality

quality2

### CODE REVIEW

**Comment by 0n3-70uch** [comment]
Short update: We need to send the status after every Domoticz switch command. Because DOmoticz update the status with wrong values.

```
domoticz/out {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "Controlicz:Schrank",
   "dtype" : "Light/Switch",
   "id" : "00014054",
   "idx" : 4,
   "name" : "Fabian > Schrank",
   "nvalue" : 0,
   "stype" : "Switch",
   "svalue1" : "0",
   "switchType" : "On/Off",
   "unit" : 1
}
```

**Comment by 0n3-70uch** [comment]
Update 2: Add Domoticz "RSSI" and "Battery" to sensor

**Comment by arendst** [comment]
What's the need for battery info on an ac powered device?

**Comment by 0n3-70uch** [comment]
Hey, the battery is only an extra function. But you can see if your device is nearly the dead. I remember that someone had trouble with some devices. The vcc regulator was broken on the chip.

**Review by andreasg73 — APPROVED** [review]

**Comment by 0n3-70uch** [comment]
Thanks :-)

**Pull request closed without merging**
