### PR TITLE
Added MIDEA/KOMECO IRHVAC protocol

### PR DESCRIPTION
**Pull request by lvta0909**
Added support to MIDEA/KOMECO HVAC protocol.
Its somewhat similar to Mitsubishi hvac protocol.

More information about the protocol / source code reference:
http://veillard.com/embedded/midea.html
https://github.com/sheinz/esp-midea-ir/blob/master/midea-ir.c

### CODE REVIEW

**Comment by ascillato2** [comment]
Hi,

Thanks a lot for sharing your ideas. 

As Tasmota can't handle ALL possible IR protocols, due to flash size restrictions, we should be better implementing a RAW IR send/receive as requested at #2116.

By now, This PR is not going to be merged due to be outside the actual scope of Tasmota. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

**Comment by Zuikkis** [comment]
I'd like to disagree on this decision.

Tasmota already has many "unnecessary" extensions, like tons of different sensors which are not useful for most people. But it's great to have them in case you need them! They can be enabled and disabled in the config when building, when disabled they don't take up space.

IR_HVAC is default disabled in my_user_config.h, so adding Midea does not take any space.

RAW IR send/receive does not really help for air conditioners, because generally they always have huge IR data packets which cannot be received (or sent?) unless you recompile Tasmota with increased buffer sizes, as explained by many users in #2116..

I have this Wifi IR blaster:
https://github.com/arendst/Sonoff-Tasmota/wiki/YTF-Wifi-Smart-IR---Tuya-Universal-Smart-IR-Hub---TYWE3S-module

Recent Tasmota supports it. With such device it would be great to have a Tasmota firmware that supports as wide range of IR devices as possible, but really is no need to have sensor support etc..

So just let users build what they want. :)

I modified the Midea commit to fit current development branch, and it seems to work nicely. Thanks @lvta0909 !

**Comment by no-Legend** [comment]
@Zuikkis 
I own two mobile hvac's from media (in Germany the company sell as comfee or koenic)
I tried to use the raw command, but I was not able to get the device controlled.
Raw was not working in any kind I tried it.

Is there a way to integrate the midea code in the latest master?

**Comment by arendst** [comment]
Working on it now.

**Comment by arendst** [comment]
Done

**Comment by no-Legend** [comment]
@arendst 
I tested now the protocol for midea. Works good for my midea (comfee,koenic) hvac.

**Pull request closed without merging**
