### PR TITLE
SDM220 Support

### PR DESCRIPTION
**Pull request by Dees7**
SDM220 works as SDM120 too cause SDM220 is almost SDM120 with additional
parameters:

* Phase angle
* Import Active Power
* Export Active Power
* Import Reactive Power
* Export Reactive Power
* Total Reactive Power

### CODE REVIEW

**Comment by Dees7** [comment]
I have SDM220 and patch every update. Please add SDM220. 

Or
SDM120 can work as SDM220 but some parameters returned as 0. Might be unite SDM120\SDM220 as single device?

**Comment by arendst** [comment]
I prefer to unite SDM120 and SDM220 in one file: SDM120.

**Comment by ascillato** [comment]
@Dees7 

Hi,

Please, can you update your PR to the last version of Tasmota? Thanks

**Comment by ascillato** [comment]
Hi @ccfiel

As the previous comments on this thread, Theo has asked to modify this PR to add SDM220 support to the actual SDM120 driver so as to not duplicate routines and code. Remember that ESP8266 flash and memory is limited so all optimizations as to be taken into account.
This PR is open until this modification got addressed. Thanks

**Comment by Dees7** [comment]
@ascillato the first PR was with SDM220 and SDM120 as different files. Now I unite them into one and selecting SDM220 with #USE_SDM220. 
What wrong in my code? what should I do?

**Review by ascillato — APPROVED** [review]

**Comment by ascillato** [comment]
@Dees7 Looks great. Thanks.

@arendst, what do you think?

**Comment by localhost61** [comment]
Hi,
- As SDM120, SDM220, SDM230 are sharing the same device entries  `#75 & #76`, a mean should be provided to toggle the `Use_SDM220` option in order to fallback to SDM120 when using the same firmware in a mixed environment with SDM120 and SDM220 devices. A new Setoption ?

tasmota 6 3 0 17 - sdm230

- I the translation process I tried to use abbreviated words in order to keep under 24 chars and I faced a weird bug : ***dots were replaced with commas*** however that's strings, not float numbers !!! 
**In fr-FR.h** => 
```
#define D_IMPORT_ACTIVE   "Puiss. act conso"
#define D_EXPORT_ACTIVE   "Puiss act fournie"
#define D_IMPORT_REACTIVE "Puiss réa conso."
```
  **In the device webpage** =>
tasmota 6 3 0 17 - dots
=> same result when compiled with core 2.3.0 or STAGE
=> same display in Firefox on windows or android (I have nothing but Firefox :-)
=> same result if I switch my android phone language to English in preferences

**Pull request merged**
