### PR TITLE
CO2 MH-Zxx

### PR DESCRIPTION
**Pull request by bashlikova**
add CO2 MH-Zxx sensor support

### CODE REVIEW

**Comment by servim** [comment]
I support! This sensor is not enough.

**Comment by Shmigger** [comment]
I look forward to these changes, too!

**Comment by servim** [comment]
Tell me, I can not understand if this sensor will be supported or not. I understand English very poorly and I am not familiar with the work of the gitkhab. [Here](https://github.com/arendst/Sonoff-Tasmota/pull/1248/files) I see that they did support, but there is no firmware in it, why?
Thank you!

**Comment by Shmigger** [comment]
@servim what kind of Sonoff device do you use?

**Comment by servim** [comment]
with CO2 sensor I want to use Wemos D1 mini

**Comment by bashlikova** [comment]
>>but there is no firmware in it, why?
You can find firmware (bin) in fork repository.
https://github.com/bashlikova/Sonoff-Tasmota/tree/development/bin

MH-Zxx sensor uses UART connection (Rx, Tx, GND) and need +5 Vcc

In configuration select sensor for GPIO 1 (Tx) or GPIO 3 (Rx) - there is no difference

image

image

**Comment by servim** [comment]
thanks It works!
I have a temperature too 63 * C, a suspicious resemblance :)

**Comment by Shmigger** [comment]
@servim What kind of CO2 sensor do you use?

**Comment by arendst** [comment]
I'm working on a supported implementation but have to wait for my MH-Z19 to arrive so hold on...

**Comment by Shmigger** [comment]
@arendst Active woking on CO2 support is the best way to transfer this to main brach of Tasmota :)

**Comment by servim** [comment]
> What kind of CO2 sensor do you use?
MH-Z19

**Comment by arendst** [comment]
Just released MH-Z19(B) support. Currently only supported on hardware serial interface due to lack of iram.

Please test and let me know your results.

image

image

**Comment by bashlikova** [comment]
It doesn't work with my MH-Z14
image
image

**Comment by servim** [comment]
Thank you, MH-Z19 is working! The temperature is like the real one.
MH-Z14 I have removed, how to get to it, I'll try, I'll tell!
PS IMHO the temperature can not be processed, I think it has an error, because the sensor in the interior of the housing is located and is most likely used to adjust the readings of co2 (saving memory)
PPS I have another CO2 sensor, 
download

the results are very different 100-150 ppm, I'll observe.

**Comment by bashlikova** [comment]
>>PPS: I have another CO2 sensor,
>>the results are very different 100-150 ppm, I'll observe.

Yes, I compare with the same sensor.
MH-Z usually gives values ​​of 100-200 lower. And MHZ is faster.

**Comment by ionciubotaru** [comment]
Adding MH-Z19 to Tasmota is a great improvement. There is also BME680 - it will be nice to add it -https://github.com/arendst/Sonoff-Tasmota/issues/1212

**Comment by arendst** [comment]
The current SoftwareSerial library uses too much iram and causes compilation to fail.

I just released a patched version of the SoftwareSerialNoIram library to be used with a second version of the MH-Z19(B) driver.

@servim Can you please verify if this combinations also works for the MH-Z19 allowing to select more different GPIOs.

**Comment by servim** [comment]
My English is very bad, I can not tell, watch the video.
https://youtu.be/TgDa1yJjDe0

**Comment by arendst** [comment]
Ah. Thnx. That makes sense. It happens because the interrupts have to be services by rom instead of iram and that takes time to service leading to missed interrupts.

I have to reconsider how to fix or conceal this.

**Comment by servim** [comment]
OK! I am ready to check at any time. I have mh-z14, but it is far away when I'm there, I can also check it.

**Comment by arendst** [comment]
Just a remark. Did you try on different GPIOs than the default hardware serial GPIOs? If not than your video is expected as  the hardware serial interferes with the software serial.

In that case please select different GPIOs and do not use GPIO1 and GPIO3:

image

**Comment by servim** [comment]
the video shows that I used gpio4 and gpio5 - (look at  1:05)

**Comment by servim** [comment]
flooded the firmware in mh-z14, there is no result :(

**Comment by arendst** [comment]
Made some changes to allow Standard SoftwareSerial test.

Pls try to test again with the following changes in user_config.h:
```
//#define USE_WS2812                               // WS2812 Led string using library NeoPixelBus (+5k code, +1k mem) - Disable by //
  #define USE_WS2812_CTYPE     1                 // WS2812 Color type (0 - RGB, 1 - GRB, 2 - RGBW, 3 - GRBW)
//  #define USE_WS2812_DMA                         // DMA supports only GPIO03 (= Serial RXD) (+1k mem). When USE_WS2812_DMA is enabled expect Exceptions on Pow

//#define USE_MHZ19                                // Add support for MH-Z19 CO2 sensor using hardware serial interface at 9600 bps (+1k1 code)
#define USE_MHZ19_SOFT_SERIAL                    // Add support for MH-Z19 CO2 sensor using iram free software serial interface at 9600 bps (+2k3 code)
//  #define USE_SERIAL_NO_ICACHE                   // Use no iram with SoftwareSerial (may loose characters)
```
This disables WS2812 which uses a lot of iram and enables MHZ19 with standard SoftwareSerial support using iram. This should now not drop characters and therefore loose values. 

Try again with GPIO4 and GPIO5.

**Comment by servim** [comment]
`
#define USE_IR_REMOTE                            // Send IR remote commands using library IRremoteESP8266 and ArduinoJson (+4k code, 0k3 mem)
//  #define USE_IR_HVAC                            // Support for HVAC system using IR (+2k code)
  #define USE_IR_RECEIVE                         // Support for IR receiver (+5k5 code)

//#define USE_WS2812                               // WS2812 Led string using library NeoPixelBus (+5k code, +1k mem) - Disable by //
  #define USE_WS2812_CTYPE     1                 // WS2812 Color type (0 - RGB, 1 - GRB, 2 - RGBW, 3 - GRBW)
//  #define USE_WS2812_DMA                         // DMA supports only GPIO03 (= Serial RXD) (+1k mem). When USE_WS2812_DMA is enabled expect Exceptions on Pow

//#define USE_MHZ19                                // Add support for MH-Z19 CO2 sensor using hardware serial interface at 9600 bps (+1k1 code)
#define USE_MHZ19_SOFT_SERIAL                    // Add support for MH-Z19 CO2 sensor using iram free software serial interface at 9600 bps (+2k3 code)
//  #define USE_SERIAL_NO_ICACHE                   // Use no iram with SoftwareSerial (may loose characters)

#define USE_ARILUX_RF                            // Add support for Arilux RF remote controller (+0k8 code)
`

`
Archiving built core (caching) in: C:\Users\sysadmin\AppData\Local\Temp\arduino_cache_623740\core\core_esp8266_esp8266_d1_mini_CpuFrequency_80,UploadSpeed_921600,FlashSize_4M1M_c90777c1f9e74f3d9082b972a2efb6fa.a
c:/arduino/arduino-sonoff/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\sysadmin\AppData\Local\Temp\arduino_build_682099/sonoff.ino.elf section `.text' will not fit in region `iram1_0_seg'

collect2.exe: error: ld returned 1 exit status

Several libraries have been found for "SoftwareSerial.h"
 Used: C:\arduino\arduino-sonoff\portable\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial
Not used: C:\arduino\arduino-sonoff\portable\sketchbook\libraries\EspSoftwareSerial-3.3.1
exit status 1
Compilation error for the board WeMos D1 R2 & mini.
`
`
//#define USE_IR_REMOTE                            // Send IR remote commands using library IRremoteESP8266 and ArduinoJson (+4k code, 0k3 mem)
//  #define USE_IR_HVAC                            // Support for HVAC system using IR (+2k code)
//  #define USE_IR_RECEIVE                         // Support for IR receiver (+5k5 code)

//#define USE_WS2812                               // WS2812 Led string using library NeoPixelBus (+5k code, +1k mem) - Disable by //
  #define USE_WS2812_CTYPE     1                 // WS2812 Color type (0 - RGB, 1 - GRB, 2 - RGBW, 3 - GRBW)
//  #define USE_WS2812_DMA                         // DMA supports only GPIO03 (= Serial RXD) (+1k mem). When USE_WS2812_DMA is enabled expect Exceptions on Pow

//#define USE_MHZ19                                // Add support for MH-Z19 CO2 sensor using hardware serial interface at 9600 bps (+1k1 code)
#define USE_MHZ19_SOFT_SERIAL                    // Add support for MH-Z19 CO2 sensor using iram free software serial interface at 9600 bps (+2k3 code)
//  #define USE_SERIAL_NO_ICACHE                   // Use no iram with SoftwareSerial (may loose characters)

#define USE_ARILUX_RF                            // Add support for Arilux RF remote controller (+0k8 code)
`
`
Archiving built core (caching) in: C:\Users\sysadmin\AppData\Local\Temp\arduino_cache_623740\core\core_esp8266_esp8266_d1_mini_CpuFrequency_80,UploadSpeed_921600,FlashSize_4M1M_c90777c1f9e74f3d9082b972a2efb6fa.a
The sketch uses 473872 byte (45%) device memory. Total Available 1044464 байт.
Global variables use 45336 байт (55%) dynamic memory, leaving 36584 bytes for local variables. Maximum: 81920 байт.
Uploading 478016 bytes from C:\Users\sysadmin\AppData\Local\Temp\arduino_build_682099/sonoff.ino.bin to flash at 0x00000000
................................................................................ [ 17% ]
................................................................................ [ 34% ]
................................................................................ [ 51% ]
................................................................................ [ 68% ]
................................................................................ [ 85% ]
...................................................................              [ 100% ]
`

**Comment by arendst** [comment]
I don't know if MH-Z14 works. I'll have to look into the protocol.

**Comment by bashlikova** [comment]
it works now with MH-Z14! Great work!
image


#define USE_MHZ19                                // Add support for MH-Z19 CO2 sensor using hardware serial interface at 9600 bps (+1k1 code)
//#define USE_MHZ19_SOFT_SERIAL                    // Add support for MH-Z19 CO2 sensor using iram free software serial interface at 9600 bps (+2k3 code)

**Pull request closed without merging**
