### PR TITLE
AS3935 update DE-language

### PR DESCRIPTION
**Pull request by device111**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@device111  added a PR to this PR 
Changend flackerd to flackert

**Comment by device111** [comment]
It's Bavarian German.. :-)
Added to PR.
Thx @Jason2866

**Comment by Jason2866** [comment]
I know i am from Bavaria too. Near Ingolstadt

**Comment by device111** [comment]
then we have the same dialect. 👍  
I'm from DEG.
Thx and best regards.

**Pull request merged**
