### PR TITLE
Feature: Adafruit SSD1331 Display support

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
## Description:
Support for the [SSD1331](https://www.aliexpress.com/item/32790785282.html) SPI 94\*64 Full Color OLED Display.
I have used **DisplayModel 14**.
Based on [release 1.2.0 of the Adafruit library](https://github.com/adafruit/Adafruit-SSD1331-OLED-Driver-Library-for-Arduino/releases/tag/1.2.0).
Inspired by @gemu2015's xdsp_09_SSD1351 driver.
Both software and hardware SPI work. For hardware SPI the OLED Reset is optional.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4 => works but was only able to use SSPI on ESP32.
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by jeroenvermeulen** [comment]
TODO:
- [ ] Make text smaller in DisplayMode 1-5
- [ ] Test on ESP32

**Comment by jeroenvermeulen** [comment]
### Test/usage information:

**ESP8266 Pins**
Work both for hardware and software SPI. Tested on ESP-12E + Wemos D1 mini
```
D4 GPIO5  = SPI DC     (DC pin)
D7 GPIO13 = SPI MOSI   (SDA pin)
D5 GPIO14 = SPI CLK    (SCL pin)
D8 GPIO15 = SPI CS     (CS pin)
D3 GPIO0  = OLED Reset (RES pin)
```
**Set Module + GPIOs**
```
Module 18;
// Software SPI:
BackLog  Gpio0 1024; Gpio1 0; Gpio2 960; Gpio3 0; Gpio4 0; Gpio5 0; Gpio12 0; Gpio13 864; Gpio14 896; Gpio15 928; Gpio16 0; Gpio17 0;
// Hardware SPI with Reset:
BackLog  Gpio0 1024; Gpio1 0; Gpio2 800; Gpio3 0; Gpio4 0; Gpio5 0; Gpio9 0; Gpio10 0; Gpio12 672; Gpio13 704; Gpio14 736; Gpio15 768; Gpio16 0; Gpio17 0;
// Hardware SPI without Reset:
BackLog  Gpio0 0; Gpio1 0; Gpio2 800; Gpio3 0; Gpio4 0; Gpio5 0; Gpio9 0; Gpio10 0; Gpio12 672; Gpio13 704; Gpio14 736; Gpio15 768; Gpio16 0; Gpio17 0;
```
**Configure Display**
```
Backlog  DisplayModel 14; DisplayRotate 0; DisplayDimmer 100; DisplayWidth 96; DisplayHeight 64; DisplayCols 16; DisplayRows 8;
```
**Draw rectangular and coloured text**
```
DisplayMode 0;
Backlog  Rule1 ON System#Boot DO DisplayText [zf1s1C65535r96:64C63488x15y9] Tasmota [f0s1C31x2y27] 0.95" SSD1331 [x2y37] 96 x 64 px [x2y47] 4SPI+Reset ENDON; Rule1 ON; Restart 1;
```

**Comment by arendst** [comment]
Thx.

I'm currently redesigning SPI CS addressing so this is on hold until released soon.

**Comment by arendst** [comment]
Merged driver fails compilation:
```
C:/Users/Theo/GDrive/Work/VisualStudio/Tasmota/dev/gd-dev-v9.2.0/tasmota/xdsp_14_SSD1331_2.ino: In function 'void SSD1331_InitDriver()':
C:/Users/Theo/GDrive/Work/VisualStudio/Tasmota/dev/gd-dev-v9.2.0/tasmota/xdsp_14_SSD1331_2.ino:75:14: error: cannot convert 'Adafruit_SSD1331*' to 'Renderer*' in assignment
     renderer = ssd1331;
              ^
```
I think you'll have to revisit the use of GEMU renderer instead of the Adafruit renderer as it also takes up too much flash code space.

BTW, your driver has been thoroughly changed to adhere to the latest Tasmota SPI configuration. It now needs dedicated CS and DC. 

See new code.

**Comment by jeroenvermeulen** [comment]
Currently it seems to be broken in `development`, I will investigate.

**Comment by jeroenvermeulen** [comment]
@arendst 
> Merged driver fails compilation
Solved with PR #10376
> I think you'll have to revisit the use of GEMU renderer instead of the Adafruit renderer as it also takes up too much flash code space.
Well in fact GEMU's renderer [extends the Adafruit renderer](https://github.com/arendst/Tasmota/blob/development/lib/lib_display/esp-epaper-29-ws-20171230-gemu-1.1/src/renderer.h#L18).
Enabling `USE_DISPLAY_SSD1331` eats 5.3K flash.

**Pull request merged**
