### PR TITLE
Display drivers

### PR DESCRIPTION
**Pull request by gemu2015**
updating oled epaper pull request didn't work well, so here is a new pr

here is an updated pull request for my display drivers

after all i can say i like the E-Papers most. perfectly readable , low power consumption easy hardware interface.
the ILI9488 is a nice display which has the opportunity to use touch buttons but =>
display must be switched off (the data sheet mentions burn effects when turned on constantly)
viewing angle is bad when using dimmed colors.  full color icons are not viewable with slight angles.
hardware interface is not for beginners. 
the OLEDs are also nice displays (especially the larger ones 1,3 inch above) but they may also burn in when turned on constantly.

updated interface doku
[DisplayText.docx](https://github.com/arendst/Sonoff-Tasmota/files/2365181/DisplayText.docx)

ILI 9488 display
ili9488

updated pull request 
===============

files changed =>
Libraries
=========
Adafruit_SH1106-master
Adafruit_SSD1306-1.1.2
esp-epaper-29-ws-20171230-gemu-1.0
FT6236
ILI9488-master

display interfaces
==================
xdrv_13_display.ino
xdsp_02_ssd1306.ino
xdsp_05_epaper_29.ino
xdsp_06_epaper_42.ino
xdsp_07_sh1106.ino
xdsp_08_ILI9488.ino

// gpio definitions
sonoff_template.h
support.ino

// defines used =>
===========
#define USE_DISPLAY

#define USE_DISPLAY_LCD
#define USE_DISPLAY_SSD1306
#define USE_DISPLAY_MATRIX
#define USE_DISPLAY_ILI9341
#define USE_DISPLAY_EPAPER29
#define USE_DISPLAY_EPAPER42
#define USE_DISPLAY_SH1106
#define USE_DISPLAY_ILI9488

// needed for E-Paper and ILI9488
// hard spi used, when hard pins are defined
#define USE_SOFTSPI  (define USE_SPI is also needed)

// show init message on display
#define SHOW_SPLASH

// use touch buttons on ILI9488
#define USE_TOUCH_BUTTONS

// use epd font together with classic GFX fonts
#define USE_EPD_FONTS

// use GFX font together with classic GFX fonts
#define USE_GFX_FONTS

// use line graph 
#define USE_GRAPH

// use analog watch
#define USE_AWATCH

### CODE REVIEW

**Comment by arendst** [comment]
Great.

I will download and investigate your branch before merging as it is a lot.

**Comment by Jason2866** [comment]
Hello @gemu2015 
I get this errors when compiling your latest display fork:
Compiling .pioenvs\sonoff\lib965\esp-epaper-29-ws-20171230-gemu-1.0\epdif.cpp.o
ADrchiving .pioenvs\sonoff\lib926\libAdafruit-GFX-Library-1.2.9.a:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino: In function 'void LcdInit(uint8_t)':

D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:48:32: error: 'DisplayClearScreenBuffer' was not declared in this scope
DisplayClearScreenBuffer();
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino: In function 'void LcdInitDriver()':
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:74:30: error: 'DisplayAllocScreenBuffer' was not declared in this scope
DisplayAllocScreenBuffer();
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino: In function 'boolean LcdPrintLog()':
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:122:10: error: 'disp_screen_buffer_cols' was not declared in this scope
if (!disp_screen_buffer_cols) { DisplayAllocScreenBuffer(); }
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:122:62: error: 'DisplayAllocScreenBuffer' was not declared in this scope
if (!disp_screen_buffer_cols) { DisplayAllocScreenBuffer(); }
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:124:40: error: 'DisplayLogBuffer' was not declared in this scope
char* txt = DisplayLogBuffer('\337');
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:129:17: error: 'disp_screen_buffer' was not declared in this scope
strlcpy(disp_screen_buffer[i], disp_screen_buffer[i +1], disp_screen_buffer_cols);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:129:66: error: 'disp_screen_buffer_cols' was not declared in this scope
strlcpy(disp_screen_buffer[i], disp_screen_buffer[i +1], disp_screen_buffer_cols);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:133:15: error: 'disp_screen_buffer' was not declared in this scope
Compiling .pioenvs\sonoff\lib965\esp-epaper-29-ws-20171230-gemu-1.0\epdpaint.cpp.ostrlcpy(disp_screen_buffer[last_row], txt, disp_screen_buffer_cols);

^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:133:50: error: 'disp_screen_buffer_cols' was not declared in this scope
strlcpy(disp_screen_buffer[last_row], txt, disp_screen_buffer_cols);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_01_lcd.ino:134:33: error: 'DisplayFillScreen' was not declared in this scope
DisplayFillScreen(last_row);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_02_ssd1306.ino: In function 'void SSD1306PrintLogLine()':
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_02_ssd1306.ino:102:13: error: 'oled_screen_buffer' was not declared in this scope
strlcpy(oled_screen_buffer[i], oled_screen_buffer[i +1], sizeof(oled_screen_buffer[i]));
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_02_ssd1306.ino:110:11: error: 'oled_screen_buffer' was not declared in this scope
strlcpy(oled_screen_buffer[last_row], disp_log_buffer[disp_log_buffer_ptr], sizeof(oled_screen_buffer[last_row]));
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_03_matrix.ino: In function 'void MatrixPrintLog(uint8_t)':
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_03_matrix.ino:237:52: error: 'DisplayLogBuffer' was not declared in this scope
char* txt = (!mtx_done) ? DisplayLogBuffer('\370') : mtx_buffer;
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_03_matrix.ino:244:27: error: 'disp_log_buffer_cols' was not declared in this scope
uint8_t max_cols = (disp_log_buffer_cols < MTX_MAX_SCREEN_BUFFER) ? disp_log_buffer_cols : MTX_MAX_SCREEN_BUFFER;
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino: In function 'void Ili9341Init(uint8_t)':
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:70:34: error: 'DisplayClearScreenBuffer' was not declared in this scope
DisplayClearScreenBuffer();
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino: In function 'void Ili9341InitDriver()':
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:92:32: error: 'DisplayAllocScreenBuffer' was not declared in this scope
DisplayAllocScreenBuffer();
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino: In function 'void Ili9341PrintLog()':
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:146:12: error: 'disp_screen_buffer_cols' was not declared in this scope
if (!disp_screen_buffer_cols) { DisplayAllocScreenBuffer(); }
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:146:64: error: 'DisplayAllocScreenBuffer' was not declared in this scope
if (!disp_screen_buffer_cols) { DisplayAllocScreenBuffer(); }
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:149:40: error: 'DisplayLogBuffer' was not declared in this scope
char* txt = DisplayLogBuffer('\370');
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:171:19: error: 'disp_screen_buffer' was not declared in this scope
strlcpy(disp_screen_buffer[i], disp_screen_buffer[i +1], disp_screen_buffer_cols);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:171:68: error: 'disp_screen_buffer_cols' was not declared in this scope
strlcpy(disp_screen_buffer[i], disp_screen_buffer[i +1], disp_screen_buffer_cols);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:177:17: error: 'disp_screen_buffer' was not declared in this scope
strlcpy(disp_screen_buffer[last_row], txt, disp_screen_buffer_cols);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:177:52: error: 'disp_screen_buffer_cols' was not declared in this scope
strlcpy(disp_screen_buffer[last_row], txt, disp_screen_buffer_cols);
^
D:/Sonoff-Tasmota-display-GEMU_Sept/sonoff/xdsp_04_ili9341.ino:178:35: error: 'DisplayFillScreen' was not declared in this
scope
DisplayFillScreen(last_row);
^
Compiling .pioenvs\sonoff\lib965\esp-epaper-29-ws-20171230-gemu-1.0\font12.c.o
Compiling .pioenvs\sonoff\lib965\esp-epaper-29-ws-20171230-gemu-1.0\font16.c.o
Compiling .pioenvs\sonoff\lib965\esp-epaper-29-ws-20171230-gemu-1.0\font20.c.o
Compiling .pioenvs\sonoff\lib965\esp-epaper-29-ws-20171230-gemu-1.0\font24.c.o
Compiling .pioenvs\sonoff\lib965\esp-epaper-29-ws-20171230-gemu-1.0\font8.c.o
*** [.pioenvs\sonoff\src\sonoff.ino.cpp.o] Error 1

**Comment by Jason2866** [comment]
Hello @gemu2015 
when i #undef  USE_PZEM004T compile fails.

**Comment by gemu2015** [comment]
hi @Jason2866

#undef USE_PZEM004T
does compile well in my setup !

**Comment by Jason2866** [comment]
Weird.... Maybe Laptop needs reboot ;-)
Thx for looking again!  
It's getting awkward for me

**Comment by mike2nl** [comment]
@gemu2015 
Some news from you side about the whole gemu display driver world?

**Comment by Jason2866** [comment]
No, not in release version. You have to use dev version

**Comment by GianCann** [comment]
> Hi guys, I'm confused, is the OLED display model SSD1306 available for usage in the current stable version of Tasmota v6.3?

I've tested OLED Display SSD1306 with 6.3.0.16 version and work 'better' (not all command i've tested).
Have you uncommented  the line _/ #define USE_DISPLAY_  in this file?
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/my_user_config.h

**Comment by demian85** [comment]
> > Hi guys, I'm confused, is the OLED display model SSD1306 available for usage in the current stable version of Tasmota v6.3?
> 
> I've tested OLED Display SSD1306 with 6.3.0.16 version and work 'better' (not all command i've tested).
> Have you uncommented the line _/ #define USE_DISPLAY_ in this file?
> https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/my_user_config.h

Yes, I've uncommented that line and the one that identifies the display model 2, that's the one I have.
Maybe the commands for display initializing are not clear. How can I check if the display is being detected? Or... dead?
Thanks.

**Comment by mike2nl** [comment]
@arendst @Jason2866 
I don't know what is exatcly now merged into tasmota from gemu's source.

I ask about to display the time: Displaytext [z] [s1x0y0t]
Also the catila T letter don't show the date.

When time is shown on the display via cosnole command 
the last number is still missing. E.g. 11:33 is 11:3

**Comment by arendst** [comment]
@mike the time is in error indeed. Will fix it soon. 

Let's keep this one open as PR and report issues as an issue.

BTW to find out what commands are support in Tasmota look through the xdrv_13_display.ino file between lines 311 thru 456

**Comment by arendst** [comment]
@mike try the latest dev release; t fixed and T added

**Comment by mike2nl** [comment]
@arendst 
will check it and report back. Thanks for have your hand on it!

**Comment by qingz2004** [comment]
When can we see the it's merged? I need the display driver SH1106.
Thanks!

**Comment by claybar** [comment]
+1 I would also love to see this merged to allow the use of a SH1106 display

**Comment by gemu2015** [comment]
2 new color displays added

SS1351  128x128 OLED Display  => https://www.ebay.de/itm/1-5-128x128-OLED-Display-Modul-RGB-SPI-Interface-Arduino-Raspberry-Pi/123256209315?hash=item1cb2a47fa3:g:WtsAAOSwZb5bTfjF

RA8876 1024x600 COLOR TFT with hardware acceleration  => https://www.buydisplay.com/default/spi-7-inch-tft-lcd-dislay-module-1024x600-ra8876-optl-touch-screen-panel

**Comment by bronzeblood** [comment]
> +1 I would also love to see this merged to allow the use of a SH1106 display

**Comment by gemu2015** [comment]
for those who want to test my display branch i made a new branch (display1) from the current Tasmota development with all display drivers included (and newest adaption to display.ino from arends)
=>https://github.com/gemu2015/Sonoff-Tasmota/tree/display1

files modified against current development branch:

in sonoff
xdrv_13_display.ino (modified to support new renderer class AND recent method for "older" unmodified drivers like ili9341)
xdsp_02_ssd1306.ino
xdsp_05_epaper_29.ino
xdsp_06_epaper_42.ino
xdsp_07_sh1106.ino
xdsp_08_ILI9488.ino
xdsp_09_SSD1351.ino
xdsp_10_RA8876.ino

in lib
lib/Adafruit-GFX-Library-1.5.6 (original lib, only some class members declared virtual for subclassing)
lib/esp-epaper-29-ws-20171230-gemu-1.1 (support for epaper 2.9 and 4.2 inch and renderer class)
lib/Adafruit_SSD1306-1.3.0 (modified for subclass of renderer)
lib/Adafruit_SH1106 (modified for subclass of renderer)
lib/FT6236  (touch screen i2c lib for ili9488 and ra9976)
lib/ILI9488  (ili9488 driver optimized for 3 wire hardware spi)
lib/SSD1351  (sad1351 driver optimized for 3 wire hardware spi)
lib/RA8876  (ra8876 driver for standard 4 wire hardware spi)

DisplayText.md doku

**Comment by Beno283** [comment]
@gemu2015 is it possible to add the Adafruit 3.5" TFT featherwing [https://learn.adafruit.com/adafruit-3-5-tft-featherwing/overview](url) to this branch? I attempted to do it, but was unsuccessful when compiling your branch and new to all this.

**Comment by gemu2015** [comment]
@Beno283 
no i will not add any more drivers. i only add displays i use myself.
you may use any display i already implemented.
the ILI9488 is a 3.5 inch TFT display (480x320) with capacitive touch screen 
(about 20 euros at buy display.com)
https://www.buydisplay.com/default/lcd-3-5-inch-320x480-tft-display-module-optl-touch-screen-w-breakout-board
i may help in getting it running.
 
this branch is anyhow outdated. use my actual universal7 branch it is up to date with tasmota dev.

**Comment by meingraham** [comment]
@gemu2015 

`use my actual universal7 branch` is this a driver in Tasmota? I could not find a fork by that project name.

Cheers!

Mike

**Comment by gemu2015** [comment]
@meingraham 
hi mike,
here is the link =>https://github.com/gemu2015/Sonoff-Tasmota
greetings Gerhard

**Comment by Beno283** [comment]
> @Beno283
> no i will not add any more drivers. i only add displays i use myself.
> you may use any display i already implemented.
> the ILI9488 is a 3.5 inch TFT display (480x320) with capacitive touch screen
> (about 20 euros at buy display.com)
> https://www.buydisplay.com/default/lcd-3-5-inch-320x480-tft-display-module-optl-touch-screen-w-breakout-board
> i may help in getting it running.
> 
> this branch is anyhow outdated. use my actual universal7 branch it is up to date with tasmota dev.

No worries, I have tried using the ILI9488 but still learning the program and processes. I'll let you know how I go.

**Comment by meingraham** [comment]
Thanks Gerhard.

Just curious - besides some of the lights driver updates you have developed, are there any other features? What's the reason for not creating a PR to incorporate these into Theo development branch?

Cheers!

Mike

**Comment by demian85** [comment]
Hi guys. Is there a way to interact with any of those LCD touch screen
displays? Or is this just meant to display text?

**Comment by gemu2015** [comment]
@meingraham 
Hi mike,
a.the display drivers are completely stable and could be easily merged. its up to Theo
b.the sendmail option is also nice but only works currently with 2.42
c.the rdm6300 driver is ready for pr
d.the sml/obis driver is also completely stable and a lot of german users use it.
since it is now configurable easily it could also be merged.
it simple samples serial streams for patterns and then excerpts the data from the stream
it is capable of collecting serial data from several software serial streams with a modified serial driver that does not wait during IRQ.
and it collects water and gas meters all in one driver
so some users collect 3 serial energy meters + gas + water with one esp driver.
e.the ibeacon driver is also ready for pr. it monitors through passive scan the activity of ibeacons or beacon key fobs, could be used for presence monitoring. the key fobs can be made beeping through MQTT cmd.
f. the lora driver is currently only for EQ3 Max and there is some work to doo.
g. the e-bus driver works stable but is only interesting for very few users of wolf heaters.

you may vote if i shall pr any of these.

some other drivers aren't stable currently and i don't find it worth to search the reason.

@demian85 
yes the ILI9488 and the RA8876 have a capacitive touch screen and you can create virtual buttons (toggle or push) to interact with.
either they may simply toggle a defined relay or they may be queried in a script.

greetings Gerhard

**Comment by meingraham** [comment]
My vote is PR anything that is stable and of common interested (everything you develop :wink:). If there is concern about the code size of these new features, then associate them with `#define USE_xxx` compiler directives and have them undefined by default. Of course, Theo can decide if they should be defined by default.

Have you tried b with 2.6-Pre? If that works, I'm sensing 2.6 will be the default Tasmota core soon after it is released on September 2.

So, my vote: PR these five:
a, c, d, e (undefined but up to Theo)
g (undefined by default)

Mike

P.S. @arendst

**Comment by ascillato** [comment]
I also vote the same as @meingraham

**Comment by claybar** [comment]
@gemu2015 

> this branch is anyhow outdated. use my actual universal7 branch it is up to date with tasmota dev.

So should this PR be made to use `universal7` rather than `displays`?  Or perhaps a new PR?

**Comment by gemu2015** [comment]
@claybar 
redirecting an active branch doesn't seem possible. updating also had many issues for me. i probably will do a new pr.

**Comment by gemu2015** [comment]
hi mike,
in the spreadsheet the latest driver 53 sml is missing 
(support for serial inputs from various sources, home power meters, heaters, heat pumps
and gpio inputs from reed contacts etc, similar to Tasmota counters)

in the supported sensors wiki there are many sensors missing
e.g. sensor 52 iBeacon, needs some explanation.

at least all sensors that use cmds or need special handling should have an entry.

the builds table is also not up to date

however  i have no knowledge how to edit these tables and entries. certainly i am willing to add the info of my drivers when appropriate 

also a cookbook and kind of library for the meter descriptors may be needed. i already have some text but we need an extra entry in the wiki.

Cheers
Gerhard

**Comment by gemu2015** [comment]
@meingraham 
the meter driver is live already (SML)
probably we should add the descriptor advice and examples in the sensor drivers link

Gerhard

**Comment by meingraham** [comment]
I split the page and created a page for the meter descriptors. I'll work on the smart meter "home" page later.

**Pull request closed without merging**
