### PR TITLE
Add support for BL0942 to xnrg_14_bl09xx.ino

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

Following https://github.com/arendst/Tasmota/discussions/13190

Added support for BL0942 to `xnrg_14_bl09xx.ino"
Similar serial protocol but 23 bytes instead of 36. Requires a different paring function.
Refactor of the initialization code (write to device) in order to properly calculate checksum depending on chip address.

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.1.0.7.4
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx. Will test asap.

I feel a lot of code size optimization using arrays coming along shortly... (change models to 0,1 and 2 and use as index for fixed values).

**Comment by arendst** [comment]
Merged and noticed broken BL0940 support on Blitzwolf SHP10.

Reverted the main file and I will investigate what went wrong here.

**Comment by arendst** [comment]
Ah. I love this message:

``BL9: Checksum failurereceived 0x63 instead of 0x63``

Will try to solve it now.

**Comment by arendst** [comment]
Fixed and released

**Comment by barbudor** [comment]
Thanks @arendst 
I missed that

**Pull request merged**
