### PR TITLE
Scripter update

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

some bug fixes,
some reformatting
google charts new options
text variable replacement new option calculate formulas %(formula)%
fix display touch init
save memory on esp32 mp3 player with psram

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by MomentumV** [comment]
Gemu, In the script docs, there's a typo for the google chart spline option; it reads 2f2 instead of lf2.
`- l2=linechart with exactly 2 lines and 2 y scales (must be given at end)
- 2f2 like above but with splined lines`
from https://tasmota.github.io/docs/Scripting-Language/

**Comment by gemu2015** [comment]
thanks, fixed

**Comment by MomentumV** [comment]
I also cannot figure out what this line means:
`("cntN" starts numbering entries with the number N an optional /X generates only an devides by X range)`

**Comment by MomentumV** [comment]
After an evening trying things, I think this could be accurate:
`Using the label string "cntN" will produce labels that cycle through the array indexes, starting with the number N.`
`For instance, "cnt6" with an array of length 8 will produce the labels 6|7|0|1|2|3|4|5|
`Using "cntN/X" will then divide the numeric value of the label, so "cnt6/2" with an array of length 8 will produce the labels 3|3|0|0|1|1|2|2|`

**Comment by gemu2015** [comment]
Yes this is accurate. The reason why you may need it is the following example.
lets say you want to have a value every hour. You have an array of 24 elements.
"cnt0" gives an x axis of 0-23 hours.
now you want to have more time resolution and have values every 15 Minutes.
you need an array of 96 Elements.
"cnt0/4" now gives an accurate axis of hours.
i know the documentation is preliminary. you are welcome to help by submitting pr´s to the Tasmota doc page.
i myself have a lot of examples i use in my devices. these are very specific to my needs and in german.
they show however what is possible. if i find the time i will translate and post some of them

**Pull request merged**
