### PR TITLE
Python pio updates

### PR DESCRIPTION
**Pull request by sillyfrog**
## Description:

Further to the discussion at the end of https://github.com/arendst/Tasmota/issues/12837 this PR refactors some of the PIO build tools to make them more "pythonic", and to have a common library so both the naming and gziping processes use the same functions for deriving file names. This also addresses an issue where the firmware files were incorrectly named when using non-default paths.

I have tested with the default setup, `platformio_overides.ini` changes and using environment variables. For the following:

- workspace_dir
- build_cache_dir
- cache_dir
- build_dir

**Please note:** I have _not_ tested on Windows (I don't have a Windows machine), however on Linux and Mac it has been OK. The process used should be cross platform. If you find any issues, please let me know and I'll fix ASAP.

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.1.0.7.3
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx.

Tested on windows and works fine.

I'm glad I still can easily disable map gzip as I don't need map gzip locally to be able to read it in VSC.

**Comment by sillyfrog** [comment]
@arendst Do you disable by deleting the file `gzip-firmware.py` file? I could make it so if you have an environment variable set it won't do the gzip file stuff. (Assuming you delete the file): that way your source could stay the same, just the `.gz` files are not created (I was thinking about doing something with environment variables to also have a way to put all of the source files somewhere else outside of the source tree).

**Comment by arendst** [comment]
No I comment out line 31 like
```
#env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", [map_gzip])
```
 I might still need the binary zipped.

**Comment by sillyfrog** [comment]
I have just pushed https://github.com/arendst/Tasmota/pull/12896 that provides options to disable the gzip creation, and override the locations of the `.bin` and `.map` files.

**Pull request merged**
