### PR TITLE
Audio i2s update

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

refactor i2s audio
select pins via tasmota GPIO gui
add codecs for s3box and s3box lite
add stereo microphone recording for s3box

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
I2S GPIOs were already defined. Can't you use the existing ones?

**Comment by arendst** [comment]
I agree

**Comment by gemu2015** [comment]
these are not compatible with esp idf audio i2s and mclk is missing

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2s.html#

An I2S bus that communicate in Standard or TDM mode consists of the following lines:

MCLK: Master clock line. It’s an optional signal depends on slave side, mainly used for offering a reference clock to the I2S slave device.
BCLK: Bit clock line. The bit clock for data line.
WS: Word(Slot) select line. It is usually used to identify the vocal tract except PDM mode.
DIN/DOUT: Serial data input/output line. (Data will loopback internally if din and dout are set to a same GPIO)

**Comment by arendst** [comment]
But what are the chances of having both the "old" and your new GPIOs on one device?

If zero than the GPIO names can be reused by your driver without any problem. It's just naming for GPIO, there is no code behind it unless you maske the relation between the GPIO and the code.

**Comment by arendst** [comment]
What if we can match the old naming to the new ones? Looking at it I think we cannot match all of them...

**Comment by s-hadinger** [comment]
There are different naming in I2s. Fell free to rename with the new one

**Comment by s-hadinger** [comment]
Do you need MCLK? It's used only when the external device is sending the clock?

**Comment by gemu2015** [comment]
the s3 box uses mclk

**Comment by gemu2015** [comment]
why not leaving both definitions ?
the old one is enabled by USE_I2S
the new one is enabled by USE_I2S_AUDIO

it well rarely be that both are used together

**Comment by gemu2015** [comment]
yes of course

**Comment by s-hadinger** [comment]
> why not leaving both definitions ?
> the old one is enabled by USE_I2S
> the new one is enabled by USE_I2S_AUDIO

I've been the only one using the previous definitions in a project still in development. I'm ok to align to any other #fidef and having the old ones depend on `USE_I2S_AUDIO`

**Comment by arendst** [comment]
I'll do some changes now.

**Comment by gemu2015** [comment]
Thx

**Pull request merged**
