### PR TITLE
[Shutter] Fix PowerON

### PR DESCRIPTION
**Pull request by SteWers**
## Description:

I have on some devices, not on all, the problem, that both shutter relais are switches on after power on. This doesn't happen after a software restart. This PR fixes the problem.
@stefanbode: Please have a look at it, if I did it the right way. 

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.1.0.241117
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by stefanbode** [comment]
Let’s keep this on hold. Here you disable the power switch on restart. May be a good idea if shutters defined and a shutter relay but should not kick in in any other situation. I do not understand why this happens NOW. It was not an issue the last 5 years.

**Comment by stefanbode** [comment]
Thanks for all the investigation efforts. We can curate the symptoms but I would better understand the root cause and fix this. If there is no shutterrelay defined it should not matter is so80 is 0 or 1. why should it mess with relay 1 and 2 if the shutterrelay can also be anything else. this is crazy first. Do both relays go ON even with the interlock defined? I did not get this. It should be absolutely impossible. There is a setoption where Tasmota reads the state of the relay and want to set it. This is default and I disabled it on shutters as far as I remember.

**Comment by SteWers** [comment]
I totally agree with you to find the root cause. Both relays go ON even when interlock is activated.
Your hint with the setoption was the right way. I think you mean SO63. When I set it to 1 the problem is away. I read about it, but as the documentation only refers to _warm start_, I haven't tested with it. I'll do some tests tomorrow and close the PR.
It would be nice, if you investigate why it isn't set, when shutter is enabled. Interesting interaction between SO80 and SO63...

**Comment by SteWers** [comment]
Found this #18670. Same problem also solved with SO63. An integration in the shutter driver is desirable.

**Comment by SteWers** [comment]
Let's try this way.

**Comment by arendst** [comment]
Before merging this I suggest to move `ShutterInit()` from FUNC_PRE_INIT to FUNC_INIT and see if this solves the issue.

By moving it to FUNC_INIT it is executed AFTER the Initial power state is set. This may well solve the issue observed.

Pls give it a try.

**Comment by SteWers** [comment]
I tried your suggestion but unfortunately it doesn't solve the problem.

**Comment by arendst** [comment]
Thx for testing

**Pull request merged**
