### PR TITLE
Support multiple SR04 ultrasonic sensors

### LINKED ISSUE #9431: Support multiple SR04 ultrasonic distance sensors
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
No - just need to use 2 SR04 sensors on a single ESP32

**Describe the solution you'd like**  
Support for multiple SR04 sensors like it already is present for buttons, e.g.

**Describe alternatives you've considered**  
Using a separate ESP per sensor would be an alternative, but more expensive and with additional cabling.

**Additional context**  
None

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by dka23**
## Description:

**Related issue (if applicable):** fixes #9431 

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [X] The code change is tested and works on core ESP32 V.1.12.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by dka23** [comment]
Looks good now - unfortunately I don't have an ESP8266 for testing this, but compilation works fine.

**Comment by vic42** [comment]
Would be nice to have an option sharing the RX pin to save GPIOs. You probably should fire the triggers "round robin" style anyway to avoid interference. Just my 2¢.

**Comment by stefanbode** [comment]
@dka23 : Just as a side topic. I also started some time ago with the SR04 sensors but replaced them all with VLC laser sensors. These only cost a fraction more and they are much more precise and most important the lifetime is much longer than 1 year. All my Sr04 died more or less after a year because of corrosion. The VLC do not have this problem.

**Comment by FerFemNemBem** [comment]
Hi,
is there any progress?
I would also like to have the multi sensor support in Tasmota.

**Comment by woidbaier** [comment]
Hi,
Is there already a date or target release when the feature is planned?
I would also like to have the multi sensor support in Tasmota.

**Comment by ascillato** [comment]
It is already supported in Tasmota to have multiple distance sensors, but with the VL53L0X that is a much more precise sensor rather than the SR04. Please, take a look at https://tasmota.github.io/docs/VL53L0x/

**Comment by FillyderErste** [comment]
Hi,

today I tried to connect 2 SR04 to a Wemos D1 mini. Firmware is latest tasmota-sensors.bin. But I receive only 1 distance in the Tasmota UI. Is there any special setting required to run more SR04 on the Wemos D1 mini?
unknown
grafik

**Comment by ascillato** [comment]
Tasmota supports only 1 SR04

**Comment by barbudor** [comment]
You should use VL53L0X/VL53L1X sensors as Tasmota can support up to 8 of them
Beside, those sensors are waaaaaayyyyy better than ultrasonic sensors (and they don't make your dog barks)
https://tasmota.github.io/docs/VL53Lxx/

**Comment by Supermichi** [comment]
We are currently facing the same problem. Unfortunately, the VL53L0X/VL53L1X is not an option since we measure transperent materials. Is there already a plan to implement support for multiple SR04s?

**Comment by shanekuz** [comment]
Same i would like support for two SR04 sensors as i use them to monitor tank water levels.

**Comment by barbudor** [comment]
Tasmota supports up to 4 VL53L0x/L1x
More reliable than SR04

**Comment by barbudor** [comment]
I just had a look and the SR04 driver is a bit complex as it supports both Serial and Ping/Echo modes
It would requires a bit of refactoring to get it working with multiple sensors, especially in serial mode

Regarding using the VL53L*X with liquids such as clear water, the way I'm doing it is:
- Using a PVC pipe of 4cm diameter
- Make a few hole in it, especially at the bottom and at the top
- Insert a round and flat piece of white floating material of almost the same diameter which can go up and down with the liquid
- Insert the pip vertically in the tank so that the floating piece can move up and down with the level of the liquid in the tank
- set the VL sensor at the top

**Comment by jgesser** [comment]
> I just had a look and the SR04 driver is a bit complex as it supports both Serial and Ping/Echo modes It would requires a bit of refactoring to get it working with multiple sensors, especially in serial mode
> 
> Regarding using the VL53L*X with liquids such as clear water, the way I'm doing it is:
> 
>     * Using a PVC pipe of 4cm diameter
> 
>     * Make a few hole in it, especially at the bottom and at the top
> 
>     * Insert a round and flat piece of white floating material of almost the same diameter which can go up and down with the liquid
> 
>     * Insert the pip vertically in the tank so that the floating piece can move up and down with the level of the liquid in the tank
> 
>     * set the VL sensor at the top

That's an interesting idea, but it seems that using 2 SR04 is still simpler. At least for me it would be easier to monitor my 2 water tanks with only one tasmota device. It doesm't necessarily need to be much precise...

**Comment by belgotux** [comment]
I don't understand why this PR is closed ? The work is already done by @dka23 
You need review of the code or something ? The commits have 3 years old. The VL53L*X is a good discovery for me, but need to check 3 water thanks and don't want to use 3 esp32. If someone prefer to use the JSN-SR04T 

Regards,

**Comment by paulh-rnd** [comment]
Just ran into this as well, same issue, same question: I want to monitor two tanks with two SR04s, and I'm not interested in the laser rangers. What work is involved in meeting this PR?

**Comment by jgesser** [comment]
Hi @paulh-rnd, @belgotux  ,  I also need this feature and this PR is not compatible anymore, impossible to merge it as is.

So, I forked the Tasmota repo and made the changes again. But right now I have only one sensor to test. So I cannot validate if two or more sensors will work correctly and display the right readings independently from each other. One sensor is still working fine with my changes.
Because of that, I didn't raise a new PR yet, We need to test it.

Here is the link to compare my changes:
https://github.com/arendst/Tasmota/compare/development...jgesser:Tasmota:sr04-multiple-sensors-support?expand=1

I can share a compiled firmware for esp8266 if you or anyone else are willing to help on testing.

**Comment by jgesser** [comment]
Here is the build of Tasmota Sensors with the changes. Based on development branch.

[firmware.zip](https://github.com/arendst/Tasmota/files/14495717/firmware.zip)

**Comment by belgotux** [comment]
Hi jgesser,

I've done some test and it's work nice with 2 devices !
I encountered some issues initially, as only one device was functioning. However, it turned out to be the new 4-level converter that I soldered, which had a problem with the mosfet ... try to check your code for nothing, bad chinesium ...
```
12:10:20.007 MQT: ip/bureau/test/tele/SENSOR = {"Time":"2024-03-17T12:10:19","SR04-1":{"Distance":70.5},"SR04-2":{"Distance":37.2}}
```
image

I've try after with the two water tank device and one spare part and it works well too!
Thanks for your time! You can PR I think ;)

image
image
The testing setup is not good looking but working :)
image

**Comment by jgesser** [comment]
Hi @belgotux ,

that sounds great. It seems you have the same use case then I, two water tanks to monitor.
Thank you very much for your time on testing. 
My new sensor are about to arrive in couple weeks, but as you have tested and it seems to be working fine, I will raise a PR right away.

**Comment by jgesser** [comment]
PR raised: https://github.com/arendst/Tasmota/pull/20975

**Pull request closed without merging**
