### PR TITLE
Ble esp32 final

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:
Introducing xdrv_52_BLE_ESP32.
This PR is Ready.

Introduces a generic ESP32 BLE 'driver' designed to be used by other device drivers so that BLE can be used by multiple 'drivers' at once.

### The issue:
There are two BLE related xSns drivers - iBeacon (xsns_52) and a Sensor driver (xsns_62) which can be built in to support native ESP32 BLE.  These two drivers conflict, and cannot be used together.
At the moment, adding a BLE sensor would involve creating additional detailed functionality inside the xsns_62 driver for each device which we wished to support, or adding an additional driver.
I believe the style of the suggested generic driver will allow people to use existing sensors (and other BLE devices requiring read/write/notify access) with Tasmota without additional development within Tasmota.
It also allows 'popular' devices to have a specific driver within Tasmota, but sharing the BLE, and not conflicting.

### xdrv_52 provides:
1/ generic BLE scanning, catching advertisments with data, and calling registered callbacks.
2/ generic BLE 'operations'.
an operation can be setup through an API call, and provide a callback on success or failure.
Operations can also be setup and executed via commands, resulting in MQTT output on success or failure.
callbacks can be registered to 'hear' all operations.
3/ callbacks can be registered to see scan results at the end of a scan.

### Example modified drivers:
xsns_52_ibeacon.ino and xsns_62_MI_ESP32.ino are disabled by USE_BLE_ESP32

In their place, these are enabled:
xsns_52_ibeacon_BLE_ESP32.ino and xsns_62_MI_ESP32_BLE_ESP32.ino 
These have been adjusted to instead of using the NimBLE stack directly, to subscribe to services provided by xdrv_48_BLE_ESP32.

I believe I have included all the features required for the two sensor drivers that we have.

### use:
xdrv_52 is enabled via 
USE_BLE_ESP32 and ESP32
BLE may be enabled through a new Configuration button on the web UI, or 'setoption115 1'.
It currently logs all adverts with extra data at LOG_LEVEL_DEBUG_MORE, and is fairly verbose about actions at LOG_LEVEL_DEBUG.
To enable xsns_52_ibeacon_BLE_ESP32 as well, enable USE_IBEACON_ESP32
To enable xsns_62_MI_ESP32_BLE_ESP32 as well, enable USE_MI_ESP32

### documentation
I have added a lot of comments at the top about usage, and some examples are at the bottom of the main file.
A pr is in the wings for updaiing the documentation on the docs site.

### Personal motivation:
I have both temp/humidity sensors and EQ-3 BLE radiator valves spread around a house.
I wanted an ESP32 based device which could act as a WIFI to BLE bridge working with both types of device.
Using the commands on the generic driver, I can read/write/notify against the EQ3 valves, and also hear the temp/humidity (once xsns_62 is updated).
I did not want to add all the bulk of an 'EQ3 driver' to Tasmota, preferring the heavy lifting of the variety of BLE command sets to be dealt with in something like Node Red.

### Requests:
I have prepared the xdrv_48 driver based on requirements gathered from xsns62, xsns52, and from my own EQ3 BLE requirements.  
This will not be a complete set of requirements to be able to read/write any BLE device completely generically, but is probably a fairly good start.
We probably can't create a generic driver which would deal with ALL BLE devices, but it would be really good to get verification that the driver is able to talk to some other devices other than the EQ3 devices.
Scan results are currently not published - there is a lot of information in the debug logs to work with, but I believe that scan results should be published - thoughts on this appreciated (e.g. should you have to ask for them, should they be a web UI feature, etc.).
E.g. thoughts on blocking devices in busy areas would be appreciated.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by btsimonh** [comment]
note small change in webserver - adding 10ms of delay each upload loop.
I'm sure this has no impact on upload time, but it does stop the ESP idle loop from timing out when compiled for esp32solo1.
The espsolo1 build still times out on ota from a server - I looked into this but it requires changes to the base (arduino?) http library - beyond my remit.

**Comment by arendst** [comment]
Thx!!!

Would it be a big problem to rebase this PR first? 

I see my changes from the 14th are not incorporated in your ``xsns_62_MI_ESP32.ino`` and ``xsns_52_ibeacon.ino``. They do not harm your changes but yours overrules my changes regarding wifi sleep.

And implementing your BLE library makes the current BLE drivers useless or are they still functional?

**Comment by btsimonh** [comment]
thankyou!
  - yes noticed your changes, but I screwed up my first attempt to rebase, and then forgot about the changes as I made my 2nd attempt at the rebase :(.
When you look at the sleep stuff - also add it into the BLE_ESP32 driver - it has the same 'set sleep if unset' feature requirement.

"And implementing your BLE library makes the current BLE drivers useless or are they still functional?"
 - the old drivers are used until USE_BLE_ESP32 is set, which switches them over.  BUT...  I've not tested the old with the new NimBLE, and would recommend USE_BLE_ESP32 is set by default.  (the old MI driver is far too complex in it's operation - if someone really wants to maintain it, then great, but since we have all the functionality and more, I don't see the need.  If we really missed something, then we can always update the new version?)

**Comment by fightforlife** [comment]
Just some Feedback: Tested the latest development tasmota32-sensor.bin (20210118 12:19)
The refactored Xiaomi sensor driver is working as expected (4x LYWSD03MMC with ATC firmware).

I tried some of the BLEOpXX commands to communicate with my EQ3 valves. (like the example you included in the driver)
But I always get the error, that the command is unknown:
```
14:50:00.152 CMD: BLEOp0
14:50:00.167 MQT: stat/tasmota_863C5C/RESULT = {"Command":"Unknown"}
```

```
Example:
Write and request next notify:
backlog BLEOp1 001A22092EE0; BLEOp2 3e135142-654f-9090-134a-a6ff5bb77046; BLEOp3 3fa4585a-ce4a-3bad-db4b-b8df8179ea09; BLEOp4 03; BLEOp6 d0e8434d-cd29-0996-af41-6c90f4e0eb2a;
BLEOp10 ->
19:25:08 RSL: tele/tasmota_E89E98/SENSOR = {"BLEOperation":{"opid":"3,"state":"1,"MAC":"001A22092EE0","svc":"3e135142-654f-9090-134a-a6ff5bb77046","char":"3fa4585a-ce4a-3bad-db4b-b8df8179ea09","wrote":"03}}
19:25:08 queued 0 sent {"BLEOperation":{"opid":"3,"state":"1,"MAC":"001A22092EE0","svc":"3e135142-654f-9090-134a-a6ff5bb77046","char":"3fa4585a-ce4a-3bad-db4b-b8df8179ea09","wrote":"03}}
19:25:08 RSL: stat/tasmota_E89E98/RESULT = {"BLEOp":"Done"}
```

**Comment by btsimonh** [comment]
@fightforlife - 
It's not build in as standard yet.  
Good news that the old MI driver is working.
We'll need the following changes before it's in the versions built and put on the server:
1/ USE_BLE_ESP32 to be defined.
2/ platformio_tasmota32.ini to have the latest arduino release (you can do this if you copy platform_override_sample.ini to platform_override.ini and build).

If you wish to drive EQ3, try 
https://github.com/btsimonh/Tasmota/tree/EQ3_BLE_ESP32_XDRV53
which I'll be issuing as a PR very soon.

(p.s. seems the comments at the top may be out of date in terms of BLEOp.
more up to date docs here:
https://docs.google.com/document/d/1PMaGJwhxtKDgruHc79bVby8Wx6kbHyKp6WM6AriXNMo/edit#heading=h.cbg1j3jsi7nr
There is a PR on the way for official Tasmota documentation updates :) )

**Comment by fightforlife** [comment]
I just tested your EQ3 branch.
I tried multiple EQ3 commands and till now everything works as expected.
Also die MI BLE Sensors are working fine. 

I will leave it running for some time and see if I notice any strange behaviour.

**Comment by btsimonh** [comment]
:) thankyou!  ref EQ3, pls feel free to discuss in discord (ble-esp32).   @ysbrand has been testing for some time.  We have some ideas about small enhancements, but it's basically complete.

**Comment by kroon040** [comment]
> 
> 
> @fightforlife -
> It's not build in as standard yet.
> Good news that the old MI driver is working.
> We'll need the following changes before it's in the versions built and put on the server:
> 1/ USE_BLE_ESP32 to be defined.
> 2/ platformio_tasmota32.ini to have the latest arduino release (you can do this if you copy platform_override_sample.ini to platform_override.ini and build).
> 
> If you wish to drive EQ3, try
> https://github.com/btsimonh/Tasmota/tree/EQ3_BLE_ESP32_XDRV53
> which I'll be issuing as a PR very soon.
> 
> (p.s. seems the comments at the top may be out of date in terms of BLEOp.
> more up to date docs here:
> https://docs.google.com/document/d/1PMaGJwhxtKDgruHc79bVby8Wx6kbHyKp6WM6AriXNMo/edit#heading=h.cbg1j3jsi7nr
> There is a PR on the way for official Tasmota documentation updates :) )

Hope that de EQ3 is soon in the development of tasmota... what is very soon?;-)

**Comment by btsimonh** [comment]
@kroon040  we're talking about HA integration and control for EQ3 over here:
https://github.com/btsimonh/Tasmota/issues
The current driver is functional, but not yet 'special' :).

**Comment by luis33338** [comment]
10600

**Comment by kroon040** [comment]
Ok I didn't see it in the changelog of tasmota development yet

https://github.com/arendst/Tasmota/blob/development/CHANGELOG.md

**Comment by rjblake** [comment]
Will this also work with the LYWSD03MMC that is flashed with the PVVX formware (Victor's variation of the ATC firmware)?

**Comment by Ysbrand** [comment]
Yes, just make sure that it only transmits a single protocol

**Comment by btsimonh** [comment]
yes.  Just make sure you set only ONE form of advert.  His custom packet is supported.  If you choose his 'all' option, TAS will be confused about the device type.... - damn @Ysbrand got there first!

**Comment by rjblake** [comment]
@Ysbrand @ @btsimonh - many thanks. Have them set only to his 19 bit option

**Comment by rjblake** [comment]
Another ask on the BLE & ESP32 - are there any preferences for a specific ESP32 board (e.g. ESP32 WROOM 32D or 32U, ESP32-Cam, ESP32-S, etc.)?

**Comment by Ysbrand** [comment]
I've been using both SP32 WROOM 32D and 32U. During my quick tests I saw barely any difference in sensitivity. Obviously an external antenna gives you some more flexibility for positioning the ESP32.

**Comment by rjblake** [comment]
@Ysbrand - does the external antenna improve the Bluetooth reception too, or just WiFi?

**Comment by Ysbrand** [comment]
I did not see any difference in BLE sensitivity. But @btsimonh did see some difference.
For BLE, at least in my case, I had better BLE reception when the antenna was positioned vertical, with horizontal position some far away devices were no longer visible.
These are the devices I'm using. As you can see: the 32D model has an antenna that extends beyond the PCB, I think this is better than the ones where the antenna is completely integrated on the board.

image

**Pull request merged**
