### PR TITLE
Domoticz add tempo ds18x20 multi sensors 

### PR DESCRIPTION
**Pull request by roblad**
## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

Thanks for making this PR.

Please, complete the checklist. Thanks

**Comment by roblad** [comment]
done

**Comment by ascillato** [comment]
Thanks. Now, let's wait for Theo to review it.

**Comment by roblad** [comment]
I am closing that and I will do another one

**Comment by roblad** [comment]
That is ok

**Comment by roblad** [comment]
another one will be created

**Pull request closed without merging**
