### PR TITLE
Mpr121 with "normal" button behavior 

### PR DESCRIPTION
**Pull request by MubiTec**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_
Buttons of mpr121 should have the same behavior than "normal" buttons, which can be configured in tasmota config (double press, 3x press, etc, as described in https://tasmota.github.io/docs/Buttons-and-Switches/)

### CODE REVIEW

**Comment by arendst** [comment]
The simple fact that this PR wants to change 4444 files should trigger you to retract this PR.

**Comment by Jason2866** [comment]
Git is not always easy.  Click on the pencil button. Doing this it generates a fork (a copy in your github)
Do your changes and provide the PR
image

**Comment by MubiTec** [comment]
You are right😂thank you for your help.
My problem is that I have a feature wish but can't solve it by myself. So I do not have a code which can be merged. 
What is the right procedure then?

**Comment by Jason2866** [comment]
Place your question in [Discussions](https://github.com/arendst/Tasmota/discussions/new)

**Pull request closed without merging**
