### PR TITLE
A4988 stepper

### PR DESCRIPTION
**Pull request by Leuselator**
## Description: Support for Stepper-motors connected to A4988-Driver-circuit 
Help needed: MQTT: I'm to stupid to enable this for MQTT - on console & REST it works just fine

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
In order to merge you should remeove the changes to files platformio.ini and my_user_config.h

**Comment by Leuselator** [comment]
I will - this afternoon...

**Comment by arendst** [comment]
And if you're add it, pls also remove the enable pin selection; it's quite obvious that this pin needs to be in certain state in order to use the device. Removing it saves precious code space.

And again, also revisit the many digitalwrites in AdjustMicroSteps; using an indexed array and just three digitalwrites probably makes code a lot smaller too.

Remember the goal of adding drivers/sensors is to add functionality with as little code as possible.

**Comment by Leuselator** [comment]
I'm not shure what you have in mind with "pls also remove the enable pin selection"
The Enable-Pin is not mandatory for function - if it is wired, you can switch off the 12V-side of A4988 if it's not wired, motor is permanently suplied with power - both works.

the array-thingy: I have to fiddle out how this "magic" works ... :-)

**Comment by Leuselator** [comment]
How to use:

1. physically connect at least Dir-&STP-Pin of A4988 to 2 free GPIO's of ESP
2. allocate those GPIOS in settings to "A4988 pins" (#170ff)
3. in console type **MOTOR {"setMIS":1,"setRPM":60,"setSPR":200,"doTurn":1.5}** (sets microstepping to 1/1, StepsPerRevolution to 200, RoundsPerMinute to 60 and lets the motor turn one and a half round)
**MOTOR {"doMove":100}** lets the motor step 100 times
**MOTOTR{"doRotate":360}** lets the motor rotate 360 degrees
REST works with : **http://<IP-address>/cm?user=aName&password=aPW&cmnd=MOTOR%20{%22setSPR%22:200,%22setRPM%22:60,%22doMove%22:360}**
Can someone plz take care to enable the MQTT-way to send this commands?
Cheers Tim

**Comment by arendst** [comment]
Mqtt works as expected. No issues here.

**Comment by meingraham** [comment]
@Leuselator 

Please create a new wiki page with the information above. 

I will add a new table to the Commands wiki for the new commands and link from that article to your new page.

Please describe in more detail the components that should be used when configuring the GPIO. If there are any constraints on which GPIO should or shouldn't be used, please include that information.

Is this driver included by default or is the a compiler #define directive that needs to be specified that the user must enable before compiling their own firmware.

Please expand on your third & fourth points with additional details. Perhaps some use cases where the use of the stepper motor is applicable.

If you get the page started, I'm sure that the community will expand on it as this new feature is applied to more and more uses.

I'm happy to "tweak" the page but I need a start in order to not put incorrect information in the article.

Regards.

Mike

**Comment by Leuselator** [comment]
@meingraham
Hey Mike - I did my best - can you please check it?

**Comment by GasTurbineMan** [comment]
Great work on getting the A4988 Stepper Motor code added to Tasmota.  Got a cheap A4988 controller and Stepper Motor delivered yesterday and started playing around.  Wired up all 6 of the assigned GPIO's from my ESP device to the A4988 as well as the 2 power sources and motor.  Entering the commands via console, it appeared they were working based on console response, but nothing was happening at the motor.  Finally I saw on another hookup diagram where the unused Reset and Sleep pins on the A4988 needed to be jumpered together.  Added that jumper and it all works.

Again, great work my all folks involved.

**Comment by meingraham** [comment]
Thanks. I updated the wiki.

**Comment by Leuselator** [comment]
Thanks for the flowers 😊!
Enjoy!
Cheers Tim
Von: GasTurbineMan <notifications@github.com>
Antworten an: arendst/Sonoff-Tasmota <reply@reply.github.com>
Datum: Freitag, 13. September 2019 um 21:16
An: arendst/Sonoff-Tasmota <Sonoff-Tasmota@noreply.github.com>
Cc: Tim Leuschner <mail@leuselsoft.de>, Mention <mention@noreply.github.com>
Betreff: Re: [arendst/Sonoff-Tasmota] A4988 stepper (#6370)


Great work on getting the A4988 Stepper Motor code added to Tasmota. Got a cheap A4988 controller and Stepper Motor delivered yesterday and started playing around. Wired up all 6 of the assigned GPIO's from my ESP device to the A4988 as well as the 2 power sources and motor. Entering the commands via console, it appeared they were working based on console response, but nothing was happening at the motor. Finally I saw on another hookup diagram where the unused Reset and Sleep pins on the A4988 needed to be jumpered together. Added that jumper and it all works.

Again, great work my all folks involved.

**Comment by GasTurbineMan** [comment]
@meingraham 
While I "thought" I might be able to edit the wiki page of commands myself, once I clicked on the "edit" button - I saw pretty quick I was in the deep water.  If you could add this info in some form, it may be beneficial for the "Stepper Motor Commands" page:

MotorMIS - (tasmota startup default = 1)
MotorSPR - (tasmota startup default = 200)
MotorRPM - (tasmota startup default = 30)
These are set at compile time and can be edited in the file:
          Sonoff-Tasmota-development x.x.x.x > Sonoff > xdrv_25_A4988_Stepper.ino

Thanks.

**Comment by meingraham** [comment]
Thanks - wiki updated.

As a general policy, we don't include information on modifying the code in the wiki. If the user wants that, they can ask or dig into the driver as you did.

**Comment by misc2000** [comment]
I need to control 2 Stepper Motor with an A4988 each. And it would be great to do it also with Tasmota. Is this possible because after the fist review it looks for me like I can only control 1 stepper per ESP? :-(

**Pull request merged**
