### PR TITLE
Ili9341 update

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

ili9341 driver 4 replaced by renderer class driver.
this driver also supports ILI9342 as used by m5stack core2
and TTGO bitcoin device which use 2 SPI busses.
(in this case we must define SSPI and the driver then uses the 2. spi bus)

since some ILI9341 boards have no cs this pin is optional 

tested with m5stack, bitcoin and esp8266
since i do not have a device with ILI9341 AND SD card on the same bus could not check this.
(like odroid) but should work.

i copied the display modes 1-5 code over from the old driver but i am not used to these modes. could you please test them before merging

ST7789 driver faster software SPI
 
Renderer support for text scaling with EPD fonts

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
The displaymode part "1-5" crashes with the Odroid Go. With displaymode 0 it does work.
```

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4

00:00:00.023 UFS: FlashFS mounted with 12308 kB free
00:00:00.047 CFG: Loaded from File, Count 232
00:00:00.048 FRC: Some settings have been reset (2)
00:00:00.049 CFG: CR 492/699, Busy 0
00:00:00.050 SPI: Hardware using GPIO18(CLK), GPIO23(MOSI) and GPIO19(MISO)
00:00:00.056 CFG: CR 492/699, Busy 0
00:00:00.058 CFG: CR 492/699, Busy 0
00:00:00.061 CFG: CR 492/699, Busy 0
00:00:00.076 SRC: Restart
00:00:00.077 Project tasmota Odroid Version 9.2.0.7(odroid-go)-1_0_5_RC6(2021-02-13T15:09:47)        
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400ec7b9  PS      : 0x00060530  A0      : 0x800ec9bd  A1      : 0x3ffb1e80
A2      : 0x3ffc2104  A3      : 0x3ffc1df8  A4      : 0x00060120  A5      : 0x00000001
A6      : 0x00060123  A7      : 0x00000000  A8      : 0x3ffbdcd8  A9      : 0x3ffbdcda
A10     : 0x00000000  A11     : 0x00000010  A12     : 0x00000001  A13     : 0x00000001
A14     : 0x00060123  A15     : 0x00000000  SAR     : 0x00000005  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000  LBEG    : 0x400815f8  LEND    : 0x40081605  LCOUNT  : 0x00000000

ELF file SHA256: 0000000000000000

Backtrace: 0x400ec7b9:0x3ffb1e80 0x400ec9ba:0x3ffb1ea0 0x400ecb2f:0x3ffb1ef0 0x400ecff6:0x3ffb1f10 0x400f893c:0x3ffb1f30 0x400ead12:0x3ffb1f50 0x40105c44:0x3ffb1f70 0x40105c67:0x3ffb1f90 0x40124aa1:0x3ffb1fb0 0x4008dbfe:0x3ffb1fd0
```

**Comment by arendst** [comment]
Thx.

I will chk and let you know.

**Comment by arendst** [comment]
OK. I have it working but need to do some more tweaking.

**Comment by arendst** [comment]
I think this must work. Didn't test with core2 though....

**Comment by gemu2015** [comment]
fixed core2, works also with display mode >1

**Comment by Jason2866** [comment]
Working with Odroid-go too.

**Pull request merged**
