### PR TITLE
Change OTA URL to http://thehackbox.org

### PR DESCRIPTION
**Pull request by Jason2866**
Due to the fact of more and more user issues related to old outdated version on
http://sonoff.maddox.co.uk/tasmota/sonoff.bin

### CODE REVIEW

**Comment by arendst** [comment]
Are these the release versions or the development versions?

**Comment by Jason2866** [comment]
Development Version

**Comment by arendst** [comment]
So it's better I should make a new release. Been thinking about it but was reluctant considering the compile issues.

@andrethomas do we now have a correct compile procedure which also satisfies the Basic R2?

If so:
- Pls hand me the (updated) compile script
- I also suggest to make a release folder here too so all the bins are in one basket ;-)

**Comment by jobhh** [comment]
Is there a specific reason why the unencrypted version of http://thehackbox.org/tasmota/release/sonoff.bin is used? Is https not supported in the firmware?

It seems like a security flaw for OTA updates. The website does have a proper Let's Encrypt certificate, so https seems like a valid option.

**Comment by ascillato** [comment]
The OTA feature provided by the Arduino Core, does not support https due to memory constraints in the ESP8266 chip.

There is not enough RAM for that.

**Comment by jobhh** [comment]
Cool, thanks for the answer :)

**Pull request closed without merging**
