### PR TITLE
Add support for VEML6075

### PR DESCRIPTION
**Pull request by ruimarinho**
Support for Vishay VEML6075 UVA/UVB I2C sensor - an alternative to the Si1145 and related sensors (which aren't true UV sensors) and the raw photodiode GUVA-S12D (learned from [here](https://github.com/schizobovine/VEML6075)).

### CODE REVIEW

**Comment by joopy** [comment]
Agree would love to see this one: VEML6075 integration

**Review by ascillato — APPROVED** [review]

**Comment by mike2nl** [comment]
@ruimarinho 
That's funny, just ended the update for the VEML6070 v1.0.0.2 driver which
was merged yesterday. 

Now you came up with the VEML6075 1 1/2 moth before i got the same idea.
Did'nt seen it until now by searching the whole issue list, Jesus.
 
Because I just ordered one today and wait for it so i could start for developing.
Funny, and now? I will wait to see what you have reached.

Possibly we can work together when you are interested.

**Comment by FabianHM** [comment]
I hope you find an implementation for the VEML6075 UVA / UVB I2C sensor. Unfortunately, the previously supported Si1145 is no alternative. My VEML6075 is ready and I like to test :-)
Thanks Fabian

**Comment by andrethomas** [comment]
@ruimarinho Is it possible to clean up this PR a little by not including some of your local changes and only include code directly relevant to the driver?

Also, try to limit use of external libraries as these result in more complex drivers and more code for maintainers of this project to read before a merge can happen.

Your PR is appreciated but unlikely to me merged in its current form.

**Comment by mike2nl** [comment]
> I hope you find an implementation for the VEML6075 UVA / UVB I2C sensor. Unfortunately, the previously supported Si1145 is no alternative. My VEML6075 is ready and I like to test :-)
> Thanks Fabian
I ordered one on saturday last weekl. Will be here around in two weeks . In the
menatime i will work on that sensor and add them to the existing veml6070 dirver.
First approach is done but i have to wait now for the reel sensor

**Comment by joopy** [comment]
Good to hear! I can test when the code is finished.

**Comment by FabianHM** [comment]
> 
> 
> @FabianHM
> 
> > I hope you find an implementation for the VEML6075 UVA / UVB I2C sensor. Unfortunately, the previously supported Si1145 is no alternative. My VEML6075 is ready and I like to test :-)
> > Thanks Fabian
> 
>     * I ordered one on saturday last week. Will be here in around two weeks i hope.
>       In the menatime i will work on that sensor and add them to the existing veml6070 dirver.
>       First approach is done but i have to wait now for the reel sensor

Has the VEML 6075 arrived meanwhile? Not that somebody close this pull request before ;-) My sensor is ready to test :-)

**Comment by FabianHM** [comment]
Has anyone else worked on the topic? 
I would be very happy if the support for the VEML6075 were given.
Thank you for your support in advance.

**Comment by FabianHM** [comment]
Any news on this?

**Comment by FabianHM** [comment]
Now that I've been using the SI1145 sensor for some time, I've realized that it's not really useful at all.
The real alternative also to get useful UVA and UVB values is the VEML6070.

I propose to remove the implementation of the Si1145 in the future in order to gain space for the implementation of the VEML6075.

@ruimarinho , @mike2nl, @joopy  : 
Would it be possible to continue the work on VEML6075?
@mike2nl Thanks again for the ingenious implementation of the VEML6070, which works great!

Hoping for early sunshine for testing
fabian

**Comment by FabianHM** [comment]
@gemu2015 : Hallo Gerhard, leider scheint an dem Projekt Sensor VEML 6075 niemand mehr zu arbeiten. Da wir schon oft zu Sensor Themen Kontakt hatten würde ich mich freuen, wenn Du hier evtl. unterstützen könntest, wenn Du Lust und Zeit hättest....
Dankeschön :-)

Grüße
Fabian

**Comment by gemu2015** [comment]
@FabianHM 
Hallo Fabian
ok arbeite nur an Projekten die ich selber benutze. Aber ein UVA,B Sensor wäre auch für mich interessant. Habe also einen geordert. Wenn der aus China da ist werde ich den Treiber bauen.
Gruß
Gerhard

**Comment by gemu2015** [comment]
@FabianHM
Hallo Fabian
Habe den Treiber in meinem Fork eingebaut und geringfügig angepasst. (Dank an @ruimarinho)
er sollte funktionieren. (kopiere einfach den Treiber und die library)
Gruß
Gerhard

**Comment by FabianHM** [comment]
> @FabianHM
> Hallo Fabian
> Habe den Treiber in meinem Fork eingebaut und geringfügig angepasst. (Dank an @ruimarinho)
> er sollte funktionieren. (kopiere einfach den Treiber und die library)
> Gruß
> Gerhard

Hallo Gerhard,
Prima, ich werde es heute Abend testen. Es gibt übrigens die libray nun in der V. 1.0.4:
https://github.com/sparkfun/SparkFun_VEML6075_Arduino_Library/archive/master.zip
Muss ich neben der o.g. Änderungen noch weitere vornehmen, z.B. in der my_user_config.h den Eintrag #define USE_VEML6075 hinzufügen?

Danke für deine Unterstützung,
Grüße
Fabian

**Comment by gemu2015** [comment]
ja, #define USE_VEML6075 in my_user:config.h oder in user_config_overwrite.h

**Comment by FabianHM** [comment]
@FabianHM <https://github.com/FabianHM> Hallo Fabian Habe den Treiber in meinem Fork eingebaut und geringfügig angepasst. (Dank an @ruimarinho <https://github.com/ruimarinho>) er sollte funktionieren. (kopiere einfach den Treiber und die library) Gruß Gerhard Hallo Gerhard, Prima, ich werde es heute Abend testen. Es gibt übrigens die libray nun in der V. 1.0.4: https://github.com/sparkfun/SparkFun_VEML6075_Arduino_Library/archive/master.zip 

Hallo Gehard, wir schreiben besser auf Englisch weiter für alle anderen....
I tried to compile a new version. There are errors when the sensor xsns_45_vl53l0x.ino is activated (duplicate labels, etc). After I removed this sensor I was able to compile the VEML6075 driver (including the library version 1.0.4). Whether the sensor works I test today.
Grüße
Fabian

**Comment by gemu2015** [comment]
Sensor conflict removed.

**Comment by FabianHM** [comment]
I tested the sensor. I noticed two problems:
1. JSON output is faulty - Solution:
Customization in xsns_96_veml6075.ino
`ResponseAppend_P(PSTR(",\"VEML6075\":{\"" D_JSON_UVA_LEVEL "\":%d,\"" D_JSON_UVB_LEVEL "\":%d,\"" D_JSON_UV_INDEX "\":%d}"), uva_level, uvb_level, uv_index);`
the comma is missing before the first slash


2. The UV index was just permanent 0. I compare it tomorrow with the values of my VEML 6070 and SI1145.

**Comment by gemu2015** [comment]
ok, komma in json added,

**Comment by FabianHM** [comment]
Here are my results of the Tests.
At first I noticed that the values of UVA and UVB were apparently displayed realistically, but the UV index remained permanently at 0.
Today I wanted to take a closer look at the sensor, but it displays the following values permanently.
I have now tried several Wemos all with the same result.
Either the sensor is defective or it is too hot ;-)

**Comment by gemu2015** [comment]
ok,  my sensor is still on the way from china.  i will report when it has arrived

**Comment by FabianHM** [comment]
Hallo Gerhard,

ist der Sensor eingetroffen und hattest Du Gelegenheit ihn zu testen?

Ich habe entdeckt wie es zu den o.g. fehlerhaften Ausgaben kam, es lag an der falschen Library.
Bei meinem ersten Test hatte ich die SparkFun_VEML6075_Arduino_Library-V_1.0.3 kompiliert, damit ging es ja. Die Fehler entstanden bei der Version SparkFun_VEML6075_Arduino_Library-V_1.0.4.

Was ist nun zu tun, damit der Sensor in die offizielle Tasmota Version aufgenommen wird??
Funktion ist derzeit einwandfrei und stabil.

Grüße
Fabian

**Comment by ascillato** [comment]
@FabianHM Please, can you translate that to English? Thanks

**Comment by gemu2015** [comment]
Hi Fabian,
yes my sensor arrived and i have tested it. i made some  modifications and it works. 
however uv index is a float that shows very small values below 1 ???
according to www it should read 0 to 11 ...
did you try my latest driver ?

what bothers me is the fact that the measured values vary extremely when changing the settings (e.g. integration time)
according to an application note it always has to be calibrated.

this discouraged me to investigate more time.

greetings
 Gerhard

[designingveml6075.pdf](https://github.com/arendst/Sonoff-Tasmota/files/3482631/designingveml6075.pdf)

**Comment by FabianHM** [comment]
Yes, I use your last driver.
I use the UV index of the sensor VEML6070, which works great, so I do not care about the value.
Do you mean the use of UVA and UVB without calibration is not worth it?

**Comment by Jason2866** [comment]
VEML6075 is EoL and Vishay recommends VEML6070 as replacement.

**Comment by mike2nl** [comment]
@FabianHM 
The VEML6070 UV-Index is good and heavy calculated.
I had rewritten the drivers calculation a while ago and i had university calibration tools to check the new math. Much work was done to get it straigth.
The VEML6070 driver/sensor is what you can use for everyday purpose. I do the same and i'm a perfectionist with sensors ;-) .

I have two old VEML6075. But so as Jason says they are EoL, but i will test this again when i get my hands on that university stuff again.

**Comment by ascillato2** [comment]
Closing this PR as this sensor is EOL and users won't have the chance to buy it.

**Comment by ascillato2** [comment]
For anyone reaching this old PR. Tasmota do supports this sensor.

**Comment by derron7** [comment]
There is a typo in the JSON Output: UvbItensity (missing "n")

**Comment by arendst** [comment]
Thx. Fixed.

**Comment by derron7** [comment]
Thank you, arendst! I'm also wondering why Power on = 0 and Power off = 1, but I can live with that. Will the sensor be committed to the master release in the near future?

**Pull request closed without merging**
