### PR TITLE
Added /stat/RESULT for Button and Switches

### PR DESCRIPTION
**Pull request by effelle**
## Description:
This PR introduce new MQTT `/stat/RESULT`, useful for a more granular control over buttons and switches under Home Assistant/OpenHab using HA integration as some users had requested.  
```
16:49:06 MQT: stat/sonoff/RESULT = {"BUTTON2":2}
16:49:06 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
16:49:06 MQT: stat/sonoff/POWER = ON
16:49:08 MQT: stat/sonoff/RESULT = {"BUTTON2":2}
16:49:08 MQT: stat/sonoff/RESULT = {"POWER":"OFF"}
16:49:08 MQT: stat/sonoff/POWER = OFF
16:49:12 MQT: stat/sonoff/RESULT = {"SWITCH1":1}
16:49:12 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
16:49:12 MQT: stat/sonoff/POWER = ON
16:49:15 MQT: stat/sonoff/RESULT = {"SWITCH1":0}
16:49:15 MQT: stat/sonoff/RESULT = {"POWER":"OFF"}
16:49:15 MQT: stat/sonoff/POWER = OFF
```
Can be bind to Setoption19 if needed to avoid eccessive MQTT traffic. 

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core pre-2.6
  - [X] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
Home Assistant Auto Discovery is very limited. Adding more and more does litter Tasmota code
and its logic structure. See https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html too

**Comment by effelle** [comment]
>Home Assistant Auto Discovery is very limited

Yes, now HA integration is limited under actual OH version but since I'm in contact with OH MQTT community too, thanks to @davidgraeff, I can assure you things will changes and the protocol will be fully implemented soon. 
And by the way the new integration I'm preparing is more efficient with less code needed.

**Comment by meingraham** [comment]
This auto discovery is active only if the user turns it on; yes? So, a user chooses to add the MQTT traffic in order to have auto discovery? It's not on by default?

**Comment by effelle** [comment]
Yes, auto discovery is on just when `Setoption19` is set to `1`. 
The new topic is on by default on this PR but as I wrote it can be activated just if setoption19 is enabled.

**Comment by Jason2866** [comment]
Imho it would be better to activate only with `Setoption19` to `1`

**Comment by effelle** [comment]
Done.

**Comment by effelle** [comment]
Testing!

**Pull request closed without merging**
