### PR TITLE
Added firmwares undefs for minimal compilation

### PR DESCRIPTION
**Pull request by ascillato**
## Description:

Added firmwares undefs undef for minimal compilation

**Related issue (if applicable):** NA

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core pre-2.6
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
That must be future use USE_KNX_NO_EMULATION as I cannot find it....

**Comment by ascillato** [comment]
If uncommenting in platformio.ini the build flag -DUSE_KNX_NO_EMULATION, and building all firmwares, minimal got bigger due this key is not being undef.
This PR is just to cover this case too.

**Comment by arendst** [comment]
Right. So the correct define is FIRMWARE_KNX_NO_EMULATION and not USE_KNX_NO_EMULATION

**Comment by ascillato** [comment]
you are right. fixing...

**Comment by ascillato** [comment]
I think, as this case could happen to other firmware options, I will add to this PR the other undefs too.

**Comment by ascillato** [comment]
Done

**Pull request merged**
