### PR TITLE
Add correction factors for R G and B for WS2812 NeoPixel strip

### PR DESCRIPTION
**Pull request by MikePRoberts**
Theo
First what you have done here is outstanding.  Thank you and well done.
I have spent today playing with a WS2812B NeoPixel LED strip.  When driving from a colour wheel I felt the Green was too strong and the Blue much too strong.  I am driving the system with Node Red on a Pi.  So I added the ability to apply a reduction to any of R G and B.  I ended up correcting Green by 192/256 and Blue by 144/256. i.e, -25% and -44% respectively. (I also had LedTable =1)  I tried to capture the improvement on video at: https://youtu.be/_sD2RtwXDHE  The LEDs are a bit bright for the camera so please look around them for a better representation of what I am seeing.  My suggestion would be a correction number for each of R G and B scaled to 256. So 256 is 100% and lower values reduce the intensity.  The overhead is then a single byte multiply and >>8 for each colour value.
Thanks again.
Mike Roberts

### CODE REVIEW

**Comment by davidelang** [comment]
Mike, could you try to clean up your branch, what you sent includes a lot of 
unrelated changes

create a branch off of the current version for developing this feature, and make 
your changes to it. Don't merge in to this branch, instead try doing a rebase 
onto a newer release hen one comes out.

**Comment by MikePRoberts** [comment]
Sorry meant to add an issue.  My mistake.  Mike

**Comment by MikePRoberts** [comment]
David

I did not intend to create a new branch – but only to add a suggestion for improvement.  I am sorry for causing a problem.

I have closed the pull request and put my comment to issues where I should have put it originally.

Please let me know if I need to do any more to clear up the mess I created.

Mike

**Comment by davidelang** [comment]
there is no problem with creating a bad pull request, it just can be ignored. 
what you did is a common mistake, one of the experienced people at $work did 
almost the same thing about a week ago.

Your contribution _is_ wanted.

It's very common for people to make mistakes with their first few pull requests 
(it's far less common for their first pull requests to be clean :-)

We do want people to compile the code they are including in a pull request, so e 
don't look to see that it's possible to do all the file manipulation through the 
web interface, it may be possible, I'm not sure.

It just works out better for everyone to have the pull requests clean. It makes 
it very easy to see what's changing, and double check the change.

David Lang

**Pull request closed without merging**
