### PR TITLE
Add setting for IRremoteESP8266 tolerance

### PR DESCRIPTION
**Pull request by hr-kapanakov**
## Description:
Add setting that allow changing IRremoteESP8266 tolerance.
Discussion as ref: https://github.com/arendst/Tasmota/discussions/14435

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.2.1
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
You beat me on this one. It was on my todo list, well done. Theo was also proposing to reuse `P_ex_TUYA_VOLTAGE_ID` as you did.

I'm just worried about leftovers in `P_ex_TUYA_VOLTAGE_ID`. Also if a user updates with OTA, the value of the option will be zero which translates to zero tolerance; and things will break. I.e. the options equals zero should not have any regression.

Is Tolerance==0 even valid?

**Comment by hr-kapanakov** [comment]
Yes, I am agree about the leftovers. About zero tolerance it seems ok based on the IRremoteESP8266 docs - https://crankyoldgit.github.io/IRremoteESP8266/doxygen/html/classIRrecv.html#aa091c449db70c65fd0221669df7438ea. I also checked the code and also seems fine to be zero: https://github.com/crankyoldgit/IRremoteESP8266/blob/93af543dcb849918b0c342ed1b6af68953a61d06/src/IRrecv.cpp#L1123
The only problem is that in such case the IR signal should match at 100% which most probably is not possible in real world.

**Comment by hr-kapanakov** [comment]
Yeah, it seems a good compromise. I'll make the change.

**Review by s-hadinger — APPROVED** [review]

**Comment by arendst** [comment]
Thx. I need to make one final chk if ex tuya voltage id isn't used for version delta.

once chkd today i will merge.

**Comment by sfromis** [comment]
Looks like the "sacrifice" of the zero value to mean default of 25 did not work for existing configs. When upgrading firmware on an IR puck, it stopped working, with `SetOption44` being zero. Only after manually setting the tolerance, I could use a remote control again. 

While zero for default works when issuing the command `SetOption44 0`, it becomes a breaking change for existing configs, where the existing value of the config option byte will usually be zero.

**Comment by s-hadinger** [comment]
@sfromis You are right, `IrReceiveUpdateTolerance()` is never called when doing an update. I suggest it is called in `IrReceiveInit()` too

**Comment by s-hadinger** [comment]
@sfromis It should be fixed now

**Pull request merged**
