### PR TITLE
update: Added airm2m esp32c3 core device

### PR DESCRIPTION
**Pull request by xe5700**
## Description:

Added airm2m esp32c3 core device

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
Thanks for the PR. I would rather have an autoconfig file instead of a module. @arendst 
Thoughts?

**Comment by arendst** [comment]
Agree with @s-hadinger. Modules are passe at the cost of code space and can easily be implemented as autoconfig files.

**Comment by sfromis** [comment]
Looks like this could better simply have been standard templates, does not even need autoconf features

**Comment by Jason2866** [comment]
There is no need to add this C3 Board in code. The device can be configured using a Template.

**Pull request closed without merging**
