### PR TITLE
Rename "Konsolen" to "Werkzeuge"

### PR DESCRIPTION
**Pull request by SteWers**
I think it is also the better word in german. Refering to https://github.com/arendst/Tasmota/commit/d51340961fe2487c673b157335cdf85e6d73106c.

### CODE REVIEW

**Comment by eku** [comment]
> I think it is also the better word in german.

I'm sorry, but `Tools` is not German. How about `Verwaltung`?.

**Comment by Jason2866** [comment]
Do find both suggestions not perfect.

**Comment by Staars** [comment]
Besides I always use the stock english version, I think the most correct term would be:
_Dienstprogramme_ - which is quite long
a bit shorter:
_Werkzeuge_

Tools is definitely no translation and if you want to read _tools_ at that place, then just flash the english version.

**Comment by SteWers** [comment]
> Do find both suggestions not perfect.

I also think it's not perfect.
For me, `Werkzeuge` is the best suggestion.

**Pull request merged**
