### PR TITLE
added rcswitch functionality

### PR DESCRIPTION
**Pull request by kenmcc**
for now it's defaulting to GPIO 14 
tested on NodeMCU, using pin D5

### CODE REVIEW

**Comment by kenmcc** [comment]
I've fixed the issue which was preventing the builds (language files werent updated except for english) and it also now uses the selected pin for the rcswitch input, rather than defaulting to GPIO 14.

**Comment by Jason2866** [comment]
Question from an non programmer.

What does this enhancmet do? Can you give an example?
THX

**Comment by kenmcc** [comment]
This allows e.g. a 433mhz receiver to be connected to one of the GPIOs as an input. The Device will attempt to listen to 433 messages from something like a wireless plug transmitter (e.g. https://www.ie.screwfix.com/energenie-13a-wireless-remote-control-sockets-pack-of-3.html), and then output that value to an mqtt broker as an mqtt message.

An interpreter (e.g. OpenHAB) would then be in a position to report the status of the plugs based on the message received.

**Comment by Jason2866** [comment]
Great. I use at the moment a arduino pro mini (rcswitch sketch) connected to serial (via tasmota serial bridge) and decode the received mqtt traffic in a rule in OpenHab...
With your solution i dont need the arduino anymore😃

**Comment by kenmcc** [comment]
Hopefully :)

**Comment by Jason2866** [comment]
I use a pir 433 sensor.  This is the same as the remote.... Just one more item and another rule in OpenHab

**Comment by kenmcc** [comment]
same use as me actually. to be honest i forgot why i made this initially! then i remembered. problem with the plugs is that you might miss a tx and end up out of sync. presence detection should, in theory, be more deterministic

**Comment by Jason2866** [comment]
For presence detection i give RCWL 0516 a try. Not wireless but more accurate?!
This little sensor is now supported too

**Comment by Jizyjiang** [comment]
Thank you for your dedication. But there is one question, how can this be used in home assistant?

**Comment by Olesatgt** [comment]
Привет, можно ли к этому отличному проекту добавить поддержку 434.92 mHz модули Somfi

**Comment by Jason2866** [comment]
Hello @kenmcc 
i had time to test your RC Switch implementation.
Congrats works at first attempt!  Solution is already integrated in my OpenHAB system :-)

**Review by umairyounus — APPROVED** [review]

**Comment by andrethomas** [comment]
Is there any specific reason why GPIO_RCSWITCH and D_SENSOR_RCSWITCH is not at the end of UserSelectablePins and kSensorNames respectively ?

**Review by andrethomas — APPROVED** [review]

**Comment by arendst** [comment]
I'm working on a total re-write as this is only halfway done.

**Comment by kenmcc** [comment]
> 
> 
> I'm working on a total re-write as this is only halfway done.
What am I missing from it? (sorry!)

**Comment by andrethomas** [comment]
I'm expecting some RF encoder/decoder chips Friday or Monday so will see how those can also be integrated in a DIY method using this PR when you are done to allow direct 433Mhz DIY switches to control Tasmota powered device directly.

**Comment by kenmcc** [comment]
> 
> 
> I'm expecting some RF encoder/decoder chips Friday or Monday so will see how those can also be integrated in a DIY method using this PR when you are done to allow direct 433Mhz DIY switches to control Tasmota powered device directly.

ah ok, I had no use for that scenario so never considered it!

**Comment by arendst** [comment]
Regarding the re-write:

- The current xsns driver is a mess-up from a counter sensor.
- There Serial.println commands
- It only has basic receive functionality, no send functionality
- Its using the 50 milliseconds function to check every second which will fail as soon as sleep is enabled. Use second function instead.
- To be able to send it needs to be a driver, not a sensor
- It's way better to start off with the irremote driver.


Any way as said earlier, I will rewrite and provide a receive/send framework to build upon.

**Comment by andrethomas** [comment]
@arendst Thanks for adding the tx ability - was going to ask about that ;)

**Comment by badabing2005** [comment]
Hi,
Just curious how could one use this to transmit RF commands.
Flashed Tasmota  on NodeMCU, configured it as generic module and GPIO12 as 105 RFSend and GPIO14 as 106 RFrecv
The console shows the received RF commands when I press the RF remote
Example: 
`18:33:50 MQT: tele/nodemcu1/RESULT = {"RfReceived":{"Data":"69ACF4","Bits":24,"Protocol":1}}`

How Do I transmit that
Do I have to just publish a message to some MQTT topic?
Which?
cmnd/nodemcu1/...
What would the message be?
`{"RfSend":{"Data":"69ACF4","Bits":24,"Protocol":1}}` ?
 
Thanks
BB

**Comment by arendst** [comment]
It's either
```
RFsend {"data":0x501014,"bits":24,"protocol":1,"repeat":10,"pulse":350}
```
or
```
RFsend data, bits, protocol, repeat, pulse
```
with most fields optional as the defaults are
```
      if (!protocol) { protocol = 1; }
      if (!pulse) { pulse = 350; }      // Default pulse length for protocol 1
      if (!repeat) { repeat = 10; }     // Default at init
      if (!bits) { bits = 24; }         // Default 24 bits
```
In addition data may be decimal or hexadecimal (using the 0x prefix)

**Comment by arendst** [comment]
Could you enable more debugging info by command ``weblog 4`` or ``SerialLog 4`` and report if the Delay value is what you want to see as PulseLength?

**Comment by badabing2005** [comment]
Thanks
Yes, the delay value is the PulseLength

```08:34:52 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 226
08:34:53 MQT: tele/nodemcu1/RESULT = {"RfReceived":{"Data":"69ACF4","Bits":24,"Protocol":1}}
08:35:04 RFR: Data 29ACF4 (2731252), Bits 24, Protocol 1, Delay 229
08:35:04 MQT: tele/nodemcu1/RESULT = {"RfReceived":{"Data":"29ACF4","Bits":24,"Protocol":1}}
08:35:07 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 226
08:35:07 MQT: tele/nodemcu1/RESULT = {"RfReceived":{"Data":"69ACF4","Bits":24,"Protocol":1}}
08:35:07 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 227
08:35:07 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 228
08:35:11 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 226
08:35:11 MQT: tele/nodemcu1/RESULT = {"RfReceived":{"Data":"69ACF4","Bits":24,"Protocol":1}}
08:35:11 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 227
08:35:12 WIF: Checking connection...
08:35:12 WIF: Connected
08:35:14 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 227
08:35:14 MQT: tele/nodemcu1/RESULT = {"RfReceived":{"Data":"69ACF4","Bits":24,"Protocol":1}}
08:35:14 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 228```

**Comment by arendst** [comment]
RfSend 6925556, 24, 225, 10 does not send a pulselength of 225 as the value 225 is in the wrong position. Correct syntax is:
```
RFsend data, bits, protocol, repeat, pulse
```
So you have to send ``rfsend 6925556, 24, 1, 10, 225

**Comment by badabing2005** [comment]
Yep, that worked, sorry for missing an obvious part.
Many thanks.

Have a good day.
BB

**Comment by andrethomas** [comment]
Yes, if you do it using HA then you do not have the limitation of 16 codes anyway - this is how I use my sonoff bridge.. don't have any of the keys configured... just send rf data via mqtt

**Comment by badabing2005** [comment]
> 
> 
> Yes, if you do it using HA then you do not have the limitation of 16 codes anyway - this is how I use my sonoff bridge.. don't have any of the keys configured... just send rf data via mqtt

I built this because I never managed to get my RF Bridge to capture the remote commands.
Even though I've updated the RF Chip with Portisch code.
It works with Generic PIR, but not EV1527 it doesn't.
I'm assuming that I have a somewhat defective RF Bridge.

I don't even know if the transmitter portion work or not.

I wonder if codes captured with the above can be sent using RF Bridge.
If yes In what format?
Thanks
BB

**Comment by Jason2866** [comment]
Just as in wiki described for the rf bridge. The standard timing is correct set for protocol 1 (RfSync, RfLow, RfHigh) So the command is 
RfCode  #1..#7FFFFF
Send 24-bit hexadecimal user code using RfSync, RfLow and RfHigh timing

**Comment by badabing2005** [comment]
> 
> 
> Just as in wiki described for the rf bridge. The standard timing is correct set for protocol 1 (RfSync, RfLow, RfHigh) So the command is
> RfCode #1..#7FFFFF
> Send 24-bit hexadecimal user code using RfSync, RfLow and RfHigh timing

Thanks,
Sorry for being thick headed.
I have the captured the following using rc-switch on Tasmota, as I mentioned Sonoff RF bridge doesn't capture my remotes.
```
19:42:54 MQT: tele/nodemcu1/RESULT = {"RfReceived":{"Data":"69ACF4","Bits":24,"Protocol":1}}
19:42:54 RFR: Data 69ACF4 (6925556), Bits 24, Protocol 1, Delay 228
```
How do I translate this to RfSync, RfLow, RfHigh? so that I could send it with Sonoff RF bridge?
Can you tell me what command exactly to type for the example above.

Thanks
BB

**Comment by arendst** [comment]
You can't as the bridge already failed to recognize your remote it also fails to send it's signal. The Bridge hardware just doesn't support your remote.

Regarding how to use the rcswitch output as input for the bridge timing values you will have to deep dive into the rcswitch code to find out the timing values needed.

**Comment by badabing2005** [comment]
Thanks @arendst 
I'm not sure if it failed to recognize, it would also mean it fails to send.

I have multiple remotes, they are all recognized using rc-switch, none of those are recognized using RF Bridge, with Portisch code which supports RC-Switch.
If I bring the remote right next to the RF Bridge, the led turns out and it recognizes some codes, but it's incorrect.

I'm assuming that perhaps the receiver portion is faulty, but that wouldn't necessarily mean that the Transmitter portion is also faulty.
I was hoping that I could test that, but obviously it's not that simple.

I ordered another RF Bridge, which when it arrives should prove if it's the remotes or the Bridge.

Thanks for all the great work you've done on this project, it's amazing.
BB

**Comment by Jason2866** [comment]
You can try
Backlog RfSync 12880; RfLow 420; RfHigh 1270; RfCode #69ACF4
this are the timings from a "1527" device i have captured with the bridge.
Sending this switches the device

**Comment by badabing2005** [comment]
Thank you @Jason2866 

I think we just confirmed that I have a fully defective RF Bridge.
Sending that command does nothing, furthermore neither my arduino, nor my NodeMCU captured anything transmitted by RFBridge

Thanks Again
BB

**Comment by GianCann** [comment]
Good morning and Happy New Year ;)
I've this receiver http://www.mantech.co.za/Datasheets/Products/433Mhz_RF-TX&RX.pdf
This work fine with raspberry and utility base on RCSwitch library that show me the code received with this remote: https://www.ebay.ca/itm/182259352786

I've connect the data pin of the receiver on pin D2 (GPI04) of D1 Mini flashed with latest version of Tasmota (Generic module), and configure this PIN as RFrecv (106).

How do read the code trasmitted from the remote?
Console don't show me anything...

**Comment by andrethomas** [comment]
If wired correctly there is nothing else to do - it should just spit out data as seen in the messages above like

```
13:44:07 MQT: tele/sonoff/RESULT = {"RfReceived":{"Data":"394AC8","Bits":24,"Protocol":1}}
```

Those particular receivers can be a bit picky at times, but they do work. I've gotten the same ones from hobbytronics and micro robotics (although I think that was a RXB6)

**Comment by GianCann** [comment]
I used 3.3v out of the D1 Mini to power the receiver and i've connected data-out of the receiver directly to pind D2.
This is correct?

**Comment by andrethomas** [comment]
Correct yes, except I used 5V to power the 433mhz receiver

image

**Comment by andrethomas** [comment]
Perhaps I should add, with the one you provided the link for the antenna is incredibly important... they are really as bad as can be without a proper antenna (i mean like 5cm distance bad)

The superheterodyne receivers are much more reliable and consistent.

**Comment by kenmcc** [comment]
I wonder if it's a timing issue in decoding the pulses from the io. I've
played with different rf433 receivers in the past, and what works fine on
eg Arduino using rcswitch library doesn't necessarily work on the esp8266,
took some messing with the pulse with duration constants. Not in a position
to dig out code and see what I changed I'm afraid, sorry

**Comment by Jason2866** [comment]
I can say it does work. I have the same rf remote as you have!
Maybe your receiver doesnt work reliable with 3.3V Arduino is 5V.
Over all this typ of rf receiver is cheap and unreliable at all....
Go get a superheterodyne one and it will work! 100% because you will have identic setup than i have 😏

**Comment by GianCann** [comment]
yes @kenmcc it seems a pulse decode problem...
I've load original RS Switch scketch Receive_Demo ( https://github.com/sui77/rc-switch/) on Arduino Nano and no data are output to serial port.
But playing with this code http://mgrigaut.free.fr/arduino/MyReceive_Jolly2.ino and changing the pulse time value, i see something...
image

**Comment by andrethomas** [comment]
All I can say about those receivers as that they are not up to spec - you do not even have an antenna connected?

I use these ones (which are a little more expensive yes) but they just work no matter what you do to them... also they work fine from 3.3V

image

**Comment by bkt92** [comment]
Please help me, how can I use RFsent command with MQTT ?

**Comment by andrethomas** [comment]
@bkt92 further up in this thread... if you look carefuly you might see https://github.com/arendst/Sonoff-Tasmota/pull/2702#issuecomment-437666170

**Comment by bkt92** [comment]
[andrethomas](/andrethomas) Thank you, I just notice the command is RFsend not RFsent, no wonder why I can't sent command via MQTT.

**Comment by andrethomas** [comment]
@bkt92 Using `RFsent` may require some time traveling...

**Pull request closed without merging**
