### PR TITLE
Adding support for Sharp GP2Y10 Dust sensor

### PR DESCRIPTION
**Pull request by remmeha**
## Description:
Readout of Sharp GP2Y10XX dust sensor.
Readout of the sensor takes ~320us. Controlled by GPIO pin. 

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by tnederlof19** [comment]
So where is this PR waiting for? Why isn't this merged?

**Comment by kofec** [comment]
Hi, I tried your code but it was interpreted as Energy monitor :
08:43:20 RSL: SENSOR = {"Time":"2020-04-10T08:43:20","ANALOG":{"Energy":0.002,"Power":20,"Voltage":230,"Current":0.086},"ADS1115":{"A0":0,"A1":0,"A2":0,"A3":0}}

**Comment by kofec** [comment]
OK, I found something. The analog assignment is wrong interpreted:
06:55:47 RSL: SENSOR = {"Time":"2020-04-11T06:55:47","ADS1115":{"A0":3317,"A1":3311,"A2":3310,"A3":3312},"GP2Y10":{"Air quality":48}}

**Comment by kofec** [comment]
Ok, My mistake. I though that order doesn't matter:
```
// User selectable ADC0 functionality
enum UserSelectableAdc0 {
  ADC0_NONE,           // Not used
  ADC0_INPUT,          // Analog input
  ADC0_TEMP,           // Thermistor
  ADC0_LIGHT,          // Light sensor
  ADC0_BUTTON,         // Button
  ADC0_BUTTON_INV,
  ADC0_RANGE,          // Range
  ADC0_CT_POWER,       // Current
//  ADC0_SWITCH,         // Switch
//  ADC0_SWITCH_INV,
  ADC0_GP2Y10,         // Sharp GP2Y10XX Dust sensor
  ADC0_END };
```

**Comment by kofec** [comment]
And I change 
`#define XSNS_66                       66`
because 58 is busy now

**Pull request closed without merging**
