### PR TITLE
Small updates to make the system working locally

### PR DESCRIPTION
**Pull request by mrBussy**
# COM port selection
After compiling I was not able to upload the firmware. Investigating learned that the COM settings where incorrect. I added a README entry to indicate that a developer has to change it to their own setup.

# Custom setting files
When creating multiple devices it is convinient to create multiple configuration files. Added the option to ignore these files using the following structure: user_config_override.*.h

### CODE REVIEW

**Comment by ascillato** [comment]
Hi, sorry but your changes make mandatory the use of user_config_override.h

That is not the case for everyone. 

Better should be to remain the actual config as it is.

**Comment by ascillato** [comment]
Also, this breaks the actual automatic compilation system for the precompiled bins from development branch.

**Comment by ascillato2** [comment]
Closing as this PR makes mandatory the use of user_config_override.h and also breaks the automatic compiling system.

Anyway, thanks for sharing your ideas and we hope you continue doing that.

**Comment by mrBussy** [comment]
You are right. I accedently uploaded a config where the DUSE_CONFIG_OVERRIDE is set. Shall I make a pull request with this issue fixed? Or are you not interested in the changes at all?

**Comment by ascillato** [comment]
It is better to let the user choose which COM port to use and if they want or not to use the USER_CONFIG_OVERRIDE.

**Pull request closed without merging**
