### PR TITLE
Bitwise dev

### PR DESCRIPTION
**Pull request by devanl**
Add commands for bitwise operations on variables to rules:
- & operation for rule trigger
- Or<n> command against Var<n>
- And<n> command against Var<n>
- Msb<n> to get most significant bit set in Var<n>

### CODE REVIEW

**Comment by ascillato** [comment]
Can you please post an usage example?

**Comment by ascillato** [comment]
Hi, can you please post an usage example? In which cases are you using this commands?

**Review by andrethomas — COMMENTED** [review]
I can't think of one - usually bitwise operations are done inside a sensor or driver code.

**Comment by andrethomas** [comment]
I would gladly think about what you're trying to achieve on a non-working day because right now I'm a bit perplexed by the methodology.

Perhaps it will become clear to me in the not so distant future.

**Comment by andrethomas** [comment]
Just attaching this from Discord Chat as to not confuse myself later :)

image

**Comment by ascillato2** [comment]
As the use case explained in Tasmota Chat has another workaround and there is no use case for this new commands, it is added the label **Feature Request (hold over)** for future reference.

If there is any new idea, please ask to reopen this to review new proposals.

Thanks everyone for sharing their ideas!!!! :+1:

**Pull request closed without merging**
