### PR TITLE
Added support to multiple SR04

### LINKED ISSUE #9431: Support multiple SR04 ultrasonic distance sensors
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
No - just need to use 2 SR04 sensors on a single ESP32

**Describe the solution you'd like**  
Support for multiple SR04 sensors like it already is present for buttons, e.g.

**Describe alternatives you've considered**  
Using a separate ESP per sensor would be an alternative, but more expensive and with additional cabling.

**Additional context**  
None

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by jgesser**
## Description:

Added support to multiple SR04 sensors.
Thanks to @belgotux for helping with the tests (https://github.com/arendst/Tasmota/pull/9432#issuecomment-2002438725)

**Related issue (if applicable):** fixes #9431

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
This solution is likely to fail on ESP32 as Tasmota only supports hardware serial on ESP32 and there are at most just three serial uarts available.

Pls test on ESP32 too with four devices and find a workable solution or decrease the amount of advertised devices.

**Comment by jgesser** [comment]
Hi @arendst, thanks for your observation.
I will reduce the maximum of sensor to 3, or even two if you think is better. I need only two and I believe Esp8266 can work only with two if I am not wrong.

Hey @belgotux, I saw on your screenshot a test with 3 sensors on ESP32, is that correct?

**Comment by jgesser** [comment]
MAX_SR04 is now 3.

**Comment by belgotux** [comment]
Hello @jgesser @arendst , I've used 6 pins, they are not all on xx_TXD and xx_RXD and it's working, strange. Don't have more than 3 sensors, but I can buy another one to test. 

Here the pins used :
image
And the configuration with tasmota32 : 
image

I've unplugged my tests but I can test with a D1 mini 4M, to test for esp8266.

**Comment by jgesser** [comment]
Hi @arendst , my sensor arrived today and I was able to successfully connect 3 SR04 to a ESP8266. All of them working independently.
Do you think we can have this PR reviewed and merged?

Please see below images:


Captura de tela 2024-03-22 235005
Captura de tela 2024-03-22 235030

**Comment by jgesser** [comment]
Hi @arendst , my sensor arrived today and I was able to successfully connect 3 SR04 to a ESP8266. All of them working independently.
Do you think we can have this PR reviewed and merged?

Please see below images:


Captura de tela 2024-03-22 235005
Captura de tela 2024-03-22 235030

**Comment by jgesser** [comment]
Hi @arendst , please let me know if there is anything else that I have to do to get this PR approved and merged. 
Thank you!

**Comment by joceliodownloads** [comment]
Is there a firmware version that supports more than one SR-04 with the script module enabled?

**Comment by sfromis** [comment]
I'd expect all builds supporting SR04 to also support up to 3, as long as it is a fresh development build.

**Comment by sfromis** [comment]
Hmmm... Looks like the current implementation is a breaking change to current users of SR04, with payload content like:
`{"Time":"2024-04-05T21:09:41.048+02:00","SR04-1":{"Distance":0.1}}`
Without changing existing rules and other cases of processing sensor data, they will not work.

**Comment by arendst** [comment]
Thought so. Will have a look. Didn't like the duplicated implementation anyway.....

**Comment by jgesser** [comment]
I think it is possible to keep compatibility if when there is only one SR04 it use the old name (without the "-idx" suffix).

**Comment by arendst** [comment]
Yes pls. Provide PR to fix legacy support.

**Comment by jgesser** [comment]
Here is it @arendst / @sfromis :
https://github.com/arendst/Tasmota/pull/21128

I tested here and it works. 
If there is only one SR04 and it is associated with index 1 it will publish the name as "SR04". Otherwise it will be "SR04-<IDX>".

PS.: I didn't change the log messages.

**Comment by jocelioalmeidaset** [comment]
I tested it on the esp8266 and it worked! However, I was unable to collect the data from each sensor individually via script, this script is a very intelligent solution to increase precision and discard invalid readings, which is why it is extremely important to be able to use scripts with data from individual sensors, credits to the Brazilian Daniel Ghisleni

>D
distMin=20.5
distMax=67.6
var=0.5
m:distAnt=0
p:dist=0
quant=0
m:perc=0

>T
dist=SR04#Distance ////////// In this part I was unable to read the sensor, on the console it appears with SR04-1 and SR04-2
if (distAnt==0 or ((dist<distAnt+var) and (dist>distAnt-var))) {
  =#calcular
} else {
  quant=quant+1
  =>print Leitura fora da faixa: %1dist% (ant: %1distAnt%, ocorrência: %0quant%)
}
; 10 leituras fora da faixa atualiza tambem
if quant>=10 {
  =>print %0quant% leituras fora da faixa, atualizando: %1dist%
  =#calcular
}

>W
Custom SR04 Distance{m}%1distAnt% cm
Custom SR04 Percent{m}%2perc% %%

>J
,"Custom":{"SR04":{"Distance":%1distAnt%,"Percent":%2perc%}}

#calcular
distAnt=dist
perc=100-(((distAnt-distMin)/(distMax-distMin))*100)
quant=0

https://youtu.be/e5afpDgdlSs?si=c5Wv5ZDeskB1FMX1

**Comment by sfromis** [comment]
You should enable `SetOption64` to have sensor names with underscore, instead of the hyphen not supported by the scripter. And then you should use the "full name", like `SR04_2#Distance` for the 2nd SR04, and so on.

**Comment by jocelioalmeidaset** [comment]
> Você deve habilitar `SetOption64`nomes de sensores com sublinhado, em vez do hífen não suportado pelo criador de scripts. E então você deve usar o "nome completo", como `SR04_2#Distance`no 2º SR04, e assim por diante.

Thank you very much, it worked perfectly!

**Comment by sfromis** [comment]
Seeing `MAX_SR04` fixed at 3, I came to think of the detail that only ESP32-S3 and original ESP32 has 3 hardware UART controllers, the other variants only have two. Of course, using USB CDC takes away one of them. Not sure if the ESP32-SOLO-1 even has two, the data sheet only talk about it in singular, but this variant is likely not too interesting.

With ESP8266 software serial, it could also be possible to allow more than 3 on this legacy platform (not that I'd want to use such).

**Comment by arendst** [comment]
Not all SR04 use a serial interface. Some use bitbanging by lib NewPing.

Let them (the users, desperate for more SR04 devices support) encounter the intricacies of different processor hardware and SR04 device types. There was a reason I only supported one of SR04....

**Pull request merged**
