### PR TITLE
Added missing text

### PR DESCRIPTION
**Pull request by mike2nl**
Added missing text define.
Typical copy and paste error while online done on github

Sorry Theo, next i will take more acre on that.

### CODE REVIEW

**Comment by mike2nl** [comment]
Theo,
sorry to nery you again ;-) but i don't know hoa i can reach you.
So far i know you use the Wemos D1 mini and you have wiritten that part in the wiki.
Have learned some things from.

Now i have more then one ;-) Wemos D1 R1 and R2 and next week a atmega + esp8266 (UNO + Wemos D1) on one board or better 2 boards for the first tests:
https://nl.aliexpress.com/store/product/UNO-WiFi-R3-ATmega328P-ESP8266-32Mb-memory-USB-TTL-CH340G-Compatible-for-Arduino-Uno-NodeMCU-WeMos/1950989_32806748844.html?spm=a2g0z.12010612.8148356.15.16de4f67qs8Jne

I would add information, links and images possible linked from my repo too. 
So others can build on that experience.
Is that OK for you?

**Comment by arendst** [comment]
You can reach me vie the link on the Github main page.

I send an email to lego.with.no.limits… but I'm not sure you received it.

Yes just add to the wiki.

**Comment by localhost61** [comment]
@mike2nl  what means the UV level OoR? Can I translate with Extrem ???

**Comment by localhost61** [comment]
I've got a NodeMCU v3 too (30pin) and use it to poll Energy meters on modbus. I managed* to connect a RS485 adapter on pin GPIO15 & GPIO13 but I believe it uses a software serial. I didn't see in TasmotaSerial that Serial 0 could be affected to those pins as Serial 2. Does it?

* I just had to remove the 4k7 pullup on the TxD pin of the adapter in order to let the ESP8266 boot.

**Comment by ascillato** [comment]
OoR: Out of Range

**Pull request merged**
