### PR TITLE
add options for INA3221 driver

### PR DESCRIPTION
**Pull request by fb-pilot**
## Description:
more defines for sensor100 INA3221 driver and extend documentation
**Related issue (if applicable):** fixes #21262

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [ ] The code change is tested and works with Tasmota core ESP32 V.3.0.0
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by fb-pilot** [comment]
here we go - as discussed with the driver

**Comment by barbudor** [comment]
1) there is a typo in `NA3221_SUPPLY_SIDE`
2) INA3221_SUPPLY_SIDE dos nothing, not implemeted in the driver
3) Although I understand what you wanted to do and would see no issue with implementing that work mode, DO NOT CHANGE THE DEFAULT BEHAVIOR as this is a breaking change for other users. Do it in a way that it can be changed in `user_config_override.h` only for those interrested

**Comment by fb-pilot** [comment]
changed ...
What do you mean with "not implemeted in the driver" ?
Is something messed up ?

**Comment by fb-pilot** [comment]
I think we also should change the title .... but have no idea how to !?

**Comment by barbudor** [comment]
As I commented in your PR, the PR title was not referring INA3221 so I hadn't had a change to review it before it is merged and your changed were not visible on my computer

I'll now review your PR and still comment

**Comment by barbudor** [comment]
Owner of the PR should see an edit button on the right of a PR title

**Review by fb-pilot — COMMENTED** [review]
I am just struggling with the tool.
I wanted to open another PR with my modification of QMC5883L driver - but messed it to the still open one.
disreguard that
Am I able to open a parallel PR - and how ?

**Comment by barbudor** [comment]
You need to learn how to use git and branches

**Comment by fb-pilot** [comment]
> You need to learn how to use git and branches

I see .... I am completely lost now :-((

**Pull request closed without merging**
