### PR TITLE
APDS-9960 - Improve gesture

### PR DESCRIPTION
**Pull request by Theosakamg**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

* Add gesture on web interface
* Enable/Disable Gesture in binary with APDS9960_GESTURE (reduce of 2k)

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core Tasmota_core
  - [x] The code change is tested and works on core ESP32
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
What is the benefit for doing a breaking change?

**Comment by Theosakamg** [comment]
This chip provide 3 features :
- Proximity engine
- Color engine
- Gesture engine (~2k)

and required ~4K on flash

But actually the driver provide 2 modes (exclusive):  Proximity + Color OR Gesture (by default)
If user would like to use ambient light sensor feature, like than BH1750 / MAX44009 and save flash space. He can disable this feature directly on binary.

_NB : I made the modification step by step.
I think in other PR, make refactoring the code to remove many #ifdef_

**Comment by Jason2866** [comment]
You are now disabling a feature which is by default active.
Breaks with no need user installations.

**Comment by Theosakamg** [comment]
My apologies ! I removed option for the test and forgot to put it back.

I do not wish to deactivate this function by default.

**Pull request merged**
