### PR TITLE
read tariffs from ornowe517

### PR DESCRIPTION
**Pull request by woojtekk**
First of all I would like to thanks for provide module for this energy counter. Since I already have this energy meter this module really made my approach to energy monitoring and management easier and easier 
ORNO-WE-517 energy poses possibility to program 4 different tariff (at the moment only via original software via rs485). Therefore I would like to present some changes that allow to read the set tariffs and publish it via MQTT as well as directly on device webpage.

xnrg_17_ornowe517.ino
-	Added registers for tariffs 1 and 2. (The energy meter can be programmed into 4 different ones)
-	Modified switch case function to check register and not the position of register in array is much convenient and is more transparent in comparison to previous method (in my opinion)
-	I am not sure which method  is faster but both works ;)

### CODE REVIEW

**Comment by woojtekk** [comment]
I'm just starting my adventure with GitHub and somehow miss to fill Checklist. Ima sorry for that. 
For all my changes checklist is the same as below: 

Checklist:

[X] The pull request is done against the latest development branch
[X] Only relevant files were touched
[X] Only one feature/fix was added per PR and the code change compiles without warnings
[X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
[  ] The code change is tested and works with Tasmota core ESP32 V.2.0.1

[X]    I accept the CLA.

NOTE: The code change must pass CI tests. Your PR cannot be merged unless tests pass

**Comment by barbudor** [comment]
Why have you split the PR in so many parts?
Can't you just make 1?
Are those PR independent?

**Comment by woojtekk** [comment]
Those PR are related with the same. Thats my fault and I am sorry for this. To be honest it's my first request and I didn't known how to do it in proper way. that's why I am asking for understanding.

Proposed changes are working on esp8266 and since they are not depend to platform should also work with esp32.

Currently I am trying send data via morbus to energy meter in order to set time and program tariff periods. Next PR will be submitted in proper way.

Greetings

**Comment by arendst** [comment]
Thx.

First - Have you looked at the already available tariff functionality in Tasmota. If so what makes this solution better.
Second - Clean up the four PR's and make one PR for review

**Pull request closed without merging**
