### PR TITLE
Update "minimal text" for he-HE and update fr-FR to 6.5.0.7

### PR DESCRIPTION
**Pull request by localhost61**
## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [ ] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works.
  - [X] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Looks messy....

No files changed.

**Comment by localhost61** [comment]
Sorry, forgot to commit locally before push.

**Comment by localhost61** [comment]
Shouldn't `firmware.map` be in `.gitignore` ?

**Comment by arendst** [comment]
Yes. Just did. Thx.

**Pull request merged**
