### PR TITLE
User Timers

### PR DESCRIPTION
**Pull request by flexiti**
**`I sent it from a temporary git repository that I have already removed (maybe too fast ), if there are any problems I can re-publish.`**  :wink: 

#define USE_USERTIMERS              //Local timers funcionality active
  ;;; if not defined, there is no user timers, only config memory is alocated for future compatibliity
  ;;; **no extra code is generated if not defined**

#define USE_USERTIMERSWEB            // view user timers on WEB
  ;;; timer are programed via MQTT, if this define is active, also via WEB interface
  ;;; user timer code is generated , without web code

#define MAX_USERTIMERS       16      // fixed configuration memory max size , do not change it
  ;;; fixed max config size

#define USED_USERTIMERS      8       // realy used timers 1 to 16
  ;;; actualy used timers 8

_13:09:54 MQT: main/sonoff/33/tele/STATE = {"Time":"2017-10-29T13:09:54", "Uptime":0, "POWER1":"OFF", "POWER2":"OFF", "Wifi":{"AP":1, "SSId":"T100", "RSSI":90, "APMac":"00:1E:8C:CE:F7:93"}, "UTimers":8}_
  ;;; "UTimers":8 menas that we have used 8 timers ( info for other apk)

_13:29:35 MQT: main/sonoff/33/tele/INFO1 = {"Module":"Witty Cloud", "Version":"5.8.0p", "FallbackTopic":"DVES_CD0211", "GroupTopic":"sonoffs", "UTimers":"8"}_
  ;;; the same at startup module info

Command:
Topic: **UTimer5**    
Payload:     **{"UTimer":{"UTrelay":2, "UTtime":"09:23","UTmode":1,"UTday":"21","UTonce":1}}**
(Not all parameters must be specified)
  ;;; Command UTimer1 ... UTimer(USED_USERTIMERS)
  ;;; UTrealy = Relay no
  ;;; UTtime = action time
  ;;; UTmode = action type: 0 -nop, 1 -on, 2 -off
  ;;; UTday = day (2 digits Hex value, bit 0 - Mon, bit 1 Tue,... 
  ;;; UTonce = one time action if 1, after that mode automaticly set to nop

Validation of the entry is weak, but it does not have bad affect to the sonoff.
You can add something here , For example, the time must only be in 06:30 format, not 6:30, but we use less memory  :wink:

13:10:03 CMD: **UTimer1**
  ;;; Timer status
_13:10:03 MQT: main/sonoff/33/stat/RESULT = {"UTimer":{"No":1, "UTmode":"1", "UTtime":"12:11", "UTrelay":"1", "UTonce":"0", "UTday":"41"}}_
  ;;; answer
User timer number 1, will on relay1 at 12:11  every monday and sunday

### CODE REVIEW

**Comment by zerog2k** [comment]
+1 on this... was just looking through the codebase and issues to see if tasmota had schedule/timer support without explicit need for external command input

**Comment by lgnd33** [comment]
+1

While I don’t have a use case for timers, I would like to see feature rich Tasmota. 

While code space might be a concern, I don’t believe in universal images and think everyone should compile their own image with settings and modules they actually need. 

In the end, if someone really needs everything, we might want to work on automated 2-step upgrade procedure (minimal+full) to break past infamous 512kb limit.

//_ on phone

**Comment by roblad** [comment]
Hi,

Do you plan to add timer for relays ?

**Comment by arendst** [comment]
Nope. Not at this time.

**Comment by roblad** [comment]
Hi,

Do you plan to add status of switch button state without relays set ? 
see that
https://github.com/arendst/Sonoff-Tasmota/issues/1265

I discovered issue with Wemeos, that no commands button options not works at all either button or switch, I canot switch to AP reset to default etc.

**Comment by davidelang** [comment]
what sort of timer are you looking for?

we already have a timer to shut off a relay after a specific time (see 
pulsetime)

other than that, you are probably better off doing the timing with your home 
automation system.

**Comment by roblad** [comment]
Hi,

It nice to have autonomus device, scheduler is always extent :-), BTW haw to use that timer set to relay start or stop after some period time i.e. 15 min after switch on, automaticaly switch off after that period time.

**Comment by davidelang** [comment]
On Wed, 29 Nov 2017, roblad wrote:

> It nice to have autonomus device, scheduler is always extent :-)

True, but the code space is limited, and the mission of Tasmota is not to do 
everything possible, but to allow a MQTT server to control everything possible

> , BTW haw to 
> use that timer set to relay start or stop after some period time i.e. 15 min 
> after switch on, automaticaly switch off after that period time.

this is exactly what pulsetime does.

**Comment by roblad** [comment]
Hi,


Haw to set for 15 min 


112..64900 | Set PulseTime for relay<x> with 1 seconds increment starting with 12 seconds (113 = 13 seconds etc.)

**Comment by davidelang** [comment]
On Wed, 29 Nov 2017, roblad wrote:

> Haw to set for 15 min
>
>
> 112..64900 | Set PulseTime for relay<x> with 1 seconds increment starting with 12 seconds (113 = 13 seconds etc.)

15 min is 900 seconds, so 112+900=1012, set pulsetime to 1012 and it will turn 
off after 15 minutes

**Comment by roblad** [comment]
Hi,

I did not think about it :-)
 thanks

**Comment by ortegafernando** [comment]
+1

**Comment by JPSINHA** [comment]
I am new user of Sonoff. I loaded the TASMOTA on my 4Ch Sonoff.
I want to use timer switching.
For it I tried to paste the code in   i18n.h.
 But at time of uploading some error message came .
 How solve the problem?
 What is actual way to configure timer.

**Comment by pvtien7** [comment]
@flexiti  can you send me complete code for sonoff basic ??? i had changing code but error on arduino. thanks !!!

**Comment by ascillato** [comment]
@flexiti, I also want the code. Thanks

**Comment by flexiti** [comment]
The code was complete for the previous tasmota  version, now there are some conflicts.
It works, I use it to control heating and lighting when energy is cheaper.
I could adopt it to this version, but the owner of Tasmot did not want it :)
_**roblad** commented on 28 Nov 2017
hi,
Do you plan to add timer for relays?
**arendst** commented on 28 Nov 2017
Nope. Not at this time._

I suppose that new patterns for colored leds chains are more important ;)

If there is a demand, I can publish it in my fork

**Comment by pvtien7** [comment]
@flexiti  if it's published in your fork, that wonderful

**Comment by flexiti** [comment]
It is published on:

https://github.com/flexiti/Sonoff-Tasmota  branch **usertimers**
(It is forked from https://github.com/JacekDob/Sonoff-Tasmota)
Works on ESP8266 and ESP32
(ESP8266 compiled using Platformio, ESP32 compiled using Arduino)

Do not use //**#define ONOFF_TEMPERATURE_LOWHIGH**    // timer on/off is temperature dependent 
it is my use for heating ;)

**Comment by ascillato** [comment]
Hi @arendst,

I have automated my patio watering for irrigation of my plants but there, my wifi is weak. So, using Home Assistant to tell Sonoff Tasmota to open valves is not an option. One solution can be using timers like the ones proposed by @flexiti. Timers are an alternative. Can be added this feature to the main version as an optional?

I tested that version and works but would be great to have that on the main tasmota :smile:

**Comment by on-off-on** [comment]
Is there relly no way to force the implementation of a timer in the "original" repository a simple timer function based on a electronic timer? :-// It would be a great feature for users like me to have "one" firmware to switch with commands from a controller e.g. FHEM and a simple timer function within the unit for areas without WLAN or LAN-access. I would like to have a timer for security reason during my holiday.... without connection to FHEM-controller...
The forked timer doesn´t work and I´m unable to find the issue :-/

**Comment by arendst** [comment]
Convinced.

I'll start working on timers keeping in mind the current @flexti implementation as documented in this PR but as a separate xdrv_09_timers.ino file.

Stay tuned...

**Comment by ascillato** [comment]
Great! Thanks a lot!

**Comment by ionciubotaru** [comment]
Timers are great and useful. Please consider replacing `Device` with `backlog`., because it's great flexibility.
Instead of `Timer1 {"Arm":1,"Time":"09:23","Days":"--TW--S","Repeat":1,"Device":1,"Power":1}` 
use: `Timer1 {"Arm":1,"Time":"09:23","Days":"--TW--S","Repeat":1,"backlog":"power1 1;power2 0;power3 2"}`

**Comment by arendst** [comment]
@ionciubotaru Nice idea but would take too much storage as the backlog string will need to be cached. So for now you will have to setup three different timers. That's why you have sixteen of them :-)

**Comment by on-off-on** [comment]
Many thanks!!! for the timerfunction -it works great 👍 

At time I have teo newbie questions:
-whats the correct way to delete an added timer entry?
-is in the GUI an entry for "timer" planned -as listed in the first thread of /1091?  that the timer is available for "everyone"?

**Comment by arendst** [comment]
To "delete" a timer you could set Arm to disable (0) or in the next release use command ``Timer<x> 0`` to clear all values of the timer. This release will also allow copying timers with command ``Timer<x> 1..16``

**Comment by ascillato** [comment]
Works Great!!!

Thanks!! :+1:

**Comment by apastuszak** [comment]
Is this implemented in the current 5.12 release?  I'm seeing a timer option in the menu?

**Pull request closed without merging**
