### PR TITLE
[SML] Serial activity monitor via LED

### PR DESCRIPTION
**Pull request by SteWers**
## Description:

Visualize the activity of one or all serial meters via LED. It is helpful for debugging and also for viewing serial activity easily. The configuration is done via console commands:

- LED-GPIO for monitoring serial activity => sensor53 l2, l13, l15 ... or l255 for turn off (default)
- meter number for monitoring serial activity => sensor53 m1, m2, m3 ... or m0 for all (default)

To start at boot-time, add the entries in the boot-section (>B) of the script.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
It doesn't feel natural for me to define a Led GPIO from a command.
Why not defining a dedicated "SML Led" to be used in template/configuration ?

**Comment by SteWers** [comment]
In general I agree with you. I thought about an extra pin via template. The cause, because I decided for the other way, is because all other configuration for SML (counter/meter) is done via script. So there are no different points, where the configuration has to be done.

**Comment by barbudor** [comment]
I'm not really versed into Scripting so I trust on that 😀

**Comment by gemu2015** [comment]
i agree with @SteWers .
SML is descriptor based and completely decoupled from Tasmota GPIO definition.
so this solution is feasible.

**Pull request merged**
