### PR TITLE
Support unique MQTT topic (configured topic suffixed with chip ID)

### PR DESCRIPTION
**Pull request by emontnemery**
As discussed in #1630. I think it's useful, and it requires only very small code changes.

### CODE REVIEW

**Comment by davidelang** [comment]
Why is the fallback topic not good enough?

**Comment by emontnemery** [comment]
Because it does not work for telemetry and hass discovery.

**Comment by davidelang** [comment]
it can be used for a scripted method to change the main topic.

hass discovery is a reasonable issue, I don't know what it needs.

**Comment by SGF-Lon** [comment]
I would be in favour of this going ahead & being implemented.  Are you suffixing it with the 4 character decimal "characters" or the 6 digit Hex characters?  I am currently using the 4 character decimal "characters" and would like to stay with that naming convention.  Will that be possible with this mod?

**Comment by emontnemery** [comment]
@SGF-Lon I'm using the 6 digit hex characters.
The issue with the 4 digit decimal number (or in reality, 0..8192, since it's a larger number truncated to 13 bits) is that there is a 50% chance for a collision already with 100 devices (birthday paradox). For hostname that doesn't really matter since dhcp-server will handle collisions, but for the mqtt topic there is no arbiter.
With the 6 digit hexadecimal you must reach around 5000 devices to have such high collision risk (and maybe there is no collision risk anyway since the hex number is simply the SoC's serial number).
Having said this, i could update the PR to support both cases?

**Comment by SGF-Lon** [comment]
@emontnemery Good points.  I probably won't have 100 devices within
my home (!) - but somebody might.  So, your approach is best.  If you
can support both by some simple usage of the editing characters (i.e
%04d versus %06X) - or something like similar - that would be
fantastic.  Otherwise, I guess I will end up converting to 6 digit
suffixes.  Thanks.

On Thu, 25 Jan 2018, at 19:28, emontnemery wrote:
> @SGF-Lon[1] I'm using the 6 digit hex characters.
>  The issue with the 4 digit decimal number (or in reality, 0..8192,
>  since it's a larger number truncated to 13 bits) is that there is a
>  50% chance for a collision already with 100 devices (birthday
>  paradox). For hostname that doesn't really matter since dhcp-server
>  will handle collisions, but for the mqtt topic there is no arbiter.>  With the 6 digit hexadecimal you must reach around 5000 devices to
>  have such high collision risk (and maybe there is no collision risk
>  anyway since the hex number is simply the SoC's serial number).>  Having said this, i could update the PR to support both cases?


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/sgf-lon
  2. https://github.com/arendst/Sonoff-Tasmota/pull/1684#issuecomment-360573519

**Comment by emontnemery** [comment]
@SGF-Lon OK, I updated as you suggest.

**Comment by emontnemery** [comment]
I don't get why there are linker errors due to `strcspn` and `strspn` in the travis build :(

**Comment by drbeat** [comment]
maybe missing <string.h> ?

**Comment by arendst** [comment]
I've managed to find support for strcspn and strspn but version 2.3.0 printf is not compatible either as can bee seen here:
```
topic
15:01:11 CMD: topic
15:01:11 RSL: Group 0, Index 1, Command TOPIC, Data 
15:01:11 MQT: stat/%.*s/RESULT = {"Topic":"wemos6"}
mqttclient
15:02:21 CMD: mqttclient
15:02:21 RSL: Group 0, Index 1, Command MQTTCLIENT, Data 
15:02:21 MQT: stat/%.*s/RESULT = {"MqttClient":"DVES_%06X"}
```
Where is says in 2.4.0
```
topic
15:07:13 CMD: topic
15:07:13 RSL: Group 0, Index 1, Command TOPIC, Data 
15:07:13 MQT: stat/wemos6/RESULT = {"Topic":"wemos6"}
mqttclient
15:10:12 CMD: mqttclient
15:10:12 RSL: Group 0, Index 1, Command MQTTCLIENT, Data 
15:10:12 MQT: stat/wemos6/RESULT = {"MqttClient":"DVES_%06X"}
```
Considering the amount of issues with 2.4.0 I still want support for 2.3.0. 

So without the correct snprintf_P support this will not be integrated in Tasmota.

**Comment by arendst** [comment]
Will be in next pre-release together with #1871

**Comment by arendst** [comment]
It's in 5.12.0b

**Pull request closed without merging**
