### PR TITLE
initial webcam support

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

support for ESP32 CAM
Initial version supports up to 4 jpg pictures shown on webpage
interface is through scripter cmds.
will update scripter doku when merged 

#define USE_WEBCAM

must change ESP32 board to esp32cam to get support for 4 Mb SPIRAM

webcam interface:

res=wc(selector par)

selector
0 = init webcam
1 = get frame into buffer N (1-4) negativ number free memory of buffer
2 = set picture size (default = FRAMESIZE_CIF)
    0 = FRAMESIZE_96x96,    // 96x96
    1 = FRAMESIZE_QQVGA,    // 160x120
    2 = FRAMESIZE_QQVGA2,   // 128x160
    3 = FRAMESIZE_QCIF,     // 176x144
    4 = FRAMESIZE_HQVGA,    // 240x176
    5 = FRAMESIZE_240x240,  // 240x240
    6 = FRAMESIZE_QVGA,     // 320x240
    7 = FRAMESIZE_CIF,      // 400x296
    8 = FRAMESIZE_VGA,      // 640x480
    9 = FRAMESIZE_SVGA,     // 800x600
    10 = FRAMESIZE_XGA,      // 1024x768
    11 = FRAMESIZE_SXGA,     // 1280x1024
    12 = FRAMESIZE_UXGA,     // 1600x1200
    13 = FRAMESIZE_QXGA,     // 2048*1536

3 get picture width
4 get picture height

in section >W
you can show webcam picture with providing w and h are preset 
\>W
\webcam image

sample script

\>D
res=0
w=0
h=0

\>B
; init cam
res=wc(0)
print init wc =%res%
; set picture size
res=wc(2 6)
; get dummy picture
res=wc(1 0)
; get h and w
w=wc(3)
h=wc(4)
print %w% - %h%

delay(500)
; store pic in buffer 2
res=wc(1 2)

; set flash led to output
spinm(4 1)

\>S

if upsecs%5==0
then
; flash led ON
spin(4 1)
; get picture to buffer 1
res=wc(1 1)
print frame size=%res%
; flash led OFF
spin(4 0)
endif

\>W
; show 2 pictures
\webcam image
\webcam image

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core Tasmota_core_stage
  - [] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Thanks for your PR.

To be able to add new features to ESP32 devices I changed the inbuilt template and module support. The idea is that programmers provide a template as with the ESP8266 containing the needed GPIO config and if needed add a module name to file ``tasmota_template_ESP32.h``. I already added the ``ESP32_CAM_AITHINKER`` module for you to use for integration the current PR. 

Pls have a try implementing the different camera GPIOS using a template and catch the required code changes using ```
if (Settings.module==ESP32_CAM_AITHINKER) {	
        webcam_setup();	
      } 
```
like you did in the original PR.

**Comment by gemu2015** [comment]
ok while implementing this i realized that GPIO36 is not configurable as needed. It is a camera pin Y8

**Comment by arendst** [comment]
You're right. I will need to rethink my ADC functionality. Bugger.

**Comment by gemu2015** [comment]
ok i implemented it, couldn't test yet because of pin 36
i corrected the template but it is modified wenn trying to apply.
 
{"NAME":"AITHINKER CAM","GPIO":[206,255,255,255,255,216,255,255,255,255,255,255,215,214,0,213,219,218,0,217,207,208,0,0,0,0,204,255,210,209,212,0,0,211],"FLAG":15,"BASE":1}

to choose without a template and use aithinker i did a #define USE_TEMPLATE at the beginning of webcam.ino

**Comment by gemu2015** [comment]
template is now configurable
however when i select the template weird things happen
webcam even when not set by template no longer works, 
WEBUI shows some power meter output like voltage,  power  

new AITHINKER template
[206,255,255,255,255,216,255,255,255,255,255,255,0,0,215,214,0,213,219,218,0,217,207,208,0,0,0,255,204,7,210,209,212,0,0,211],"FLAG":7,"BASE":1}

**Comment by gemu2015** [comment]
now with latest tasmota  the camera template works!

**Comment by arendst** [comment]
Great. 

Still thinking about how to handle the abundance of new GPIO definitions as the current uint8_t of max 256 is almost full. A change to uint16_t would be the most obvious solution.

**Comment by gemu2015** [comment]
yes uint16_t will never overflow (hopefully)
i the meantime i have mailing pictures ready, Shall i update this pr or do that in a later release?

**Comment by arendst** [comment]
Pls do an additional PR later as I want to have the basics ready first.

**Comment by gemu2015** [comment]
i think it is better to close this pr and make a new one when the pin handling is complete.
I have updated to current Tasmota and adapted the changes.

**Comment by tonilopezortiz78** [comment]
What about if you want to stream the video or pictures to your server (digital ocean or AWS)?
Anyone is working on that?
thanks

**Pull request closed without merging**
