### PR TITLE
scripter esp32 flash file ffat support

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

adds flash file FFAT support for ESP32
added 2 linker files

for 4mb flash
esp32_partition_app1572k_ffat983k.csv
for 16mb flash  (e.g.TTGo watch)
esp32_partition_app1984k_ffat12M.csv

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.3.2
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@gemu2015  considering to support littlefs with ESP32?
https://github.com/espressif/arduino-esp32/tree/esp32s2/libraries/LITTLEFS

**Comment by gemu2015** [comment]
@Jason2866 
I will wait until littlefs is part of Arduino ESP32 release and available in Tasmota. 
(https://github.com/espressif/arduino-esp32/tree/idf-release/v4.2 branch has it)
it is a quick adaptation when it will be available.

**Comment by Jason2866** [comment]
I ask because i do the customized Tasmota framework builds for ESP8266 and ESP32
If you want that the littlefs is included in next Tasmota framework ESP32 i will add.
It is up to you to decide :-)
LittleFS is not included in the upcoming official release 1.0.5. (based on IDF3.3)
https://github.com/espressif/arduino-esp32/releases/tag/1.0.5-rc2

**Comment by gemu2015** [comment]
i don't consider it to be urgent. ESP32 currently uses FFAT(not SPIFFS) which is OK
so lets wait until it is part of the official release.

**Comment by Jason2866** [comment]
Okay, you are the only one using file systems.

**Pull request merged**
