### PR TITLE
Add units to comments for temp & pressure

### PR DESCRIPTION
**Pull request by mhansen**
Reverse engineered what units these are from looking at the code.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core ESP8266 V.2.7.1
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

There's no change to test, this is comments-only.

### CODE REVIEW

**Comment by arendst** [comment]
Alas. This is too generic.

Temperature can be Celsius or Fahrenheit depending on SetOption8 set. Same for pressure. It can be hPa or mmHg depending on SetOption24

It's better you scan the tele messages which inlude the correct unit type.

**Comment by mhansen** [comment]
Thanks for the guidance - good to know as I was incorrectly assuming these were Celsius!

**Comment by mhansen** [comment]
I did a bit of digging, and filed https://github.com/arendst/Tasmota/issues/8808, it looks like `global_temperature` is used as Celsius in all but one place.

**Comment by mhansen** [comment]
Filed https://github.com/arendst/Tasmota/issues/8810 for figuring out the units of `global_pressure`.

**Pull request closed without merging**
