### PR TITLE
process Backlog commands without minimum delay

### PR DESCRIPTION
**Pull request by ljakob**
## Description:

improve latency processing rules with multiple commands via Backlog

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] tested on v6.6.0
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
This brakes backward compability and for some commands a delay is necessary (rf bridge)

**Comment by ljakob** [comment]
> This brakes backward compability and for some commands a delay is necessary (rf bridge)

what do you propose? I've no problem keeping that patch locally. I needed a solution where rules with a couple of commands are processed without noticeable delay.

**Comment by Jason2866** [comment]
The idea for the possibility to have no delay in between backlogs commands is fine.
For a 100% solution it needs to behave like before and with a (new) Setoption to change to minimum delay.
Anyway, It is up to Theo to decide!

**Comment by andrethomas** [comment]
Perhaps this can be set to a default of 2 and user modified from `my_user_config.h`

I don't think it warrants wasting a setoption location for something that would not necessarily need to be changed during runtime - I think being able to set this prior to compile would be sufficient.

**Comment by ascillato** [comment]
Agree

**Comment by laurentdong** [comment]
I like the idea that have an adjustable Setoption for backlog delay time. It would be better to have the setting by ms instead of 100ms. In order to keep the backward compatibility, the default value could be 200.

**Comment by arendst** [comment]
Phase 1

**Comment by arendst** [comment]
And phase 2.

Everybody happy with command SetOption34 0..255 to set backlog delay. Default stayed at 200 mSec

**Comment by andrethomas** [comment]
@arendst You're the only one that **_HAS_** to be happy but I am sure others are also :)

**Comment by Jason2866** [comment]
Happiness all around 😀
Thx!

**Pull request merged**
