### PR TITLE
Read from ACCMODE register

### PR DESCRIPTION
**Pull request by pauloamexio**
Read from ACCMODE Register to check if the reactive power and active power are positive and negative (for both channels)

Discussion link: https://github.com/arendst/Tasmota/discussions/12861

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.1.0.7.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx.

Did some refactoring to save 40 precious code bytes.

**Comment by pauloamexio** [comment]
Ok :) 
Tomorrow I will test with your modifications (right now the solar panels production are low ).

**Comment by pauloamexio** [comment]
Hello, 

Test this morning with the new modifications and it's working well :)

image

**Comment by arendst** [comment]
Thx for the feedback.

**Pull request merged**
