### PR TITLE
Fix regression build flags

### PR DESCRIPTION
**Pull request by Jason2866**
from #8932

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota stage core ESP8266 V.2.7.3.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
I still don't like it:
```
C:\Users\Theo\.platformio\packages\framework-arduinoespressif8266@src-d400979fef2d7d7efe8a9f0e5249340c\libraries\Ticker\src/Ticker.h: In member function 'void Ticker::attach(float, void (*)(TArg), TArg)':
Retrieved `C:\Temp\.pioenvs\tasmota\lib932\bearssl-esp8266\rsa\rsa_default_pubexp.c.o' from cache
C:\Users\Theo\.platformio\packages\framework-arduinoespressif8266@src-d400979fef2d7d7efe8a9f0e5249340c\libraries\Ticker\src/Ticker.h:78:32: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
Retrieved `C:\Temp\.pioenvs\tasmota\lib932\bearssl-esp8266\rsa\rsa_i15_keygen.c.o' from cache
 #pragma GCC diagnostic ignored "-Wcast-function-type"
Retrieved `C:\Temp\.pioenvs\tasmota\lib932\bearssl-esp8266\rsa\rsa_i15_modulus.c.o' from cache
                                ^
Retrieved `C:\Temp\.pioenvs\tasmota\lib932\bearssl-esp8266\rsa\rsa_i15_oaep_decrypt.c.o' from cache
C:\Users\Theo\.platformio\packages\framework-arduinoespressif8266@src-d400979fef2d7d7efe8a9f0e5249340c\libraries\Ticker\src/Ticker.h: In member function 'void Ticker::attach_ms(uint32_t, void (*)(TArg), TArg)':
Retrieved `C:\Temp\.pioenvs\tasmota\lib932\bearssl-esp8266\rsa\rsa_i15_oaep_encrypt.c.o' from cache
C:\Users\Theo\.platformio\packages\framework-arduinoespressif8266@src-d400979fef2d7d7efe8a9f0e5249340c\libraries\Ticker\src/Ticker.h:89:32: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
Retrieved `C:\Temp\.pioenvs\tasmota\lib932\bearssl-esp8266\rsa\rsa_i15_pkcs1_sign.c.o' from cache
 #pragma GCC diagnostic ignored "-Wcast-function-type"
```
Warnings I didn't have before.

**Comment by Jason2866** [comment]
Agree. I will post in Arduino github. Core 2.7.3 is not ready for release.

**Comment by Jason2866** [comment]
https://github.com/esp8266/Arduino/issues/7458#issuecomment-660632510

**Comment by Jason2866** [comment]
@arendst  Messed up something with git commands in my fork. The orig. Arduino branch core 2.7.3 works without a warning.
Will rebuild. No change needed in Tasmota setup. "Just" have to correct my fork and setup

**Pull request merged**
