### PR TITLE
Zigbee add EZSP 6.7.8 as Release Candidate firmware

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Added Sonoff-signed EZSP v6.7.8 which is now our Release Candidate to solve the issue with IKEA battery drain.

EZSP v6.5.5 was moved to archive.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by MattWestb** [comment]
`ncp-uart-sw_6.7.6_115200.ota` - recommended stable version for EZSP v6, EZSP v7, and EZSP v8 compatible hosts.`

Its not true its only v8 (therefore we was getting the 6.5.5 for v7 and older hosts).

**Comment by s-hadinger** [comment]
Correct. I will fix that when we push v6.7.8 as recommended version

**Comment by MattWestb** [comment]
Great !!
I trying getting the ZHA users not storming to installing it if getting problems.
But if its some brave ones is doing it then its its good getting some beta testing done 2 :-)))

**Comment by MattWestb** [comment]
One more thing if / then the 6.7.8..0 is being stable and recommended version i think it can being good implanting one warning if the device is running on not recommended version in the log so the user not running on wrong version by "mistake". 
Is it also possible query if original firmware is running by the hex string its sending on NCP reboot ?

**Comment by s-hadinger** [comment]
@MattWestb Good suggestion.

The version of EZSP is already displayed in the logs
`MQT: tele/tasmota/ZBBridge/RESULT = {"ZbState":{"Status":55,"Version":"6.7.8.0","Protocol":8,"Stack":2}}`

But adding a warning on the UI will be a good thing.

**Pull request merged**
