### PR TITLE
Update de-DE.h

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core pre-2.6
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by curzon01** [comment]
Suggest "Gesamtverbrauch" instead of "Gesamtnutzung" might be more common for "Total Usage".

When still using special char like for Ω unit "Ohm" for string constant like D_UNIT_KILOOHM it might be transformed in modern browsers, not on older on. If decission is to keep that can also be used for µ, m³... as they are all double byte UFT?

**Comment by Jason2866** [comment]
Hallo Norbert, i changed Ohm to Ω, because µ is already used in the language file.
Will change "Gesamtnutzung" to "Gesamtverbrauch"

**Comment by ascillato** [comment]
I prefer also the Ω instead of Ohm, but for non-technical people would be better the ohm letters approach, because using the symbol they won't be able to read that (mmm, it says 3.5 little arcs :rofl: )

**Comment by Jason2866** [comment]
Non technical people will never see the Ω in Tasmota ;-)

**Comment by meingraham** [comment]
> ( mmm, it says 150 little arcs 🤣 )

150 little horseshoes :wink:

**Pull request merged**
