### PR TITLE
LVGL library updated to v9.0.0, some small breaking changes in C, none in HASPmota

### PR DESCRIPTION
**Pull request by s-hadinger**
### **MAJOR LVGL UPDATE** to v9.0.0

Changes to the `C` interface are described here: https://docs.lvgl.io/master/CHANGELOG.html

It should be minor changes since we provide synonyms for all functions that changed names.

HASPmota is supposed to have no changes.

Improvements:
- Freetype upgraded to 2.13.2, and now supports BDF (bitmap) fonts embedded in TTF

Known issues:
- PNG decoding might fail on non-PSRAM due to change of cache behavior, see https://github.com/lvgl/lvgl/issues/5579

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Mhh, performance loss in V9. Reason unclear.
https://github.com/lvgl/lvgl/issues/5459

**Comment by s-hadinger** [comment]
The performance impact was not obvious in my test. In Tasmota the biggest performance hit comes from the fact that we don't fully use DMA because of SPI conflicts with other devices

**Comment by arendst** [comment]
I'll merge to see if our users also notice performance issues.

**Comment by helmar74** [comment]
I just created the following issue:
https://github.com/arendst/Tasmota/issues/20717
Might it be related to this PR?

**Comment by s-hadinger** [comment]
I doubt since you only use Display commands

**Pull request merged**
