### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
## Description:

Update Italian language.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with core ESP32 V.1.0.6
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by ascillato** [comment]
Hi @bovirus 

Thanks a lot for the translations.

As you have been very precise in the italian translation, I have a question to you about the reasoning behind the key:

```cpp
#define D_SHOW_MORE_OPTIONS "Altre opzioni"
```

I would like to understand why is this more suitable for the everyday use.

That key is used in the Initial WiFi Configuration Page.

image

and when clicking on it, you see

image

So, as this button is just showing more options that are hidden behind it, and it is not taking the user to another page, in English is more suitable the **_MORE OPTIONS_** label for this. Also, in Tasmota main configuration menu, there is the **_Other Options_** label that actually takes the user to another page.

I'm totally fine with the translation of this key, I just want to undestand this detail for further translations.

Thanks.

**Comment by ascillato** [comment]
Checking the previous image I realize that the following keys should be different. The restore configuration is equal to reset configuration and in the previous menu it shows both buttons with the same label but they do different things.

```cpp
#define D_RESET_CONFIGURATION          "Ripristino impostazioni"

#define D_RESTORE_CONFIGURATION        "Ripristino impostazioni"
```

**Comment by bovirus** [comment]
"Restore" is "Ripristino"
"Reset" should be "Ripristino impostazioni predefinite" but it's too long.

If you should have two different string "you can use "Impostazioni predefinite"

**Comment by ascillato** [comment]
Great!!! Thanks for the fast answer 👍

**Comment by ascillato** [comment]
I have just changed `D_RESET_CONFIGURATION` to `Impostazioni predefinite`

Thanks.

**Comment by bovirus** [comment]
OK. Thanks.

**Comment by bovirus** [comment]
I have an idea for next release

#define D_RESTORE_CONFIGURATION        "Carica impostazioni"

Restore Settings = Load setting from external file.
Then ifor me if it's true

Backup settings -> Save settings
Restore settings -> Load settings
 
For me is more clear.

**Comment by ascillato** [comment]
Yes, I agree, it is more clear that way.

**Comment by bovirus** [comment]
@ascillato 
I will change in Italian on next update.
I propose you to change them in English file on next update.

**Comment by ascillato** [comment]
I have just changed those keys now in the italian translation file.

Backup settings -> "Salva impostazioni"
Restore settings -> "Carica impostazioni"

Thanks a lot for the help.

In English seems that Backup and Restore should be better understandable for new users or for non tech users, it feels like more accurate. What Tasmota is really doing is just a Save and Load, but seems better that in the English translation is better as it is now. In the other hand, in Italian, seems to be much much better to be "Salva impostazioni" and "Carica impostazioni" as you have proposed. These feels like having a more accurate meaning to what Tasmota is doing.

**Comment by arendst** [comment]
No we won't!

There is a major difference between load/save and backup/restore. The first allows for any layout, the seconds just is supposed to restore a made backup. This is common data administration.

Discussion is futile.

**Pull request merged**
