### PR TITLE
Xsns 102 ld2410

### PR DESCRIPTION
**Pull request by md5sum-as**
## Description:

Added new features:
- command **LD2410EngineeringStart**. Starting engineering mode for tuning moving and static sensitivity
- command **LD2410EngineeringEnd**. Stop engineering mode
- commang LD2410Get. Get last  received moving/static target energy
- add Setoption160 - Disable generate moving event by sensor report - use LD2410 out pin for events (1 for disable)
- added output to main web page engineering statistics when receive engineering reports
Снимок экрана от 2024-08-01 01-37-31 Снимок экрана от 2024-07-31 22-36-27

Refactoring language header files - add/move defines for xsns_102_ld2410.ino module
_UPD: check with Tasmota core ESP32 V.3.0.2_

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.7
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.0.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by md5sum-as** [comment]
UPD: check with Tasmota core ESP32 V.3.0.2

**Comment by ortegafernando** [comment]
Hi, do you think this is compatible with the low consumption HLK-LD2410S version? thanks

**Comment by md5sum-as** [comment]
> Hi, do you think this is compatible with the low consumption HLK-LD2410S version? thanks

Hi. 
No, not compatible, tested. As expected from the documentation.
The 2410S has a different communication protocol. The manufacturer sent me the documentation for it, but only in Chinese, and I plan to create a module for the 2410S in the future.

**Comment by arendst** [comment]
Unstale

**Comment by wiktor-m** [comment]
> > Hi, do you think this is compatible with the low consumption HLK-LD2410S version? thanks
> 
> Hi. No, not compatible, tested. As expected from the documentation. The 2410S has a different communication protocol. The manufacturer sent me the documentation for it, but only in Chinese, and I plan to create a module for the 2410S in the future.

Hi @md5sum-as,
Here is PDF for LD2410S from manufacturer:
https://drive.google.com/drive/folders/1wC8KC-DaNavNbpeVouZ1HdiBzZ9YrAcg
I need support LD2410S too :) Is there a chance that you will write something for LD2410S soon?

**Comment by md5sum-as** [comment]
> > > Hi, do you think this is compatible with the low consumption HLK-LD2410S version? thanks
> > 
> > 
> > Hi. No, not compatible, tested. As expected from the documentation. The 2410S has a different communication protocol. The manufacturer sent me the documentation for it, but only in Chinese, and I plan to create a module for the 2410S in the future.
> 
> Hi @md5sum-as, Here is PDF for LD2410S from manufacturer: https://drive.google.com/drive/folders/1wC8KC-DaNavNbpeVouZ1HdiBzZ9YrAcg I need support LD2410S too :) Is there a chance that you will write something for LD2410S soon?

Hi [wiktor-m](https://github.com/wiktor-m),
I have seen this document. Unfortunately, it does not fully describe the protocol.
I created a separate module for the ld2410s because the communication protocols are very different. https://github.com/arendst/Tasmota/pull/22253

**Comment by wikmas** [comment]
> > > > Hi, do you think this is compatible with the low consumption HLK-LD2410S version? thanks
> > > 
> > > 
> > > Hi. No, not compatible, tested. As expected from the documentation. The 2410S has a different communication protocol. The manufacturer sent me the documentation for it, but only in Chinese, and I plan to create a module for the 2410S in the future.
> > 
> > 
> > Hi @md5sum-as, Here is PDF for LD2410S from manufacturer: https://drive.google.com/drive/folders/1wC8KC-DaNavNbpeVouZ1HdiBzZ9YrAcg I need support LD2410S too :) Is there a chance that you will write something for LD2410S soon?
> 
> Hi [wiktor-m](https://github.com/wiktor-m), I have seen this document. Unfortunately, it does not fully describe the protocol. I created a separate module for the ld2410s because the communication protocols are very different. #22253

Hi md5sum-as,
Thank you very much.
Verry good job!

**Comment by NicolasBernaerts** [comment]
Hi,
If interested, I've developped tasmota drivers for LD2410 and LD2450.
It includes graphical radar.
If you want to reuse it for official driver, dot not hesitate.
Cheers.
nicolas

**Comment by cmmdwl** [comment]
Guys, I'm not very familiar with tasmota How do I get moving/static target energy to be sent to homeassent I'd like to use the energy judgement rather than the distance judgement that comes with it

**Pull request merged**
