### PR TITLE
Allow to build Minimal firmware with TLS support

### PR DESCRIPTION
**Pull request by bkmit**
## Description:

Do not undefine USE_MQTT_TLS by force for MINIMAL firmware.
This PR do not change any defaults.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato** [comment]
Sorry, This won't work. Minimal firmware is not for normal usage. It is a super small version to be used just in the UPDATING process. Adding this option will increase its size, making the minimal unusable for updating.

**Comment by bkmit** [comment]
This works perfectly  for me. I know what purpose of minimal was created for.
This patch do not change current project build defines, only allow to define USE_MQTT_TLS in user_config_override.h or platfomio_override.ini files if user (like me) need to.
I am using custom built TLS-enabled minimal image to do MQTT only management of all my modules.
Hope this explain why I have created this PR.

**Comment by ascillato** [comment]
The minimal firmware will work in your device for just few seconds while it is updating to your full version. Adding more unneeded features to the _Interim Update Firmware_, makes this minimal to be bigger, restricting the available free space for the full version.

**Comment by ascillato2** [comment]
@arendst What do you think ?

**Comment by ascillato2** [comment]
@bkmit Bohdan, ok, you have a valid point.

@arendst Theo, what do you think?

**Comment by ascillato** [comment]
@bkmit Bohdan,

Thanks for sharing :+1:

**Pull request merged**
