### PR TITLE
TuyaMCU Update

### LINKED ISSUE #8663: Support for 2 channel Tuya MCU dimmer
**Have you looked for this feature in other issues and in the docs?**  
Yes
**Is your feature request related to a problem? Please describe.**  
Default implementation of tuya mcu api in xdrv_16_tuyamcu.ino support only dimmer with one channel. Also we need two brightness sliders in web interface, 

**Describe the solution you'd like**  
Support for two brightness sliders in web interface when fnId: 22 (2nd dimmer) is define with non zero dpId. I tried to add TUYA_MCU_FUNC_DIMMER2 to xdrv_16_tuyamcu.ino but workaround with two sliders from PWM dimmer sends dim command to 2 channels. Also input from button send on/off state to 2 channels. Likely bad executecommand in:
`if (fnId == TUYA_MCU_FUNC_DIMMER2) { //2 channel
          AddLog_P2(LOG_LEVEL_DEBUG, PSTR("TYA: 2CH RX Dim State=%d"), packetValue);
          Tuya.new_dim2 = changeUIntScale(packetValue, 0, Settings.dimmer_hw_max, 0, 100);
          if (Tuya.ignore_dimmer_cmd_timeout2 < millis()) {
            if ((power || Settings.flag3.tuya_apply_o20) &&  // SetOption54 - Apply SetOption20 settings to Tuya device
                (Tuya.new_dim2 > 0) && (abs(Tuya.new_dim2 - Settings.light_dimmer) > 1)) {
              Tuya.ignore_dim2 = true;
              snprintf_P(scmnd, sizeof(scmnd), PSTR(D_CMND_DIMMER "3 %d"), Tuya.new_dim2 );
              ExecuteCommand(scmnd, SRC_SWITCH);
            }
          }`

**Describe alternatives you've considered**  

**Additional context**  
DpID's for MS-105B: 2 Gang Dimmer Switch:
dpID 1 - on, off 1 ch
dpID 2 - dimmer 1 ch
dpID 7 - on, off 2 ch
dpID 8 - dimmer 2 ch

Logs from @LukevdPalen:
ACTION | Frame Header | Version | Command Word | Data Length | dpID | Data Type | Function Length | Function Command | Verification Method
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 ON | 55aa | 00 | 06 | 0005 | 01 | 01 | 0001 | 01 | 0e
1 OFF | 55aa | 00 | 06 | 0005 | 01 | 01 | 0001 | 00 | 0d
1 dim10 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 00000065 | 7a
1 dim20 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 000000c3 | d8
1 dim30 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 00000127 | 3d
1 dim40 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 0000018b | a1
1 dim50 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 000001ef | 05
1 dim60 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 0000025b | 72
1 dim70 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 000002be | d5
1 dim80 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 0000031d | 35
1 dim90 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 00000381 | 99
1 dim100 | 55aa | 00 | 06 | 0008 | 02 | 02 | 0004 | 000003e8 | 00
2 ON | 55aa | 00 | 06 | 0005 | 07 | 01 | 0001 | 01 | 14
2 OFF | 55aa | 00 | 06 | 0005 | 07 | 01 | 0001 | 00 | 13
2 dim10 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 00000061 | 7c
2 dim20 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 000000c3 | de
2 dim30 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 00000129 | 45
2 dim40 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 0000018d | a9
2 dim50 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 000001ef | 0b
2 dim60 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 00000254 | 71
2 dim70 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 000002b9 | d6
2 dim80 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 0000031e | 3c
2 dim90 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 00000380 | 9e
2 dim100 | 55aa | 00 | 06 | 0008 | 08 | 02 | 0004 | 000003e8 | 06

[xdrv_16_tuyamcu.zip](https://github.com/arendst/Tasmota/files/4764542/xdrv_16_tuyamcu.zip)

### LINKED ISSUE #8880: TuyaMCU ability to set a color
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
I have a 700ml diffuser that uses the TuyaMCU. It follows the same set of dplds which are listened on the docs but there is no way to have a custom light color using the method provided even though you can set the light color using TuyaSend3 with a hex value.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
I would like for there to be another fnId with a type something along the lines of "Hex Color" or something like that where you can specify what dpld is to be used to control the light color.

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
I have tried to by adding 3 PWM items in the module config page and then, using scripting, used TuyaSend for whenever the color has been changed. There are a couple of downsides to this. Firstly, I cannot get grammar correction and I can't fade between the colors. Also, when I set the dimmer value to 0, tasmota will turn off the device including the mister.

**Additional context**  
_Add any other context or screenshots about the feature request here._
TuyaMCU Docs Page: [https://tasmota.github.io/docs/TuyaMCU/#fnid](https://tasmota.github.io/docs/TuyaMCU/#fnid)
**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by effelle**
## Description:
----------------------------------------------------
**Changelog:**
1. Support for two dimmers devices
2. Initial support for RGB, RGB+W and RGB+CT lights
3. New ModeSet Function to switch between white and RGB light
4. Support for Fan controllers (or any other enum Type4 dpId)
5. Initial support for shutters
6. Extra functions
7. New optional topic ready to be used with any home automation system
8. TuyaSend command updated
----------------------------------------------------

1: To enable a dual dimmer setup assign the following functions (fnId):
- 21 as Dimmer1
- 22 as Dimmer2
- 11 as Relay1
- 12 as Relay2

Tasmota will automatically enable `SetOption68` and the dimmers will respond to `Channel1` and `Channel2` commands.

**Obs.: The use of `SetOption68` is limited to two channels and will be automatically disabled if any other combination of lights will be used.**

2: Special lights:
To enable an CT light assign the following functions (fnId):
- 21 as Dimmer1
- 11 as Relay1
- 23 as CT channel

To enable an RGB light assign the following functions (fnId):
- 21 as Dimmer1
- 11 as Relay1
- 24 as RGB controller

To enable an RGB+W light use the RGB configuration and append fnId 25 to the correct dpId.
Last but not least, for an RGB+CT light use the RGB configuration and append fnId 23.

**obs.: At the present time the use of `SetOption68` for more than two channels and the light split option (SetOption37 >= 128) are not supported.**

3: The majority of  TuyaMCU devices with an RGB+W or an RGB+CT light needs a button to switch between White and colored light. 
Is now possible enable the ModeSet selector adding the function 26. A button on the WebUI will be available. 
When the ModeSet function is enabled will not be possible to update both lights at the same time. The possible values are 0 (white) and 1 (colorful).

4: To setup a fan controller select one of the available functions:
- 61 for 3 speeds fan controller (possible values 0,1, 2)
- 62 for 4 speeds fan controller (possible values 0, 1, 2, 3)
- 63 for 5 speeds fan controller (possible values 0, 1, 2, 3, 4)
- 64 for 6 speeds fan controller (possible values 0, 1, 2, 3, 4, 5)

**Obs.: Different from other fan controllers like the Ifan03, the value `0` desn't mean OFF.  A TuyaMCU will consider a `0` as the lowest speed possible. ON/OFF states for a fan are always managed by another dpId, then you need to add the correct relay function.**

5: Single Shutter or double shutters devices can be managed with a normal dimmer setup, for devices that have the face plate buttons reporting to another dpId like the Zemismart WiFi Tuya Roller Shade, enable:
- 27 to report the state of Dimmer1
- 28 to report the state of Dimmer2

6: Some extra functions were enabled and are still a work in progress:
- 97 for motor direction
- 98 for error logging (report only)
- 99 as a dummy function

The last one is useful only if you don't want to manage the dpId assigned to the MCU. Enabling the dummy will let you remove the first relay (fnId 11) added by default in any configuration.

7: Use `TuyaSend9` without any payload to toggle a `STAT` topic reporting the equivalent `TuyaSend<x>` command needed to update a dpId, for example:
```json
17:45:38 CMD: power 1
17:45:38 MQT: stat/tasmota_49A3BC/RESULT = {"POWER":"ON"}
17:45:38 MQT: stat/tasmota_49A3BC/POWER = ON
17:45:38 MQT: stat/tasmota_49A3BC/TUYASEND1 = 1,1
```
Disabled by default, the topic can be easily grabbed by any home automation system.

8: Instead of using `SerialSend5 55aa000100000` to get all the device information, you may want to use`TuyaSend8` command or use `TuyaSend0` to query just the state of the dpId.

@arendst : I've reused the old 33F on settings.h.

newtuya

**Related issue (if applicable):** fixes #8880 and #8663

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Great!

**Comment by antoniomolram** [comment]
Good news! I'm just anxious to try it this nicht at home! Thank you @effelle

**Comment by effelle** [comment]
Will probably need some extra polish but since is a big update any feedback will be really appreciated.

**Comment by antoniomolram** [comment]
sure! don't worry. I will give you some feedback during this week.

**Comment by digiblur** [comment]
Nice job!  I'll have to check this out this weekend when I have time to play.

**Comment by effelle** [comment]
@arendst 
Theo did you change something related to `FUNC_SET_CHANNELS`? On 8.5 Hsbcolor, color and sometimes CT commands stopped triggering the event from both webui and console. Dimmers commands are working fine. The only solution I have as a patch for now is move the call for `TuyaSetChannels()` under `FUNC_EVERY_SECOND`.

**Comment by arendst** [comment]
Nope. No change on my side.

**Comment by rjmcdougall** [comment]
I have been trying to get XMCosy string lights working -- with the latest build it seems like the RGB control to dpid 5 doesn't work. 

The only format that works that I can find is RRGGBB as the type3 string.

Have we seen other tuya controllers which might only work with RGB, or is there something else that I could try?


https://www.amazon.com/Outdoor-String-Lights-Colored-Waterproof/dp/B08614LWZK?ref_=ast_sto_dp

**Comment by effelle** [comment]
Yes I have. Tuya folks have nothing to do then there are two different setup to pass the RGB color and at this point I don't exclude there are more out there.
If you are sure dpid 5 is the rgb try to issue a tuyasend this way 
```json
TUYASEND3 = 5,140100ffff6464
```
If is working means you need a string with `RRGGBBffff6464` format instead of `HUE0SAT0BRI0`.
Meaning you need to wait until I will have the time to do an update. No ETA.

**Comment by rjmcdougall** [comment]
I suspect it is what you point out, since when I do a send0 and read back dpid 5 when color is blue, the value is 0000FF00006464. Looking forward to the update!

**Comment by effelle** [comment]
Ok, I'll try to find some time for it.

**Comment by rjmcdougall** [comment]
do you think it will require a parameter to control the format, or can you auto-detect somehow?

**Comment by rjmcdougall** [comment]
23:19:35 CMD: Group 0, Index 3, Command "TUYASEND", Data "5,140100ffff6464"
23:19:35 TYA: Send "55aa000600120503000e3134303130306666666636343634bf"
23:19:35 RSL: stat/tasmota_7FFA57/RESULT = {"TuyaSend":"Done"}

**Comment by effelle** [comment]
No there will be another fnId for the RGB becasue the most common (fnId 24) is the one already implemented.

**Comment by effelle** [comment]
https://github.com/arendst/Tasmota/pull/9769

**Comment by rjmcdougall** [comment]
Awesome! Will try

**Comment by effelle** [comment]
Please report your findings and... Good luck!

**Comment by rjmcdougall** [comment]
I build and tested this:

Good news: color works!

However, when I set this I now see the color selector, color temp and mode
go away on the UI -- and it's replaced with 3 RGB sliders.

There is no longer access to CW on the menu.

Could this be that I have configured something wrong?

11:41:29 RSL: stat/tasmota_7FFA57/RESULT =
{"TuyaMCU":[{"fnId":11,"dpId":1},{"fnId":21,"dpId":3},{"fnId":26,"dpId":2},{"fnId":24,"dpId":5}]}

[image: Screen Shot 2020-11-14 at 10.41.55 AM.png]

**Comment by rjmcdougall** [comment]
Also if I try and set 23->4 (CT channel) then it removes the RGB setting
(24,5).

**Pull request merged**
