### PR TITLE
update eMail lib to v1.2.0

### PR DESCRIPTION
**Pull request by Jason2866**
Fixing compile errors with Arduino ESP8266 Core 3.0.0
The lib uses `PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED` if the option is set.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with core ESP32 V.1.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@arendst do not merge until @gemu2015 is helping fixing the error for build core2

**Comment by gemu2015** [comment]
when i adapted this lib i had to make several changes. will have to redo these changes on the new lib. will take some time.

**Comment by gemu2015** [comment]
@Jason2866 
i am also working on these files. makes no sense we both do ?

**Comment by Jason2866** [comment]
At @gemu2015 i am finished. I tried to implement your changes. If it fails now please have a look.
Sorry for making you double work

**Comment by gemu2015** [comment]
should compile now without errors
also added extended debug via web console as requested by some users

[Archiv.zip](https://github.com/arendst/Tasmota/files/6592222/Archiv.zip)

**Comment by Jason2866** [comment]
@arendst  can be merged now.  @gemu2015 a big thx for doing the whole real work!

**Pull request merged**
