### PR TITLE
Platformio override

### LINKED ISSUE #7005: platformio.ini override
**Have you looked for this feature in other issues and in the wiki?**  
yup

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
Add an option to override the default platformio.ini to retain user specific settings

**Describe alternatives you've considered**  
Modify the file everytime i do a pull from the master repo

**Additional context**  
If you could add a line in the platformio.ini like:

```
[platformio]
extra_configs = platformio_override.ini

```
This file could function the same way as user_config_override.h. Put in .gitignore and this way userspecific settings could remain in that file. Settings like:
- default_envs
- build_flags (-DUSE_CONFIG_OVERRIDE
- upload_port
- ... any other settings 

Kind regards,
Bert

### PR DESCRIPTION
**Pull request by bvduijn**
## Description:

**Related issue (if applicable):** fixes #7005 

## Checklist:
  - [X ] The pull request is done against the latest dev branch
  - [X ] Only relevant files were touched
  - [X ] Only one feature/fix was added per PR.
  - [X ] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by bvduijn** [comment]
@Jason2866 as per issue #7014

**Comment by ascillato** [comment]
Hi, sorry. Too many files changed unrelated to your main goal.

**Comment by Jason2866** [comment]
Sorry, your PR is not correct. It is NOT done to the latest development version!

> [X ] The pull request is done against the latest dev branch

**Comment by ascillato** [comment]
Hi, this PR can't be merged as it is because is not against latest codebase. So, it needs to be fixed.

I just tested your idea and works fine. If the file **platformio_override.ini** does not exist, it will compile correctly and without warnings. So, this change should not affect existent user setups :+1:

Anyway, I understand that this PR wants to make things easier for users, but I was wondering if this extra file makes things more complicated for new users. In my opinion, we can just add few comments on **platformio.ini** file on how to use it, instead of having another file to modify. As **platformio.ini** will continue to evolve due to new cores, options, environments, etc. I think it is better for an user to just use **latest codebase** and **platformio.ini** and set its own options there. The most used options are which Tasmota flavour to compile, Enabling user_config_override and COM port to flash. We can put those options at the top of the file if this make usage a bit easier.

**Comment by bvduijn** [comment]
@Jason2866  I thought I synced the latest dev branch before submitting my PR. I need to sync again I suppose.

@ascillato I see your point. My idea was merely intended so personal settings won't get lost when a fetch is done. I suppose your solution could work as well and it mere personal preference.

**Comment by ascillato** [comment]
@bvduijn

Yes, you are right. And as this change is backwards compatible and works fine, it should be added to Tasmota.

Please, re do the PR in order to be up to date with action codebase of development branch. Thanks

**Comment by ascillato2** [comment]
Closing this PR as it is aimed to wrong branch.

@bvduijn

Please, can you re do the PR in order to be up to date with actual codebase of the development branch? Thanks

**Comment by ascillato** [comment]
PR made by @Jason2866 on https://github.com/arendst/Tasmota/pull/7047

**Pull request closed without merging**
