### PR TITLE
Fix for SHT mode 1 with pulsed output: Stop pulse must be at same dir…

### PR DESCRIPTION
**Pull request by rakaiser**
…ection as start pulse.

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
@stefanbode pls advise.

**Comment by stefanbode** [comment]
I do not see any benefit of the change. Please explain what it will change and why this is required.

**Comment by stefanbode** [comment]
I agree that on pulse motors the pulse should be on the same relay. But specially with multiple shutter assigned I assume this will not work. I will check why the original code flip the wrong relay. We have the movement direction already. Currently I assume the fix must be a little different.

**Comment by stefanbode** [comment]
Ok, I understand now the problem. Let me check later if a movement of the direction=0 if clause behind the switch is possible. I agree setting this to 0 at that point create a static value for the switch. And this is for sure wrong.

**Comment by stefanbode** [comment]
I will bring up line 496 up after line 478. Then the relay is fine. Currently only on my mobile with no edit options to do so

**Comment by arendst** [comment]
Thx. I will make the suggested line change today.

**Comment by arendst** [comment]
Merged as requested.

**Comment by rakaiser** [comment]
Thx for fixing that obvious flaw. Works ok with my modified belt winder. Mode SHT_TIME combined with SHT_PULSE obviously not yet used.

**Comment by stefanbode** [comment]
Thanks for fixing this. Still on "holiday" after a motorbike accident in Thailand. I assume no other side effects. The issue came up when optimizing the operation time to ensure accurate movement. Automate testing is a little bit tricky because you do not get back easily feedback on the standard procedures. e.g. if the right relay way ON for 0.2 seconds. Anyhow @rakaiser thanks for bringing up any issue and we are happy to solve this asap.

**Pull request closed without merging**
