### PR TITLE
Add driver xdrv_85_BLE_EQ3_TRV

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:

New driver for EQ3 bluetooth radiator valves.
We have maybe 6-10 people already using this.
Probably not something to include in a default build.
Enabled via 
#define USE_EQ3_ESP32

only for 
#define ESP32
#define USE_BLE_ESP32

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.1.0.7.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Ysbrand** [comment]
As there is space enough when using ESP32 (correct me if I'm wrong), may I suggest to make it default in tasmota32-bluetooth?

**Comment by btsimonh** [comment]
info on size.
The .bin file for bluetooth with empty user_config_override.h is 1301k
The .bin file for bluetooth with empty user_config_override.h with USE_EQ3_ESP32 is 1310k
Does this mean it adds 9K to the code size?

It would be possible to add some 'enable' variable to ensure it is not active unless turned on in autoexec.bat?
RAM loading is not high (<100 bytes static).

**Comment by fightforlife** [comment]
Manual compilation with USE_EQ3_ESP32 is still needed, correct?
Would it be feasible to add it as standard to the esp32 bluetoth build?

**Comment by Kugeleis** [comment]
@arendst  please update the docs on how to enable it https://tasmota.github.io/docs/EQ3-TRV/
thanks

**Pull request merged**
