### PR TITLE
Support for VEML6075 and initial Support for VEML7700

### PR DESCRIPTION
**Pull request by device111**
Add support for VEML6075.
-Shows UVA, UVB, UVIndex

supported Commands are:

| Command        |      Description |
|----------------|------------------|
|VEML6075power   | Power up/down    |
|VEML6075dynamic | HD Mode          |
|VEML6075inttime | Integration Time |

Add initial Support for VEML7700  (#8260)
- the implementation based on Adafruit VEML7700 Libary.
- Shows Illuminance and White Content of Light.

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core ESP8266 V.2.7.1
  - [x] The code change is tested and works on core ESP32 V.1.12.0
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by device111** [comment]
@arendst 
are any problems with the PR?

**Comment by arendst** [comment]
Still investigating the used libraries. I noticed a pow math function using 5k code. AN alternative is available and provided by Tasmota. Needs lib update though. Not a big problem but I need to find time to do it.

**Comment by device111** [comment]
ah ok. thanks for info.
at the moment, the driver don't use "readLuxNormalized" and "readWhiteNormalized" with the math-pow function for the readings. 
If i had time, i did a integration without Libary.

**Comment by scum2000** [comment]
Guys, wondering if you can help. I'm trying to use both a bme280 and veml6075. I compiled my own tasmota with various versions up to 8.3.1.3. both sensors show up in the i2cscan command but if I comment out #define_bmp in the build the veml6075 shows up in main menu. If I don't bme280(same with bmp280, tried both) shows instead. Do you have any suggestions of anything I can try? Thanks.

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by scum2000** [comment]
Thanks for the response. I already did and they told me to come here. No worries

**Pull request merged**
