### PR TITLE
Enable user mode for GPIO2 and GPIO5 on the Sonoff Dual

### PR DESCRIPTION
**Pull request by danielztolnai**
GPIO 2 and 5 on the Sonoff Dual are unused, so the pads can be routed out and used for senor connection.

### CODE REVIEW

**Comment by arendst** [comment]
Are these GPIOS easily access-able to the regular user?

**Comment by danielztolnai** [comment]
They require the same amount of soldering skills as the currently available user mode GPIOs as they are all available on the pads near the ESP8266. While creating the image below, I've realized that 3 other GPIOs can be accessed the same way.

sonoff_dual_gpios
Note1: GPIO15 has a 10k pull-down resistor on the board, the others are not connected to anything at all.

**Comment by localhost61** [comment]
And what about the Dual R2? Do you know for them? I'm willing to add a DS18B20.

**Comment by danielztolnai** [comment]
@localhost61, personally I do not own a Dual R2, but based on the photos in #1249 the following GPIOs should be available: GPIO2, GPIO4, GPIO14 and GPIO16. They are on the same pin number as on the ESP8266 (see the annotated photo above) and the same amount of soldering skills are required to connect a sensor to them.

**Comment by localhost61** [comment]
You are write, those pins or not connected and 6,7,8 & 11 neither.
But after thinking, the R2 version don't have the constraints of the R1, it seems that nothing prevent to use RX or TX on the header, provided that one remove the sensor(s) for serial programming, which is even not necessary in the case of OTA update.

**Comment by digiblur** [comment]
Happened to see this one referenced in my Dual R2 research.  According to previous threads here the device has a ESP8285.  I found one site documenting the GPIO pins and it states GPIO0, 2, and 15 will drive start up states and 6, 7, 8 and 11 are unsable.  Only leaves with a few other free pins available on the chip itself.

https://hackaday.io/project/28220-one-tube-nixie-clock/log/70865-esp8285-gpio

**Pull request closed without merging**
