### PR TITLE
Add Compiled Development Binaries Link to ReadMe

### PR DESCRIPTION
**Pull request by ascillato**
@andrethomas automated binaries from development. Explained at #3397.

### CODE REVIEW

**Comment by arendst** [comment]
I sure hope they compile with the correct  byte, word and 32bit boundary.

**Comment by andrethomas** [comment]
@arendst Anything you need me to do to confirm?

**Comment by arendst** [comment]
If possible check this https://github.com/arendst/Sonoff-Tasmota/issues/3385#issuecomment-409957965

**Comment by andrethomas** [comment]
Oh that one where I commented on Align() :P

**Comment by arendst** [comment]
Just checked your sonoff.bin compile and notice again wrong alignment.

image


So let's see if people start making issues regarding different kinds of trouble caused by flash read mis-alignment.

**Comment by andrethomas** [comment]
Yeah, I saw - looking into it but all the compiler options are correct from what I can tell - even explicitly specifying 4 byte alignment for functions changes nothing.

I will fix it as soon as I can identify the problem

**Comment by andrethomas** [comment]
@arendst @ascillato 

I have double checked everything right down to the lowest level that I can (to my current knowledge) and it seems as if everything is as it should be... compiler directives are good on both platforms, and so are the linker scripts.

I suspect the reason why linking and/or compiler optomisation is different on Linux than it is on Windows must be that the compiler on Linux is actually compiled on 

The compiler binaries from extensa appear to be compiled under different compiler environments for Linux vs Windows so I suspect the optomisation stems from there somehow - most likely compiler directives are selectively excluded or included based on the architecture used to perform the actual compilation.

On Linux:

```
xtensa-lx106-elf-g++ (crosstool-NG 1.20.0) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

xtensa-lx106-elf-gcc (crosstool-NG 1.20.0) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Windows:

```
xtensa-lx106-elf-g++ (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

xtensa-lx106-elf-gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Any ideas on a way forward or we just leave it as is for now and see what happens.

**Comment by arendst** [comment]
Thx for the extensive diagnostics.

I guess just leave it for now and see what users come up with. Problem is that because of misalignment anything could happen...

**Pull request merged**
