### PR TITLE
Python PIO tool controls using environment variables

### PR DESCRIPTION
**Pull request by sillyfrog**
## Description:

A minor enhancement to the PIO tools to allow you to disable the compression of `.map` and `.bin` files using environment variables. It also allows overriding the final location of the `.map` and `.bin` files.

For example, to disable the compression of the `.map` files, put the following in your environment:
```
TASMOTA_DISABLE_MAP_GZ=1
```

All of the options are at the top of `tasmotapiolib.py`.

(The top of this page outlines ways to set environment variables: https://docs.platformio.org/en/latest/envvars.html)

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.1.0.7.3
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx again! Testing...

**Comment by arendst** [comment]
I don't like the OS environment useage. On windows many shells are running and setting the correct environment value is not that easy.

I prefer to have a value set in the ``platformio_override.ini file`` to be handled by the python gzip script.

**Comment by Jason2866** [comment]
@sillyfrog  Take a look here https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#custom-firmware-program-name
You can add for example to `build_flags` and parse for. Now you are in the Platformio rabbit hole. Since it is Python, a easy task for a Pythonic ;-)

**Comment by sillyfrog** [comment]
@arendst While writing the description for the PR I had a similar thought... However after looking further at the docs, I some how missed yesterday that there is a way to add custom options to the `.ini`. I'll do that now and add another PR.

**Pull request merged**
