### PR TITLE
Code of Conduct v2.0

### PR DESCRIPTION
**Pull request by don-willingham**
## Description:
[contributor-covenant.org](https://www.contributor-covenant.org/) code of conduct version 2.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by don-willingham** [comment]
Should the top level README reference the code of conduct? Does it fit in the Support or Developer Community sections? Make a community standards section before both? Should the [Contributor Covenant](code_of_conduct.md) badge be added?

**Comment by Jason2866** [comment]
Imho adding to https://github.com/arendst/Tasmota#contribute section would fit and adding the badge there too.

**Comment by arendst** [comment]
Agree with Jason

**Comment by ascillato** [comment]
Agree with this PR and Jason's idea.

Thanks for your contributions.

**Pull request merged**
