### PR TITLE
Add mutex to many camera functions.

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:

Add mutex to many camera functions.
Not a guaranteed fix every time, but does improve chances of AIThinker CAM working.

**Related issue (if applicable):** helps with [discussion](https://github.com/arendst/Tasmota/discussions/18482)

## Checklist:
  - [*] The pull request is done against the latest development branch
  - [*] Only relevant files were touched
  - [*] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [*] The code change is tested and works with Tasmota core ESP32 V.2.0.9
  - [*] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by btsimonh** [comment]
I noticed that through a wcinit command, the stream stopped.  Added a commit to allow the stream to continue after the camera is re-configured.

@arendst - 
I have noticed that a software restart (or firmware upgrade..) can (rarely) result in a 0x105 error.
I think this is because the camera is left mid-i2c, and then can no longer be discovered.
As there are devices without a GPIO for CAM_RESET, I'd like to 'close' the camera before restarting.
Would FUNC_SAVE_BEFORE_RESTART be suitable?
hmm..  just tested and using that in xdrv 81 cauases restart to hang...
Advice?

**Comment by btsimonh** [comment]
looks like FUNC_SAVE_BEFORE_RESTART is not a good one - it's called on saveall.  But I can't see an API command to close a driver...

**Comment by arendst** [comment]
Does a close also happens when you stop the stream. Ie I use the GUI. When I close the GUI I see the stream is stopped in the console.

If yes, try what happens if you do this and then do a restart to see if it comes up alive again. If it doesn't comes back up then any pre-closure will fail too.

**Comment by btsimonh** [comment]
will give it a go tonight.  Basically, restart from the web console (so stream is already stopped).
But I'd really like to do a full deinit as well if you think of some way to get a call through at all restart points.

**Comment by arendst** [comment]
I suppose you know this:
```
/**
 * @brief Initialize the camera driver
 *
 * @note call camera_probe before calling this function
 *
 * This function detects and configures camera over I2C interface,
 * allocates framebuffer and DMA buffers,
 * initializes parallel I2S input, and sets up DMA descriptors.
 *
 * Currently this function can only be called once and there is
 * no way to de-initialize this module.
 *
 * @param config  Camera configuration parameters
 *
 * @return ESP_OK on success
 */
esp_err_t esp_camera_init(const camera_config_t* config);
```
where it states no way no to do a de-init.

Take a look at ``esp_camera.h`` for further info (in framework-arduinoespressif32).

**Comment by btsimonh** [comment]
yep, saw that...   but also note it says to call camera_probe before calling the fn, and you can't because it's static....
I tested the wcinit cmnd repeatedly, which deinits then inits, and it's quite reliable with the mutexes in place.
Plus they have a deinit function - so I'm guessing the comments to be old.

Final PR additions above.  Let's not worry about closing on restart.  I tried to reproduce on another module, and could not in 10 or so tries, so unless someone has this specific issue and can't power off restart, we can defer it.

**Pull request merged**
