### PR TITLE
add SDM630 Active Power Total in Webinterface

### PR DESCRIPTION
**Pull request by matrix1000**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.10
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

This is my first Changerequest.
According to Discussion: https://github.com/arendst/Tasmota/discussions/19103

### CODE REVIEW

**Comment by Jason2866** [comment]
Please add a description what the PR does solve or change.

**Comment by Jason2866** [comment]
What happens when connected only 1 phase? The additional line will litter since it redundant.

**Comment by matrix1000** [comment]
Alright, I will modify the languages and take into care the double display problem with only one phase.

**Comment by arendst** [comment]
I see what you want. The current solution works for energy producing connections but fails on most non-energy producing multi phase connections; a sum of power usage us useless in that case (and was never requested in the past)

We need to find a better way to show this information for energy producing connections only. I fear another SetOption is needed.

**Comment by matrix1000** [comment]
Ok I understand. Anything I can do to help?

**Comment by matrix1000** [comment]
push

**Comment by matrix1000** [comment]
push

**Comment by arendst** [comment]
Implemented just now. It only shows on multi phases AND both positive and negative values.

**Comment by matrix1000** [comment]
Many many thanks! :-)

**Pull request closed without merging**
