### PR TITLE
Add Full support of all protocols in IRremoteESP8266

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

New mode USE_IR_REMOTE_FULL activating all options and protocols in IRremote8266, including HVAC. Warning, flash code +81k, so this is to be reserved to Dedicated-IR firmwares.

To avoid huge source code, i have created a new page `sonoff/xdrv_05_irremote_full.ino`.If needed it can be back merge into `sonoff/xdrv_05_irremote.ino`.

> @arendst I'm struggling to change compile options in `lib/IRremoteESP8266-x.x.x/src/IRremoteESP8266.h` based on `my_user_config.h`. This PR does not activate all HVAC decode protocols for this reason.

### This feature adds a lot of new options and fields, I will create a dedicated wiki page.

For codes <64 bits, IRreceive also adds an `dataLSB` version, that makes easier calculation for NEC or PIONEER protocols.

Example IRsend (backwards compatible):
```Irsend {"Protocol":"NEC","Bits":32,"Data":"0x6170A857","Repeat":0}```

Example IRsend with repeat and 64 bits:
```IRsend {"Protocol":"Pioneer","Bits":64,"Data":"0xA55A50AFA55A50AF"}```

Same example using LSB encoding:
```IRsend {"Protocol":"PIONEER","Bits":64,"DataLSB":"0xA55A0AF5A55A0AF5"}```

Example of IRHVAC send:
```IRhvac {"Vendor":"Mitsubishi_Heavy_152","Power":"On","Mode":"Hot","FanSpeed":3,"Temp":22}```

Example of IRReceive (non-HVAC):
```21:09:30 RSL: tele/sonoff/IR1/RESULT = {"IrReceived":{"Protocol":"PIONEER","Bits":64,"Data":"0xA55A50AFA55A50AF","DataLSB":"0xA55A0AF5A55A0AF5","Repeat":0}}```

Example of HVAC remote receive:
```21:17:27 RSL: tele/sonoff/IR1/RESULT = {"IrReceived":{"Protocol":"MITSUBISHI_HEAVY_152","Bits":152,"Data":"0xAD513CE51A08F705FA02FDC03F08F700FF807F","Repeat":0,"IRHVAC":{"Vendor":"MITSUBISHI_HEAVY_152","Model":-1,"Power":"on","Mode":"auto","Celsius":"on","Temp":"22.0","FanSpeed":"medium","SwingV":"off","SwingH":"off","Quiet":"off","Turbo":"off","Econo":"off","Light":"off","Filter":"off","Clean":"off","Beep":"off","Sleep":-1}"}}```

If protocol is unknow, it will report supported protocols:

```Irsend {"Protocol":"xx"}```
```21:12:20 MQT: stat/sonoff/IR1/RESULT = {"IRSend":"Wrong Protocol (RC5|RC6|NEC|SONY|PANASONIC|JVC|SAMSUNG|WHYNTER|AIWA_RC_T501|LG|MITSUBISHI|DISH|SHARP|DENON|SHERWOOD|RCMM|SANYO_LC7461|RC5X|NEC (non-strict)|NIKAI|MAGIQUEST|LASERTAG|CARRIER_AC|MITSUBISHI2|HITACHI_AC1|HITACHI_AC2|GICABLE|LUTRON|PIONEER|LG2|SAMSUNG36|LEGOPF|INAX)"}```

```IRhvac {"Vendor":"XX"}```
```21:14:09 MQT: stat/sonoff/IR1/RESULT = {"IRHVAC":"Wrong Vendor (COOLIX|DAIKIN|KELVINATOR|MITSUBISHI_AC|GREE|ARGO|TROTEC|TOSHIBA_AC|FUJITSU_AC|MIDEA|HAIER_AC|HITACHI_AC|HAIER_AC_YRW02|WHIRLPOOL_AC|SAMSUNG_AC|ELECTRA_AC|PANASONIC_AC|DAIKIN2|VESTEL_AC|TECO|TCL112AC|MITSUBISHI_HEAVY_88|MITSUBISHI_HEAVY_152|DAIKIN216|SHARP_AC|GOODWEATHER|DAIKIN160|NEOCLIMA|DAIKIN176|DAIKIN128)"}```

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by s-hadinger** [comment]
@arendst It looks the compilation fails also on the development branch for sonoff-sensors.

``` /xxx/ld: .pioenvs/sono
ff-sensors/firmware.elf section `.text1' will not fit in region `iram1_0_seg'

**Comment by arendst** [comment]
Thx Stephan. 

Yes I noticed the sonoff-sensor mis-compile too but cannot find the culprit yet; the iram usage in the map file is below the max value so why it complaints about iram segment is a mistery to me for now. I'll further investigate.

**Comment by arendst** [comment]
> @arendst I'm struggling to change compile options in lib/IRremoteESP8266-x.x.x/src/IRremoteESP8266.h based on my_user_config.h. This PR does not activate all HVAC decode protocols for this reason.

I understand the issue and I also see no solution yet how to solve this other than making a copy of the library and rename all references to IRremoteESP8266.h ...

**Comment by s-hadinger** [comment]
> I understand the issue and I also see no solution yet how to solve this other than making a copy of the library and rename all references to IRremoteESP8266.h ...

I feared you'd say that... So be it, let me see how I can do that in a programmatic way.

And thanks for the merge.

**Comment by arendst** [comment]
If two libraries are needed than I suggest to change the library used by the "old" irremote driver as I already did patch some things there.

In that case your full support driver can quickly be updated when a new librarie is released while the "old" driver just has to wait.

**Comment by gonzzzales** [comment]
Hello!!!
I try to use USE_IR_REMOTE_FULL options, but i have error while compilation.
In this line String sendACJsonState(const stdAc::state_t &state) {
i have error xdrv_05_irremote_full:113:30: error: 'stdAc' does not name a type

Please help!!!!!

**Comment by s-hadinger** [comment]
Compile using tasmota-ir or tasmota-ircustom.

**Comment by gonzzzales** [comment]
Sorry, but how i must do it? I tryed to uncomment stroke tasmota-ir in file platformio.ini and replace #define USE_IR_REMOTE to #define USE_IR_REMOTE_FULL in file my_user_config.h, but still got the same error.

**Comment by s-hadinger** [comment]
Just uncomment `tasmota-ircustom` and you're done. It automatically enables all protocols.

**Comment by eku** [comment]
Does the update process still work with such a large firmware image? Would it make sense to use the full flash of the IR-ESP modules, which is typically 2MB or more, instead of just the first 1MB?

**Comment by s-hadinger** [comment]
That's why you need to disable any feature you don't need. `tasmota-ir` disables a lot of features. You can start from this one too (no need to touch the `#define USE_IR_REMOTE_FULL` - it's automatic).

What are you trying to do?

**Comment by eku** [comment]
@s-hadinger I read from your comment that this functionality will not be included in any of the standard images but only in self-made firmware images.

**Comment by gonzzzales** [comment]
i try to uncomment tasmota-ircustom, but still not work((
i have installed esp bord from board-manager, i need to do something more with platform.txt or borads.txt?
This command in console IRhvac {"Vendor":"xx"} have the answer - stat/tasmota_534FE1/RESULT = {"Command":"Unknown"}

**Comment by gonzzzales** [comment]
When i flash tasmota32-ir.bin file with tasmotizer it work, but i want to use new version of IRRemote library

**Comment by s-hadinger** [comment]
Use `tasmota-ir` from the development branch here: http://ota.tasmota.com/tasmota/

It already includes IRRemoteESP8266 v2.7.10 since yesterday: #9203

**Comment by gonzzzales** [comment]
Thanks a lot, now it work!!!
One more question, is it possible to make POST-request to operate with it?
I try to do this http://192.168.0.106/cm?cmnd=IRHvac with JSON Content {"Protocol":"FUJITSU_AC","Power":"Off"}, but got this answer
{
    "IRHVAC": "Wrong Vendor, Mode or FanSpeed"
}

How must i fill request correctly?

**Comment by gonzzzales** [comment]
I found the rigth way!!!
Thanks a lot

**Pull request merged**
