### PR TITLE
Add custom build environment

### PR DESCRIPTION
**Pull request by claybar**
## Description:

Currently to build a custom build the platformio.ini file needs to be edited.  This method has a few downsides,
- The edited file needs to often be stashed when doing a git pull
- The final build is still labeled according to the build env (sonoff, display etc).  Makes it difficult to establish the build is actually custom
- Custom builds are difficult to perform on an automated system because of the editing required

Some of these issues could be solved by having a copy of the repo, but then needs to be rebased regularly.

This PR attempts to solve this by adding a new env to the build `sonoff-custom`, automatically setting USE_CONFIG_OVERRIDE.

There is one current issue, the build will fail on this new environment because the file `user_config_override.h` does not exist by default.  I haven't got a solution to this as yet, but will work on this is if the general idea of this PR is acceptable.  I welcome any input on this.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to add to _changelog.ino_ file without updating version)
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works.
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by claybar** [comment]
As expected this PR did not build successfully on Travis because of the missing file issue of the new `sonoff-custom` env.

It also failed because of `sonoff-sensors`, but this is because of an issue in the upstream `development` branch.  Once this is sorted I will merge it into this PR.

**Comment by meingraham** [comment]
@claybar 

There are occasions when one wants to build sonoff, sonoff-sensors, sonoff-minimal, etc., while also using user_config_override.h. Thus "custom" is not the only time the compiler directive is used.

The only line in platform.ini that needs to be modified is to uncomment -DUSE_CONFIG_OVERRIDE in the [common] section. This then gives you the option of compiled any of the firmware variants while also using one's own custom settings.

I would vote down adding this section as "custom" can have differing meanings for users and may only add confusion. When one retrieves a fresh copy of the code, all you need to do is edit the one line and now you can compile any "custom" variant.

Of course, you are always free to maintain your own fork which gives you the option of doing it the way you prefer.

Regards.

Mike

**Comment by arendst** [comment]
I think Mike stated it well.

It's almost the same procedure I use (I just keep my own copy of platformio.ini and merge changes when the come along).

**Comment by ascillato2** [comment]
Closing this PR as it is not going to be merged.

Thanks for sharing your ideas.

**Comment by claybar** [comment]
While frustrating, I can see some logic behind this.  Although I agree changing one line is all it takes (and this still remains in this PR), this is still not ideal for automated systems.  You also end up with a binary without a name indicating it is not a 'standard' build.

I will move forward with a custom fork I think.  And hope there isn't a CODE_IMAGE 7 added to the main  repo.

**Comment by meingraham** [comment]
@claybar 

You may want to get in touch with @andrethomas. He developed and maintains the scripting that builds all of the Tasmota firmware variants in the hackbox repository. I believe he uses PlatformIO and generates all of the binaries for each of three different cores with all of the associated variants (sonoff, sonoff-classic, sonoff-sensors, sonoff-minimal, etc.). He may be able to provide some guidance on the automation of binary compilation while providing your desired customized settings as well as specific binary naming options.

Cheers!

Mike

**Comment by claybar** [comment]
Thanks, I will keep that in mind..

I wasn't referring to the filename of the binary, that is easily changed with a script.  I am more meaning the string contained within the binary, the one that is displayed on the 'information' page of the webserver.  This will display something like `(sonoff)` or '(display)` even when the config has been changed.  This string comes from `i18n.h` and is selected by the value of CODE_IMAGE, hence my comment above about using a new value of 7.  Even if I do this in a custom fork it may get clobbered one day if the main repo ever uses 7 for something else.

**Comment by meingraham** [comment]
@claybar 

re: filename & image name - Andre's build script incorporates both.

**Pull request closed without merging**
