### PR TITLE
New feature Auto Clear Remote Temp for MiElHVAC

### LINKED ISSUE #22365: MiElHVAC Remote Temp and reverting to internal temp
### PROBLEM DESCRIPTION
After sending command with remote temperature to miel hvac unit the unit correctly reports the new room temperature BUT 
the unit never reverts to internal temp.(waiting time of over 10minutes)
Tried sending  0 temp  but instead of reverting to internal temp sensor it shows 10.
(cmnd/tasmota_xxx/HVACRemoteTemp) 

only power cycling the unit fixes the problem

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by grzegorz914**
## Description:
* This PR add auto clear remote temperature function
* This function is called on first run and also `10sec` after the remote temperature stop updating its value
* Send `clear` manually is also available
* The auto clear time is in (ms), default is `10000ms`, can be changed with command `HVACRemoteTempClearTime`

**Related issue (if applicable):** fixes #22365

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.1.0.241023
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by mamrai1** [comment]
I think 10sec are not enough. Maybe set the time to follow teleperiod ? Or 60 sec are more realistic

**Comment by grzegorz914** [comment]
Why is not realistic? you can call Remote Temp every 1 sec or quickly.

**Comment by mamrai1** [comment]
I mean realistic for an Hvac operation…the default in swicago library i think is 3 minutes…

**Comment by grzegorz914** [comment]
10 sec is very long time, the microcontroller respond time is in milliseconds. Where You see the problem to send data for example every 5 sec. I think the data need to be operated as quickly as possible.

**Comment by mamrai1** [comment]
Ok. Let imagine 2 scenarios:
1. The remote temperature sensor is on the same microcontroller: yes 10 sec is more than enough but
2. The remote temperature sensor  is on another controller (in the same room of course) and sends the data via the mqtt server or directly on the controller on the unit: it does make sense to send the readings at teleperiod ….

**Comment by grzegorz914** [comment]
I use PLC to communicate with my microcontrollers, the 10sec is very long time where my loop in code is 7ms. Update data every few seconds is not a problem and also is nothing for CPU load. I don’t understand where is the problem, You can send the Remote Temp every 1sec, 2sec, 500ms etc. This technically is not a problem.

**Comment by mamrai1** [comment]
Many users use wifi/mqtt…  Would be ok only a check in the mqtt loop if there is disconnection from the mqtt server?

**Comment by mamrai1** [comment]
Also in looked at mitsubishi2mqtt project and the time is set at 5 minutes !  (lines ~ 1350)

https://github.com/gysmo38/mitsubishi2MQTT/blob/master/src/mitsubishi2mqtt/mitsubishi2mqtt.ino

**Comment by grzegorz914** [comment]
This is wrong, in 5min the temp can changed from 20 to 25 grad. What happened if set temp is set to 23? nothing, just heating because the remote temp was not refreshed.

**Comment by mamrai1** [comment]
I do agree that in some situations the 5min is too long but also in some  situations the 10sec is too short. :)

**Comment by grzegorz914** [comment]
What is the benefit to get longer time? 
Why the 10sec time is not OK?,  because for me shorter time is always better because gat more real time data to the device.

**Comment by grzegorz914** [comment]
I can make the auto clear time configurable but I have not enough skill with Tasmota to store it in non-volatile memory. In other case will always revert to default after restart.  May be someone can help.

**Comment by arendst** [comment]
Make it a command.

This can then be used in a persistent rule during restart/boot and set the desired parameter like it was persistent.

This way no additional resources are neede.

**Pull request merged**
