### PR TITLE
Add Bugfix Arduino Core 2.5.1 and use as default

### PR DESCRIPTION
**Pull request by Jason2866**
Since bugfix release is still not availible via orig. Platformio Github it is donwloaded via forked source from https://github.com/Jason2866/platform-espressif8266.git#Tasmota

## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by s-hadinger** [comment]
Nice and very timely, I was needing specific features from 2.5.1 WiFiClientBearSSL.cpp.

Btw, I suggest we also add `-DBEARSSL_SSL_BASIC` in the build flags. When using TLS, this flag avoids loading all the Elliptic Curves algorithm, and saves ~45KB of flash. Anyways, Elliptic Curves are far too slow for ESP8266 and the handshake would take more the 5 seconds. With this flag we limit to RSA algorithms which are faster.

**Comment by s-hadinger** [comment]
One more thing, it looks like 2.5.1 has just been released on Platform.io.

Version looks ugly but this works:
```
[core_2_5_1]
platform                  = espressif8266@6455ab7
```

**Comment by Jason2866** [comment]
@s-hadinger ` platform                  = espressif8266@6455ab7` Is not a solution for Windows users
image

**Comment by Jason2866** [comment]
The setup which i provide builds a error free enviroment:

```
PlatformManager: Installing platform-espressif8266
espressif8266 @ 6455ab7 is already installed
Uninstalling toolchain-xtensa @ 1.40802.0:      [OK]
The platform 'https://github.com/Jason2866/platform-espressif8266.git#Tasmota' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.
PackageManager: Installing toolchain-xtensa @ ~1.40802.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
PackageManager: Installing framework-arduinoespressif8266
git version 2.19.1.windows.1
Cloning into 'C:\Users\Hans\.platformio\packages\_tmp_installing-mp973n-package'...
remote: Enumerating objects: 1567, done.
remote: Counting objects: 100% (1567/1567), done.
remote: Compressing objects: 100% (1345/1345), done.
remote: Total 1567 (delta 190), reused 806 (delta 63), pack-reused 0
Receiving objects: 100% (1567/1567), 23.69 MiB | 5.46 MiB/s, done.
Resolving deltas: 100% (190/190), done.
Checking out files: 100% (1267/1267), done.
Submodule 'libraries/ESP8266SdFat' (https://github.com/earlephilhower/ESP8266SdFat.git) registered for path 'libraries/ESP8266SdFat'
Submodule 'libraries/SoftwareSerial' (https://github.com/plerup/espsoftwareserial.git) registered for path 'libraries/SoftwareSerial'
Submodule 'tools/esptool' (https://github.com/espressif/esptool.git) registered for path 'tools/esptool'
Submodule 'tools/pyserial' (https://github.com/pyserial/pyserial.git) registered for path 'tools/pyserial'
Submodule 'lwip2' (https://github.com/d-a-v/esp82xx-nonos-linklayer.git) registered for path 'tools/sdk/lwip2/builder'
Submodule 'tools/sdk/ssl/bearssl' (https://github.com/earlephilhower/bearssl-esp8266.git) registered for path 'tools/sdk/ssl/bearssl'
Cloning into 'C:/Users/Hans/.platformio/packages/_tmp_installing-mp973n-package/libraries/ESP8266SdFat'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 3624 (delta 10), reused 16 (delta 7), pack-reused 3604
Receiving objects: 100% (3624/3624), 10.15 MiB | 1.48 MiB/s, done.
Resolving deltas: 100% (1961/1961), done.
Cloning into 'C:/Users/Hans/.platformio/packages/_tmp_installing-mp973n-package/libraries/SoftwareSerial'...
remote: Enumerating objects: 957, done.
remote: Total 957 (delta 0), reused 0 (delta 0), pack-reused 957
Receiving objects: 100% (957/957), 180.29 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (516/516), done.
Cloning into 'C:/Users/Hans/.platformio/packages/_tmp_installing-mp973n-package/tools/esptool'...
remote: Enumerating objects: 1940, done.
remote: Total 1940 (delta 0), reused 0 (delta 0), pack-reused 1940
Receiving objects: 100% (1940/1940), 7.13 MiB | 4.68 MiB/s, done.
Resolving deltas: 100% (1200/1200), done.
Cloning into 'C:/Users/Hans/.platformio/packages/_tmp_installing-mp973n-package/tools/pyserial'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 5825 (delta 5), reused 18 (delta 5), pack-reused 5807
Receiving objects: 100% (5825/5825), 1.62 MiB | 2.83 MiB/s, done.
Resolving deltas: 100% (4264/4264), done.
Cloning into 'C:/Users/Hans/.platformio/packages/_tmp_installing-mp973n-package/tools/sdk/lwip2/builder'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 932 (delta 0), reused 2 (delta 0), pack-reused 927
Receiving objects: 100% (932/932), 453.45 KiB | 1.40 MiB/s, done.
Resolving deltas: 100% (544/544), done.
Cloning into 'C:/Users/Hans/.platformio/packages/_tmp_installing-mp973n-package/tools/sdk/ssl/bearssl'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 2637 (delta 47), reused 53 (delta 32), pack-reused 2539
Receiving objects: 100% (2637/2637), 1.90 MiB | 3.25 MiB/s, done.
Resolving deltas: 100% (2059/2059), done.
Submodule path 'libraries/ESP8266SdFat': checked out 'f0962921955e2503243f28de0fdc9ac188177ffb'
Submodule path 'libraries/SoftwareSerial': checked out 'd4ae180f33347c851dc2e51ce1779f02b4d3fa11'
Submodule path 'tools/esptool': checked out '9ad444a6e06e58833d5e6044c1d5f3eb3dd56023'
Submodule path 'tools/pyserial': checked out 'c54c81d933b847458d465cd77e96cd702ff2e7be'
Submodule path 'tools/sdk/lwip2/builder': checked out '2314329c86cb7eb9670e3adf7632bd52001f45cd'
Submodule 'lwip2-src' (https://git.savannah.nongnu.org/git/lwip.git) registered for path 'tools/sdk/lwip2/builder/lwip2-src'
Cloning into 'C:/Users/Hans/.platformio/packages/_tmp_installing-mp973n-package/tools/sdk/lwip2/builder/lwip2-src'...
remote: Counting objects: 52667, done.
remote: Compressing objects: 100% (12341/12341), done.
remote: Total 52667 (delta 39682), reused 52649 (delta 39672)
Receiving objects: 100% (52667/52667), 10.06 MiB | 4.00 MiB/s, done.
Resolving deltas: 100% (39682/39682), done.
Submodule path 'tools/sdk/lwip2/builder/lwip2-src': checked out '159e31b689577dbf69cf0683bbaffbd71fa5ee10'
Submodule path 'tools/sdk/ssl/bearssl': checked out 'a143020fe65e2ae11a4f96485c903b6133e1bbc7'

```

**Comment by s-hadinger** [comment]
Platform.io is still a mystery to me. First time I tried nothing happened, it didn't download the project from your github repo. Now it works.

**Comment by Jason2866** [comment]
@s-hadinger  platformio has a complex build structure to setup a environment.
I still do not understand all details. Hell is try to understand how linking works
Did invest some time in. Still a miracle...

**Pull request merged**
