### PR TITLE
Remove support for outdated cores and add core pre 2.6 (Arduino IDE)

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

Support for core 2.5.2 dropped. Housekeeping

**Edit:** 
Remove core 2.4.2 and 2.3.0. too. Removed Arduino OTA
_Add support for core pre 2.6. for Arduino. No additional setup needed._
Changed wiki: https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core pre-2.6
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
@Jason2866 do you know if your pre-2.6.0 core works in Arduino IDE?

**Comment by Jason2866** [comment]
No, it doesnt work because setting up a working! freezed staged version for Arduino IDE is horrible to do. I have looked into and gave up. There where always new things coming up.
Imho using Arduino IDE for building a complex project like Tasmota is a pain....

**Comment by andrethomas** [comment]
It is possible for us to provide a board JSON file for the Arduino IDE based on the pre-2.6 from @Jason2866

**Comment by andrethomas** [comment]
I think the question is whether or not we actually want to go that far... I like that we have simplified things by dropping the old cores but I think as we have with platformio.ini the option is still there for the user to use if they chose to do so. Perhaps the same could be true for Arduino IDE.

**Comment by Jason2866** [comment]
I vote for drop Arduino IDE support. If the setup for pre2.6 is done and it works correct
there is still the mess with copy this and that stuff in the extra installed portable Arduino IDE.
We have every now and than users in Discord with Tasmota and Arduino IDE problems

**Comment by effelle** [comment]
Arduino IDE is obsolete, and a PRO version is coming:
https://blog.arduino.cc/2019/10/18/arduino-pro-ide-alpha-preview-with-advanced-features/

**Comment by arendst** [comment]
@effelle Arduino Pro is Alpha code. Will take years to become stable as most people already started using platformio.

But yes, I'm afraid we will have to get rid of Arduino IDE in favour of platformio.

**Comment by effelle** [comment]
I know Theo, was presented officially on Rome Maker Faire last week, but sooner or later they will probably quit the old IDE.

**Comment by Jason2866** [comment]
I think this one works `https://github.com/Jason2866/Arduino/releases/download/2.5.3/package_esp8266com_index.json`
Install as one and only `Boards Manager URL`
Give it a try

**Comment by andrethomas** [comment]
There is nothing that can be done in the Arduino IDE that cannot be done in PIO.

Drop it @arendst :)

**Comment by joba-1** [comment]
Hi,

* I understand the reasons to drop older cores with security bugs
* I understand Arduino IDE is hard to use for complex projects like this (or anything but beginner stuff imo)

Still, the Arduino IDE is _the_ entry point for IoT beginners.
So dropping support could raise the bar too high for some people that might otherwise enter their tasmota experience tour.

**Comment by andrethomas** [comment]
@joba-1 That is true I guess...

**Comment by Jason2866** [comment]
I dont agree with @joba-1  It is a mess to setup Arduino IDE for Tasmota. No other IDE needs so many
steps to get it going. For startes is Gitpod! No install and you get your firmware in 5 minutes.

**Comment by effelle** [comment]
@joba-1 :
> I understand Arduino IDE is hard to use for complex projects like this (or anything but beginner stuff imo)

> [...]So dropping support could raise the bar too high for some people that might otherwise enter their tasmota experience tour.

These two statements are a little contradictory, you seem to be against dropping Arduino IDE but at the same time you admit Tasmota is too complex for it...  
I'm not polemical, I just want to understand your point of view. 
I develop for IoT under VS Code/PlatformIO and sometime even for Python (my daily driver is Pycharm). When I'm not on my workstation I use Gitpod, easy to configure for a quick to compile and download. In both cases I can firmly say the productivity is on another level when compared to Arduino IDE. 

F.

**Comment by joba-1** [comment]
@effelle no problem.

Arduino IDE is easy to use for beginners (for blink type projects) but it is hard to setup a complex project like tasmota for maintainers to keep it easy to use.

@Jason2866 
What I describe is exactly my personal experience. I knew Arduino IDE, so felt comfortable trying to compile tasmota following the wiki steps. I probably wouldn’t have bothered if it involved learning a new, cloud based development environment, even if overall it is easier to use (which it is).

**Comment by Jason2866** [comment]
Edit: PR changed. Delete all old outdated cores and added core pre 2.6 for Arduino IDE

**Comment by arendst** [comment]
> I think this one works https://github.com/Jason2866/Arduino/releases/download/2.5.3/package_esp8266com_index.json
Install as one and only Boards Manager URL
Give it a try

Just did and it happily compiles, at least using my override file.

**Comment by arendst** [comment]
The changed ``boards.txt`` and ``platform.txt`` files contained the OTA upload functionality for the Arduino IDE. To keep the functionality with pre-2.6.0 I have changed them both. So yes, there are still changes needed to these files if OTA upload is needed (as I used).

Let's not run too fast. The upcoming release should still support Arduino IDE.

The following may drop support.

**Comment by Jason2866** [comment]
okay. 
Pre 2.6 can be used now from everyone. The support of `-u _printf_float -u _scanf_float` is disabled already in the build. The OTA upload is a feature (i think) only you use :-) So i see no need for a extra
file for core pre 2.6.

**Comment by andrethomas** [comment]
@Jason2866 I'm going to make a prediction here now to say in a few months time you will be saying

> Core 2.6.0 needs to be deleted ;-)

**Pull request closed without merging**
