### PR TITLE
SDM120 power meter - new metrics

### PR DESCRIPTION
**Pull request by gtortone**
Hi,
I added new metrics to SDM120 power meter (reactive power and apparent power) and baud configuration for RS485.

Regards,
Gennaro

### CODE REVIEW

**Comment by arendst** [comment]
Hi Gennaro, any chance you get rid of the three .vscode files?

This makes integration for me as easy as selecting the Merge Pull request button?

**Comment by gtortone** [comment]
Hi Theo,
sorry about it !! how can I fix this for future PRs ?

Thanks !

**Comment by gtortone** [comment]
I did it !

**Comment by Dees7** [comment]
Hello. 
I was able to connect SDM120 through MAX485 to ESP8266 board.
There is an direction pins on MAX485. What pin should I select and how configure ?

**Pull request merged**
