### PR TITLE
add options for INA3221 driver

### PR DESCRIPTION
**Pull request by fb-pilot**
## Description:
A fresh try ... more defines for sensor100 INA3221 driver and extend documentatio
**Related issue (if applicable):#21262 + #1382

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [ ] The code change is tested and works with Tasmota core ESP32 V.3.0.0
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@fb-pilot Current driver `INA3221` fails to compile. Errors occur when linking.
Please have a look and provide a PR to fix. Thx!

**Comment by fb-pilot** [comment]
solved - thanks for testing.

**Comment by Jason2866** [comment]
@fb-pilot wrong folder for the driver ;-)

**Comment by fb-pilot** [comment]
uups - that was too late yesterday night :-((

**Pull request merged**
