### PR TITLE
Ble esp32

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:
Introducing xdrv_48_BLE_ESP32.
This PR is Ready.

Introduces a generic ESP32 BLE 'driver' designed to be used by other device drivers so that BLE can be used by multiple 'drivers' at once.

### The issue:
There are two BLE related xSns drivers - iBeacon (xsns_52) and a Sensor driver (xsns_62) which can be built in to support native ESP32 BLE.  These two drivers conflict, and cannot be used together.
At the moment, adding a BLE sensor would involve creating additional detailed functionality inside the xsns_62 driver for each device which we wished to support, or adding an additional driver.
I believe the style of the suggested generic driver will allow people to use existing sensors (and other BLE devices requiring read/write/notify access) with Tasmota without additional development within Tasmota.
It also allows 'popular' devices to have a specific driver within Tasmota, but sharing the BLE, and not conflicting.

### xdrv_48 provides:
1/ generic BLE scanning, catching advertisments with data, and calling registered callbacks.
2/ generic BLE 'operations'.
an operation can be setup through an API call, and provide a callback on success or failure.
Operations can also be setup and executed via commands, resulting in MQTT output on success or failure.
callbacks can be registered to 'hear' all operations.
3/ callbacks can be registered to see scan results at the end of a scan.

### Example modified drivers:
xsns_52_ibeacon.ino and xsns_62_MI_ESP32.ino are disabled by USE_BLE_ESP32

In their place, these are enabled:
xsns_52_ibeacon_BLE_ESP32.ino and xsns_62_MI_ESP32_BLE_ESP32.ino 
These have been adjusted to instead of using the NimBLE stack directly, to subscribe to services provided by xdrv_48_BLE_ESP32.

I believe I have included all the features required for the two sensor drivers that we have.

### use:
xdrv_48 is enabled via 
USE_BLE_ESP32 and ESP32
BLE may be enabled through a new Configuration button on the web UI, or 'setoption115 1'.
It currently logs all adverts with extra data at LOG_LEVEL_DEBUG_MORE, and is fairly verbose about actions at LOG_LEVEL_DEBUG.
To enable xsns_52_ibeacon_BLE_ESP32 as well, enable USE_IBEACON_ESP32
To enable xsns_62_MI_ESP32_BLE_ESP32 as well, enable USE_MI_ESP32

### documentation
I have added a lot of comments at the top about usage, and some examples are at the bottom of the main file.
A pr is in the wings for updaiing the documentation on the docs site.

### Personal motivation:
I have both temp/humidity sensors and EQ-3 BLE radiator valves spread around a house.
I wanted an ESP32 based device which could act as a WIFI to BLE bridge working with both types of device.
Using the commands on the generic driver, I can read/write/notify against the EQ3 valves, and also hear the temp/humidity (once xsns_62 is updated).
I did not want to add all the bulk of an 'EQ3 driver' to Tasmota, preferring the heavy lifting of the variety of BLE command sets to be dealt with in something like Node Red.

### Requests:
I have prepared the xdrv_48 driver based on requirements gathered from xsns62, xsns52, and from my own EQ3 BLE requirements.  
This will not be a complete set of requirements to be able to read/write any BLE device completely generically, but is probably a fairly good start.
We probably can't create a generic driver which would deal with ALL BLE devices, but it would be really good to get verification that the driver is able to talk to some other devices other than the EQ3 devices.
Scan results are currently not published - there is a lot of information in the debug logs to work with, but I believe that scan results should be published - thoughts on this appreciated (e.g. should you have to ask for them, should they be a web UI feature, etc.).
E.g. thoughts on blocking devices in busy areas would be appreciated.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by btsimonh** [comment]
@Jason2866 - I note your change to Arduino core.  It helps with some BLE/Wifi interaction, but this set works with the release Arduino core too.
As soon as this goes in, I have an EQ3 driver which depends upon it ready as a PR & example of BLE control.

**Comment by fightforlife** [comment]
I would love to see this! I  also have these EQ3 valves and want to conrol them via MQTT. Currently I am using my own simple ESP32 program. But a tasmota integration would be way better!

**Comment by gemu2015** [comment]
nice project!
Although i am not a fan of BLE in home automation (except ibeacon presence monitoring)
i think this is a good approach.

since i also use ESP32 Tasks i want to draw your attention to the fact that the task stack of ESP32 BLE drivers in Tasmota and probably in your project is much too low for stable operation.

in original RTOS stack size is in words, so 2048 would be 8192 and far enough, but on ESP32 RTOS stack size is given in bytes (see ESPRESSIF docs). And 2048 is definitely too low for stable operation.

**Comment by btsimonh** [comment]
@fightforlife 
> I would love to see this! I also have these EQ3 valves and want to conrol them via MQTT. Currently I am using my own simple ESP32 program. But a tasmota integration would be way better!
You can try it here:
https://github.com/btsimonh/Tasmota/tree/EQ3_BLE_ESP32
We will propose a PR for EQ3 once the BLE PR is accepted.
p.s. expect this PR to close, and a new one to open int he next few days....

**Comment by btsimonh** [comment]
@gemu2015 - noted on stack size.  We're already above 2048, should really measure the max used - i understand there are APIs to do this (@Jason2866 - we could do something general here on ESP32 and tasks?).

**Comment by Jason2866** [comment]
@gemu2015 @btsimonh  if the change is possible via sdkconfig for the idf 3.3 build we can do a customized build variant (same process as for the ESP32solo1 build).

**Comment by gemu2015** [comment]
you may determine the needed stack size  by calling uxTaskGetStackHighWaterMark(NULL) in the task itself. this call returns the max needed stack size. you then can set the stack size to a slightly higher value.

i found that at least 4k stack was needed, depending on what is done in the task. when doing HTTPS i did even need about 8k stack.

if stack is too low you may get weird results like random crashes.

**Comment by Jason2866** [comment]
@gemu2015  Thx for the info!

**Comment by btsimonh** [comment]
I believe you can also get a list of tasks, get the name, current stack size, and high water for each - it's probably a core thing - do we have a 'support esp32' type 'driver' to which we could add a command (maybe it's already there somewhere)?

**Comment by gemu2015** [comment]
Tasmota (Arduino) runs with a stack size:
#define CONFIG_ARDUINO_LOOP_STACK_SIZE 8192

this is on the save side. i would not choose a much lower size until you are sure it is enough.

if have tasks that worked with 4096, but i would not go lower.

i only wanted to warn that the existing Tasmota BLE drivers have much too low stack size (2048) to run stable

this documentation has some apis for listing tasks but these are claimed to be only for debug purposes because they burden the cpu and use memory. 

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos.html

**Comment by gemu2015** [comment]
i will try to implement a task list cmd. think would be useful.

**Comment by gemu2015** [comment]
@Jason2866 
you may probably help here. i implemented the list tasks command but can't get it linked in.

vTaskList needs 2 special defines, but these don't help, still unresolved references.

i went through all net references but didn't find a solution yet.

build_flags                 = ${core32.build_flags} -DCONFIG_FREERTOS_USE_TRACE_FACILITY -DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS

[support_command.ino.zip](https://github.com/arendst/Tasmota/files/5808096/support_command.ino.zip)

**Comment by Jason2866** [comment]
It is not in the Arduino ESP32 build. https://github.com/espressif/esp32-arduino-lib-builder/blob/master/sdkconfig#L622

**Comment by gemu2015** [comment]
yes i also saw this, so for the time being start with fairly hight stack size and then determine the stack watermark in the task and adjust the stack size thereafter.

**Comment by btsimonh** [comment]
see revised PR https://github.com/arendst/Tasmota/pull/10600

**Pull request closed without merging**
