### PR TITLE
TOF10120 (I2C) support

### PR DESCRIPTION
**Pull request by cyrilpawelko**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by cyrilpawelko** [comment]
This is the driver to support TOF10120 Time Of Flight laser sensor.
I bought one and wanted to use it with tasmota.
Logic was copied from xsns_77_vl53l1x.ino
Tested with TOF10120 on Wemos D1 (ESP8266) - Distance reporting is accurate

**Comment by arendst** [comment]
Tickle

**Comment by arendst** [comment]
Thx. Merged my way.

**Comment by Lordcybertracker** [comment]
Hello,
Exactly the TOF10120 I am trying to address to Tasmota.

How should I proceed here?

Thanks

**Comment by barbudor** [comment]
TOF10120 is I2Cdriver57
Not included is default build
You need to self compile with `#define USE_TOF10120`

**Comment by Lordcybertracker** [comment]
Hello,
I have now compiled the tasmota myself and that too
#define USE_TOF10120
in the my_user_config inside.
he finds the sensor via i2cscan. but it doesn't show me any values.
What else do I have to adjust?
Thanks

**Comment by barbudor** [comment]
The driver is probably not enabled
Check with command `i2cdriver` that you don't have a `!` in front of number 57.
If you have, enter command `I2Cdriver57 1`

**Comment by sfromis** [comment]
And if you do not have number 57 in the list, you are not using a build with the driver included.

**Comment by Lordcybertracker** [comment]
THX its running.

**Pull request closed without merging**
