### PR TITLE
Add support for light sensor TSL2591

### PR DESCRIPTION
**Pull request by c7haki**
## Description:

add support for light sensor TSL2591

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core pre-2.6
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by digiblur** [comment]
Oooooo... very nice. I have a test setup I did still with this sensor attached when I did my light bulb comparison video.

**Comment by mike2nl** [comment]
It looks to much Adafruit. In the header are to much things we don't need or use in Tasmota. The driver must possible be rewritten to get it conform.

@c7haki look at all the other drivers and chenage the things so that you could get a good PR.

**Comment by ascillato** [comment]
Just a little detail, it is missing in `my_user_config.h` file, the entry:

//#define USE_TSL2591

In order to let users to easily uncomment it, compile and use it. ;)

**Comment by ascillato2** [comment]
Thanks :+1:

**Review by ascillato2 — APPROVED** [review]

**Pull request merged**
