### PR TITLE
ensure minimum interrupt time

### LINKED ISSUE #18949: Issues with Zero Cross Detection
### PROBLEM DESCRIPTION
See attached screenshots showing input AC waveform (GPIO34 set as counter4) and pwm out pin GPIO25 (tried as both PWM and PWM_i) - fundamentally testing the PWM feature with option99 set and PWM frequency set at 100Hz, zero crossing 50Hz rectified mains (100Hz) via optocoupler on GPIO34). (Zero crossing now seems to be mostly working - huge improvement).
Issues are:
 1) Screenshot Stutter,2 - The zero crossing detector is not catching every zero crossing.   Not sure if we can rather set a rising or falling edge.The LED connected in lieu of thyrister is not smooth - but has an erratic flicker. Also not sure if triggering at zero or peak crossing ?

2) PWM waveform - this is a pulse of around 5 - 10us - was expecting a PWM waveform with length set by the pwm slider (but the trigger is useable).

3) Screenshots PWM trigger point - The trigger point should follow the setting of the slider allowing a full waveform to be created by triggering a thyristor or similar - I have tested with the slider on low (maybe 5%), middle and high (maybe 95%).  The low setting trigger point would give full power, the middle point seems to be at random and the high seems to be at midpoint of the waveform.  This would only give at best 50% power setting - not 100%. 

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): ESP32-WROOM-32D DEVKIT
- [ ] Tasmota binary firmware version number used: 12.5.0.4 on ESP32_____
  - [ X] Pre-compiled
  - [ ] Self-compiled
- [x ] Flashing tools used: Tasmota Web installer
- [x ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here: (not sure if you wanted me to run the command above?)
09:28:38.844 CMD: Backlog Template; Module; GPIO 255
09:28:38.889 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/stat/RESULT = {"NAME":"Load-ctl","GPIO":[0,0,0,0,0,0,0,0,224,4896,225,4897,0,0,0,0,0,0,0,0,0,416,0,0,0,0,0,0,0,288,355,4706,4740,0,0,4707],"FLAG":0,"BASE":1}
09:28:39.096 MQT: 2_Gr/Load-ctl/Tas_Testint_3EA07C/stat/RESULT = {"Module":{"0":"Load-ctl"}}
09:28:39.325 MQT: Gr/Load-ctl/Tas_Testint_3EA07C/stat/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"4896":"ADC CT Power1"},"GPIO14":{"225":"Relay2"},"GPIO15":{"4897":"ADC CT Power2"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"0":"None"},"GPIO24":{"0":"None"},"GPIO25":{"416":"PWM1"},"GPIO26":{"0":"None"},"GPIO27":{"0":"None"},"GPIO32":{"0":"None"},"GPIO33":{"288":"Led1"},"GPIO34":{"355":"Counter4"},"GPIO35":{"4706":"ADC Input3"},"GPIO36":{"4740":"ADC Temp5"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"4707":"ADC Input4"}}

```
- [x ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
None
  Rules output here:

```
- [x ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
Status 0
(edited out detail)
09:30:31.588 MQT: ----Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota","Tasmota2","Tasmota3"],"Topic":"Tas_Testint_3EA07C","ButtonTopic":"0","Power":7,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
09:30:31.603 MQT: -----_Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32.bin","RestartReason":"Vbat power on reset","Uptime":"0T00:30:50","StartupUTC":"2023-06-23T22:59:41","Sleep":50,"CfgHolder":4617,"BootCount":19,"BCResetTime":"2023-06-13T10:36:03","SaveCount":116}}
09:30:31.614 MQT:-----_Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS2 = {"StatusFWR":{"Version":"12.5.0.4(tasmota32)","BuildDateTime":"2023-06-22T21:59:17","Core":"2_0_10","SDK":"4.4.5.230614","CpuFrequency":160,"Hardware":"ESP32-D0WD-V3 rev.3","CR":"567/699"}}
09:30:31.624 MQT:---------- _Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxx",""],"TelePeriod":15,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","20000080","00026000","00004000","00000001"]}}
09:30:31.658 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS4 = {"StatusMEM":{"ProgramSize":1532,"Free":1347,"Heap":112,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"16405E","FlashFrequency":40,"FlashMode":"DIO","Features":["00000809","9F9AD7CF","0015A001","B7F7BFCF","05DA9BC0","E0360DC7","480840D2","20200000","D4BC482D","000A80B1"],"Drivers":"1,2,3,4,5,7,8,9,10,11,12,14,16,17,20,21,24,26,27,29,34,35,38,50,52,59,60,62,63,66,67,68,82,86,87,88","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,98,103,105,127","I2CDriver":"7,8,9,10,11,12,13,14,15,17,18,20,24,29,31,36,41,42,44,46,48,58,62,65,69,76,77"}}
09:30:31.675 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS5 = {"StatusNET":{"Hostname":"Tas-Testint-3EA07C-0124","IPAddress":"192.168.X.X","Gateway":"192.168.X.X","Subnetmask":"255.255.255.0","DNSServer1":"192.168.X.X","DNSServer2":"0.0.0.0","Mac":"40:22:D8:3E:x.x,"IP6Global":"","IP6Local":"fecxx07c","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"192.168.x.x","DNSServer2":"0.0.0.0","Mac":"00:00:00:00:00:00","IP6Global":"","IP6Local":""},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
09:30:31.691 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS6 = {"StatusMQT":{"MqttHost":"x.x.io","MqttPort":1883,"MqttClientMask":"xxxx-DVES_%06X","MqttClient":"xxxx-DVES_3EA07C","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
09:30:31.704 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS7 = {"StatusTIM":{"UTC":"2023-06-23T23:30:31","Local":"2023-06-24T09:30:31","StartDST":"2023-10-01T02:00:00","EndDST":"2023-04-02T03:00:00","Timezone":99,"Sunrise":"13:47","Sunset":"05:57"}}
09:30:31.868 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS10 = {"StatusSNS":{"Time":"2023-06-24T09:30:31","COUNTER":{"C4":1184},"ANALOG":{"CTEnergy1":{"Energy":0.001,"Power":0,"Voltage":230,"Current":0.000},"CTEnergy2":{"Energy":0.000,"Power":0,"Voltage":230,"Current":0.000},"A3":0,"A4":449,"Temperature5":52.3},"ESP32":{"Temperature":53.3},"TempUnit":"C"}}
09:30:31.888 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/stat/STATUS11 = {"StatusSTS":{"Time":"2023-06-24T09:30:31","Uptime":"0T00:30:50","UptimeSec":1850,"Heap":113,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":111,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":39},"POWER1":"ON","POWER2":"ON","POWER3":"ON","Dimmer":97,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"xxxx","BSSId":"EC:BE:DD:4A:x:x","Channel":11,"Mode":"11n","RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:03"}}}
09:30:34.911 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/tele/STATE = {"Time":"2023-06-24T09:30:34","Uptime":"0T00:30:53","UptimeSec":1853,"Heap":119,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":167,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":39},"POWER1":"ON","POWER2":"ON","POWER3":"ON","Dimmer":97,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"xxx","BSSId":"EC:BE:DD:4A:x.x","Channel":11,"Mode":"11n","RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:03"}}
09:30:35.075 MQT: _Gr/Load-ctl/Tas_Testint_3EA07C/tele/SENSOR = {"Time":"2023-06-24T09:30:34","COUNTER":{"C4":1512},"ANALOG":{"CTEnergy1":{"Energy":0.001,"Power":0,"Voltage":230,"Current":0.000},"CTEnergy2":{"Energy":0.000,"Power":0,"Voltage":230,"Current":0.000},"A3":0,"A4":261,"Temperature5":138.3},"ESP32":{"Temperature":53.3},"TempUnit":"C"}

```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
Ongoing issue

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Ongoing issue

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

1) It is expected that the zero crossing detector would trigger consistently for every crossing.  Might be noise on the waveform (top is a bit saturated) - but this is on a test bench and real implementation will be noisier.  Can we do a rising or falling edge slightly out of the noise ? Falling might be better as allows a short delay before triggering of the next cycle for 100%.

2) It is expected the PWM waveform will trigger consistently at a specific crossing point.

3) It was expected that we get a pulse of a certain width from the PWM - but not a serious issue as all we really need is a correctly positioned pulse to trigger power circuitry which switches off at Zero crossing.  

4) Ideally at full power the pulse will start at the zero crossing, and at lower settings start later in the waveform reducing the on time.

5) Very Low priority - Incidental to this exercise we have noticed the mains frequency swings a fair bit compared to the 100Hz of the PWM.  If we implement with fixed triggering delays on variable freq mains the power out will vary.  Ideally the triggering delays should be tied to the mains frequency - or % of time between zero crossings which should be accurate enough.  Will also allow for auto detection of 50 or 60Hz mains.

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
Two sets of screen shots.  Note the scope is triggering on the rectified mains input - rising edge at about 1.7V.  Any less and the scope battles to hold the trigger point.

Stutter - image
Stutter2 - 
image

Triggering point
Low -
image
Medium - 
image
High - 
image

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
We are using MQTT extensively - and are resetting the counter with every MQtt report - 15secs.

I am not really a programmer and only know enough to be dangerous ... but very happy to further test if you need testing done.

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by stefanbode**
prevent interrupts <30 micro seconds because sometimes see crashes on esp8266. esp32 stop of interrupt >30microseconds and < 105microseconds

## Description:
fix #18949
**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.11
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by SteWers** [comment]
@stefanbode: I tested the version. It works very fine, but when I set Dimmer or ZCDimmerSet to 100, the light switches off. 99.99 is OK.

**Comment by stefanbode** [comment]
This makes no sense. On 100% the enable_time is 0. This does mean after the zero-cross event the first interrupt will set the GPIO to HIGH. The only explanation is in hardware. The event is raised BEFORE the zero cross actually is 0V. In this case the HIGH signal come before the 0V signal that "kill" the triac signal. There could be similar problems with 0% when the zero cross comes to late after the real zero cross. The only workaround is a dead zone at 0 and 100%. Can you check if 99.9% is working and what enable time you get the log files.

**Comment by SteWers** [comment]
That makes really no sense, but there is a simple bug caused by unsigned values in line 153. As a negative value can not be processed, the 100% value fails. I did this small change, to keep the values always positive in the calculation and comparing:
`if (time_since_zc+5 >= ac_zero_cross_dimmer.enable_time_us[i] && !ac_zero_cross_dimmer.triggered[i] ) {`

**Comment by stefanbode** [comment]
Ohh yes. Absolutely right. Will fix now. Good catch.

**Comment by stefanbode** [comment]
Fixed with #19221

**Pull request merged**
