### PR TITLE
report signal strength in dBm over MQTT

### LINKED ISSUE #7113: implement option to present WiFi RSSI in dbm instead of percent
**Have you looked for this feature in other issues and in the wiki?**  

Yes,

**Is your feature request related to a problem? Please describe.**  

Having the RSSI in percent instead of dbm is user friendly, but not very precise.

**Describe the solution you'd like**  

A SetOption to choose between the current percent presentation and dbm.

**(Please, remember to close the issue when the problem has been addressed)**  

I would implement this myself and send a PR, just wanting to know if this has a chance of being accepted before I invest the time.

### PR DESCRIPTION
**Pull request by RoadRunnr**
## Description:

* report signal strength in dBm over MQTT
* include dBm in debug log and in WebIf information display.

**Related issue (if applicable):** fixes #7113

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Great!

As for me just get rid of the setoption. Makes code smaller and dBm is implemented nicely.

So pls remove setoption and I'll merge

**Comment by ascillato** [comment]
So as to not break backwards compatibility, the json message will include both values? RSSI % and dBm?

**Comment by arendst** [comment]
It's just an additional json field/value pair so should be no issue for json processors.

**Comment by arendst** [comment]
Ah I see. I choose the wrong name for rssi quality...

**Comment by arendst** [comment]
But with this solution you have no idea if it's rssi quality or just rssi.

We need a new value pair for rssi in dBm

**Comment by ascillato** [comment]
> We need a new value pair for rssi in dBm

Totally agree.

**Comment by RoadRunnr** [comment]
updated, SetOption removed, the signal strength is now reported in dBm in a new JSON node called "Signal".

About the JSON, I opted for keeping it as short as possible, it would also be sensible to call it "SignalStrength". Not sure which one is better.

**Pull request merged**
