### PR TITLE
Add MAC address to Home Assistant Discovery Message

### LINKED ISSUE #6226: Add MAC address to Home Assistant Discovery Message
**Have you looked for this feature in other issues and in the wiki?**
Yes, nothing found.

**Is your feature request related to a problem? Please describe.**
Home Assistant is using identifiers like the MAC address or serial numbers to match up devices which are reported by multiple integrations.
I have a device tracker integration set up (Unifi), which creates Home Assistant devices for each device found on the network, identified by their MAC address. Because the MAC address is not provided in the MQTT discovery message by Tasmota, these Home Assistant devices cannot be matched with the devices created by the MQTT integration.
As a result, I now have two entries in my Home Assistant device_registry for every Sonoff on my network.

**Describe the solution you'd like**
The MAC address of Tasmota devices should be included in the payload of the Home Assistant MQTT discovery message as an additional attribute `cns` (see https://www.home-assistant.io/docs/mqtt/discovery/ section _Supported abbreviations for device registry configuration_).

JSON: `"cns": [ ["mac", "$DEVICE_MAC_ADDRESS"] ]`
where $DEVICE_MAC_ADDRESS is the Sonoff's MAC address in FF:FF:FF:FF:FF:FF form (lowercase is also possible).
It needs to be a nested list, because the attribute is itself a listing of identifiable connections and each connection is given as a list with its type as first and value as second element.

**Describe alternatives you've considered**
Leave it like it is and live with multiple device_registry entries for the same device.

### PR DESCRIPTION
**Pull request by caphm**
## Description:

**Related issue (if applicable):** fixes #6226

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by meingraham** [comment]
This is required because HA recently introduced a device registry? Just pinpointing the reason why this is now a requirement for proper operation of the HA auto-discovery feature already in Tasmota.

If a user is using an older version of HA, will having the additional MAC attribute in the payload be ignored? In other words, does this change retain backward compatibility?

How much additional program memory does this change require?

P.S. Are we at the point where Tasmota HA integration needs to be off by default and HA users need to compile their own binaries in order to add HA support? With Gitpod, this is not a huge burden.

**Comment by caphm** [comment]
> This is required because HA recently introduced a device registry? Just pinpointing the reason why this is now a requirement for proper operation of the HA auto-discovery feature already in Tasmota.

HA auto-discovery will still work without this, but there will be mutliple devices created in HA because it is missing the MAC as an identifier to merge potential duplicaes in the device registry. See https://developers.home-assistant.io/docs/en/device_registry_index.html under _Defining devices_.

> If a user is using an older version of HA, will having the additional MAC attribute in the payload be ignored? In other words, does this change retain backward compatibility?

Yes. The additional attribute is part of the `device` object within the payload, which is ignored entirely if HA version doesn't support it (no device registry present).

> How much additional program memory does this change require?

I don't know how to determine that. Do you mean how much larger the binary will become or the memory usage during operation?
I can't compare the binary sizes right now, but it should be minimal. There's 58 characters being added to the `const char[]` in total (29 each), plus an additional call to `WiFi.macAddress().c_str()`. It should only be a couple of bytes in total.

> P.S. Are we at the point where Tasmota HA integration needs to be off by default and HA users need to compile their own binaries in order to add HA support? With Gitpod, this is not a huge burden.

That's not for me to provide an opinion on.

**Comment by meingraham** [comment]
Thanks for the information.

re: my P.S. - Yup, meant for Theo... since he'll evaluate this PR an your notes as well.

**Comment by ascillato** [comment]
> P.S. Are we at the point where Tasmota HA integration needs to be off by default and HA users need to compile their own binaries in order to add HA support? With Gitpod, this is not a huge burden.

You are right, but I think that the amount of Tasmota users that also use Home Assistant is enough so as to mantain it enabled by default.

**Comment by emontnemery** [comment]
This change is not needed because serial number is included as identifier in the device info already:
https://github.com/arendst/Tasmota/blob/956f56e0e17f89c79455d1ebcd4c45f477799501/tasmota/xdrv_12_home_assistant.ino#L107

Reverted as part of #7901.

**Pull request merged**
