### PR TITLE
Support for pmsa003i

### PR DESCRIPTION
**Pull request by FunJp**
## Description:

Add support for the PMSA003I I2C air quality sensor

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx. Looks almost ok.

Pls put the global vars in a struct to solve possible duplications.

**Comment by FunJp** [comment]
Hey,

I assume that this was what you had in mind about all the global variables ? If you also would prefer to also have the followings in the struct just let me know.

`bool pmsa003i_type = false;
bool pmsa003i_ready = false;
uint8_t warmup_counter;  // count for warmup`

Also, while looking thru other sensor, I notice that the xsns_18_pms5003.ino could also benefits from using a similar struct. I won't touch it in this PR, but it might be worth a look too at some point

**Comment by arendst** [comment]
Yeah I like to have them all in a struct but then do not call it ``data`` as being the most obvious variable name....

Call it related to your driver like ``Pmsa003i`` which is most probably unique within the tasmota global variable world.

**Comment by arendst** [comment]
Thx.

**Pull request merged**
