### PR TITLE
Change remove floating point libs from IRAM

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Changed linker script to move all floating point libs from libgcc.a out of IRAM. No interrupt handler is using float/double so we can safely move them back to IROM.

This is a quick and dirty patch, I'm sending a PR to Arduino Core in parallel to make it a compile flag.

IRAM size reduction:

- Tasmota (std): from 31660 to 30620 **(-1040 bytes)**
- Tasmota-sensors: from 31656 to 30616 **(-1040 bytes)**
- Tasmota-IR: from 29364 to 28324 **(-1040 bytes)**

The actual change is adding the following in `eagle.app.v6.common.ld` in section `.irom0.text:`:

```
    *libgcc.a:*f2.o(.literal .text)
    *libgcc.a:*f3.o(.literal .text)
    *libgcc.a:*fsi.o(.literal .text)
    *libgcc.a:*fdi.o(.literal .text)
    *libgcc.a:*ifs.o(.literal .text)
    *libgcc.a:*idf.o(.literal .text)
```

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core Tasmota_core_stage
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
5 test devices with different sensors does work without a issue with this PR

**Comment by arendst** [comment]
I store my source on "Google Drive". This fails the compiler as the linker path contains a space in the path. Moving the source to a non spaced folder works fine.

Working on renaming "Google Drive" to "GoogleDrive"...

**Comment by s-hadinger** [comment]
This is probably not the best way to force a local linker script, but I didn't find a better way.

Anyways, I hope the PR https://github.com/esp8266/Arduino/pull/7180 will be quickly merged in Arduino Core. After that it will only be a compilation flag.

**Comment by arendst** [comment]
Fixed it by removing and re-installing Google Drive pointing it to a renamed folder. Very (in)flexible this Google stuff.

**Comment by Jason2866** [comment]
Another way would be patching the file on the fly.
https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#override-package-files

EspEasy is doing this. Example [PUYA patch](https://github.com/letscontrolit/ESPEasy/blob/mega/patches/puya.patch)

**Comment by s-hadinger** [comment]
That's very interesting, I didn't know this feature. I'm a bit reluctant to use patch files, they can very easily break whenever Arduino updates their files.

**Pull request merged**
