### PR TITLE
Smart Meter Interface: Add support for all common serial transmission modes

### PR DESCRIPTION
**Pull request by ul-gh**
This commit adds support for all common serial transmission modes
with different bit length (5, 6, 7 and 8), one or two stop bits,
even, odd or no parity to the smart meter scripting language.

The changes are backwards-compatible on the user interface side.
==> The changes also work with software serial (TasmotaSerial) if
commit# 56cdefc7e4741ee99ab66b3b80265310d3dada21 is applied.
(From branch: https://github.com/ul-gh/Tasmota/tree/TasmotaSerial_all_modes)

Following example adds a sensor readout using 7bits, even parity,
one stop bit mode for an OBIS based smart meter:

>D
>B
=>sensor53 r
>M 1
+1,2,o7E1,0,9600,grid
1,1-0:1.7.0*255(@1,P_in,W,P_in,2
\#

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with core ESP32 V.1.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Already implemented since a while https://github.com/arendst/Tasmota/commit/00fd7f2f7c62765a95fcde751cf297f1bd37d2d3

**Comment by ul-gh** [comment]
This change is about the [scripting language](https://tasmota.github.io/docs/Smart-Meter-Interface/#meter-definition) (one page further down).

With this change, there should also be no performance issues, also total code size is reduced.

**Comment by Jason2866** [comment]
Needs changes or closing since https://github.com/arendst/Tasmota/commit/56cdefc7e4741ee99ab66b3b80265310d3dada21 will not be merged.

**Comment by ul-gh** [comment]
The scripter code, all the same as before, invokes TasmotaSerial::hardwareSerial() to check if the pin supports the hardware UART and switches accordingly.

The relevant change regarding the interface to the software serial driver is basically only the addition of the second argument when TasmotaSerial::begin() is invoked.

This should work fine in any case, even if TasmotaSerial does not support the addditional transmission protocols, it will just silently ignore the not supported modes. (Which should of course be documented)
```
diff --git a/tasmota/xsns_53_sml.ino b/tasmota/xsns_53_sml.ino
--- a/tasmota/xsns_53_sml.ino
+++ b/tasmota/xsns_53_sml.ino

@@ -2517,50 +2549,35 @@ init10:
[...]
-        if (meter_ss[meters]->begin(meter_desc_p[meters].params)) {
+        if (meter_ss[meters]->begin(meter_desc_p[meters].params, ser_opts) {
```

**Pull request closed without merging**
