### PR TITLE
Zigbee add visual map of network

### PR DESCRIPTION
**Pull request by s-hadinger**
### **Major feature / Experimental**

Added visual map of the Zigbee network, including LQI of each link (if known).

ZbMap_example

Pressing the `Zigbee Map` button triggers an automatic `ZbMap` command and waits until mapping is complete. It takes 2 seconds per device.

Red circle is the coordinator, orange boxes are routers, blue ellipses are end-devices.

Two buttons are also added on the main page, to allow joining of new devices (`ZbPermiJoin`) and Zigbee map (`ZbMap`), and a new visual indicator when joining of new devices is allowed.

ZbPermitJoin

Note: the visual map uses `vis.js` network library, which is not included as it is too big to fit in Tasmota memory. For this reason, viewing the map requires that your browser has internet access. But no data is tranferred to any site and the rendering is done locally in the browser.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by MattWestb** [comment]
Great work Stephan !!!!
And i can see that your Philips HUE bulb have the same bug as my = not deleting end devices that have timed out and keep reporting it in its neighbour table. Hard resetting the bulb and rejoining it and its OK (until next end device is leaving) and perhaps the same with the OSRAM plug (or the IKEA remote have changing parent for some seconds / minutes ago). 
Looks very nice and helping much then having problems with the network :-)))

**Comment by s-hadinger** [comment]
Thanks. Indeed this will probably help many users understand better their zigbee network.

**Comment by MattWestb** [comment]
Is it possible using the EEPROM on the Sonoff board as cache for the `vis.js` file then is being downloaded if the EEPROM is present and dont need waiting for it being downloaded every time loading the map ?
Only brainstorm as usual from my side :)

**Comment by s-hadinger** [comment]
Unfortunately not. Vis.js is more than 600kb in size, way too big for eeprom and a waste for Flash

**Pull request merged**
