### PR TITLE
domoticz blinds -> tasmota support

### PR DESCRIPTION
**Pull request by ahoiahoi**
## Description:

This adds support for Blinds devices in domoticz to send updates to tasmota

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by roondar** [comment]
Hi @stefanbode, can you add your review ?

**Comment by stefanbode** [comment]
I would not move the definitions to main. Maybe we can integrate the additional code into shutter. In general i support the Integration

**Comment by roondar** [comment]
> I would not move the definitions to main. Maybe we can integrate the additional code into shutter. In general i support the Integration

Ok , So may be @arendst can approve the changes ?

**Comment by arendst** [comment]
I'm in favour of Stefan's integration keeping it as confined as possible.

**Comment by stefanbode** [comment]
Give me 24h and will provide a new version with same functionality hopefully. Will keep you posted here

**Comment by stefanbode** [comment]
The crossreference of these two modules are only:

#define D_CMND_SHUTTER_POSITION "Position"
#define D_SHUTTER "SHUTTER"

besides this this xdrv7 could be committed without the change to the shutter driver xdrv27. the proposed changes to xdrv27 do not make it better. In general I think the main topic: D_SHUTTER is ok for the i18n. But there need be a function that you can call to get the other commands. Like the  FUNC_SHOW_SENSOR something that give you in a static order the keys for the additional functions this add-on provide. This would enable that any module can call another module without getting source code reference. Anyhow after some thinking not an easy to solve problem.

**Comment by stefanbode** [comment]
If we move all shutter definitions to i18 and make them conditional with
```
#ifdef USE_SHUTTER

#endif //USE_SHUTTER
```
we can at least avoid impact on the compilation code. I will prepare a push for this change.

**Comment by stefanbode** [comment]
Submitted push #7195 to make your life easier.

**Comment by roondar** [comment]
> Submitted push #7195 to make your life easier.

Well done :)
Thanks you.

**Comment by ascillato** [comment]
@ahoiahoi 

Hi, can you update your PR. Now, you should use the definitions made on #7195 to simplify your changes. Thanks.

**Pull request merged**
