### PR TITLE
Adds new commands to use RCSwitch functionality on Sonoff Bridge with the Portisch firmware directly.

### PR DESCRIPTION
**Pull request by hkiam**
adds new commands to use RCSwitch functionality with the Portisch firmware directly.
Examples:
  RFSwitchOn 10001, 2
  RFSwitchOff 10001, 2

  RFSwitchOn a, 2
  RFSwitchOff a, 2

  RFSwitchSend 0x501014, 24, 1, 10, 350

### CODE REVIEW

**Comment by haegar33** [comment]
I dont understand this new command.  The 2-liner readme shows a syntax with 5 arguments, the example only has 2??  I would have no idea what to use for my setup. Which Portish Version is required? Please provide more information before committing such a patch! It might nevertheless be useful.

**Comment by hkiam** [comment]
## Sonoff-Tasmota RCSwitch Modification

## Info
Send RC codes
Use your Sonoff RF Bridge to operate remote radio controlled devices. This will most likely work with all popular low cost power outlet sockets (see: https://github.com/sui77/rc-switch):<br />
All you need is a Sonoff RF Bridge with Portisch RF-Bridge-EFM8BB1 updated firmware and one or more devices with one of the supported chipsets:
- SC5262 / SC5272
- HX2262 / HX2272
- PT2262 / PT2272
- EV1527 / RT1527 / FP1527 / HS1527
- Intertechno outlets
- HT6P20X
<br />
If yours doesn't work, you might need to adjust the pulse length.<br />

## Details
Since the Portisch firmware with RfRaw (see https://github.com/arendst/Sonoff-Tasmota/wiki/Commands) is able to directly send data directly to the RF chip, this modification uses the RfRaw command and translates the output of the RCSwitch library.
For exmaple the new command **"RFSwitchOn 10001, 2"** will be internally translated to: **"rfraw AA B0 21 03 04 015E 041A 2A62 02010101100110011001010110010101100110011001010110 55"**<br />
So instead of having to get or set up a remote control before having to record the code, the configurations set on the device can simply be used as parameters.<br /><br />
For this I have added three new commands: (The last three parameters are optional!)<br />
- **RFSwitchOn address, channel**[, protocol][, repeats][, pulse]<br />
- **RFSwitchOff address, channel**[, protocol][, repeats][, pulse]<br />
- **RFSwitchSend data, bits**[, protocol][, repeats][, pulse]<br />

More Examples:<br />
  - RFSwitchOn 10001, 2 <br />
  - RFSwitchOff 10001, 2 <br />
  - RFSwitchOn a, 2 <br />
  - RFSwitchOff a, 2 <br />
  - RFSwitchSend 0x501014, 24, 1, 10, 350 <br />
  
## Thanks
This modification based on the great work from the Tasmota Firmware, the Portisch RF Firmware and the RCSwitch Library.<br />
https://github.com/sui77/rc-switch<br />
https://github.com/Portisch/RF-Bridge-EFM8BB1<br />
https://github.com/sui77/rc-switch/<br />
<br />
<br />
<br />

**Comment by Jason2866** [comment]
@hkiam  with Portisch firmware all this protocols do already work.
Since all is already supported there is no need to change and waste flash space

**Comment by andrethomas** [comment]
Its up to @arendst but I personally don't think this adds value since the protocols listed are already supported directly by the Portisch firmware.

**Comment by arendst** [comment]
As noted by dev team it will increase code size while functionality stays the same.

Thx for your hard work but for now this will not be implemented.

**Pull request closed without merging**
