### PR TITLE
#enhancement: Adding option to compensate on a global level temperature

### PR DESCRIPTION
**Pull request by stefanbode**
## Description:
nearly all sensors have some deviation on temperature based on different reasons. To compensate for all different kinds o temperature sensors would result in a heavy add of code. Therefore I use the "small edition" with only ONE compensation factor. If there are more sensors this compensation will work for all temp-sensors. Comp can be between -12.6 °C/F and +12.6°C/F. It should suitable for most cases. Just digital +- independent if it is C or F. If changing the UNIT, the compensation will be wrong.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x ] The pull request is done against the latest dev branch
  - [ x] Only relevant files were touched
  - [ x] Only one feature/fix was added per PR.
  - [ x] The code change is tested and works on core 2.6
  - [ x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [ x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by blakadder** [comment]
A feature that got requested quite a few times in discord. Definitely more practical than using rules and var writing

**Comment by arendst** [comment]
Simple and yet so useful!

**Comment by stefanbode** [comment]
Just someone needs to have a good idea, where to put it in the wiki, so it can be found

**Comment by blakadder** [comment]
say no more :D

**Comment by meingraham** [comment]
@stefanbode 
> If changing the UNIT, the compensation will be wrong

Does this mean that if you first set the offset and then change the temperature unit (`SetOption8`), the offset value will be "converted" and therefore not what the user originally entered (i.e., wrong)?

**Comment by blakadder** [comment]
the offset number will stay the same and thus changing the measurement unit will change the offset value aka temperature be wrong

**Comment by meingraham** [comment]
OK... this explanation should be included - the compensation will be wrong... and why.

**Comment by stefanbode** [comment]
yes. The offset will be added at the end. Maybe we should check, if we report in F there is a double call the ConvertTemp/ConvertCelciusToFahrenheit function. It works fine with the DS18b20 and DHT in °C. I made the change in The ConvertTemp and in the ConvertCelciusToFahrenheit. Maybe we need a IF clause in ConvertTemp to avoid problems, if temp is reported in F afterwards.

**Comment by blakadder** [comment]
seems you've done the wiki job yourself :D

**Comment by meingraham** [comment]
The command needs to be added to the Commands article instead... and referenced from each of those sensor pages. I was going to wait for Stefan to make the change he proposed above.

**Pull request merged**
