### PR TITLE
remove fixed address 0x10000 for firmware

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

since it prevents the use of a factory firmware. The main changes are [this](https://github.com/Jason2866/platform-espressif32/commit/2e9045e914a541a226b285bf67ac228d731c817e)

To use it needs an entry in `platformio_override.ini`

```
[env:tasmota32_base]
; *** Uncomment next line ";" to enable development Tasmota Arduino version ESP32
platform  = https://github.com/Jason2866/platform-espressif32.git
```
Thx @Staars  for the changes in `post_esp32.py`

@s-hadinger  Can you test?

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
It does not seem to work, the computed address for firmware build is still 0x10000 instead of 0xE0000. And the command to flash the firmware is not yet fixed.

**Comment by s-hadinger** [comment]
Scratch that. My setup had `board_build.partitions` specified in addition to the board, and it created conflicts.

We still need to patch the command to flash the board.

Well done!

**Comment by s-hadinger** [comment]
Btw, is it normal to have partition in autoexec.be?

**Comment by Jason2866** [comment]
@s-hadinger  partition.be is as autoexec.be in littlefs.bin. Nothing that will be in productive version. I just wanted a quick test if flashing of littlefs partition is working...

**Pull request merged**
