### PR TITLE
Add Support to Domoticz P1 Smart Meter Sensor

### PR DESCRIPTION
**Pull request by pablozg**
## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

The only important change is the need to store six variables in the Settings struct, and save it every 5 minutes toa void lost data in case of lost power or unexpected reboot.

### CODE REVIEW

**Comment by s-hadinger** [comment]
Please use uint32_t type instead of unsigned long (which I'm not sure whether they are 32 or 64 bits long)

**Comment by arendst** [comment]
What does this do?

Currently there is no P1 smart meter driver in this development branch (as far as I know)

**Comment by pablozg** [comment]
Actually I have three meters at home, one sonoff pow r2, a sdm120 and the solar inverter.

I live in Spain and I have a tariff with two periods and I want to have the control of the  consume of the grid, the house and the produced energy with the solar installation in both periods of time.

The two periods are:

From 22 at night to 12 in the morning and from 12 in the morning to 22 at night, this in winter.

From 23 to 13 and viceversa in summer.

As I have tasmota in each meters, my goal is have one p1 smart meter sensor with each meter.

And as the meters itself can't control the both periods I have to control it with tasmota using the total energy counter and using two counters for the consume and return energy in each periods of time.

My English is not good enough, so if you have more questions, let me know. 

Thanks.

**Comment by arendst** [comment]
From your answer I conclude you still do not have a physical P1 meter (also called a smart energy meter in the Netherlands with a P1 port spitting out serial energy data) but you want to use the P1 meter service of Domoticz for your regular Energy meters like Pow and SDM.

In that case I'm not sure why the intermediate energy data has to be stored in flash; the energy monitoring hardware already stores their data in flash.

**Comment by arendst** [comment]
OK.

As I do not like the current selected Settings and RTC area usage I'll do the following:

- I prepare the settings area with your requested 20 byte energy usage data.
- I do the same in the RTC area.
- It will be a data structure called EnergyUsage.

Once I published this pls change your PR to use these values. I then will merge.

**Comment by arendst** [comment]
In addition I do a complete rewrite of this.

So for now pls hold your breath while I'm working on this. Once released pls test it.

**Comment by pablozg** [comment]
> From your answer I conclude you still do not have a physical P1 meter (also called a smart energy meter in the Netherlands with a P1 port spitting out serial energy data) but you want to use the P1 meter service of Domoticz for your regular Energy meters like Pow and SDM.
> 
> Got it.

You are right, I have a smart counter installed by the grid company, but I don't have access to it.

So with this mod I'm able to get the same functionality with the pow r2 and the sdm120.

Don't worry about your changes, you have a better global vision about how the software works.

I do my best on it, but I know maybe it's not the better form to do it, so I will learn about your changes.

I will wait to test it.

**Comment by arendst** [comment]
Just noticed we openend up a can of worms:

image

In my case there is even a weekend tarrif...

**Comment by pablozg** [comment]
> 
> In my case there is even a weekend tarrif...

Then we have to try cover all situations 😅

**Comment by pablozg** [comment]
Hi, I started to test your phase1 of the P1 smart meter implementation, and now with the pow R2 is working fine, but please remind to add an option to add  the offset of time between std and dst to the start hour when we are in summer time, because my electrical company don't have a weekend tariff but in summer the start hour begin one hour later as the difference between std and dst.

I suppose this change will come with the phase 2.

Thanks.

**Comment by arendst** [comment]
Just found out that in the Netherlands even special holidays have Off-Peak tariff.

I start to feel like I should never have jumped this train...

**Comment by pablozg** [comment]
I know, but I think we try to cover as many cases as possible, but there will always be a special case not covered.

As an example, in Spain you can choose up to three tariff (the two standard and one more at night with a lower cost), but I think that people with three tariff will use the smart meter P1 anyway.

Maybe we must open a poll to know how many differents tariff the users of the tasmota comunity have, and now that you are in the train continue until the end. :smiley:

What do you think?

**Comment by arendst** [comment]
I'll jump the train and be a real hobo.

**Comment by meingraham** [comment]
I have no idea of the tariff structures you are referring to. We don't anything like that where I live.

But on the subject of support for smart meters, is there any opportunity to merge support the P1 driver and the @gemu2015 driver... and then implement tariff configuration in one smart meter driver?

Mike

P.S. Jumping off this train now that I threw the grenade into the topic ;-)

**Comment by arendst** [comment]
Mike, you just caught me before a jumped.

I know Gerard is doing the Smart meter driver. That's fine and it will integrate with what we are doing here. This is more trying to emulate smart meter information with current Tasmota energy sensors.

In the end both will report to Domoticz directly.

**Comment by pablozg** [comment]
I will check the last commit ASAP. Thanks.

**Comment by pablozg** [comment]
Hi @arendst I will test the new code along the day, but I think we can have some troubles with it, because the active power of the sdm120 can be positive if you are using energy from the grid and negative if you are injecting energy to the grid (this is my case using the solar inverter).

The second thing is that I think is not necessary to add the sdm220 definitions, because if you see the protocols of both meters, they can meter the same parameters.

SDM120: http://www.eastroneurope.com/media/_system/tech_specs/3914/SDM120%20PROTOCOL.pdf
SDM220 : http://megadevices.com.ua/wp-content/uploads/2016/06/SDM220Modbus_protocol_V1.1.pdf

Medida SDM120

**Comment by pablozg** [comment]
@arendst  after a short test, no total energy are reported and stored.

A change is needed in sonoff_template.h ir order to test the new code:
#if defined(USE_SDM120) || defined(USE_SDM120_2) instead #ifdef USE_SDM120, line 585

sd 120v2
sdm120v2domo

**Comment by arendst** [comment]
Thx for the test and suggestions. I will work on it.

BTW I forgot to add the P1 smart meter function to the prodiction side. Will work on it too.

**Comment by arendst** [comment]
With the latest changes you should at least see the total energy increment. This will start from zero. If you want to start from the current value you will need to use command ``EnergyReset3 484708`` only once to store the offset of 484.708 kWh in Tasmota's flash.

I cannot see why there are no negative values display; they should be displayed as negative numbers...

The Domoticz usage counters still need to be implemented.

**Comment by pablozg** [comment]
Hi, now I'm working, I'll test it tomorrow. :+1:

**Comment by pablozg** [comment]
Hi @arendst, I think we still having troubles with the energy counters, I have used the command 'EnergyReset3' to have both counters (tasmota and sd120) with the same value, but few hours after the tasmota counter is increasing faster than the sdm120.

What do you think about it? I still testing to see how bigger can be the difference.

sdm120v2

**Comment by arendst** [comment]
From your first screen dump, using the the original SDM code, it seems Energy Total is the sum of Import Active and Export Active.

With the new code Energy Total should increment just like the original SDM code provided you set it correctly once.

**Comment by pablozg** [comment]
Hi @arendst, Yesterday I added the sdm total active counter, and reset the total energy to have both counters with the same value.

After less of one day, they have a little difference.

sdm120v2-2

**Comment by arendst** [comment]
Thx again for testing. 

Pls continue for another 24 hours and see if the difference stabilizes or grows.

**Comment by pablozg** [comment]
@arendst, I forgot to comment that if I enable the debug_more option, this line `AddLogBuffer(LOG_LEVEL_DEBUG_MORE, buffer, (buffer[2]) ? buffer[2] + 5 : sizeof(buffer));` produces reboots by exceptions.

I will continue testing it.

**Comment by pablozg** [comment]
Hi @arendst I still testing and I find some troubles with the data send to domoticz when the value is negative:

wrong data

So we have to send the data to the right place. positive values to consumed and negative values (in positive form) to produced.

`if (Energy.active_power >= 0){
        DomoticzSensorP1SmartMeter(energy_total1_chr, energy_total_chr, energy_non, energy_non, (int)Energy.active_power, 0);
      }else{
        DomoticzSensorP1SmartMeter(energy_total1_chr, energy_total_chr, energy_non, energy_non, 0, (int)-Energy.active_power);
      }`

The previous fix still making exceptions reboots:

`16:53:30 MQT: sonoff/tele/INFO3 = {"RestartReason":"Fatal exception:9 flag:2 (EXCEPTION) epc1:0x401061c8 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000003 depc:0x00000000"}`

And the difference between Tasmota Energy Total and SDM still increasing.

diffsdm

**Comment by pablozg** [comment]
@arendst, I still having exceptions with last code: :cry:

` AddLogBuffer(LOG_LEVEL_DEBUG_MORE, buffer, sizeof(buffer));`

`18:52:50 MQT: sonoff/tele/INFO3 = {"RestartReason":"Fatal exception:9 flag:2 (EXCEPTION) epc1:0x401061c8 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000003 depc:0x00000000"}
18:56:34 MQT: sonoff/tele/INFO3 = {"RestartReason":"Fatal exception:9 flag:2 (EXCEPTION) epc1:0x4010626d epc2:0x00000000 epc3:0x00000000 excvaddr:0xffffffff depc:0x00000000"}`

If I set only debug, all works as expected.

**Comment by arendst** [comment]
I think the exception are caused by timing issue; every 200mS a modbus request is executed to get one of the SDM120 registers. Adding the buffer dump to this exceeds the 200mS which may cause the exception.

I'll investigate further.

The difference in total value is likely caused by rounding errors I introduce by adding relative totals with every reading. I'll change it to absolute totals every day and see what happens.

Expect an update today.

**Comment by pablozg** [comment]
Ok I will wait for an update, anyway I observed that since yesterday at 23:20 until now the boot Count has passed from 49 to 59 and the restart reason is "exception".

**Comment by arendst** [comment]
So you also get the exception without logging set to 4?

**Comment by pablozg** [comment]
Yes, I think it can be the reason of the energy total difference, but I don't see the reason, The ESP12-F module only have connected the ttl to rs485 module.

**Comment by pablozg** [comment]
Hi again @arendst, I think that exceptions reboots, are related to data adquire (maybe with timings), because before start using the new driver the sdm120 only show the default menu option (total kwh counter) when a grid lost ocurrs, I know it because I prefer to see the actual consume in the meter (I have to select this menu by hand every time the SDM restarts).

But now with the new driver every time I have an exception in Tasmota, the sdm shows the default menu again.

I sorry but my programming skills aren't so good to try to resolv this by my self.

I hope this info can be useful for you.

**Comment by arendst** [comment]
Thnx. In that case perhaps the timing change from 250mS (old driver) to 200mS (new driver) is just too much.

I'll change it to a higher value.

I also managed to change the energy total to be less deviative (I hope). Will release an update soon.

**Comment by pablozg** [comment]
Hi @arendst, I'm testing the new code, but again I have exceptions when you try to log any info:

````
AddLog_P2(LOG_LEVEL_DEBUG, PSTR("NRG: Energy Total %s %sWh"), energy_total_chr, (kwh) ? "k" : "");
````
It ends with the module configuration lost (tx and rx pins).

If I comment this line and compile the code again, works without issues, so by now I'm testing it without debug info.

I'm thinking that maybe we have to use the "import_active" counter and not the "total active", because it's the sum of the exported and imported energy, and we need to report to domoticz or other software only the consumed energy and not the energy exported too. If you need control it, we have this attempt to implement the P1 meter sensor that control itself the consumed and the produced energy.  What do you think about it?

Thanks.

**Comment by pablozg** [comment]
I still having unexpected exceptions (Less than before, From yesterday at 18:30 to now 5 exceptions), I will try to change the wires, but Can I do anything to find the origin of the exceptions?

**Comment by arendst** [comment]
Finding the origin of the exception can be done using the address noticed in the exception info after the reboot. It's the first hex value.
If you compile your own code you should find a .map file in the root folder. In this file you may find part of the address listed in the exception. This will point to a name in the source code (or in the SDK) which could give some info where the fault occured.

Another problem might be the way I call the modbus updates. In the original driver it was done in the loop loop. In the new driver it is done using a ticker interrupt. I've seen exceptions before using this mechanism but I cannot explain why it hurts the SDM120 driver while the Pzem400Ac driver works just fine.

You might want to move the specific 300mS call out of the ticker loop and use the loop loop instead with a standard 250mS call.

**Comment by pablozg** [comment]
The last exception was 0x4010626d and in the firmware.map I found this:

````
 *fill*         0x0000000040106035        0x3 
 .text.low_level_output
                0x0000000040106038       0x6d C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(eagle_lwip_if.o)
                                         0x71 (size before relaxing)
 *fill*         0x00000000401060a5        0x3 
 .text.ets_rtc_timer_arm
                0x00000000401060a8       0x62 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(ets_timer.o)
                                         0x76 (size before relaxing)
 *fill*         0x000000004010610a        0x2 
 .text.ets_timer_intr_set
                0x000000004010610c       0x78 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(ets_timer.o)
                                         0x90 (size before relaxing)
 .text.timer_insert
                0x0000000040106184       0xc9 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(ets_timer.o)
                                         0xe9 (size before relaxing)
 *fill*         0x000000004010624d        0x3 
 .text.ets_timer_disarm
                0x0000000040106250       0x54 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(ets_timer.o)
                                         0x67 (size before relaxing)
                0x0000000040106250                ets_timer_disarm
 *fill*         0x00000000401062a4        0x0 
 .text.ets_timer_handler_dsr
                0x00000000401062a4       0x18 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(ets_timer.o)
                                         0x1c (size before relaxing)
 .text.ets_timer_arm_new
                0x00000000401062bc      0x1b2 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(ets_timer.o)
                                        0x1fa (size before relaxing)
                0x00000000401062fc                ets_timer_arm_new
 *fill*         0x000000004010646e        0x2 
 .text.system_get_os_print
                0x0000000040106470        0xc C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                0x0000000040106474                system_get_os_print
 .text.os_printf_plus
                0x000000004010647c      0x131 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                                        0x15d (size before relaxing)
                0x0000000040106490                os_printf_plus
 *fill*         0x00000000401065ad        0x3 
 .text.system_restart_core
                0x00000000401065b0       0x3f C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                                         0x4b (size before relaxing)
                0x00000000401065b8                system_restart_core
 *fill*         0x00000000401065ef        0x1 
 .text.system_deep_sleep_local_2
                0x00000000401065f0       0xb9 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                                         0xed (size before relaxing)
                0x00000000401065fc                system_deep_sleep_local_2
 *fill*         0x00000000401066a9        0x3 
 .text.system_get_time
                0x00000000401066ac       0x16 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                                         0x1a (size before relaxing)
                0x00000000401066b0                system_get_time
 *fill*         0x00000000401066c2        0x2 
 .text.system_get_free_heap_size
                0x00000000401066c4       0x16 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                0x00000000401066c8                system_get_free_heap_size
 *fill*         0x00000000401066da        0x2 
 .text.system_rtc_mem_write
                0x00000000401066dc       0x5a C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                0x00000000401066e0                system_rtc_mem_write
 *fill*         0x0000000040106736        0x2 
 .text.system_rtc_mem_read
                0x0000000040106738       0x56 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user_interface.o)
                                         0x5a (size before relaxing)
                0x0000000040106738                system_rtc_mem_read
 *fill*         0x000000004010678e        0x2 
 .text          0x0000000040106790       0xc7 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(nmi-vector.o)
                                         0xcb (size before relaxing)
                0x000000004010679c                _NMILevelVector
 *fill*         0x0000000040106857        0x1 
 .text          0x0000000040106858       0x1e C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(user-vector.o)
                0x000000004010685c                _UserExceptionVector_1
 *fill*         0x0000000040106876        0x2 
 .text.Cache_Read_Disable_2
                0x0000000040106878       0x3f C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x47 (size before relaxing)
                0x000000004010687c                Cache_Read_Disable_2
 *fill*         0x00000000401068b7        0x1 
 .text.Cache_Read_Enable_2
                0x00000000401068b8       0x2a C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x36 (size before relaxing)
                0x00000000401068b8                Cache_Read_Enable_2
 *fill*         0x00000000401068e2        0x2 
 .text.spi_flash_get_id
                0x00000000401068e4       0x55 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x71 (size before relaxing)
                0x00000000401068e4                spi_flash_get_id
 *fill*         0x0000000040106939        0x3 
 .text.spi_flash_read_status
                0x000000004010693c       0x2b C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x3b (size before relaxing)
                0x0000000040106940                spi_flash_read_status
 *fill*         0x0000000040106967        0x1 
 .text.spi_flash_write_status
                0x0000000040106968       0x66 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x86 (size before relaxing)
                0x0000000040106974                spi_flash_write_status
 *fill*         0x00000000401069ce        0x2 
 .text.flash_gd25q32c_read_status
                0x00000000401069d0      0x19d C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                        0x1e1 (size before relaxing)
                0x00000000401069e8                flash_gd25q32c_read_status
 *fill*         0x0000000040106b6d        0x3 
 .text.flash_gd25q32c_write_status
                0x0000000040106b70      0x198 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                        0x1e4 (size before relaxing)
                0x0000000040106b80                flash_gd25q32c_write_status
 .text.spi_flash_check_wr_protect
                0x0000000040106d08       0xa2 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0xd6 (size before relaxing)
                0x0000000040106d18                spi_flash_check_wr_protect
 *fill*         0x0000000040106daa        0x2 
 .text.spi_flash_erase_sector
                0x0000000040106dac       0x50 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x68 (size before relaxing)
                0x0000000040106db8                spi_flash_erase_sector
 .text.spi_flash_write
                0x0000000040106dfc       0x56 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x6a (size before relaxing)
                0x0000000040106e00                spi_flash_write
 *fill*         0x0000000040106e52        0x2 
 .text.spi_flash_read
                0x0000000040106e54       0x5b C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(spi_flash.o)
                                         0x6f (size before relaxing)
                0x0000000040106e58                spi_flash_read
 *fill*         0x0000000040106eaf        0x1 
 .literal       0x0000000040106eb0        0x4 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\libgcc.a(_divsf3.o)
                                         0x10 (size before relaxing)
 .literal       0x0000000040106eb4        0x0 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\libgcc.a(_cmpsf2.o)
                                         0x18 (size before relaxing)
 .literal       0x0000000040106eb4        0x0 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\libgcc.a(_fixsfsi.o)
                                          0x4 (size before relaxing)
 .literal       0x0000000040106eb4        0x4 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\libgcc.a(_cmpdf2.o)
                                         0x18 (size before relaxing)
 .text          0x0000000040106eb8      0x135 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\libgcc.a(_divsf3.o)
                0x0000000040106f34                __divsf3
 *fill*         0x0000000040106fed        0x3 
 .text          0x0000000040106ff0      0x122 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\libgcc.a(_cmpsf2.o)
                0x0000000040106ff0                __eqsf2
                0x0000000040106ff0                __nesf2
````

I think is related to the timers as you said. I will try to put the call into the loop.

**Comment by arendst** [comment]
Right:
```
.text.ets_timer_disarm
                0x0000000040106250       0x54 C:\Users\pablo\.platformio\packages\framework-arduinoespressif8266@src-bac0718d57cb81d5753774eb032ee50f\tools\sdk\lib\NONOSDK22y\libmain.a(ets_timer.o)
                                         0x67 (size before relaxing)
                0x0000000040106250                ets_timer_disarm
```
is causing issues. It is used by the Ticker. Pls continue as you suggested.

You'll need to add a XnrgCall(FUNC_EVERY_250_MSECOND) in the energy.ino driver function call switch options. Then comment out the call XnrgCall(FUNC_EVERY_300_MSECOND) in the energy.ino evry 100mSec loop.

**Comment by pablozg** [comment]
I just saw that you made the work for me, I was far home since you last comment, when I 'm back I will test the changes and see if the exceptions go away. Thanks.

**Comment by pablozg** [comment]
I just saw that you made the work for me, I was far home since you last comment, when I 'm back I will test the changes and see if the exceptions go away. Thanks.

**Comment by pablozg** [comment]
Hi @arendst, about the exceptions I think now are gone, the new code are running since 15 hours and no exceptions has occurs. :smile:

About my last suggestion I'll put some energy info:

As I said at beginning of the PR, I have two meters:

The POW R2 meter measure all house consume, the SDM120 only measure the grid consume (and the energy injected to grid by the solar inverter during the day).

As you can see, using the "EnergyUpdateTotal" function in the case 7, "today energy" is greater than the real consume of the house measured by the pow R2.

caseactual

Since yesterday at midnight I change the code to use the case 9 (import_active) instead the case 7, and now the measure work as expected, the energy measured by pow R2 is greater than the grid consume measured by the sdm120, because now I'm producing solar energy. 

casenuevo

The people without solar inverter, no difference will note because always are importing energy from the grid.

What do you think?

**Comment by arendst** [comment]
You have a good point. I'll change it. Problem is that the initial SDM120 hardware doesn't have the Import Active but I'll work around it.

**Comment by pablozg** [comment]
I'm testing the last code and at midnight the  today counter haven't been reset to 0.

When I try to use the command EnergyReset1 0, the counter value change to 0 as expected, but few seconds after,  it's change to 0.411, I think this value is the consumed energy from midnight, but I'm not sure if this is correct.

```
00:43:49 CMD: EnergyReset1 0
00:43:49 MQT: sonoff/stat/RESULT = {"EnergyReset":{"Total":539.297,"Yesterday":0.000,"Today":0.000}}
00:43:51 MQT: sonoff/tele/HASS_STATE = {"Version":"6.6.0.11(sonoff)","BuildDateTime":"2019-09-08T21:52:22","Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Module":"Generic","RestartReason":"Hardware Watchdog","Uptime":"0T00:43:42","WiFi LinkCount":1,"WiFi Downtime":"0T00:00:06","MqttCount":1,"BootCount":116,"SaveCount":355,"IPAddress":"10.10.0.75","RSSI":"46","LoadAvg":21}
00:44:05 MQT: sonoff/tele/STATE = {"Time":"2019-09-09T00:44:05","Uptime":"0T00:43:56","UptimeSec":2636,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Isabella_T","BSSId":"D4:6E:0E:D0:43:EC","Channel":6,"RSSI":50,"LinkCount":1,"Downtime":"0T00:00:06"}}
00:44:05 MQT: domoticz/in = {"idx":93,"nvalue":0,"svalue":"1345;539304.0","Battery":100,"RSSI":5}
00:44:05 MQT: domoticz/in = {"idx":92,"nvalue":0,"svalue":"35826.3;503477.7;0;0;1345;0","Battery":100,"RSSI":5}
00:44:05 MQT: sonoff/tele/SENSOR = {"Time":"2019-09-09T00:44:05","ENERGY":{"TotalStartTime":"2019-09-09T00:40:16","Total":539.304,"Yesterday":0.000,"Today":0.411,"Period":0.00,"Power":1345.00,"ApparentPower":1380.79,"ReactivePower":325.10,"Factor":0.97,"Frequency":50.00,"Voltage":229.2,"Current":6.08,"ImportActive":538.953,"ExportActive":24.916,"ImportReactive":195.791,"ExportReactive":3.497,"PhaseAngle":0.00}}
00:44:11 MQT: sonoff/tele/HASS_STATE = {"Version":"6.6.0.11(sonoff)","BuildDateTime":"2019-09-08T21:52:22","Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Module":"Generic","RestartReason":"Hardware Watchdog","Uptime":"0T00:44:02","WiFi LinkCount":1,"WiFi Downtime":"0T00:00:06","MqttCount":1,"BootCount":116,"SaveCount":355,"IPAddress":"10.10.0.75","RSSI":"48","LoadAvg":19}
00:44:25 MQT: sonoff/tele/STATE = {"Time":"2019-09-09T00:44:25","Uptime":"0T00:44:16","UptimeSec":2656,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"Isabella_T","BSSId":"D4:6E:0E:D0:43:EC","Channel":6,"RSSI":48,"LinkCount":1,"Downtime":"0T00:00:06"}}
00:44:25 MQT: domoticz/in = {"idx":93,"nvalue":0,"svalue":"1343;539311.1","Battery":100,"RSSI":4}
00:44:25 MQT: domoticz/in = {"idx":92,"nvalue":0,"svalue":"35833.3;503477.7;0;0;1343;0","Battery":100,"RSSI":4}
00:44:25 MQT: sonoff/tele/SENSOR = {"Time":"2019-09-09T00:44:25","ENERGY":{"TotalStartTime":"2019-09-09T00:40:16","Total":539.311,"Yesterday":0.000,"Today":0.418,"Period":7.01,"Power":1343.80,"ApparentPower":1381.11,"ReactivePower":326.70,"Factor":0.97,"Frequency":50.04,"Voltage":229.3,"Current":6.06,"ImportActive":538.961,"ExportActive":24.916,"ImportReactive":195.792,"ExportReactive":3.497,"PhaseAngle":0.00}}

```

**Comment by pablozg** [comment]
Hi @arendst, I made an implementation of the export control and works without issues until now, Can you take a look to it? Thanks.

exportcontrol

**Comment by arendst** [comment]
I'm working on your export control. Looks OK with me.

Wouldn't it make sense to delete import_active from the SDM120 as it is the same as Energy_Total. In that case I will also move Export_Active to energy and make it display once the field has been updated from NAN to any value. This way future Export_Active sensors (like DDS238) can also easily be integrated.

**Comment by pablozg** [comment]
> Wouldn't it make sense to delete import_active from the SDM120 as it is the same as Energy_Total. 

I think we may leave it, because in case of a reset, exception, etc. I use it to calc the "energyReset3" value and always we can have a reference of the hardware value.

If you don't want it in the webui is ok, but I think we may leave it in the json string.

**Comment by pablozg** [comment]
Now I will try to implement the use of an offset in summer time like we use in Spain.

I thinking to add a new tariff flag and new value like "ENERGY_TARIFF_OFFSET" to use it if the new flag is activated.

What do you think about it?

**Comment by arendst** [comment]
Don't do it. I will in very near future as I want it to be like setting two tarrif values again. This way we tackle countries with more than one hour offset.

**Comment by arendst** [comment]
The latest update changes command ``tariff3`` to tariff9`` and adds commands ``tariff3`` and ``tariff4`` to enter Daylight Savings tariff start hour.

Considering the low use of current implemntation your previous tariff settings are lost.

**Comment by meingraham** [comment]
So, Tariff 1-4 set the off-peak start/end hours for STD/DST? Is that correct?

What does it mean to "toggle weekend"?

**Comment by arendst** [comment]
Toggle weekend enables tariff1 during the whole weekend. If not set weekend is treated as week-day.

**Comment by meingraham** [comment]
Sorry, I'm still not clear.

`Tariff1 23 = Tariff1 ST, Tariff2 7 = Tariff2 ST, Tarriff3 22 = Tarrif1 DST, Tariff4 6 = Tariff2 DST, Tariff9 0/1 = Weekend toggle`

`enables tariff1 during the whole weekend`
I thought Tariff1-Tariff4 set an hour of the day?

**Comment by arendst** [comment]
There are only two Tariffs.
- Tariff1 is active during Off-Peak hours and could start at 23 hour
- Tariff2 is active during business hours and could start at 7 hour

During daylight Savings these start hours could be different. To set them you execute command ``Tariff3`` for Tariff1 or ``Tariff4`` for Tariff2.

This is confusing so I will release another solution. Forget above info.

I will make two commands
- ``Tariff1 22,23`` which will start Off-Peak tariff during Standard Time at 22nd hour and during Daylight Savings time at 23th hour.
- ``Tariff2 6,7`` which will start Standard tariff during Standard Time at 6th hour and during Daylight Savings time at 7th hour.

Then forget about command ``Tariff3`` and ``Tariff4``.

``Tariff9`` stays as weekend toggle.

**Comment by meingraham** [comment]
While you are re-thinking... Is there ever a tariff policy that would go into effect not at the top of the hour? Should these values be minutes from midnight?

Again, I don't have a tariff policy in my area, so I'm speaking from ignorance :wink:

**Comment by arendst** [comment]
I read your concern but for now we go for the top of the hour.

**Pull request closed without merging**
