### PR TITLE
IRremoteESP8266 upgraded to v2.8.5

### PR DESCRIPTION
**Pull request by mbronk**
## Description:
Upgrades IRremoteESP8266 `v2.8.4` ->  [**`v2.8.5`**](https://github.com/crankyoldgit/IRremoteESP8266/releases/tag/v2.8.5). 

**Related issue (if applicable):** `n/a`
## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.9
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by mbronk** [comment]
@s-hadinger, @arendst  -  While I've submitted it as a single PR as these are complete set of changes, I'm also happy to split on a per-commit basis. Let me know if you'd prefer that. 
My apologies if this creates trash - this is my first contrib. to this repo and still learning the ropes :)

---

@s-hadinger - I believe you've been historically doing these IRremoteESP8266 upgrades. I hope I was able to recreate the process (essentially copied&commited the sources as-is). If there's a different procedure for it, I'd so welcome some guidance & help (or: feel free to discard my commit and do it proper - I mostly care about https://github.com/arendst/Tasmota/pull/18610/commits/5306dc7c4d1c2f64a371c63a93fd08effda5aa98)
**Note**: I've also cherry-picked https://github.com/arendst/Tasmota/pull/18610/commits/59e6c26ea8cb83c037c90f4b8768e65aeaaba248 as it was there on top of of v2.8.4 sources. Can't tell if this change is required (but seemed harmless so I merged it in). Hope you can advise.

As for the rest of the changes, they're meant to follow the updates in IRremoteESP8266 library (I'm the author of these downstream changes, actually).


I have *not* tested on ESP32 (missing a free board for that). Is there any chance for a help w/ that?

**Comment by s-hadinger** [comment]
Hi, nice work. However I prefer to have two separate PRs 1/ update IRRemote lib, 2/ expand. the features.

Can you remove the changes to `xdrv_05_irremote_full.ino` and send them in a separate PR please?

**Comment by mbronk** [comment]
> Can you remove the changes to `xdrv_05_irremote_full.ino` and send them in a separate PR please?

Sure thing, just updated _(will wait w/ creating a PR for the rest once this is approved, not to create too much noise)_
Note I have kept: https://github.com/arendst/Tasmota/pull/18610/commits/59e6c26ea8cb83c037c90f4b8768e65aeaaba248, https://github.com/arendst/Tasmota/pull/18610/commits/437d8a08dc34207463dc6832aa7d55e6d9de08a9 on top of vanilla `2.8.5` sources of IRremote8266, but can separate these changes also.

**Review by s-hadinger — CHANGES_REQUESTED** [review]
Why did you remove this line?

**Comment by mbronk** [comment]
> Why did you remove this line?

@s-hadinger  Sorry, which one? This comment doesn't show for me as linked to any particular line (or I need more coffee :) ). Could you add a perma-link?

Random guess - are you referring to `-DUSE_IR_REMOTE_FULL` by any chance? If yes, it is already covered by `-DFIRMWARE_IR`  See here: https://github.com/arendst/Tasmota/blob/6fe1bbd617b226f8cbde07325486904c708e60f1/tasmota/include/tasmota_configurations.h#L378-L400

I could of course let it be as these are just WARNs (or create an `#ifndef`), though I have noticed it is not defined for the ESP8266 version, so I figured it'd be simpler to keep level.
If this creates some nasty side-effect I missed, let me know!

**Review by s-hadinger — APPROVED** [review]

**Comment by s-hadinger** [comment]
Ah ok, thanks

**Pull request merged**
