### PR TITLE
Zigbee fix compilation for future core

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Fix compilation error with future Arduino core for ESP32.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by mipurel** [comment]
I have Aqara Magic Cube on ZigbeeBridgePro
Version 12.4.0 from http://ota.tasmota.com/tasmota32/tasmota32-zbbrdgpro.bin works fine since version 12.5.0 and above there is a bug probably related to this PR. Attributes incorrectly converted to strings 

```09:10:04.266 ZIG: {"ZbZNPReceived":"45C439620192DB"}
09:10:04.316 ZIG: {"ZbZNPReceived":"44810000120039620201006200ACEE0F00000818B80A550021600092DB1C"}
09:10:04.318 ZIG: {"ZbZCLReceived":{"groupid":0,"clusterid":"0x0012","srcaddr":"0x6239","srcendpoint":2,"dstendpoint":1,"wasbroadcast":0,"LinkQuality":98,"securityuse":0,"seqnumber":0,"fc":"0x18","frametype":0,"direction":1,"disableresp":1,"manuf":"0x0000","transact":184,"cmdid":"0x0A","payload":"5500216000"}}
09:10:04.321 ZIG: ZbZCLRawReceived: {"0x6239":{"0012/0055":96,"Endpoint":2,"LinkQuality":98}}
09:10:04.742 RSL: SENSOR = {"ZbReceived":{"Cube":{"Device":"0x6239","Name":"Cube","xV��":"flip90","���?xV��\r":0,"���?���?6":4,"Endpoint":2,"LinkQuality":98}}}
09:10:21.879 WIF: Checking connection...
09:34:19.282 RSL: SENSOR = {"ZbReceived":{"Cube":{"Device":"0x6239","Name":"Cube","AqaraCube":"flip90","\"Name\":\"%s\",":4,"AqaraCubeFromSide":0,"Endpoint":2,"LinkQuality":98}}}
09:35:17.091 RSL: SENSOR = {"ZbReceived":{"Cube":{"Device":"0x6239","Name":"Cube","AqaraCube":"flip90","\"Name\":\"%s\",":4,"AqaraCubeFromSide":5,"Endpoint":2,"LinkQuality":83}}}
09:36:35.845 RSL: SENSOR = {"ZbReceived":{"Cube":{"Device":"0x6239","Name":"Cube","":"tap","\"Name\":\"%s\",":0,"Endpoint":2,"LinkQuality":105}}}
```

**Comment by mipurel** [comment]
Ok. Thanks.

**Comment by s-hadinger** [comment]
@mipurel This should be fixed now with https://github.com/arendst/Tasmota/pull/20452

**Comment by mipurel** [comment]
Good job @s-hadinger . Now it works fine.

**Pull request merged**
