### PR TITLE
Webcam update

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

add face detector 

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core ESP8266 V.2.7.0
  - [ ] The code change is tested and works on core ESP32 V.1.12.0
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx.

What tool do you use that adds and removes spaces at random code lines. Especially around = and arithmetic signs and even line indents. I try to use google cpp code book to keep the code readable and consistent. Having spaces around these items adds to readability.

Could you be so kind to have a look at readability and consistenty too?

**Comment by gemu2015** [comment]
which tool do you recommend ? (i am on macOS)
i tried online tools and was not satisfied at all.

some formatting differences result from hand merging.
because we both worked at the same source i could not automatically merge sometimes

**Comment by arendst** [comment]
I understand.

I just use VSC with extension ``Trailing Spaces`` and tried ``cpplint`` but that needs external python tools which is an issue on Windows where there are python version everywhere. It doesn't work for me so it's all by hand.

**Comment by gemu2015** [comment]
ok, will be more thoroughly next time

**Pull request merged**
