### PR TITLE
decode-config.py: adapt settings

### PR DESCRIPTION
**Pull request by curzon01**
- add DimmerRange (dimmer_hw_min/dimmer_hw_max)
- add DeepSleepTime (deepsleep)
- change PowerDelta (energy_power_delta)
- rename novasds_period > novasds_startingoffset
- fix tuya_disable_dimmer remove
- fix json 'header' crc32

## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core pre-2.6
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by localhost61** [comment]
@curzon01 
Please could you make `decode-config.py` compatible with python v3?
Python v3 is the version installed in PlatformIO and v2 is soon EOL.
I tried to use in a Terminal session of the PlatformIO IDE:
`%USERPROFILE%\.platformio\python37\Tools\scripts\2to3.py -w decode-config.py`
But it was not enough, after a seamless conversion I got:
`decode-config.py -H`
```
  File "decode-config.py", line 187
    print("{}. Try 'pip install {}' to install it".format(er,er.split(' ')[len(er.split(' '))-1]), file=sys.stderr)
                                                                                                       ^
SyntaxError: invalid syntax
```
The message didn't help to understand which module was missing.

**Comment by localhost61** [comment]
Hum... 
Forget it `python decode-config.py -H` works fine after 2to3 conversion, it's just an issue with the .py extension which is handled on my system by c:\windows\py.exe by default, and without a shebang like:
`#!/usr/bin/env python3` it chose the wrong version and ran python v2.
With the new shebang I obtain a meaningful:
`No module named 'configargparse'. Try 'pip install 'configargparse'' to install it` 

After installing missing modules in PlatformIO environment, there are still errors after 2to3 conversion:
`python decode-config.py -f Config.dmp`
```
Traceback (most recent call last):
  File "decode-config.py", line 3259, in <module>
    args = ParseArgs()
  File "decode-config.py", line 3250, in ParseArgs
    if args.debug >= 1:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by curzon01** [comment]
Will have a look asap but pls be patient I'm currently very busy with other tasks and it can take 2-3 weeks...

**Comment by localhost61** [comment]
Cool !
This is not a high priority, I managed to use it with Python 2.7 on Windows. The integration of the last changes made to the settings since version 6.6.0.21 goes before.

**Comment by localhost61** [comment]
@curzon01  Thanks for the last upgrade!
I quickly tested decode-config.py in a PlatformIO Terminal session and it worked like a charm with embedded python 3.7.4 (under Windows 8.1).
I just had to launch the `pip3 install future requests configargparse` command because `past` module was not recognized.

**Pull request merged**
