### PR TITLE
Add support for water/gas S0-based meter

### PR DESCRIPTION
**Pull request by goeran03**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by goeran03** [comment]
This is another contribution for a S0-interface based water/gas meter.

**Comment by goeran03** [comment]
see discussion #18421

**Comment by sfromis** [comment]
Was the existing support for S0 pulse-based meters insufficient?

**Comment by goeran03** [comment]
As far as I know, it only supports 1 channel and does not store the total consumption values over power cycles

 

Von: sfromis ***@***.***> 
Gesendet: Samstag, 15. April 2023 22:27
An: arendst/Tasmota ***@***.***>
Cc: goeransaenger ***@***.***>; Author ***@***.***>
Betreff: Re: [arendst/Tasmota] Add support for water/gas S0-based meter (PR #18419)

 

Was the existing support for S0 pulse-based meters insufficient?

**Comment by arendst** [comment]
Your implementation has some major pitfalls.

- By inserting new gpios into the existing list of gpios removes backward compatibility with any version. There is a reason why the template source tries to tell you to add new gpios at the end of the list.
- By using a define in the settings area you exclude certain devices from using the driver. In your case ESP32 cannot use it.

Overall the functionality is already available using script/sml where data needs to be stored in the backend.

Thx for the idea but this won't be merged.

**Comment by goeran03** [comment]
Oh that’s ok for me. Currently I don’t have the resources to bring it in the fashion you’ve requested. Thanks
    	
    
  

 Von: Theo Arends ***@***.***>Gesendet: Sonntag, April 16, 2023 8:52 AMAn: arendst/Tasmota ***@***.***>Cc: goeransaenger ***@***.***>; Author ***@***.***>Betreff: Re: [arendst/Tasmota] Add support for water/gas S0-based meter (PR #18419) 
Closed #18419.

**Pull request closed without merging**
