### PR TITLE
Zigbee support more alarms types

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Support more alarms types from the ZCL spec:
- `CIE`: standard CIE (don't ask me what it is)
- `Occupancy`: PIR sensors
- `Contact`:  window or door contacts, like Mi Door
- `Fire`: fire sensor
- `Water`: water sensor
- `CO`: carbon monoxide detector
- `Personal`: personal emergency device
- `Movement`: vibration/movement sensor
- `Panic`: panic button
- `GlassBreak`: glass break sensor

Detection is automatically done at pairing time.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by derFrickler** [comment]
Great work on the zigbee stuff tthat has been done in the latest versions!
Would be cool to show the current state/alarm on the webui as well - especially for the door/contact sensors.

**Comment by s-hadinger** [comment]
Yes. This is on the roadmap.

**Comment by joba-1** [comment]
not contributing a lot, so here is my chance: CIE = Control and Indicating Equipment :)

**Comment by s-hadinger** [comment]
Thanks. I've been looking for the acronym and never found what it means

**Pull request merged**
