### PR TITLE
Create Matter_Plugin_9_Virt_Sensor_Occupancy.h

### PR DESCRIPTION
**Pull request by lboue**
## Description:
Add the missing Matter Occupancy Virtual Sensor.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
The header file is automatically generated from the Berry code. Just adding the header will not change anything. Can you please provide the corresponding Berry file?

**Comment by lboue** [comment]
@s-hadinger I just add berry file that implements the behavior for a Virtual Occupancy Sensor: [5ec5adf](https://github.com/arendst/Tasmota/pull/19786/commits/5ec5adfe83818eef88d8011fc14fcddc1c09e904).

**Comment by lboue** [comment]
Add missing v_occupancy and v_onoff in Matter_UI.be

**Comment by lboue** [comment]
@s-hadinger I couldn't figure out why I have an empty line in the list:

image

**Pull request merged**
