### PR TITLE
Add speed and heading info to GPS driver

### PR DESCRIPTION
**Pull request by pkkrusty**
Added NAV-VELNED messages to driver, allowing speed and heading info on the main web page and JSON messages. Probably could be optimized; mostly another exercise in copy/paste. Also reduced threshold for movement to 100 from 1000. Testing indicated this was more reasonable when horizontal accuracy was 5m or less (which is normal for non-obstructed sky)

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ x] The pull request is done against the latest development branch
  - [ x] Only relevant files were touched
  - [ x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ x] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [ x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Edge case considering how many portable tasmotas are out there. What's the impact on code size and ram usage? If too much use defs to save resources for non-portable users.

**Comment by pkkrusty** [comment]
Good point. I'll put changes into a #define.

**Comment by pkkrusty** [comment]
Adjusted code so requires #define USE_GPS_VELOCITY. 0k4 code space. Maybe 40 bytes RAM (not sure).

**Comment by DouglasRudd** [comment]
G'Day.
I am developing a device that will be used inside a company vehicle while it is being used within our warehouse yard to track and monitor movement and speed, the yard has 100% wifi coverage on our local Lan, I have tried the Unofficial Bin from the web installer but the value for the lon: has the alt: appended to the end of it, I tried to recompile from both the Main and the Dev branch and both of them do not return the lat: value, when I try to compile with #define USE_GPS_VELOCITY. there is an error ( missing the leading " at line 921). I have been trying to debug this my self and have found that for some reason 
on line 901, dtostrfd((double)UBX.rec_buffer.values.lat/10000000.0f,7,lat); is rendering a null.  any help would be appreciated. 
thanks

**Comment by arendst** [comment]
Latest dev (v14.1.0.2) fixes the compile issue. I see this with regards to lat:

image

**Comment by sfromis** [comment]
I noticed that the "GPS Speed" field lacks a unit. Ideally, it could align with what can be configured via the command SpeedUnit. Sure, that is mentioned as being for wind speed, but the units should be perfectly fine for transportation speed too.

**Pull request merged**
