### PR TITLE
[Shutter] Fix UI inverted mode

### PR DESCRIPTION
**Pull request by SteWers**
## Description:
Fix UI for shutter in inverted mode

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.1.0.241117
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Was this an issue before the new GUI was introduced too?

**Comment by SteWers** [comment]
May be. There were several issues with the inverted mode, as you have to think completely in the other direction. Something felt wrong, when I saw the new (very nice) UI. So I investigated both modes. Normal mode worked correct.
In line 1436 was the wrong flag requested for inverted mode. After changing it, the buttons were displayed at the right position, but commanding the wrong direction. The rest of the code is for solving that. Now it works in both modes, but maybe there is a "nicer" way to solve it.

**Comment by arendst** [comment]
Let's ask @stefanbode what he thinks is the correct solution.

**Comment by SteWers** [comment]
Good idea.
I had a quick look at the release 14.3.0. The buttons were not swapped. As they were not near to the slider, it was no problem. 
image
(Shutter 1 is not inverted, shutter 2 is inverted)

But now the slider should move towards the button, which is pressed.
image
(Same configuration as above with the fix applied)

**Comment by stefanbode** [comment]
Great thanks. Agree to all findings. Nice change.

**Pull request merged**
