### PR TITLE
Adding support for ILI9488/XPT2046 display

### PR DESCRIPTION
**Pull request by mikep1998**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with core ESP32 V.1.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by mikep1998** [comment]
Yes, you are right the mapping can be done before the rotation. Or after not much of a difference. The Negative values are seen because the the values of rotmap_max and rotmap_min are imprecise and the map function can return values outside of rotmap_max or rotmap_min. 

Example if the xmax is 100 and the read from the touch is 90 then map will return negative value.

**Comment by gemu2015** [comment]
then you should rethink the mapping function. it should limit the values inside the unrotated screen bounds

**Comment by gemu2015** [comment]
these variables hold the unrotated size

   uint16_t gxs;
   uint16_t gys;

**Comment by mikep1998** [comment]
I don't understand the issue. 
if not map then what function to use? Or write your own.

**Comment by mikep1998** [comment]
Ok let me rework it.

thanks for the suggestion.

**Comment by gemu2015** [comment]
map and then

constrain(x, a, b)

**Pull request merged**
