### PR TITLE
rf receive HEX DEC setting

### PR DESCRIPTION
**Pull request by sammy2360**
hi arendst,
created a setting in setoption to switch between HEX and DEC data in the json object when an RF signal is recieved on the sonoff bridge.

i have used setoption 28 as it was labeled as spare.
i have tested this and all seems to be working as it should.

in sonoff.ino i have changed the CMND_SETOPTION index from 26 to 28 which may enable the setting for knx_enable_enhancement. 
this may have to be looked at. maybe by adding ||(index == 28) instead.

thanks for all your great work.
sam

### CODE REVIEW

**Review by ascillato — CHANGES_REQUESTED** [review]
Hi,

Can you modify your PR so as to leave platformio.ini file without changes?

Thanks

**Comment by sammy2360** [comment]
yes ill download a fresh copy and delete the modified one. apologies.

**Comment by sammy2360** [comment]
ok that is the platform.ini back to the original state. it is still listed in the pr but with no changes. will that disappear? please forgive me im new to github.

**Comment by arendst** [comment]
Just implemented. Thnx.

**Pull request closed without merging**
