### PR TITLE
lib folder reshuffle

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

all librarys in folder `lib` Blame @blakadder. He asked for ;-)

If you do not merge it is 100% okay. It is just for beauty 

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.5
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@eku Move your library from `lib`to folder `lib/lib_div` No further change needed

**Comment by eku** [comment]
@Jason2866 thanks. PR updated \o/

**Comment by GrendelWWU** [comment]
> Damn, the changes break my PR #9419. What changes should I make in PR?

Hello, did you already find the reason for these restarts?
My project is nearing completion and soon, I'll solder the PCB for it.
Best regards,
Thomas

**Comment by Jason2866** [comment]
@GrendelWWU  please dont hijack a PR with a not related question

**Comment by GrendelWWU** [comment]
> @GrendelWWU please dont hijack a PR with a not related question

Sorry, Jason. I thought, the PRs were merged and PR9419 was about my problem. So, I chose to ask here. Excuse me, I'm not very familiar with all these stuff.

**Comment by Jason2866** [comment]
@GrendelWWU 
For help and questions visit us at Discord [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). 

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Pull request merged**
