### PR TITLE
Add dali broadcast support

### PR DESCRIPTION
**Pull request by agners**
Initial support for DALI (Digital Addressable Lighting Interface) bus
support. Currently only two commands are implemented which send out
commands using bus broadcasts. This is sufficient to control a single
DALI capable device.

The DALI library has been borrowed from the Simple DALI Controller
project:
https://create.arduino.cc/projecthub/NabiyevTR/simple-dali-controller-506e44

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato** [comment]
Hi, the DALI library uses the delay instruction a lot. Sorry but that is a NO GO for being merge into Tasmota as will interfere with other routines like wifi, mqtt, etc and also will reduce the response time.

Please, try to rewrite it in order to not use delay or use it in very short time frames and returning to the main execution thread.

**Comment by arendst** [comment]
Thx too. Pls select driver number 29 as the selected one is already in use.

**Review by ascillato2 — CHANGES_REQUESTED** [review]
Delay instruction is used a lot.

**Comment by agners** [comment]
The worst functions in terms of delay are no longer called. It is only the protocol functions. The protocol uses a fixed baud rate of 1200bps, and hence timing is crucial. What tools are available to get such a timing in Tasmota?

**Comment by s-hadinger** [comment]
TasmotaSerial may handle this with the 'nw' parameter. It is entirely interrupt based, no delay().

**Comment by ascillato2** [comment]
Closing this PR as it needs a rewrite of the library.

If you need any help, please, feel free to ask here or in the Tasmota Support Chat. Thanks.

**Pull request closed without merging**
