### PR TITLE
New feature Outdoor Temperature for MiElHVAC

### PR DESCRIPTION
**Pull request by grzegorz914**
## Description:
* Add Outdoor Temperature

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.1.0.241015
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Is this it or are you planning to add even more "features"?

**Comment by grzegorz914** [comment]
I will add more, but one PR for feature.

**Comment by mamrai1** [comment]
Outdoor temperature is remote temperature feature?

**Comment by grzegorz914** [comment]
No, Remote Temperature is other thing.

**Comment by grzegorz914** [comment]
Remote Temperature is a External Room Temperature Sensor Input.

**Comment by mamrai1** [comment]
And how do i publish the remote temperature with tasmota?

**Comment by grzegorz914** [comment]
Just like this: `http://ip/cm?cmnd=HVACRemoteTemp 21`

**Comment by mamrai1** [comment]
Thanks. I tried and works but i thought if sending remote temp of 0 will revert back to internal sensor but it didn’t. Also waiting half an hour it didn’t revert to internal temp. I had to power  cycle the unit

**Comment by grzegorz914** [comment]
Are you try just stop sending remote temp?

**Comment by grzegorz914** [comment]
Ok, please open new issue for this.

**Pull request merged**
