### PR TITLE
Compress more strings with UnishoxStrings

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Move more strings to Unishox compression. The code decrease is only 56 bytes for this PR, largely due to the addition of UnishoxStrings (which code will be shared with more parts).

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
On hold, I need to change in Zigbee hue code too.

**Comment by suhajda3** [comment]
Resource links no longer returns an empty object. Breaks compatibility with [homebridge-hue](https://github.com/ebaauw/homebridge-hue/)

Issue: https://github.com/ebaauw/homebridge-hue/issues/1052

**Comment by s-hadinger** [comment]
Homebridge is not supported in Tasmota. We can only make small changes of they are easy enough.

**Comment by suhajda3** [comment]
Thanks for your reply @s-hadinger. 👍 

I understand that `homebridge-hue` is not supported by Tasmota, but the resourcelinks feature was added by [you](https://github.com/ebaauw/homebridge-hue/issues/512#issuecomment-523837263) and it's still in the Tasmota code, yet it looks like UnishoxStrings broke it.

**Pull request merged**
