### PR TITLE
Support Home Assistant state class

### PR DESCRIPTION
**Pull request by mitchellrj**
## Description:

**Related issue (if applicable):** fixes #13946

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

Unsure how to compile or run tests locally, couldn't find documentation on that part. Will wait for CI.

### CODE REVIEW

**Comment by arendst** [comment]
That's a lot of duplication wasting ditto code space.

There must be a better way to add the same text to almost all entries. Keywords "lookup table" and "fixed string".

**Comment by mitchellrj** [comment]
That sounds good to me if you're happy with expanding the scope to include a small refactor 👍

**Comment by ascillato** [comment]
Bump

**Comment by ascillato** [comment]
bump

**Comment by ascillato** [comment]
bump

**Comment by ascillato** [comment]
bump

**Pull request closed without merging**
