### PR TITLE
Zigbee friendly names per endpoint

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Zigbee now support ability to specify different friendly names for each endpoint. This is useful for n-way switches.

The command `ZbName` can take an additional parameter as endpoint number. The endpoint must already be registered.

- `ZbName 0x9DF2,Switch` to set a default name to the device
- `ZbName 0x9DF2,` to remove the default name
- `ZbName 0x9DF2,Sw2,2` to use`Sw2` as friendly name for messages received from or sent to endpoint `2`
- `ZbName 0x9DF2,,2` to remove the name for endpoint 2

Example:

`ZbRestore {"Device":"0x9DF2","Name":"Switch","Names":{"2":"Sw2"},"IEEEAddr":"0x842E14FFFE13A51E","Endpoints":[1,2],"Config":["O01","O02"]}`

You can toggle the switch on endpoint 2 in two ways:

Via global name and endpoint:
`ZbSend {"Device":"Switch","Endpoint":2,"Send":{"Power":1}}`

Or via the device specific name:
`ZbSend {"Device":"Sw2","Send":{"Power":1}}`

Other change: the internal file definition is now moving to `zbv4` to allow easier extensions.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by urechi** [comment]
Nice one, many thanks for all the hard work.

**Comment by s-hadinger** [comment]
You're welcome. The ability to control multiple endpoints with Alexa is coming soon

**Comment by urechi** [comment]
Hey @s-hadinger,

I've got some time now to test the changes that you've made. I have `ZbDeviceTopic 1` and `SetOption112 1` for the friendly name in the topic.

```
17:30:57.007 CMD: ZBName 0xD4AF
17:30:57.009 SRC: WebConsole from 192.168.1.44
17:30:57.010 CMD: Grp 0, Cmd 'ZBNAME', Idx 1, Len 6, Pld 54447, Data '0xD4AF'
17:30:57.021 MQT: stat/SmartHub-D3F00C/RESULT = {"0xD4AF":{"Name":"Kitchen_Light_Switch","Names":{"1":"Kitchen Light Switch Left","2":"Kitchen Light Switch Right"}}}
```
Device friendly name is `Kitchen_Light_Switch`
Endpoint 1 friendly name is `Kitchen Light Switch Left`
Endpoint 2 friendly name is `Kitchen Light Switch Right`

Before I named my endpoints the MQTT topic used to be `tele/SmartHub-D3F00C/Kitchen_Light_Switch/SENSOR`
After I named my endpoints the topics are `tele/SmartHub-D3F00C/Kitchen_Light_Switch_Left/SENSOR` and `tele/SmartHub-D3F00C/Kitchen_Light_Switch_Right/SENSOR`

So it looks like the endpoint friendly name takes precedence over device friendly name in the MQTT topic.

Also, the SENSOR JSON payload looks like this now (with `ZbNoPrefix` enabled):
```
17:34:55.344 MQT: tele/SmartHub-D3F00C/Kitchen_Light_Switch_Left/SENSOR = {"Kitchen Light Switch Left":{"Device":"0xD4AF","Name":"Kitchen Light Switch Left","Power":1,"Endpoint":1,"LinkQuality":53}}
```
So again the device friendly name is replaced by the endpoint friendly name at the beginning.


Before the changes:
Topic:`tele/<hub_name>/<device_friendly_name>/SENSOR`
JSON: `{"<device_friendly_name>":{"Device":"0x0000","Name":"<device_friendly_name>","Power":1,"Endpoint":1,"LinkQuality":53}}`

After the changes:
Topic: `tele/<hub_name>/<endpoint_friendly_name>/SENSOR`
JSON: `{"<endpoint_friendly_name>":{"Device":"0x0000","Name":"<endpoint_friendly_name>","Power":1,"Endpoint":1,"LinkQuality":53}}`

My initial suggestion was that the topic continues to use the device friendly name and the JSON payload contains both the device friendly name and endpoint friendly name like in this example here:
Topic: `tele/<hub_name>/<device_friendly_name>/SENSOR`
JSON: `{"<device_friendly_name>":{"Device":"0x0000","Name":"<endpoint_friendly_name>","Power":1,"Endpoint":1,"LinkQuality":53}}`

This is not a problem but I wanted to double check with you that this is the desired behavior. Happy to stay as it is.

**Comment by s-hadinger** [comment]
I'm not sure I'm following you on this. The point was precisely to have different topics and different keys in JSON, to be more in the spirit of MQTT if you need retained messages or IOT shadows.

This should be seen externally as different virtual devices.

**Comment by urechi** [comment]
You are right and that's perfectly fine, happy with the approach to be seen externally as different virtual devices.

**Pull request merged**
