### PR TITLE
Add template for Luminea ZX2820

### PR DESCRIPTION
**Pull request by ascillato**
https://github.com/arendst/Sonoff-Tasmota/issues/4904

Luminea ZX2820 (Smart plug with power monitoring)

@arendst Please, review it if you want to add this device to the list or as an optional. Thanks

### CODE REVIEW

**Comment by elzershark** [comment]
no function. Modell ZX-2820-675
funktioniert nicht. kein schalten. keine anzeige. kein gar nichts. nur über generic Einstellung

**Comment by knop-ster** [comment]
Ich werd’s die Tage checken.

I will Check it next days.

**Comment by elzershark** [comment]
Modul BlitzWolf SHP Module(45) for the Modell ZX-2820-675 is working

**Comment by knop-ster** [comment]
I was able to check the profile for ZX2820-675. My device calculates the correct Voltage, etc. and i can turn it on and off agein. I don't know where is the problem. 

Does your Luminea looks like this?

img_7894
img_7893

**Comment by elzershark** [comment]
it is the old version... my is the new...  but is ok. i have the template..

**Pull request merged**
