### PR TITLE
Add virtual Buttons & Switches in Digtian driver

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

**Related issue (if applicable):** Followup on previous PR and the discussion with @jeroenst

Take advantage of recent support for virtual Buttons and Switches to implement that on the inputs of the DINGTIAN Relay board

3 new optional defines are supported:
```C++
#define DINGTIAN_INPUTS_INVERTED               // Invert input states (Hi => OFF, Low => ON)
#define DINGTIAN_USE_AS_BUTTON                 // Inputs as Tasmota's virtual Buttons
#define DINGTIAN_USE_AS_SWITCH                 // Inputs as Tasmota's virtual Switches
```
- Only one of DINGTIAN_USE_AS_BUTTON or DINGTIAN_USE_AS_SWITCH should be used
- DINGTIAN_INPUTS_INVERTED allows Buttons Inverted (and also invert values in Berry's `tasmota.get_switches()`). It also works with Switches although inversion can be handled by `SwitchMode`
- All Buttons or Switches features are supported (including Rules trigger, default attachement to power and options to detach, multipress buttons, all switchmodes, ....)
- :warning:  Warning: On the 32 I/O version of the board, Tasmota is limited to 28 switches. Buttons can be up to 32.
- Virtual buttons/switches are always enumerated after native GPIO. Use loglevel 3 to see which indexes are assigned to Dingtian I/O:
```haskell
00:00:00.123 DNGT: clk:14, sdi:13, q7:16, pl:32, rck:15, count:8
00:00:00.124 DNGT: Dingtian relays: POWER1 to POWER8
00:00:00.125 DNGT: Dingtian inputs: Switch1 to Switch8
```

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by jeroenst** [comment]
I can confirm this works ok

**Comment by jeroenst** [comment]
I want to thank @barbudor for this pull request.

I'm using it to control a heat pump and gas boiler by a berry script:
https://github.com/jeroenst/dingtian-heatpump-control/tree/master

**Comment by stefdewilde** [comment]
@jeroenst I assume you did this with the dingtian boards that weren't preprogrammed?

**Comment by jeroenst** [comment]
@stefdewilde I had to request a dingtian board which is unlocked and only contained test software which I erased before flashing Tasmota.

**Comment by barbudor** [comment]
I'm unsure about the effect of `SetOption114`. I haven't tried it
Can you try with `SwitchMode<x> 15` ?

@arendst Any reason why `SO114` wouldn't work with virtual switches ?

**Comment by arendst** [comment]
Just teste SO114 with PCF8574 virtual switches and it works as expected:
```
23:02:18.995-027 SRC: Switch
23:02:19.000-024 MQT: stat/wemos5/POWER4 = {"POWER4":"ON"}
23:02:19.005-025 MQT: stat/wemos5/POWER4 = ON
23:02:19.575-027 CFG: Saved to flash at FA, Count 733, Bytes 4096
23:02:19.683-027 SRC: Switch
23:02:19.690-024 MQT: stat/wemos5/POWER4 = {"POWER4":"OFF"}
23:02:19.695-025 MQT: stat/wemos5/POWER4 = OFF
23:02:20.611-027 CFG: Saved to flash at F9, Count 734, Bytes 4096
23:03:14.238-027 CMD: switchmode
23:03:14.240-027 SRC: Serial
23:03:14.244-027 CMD: Grp 0, Cmd 'SWITCHMODE', Idx 1, Len 0, Pld -99, Data ''
23:03:14.252-024 MQT: stat/wemos5/SWITCHMODE = {"SwitchMode1":0}
23:03:33.160-027 CMD: so114
23:03:33.162-027 SRC: Serial
23:03:33.165-027 CMD: Grp 0, Cmd 'SO', Idx 114, Len 0, Pld -99, Data ''
23:03:33.173-024 MQT: stat/wemos5/SO = {"SetOption114":"OFF"}
23:03:36.943-027 CMD: so114 1
23:03:36.945-027 SRC: Serial
23:03:36.948-027 CMD: Grp 0, Cmd 'SO', Idx 114, Len 1, Pld 1, Data '1'
23:03:36.956-024 MQT: stat/wemos5/SO = {"SetOption114":"ON"}
23:03:37.617-027 CFG: Saved to flash at F8, Count 735, Bytes 4096
23:03:40.379-024 MQT: stat/wemos5/SWITCH1 = {"Switch1":{"Action":"TOGGLE"}}
23:03:41.395-024 MQT: stat/wemos5/SWITCH1 = {"Switch1":{"Action":"TOGGLE"}}
23:03:44.394-024 MQT: stat/wemos5/SWITCH1 = {"Switch1":{"Action":"TOGGLE"}}
23:03:45.097-024 MQT: stat/wemos5/SWITCH1 = {"Switch1":{"Action":"TOGGLE"}}
23:03:47.264-024 MQT: stat/wemos5/SWITCH2 = {"Switch2":{"Action":"TOGGLE"}}
23:03:47.873-024 MQT: stat/wemos5/SWITCH2 = {"Switch2":{"Action":"TOGGLE"}}
23:03:49.503-024 MQT: stat/wemos5/SWITCH3 = {"Switch3":{"Action":"TOGGLE"}}
23:03:50.212-024 MQT: stat/wemos5/SWITCH3 = {"Switch3":{"Action":"TOGGLE"}}
23:03:51.969-024 MQT: stat/wemos5/SWITCH4 = {"Switch4":{"Action":"TOGGLE"}}
23:03:52.782-024 MQT: stat/wemos5/SWITCH4 = {"Switch4":{"Action":"TOGGLE"}}
```
For SO114 to work ``switchmode`` needs to be set between 0 and 2 and SO19 should be 0

**Comment by Maratug** [comment]
I found my problem. I had switchtopic defined and when I toggle a switch instead of "SRC: Switch" I had "SRC: MQTT" and so114 didn't work. Your log was very helpful. @arendst and @barbudor Thank you

**Pull request merged**
