### PR TITLE
additional to add DeviceName PR

### PR DESCRIPTION
**Pull request by AlfaBravoX**
I am operating an android App that is heavily using Tasmota devices data. The app is made so, it creates GUI only using Tasmota retain mqtt messages. This is big advantage, because other gui apps usually needs to modify GUI config when new elemet is added. This is not necessary here. One limitation is missing DeviceName in Telemetry STATE message. IThis patch may help others who are building GUI just based on MQTT messages. to keep my app simple I want to avoid Using discovery Tasmota mqtt messages and deal with multiple topics correlating them later

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.2.1
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
Please make only 1 PR, not 2 for the same features

**Comment by Jason2866** [comment]
In general, Tasmota is designed to have as less as possible redundant infos in messages. Take in account that that your personal wanted changes are not going to be included.

**Comment by ascillato2** [comment]
Hi,

For device name, you can just send the device name command empty and it will respond with its name. No need to add this as a constant in status message.

Closing as it is not going to be merged. Sorry.

**Comment by AlfaBravoX** [comment]
Hold the bus please, if GUI has ie. dozens of elements, it means APP needs to send dozens `DeviceName` commands, so where is the resources saving?? If PR is approved for INFO1 for example, problem is solved and it wont hurt anyone not even too much more CPU cycles. My quite long justification was pointing to the fact, that there are no retained message contains `DeviceName` (ok not counting `discovery`) Other coders may benefit from this as well when building config file independent GUIs. Just my 5 cents.

**Comment by ascillato** [comment]
https://github.com/arendst/Tasmota/pull/14595#issuecomment-1022201565

**Comment by Jason2866** [comment]
Smartphones have way more ressources in every aspect than a ESP8266. Why not doing proper mqtt json parsing? You will get all infos detailed and very well structured.

**Comment by arendst** [comment]
You can find the device name in the Tasmota discovery message:
```
15:58:48.905 MQT: tasmota/discovery/98F4AB6D2DB4/config = {"ip":"192.168.2.115","dn":"Esp32d","fn":["Esp32d",null,null,null,null,null,null,null],"hn":"esp32d","mac":"98F4AB6D2DB4","md":"ESP32-DevKit","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"2022.01.3","t":"esp32d","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":0,"lt_st":0,"sho":[0,0,0,0],"ver":1} (retained)
```
where dn is the DeviveName.

**Comment by AlfaBravoX** [comment]
Yes, I saw DeviceName included in discovery while I was walking over the code, ok so I think I can use `dn` for getting the name and handle JSON structure at APP itself

**Pull request closed without merging**
