### PR TITLE
Generate TEMPLATES.md with new template format

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

Updates `templates.py` in order to generate TEMPLATES.md based on new template format

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [NA] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [NA] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
Please hold, as suggested by Python Master @jziolkowski , I will replace pycurl by requests

**Comment by arendst** [comment]
I'll hold

**Comment by barbudor** [comment]
Hi Theo @arendst 
Completed the change and also tested against already converted templates just in case
You can merge at your convenience
Thanks

**Comment by arendst** [comment]
Thx!

**Pull request merged**
