### PR TITLE
Added ENS160 (Air quality) and ENS210 (Temperature & Humidity) sensor

### PR DESCRIPTION
**Pull request by chrfriese123**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Did i missed something i see no Tasmota driver?

**Comment by ascillato** [comment]
Hi, 

Did you made a driver? A library alone won't do anything.

**Comment by chrfriese123** [comment]
Hi,
I'm sorry my mistake. I'm new to Gitpod / Github and have the drivers in my fork
     https://github.com/chrfriese123/Tasmota/tree/development/tasmota

Driver files are
    xsns_83_ens160.ino
    xsns_84_ens210.ino

I'm not sure how to commit. I'll try and hopefully don't destroy anything.

**Comment by Jason2866** [comment]
@chrfriese123  didnt saw that your PR was against branch master.
PR are here only valid against branch development.
Please update your development branch and include all the needed changes.

**Pull request merged**
