### PR TITLE
Experimental support for gesture sensor APDS 9960

### PR DESCRIPTION
**Pull request by Staars**
Hi, 

this might not go into the main branch, but I thought I share my experiment.

I had a APDS-9960 lying around and after testing it on an ARDUINO-2560 I wanted to get it to work in Sonoff-Tasmota. Therefore I adapted the library and the examples from Shawn Hymel (Sparkfun), which in its core stay unchanged.

Beside the resulting sensor driver there is new GPIO-pin-name introduced, which is IRQ. Probably it would be possible to realize it via polling in the state loop too.

Observations:
The main problems that I encountered had to do with power consumption. I had to use a 10µF Capacitor over 3.3V and GND but your mileage may vary here a lot. At least the general Sonoff-user should have enough experience to deal with it given the fact that beforehand you had to solder some pins on a PCB, right?

Current state:
The gesture sensor is configured for IRQ and gives a MQTT-Message. 
You can switch gesture mode on and off via MQTT-command GESTURE (0 and 1 or nothing to get status).

When gesture mode is off, the webserver shows ambient light level and telemtry data gives: RED, BLUE, GREEN and AMBIENT.

### CODE REVIEW

**Comment by renne** [comment]
I want to use the APDS-9960. Are there any plans to merge the pull request?

**Comment by ascillato** [comment]
Hi,

Sorry that was not responded before. There were lots of issues.

I added the enhacement label to the issue be taken into account.

Very nice chip! Thanks for share :+1:

**Comment by Staars** [comment]
I haven‘t looked at the code for months and there are obviously lots of changes in TASMOTA. 
If I find the time I will try to rebuild the driver as a „user defined sensor“ and then we will see, if there is any interest.

Best regards

**Comment by renne** [comment]
[H801 5-channel LED-controller](https://github.com/arendst/Sonoff-Tasmota/wiki/H801) with room-sensors:
* [RCWL-0516 microwave motion detector](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-RCWL-0516-Microwave-Radar-Sensor)
  * motion detection in the complete room
* [Bosch SensorTec BME280 athmospheric sensor](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-BME280-Temperature,-Humidity-and-Pressure-Sensor)
   * Temperature
   * Humidity
   * Pressure
* APDS-9960
   * Ambient light brightness
   * Gesture/promiximity control

[BME280](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-BME280-Temperature,-Humidity-and-Pressure-Sensor) and [RCWL-0516](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-RCWL-0516-Microwave-Radar-Sensor) work fine in generic profile. It's only missing support for user defined GPIO2/GPIO3 (I²C) in H801 profile and the APDS-9960 library to get a sophisticated closed-loop brightness/color temperature control including gesture based setpoints. ;-)

Wiring:

| GPIO | H801 | RCWL-0516 | BME280 | APDS-9960 |
| --- | --- | --- | --- | --- |
| | 3.3 | 3V3 | VIN | VIN |
| | GND | GND | GND | GND |
| 3 | TX | NC | SCL | SCL |
| 2 | RX | NC | SDA | SDA |
| 0 | J3 | OUT | NC | NC |
| | NC | NC | NC | INT |

00001img_00001_burst20180619132219

**Comment by Staars** [comment]
Okay, I have refactored my code und it works (somehow;).
It is definitely still buggy but it should be okay to test some things out.

I try to upload it tomorrow, maybe I can iron out some bugs. Please don't expect a perfect solution.

**Comment by Staars** [comment]
Good morning, 
I have refreshed my fork of tasmota and (with my lack of git-fu) disconnected my fork from this pull request.
But You can find the new version on my GitHub-account.

Maybe I can get some response from Rene and if this thing matures, I could do a new PR or leave the driver in an own tiny repository.

If there are any questions, please contact me here. 

Best regards
Christian

**Comment by renne** [comment]
Is there anything to configure or comment/uncomment in your code or just cloning and building like standard Tasmota?

**Comment by Staars** [comment]
Hi,

please uncomment the DEFINE in line 26. 
It should compile (hopefully;). Then upload/flash.

In Tasmota configure I2C in the usual  way and (ab-)use „GPIO-DSB“ for the interrupt pin.

For basic  testing use some generic board and only the apds9960 (no additional sensor). I added a small capacitor between vcc and ground.

You should see something in the web console. 

If that works, configure MQTT and react to the messages. I use Node-Red.

I will clean up the code in next weeks but I  don‘t have very much time atm . If possible, I will add the functionality for „rules“, but first I have to understand, how to implement it.

Last notes: 
NEAR and FAR work quite unreliable, which is very likely not a software problem.
In the future I will rename OVERLOAD to LONG. Initially I only used it as a debug message, but we can use it as a special gesture (long press/hold) too.


Best regards
Christian

**Comment by renne** [comment]
Hi,
I'm using GPIO0 as "04 DS18x20". As the GPIOs are quite short on the H801 (I'm going to use GPIO0 for motion detection) I suggest to support interruptless operation by polling in the main loop. Proximity works well in gesture messages but R,G,B,C values were very rare and don't show up anymore even when using a LED flashlight.

NEAR and FAR are unreliable here and with the RaspberryPi 3B, too. This may be a timing/sensitivity issue. We probably need more testers to find a pattern. So I suggest to postpone NEAR/FAR gestures.
"OVERLOAD" can be used as "OFF/ON" toggle if we cannot get "NEAR/FAR" working reliably (although I set GPIO0 to "04 DS18x20" I get "ON/OFF" messages).

Luckily I installed Node-Red on Monday. ;-)

Best regards,

Renne

**Comment by renne** [comment]
Hi,

ToDos:

- APDS-9960 needs restart via MQTT/web-interface to make it work after connecting power
- OVERLOAD necessary to print RGBC values, should also happen with teleperiod and light changes
- RGBC values do not change after first reading
- find alternative for hardware interrupt

Capacitors (10nf, 10µF, 220µF, 1000µF) have no influence compared with non-capacitor operation on H801. The effects I saw were just the body influencing the sensor.

Best regards
Renne

**Comment by Staars** [comment]
New version in the other repo, see commit-message for changes.
To see RGBAP-Message turn off gesture mode (gesture 0 in the console) and wait for tele message, see web page or enter status 10.

I have no idea atm regarding the reboot problems.

I think the need for a capacitor will vary a lot and if you don't one, it's fine.

**Comment by renne** [comment]
Except the need to restart after connecting power it works without a hardware interrupt!  :-)

**Comment by Staars** [comment]
Good point, I will simply undefine use_veml6070. 
I think, that a user-driver should be deactivated by default (thats why I did the uncomment thing in line 26) and then you see whats going on, when you activate the driver in the source code (including the deactivation of conflicting drivers). I hope this makes sense;)

If you want to track changing sensor values, you can decrease the tele-interval to the minimum and react to it via Node-Red. At least this function is built-in and doesn’t require additional code.
But I promise, the next thing I try to implement is the use of rules.

**Comment by renne** [comment]
I suggest to add the `#define USE_APDS9960` directly above `USE_VEML6070` in user_config.h and add a comment they both use 0x39h. I suggest to throw a compile error if both are activated. If you just disable the VEML6070 it compiles fine. This can lead to hours of debugging for someone who wants to use the VEML6070 and doesn't know why it is not working.

**Comment by renne** [comment]
@Staars 
Do you have any problems the APDS-9960 is not initialized after powering the ESP8266?

**Comment by Staars** [comment]
Yes, this would be possible (and useful) if the driver becomes part of the tasmota project.
At the moment I only have to deal with one file, which works like a plug-in and forces the user to actively turn it on and read the underlying code (I will add some comments to warn about SHT and VEML6070). IMHO this is okay for now.
Let‘s see how far we can get with the development and then I can make a new pull request. 
As you might know, the response to my last one was not exactly overwhelming ;)

Best regards
Christian

**Comment by Staars** [comment]
I‘m still not sure, why the sensor is sometimes not initialized and still search for a pattern.

**Comment by renne** [comment]
```
00:00:00 Project sonoff Sonoff (Topic sonoff, Fallback DVES_6F9563, GroupTopic sonoffs) Version 6.0.0a-2_4_1
00:00:00 I2C: APDS9960 found at address 0x39
00:00:00 APDS9960 not initialized
```
The `APDS9960_init()` call seems to fail.

**Comment by Staars** [comment]
This is after power on?
Does a reboot via web interface help?

**Comment by renne** [comment]
Yes, every time I power the H801 on I get that message. Clicking "Restart" or executing "restart 1" in the web-interface solves the problem.

**Comment by Staars** [comment]
Okay, same here. I will try out some things tomorrow.

**Comment by Staars** [comment]
Some changes:
-support for rules (Tele-APDS9960#Gesture=1...6) for in-device actions
-necessary change of the mqtt-payload to a number format
-fix initialization error on power on

@renne: 
If you can live with the changes, I would further clean up the code and make a new PR to end this thread.

**Comment by renne** [comment]
With numbers for the gestures users have to look up the documentation when configuring theirs systems. So I suggest to replace the numbers of the gestures with names (up, down, left, right, long, none).

**Comment by Staars** [comment]
Yes, that is the caveat. 

Here is my plan:

I will make a new Pull Request with the recent driver, so please watch out for it and respond there. After I see activity there, I will close this old PR.

I will test further, if „rules“ can respond to strings or maybe I extend the JSON (e.g. {„Gesture“:1, „Up“} or something like that).

Anyway, thank You for your help. I’ll see you on the other side (thread;)

**Comment by Staars** [comment]
I made a new PR #3051, so I close this now.

Thank's to all responders!

**Pull request closed without merging**
