### PR TITLE
Add %json% substitution for rules

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

**Related issue (if applicable):** fixes #20709

Allows to use the pseudo-variable `%json%` to republish the complete JSON which triggered the rules.
Can be used with `WebQuery`

Example:

```
13:39:14.264 CMD: rule1 on tele-uptime do WebQuery http://httpbin.org/post POST %json% endon
13:39:16.425 RUL: TELE-UPTIME performs "WebQuery http://httpbin.org/post POST {"Time":"2024-02-13T13:39:16+01:00","Uptime":"0T00:10:43","UptimeSec":643,"Heap":19,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":48,"MqttCount":1,"Wifi":{"AP":1,"SSId":"some-wifi","BSSId":"80:XX:XX:X:XX:80","Channel":10,"Mode":"11n","RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:04"}}"
13:39:16.991 MQT: nodemcu/stat/WEBQUERY = {"WebQuery":{  "args": {},   "data": "{\"Time\":\"2024-02-13T13:39:16+01:00\",\"Uptime\":\"0T00:10:43\",\"UptimeSec\":643,\"Heap\":19,\"SleepMode\":\"Dynamic\",\"Sleep\":50,\"LoadAvg\":48,\"MqttCount\":1,\"Wifi\":{\"AP\":1,\"SSId\":\"some-wifi\",\"BSSId\":\"80:XX:XX:XX:XX:80\",\"Channel\":10,\"Mode\":\"11n\",\"RSSI\":68,\"Signal\":-66,\"LinkCount\":1,\"Downtime\":\"0T00:00:04\"}}",   "files": {},   "form": {},   "headers": {    "Accept-Encoding": "identity;q=1,chunked;q=0.1,*;q=0",     "Content-Length": "294",     "Host": "httpbin.org",     "User-Agent": "ESP8266HTTPClient",     "X-Amzn-Trace-Id": "Root=1-65cb62f5-1d29c13a3ec52d3b0e02ec97"  },   "json": {    "Heap": 19,     "LoadAvg": 48,     "MqttCount": 1,     "Sleep": 50,     "SleepMode": "Dynamic",     "Time": "2024-02-13T13:39:16+01:00",     "Uptime": "0T00:10:43",     "UptimeSec": 643,     "Wifi": {      "AP": 1,       "BSSId": "80:AF:CA:05:41:80",       "Channel": 10,       "Downtime": "0T00:00:04",       "LinkCount": 1,       "Mode": "11n",       "RSSI": 68,       "SSId": "mado-wifi",       "Signal": -66    }  },   "origin": "XXX.XX.XXX.XXX",   "url": "http://httpbin.org/post"}}
```

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
I hope the OP has enough memory to service ``status0`` as %json%

**Comment by Jason2866** [comment]
Special use case. Like how small the solution is. Nice PR!

**Comment by barbudor** [comment]
> I hope the OP has enough memory to service `status0` as %json%

What is the "OP" ?
I'm not allocating any additional memory but just re-using a pointer to the original JSON string

Are you refering to what happens in WebQuery ?
Indeed it would be use with large messages like Status0. I'll try later how it behave

**Comment by Jason2866** [comment]
"OP" = Original Poster

**Comment by arendst** [comment]
With OP I meant the original #20709 guy. By replacing %json% witht eh full JSON message you extent the rule String with the full json message. In case of a status0 message this is over 3k5 ram !?!

**Comment by barbudor** [comment]
I confirm, this PR is not safe
Let me check if it can be easily solved otherwise we will have to revert

**Comment by barbudor** [comment]
Actually it is very easy to break with replace, even without this PR

Anyhow, @arendst I believe it is not safe and we should revert that before more problems occurs
May be worth rethinking the variable substitution to make it more memory efficient but that will need a bit of thinkink

> Special use case. Like how small the solution is. Nice PR!

Small but deadly !

**Pull request merged**
