### PR TITLE
Revert to modular build 2.5.0 release

### PR DESCRIPTION
**Pull request by Jason2866**

### CODE REVIEW

**Comment by Jason2866** [comment]
@ivankravets  With Arduino IDE there is no problem with Core 2.5.0. Generated firmware does work without issues. The problem is only with Platformio

**Comment by ivankravets** [comment]
Do you use the same flags? LD Script?

**Comment by Jason2866** [comment]
Yes, same flags. Nothing changed in Arduino. Linker script from Arduino used
image

**Comment by Jason2866** [comment]
For building with Platformio this setting is used:
```
platform                  = espressif8266@2.0.0
build_flags               = ${esp82xx_defaults.build_flags}
                            -Wl,-Teagle.flash.1m.ld
                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH_LOW_FLASH
                            -DVTABLES_IN_FLASH
                            -fno-exceptions
                            -lstdc++
```

**Comment by Jason2866** [comment]
New toolchain does work with this setup too:
```
platform                  = espressif8266@2.0.0
build_flags               = ${esp82xx_defaults.build_flags}
                            -Teagle.flash.1m.ld
                            -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH_LOW_FLASH
                            -DVTABLES_IN_FLASH
                            -fno-exceptions
                            -lstdc++
```
So the option `-Wl,` does mess up. This Option shouldnt do any harm here....

**Comment by ivankravets** [comment]
You need espressif8266@2.0.1 or above. Not 2.0.0.

**Pull request merged**
