### PR TITLE
Fix comments to reflect correct file name

### PR DESCRIPTION
**Pull request by andrethomas**
Fix comments at top of the file to reflect correct file name to xsns_26_lm75ad.ino

### CODE REVIEW

**Comment by arendst** [comment]
I'm updating it already by hand :-) as I want it to use my standard conversion.

Just looked at the handbook and am wondering why you expect bit 15 to be the minus indicator as the handbook talks about either bit 11 or 9 depending how the chip is configured. Did you check for negative temperatures?

**Comment by andrethomas** [comment]
Cool thanks

Yup, view 7.4.3 Temperature register in datasheet https://www.nxp.com/docs/en/data-sheet/LM75A.pdf

D10 is checked, if clear means + temp and if set means - temperature.

I check it in float LM75ADConvertTemp(uint16_t t) with & 0x8000 (0b1000 0000 0000 0000)
Then I lose the bit by shifting it out and then drop the lower 5 bits because they are not used.

We only went down to 7 deg C outdoors last night but I'll dunk it in the freezer and see what happens to make sure

**Comment by arendst** [comment]
Ah, you're right! the data is shifted to the left by 5 bits. OK OK OK.

**Comment by andrethomas** [comment]
Hmm, hang on.. I'm getting weird numbers on the negative's from the freezer... will debug

**Comment by arendst** [comment]
Yeah, there is more to it for negative numbers than just the shift right. It's 2's complement so we need to substract a value:

image

**Comment by arendst** [comment]
See if this works:
```
  int16_t sign = 1;
  if (t & 0x8000) { // we are getting a negative temperature value
    t = (~t) +0x20;
    sign = -1;
  }
  t = t >> 5; // shift value into place (5 LSB not used)
  tmpt = ConvertTemp(sign * t * 0.125);
```

**Comment by andrethomas** [comment]
We were almost on the same track but your code is more opto'd 👍 

`float LM75ADConvertTemp(uint16_t t) {
  int16_t sign = 1;
  if (t & 0x8000) { // we are getting a negative temperature value
    t = (~t) +0x20;
    sign = -1;
  }
  t = t >> 5; // shift value into place (5 LSB not used)
  return ConvertTemp(sign * t * 0.125);
}`

Here's a log on the recovery from removing it from the freezer.. i added the raw value just for debugging on my side

`{"Time":"2018-06-05T15:33:16","LM75AD":{"Temperature":-12.2},"LM75AD":{"RawValue":62400},"TempUnit":"C"}
{"Time":"2018-06-05T15:33:31","LM75AD":{"Temperature":-12.2},"LM75AD":{"RawValue":62400},"TempUnit":"C"}
{"Time":"2018-06-05T15:33:46","LM75AD":{"Temperature":-12.2},"LM75AD":{"RawValue":62400},"TempUnit":"C"}
{"Time":"2018-06-05T15:34:01","LM75AD":{"Temperature":-11.8},"LM75AD":{"RawValue":62528},"TempUnit":"C"}
{"Time":"2018-06-05T15:34:16","LM75AD":{"Temperature":-5.7},"LM75AD":{"RawValue":64064},"TempUnit":"C"}
{"Time":"2018-06-05T15:34:31","LM75AD":{"Temperature":-1.8},"LM75AD":{"RawValue":65088},"TempUnit":"C"}
{"Time":"2018-06-05T15:34:46","LM75AD":{"Temperature":1.5},"LM75AD":{"RawValue":384},"TempUnit":"C"}
{"Time":"2018-06-05T15:35:01","LM75AD":{"Temperature":4.0},"LM75AD":{"RawValue":1024},"TempUnit":"C"}
{"Time":"2018-06-05T15:35:16","LM75AD":{"Temperature":6.1},"LM75AD":{"RawValue":1568},"TempUnit":"C"}
{"Time":"2018-06-05T15:35:31","LM75AD":{"Temperature":7.6},"LM75AD":{"RawValue":1952},"TempUnit":"C"}`

**Comment by andrethomas** [comment]
```
float LM75ADConvertTemp(uint16_t t) {
  int16_t sign = 1;
  if (t & 0x8000) { // we are getting a negative temperature value
    t = (~t) +0x20;
    sign = -1;
  }
  t = t >> 5; // shift value into place (5 LSB not used)
  return ConvertTemp(sign * t * 0.125);
}
```

**Comment by arendst** [comment]
Ha that's even shorter!!

Thnx for testing. Great it works. Let's close this one.

**Pull request closed without merging**
