### PR TITLE
Refactor webcam , core2

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

refactor webcam, make rtsp a software selectable option
refactor core2
some fixes for scripter

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Wouldnt it be usefull to have [here](https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_configurations_ESP32.h) some standard defines for the core2

**Comment by gemu2015** [comment]
agree

here are my defines.

// these may be useful for all core2 users
#define USE_M5STACK_CORE2
#define USE_UFILESYS
#define USE_SDCARD
#define SDCARD_CS_PIN 4
#define GUI_TRASH_FILE
#define USE_I2C
#define USE_BMA423
#define SAY_TIME
#define USE_WEBRADIO
#define USE_SPI
#define USE_DISPLAY
#define USE_DISPLAY_ILI9342
#define USE_TOUCH_BUTTONS
#define JPEG_PICTS
#define USE_FT5206
#define USE_MPU6886
#define USE_SENDMAIL
#define USE_ESP32MAIL

// these are script related
#define UFSYS_SIZE 8192
#define USE_SCRIPT_TASK
#define LARGE_ARRAYS
#define SCRIPT_LARGE_VNBUFF
#define USE_SCRIPT_GLOBVARS
#define USE_SCRIPT_SUB_COMMAND
#define MAXFILT 10
#define USE_ANGLE_FUNC
#define MAXVARS 75
#define MAXSVARS 15
#define SCRIPT_FULL_WEBPAGE
#define SCRIPT_GET_HTTPS_JP
#define USE_GOOGLE_CHARTS

**Comment by arendst** [comment]
Thx. I'll add it tasmota_configurations_ESP32.h

**Comment by boualimed** [comment]
في الأربعاء، 20 جانفي، 2021 10:47 ص gemu <notifications@github.com> كتب:

**Comment by Jason2866** [comment]
@boualimed  Only English

**Pull request merged**
