### PR TITLE
Sensirion SGP30 Support

### PR DESCRIPTION
**Pull request by gemu2015**
support for SGP30 environmental sensor

### CODE REVIEW

**Comment by arendst** [comment]
Give it a try and let me know if it works as I do not own this sensor.

**Comment by gemu2015** [comment]
it works a couple of weeks already

the sensor is from eckstein on ebay  =>https://www.ebay.de/itm/282823690099 <https://www.ebay.de/itm/282823690099>

**Comment by arendst** [comment]
It might work with your code but I did a rewrite using the sensors handbook regarding stability.

Pls have go at my implementation and let me know if it works too.

**Comment by gemu2015** [comment]
after OTA the module stays offline, i must disassemble device and flash via serial.  

i do not have the time at the moment, i will report at least tomorrow

**Comment by gemu2015** [comment]
ok, it works.

merging your new version updated my user_config_overwrite and i lost my ap access (why is that, it is on gitignore ??)

thank you!

**Comment by gemu2015** [comment]
you should name it eCO2 since it is not the same as CO2

**Comment by arendst** [comment]
Yeah that gitignore thing is an item I'm working on in another PR. It seems I will have to provide a user_config_override_sample file instead of the ready made user_config_override.h

Glad it works. What's the difference between CO2 and eCO2?

**Comment by gemu2015** [comment]
From the SGP30 datasheet => equivalent CO2 => eCO2
1 CO2eq output is based on a hydrogen measurement. The SGP is not suited for applications where real CO2 detection is required.
Von meinem iPad gesendet

**Comment by gemu2015** [comment]
A Major accurracy improvement would be to add a Humidity value to the SGP30 calculation In case you have a Humidity Sensor Running in parallel 

Von meinem iPad gesendet

**Comment by arendst** [comment]
Looked at the humidity part but calculating absolute humidity seems to be a challenge in it self. The sensirion handbook formula is way of compared to a google absolute humidity table.

The formula from here https://onlineconversion.vbulletin.net/forum/main-forums/convert-and-calculate/322-relative-humidity-absolute-humidity/page2?t=567 provides another different value.

For now I stop developing humidity support.

If you want to get humidity and temperature from an attached sensor I used the following code within the Sgp30Show Json routine succesfully:
```
      double sgp30_tm = 0;
      double sgp30_rh = 0;

      char *temperature = strstr(mqtt_data, D_JSON_TEMPERATURE);  // ..,"SI7021-14":{"Temperature":22.0,"Humidity":42.8},"TempUnit":"C"}
      if (temperature) sgp30_tm = strtod(temperature +strlen(D_JSON_TEMPERATURE) +2, NULL);
      char *humidity = strstr(mqtt_data, D_JSON_HUMIDITY);  // ..,"SI7021-14":{"Temperature":22.0,"Humidity":42.8},"TempUnit":"C"}
      if (humidity) sgp30_rh = strtod(humidity +strlen(D_JSON_HUMIDITY) +2, NULL);
```

**Comment by gemu2015** [comment]
Yes you are right, the special absolute humidity is a complicated formula and probably not worth the effort

the difference between CO2 and eCO2 is however important and we should not use the same name

**Pull request closed without merging**
