### PR TITLE
Shitf595 dynamic device count

### PR DESCRIPTION
**Pull request by jziolkowski**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.1.0.241117
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
What if not all your relays are on the 595 ?
Like if you have a display which has an on/off on the same device ?

**Comment by arendst** [comment]
Once I receive my 595 based relay board I will look at the code, haven’t seen it yet, and make it work like the mcp23xxx one with virtual relays.

**Comment by barbudor** [comment]
@arendst Which board have you ordered ?

**Comment by jziolkowski** [comment]
@barbudor https://www.aliexpress.com/item/1005007370916864.html this one

**Comment by jziolkowski** [comment]
> What if not all your relays are on the 595 ? Like if you have a display which has an on/off on the same device ?

That's why I reference devices_present in the condition. Since to my knowledge GPIO-configured relays take precedence over drivers, that should be enough to check if the driver can add more relays (especially that if used together with PCF and MCP which have lower driver number and I assume will bump the devices_present counter before 595 init)

**Comment by jziolkowski** [comment]
>  make it work like the mcp23xxx one with virtual relays.

What do you mean by that? Like a configurable driver, or being able to use only a part of the outputs?

**Comment by arendst** [comment]
As said, I haven’t looked at the driver yet, but it should just add relays like extending normal gpuo relays. Come to think about it I may be misguided by the fact thaat the 595 driver only supports outputs. In that case forget my remarks.

**Comment by Noschvie** [comment]
> https://www.aliexpress.com/item/1005007370916864.html this one

this board uses an ESP8266, is there a board with an ESP32 too? Thanks!

**Comment by jziolkowski** [comment]
> > https://www.aliexpress.com/item/1005007370916864.html this one
> 
> this board uses an ESP8266, is there a board with an ESP32 too? Thanks!

Short answer: no.

I replaced it with an ESP32-C3-12F. But I did that because I need ESP32 with its 16 shutters support.

If you want to only have a ton of relays, you're fine with ESP8266

**Comment by barbudor** [comment]
@Noschvie There are the Dingtian boards
Up to 32 inputs and 32 outputs but they are more expensives
https://www.aliexpress.com/item/1005007002132841.html

There's a Tasmota driver for it

Beware that if you want to flash Tasmota you need to tell them when ordering otherwise they ship with their own firmware and they blow the fuses to prevent reflashing.

**Comment by jziolkowski** [comment]
16 vs 32 relays, tho

**Comment by barbudor** [comment]
8, 16 or 32 relays

**Comment by jziolkowski** [comment]
> 373*123*43mm

wow... almost 40cm.

**Comment by arendst** [comment]
I'll merge this now.

**Pull request merged**
