### PR TITLE
Set color for WebUI

### PR DESCRIPTION
**Pull request by MatzeJoerling**
Hi,

patch to have the ability to change the button and the button hover color.
Commands are:
```
WebButtonColor #ff0000
WebButtonColorHover #ff00ff
```
### todo:
- translation for other languages
- better check if colorcode is really hex rgw value
- allow default color names like red, green, yellow ...??
- updatecheck code is a guess! 

How does it look like?
screenshot 2017-12-21 tasmotacolor

I have not counted thy bytes, but i dont think that this feature grows the binary to much.
any chance to apply this? 

regards M.

### CODE REVIEW

**Comment by eXCepT74** [comment]
Where in code i can change background and text color ? I only found button hover and button background in webserver <style>  but cant find page background and text color. I wanted to make it darker or even black with change main text to white or grey for save my eyes ;).

**Comment by MatzeJoerling** [comment]
this is for Button color only!

you type "WebButtonColor #ff0000" and "WebButtonColorHover #ff00ff" with you prefered colors in the Webconsole .
you also can use mqtt to send it:
mosquitto_pub -h 192.168.0.x -t "cmnd/sonoff4/WebButtonColor" -m "#ff0000"
mosquitto_pub -h 192.168.0.x -t "cmnd/sonoff4/WebButtonColorHover" -m "#00ff00"

The Text color remains black and white also the page background. perhaps in next release.

**Comment by eXCepT74** [comment]
Thats great that i can change color by command. It would be nice to have posibility of change text & BG color before compilation. Default can be as is right now . But with that option everyone can make custom look of his control page. Anyway good job!

**Comment by salopette** [comment]
Can anyone help me when I write in the console nothing happens.
[URL=http://www.directupload.net][IMG]http://fs1.directupload.net/images/180401/e9eu2pyu.jpg[/IMG][/URL]

**Comment by localhost61** [comment]
@salopette
Did you merge the commit to your local build?

**Comment by salopette** [comment]
> https://github.com/localhost61

how do I do that???

**Comment by localhost61** [comment]
@salopette , as a newcomer, still learning, I'm maybe not the best person to  give you instructions.

That said, you have at first to manage to build locally a copy of the Tasmota's main branch [see Upload](https://github.com/arendst/Sonoff-Tasmota/wiki/Upload). When the build completes successfully, and you can flash your Sonoff with it, you are ready for next step.
To merge this branch locally, and manually, you can download the files involved in the modifications, and
replace the ones of the main branch. But it's warmly recommended to first compare original and modified source code in order to enhance chances of a successful build. Because <this> branch may not be uptodate with the main branch.
The <files changed> tab in this page shows you the modifications done on [9 files](https://github.com/arendst/Sonoff-Tasmota/pull/1410/files). It's not huge and should be quite easy to adapt locally.
The best would be to report them by editing your local copies by yourself.

**Comment by ascillato2** [comment]
Thanks for sharing your ideas. By now, This PR is not going to be merged due to be outside the actual scope of Tasmota. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

**Pull request closed without merging**
