### PR TITLE
Fixes to SM2135 code

### PR DESCRIPTION
**Pull request by peteben**
## Description:
Fixes to SM2135 code
Changed CW current to 30 ma for better light output relative to RGB
Modified to always output to every channel (RGB and CW)
Previous version was not turning off RGB channels.
Tested with LE LampUX 907001-US

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
See discussion https://github.com/arendst/Tasmota/issues/6495#issuecomment-549285235 for choosing the actual mA setup(s).
Did you do tests with your changea on several bulbs? Can you provide the data (heating)?

**Comment by arendst** [comment]
Your changes break other lamps using this driver.

I've updated the current driver with additional code to support your lamp. Pls give it a try using the following template:
```
{"NAME":"LE LampUX 907001-US","GPIO":[0,0,0,0,0,0,0,0,4066,0,4032,0,0,0],"FLAG":0,"BASE":18}
```
and report back if it fixes your issue.

**Comment by c-** [comment]
Talk about timing. As a data point, I've been messing with a TYLC5/SM2135EH device (KULED 800lm A19 RGB+CCT 9.5W) for the last couple of days and I've been having the problem with the RGB channels failing to toggle off. That LE LampUX 907001-US template definitely seems to fix it. I still have a bulb open on my workbench if you're interested details.

**Comment by arendst** [comment]
Glad it fixes your issue.

**Comment by peteben** [comment]
Yes, the new code seems to work. I still need to do more testing with the current values, though. Right now, the C and W channels show similar brightness as the RGB when full on. I will do a side by side compare with the native tuya firmware to compare.  It might be necessary to include an option to set the current for different types of lamps.
For example, the bulb I am currently testing has 2 each R,G, B LEDS and 15 each C and W LEDS. I suspect different models will have less or more.

Thanks for integrating this fix.

**Comment by arendst** [comment]
Close as the initial change has been implemented

**Pull request closed without merging**
