### PR TITLE
Make scripter configuration interface localizable

### PR DESCRIPTION
**Pull request by bkmit**
## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by andrethomas** [comment]
I can to some extent understand the localization aspect of this PR.

The creation of the tasmota-script.bin variant I don't understand at all.

**Review by ascillato — CHANGES_REQUESTED** [review]
Making the script user interface able to be translated into other languages I totally agree.

But as there are so many variants of user's setups (the sensors they have, their language, features enabled or not) I don't see adding a new variant for firmware types to solve anything from user's perspective. As scripting is optional (as many other features) it is better to let the user to select the advanced features or sensors they need. The changes in platformio, travis and my_user_config.h are not needed IMHO

Anyway, your work on localization of scripting is totally needed and should be a good thing to be added.

**Comment by bkmit** [comment]
My intent was very  simple - really pass travis CI checks. But none of allready defined environmens link scripter!

**Comment by Jason2866** [comment]
@bkmit Travis is a tool to check. Not the holy gral that has to be statisfied if it makes no sense.
The localization for scripter is missing, if you could change your PR without changing
the files @ascillato already mentioned it would be nice.

**Comment by bkmit** [comment]
Yes, sir, yes! :)

**Review by ascillato — APPROVED** [review]
Thanks a lot for working on this. Very appreciated :+1:

**Comment by andrethomas** [comment]
Thx @bkmit , appreciated :)

**Pull request merged**
