### PR TITLE
Add translation for AS3935

### PR DESCRIPTION
**Pull request by device111**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core Tasmota_core
  - [x] The code change is tested and works on core ESP32
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
Why wasting rare flash space for adding explanations that can easily added and explained in the docu?
If setup is done correct this messages will never appear.

**Comment by device111** [comment]
there are 160 Bytes of Ram and 240 Bytes of Flash. No waste...Pure Info.
But if it's to much, i can close ist...

**Comment by effelle** [comment]
Let's see what @arendst think of it.

**Comment by ascillato2** [comment]
Hi,

As it is now this PR has nothing to do with the title of this PR. This PR is just trying to add translations for AS3935 that it is just moving out strings from the driver to the translations files. That sum zero flash usage and everyone will agree.

Changing the title of this PR to what it is really about.

**Review by ascillato2 — APPROVED** [review]
Add translation for AS3935 is a good idea and adds zero extra flash usage. Thanks.

**Pull request merged**
