### PR TITLE
Tasmota build env with core pre 2.6.x

### PR DESCRIPTION
**Pull request by Jason2866**
Build Tasmota with SDK 2.2.y on pre 2.6.x (freezed on Arduino ESP8266 Master commit 8c37601)
"Stable" alternative to branch Feature/Stage because it is a work in progress and can brake stuff...

## Description:

**Related issue (if applicable):** fixes: mqtt reconnects

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core pre 2.6.x 
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Why is the same source using your pre compile:
```
DATA:    [=====     ]  54.9% (used 44968 bytes from 81920 bytes)
PROGRAM: [=====     ]  48.8% (used 500152 bytes from 1023984 bytes)
Creating BIN file ".pioenvs\sonoff\firmware.bin" using ".pioenvs\sonoff\firmware.elf"
```
different from stage using the same platformio params:
```
DATA:    [======    ]  55.4% (used 45368 bytes from 81920 bytes)
PROGRAM: [=====     ]  48.6% (used 497204 bytes from 1023984 bytes)
Creating BIN file ".pioenvs\sonoff\firmware.bin" using ".pioenvs\sonoff\firmware.elf"
```
I hate it when PROGRAM grows without obvious reason.

**Comment by Jason2866** [comment]
will investigate! Build process should be the same

**Comment by arendst** [comment]
FIXED!!!

Caused by your previous package still in the platformio chain. After removing the package it started downloading your latest package and compile is now equal to stage.

Sorry.

**Comment by Jason2866** [comment]
Yes, i have the same results.
pre compile
image

stage:
image

**Comment by Jason2866** [comment]
Should i add this open PR https://github.com/esp8266/Arduino/pull/6326 to pre 2.6.x and update to latest feature/stage? My experience with is fine. The PR saves 600+ bytes in iram!

**Comment by arendst** [comment]
Yes pls do. We can always roll back.

**Comment by Jason2866** [comment]
Updated core_pre 2.6.x to 
commit https://github.com/esp8266/Arduino/commit/c6bfec900c05a90ffd67bb484faf808205dc2607
with PR https://github.com/esp8266/Arduino/pull/6326

**Pull request merged**
