### PR TITLE
Modbus bridge write

### PR DESCRIPTION
**Pull request by jeroenst**
## Description:

**Related issue (if applicable):** fixes issues in https://github.com/arendst/Tasmota/issues/9586

I have done a lot of work to finish the modbus writing.

I have tested all function codes for the modbus send cmd and the modbustcp connection.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.4.1 **N/A**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

Results of automated testing via ModbusTCP:
```
Testing function code 1
TX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x01 0x00 0x90 0x00 0x16 
RX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x01 0x03 0x00 0x01 0x02    => OK!

Testing function code 2
TX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x02 0x00 0x90 0x00 0x16 
RX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x02 0x03 0x00 0x01 0x02    => OK!

Testing function code 3
TX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x03 0x00 0x90 0x00 0x02 
RX: 0x00 0x01 0x00 0x00 0x00 0x07 0xf7 0x03 0x04 0x00 0x00 0x00 0x01    => OK!

Testing function code 4
TX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x04 0x00 0x90 0x00 0x02 
RX: 0x00 0x01 0x00 0x00 0x00 0x07 0xf7 0x04 0x04 0x00 0x00 0x00 0x01    => OK!

Testing function code 5 ON
TX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x05 0x00 0x90 0xff 0x00 
RX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x05 0x00 0x90 0xff 0x00    => OK!

Testing function code 5 OFF
TX: 0x00 0x01 0x00 0x00 0x00 0x06 0xff 0x05 0x00 0x90 0x00 0x00 
RX: 0x00 0x01 0x00 0x00 0x00 0x06 0xff 0x05 0x00 0x90 0x00 0x00    => OK!

Testing function code 6
TX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x06 0x00 0x90 0x00 0x01 
RX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x06 0x00 0x90 0x00 0x01    => OK!

Testing function code 15
TX: 0x00 0x01 0x00 0x00 0x00 0x09 0xf7 0x10 0x00 0x90 0x00 0x15 0x02 0x06 0xc4 
RX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x10 0x00 0x90 0x00 0x15    => OK!

Testing function code 16
TX: 0x00 0x01 0x00 0x00 0x00 0x09 0xf7 0x10 0x00 0x90 0x00 0x01 0x02 0x06 0xc4 
RX: 0x00 0x01 0x00 0x00 0x00 0x06 0xf7 0x10 0x00 0x90 0x00 0x01    => OK!
```

### CODE REVIEW

**Comment by arendst** [comment]
Thx.

**Comment by jeroenst** [comment]
My pleasure, it was a lot of work, more than I expected.

**Comment by henfri** [comment]
Hello,

thanks for this development!
Does this allow to read Modbus-TCP and write Modbus-RTU (and vice versa)?
Where do I find documentation?

Best regards,
Hendrik

**Comment by Tom-Bom-badil** [comment]
Hi Hendrik,

AFAIK the questioned functionality was part of [another recent project](https://github.com/arendst/Tasmota/issues/9586). Not sure if they finished.

/tom

**Comment by henfri** [comment]
Thanks!

**Comment by jeroenst** [comment]
Code is finished but on beta status. 

Here you can find the documentation:

https://github.com/tasmota/docs/blob/master/docs/Modbus-Bridge.md

**Comment by nikito7** [comment]
This works like TCP_BRIDGE?

Tcp_bridge is RTUoverTCP

**Comment by isaacncz** [comment]
> Code is finished but on beta status.
> 
> Here you can find the documentation:
> 
> https://tasmota.github.io/docs/Modbus-Bridge/

hi, i would like to request for stating the version of Tasmota supported in the documentation

**Pull request merged**
