### PR TITLE
Initial Support Solar Solax X1 Inverters

### PR DESCRIPTION
**Pull request by pablozg**
## Description:

Support for solax X1 solar inverters, getting all readables  values by RS485 port, using a RS485 to TTL board and connected to hardware Serial of ESP8266

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X ] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2 (Working with 2.5.2)
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
I'll merge but there are some actions I need to take:

- No need to use ifdefs in language files; if the define is not used it os not compiled either
- Fixed use of celsius is wrong; need to be changed to tasmota global temperature handling
- Consolidate code to decrease code size considerably

In the end it needs to be tested by you as I do not own the device.

**Comment by pablozg** [comment]
It's ok for me, my programming level is limited and it's a good chance to learn about code optimization. If you need I can send you the rs485 protocol used in solax inverters.

**Comment by arendst** [comment]
Well there wasn't much to gain other than masking the debug messages.

Thx for your contribution

**Comment by pablozg** [comment]
I have tested and is working without issues. By the moment the code only support one inverter at once (I only have one Inverter), but in the future if anyone needs a multi-inverter configuration I can try to make some changes.

Thanks for your continuous work with tasmota.

**Pull request merged**
