### PR TITLE
New feature: 433MHz weather sensor decoding

### PR DESCRIPTION
**Pull request by toastbrot69**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.3.2
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

## Decoding of OOK (on-off-keying) based temperature/humidity sensors from various weather stations sending at 433.92MHz and forwarding them via MQTT.

Just set the pin connected to the receiver to "OOK RX"
 
 Required hardware:
 Tested with:
 

- A Sonoff-RF-Bridge (433MHz) can be used with a minor hardware-patch, no Portisch-Firmware needed.
      Also the "normal" or Portisch features for decoding/sending are unharmed. 
      - Wire a 160...680 Ohm resistor from pin 10 of the EFM8BB1 to any free gpio of the ESP. 
         This might be gpio 4/5 if the USB lines have been cut (R2), or one of the free gpio 12/14 
         pads on the bottom-side. Im using gpio 4.
         See https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-RF-Bridge---Direct-Hack
  
 
- A CC1101 module (attached to a D1 mini) (#define USE_CC1101)
       using the Driver-lib from ELECHOUSE/lSatan
       With this you are not fixed to 433.92MHz, but any the CC1101 is capable, including 868MHz
       (I used a 868MHz module for 433MHz which is no problem since we are only receiving. 
        Maybe the sensitivity is not as good as with a 433MHz module)
       The pins for the CC1101 are fixed:
```      SCK_PIN    = D1 Mini: D5 (GPIO 14)
         MISO_PIN   = D1 Mini: D6 (GPIO 12)
         MOSI_PIN   = D1 Mini: D7 (GPIO 13)
         SS_PIN     = D1 Mini: D8 (GPIO 15)
         GDO0       = any free gpio ("OOK RX")
```
 
 Not tested, but should work with any 433MHz receiver providing a "carrier" signal
 
 Commands: 

- sensor100 debug 0..3 0: no debug output
                                     1: pulse-duration output for protocol reverse-engineering
                                     2: output from the various OOK decoders
                                     3: 1+2   

- #if USE_CC1101:
   sensor100 freq xxx.yyy    set CC1101 to xxx.yyy MHz
 
 Implemented decoder:

 1. WT450H (temp, hum, batt)
 2. LaCrosse TX3 (temp, hum)
 3. Infactory (Pearl) (temp, hum, batt)

Have fun

### CODE REVIEW

**Comment by toastbrot69** [comment]
> but did you have a look at current driver xsns_37_rfsensor.ino which already decodes alecto protocol. I think it can easily be extended with your protocols without adding aditional libraries as you do.

Hi,
The additional library is only necessary if you use a CC1101 module, no need for that if a Sonoff-rf-bridge or a receiver like Aurel is used.

**Comment by Jason2866** [comment]
adding the protocols to the RC_Switch library (used be xdrv_17_rcswitch.ino) would be possible too, no new extra driver is needed.
Adding protocols to RfBridge MCU is possible. Doing this no change in code of Tasmota is needed.
See https://github.com/Jason2866/RF-Bridge-EFM8BB1  (added support for DIGOO DG-R8H and Pool thermometer)
Adding the C1101 hardware for a use case which are 2 altenatives already there

**Comment by arendst** [comment]
As the groundwork already has been laid in sensor driver ``xsns_37_rfsensor.ino`` I suggest you focus on adding the devices to this driver and forget about the C1101 hardware as there are already alternatives like the sonoff bridge (with or wothout your hardware change) and the use of an Atmel RF receiver (like I use for both 434MHz and 868MHz weather sensors)

**Comment by toastbrot69** [comment]
Ok, but as it seems at first glance, both pulse-receivers in xdrv_17 and the rc_switch library cant handle NRZ signals like the WT450H?!

**Pull request closed without merging**
