### PR TITLE
EXS dimmer support

### PR DESCRIPTION
**Pull request by RoadRunnr**
## Description:

Add support for the EX-Store WiFi Dimmer v4.

https://ex-store.de/2-Kanal-RS232-WiFi-WLan-Dimmer-Modul-V4-fuer-Unterputzmontage-230V-3A

**Related issue:**  #5856

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2, 2.5.2, and pre-2.6
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by RoadRunnr** [comment]
rebased onto latest dev branch changes

**Comment by RoadRunnr** [comment]
@arendst what do I have to do for someone to have a look at this PR? I had to rebase it twice already because changes to the development branch caused conflicts...

Is there something fundamentally wrong with this PR?

**Comment by arendst** [comment]
Pls change name "EXS MCU reset" to "EXS reset" as it doesn't look well in drop down box.

**Comment by Jason2866** [comment]
I will buy this device if merged😀

**Comment by arendst** [comment]
Leave it be. I'll merge using local changes.

Hold on.

**Comment by arendst** [comment]
Done.

**Comment by gerrylenz** [comment]
Hi,

`#define D_SENSOR_EXS_MCU_RESET "EXS MCU Reset"`
It's not "Reset" it means enable. Is Pin13 not LOW the mcu set all channels to 0 (Gate & Dimm) and don't accept commands.
Better define as
`#define D_SENSOR_EXS_MCU_ENABLE "EXS MCU enable"`

optional for tasmota
**delete**
`
#define D_CMND_EXS_GATE "ExsGate"
#define D_CMND_EXS_GATES "ExsGates"
`
Tasmota dosn't support 2 Buttons for same On/Off function.
The firmware in MCU can switch Gates as 0 or 1 or Dimm as 0 or 1. Both function is different. Command "GATE" switched 0 or full. "DIMM" activate a dimm loop. Is GATE set to 1, no dimm function available.

change in xdrv_30_exdimmer.ino
**delete**
```
static inline void ExsSetChannelV10(uint8_t channel, const uint8_t *buffer)
{
  Exs.dimmer.channel[channel].on = buffer[0];
  Exs.dimmer.channel[channel].dimm = buffer[1];
  Exs.dimmer.channel[channel].bright_tbl = 0;
}

static inline void ExsSetChannel(uint8_t channel, const uint8_t *buffer)
{
  Exs.dimmer.channel[channel].on = buffer[0];
  Exs.dimmer.channel[channel].dimm = buffer[1];
  Exs.dimmer.channel[channel].bright_tbl = buffer[2];
}
```

**change**
```
void ExsPacketProcess(void)
{
  uint8_t len = Exs.buffer[1];
  uint8_t cmd = Exs.buffer[2];

  switch (cmd)
  {
  case EXS_GET_VALUES:
      /*
         format firmware 2.1
         0. byte  = startMarker
         1. byte  =  0. crc of bytes 2(CMD) - 11(GATE_LOCK)
         2. byte  =  1. len_Of_Payload
         3. byte  =  2. CMD
         4. byte  =  3. MAJOR
         5. byte  =  4. MINOR
         6. byte  =  5. GATE1_ON
         7. byte  =  6. GATE1_DIMM
         8. byte  =  7. GATE1.BRIGHT
         9. byte  =  8. GATE2_ON
        10. byte  =  9. GATE2_DIMM
        11. byte  = 10. GATE2.BRIGHT
        12. byte  = 11. GATE_LOCK
        13. byte  = '\0'
      */
    if (len > 9)
    {
      Exs.dimmer.version_major = Exs.buffer[3];
      Exs.dimmer.version_minor = Exs.buffer[4];

      Exs.dimmer.channel[0].on = Exs.buffer[5];
      Exs.dimmer.channel[0].dimm = Exs.buffer[6];
      Exs.dimmer.channel[0].bright_tbl = Exs.buffer[7];
      
      Exs.dimmer.channel[1].on = Exs.buffer[8];
      Exs.dimmer.channel[1].dimm = Exs.buffer[9];
      Exs.dimmer.channel[1].bright_tbl = Exs.buffer[10];

      Exs.dimmer.gate_lock = Exs.buffer[11];
    }
    else
      /*
         format firmware 1.0
         0. byte  = startMarker
         1. byte  =  0. crc of bytes 2(CMD) - 9(GATE_LOCK)
         2. byte  =  1. len_Of_Payload
         3. byte  =  2. CMD
         4. byte  =  3. GATE1_ON
         5. byte  =  4. GATE1_DIMM
         6. byte  =  5. GATE1.BRIGHT
         7. byte  =  6. GATE2_ON
         8. byte  =  7. GATE2_DIMM
         9. byte  =  8. GATE2.BRIGHT
        10. byte  =  9. GATE_LOCK
        11. byte  = '\0'
    */
    {
      Exs.dimmer.version_major = 1;
      Exs.dimmer.version_minor = 0;
      Exs.dimmer.channel[0].on = Exs.buffer[3] - 48;
      Exs.dimmer.channel[0].dimm = Exs.buffer[4] - 48;
      Exs.dimmer.channel[0].bright_tbl = Exs.buffer[5] - 48;
      
      Exs.dimmer.channel[1].on = Exs.buffer[6] - 48;
      Exs.dimmer.channel[1].dimm = Exs.buffer[7] - 48;
      Exs.dimmer.channel[1].bright_tbl = Exs.buffer[8] - 48;

      Exs.dimmer.gate_lock = Exs.buffer[9] - 48;
    }

    ExsDebugState();
    ExsSyncState();
    ExsDebugState();
    break;
  default:
    break;
  }
}
```

Thanks RoadRunnr fo your work!

**Comment by gerrylenz** [comment]
Little changes
For Exs.dimmer.channel[0].on use same buffer as Exs.dimmer.channel[0].dimm
```
    if (len > 9)
    {
      Exs.dimmer.version_major = Exs.buffer[3];
      Exs.dimmer.version_minor = Exs.buffer[4];

      //Exs.dimmer.channel[0].on = Exs.buffer[5];
      Exs.dimmer.channel[0].on = Exs.buffer[6];
      Exs.dimmer.channel[0].dimm = Exs.buffer[6];
      Exs.dimmer.channel[0].bright_tbl = Exs.buffer[7];
      
      //Exs.dimmer.channel[1].on = Exs.buffer[8];
      Exs.dimmer.channel[1].on = Exs.buffer[9];
      Exs.dimmer.channel[1].dimm = Exs.buffer[9];
      Exs.dimmer.channel[1].bright_tbl = Exs.buffer[10];

      Exs.dimmer.gate_lock = Exs.buffer[11];
    }
    else
      /*
         format firmware 1.0
         0. byte  = startMarker
         1. byte  =  0. crc of bytes 2(CMD) - 9(GATE_LOCK)
         2. byte  =  1. len_Of_Payload
         3. byte  =  2. CMD
         4. byte  =  3. GATE1_ON
         5. byte  =  4. GATE1_DIMM
         6. byte  =  5. GATE1.BRIGHT
         7. byte  =  6. GATE2_ON
         8. byte  =  7. GATE2_DIMM
         9. byte  =  8. GATE2.BRIGHT
        10. byte  =  9. GATE_LOCK
        11. byte  = '\0'
    */
    {
      Exs.dimmer.version_major = 1;
      Exs.dimmer.version_minor = 0;
      
      //Exs.dimmer.channel[0].on = Exs.buffer[3] - 48;
      Exs.dimmer.channel[0].on = Exs.buffer[4] - 48;
      Exs.dimmer.channel[0].dimm = Exs.buffer[4] - 48;
      Exs.dimmer.channel[0].bright_tbl = Exs.buffer[5] - 48;
      
      //Exs.dimmer.channel[1].on = Exs.buffer[6] - 48;
      Exs.dimmer.channel[1].on = Exs.buffer[7] - 48;
      Exs.dimmer.channel[1].dimm = Exs.buffer[7] - 48;
      Exs.dimmer.channel[1].bright_tbl = Exs.buffer[8] - 48;

      Exs.dimmer.gate_lock = Exs.buffer[9] - 48;
    }

```

**Comment by Jason2866** [comment]
@gerrylenz  Thx, for supporting a 3rd party firmware for your dimmer!
For me Tasmota was THE reason to buy your dimmer :-)

**Comment by arendst** [comment]
No need. I'm already updating the EXS driver.

**Comment by arendst** [comment]
Done. Happy testing.

**Pull request closed without merging**
