### PR TITLE
Fix %timerN% rule variables for SunRise/Sunset timers

### PR DESCRIPTION
**Pull request by cybermaus**
Enhance %timerN% rule variables to also work for timers with SunRise/SunSet configuration

## Description:

The %timerN% variables added by #14619 only work with hard-scheduled timers. For sunrise/sunset, it is incorrectly interpreting the offset time as real time. This fix corrects that.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.5
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

## Use case

It allows for a very nice paired-timer setup that takes "what if sunrise before on" and "what if sunset after off" into account.
As well as recalculate correct time of day on/off state after power cycle.

While it does require some static rules, it allows to set the desired times using the UI, for causal use by less savvy family members. 

```
# Program the schedule timers in UI with your desired times
# Odd timers 1,3 interpreted by the rules as ON, even timers 2,4 are OFF
# Example times:
#       Timer1 ON  at 06h00   (unless if past timer 2)
#       Timer2 OFF at SunUp   (always)
#       Timer3 ON  at SunDown (unless if past timer 4)
#       Timer4 OFF at 23h00   (always)
# Note, this fails if SunDown past midnight, hence of SunDown <06h00 then SunDown=SunDown+24h00
# Further rules will then calculate the "unless if" part and switch accordingly

Timers 1
Timer1 {"Enable":1,"Mode":0,"Time":"06:00","Window":0,"Days":"1111111","Repeat":1,"Output":2,"Action":3}
Timer2 {"Enable":1,"Mode":1,"Time":"00:00","Window":0,"Days":"1111111","Repeat":1,"Output":2,"Action":3}
Timer3 {"Enable":1,"Mode":2,"Time":"00:00","Window":0,"Days":"1111111","Repeat":1,"Output":2,"Action":3}
Timer4 {"Enable":1,"Mode":0,"Time":"23:00","Window":0,"Days":"1111111","Repeat":1,"Output":2,"Action":3}

Rule2
ON System#Init DO backlog Power1 0; Power1 0 ENDON
ON Time#Initialized DO Backlog var1 0; event checktime=%time% ENDON
ON Clock#Timer DO Backlog var1 0; event checktime=%time% ENDON
ON event#checktime>=%timer1% DO var1 1 ENDON
ON event#checktime>=%timer2% DO var1 0 ENDON
ON event#checktime>=%timer3% DO var1 1 ENDON
ON event#checktime>=%timer4% DO var1 0 ENDON
ON event#checktime DO Power1 %var1% ENDON
Rule2 1
```

### CODE REVIEW

**Comment by cybermaus** [comment]
Oh? I was still modding it with your suggested change. Took a bit of time because I wanted to test on actual device too (even though trivial change)  Does that mean I do not need to commit that change anymore?

**Comment by arendst** [comment]
Yep. Sorry. Thx. All done.

**Comment by barbudor** [comment]
I don't understand
Wasn't this already addressed by my https://github.com/arendst/Tasmota/pull/15230 ?

**Comment by cybermaus** [comment]
Well, during my testing, I did not get any sensible values. And I was not aware of that issue #15230

Reading the code for that issue, it also looks as if (as per title) it does address negative values (it modulates it back it within bounds). And it does seem to add the correct SunMinutes(). 

But it does not interpret the 720 minutes offset that the .time has when it is a sunrise/sunset value, so that would explain why I would not get any sensible values.

**Comment by barbudor** [comment]
ok, it was 6 months ago but I remember spending quite some time to find a good way to handle the way time was coded
thanks

**Comment by cybermaus** [comment]
Well, I do not want to go and upset anyone, but while utterly unaware of your code, I am quite sure I did not get good values before. I will do some more testing, With both the pre and post version

**Comment by barbudor** [comment]
not upset, just surprised as I thought it was well tested 😄

**Comment by barbudor** [comment]
Your changes are in a different part of the rules. Still don't get the difference between those 2 sections

It looks like the code you introduces is very related to the same that I added in `xdrv_09_timer:TimerGetTimeOfDay()`
There is probably some optimization to do here re-using that function to avoid doing the same calculation in 2 different locations.

**Comment by cybermaus** [comment]
Right now, I am on something else. But when I checked earlier, an important difference was that in your code, there was no mention whatsoever of the 720 minutes offset that the .time value has when it is a sun value. Instead, it just wraps around at 0 and 1440. 

I need to check better, but while this may under some circumstanced yield the same (as 720 is mid between) I think it is not always so. But as stated, busy on somewhere else now, will check better later.

**Comment by cybermaus** [comment]
Ok, @barbudor, I have to apologise. Your code works.  Your testing was correct.

_Maybe not relevant, but why did I miss it during testing ... Originally I was on 11.0.0.3, where your code was not in yet. I checked sources, found why I had the issue. Next I did in fact (as per requirement & good practice) upgraded and checked against the latest version, but as the source did not change, I "knew" what I was going to find, and in retrospect I must have retested sloppily. Classic, almost textbook, example of confirmation bias. Sorry._

However....

There is one aspect of your code that is not in line with my use case. And arguable even breaks pre-existing functionality. 
You correct negative numbers, and calculate the correct time. Ok. But you also prevent times higher then 24h00 (1440).

This is relevant as I use these devices up Sweden. Where the sun sets very late. Past midnight. Sometimes not at all 
Your code converts very late (24h45) to very early (00h45). Which makes ">=" comparing very difficult (see use case all way above)

Also, strictly speaking this breaks the already present "permanent daytime" provision from #9543 (admittedly also made by me, but already a while ago). As you can see permanent day is expressed as 2047, which now is shifted to a valid sunset time of 10h07. There was a functional reason why permanent day was shifted to a high number, so >= would never be true.

So I (respectfully, as you are a appreciated contributor, and I am nobody) would argue the code should allow for sunset late night, rather then shifting it to early morning.
At the very least the "permanent daytime" value should be retained, and not converted to 10h07

**Comment by barbudor** [comment]
Once again, there was no critism in my comment (sorry if the shortness appeared as aggressive) and your contributions are as valuable as mine. Even more as they address very specific case where you have experience and I don't.
I was more wondering why my change was not good enough and you gave a perfectly valid explanation and I thank you for that.
I still don't understand yet why the variable replacement is performed in 2 places and why I missed the location where you did your changes (again mainly wondering why my PR was not good enough, nothing to do with yours). I need to dig a little further.

If I undersyand you well, my `xdrv_09_timer:TimerGetTimeOfDay()` is buggy and should be fixed.
May be it would be great that you fox it so that it can be used in both parts of the code and avoid dupplicating thoses calculation ?
What do you think ?
Thanks again

**Comment by cybermaus** [comment]
It should definitely be de-duplicated. And I have no problem taking that on me, given the whole suntime timer thing is important to me.  But I need to study it all a bit better to see how this locations work together.

**Comment by barbudor** [comment]
You can go ahead with the PR and I think it can all go in the same PR

**Pull request merged**
