### PR TITLE
Language Unit Translate

### PR DESCRIPTION
**Pull request by Theosakamg**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core ESP8266 V.2.7.0
  - [] The code change is tested and works on core ESP32 V.1.12.0
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Theosakamg** [comment]
_CI error not link to modification_

```
Error: Got an unrecognized status code '403' when downloaded https://github.com/tasmota/Arduino/releases/download/2.7.0/esp8266-2.7.0.zip
##[error]Process completed with exit code 1.
```

**Comment by arendst** [comment]
It IS related to your change:

```
In file included from tasmota/i18n.h:621:0,
                 from /home/runner/work/Tasmota/Tasmota/tasmota/tasmota.ino:43:
/home/runner/work/Tasmota/Tasmota/tasmota/support.ino: In function 'char TempUnit()':
tasmota/language/en_GB.h:693:24: error: invalid conversion from 'const char*' to 'char' [-fpermissive]
 #define D_UNIT_CELSIUS "C"
                        ^
/home/runner/work/Tasmota/Tasmota/tasmota/support.ino:624:71: note: in expansion of macro 'D_UNIT_CELSIUS'
   return (Settings.flag.temperature_conversion) ? D_UNIT_FAHRENHEIT : D_UNIT_CELSIUS;
                                                                       ^
```
I will need to fix this.

**Comment by kugelkopf123** [comment]
Its the same for de-DE.

**Comment by arendst** [comment]
It should be fixed already.

**Comment by Theosakamg** [comment]
My apologies poorly tested on the 2nd commit...

**Pull request merged**
