### PR TITLE
Added support for LG wall hvac

### PR DESCRIPTION
**Pull request by evzone**
Hi,

Great work so far! I would like to contribute to this extraordinairy project.

I have added a new function in irremote to support LG wall HVAC systems. The function has been tested with a real LG A/C I own and it works ok. The function uses sendLG from irsend library.

evzone

### CODE REVIEW

**Comment by evzone** [comment]
Sorry for reverting my commits but some checks were failed.
Last commit is the good one.

**Comment by ascillato** [comment]
Hi,

Thanks a lot for sharing your ideas, but it is not likely that this PR got merged soon due to now it is being worked the send and receive raw IR codes in order to support a wider range of IR devices. The esp8266 has not enough flash space to have support for all possible protocols. That is why the issue https://github.com/arendst/Sonoff-Tasmota/issues/2116 is open to be worked on.

**Comment by ascillato** [comment]
Anyway, until the #2116 is finished, this PR can be useful for some users.

**Comment by ascillato2** [comment]
Hi,

Thanks a lot for sharing your ideas, this PR can be useful for some users until #2116 is finished to send and receive raw IR codes in order to support a wider range of IR devices. The esp8266 has not enough flash space to have support for all possible protocols. That is why the issue #2116 is open to be worked on.

Anyway, until the #2116 is finished, this PR can be useful for some users. 

Please address the requested changes. IRHVAC is an optional feature in order to reduce flash and RAM. If an user want to use this, can enable it and compile Tasmota and disable the features that are not needed.

**Comment by pablogventura** [comment]
This is not working using tasmota-ir.bin v8.1 Is it a bug?

**Comment by s-hadinger** [comment]
Tasmota-ir now uses IRremoteESP8266 library for all HVAC. Please see here the supported HVACs: https://github.com/crankyoldgit/IRremoteESP8266/blob/master/SupportedProtocols.md

Complete documentation here: https://tasmota.github.io/docs/#/Tasmota-IR

**Comment by pablogventura** [comment]
Thanks for your response!

My LG air conditioner remote (AKB74395308) is supported, but when I try to send the command http://sonoff/cm?cmnd=IRhvac {"Vendor":"LG","Power":1} Tasmota says:

"Wrong Vendor (COOLIX|DAIKIN|KELVINATOR|MITSUBISHI_AC|GREE|ARGO|TROTEC|TOSHIBA_AC|FUJITSU_AC|MIDEA|HAIER_AC|HITACHI_AC|HAIER_AC_YRW02|WHIRLPOOL_AC|SAMSUNG_AC|ELECTRA_AC|PANASONIC_AC|DAIKIN2|VESTEL_AC|TECO|TCL112AC|MITSUBISHI_HEAVY_88|MITSUBISHI_HEAVY_152|DAIKIN216|SHARP_AC|GOODWEATHER|DAIKIN160|NEOCLIMA|DAIKIN176|DAIKIN128|AMCOR|DAIKIN152|MITSUBISHI136|MITSUBISHI112|HITACHI_AC424)"

**Comment by pablogventura** [comment]
I confirmed that LG HVAC is not supported in IRremoteESP8266. Sorry for the confusion. They are working on that. Thanks you!

**Comment by pablogventura** [comment]
https://github.com/crankyoldgit/IRremoteESP8266/issues/1008
Now IRremoteESP8266 has support for Lg!

How should I use it from Tasmota?

**Comment by s-hadinger** [comment]
It's available in the latest Tasmota-IR firmware.

**Comment by pablogventura** [comment]
Is it available in latest release?

**Pull request merged**
