### PR TITLE
Master

### PR DESCRIPTION
**Pull request by gerrylenz**
## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x ] The pull request is done against the latest dev branch
  - [ x] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR.
  - [ x] The code change is tested and works on core pre-2.6
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [ x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

**Changes:**
_sonoff.ino_
2 x
`if (EXS_RELAY == my_module_type) {`

to

`if ((EXS_RELAY == my_module_type) || (EXS_Blackline == my_module_type)) {`

_Add in sonoff_template.h_

```
enum SupportedModules {
...
      EXS_RELAY,
->  EXS_Blackline,
      WION,
...
```

```
const uint8_t kModuleNiceList[] PROGMEM = {
...
      EXS_RELAY,
->  EXS_Blackline,
     SUPLA1,
...
```

```
const mytmplt kModules[MAXMODULE] PROGMEM = {
...
 { "EXS Relay(s)",    // EXS_RELAY - ES-Store Latching relay(s) (ESP8266)
...
 },
  { "EXS Blackline",   // EXS_Blackline - ES-Store Latching relay(s) (ESP8266)
                       // https://ex-store.de/2-Kanal-WiFi-WLan-Relay-V5-Blackline-fuer-Unterputzmontage
     GPIO_USER,        // GPIO00 V5.0 Module Pin 4
     0,                // GPIO01 UART0_TXD
     GPIO_USER,        // GPIO02 V5.0 Module Pin 3
     0,                // GPIO03 UART0_RXD
     GPIO_USER,        // GPIO04 V5.0 Module Pin 2
     GPIO_USER,        // GPIO05 V5.0 Module Pin 1
                       // GPIO06 (SD_CLK   Flash)
                       // GPIO07 (SD_DATA0 Flash QIO/DIO/DOUT)
                       // GPIO08 (SD_DATA1 Flash QIO/DIO/DOUT)
     0,                // GPIO09 (SD_DATA2 Flash QIO or ESP8285)
     0,                // GPIO10 (SD_DATA3 Flash QIO or ESP8285)
                       // GPIO11 (SD_CMD   Flash)
     GPIO_REL1,        // GPIO12 Relay1 ( 1 = Off)
     GPIO_REL2,        // GPIO13 Relay1 ( 1 = On)
     GPIO_REL3_INV,    // GPIO14 V5.0 GPIO_REL3_INV Relay2 ( 1 = Off)
     GPIO_LEDLNK,      // GPIO15 V5.0 LED1 - Link and Power status
     GPIO_REL4_INV,    // GPIO16 V5.0 GPIO_REL4_INV Relay2 ( 1 = On)
     0
  },
...
```

### CODE REVIEW

**Comment by arendst** [comment]
Thx Gerry but alas the PR is wrong and what is more, there is no need to add this to the code. Just make a template based on the current EXS Relay and you're set to go.

See wiki regarding (online) templates.

**Comment by gerrylenz** [comment]
> See wiki regarding (online) templates.
I see. It's only for usability. With this changes the user can direct select.

Another future: send IPAddress with MQTT stat. 

_add in i18n.h_
#define D_JSON_IPADDRESS "IPAddress"

_change in sonoff.ino_
void MqttShowState(void)
...
  ResponseAppend_P(PSTR(",\"" D_JSON_WIFI "\":{\"" D_JSON_AP "\":%d,\"" D_JSON_SSID "\":\"%s\",\"" D_JSON_BSSID "\":\"%s\",\"" D_JSON_CHANNEL "\":%d,\"" D_JSON_IPADDRESS "\":%s,\"" D_JSON_RSSI "\":%d,\"" D_JSON_LINK_COUNT "\":%d,\"" D_JSON_DOWNTIME "\":\"%s\"}}"),
    Settings.sta_active +1, Settings.sta_ssid[Settings.sta_active], WiFi.BSSIDstr().c_str(), WiFi.channel(), WiFi.localIP().toString().c_str(), WifiGetRssiAsQuality(WiFi.RSSI()), WifiLinkCount(), WifiDowntime().c_str());
...
Better check which ip has modul without look in router.

**Comment by andrethomas** [comment]
> I see. It's only for usability. With this changes the user can direct select.

And without this change, there is more free space for other features :)

**Comment by arendst** [comment]
> Another future: send IPAddress with MQTT stat.

Execute command ``status 5`` to get the ipaddress.

**Comment by gerrylenz** [comment]
> And without this change, there is more free space for other features :)

You have right.

**Comment by gerrylenz** [comment]
> Execute command `status 5` to get the ipaddress.

Stats send periodically without any get command.
Thx for your answers.

**Pull request closed without merging**
