### PR TITLE
Added support for DS3502 digital poti

### PR DESCRIPTION
**Pull request by f-reiling**
## Description:

This PR adds support for digital poti DS3502 

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.2.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by f-reiling** [comment]
Please support as workflow CopyDocs fails.

**Comment by arendst** [comment]
I'll do a rewrite for four.

What's the use-case for these devices?

**Comment by arendst** [comment]
I'll do a rewrite for four.

What's the use-case for these devices?

**Comment by arendst** [comment]
Four DS3502 devices have been implemented today.

Use command ``Wiper<x> 0..127`` to control them.

**Pull request closed without merging**
