### PR TITLE
changed driver xsns_11_veml6070.ino

### PR DESCRIPTION
**Pull request by mike2nl**
Added a lot of new calculations
Added suspend and wakeup
Added text defines and one unit W/m2 to the language files
Added version history to the driver
New version is 1.0.0.1, defined inside the driver in history

Not changed:
I have nothing changed for the Domotics texts or values.
Because i don't have it and therefore it is at is was.
Possible arendst can help in that case.

### CODE REVIEW

**Comment by arendst** [comment]
Hi Mike,

I've seen a lot of comms going on about this new driver. That's great!

But... I see you are still using the FUNC_PREP_BEFORE_TELEPERIOD.

With the introduction of rules a sensor is supposed to provide information instantly almost every two seconds. As most sensors are too slow I use a storage for the latest measurment and provide that when the FUNC_JSON_APPEND or FUNC_WEB_APPEND is requested. FUNC_JSON_APPEND is also used by rules.

The current VEML6070 driver uses this approach already.

So could you take some time to re-write the FUNCS like I did for the current VEML6070 driver. I don't think it's a big issue but as you have done a lot of testing while writing the new driver I think you have the right environment to make the change and test it too.

Sorry for the work needed but I think in the end it's worthwhile.

**Comment by mike2nl** [comment]
Hi Theo,
uff now i do not really understand what you mean, sorry.
What precisely i must change that it's done?

I hang a little bit because that style of cdoing is totaly new for me.
Industrial coding in this cases is different and i still learning.

FUNC_PREP_BEFORE_TELEPERIOD i found now...

you wrote:
The current VEML6070 driver uses this approach already.
Mhh, locked right now in your repo and the FUNC_PREP_BEFORE_TELEPERIOD is still there.

Can you hit me, softly, in the right direction, please.

**Comment by arendst** [comment]
Ah you're right! It seems I never released it. Hold on...

**Comment by arendst** [comment]
I'll release your and I will have a look at what I want. Forget your action for the moment.

**Comment by mike2nl** [comment]
Theo,

i think i got it..
driver xsns_25_sdm630.ino
Line 328 ... 349

You mean that?

**Comment by arendst** [comment]
I'll come back to that.

Pls repair some translation files first which are missing translations in several language files like D_UNIT_INCREMENT (nowhere), D_UV_INDEX_1 (only in BG and CZ), D_JSON_UV_POWER

Compilation currently fails.

**Comment by mike2nl** [comment]
Oops will take a look directly

**Comment by mike2nl** [comment]
Hloy shih tzu,
you are right. Jesus never happend to me.
In the english en-GB i have it on my side ;-).
Will change them all and do a PR directly in 15 minutes, SORRY.

**Comment by mike2nl** [comment]
PR added Theo
All languages files and the i18n are cahnged now.
Sorry Thoe, next time i will take more care on that.

**Comment by arendst** [comment]
No hard feelings ;-)

Had to make two additional fixes and just Pushed the functional version online.

**Comment by mike2nl** [comment]
more fixes. Jesus.
Ok i must write me a step by step paper. After my 4th heart attack i have my issues i know.
But i doný give up in any way ;-)
So you may hit me softly every time ;-)

**Pull request merged**
