### PR TITLE
Shutter ha discovery

### PR DESCRIPTION
**Pull request by halfbakery**
## Description:

**Related issue (if applicable):**
Home Assistant shutter autodiscovery support added.

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core ESP8266 V.2.7.1
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by effelle** [comment]
Thanks, was in my queue list.
I need to do some check before merging it because it can break another thing I'm working on with HA devs.

**Comment by halfbakery** [comment]
Is there any news?

**Comment by effelle** [comment]
@halfbakery, 
fear not,  I didn't forget you.
Fact is the Relay/Light void of the Discovery will pass through a deep rewrite to add shutters and fans, mostly to cover the new TuyaMCU functions in the works. 
Those changes will be merged after the new master will be out to have more time to test them. 
I think is more convenient merge your changes after the new code will be ready but if @arendst agree this PR can be merged right now, I'll rework the code later.

**Comment by halfbakery** [comment]
My PR is quite small an mostly non-intrusive (most of the code is protected by the activated shutter support). It would be great if it could be merged before the major rewrite.

**Pull request merged**
