### PR TITLE
Added Huafan Wireless WiFi Smart Socket (Plug)

### PR DESCRIPTION
**Pull request by jwrw**
The HuaFan Wireless WiFi Smart Plug (or Smart Socket) 

Similar functionality to Sonoff SC but within a unit including a plug and socket.

Note that this unit uses a 40MHz crystal - a fix is currently in progress to add this capability to esp8266/Arduino module so this can be changed on the board menu.  Until that is released, a change needs to be made manually in core_esp8266_phy.c

### CODE REVIEW

**Comment by khcnz** [comment]
Checkout what has been done with other esp core files that needed modification (some PWM ones). If you include them in local directory the build process will use these as over-rides - you could posbbily include the core change there?

**Comment by khcnz** [comment]
Also do you have a link to the Huafan device?

**Comment by jwrw** [comment]
The necessary core change for the crystal has been incorporated into the esp8266/Arduino project.  It's in the current main branch and should be in the next release.
I'm doing a 'how to' for modding the socket at it's not as hacker-friendly as the Sonoff devices.  In the meantime see [https://www.banggood.com/Wireless-Mobile-Remote-Control-WiFi-Smart-Socket-UK-Power-Plug-Timing-Switch-p-1129249.html?rmmds=buy](url) and [http://www.huafansmart.com/smart-home/](url)

**Comment by jwrw** [comment]
Hmm... Those links didn't go as expected - try again...
[Socket on Banggood](https://www.banggood.com/Wireless-Mobile-Remote-Control-WiFi-Smart-Socket-UK-Power-Plug-Timing-Switch-p-1129249.html?rmmds=buy) and [HuaFan Home Automation](http://www.huafansmart.com/smart-home/)

**Comment by jwrw** [comment]
Added some wiki notes on modding / flashing this device [HF SmartSocket](https://github.com/arendst/Sonoff-Tasmota/wiki/Preparing-the-HuaFan-Smart-Socket-%5C-Smart-Plug-for-flashing)

**Comment by jwrw** [comment]
Is there anything else needed to get this merged into the base?

**Comment by arendst** [comment]
I will merge in next release

**Comment by ThomDietrich** [comment]
@jwrw I've added your wiki article to the sidebar menu: https://github.com/arendst/Sonoff-Tasmota/wiki/HuaFan-Smart-Socket

**Comment by PeteBa** [comment]
@jwrw A great PR for a handy device. I have added a section into the wiki that provides a "soldering free" hook-up option for programming

**Pull request closed without merging**
