### PR TITLE
Tuya esp32c3

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

As disccussed in https://github.com/arendst/Tasmota/discussions/14086
esp32C3 is a good alternative to esp8266 for Tuya frankesteinization
This PR brings Tuya_MCU to C3

TUYA_MCU is module 2 on C3 vs 54 on ESP8266
So templates need to be manually adapted

Note that it also brings SK03_TUYA in order to minimize code change.
Alternatively, SK03_TUYA could be excluded with #if

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.1.1
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Thx.

I see the issue with modulenames and I don't like it. Shouldn't we enable this tuya thing not also for ESP32 and ESP-S2? If so I will think about a solution for all ESP32 without using the modulename as leading for enabling the code.

**Comment by barbudor** [comment]
I think there is definitely a use case for 32C3 especially in case of brain transplant, less with 32 and 32S2
However if this ease the maintenance of code base then it's surely a good move

**Comment by s-hadinger** [comment]
Agree with Theo, it should be managed with autoconf, i.e. Template and Setoption, instead of a module

**Comment by arendst** [comment]
Refactored differently just now.

**Pull request closed without merging**
