### PR TITLE
Revert changes to add IPV6

### PR DESCRIPTION
**Pull request by Jason2866**
there are several issues rised in Discord after upgrading to latest development version.
Devices are not reachable. Only after activating IPV6 in router this devices are working normal again.
Implementation of IPV6 needs further investigations

## Description:

After OTA devices are not working anymore

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2, 2.5.2, and pre-2.6
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
People complaining about this issue are they using the pre-compiled binaries or are they compiling it themselves? What platformio option do they use?

I cannot understand why this update causes issues and why ipv6 needs to be activated in a router as long as the default platformio compile options are used; ipv6 is not even enabled in the default compile set for pre-2.6.0

**Comment by andrethomas** [comment]
Its a bug introduced by a change in platformio.ini when [core_pre_ipv6] was added and more specifically this

```
platform                  = ${core_pre.platform}
build_flags               = ${core_pre.build_flags}
platform                  = ${core_pre_ipv6.platform}
build_flags               = ${core_pre_ipv6.build_flags}
```

So it is impacting on dev bins pre-2.6

Will advise when fixed.

**Comment by altelch** [comment]
Ok, as I wrote on discord I can understand why it probably causes problems with v4 when v6 is enabled. I don't check for v4 if v6 is ok. This could be changed if one needs dual-stack. But if it's not caused by my code but by enabling pre_2_6 the the revert won't solve this.

**Comment by arendst** [comment]
This should be the correct platformio.ini settings:
```
[core_active]
; Select one core set for platform and build_flags
;platform                  = ${core_2_3_0.platform}
;build_flags               = ${core_2_3_0.build_flags}
;platform                  = ${core_2_4_2.platform}
;build_flags               = ${core_2_4_2.build_flags}
;platform                  = ${core_2_5_2.platform}
;build_flags               = ${core_2_5_2.build_flags}
platform                  = ${core_pre.platform}
build_flags               = ${core_pre.build_flags}
;platform                  = ${core_pre_ipv6.platform}
;build_flags               = ${core_pre_ipv6.build_flags}
;platform                  = ${core_stage.platform}
;build_flags               = ${core_stage.build_flags}
```

**Comment by andrethomas** [comment]
Correct - the build script was searching for `core_pre` to select the core, so now to make it unique it has to search for `core_pre.`

**Comment by Jason2866** [comment]
My 2 cents. The IPv6 implementation is not well tested. It is too early to include and risk peoples devices.

**Comment by andrethomas** [comment]
> My 2 cents. The IPv6 implementation is not well tested. It is too early to include and risk peoples devices.

It is selected by user during self-compile so just wait a little so that I can fix the build script because I did not anticipate having another core_pre in platformio.ini

**Comment by Jason2866** [comment]
Closing everyone who enables IPv6 should know what he/she does.

**Comment by andrethomas** [comment]
@altelch I think dual-stack would be preferred if you want to continue support for IPv6 - I find it very unlikely that users would be using IPv6 exclusively... perhaps even less likely that someone actually knowingly and willingly using IPv6 on a LAN.

@Jason2866 The issue with pre-2.6 dev bins should be solved now - if you have time please test to confirm.

Why do I feel like I played a part in a Loriet cartoon strip...

**Comment by altelch** [comment]
@andrethomas I'll look into probable issues regarding dual stack usage but my reason to support v6 only is that I really need this use case as I already have several tasmota-devices in my work environment and we plan to roll out more. All our mgmt. and sensor networks are IPv6 only without configured IPv4. In home use I don't really see the need to have dualstack. Mostly we see NATed legacy environments. It's a nice to have that I'm able to run dualstack and access my devices from remote if I own a static v6 prefix but in a private environment I normaly don't have constrains with the number of legacy ip addresses. Outside this scenario it's nice to not burn your legacy addresses on IOT Devices if you don't run a NATed environment. So if the PR will remain in Tasmota we'll start to continue a deeper v6 integration into some missing parts to make v6 more usefull. Currently the only part that will not work with v6 is the emulation part but there the cause is amazon echo not supporting IPv6.

Regarding Loriot cartoon strip:
https://tmpfile.uni-kl.de/feb6de58-40c4-4313-a898-2e25ac8387d6/+inline?

Greetings,
    
             Altelch.

**Comment by andrethomas** [comment]
@altelch Thanks would be appreciated if you can look into it because without dual-stack I'm not sure it will ever be useful to 99% of the users... even those that want to "play" with IPv6 would want and probably need dual-stack support.

Regarding Loriot check this https://www.youtube.com/watch?v=XGzf_ENs0YU (It has English subtitles if you don't understand german)

**Comment by joba-1** [comment]
how about starting with what one contributor currently needs and once that works add dual stack?

> Why do I feel like I played a part in a Loriet cartoon strip...

because life _is_ a Loriot cartoon :)

**Pull request closed without merging**
