### PR TITLE
Light controller code update for dual dimmers.

### PR DESCRIPTION
**Pull request by wvdv2002**
## Description:
The updated light controller from PR #5702 breaks the ability to use light_type LT_SERIAL2. With two dimmers you cannot set the channels individually anymore. So command `channel1 50`  or `channel2 50` does not work anymore.

This is because it it's light_subtype becomes LST_COLDWARM. And the cold/warm light bulb type has some protections against the total brightness being more than 255, as well as not using channels 1 and 2 for the 

This PR addresses these issues. 

I doubt it is the right way in the current light controller designers vision. Maybe @s-hadinger can have a look at this code. 

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by s-hadinger** [comment]
I'll take a look.

**Comment by s-hadinger** [comment]
I don't know this device. You are controlling two independent dimmers? For white lights? Without any change in code, you should be able to control both channels with `Color #FFFF`.

Could you give more details about your configuration and what you want to achieve?

The PR you kindly submitted works for the `Channel` command but will most certainly fail with Alexa control: controlling dimmers will be near impossible, and reports back to Alexa will be wrong. Ideally it should be reported as two distinct lights each with its own channel.

**Comment by s-hadinger** [comment]
Sorry, I see the issue now. Let me think about it.

**Comment by s-hadinger** [comment]
I submitted PR #5951 instead, it is a more generic fix for this bug that impacts Cold/Warm white bulbs as well.

You can close this PR.

Thanks for reporting this nasty bug!

**Comment by wvdv2002** [comment]
Thank you @s-hadinger, your solution is much more elegant as far as I can see. I will test the code when I have the time again.

**Comment by PA3VOS** [comment]
Hi Wouter,

I was informed by Theo Arends that you could possibly help me out. I have my Armtronix Wifi one dimmer, that has implemented in the latest sonoff.bin,  running well in Domoticz. But I also bought the Dual dimmer version. I achieved to change the firmware. But this does not make any sense as dual dimmer is not supported. Are you able to assist?

**Comment by wvdv2002** [comment]
Hello @PA3VOS,

I indeed wrote the code for the armtronix dimmer for the sonoff device (the first version).

There are two ways you can go about this.

## Beta software:
If you flash [this](https://github.com/wvdv2002/Wifi-Two-Dimmer-Board/tree/master/Arduino_Code/Atmega328_two_dimmerV0.5_Dimlib) Arduino sketch to the Atmega328 on the Armtronix:  and use the (still beta) version of my [sonoff fork](https://github.com/wvdv2002/Sonoff-Tasmota/commits/arm-singledimmer), it should work with the dual dimmer as well. As the code is now the same for the single and dual version. The dimmer code has been update to use dimlib which works much better than the original Armtronix dimmer code.



To set one of the two dimmers you need to post "****/cmnd/channel2" on MQTT or "****/cmnd/channel1". with the value of the dimmer.


## Less beta software:
Use [this](https://github.com/wvdv2002/Wifi-Two-Dimmer-Board/tree/master/Arduino_Code/Atmega328_two_dimmerV0.4_Tasmota) code for the Atmega: 
Use the official most recent Sonoff Tasmota software with the Armtronix dimmer enabled and compiled.
There have been some updates to the light controller in the official sonoff repository, I don't know yet if they work with the Armronix dimmer module. For the discussion on this topic:
https://github.com/arendst/Sonoff-Tasmota/pull/5951


## Most guaranteed to work:
Use [this](https://github.com/wvdv2002/Wifi-Two-Dimmer-Board/tree/master/Arduino_Code/Atmega328_two_dimmerV0.4_Tasmota) code for the Atmega: 
Use the [Sonoff code](https://github.com/arendst/Sonoff-Tasmota/tree/e284e78b4d526459a3279f9373313b9afec4c1bb) from just after the Armtronix dimmer module was merged:

**Pull request closed without merging**
