### PR TITLE
Added support for Hiking DDS238-2 ZN/S Energy Meter (Modbus)

### PR DESCRIPTION
**Pull request by matteo-campanella**
## Description:

Added support for Hiking DDS238-2 ZN/S Energy Meter (Modbus)

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
Thx for the work on the driver. Is it still availiable?
http://www.chinaenergymeter.com/1-1-1-sw-single-phase-electricity-meter.html

**Comment by matteo-campanella** [comment]
> Thx for the work on the driver. Is it still availiable?
> http://www.chinaenergymeter.com/1-1-1-sw-single-phase-electricity-meter.html

Yep, got one last month from AliExpress - https://www.aliexpress.com/item/32812065998.html

**Comment by arendst** [comment]
Thx Matteo.

While looking at the code I think it resembles the SDM120 a lot. I'm currently recoding this to incorporate it in the energy driver. 

Pls have a look at file xnrg_08_sdm120.ino and see if you can change your file xsns_55_dds2382.ino into a new file xnrg_09_dds2382.ino.

Doing it this way uses less code as it will use the modbus library already within Tasmota.

**Comment by arendst** [comment]
I'm working on an implementation based on your input. Pls hold on.

**Comment by arendst** [comment]
Implemented. Pls give it a try and let me know it works.

**Comment by matteo-campanella** [comment]
> Thx Matteo.
> 
> While looking at the code I think it resembles the SDM120 a lot. I'm currently recoding this to incorporate it in the energy driver.
> 
> Pls have a look at file xnrg_08_sdm120.ino and see if you can change your file xsns_55_dds2382.ino into a new file xnrg_09_dds2382.ino.
> 
> Doing it this way uses less code as it will use the modbus library already within Tasmota.

Hello Theo, I'm trying to migrate to xnrg and TasmotaModbus, but I am receiving garbled data when configured to rx/tx on GPIO13/15 - maybe some work in progress on TasmotaSerial?

**Comment by arendst** [comment]
Matteo, I just released the xnrg version. Pls give it a try and report back.

**Comment by arendst** [comment]
Pls read my previous responses regarding the already implemented version waiting for you to test.

**Comment by matteo-campanella** [comment]
Theo, sorry for the delay. Tested and working!

**Comment by arendst** [comment]
Thx

**Review by arendst — COMMENTED** [review]
Solved and closed

**Comment by chaveiro** [comment]
@matteo-campanella  wonder if you could also add support natively for the DDS238-2 WIFI version?
See https://github.com/arendst/Tasmota/discussions/11837

**Pull request closed without merging**
