### PR TITLE
Allow to configure GPIO pin for OLED Reset

### PR DESCRIPTION
**Pull request by bkmit**
## Description: This PR update  Adafruit SSD1306 and GFX libraries to latest versions.
This allow to specify runtime configure optional GPIO for OLED reset.
This was tested on Heltec WiFi Kit 8 development board.

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

Working Heltec WiFi Kit 8 Template:
{"NAME":"WiFiKit8","GPIO":[255,255,255,255,6,5,0,0,255,255,255,255,162],"FLAG":0,"BASE":18}

### CODE REVIEW

**Comment by arendst** [comment]
I will first update both libraries.

Then you can provide your PR

**Comment by arendst** [comment]
Ah. I will implement your PR too considering the small changes needed.

Hold on please.

**Comment by bkmit** [comment]
Thank your for interest to this.

**Comment by foxsam21** [comment]
Does this mean that [this](https://www.amazon.com/gp/product/B076JDVRLP/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1) board should work?

**Comment by bkmit** [comment]
> @gemu
> Does this mean that [this](https://www.amazon.com/gp/product/B076JDVRLP/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1) board should work?

Yes, it does. I have tested patch on this same board.

**Pull request closed without merging**
