### PR TITLE
Zigbee move all strings to PMEM

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Reduces memory footpring of ZIgbee by 5.5KB.
I thought initially that string literals inside PROGMEM structures were automatically in PROGMEM too. But it's not the case.

This PR explicitly declares every string literal as PROGMEM, saving 5.5KB of previous RAM. Unfortunately this makes the code less readable.
The macros `ZF()` declares a string literal in PROGMEM, the macro `Z()` uses it in a struct.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core Tasmota_core_stage
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Off the record, is there a way to compile Zigbee WITHOUT Hue Emulation? Currently I get all kinds of compiler errors in xdrv_23_zigbee_3_hue.ino when I disable Hue emulation.

I never used any emulation so this came as a surprise.

**Comment by arendst** [comment]
You may be able to save some more code space by placing the text strings in a PROGMEM constant separated by "|" like the commands PROGMEM string and using an indexed uint8_t Z_status table to be used with function  GetTextIndexed.

A binary dumps now shows the Z_Status table uses 8 bytes per entry as the text string flash address is used instead of an index in the text string.

image

**Comment by s-hadinger** [comment]
Good hint Theo, I will indeed refactor using a more compact structure.

**Comment by s-hadinger** [comment]
@arendst Maybe you could also declare all modules names from `kModules` in `tasmota_template.h` to PROGMEM strings. It may also free up some hundreds of bytes of memory.

**Comment by arendst** [comment]
Thx. I'll experiment.

**Pull request merged**
