### PR TITLE
add support for 4.2 inch epaper display from WeAct Studio (partial up…

### PR DESCRIPTION
**Pull request by timehlers**
02.07.2024

## Description:

Add support for newer epaper display WeAct Studio 4.2" (partial update).

Hi,

I tried to figure out the display.ini requirements for the newer epaper display from AliExpress (WeAct Studio), which does not need any lookup tables anymore for refresh. I did a lot of trial and error but finally got a display.ini working.

Unfortunately this needs some patches also to the uDisplay.cpp code, because:

1. We don't have a ":l", ":L" or ":L\<number\>" section (I set a new ep_mode=3, in case we don't have these sections, but ":f" or ":p").
2. The memory area needs a different setup (uDisplay::SetMemoryArea). For this display we need to swap y-start and y-end, means instead of for example "45,4,00,00,2b,01" we need "45,4,2b,01,00,00".
3. By default the display will omit the first pixel line and place it at the bottom, so we need to reduce the y-position in "uDisplay::SetMemoryPointer" by 1 to fix this.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.7
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.0.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Are the changes fully compatible to the current implementation?

**Comment by timehlers** [comment]
Also, nobody until now should have an epaper section ":f" or ":p", while not having any of these: ":l", ":L" or ":L<number>" sections, because until now no epaper display is supported without lookup tables for refresh -- so nobody should accidentally run now into ep_mode=3 in my opinion.

**Comment by arendst** [comment]
> Also, nobody until now should have an epaper section ":f" or ":p", 

While looking at WS_epaper29_v1_display.ini I see both :f and :p sections so forcing mode 3 as you do doesn't seem the appropriate solution.

**Comment by timehlers** [comment]
I made it a bit more clear now and better programmed, hopefully in the second commit.

**Comment by timehlers** [comment]
Btw, it is this display:

https://a.aliexpress.com/_EwkB0VN

:)

**Pull request merged**
