### PR TITLE
Tuya: DimmerRange Issue

### PR DESCRIPTION
**Pull request by Tortue95**
## Description:

**Related issue:**
https://github.com/arendst/Tasmota/issues/11349#issuecomment-978348187
https://github.com/arendst/Tasmota/issues/11349#issuecomment-978348187

sorry it's my first PR... multiple file was changed for unknown reason ...

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [] Only relevant files were touched (sorry it's my first PR... I push only one file on my 
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.1.1
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
Your PR is broken. Pleas redo it from a clean development base

**Comment by ascillato** [comment]
Hi, your PR has conflicts and can not be merged. Sorry.

Please, re do your PR but just modifying the intended files. Your PR is also modifying Github action files and release notes.

**Comment by Tortue95** [comment]
ok sorry, it's my first PR I will try to do it

**Comment by ascillato** [comment]
Seems that you just want to modify tasmota/xdrv_16_tuyamcu.ino, so the fastest way to do that being sure that the PR will be ok, is going to the file in the repo (by web browser - https://github.com/arendst/Tasmota/blob/development/tasmota/xdrv_16_tuyamcu.ino ) and click on the pencil (edit). There you can just do your modifications and then click on the green button. That will produce a PR using latest codebase and your changes.

**Comment by ascillato2** [comment]
If you need help on anything in particular, please ask.

**Comment by Tortue95** [comment]
ok I will pass trough the web interface for this time :)

**Pull request closed without merging**
