### PR TITLE
Update my_user_config.h

### PR DESCRIPTION
**Pull request by ghostrider85**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest dev branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Nice try. Won't do

**Comment by ghostrider85** [comment]
Hi I wanted to compile the firmware for myself.
haven't understood how it works yet

sorry

Am Fr., 27. Nov. 2020 um 08:41 Uhr schrieb Theo Arends <
notifications@github.com>:

**Comment by ascillato2** [comment]
On the main Tasmota page ( https://github.com/arendst/Tasmota ) you can click on GITPOD and a safe Compiling Environment will pop up for you to edit and compile just for you.

Screenshot_20201127-080624_Chrome~2

After it initialize, you can edit the files you want and in the lower window (called console) you can write `platformio -e tasmota` to start the compilation process. Then in the build_output folder you will have your Bin file.

**Comment by ghostrider85** [comment]
Thank you i have find it

Am Fr., 27. Nov. 2020 um 12:12 Uhr schrieb Adrian Scillato <
notifications@github.com>:

**Pull request closed without merging**
