### PR TITLE
Add support for ORNO WE-517 Modbus Power Meter

### PR DESCRIPTION
**Pull request by maximevince**
## Description:

This PR adds support for the ORNO WE-517 3-phase power meter with modbus.
By connecting a UART <-> RS485 converter to the Serial RX/TX lines, Tasmota can read out the meter.

I used 8E1 as the serial power config. I am not sure if this is support by SoftwareSerial?
It might only work on the hardware serial port now.

Also, I have no ESP32 to test, so only ESP8266 was tested.

**Related issue (if applicable):** No related issue, this is support for a new power meter.

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
CI fail in Taasmota32 sensors `/home/runner/work/Tasmota/Tasmota/tasmota/xnrg_17_ornowe517.ino:183:39: error: 'GPIO_WE517_RX' was not declared in this scope`

**Comment by maximevince** [comment]
> CI fail in Tasmota32 sensors `/home/runner/work/Tasmota/Tasmota/tasmota/xnrg_17_ornowe517.ino:183:39: error: 'GPIO_WE517_RX' was not declared in this scope`
> Working okay if you can not test but compilation has to be successful

Okay thanks, the issue is fixed now. All checks passing.

**Comment by arendst** [comment]
See here https://github.com/arendst/Tasmota/pull/9237#issuecomment-690216553 why on hold

**Comment by arendst** [comment]
Thx. Just merged with needed changes.

**Comment by maximevince** [comment]
Awesome! 👍

**Comment by Bitfriemler22** [comment]
I like the driver very much. The meter is perfect for my use and the driver does everything that is needed, thanks maximevince.
But I found a minor typo in xnrg_17_ornowe517.ino: The address for "Phase 2 volt amps reactive" shall be "0x0028".

**Comment by maximevince** [comment]
> I like the driver very much. The meter is perfect for my use and the driver does everything that is needed, thanks maximevince. But I found a minor typo in xnrg_17_ornowe517.ino: The address for "Phase 2 volt amps reactive" shall be "0x0028".

Thanks for noticing!
I have created an additional pull request with the fix here:
https://github.com/arendst/Tasmota/pull/14841

**Pull request closed without merging**
