### PR TITLE
BLE_MI_HM10: support for Mi Scale v1/v2

### PR DESCRIPTION
**Pull request by mrekin**
## Description:

Added Mi Scale support to HM10 BLE driver. Integration based on ble advetising packets.
Code based on PR#13517 (for MI32) with changes for HM10 driver and fixes.
Tested on ESP8266 + HM10 (latest dev build 10.1.0.1) with MI Body Composition scale v2 (0x181B) with weight and impedance features.
Existing 'WeightRes' command may be used to set weight resolution (default value is 0).

Advertisement format from
https://github.com/wiecosystem/Bluetooth/blob/master/doc/devices/huami.health.scale2.md

Cons:
1. Sometime packets missed (test enviroment is ESP8266+HM10 and 7 BLE devices (3 ATC, 2 LYWSD02 , 1 CGD1 and 1 MISCALEV2 ) - mostly when HM10 scan LYWSD02 devices. Scanning takes ~ 1 min for 2 devices (subscribe - ... -disconnect operations). For most other devices this is not big problem due to periodical transmission, but for scales it is problem. Can it be solved (may be buffer size of something else) - I don't know.
2. Home assistant autodiscovering works, but not all params from json recognized as HASS objects.
3. I can't migrate code to NRF24 driver (but want :) ), not all code clear for me.

This is my first PR to Tasmota and first C++ development since 2005 :) So code review is preferred.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.1.1
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by atifan** [comment]
Hi, that is what i am looking for, but I have an ESP32-CAM board with tasmota-bluetooth firmware flashed.
Will there be an ESP32 firmware with support of Mi Scale?
Thanks

**Comment by mrekin** [comment]
> Hi, that is what i am looking for, but I have an ESP32-CAM board with tasmota-bluetooth firmware flashed. Will there be an ESP32 firmware with support of Mi Scale? Thanks

Hi!
Look at the PR
https://github.com/arendst/Tasmota/pull/13517

**Comment by atifan** [comment]
Hi thank you, i will look  :)

**Comment by dcoder42** [comment]
I have used some of your V2 improvements in my last commit for the ESP32 #13517

has_impedance and impedance_stabilized is actually the same bit. For the ESP32 i have replaced has_impedance with impedance_stabilized. Using feature.impedance was a good idea to differentiate between V1 and V2.

**Comment by mrekin** [comment]
> I have used some of your V2 improvements in my last commit for the ESP32 #13517
> 
> has_impedance and impedance_stabilized is actually the same bit. For the ESP32 i have replaced has_impedance with impedance_stabilized. Using feature.impedance was a good idea to differentiate between V1 and V2.

I'm waiting your last commit to re-use mqtt messages text and "triggering rules" :)

**Comment by mrekin** [comment]
Up. Waiting for #13517

**Comment by mrekin** [comment]
Logic updated according disscussions in #13517 and some bug fixed.
Seems PR ready to commit (no futher development planned). 
New HM10 driver take 17k flash size (9k before MIScale support added).

**Pull request merged**
