### PR TITLE
Support IF in Rules

### PR DESCRIPTION
**Pull request by laurentdong**
Codes are already tested by me but might need more test, especially for very complex scenario.

IF statement need Expression's support that I implemented before.
Be default, Both EXPRESSION and IF support is disabled. In order to enable IF support, please un-comment these lines in my_user_config.h (or put in user_config_override.h):
  #define USE_EXPRESSION                         // Add support for expression evaluation in rules (+3k2 code, +64 bytes mem)
     #define SUPPORT_IF_STATEMENT                 // Add support for IF statement in rules (+4k2 code, -332 bytes mem)

I use backlog to execute commands in IF statement. In order to properly insert commands into backlog, I re-implement backlog with LinkedList. But I still kept the original implementation if IF statement are disabled by un-comment "#define USE_EXPRESSION"

The major features of IF statement are:

- Support IF, ELSEIF, ELSE
- Support not only comparison but also using logical expression as condition
- Support run multiple commands
- Support nested IF statement
- All the commands run by IF statement will go to the BACKLOG!
- No limit for logical operators, parenthesis and nested IF statement. Depends on your RAM!

Form of IF statement:
\<if-statement\> ::=
IF "(" \<logical-expression\> ")" \<statement-list\> {ELSEIF "(" \<logical-expression\> ")" \<statement-list\>} [ELSE \<statement-list\>] ENDIF
\<logical-expression\> :=
\<comparison-expression\> |
(\<comparison-expression\> | \<logical-expression\>) {(AND | OR) \<logical-expression\>} |
"(" \<logical-expression\> ")" {(AND | OR) \<logical expression\>}
\<comparison-expression\> ::=
\<math-expression\> ("=" | "<" | ">" | "|" | "==" | "<=" | ">=" | "!=") \<math-expression\>
\<statement-list\> ::=
\<statement\> {";" \<statement\>}
\<statement\> ::=
\<Sonoff-Tasmota-command\> | \<if-statement\>

In English:
If statement support 3 format:
1. IF (\<condition\>) \<statement-list\> ENDIF
2. IF (\<condition\>) \<statement-list\> ELSE \<statement-list\> ENDIF
3. IF (\<condition\>) \<statement-list\> [ELSEIF (\<condition\>) \<statement-list\> ]* ELSE \<statement-list\> ENDIF

\<condition\> is a logical expression which can be:
1. A comparison expression for example:
   VAR1 >= 10
2. Multiple comparison expression with logical operator "AND" or "OR" between them. "AND" has higher priority than "OR". Fox example:
   UPTIME > 100 AND MEM1 == 1 OR MEM2 == 1
3. Parenthesis can be used to change the priority of logical expression. For example:
   UPTIME > 100 AND (MEM1 == 1 OR MEM2 == 1)

\<statement-list\> can be:
1. A Sonoff-Tasmota command. For example:
   ledpower on
2. A IF statement ("IF .... ENDIF")
3. Multiple Sonoff-Tasmota command or IF statement split with ";". For example:
   Power1 off; Ledpower on; if (mem1 == 0) Var1 Var1+1; mem1==1 endif; Delay 10; POWER1 on
4. Do not need leading with "BACKLOG" for multiple commands.

Examples:
This rule is used to control my pressure pot with a Sonoff S31 . Once it finish cocking, shut off the power immediately.
`rule1 on system#boot do var1 0 endon on energy#power>100 do if (var1!=1) ruletimer1 0;var1 1;endif endon on tele-energy#power<50 do if (var1==1) var1 2;ruletimer1 600;endif endon on rules#timer=1 do backlog var1 0;power off endon`

### CODE REVIEW

**Comment by netpok** [comment]
Based on the extra code space it needs I would say this needs it's own enable define, also I think you forgot to revert a change in [line 440 of my_user_config.h](https://github.com/arendst/Sonoff-Tasmota/pull/5388/commits/48b83f3bda92c222a9b2505f29e0ac1ebce6c3ee#diff-c018ec0aa3c54e561e42b0340f4ed526R440)

**Comment by laurentdong** [comment]
@netpok Yes. I agree to have a separate compile switch for IF statement because some guys might don't need IF but still want to use expression. It will be under USE_EXPRESSION because it depends on expression.
Updated.

**Comment by laurentdong** [comment]
I can solve the conflicts if someone still wants to merge in this feature.

**Comment by meingraham** [comment]
@laurentdong 

I think it's work getting the code to the point where all conflicts are resolved.

The feature can be disabled by default and a user can compile the rules enhancement if they want/need it.

How much memory does this consume?

Mike

**Comment by laurentdong** [comment]
@meingraham 
I merged the code.
This feature added 4.2K code, but it require USE_EXPRESSION which added another 3.2K code.

**Comment by meingraham** [comment]
@laurentdong 

Can you write up what features each #define adds and any explanations that we can add to the wiki. Examples would be good too.

I'm happy to incorporate what you send into the wiki. I just won't be able to get everything that you've added and explain it properly.

Thanks

Mike

**Comment by laurentdong** [comment]
@meingraham 
I updated the description of this pull request to include more information.

**Comment by arendst** [comment]
Laurent can you pls make a new PR? This one has 1107 files changed over time...

**Comment by meingraham** [comment]
@laurentdong 

[Please review](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules:-IF-ELSE-ELSEIF-and-AND-OR-Support)

**Comment by laurentdong** [comment]
@arendst 
OK. I created a new pull request #6386 and going to close this one.

**Pull request closed without merging**
