### PR TITLE
Udisplay

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

universal display driver for most pixel driven displays initial commit

currently 2 sample descriptors for SH1106 and ILI9341

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with core ESP32 V.1.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
What does this do without scripter enabled?

To allow user control over enablement I suggest to use GPIO ``Option A3``. This way the driver should be able to co-exist within the current display arena without taking over any previous or following driver.

**Comment by gemu2015** [comment]
if descriptor is not found within scripter (section >d), 
next the descriptor is checked in filesystem ("dspdesc.txt") 
and last a flash based descriptor may be loaded.

**Comment by s-hadinger** [comment]
I'm working on integrating LVGL graphics engine and I'm interested in a uniform descriptor for displays. I'm using https://github.com/adafruit/Adafruit_LvGL_Glue to be able to use any Adafruit GFX compatible display. I'll check how to use it without scripter via Berry instead.

**Comment by gemu2015** [comment]
this is work in progress. The goal is a uniform display driver that can use most pixel hardware with a single driver.
in all common libraries you have to #define your display and every option. 
i am implementing i2c and SPI (4 wire and 3 wire) interfaces.  since most hardware chips operate in a similar manner it is possible to describe the interface with a simple (text) descriptor.
and even hot swap the driver that way.
i will translate the register settings to descriptors step by step.
ILI9341 and SH1106 are already working.  I have an initial syntax description in the display docs.

**Pull request merged**
