### PR TITLE
Refactor TX2x sensor float outputs

### PR DESCRIPTION
**Pull request by curzon01**
## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Any gain in smaller code footprint?

**Comment by arendst** [comment]
YES! A wopping 28 bytes :-( Pity.

**Comment by arendst** [comment]
I see from the test_ext_printf.cpp file that you could also add the decimal resolution directly in the source string. So a line with ``...:%*_f,...`` can also be written as ``...%1_f,...``. This way the code should be a lot smaller as you use a lot of fixed decimals being 1.

**Comment by arendst** [comment]
Just changed this:
```
    ResponseAppend_P(PSTR(",\"" D_TX2x_NAME "\":{\"" D_JSON_SPEED "\":{\"Act\":%*_f,\"Avg\":%*_f,\"Min\":%*_f,\"Max\":%*_f},\"Dir\":{\"Card\":\"%s\",\"Deg\":%*_f,\"Avg\":%*_f,\"AvgCard\":\"%s\",\"Min\":%*_f,\"Max\":%*_f,\"Range\":%*_f}}"),
      1, &wind_speed_float,
      1, &wind_speed_avg_float,
      1, &wind_speed_min_float,
      1, &wind_speed_max_float,
      wind_direction_cardinal_string,
      1, &wind_direction_float,
      1, &wind_direction_avg_float,
      wind_direction_avg_cardinal_string,
      1, &wind_direction_min_float,
      1, &wind_direction_max_float,
      1, &wind_direction_range_float
    );
```
in to this:
```
    ResponseAppend_P(PSTR(",\"" D_TX2x_NAME "\":{\"" D_JSON_SPEED "\":{\"Act\":%1_f,\"Avg\":%1_f,\"Min\":%1_f,\"Max\":%1_f},\"Dir\":{\"Card\":\"%s\",\"Deg\":%1_f,\"Avg\":%1_f,\"AvgCard\":\"%s\",\"Min\":%1_f,\"Max\":%1_f,\"Range\":%1_f}}"),
      &wind_speed_float,
      &wind_speed_avg_float,
      &wind_speed_min_float,
      &wind_speed_max_float,
      wind_direction_cardinal_string,
      &wind_direction_float,
      &wind_direction_avg_float,
      wind_direction_avg_cardinal_string,
      &wind_direction_min_float,
      &wind_direction_max_float,
      &wind_direction_range_float
    );
```
Saving 32 bytes!!

**Comment by s-hadinger** [comment]
> I see from the test_ext_printf.cpp file that you could also add the decimal resolution directly in the source string. So a line with `...:%*_f,...` can also be written as `...%1_f,...`. This way the code should be a lot smaller as you use a lot of fixed decimals being 1.

Correct, I forgot to mention it in the doc.

**Comment by curzon01** [comment]
I'd made test with the neopool driver replacing dtostrfd using test_ext_printf and it save a lot more, doesn't know why it's here only less bytes (but better than nothing...)

**Pull request merged**
