### PR TITLE
Add Joywell 5ch power strip

### PR DESCRIPTION
**Pull request by fnordsh**
Add support for Joywell 5ch power strip.
See: https://www.amazon.de/Steckdosenleiste-Steckdose-App-Steuerung-Bedienung-Joywell/dp/B079C1HPSK

### CODE REVIEW

**Comment by gertmenke** [comment]
Just to clarify: The article description suggests this thing has 4 channels, but in fact there are 5 relays, one for each socket and one for the included usb power supply.

**Comment by Jason2866** [comment]
Could you post some photos? Where are Rx, Tx, GPIO 0, Gnd?
How to disassemble? Something "special" to know?
THX!

**Comment by gertmenke** [comment]
I've posted some details in the sonoff-users group a while ago:
https://groups.google.com/forum/#!topic/sonoffusers/edE3DMJccs8

But I'll try and add some more details and/or better photos here when I get back home this afternoon/evening.

**Comment by gertmenke** [comment]
Okay, here are more details:

It's helpful to have a triangle-screwdriver:
dsc_0424a
These are the same screws we all love from the Teckin/Blitzwolf sockets.
You *can* use a flat or tri-wing screwdriver, if you are careful, but I'd recommend getting a matching bit, as they are not expensive.

The plastic hooks are easily loosened; I like to use a guitar pick, but a flat screwdriver works just as well.

dsc_0282
On the left is the USB power supply, on the right is the control board.

dsc_0291
Remove the plastic clip that holds the mains cable in place.
The control board is held by 3 Phillips screws.

dsc_0292

Here's the documentation for the TYWE2S module:
https://fccid.io/2ANDL-TYWE2S/User-Manual/Users-Manual-3596121

As far as I can see, GPIO0 can only be reached via a test point on the back, so you'll need to desolder the module.

dsc_0300a

After flashing Tasmota (and preferably making sure that it connects to your WLAN correctly), solder the module back in. When putting the back cover back on, make sure the socket contacts are still in the correct place. (When closed, the back cover holds them in place.)

Well, that's it!

I really like these power strips; even though flashing the firmware is a bit of work at first, it's still faster than flashing 4 or 5 single sockets, and they have the best switchable-sockets-per-euro ratio that I've found so far. Also, they look good on my workbench. :-)

If you have any further questions, just ask!

**Comment by Jason2866** [comment]
Thank you for your detailed how to!
Just my 2 cents, the build quality / design is not the best...

**Comment by gertmenke** [comment]
@Jason2866 
>  Just my 2 cents, the build quality / design is not the best...

I agree, it looks a bit cheap, and the button feels a bit fragile.
But I'm sufficiently confident that it won't burn my house down. :-)

**Comment by gertmenke** [comment]
@Jason2866 
Out of curiosity: What are your main concerns, and how would you improve it?
I think I'd have added an air gap between the mains and the 3V parts of the control board, and the socket contacts could probably be fixated better. But at least they've included a fuse.

**Comment by Jason2866** [comment]
The things you mentioned. Low Voltage to Ac voltage "spaces" wiring and cable management.
Finally soldered connections in power strip, that isnt the best idea. After VDE this isnt allowed....
Better is crimpend or Punktgeschweißt (i dont know the english word)
The Power rails if the got warm maybe get deformed and this makes bad contact 
and than it got hotter....

**Comment by gertmenke** [comment]
The power strip has indeed only the CE symbol, no VDE. (I think the latter is not mandatory in the EU, but it's still interesting to know.)

**Comment by gertmenke** [comment]
It'd be interesting to know about other available options. There are some other power strips on Amazon that look like they're probably ESP8266-based, but this is the only one with 4 sockets that I know of.

**Comment by gertmenke** [comment]
You're probably right about the lottery thing. In my opinion, the original Sonoff S20 have a much better internal design than some of the "no-name" clones, or the Teckin/Blitzwolf ones, for example. (But the latter have power measurement and look at least okay-ish to me.)

**Comment by Jason2866** [comment]
Yes, i have original! Sonoffs too. Build quality is for China good.
I bougt a few days ago a gosund powermeter socket. It is not as bad...
But i never would connect or switch devices which needs much current unattended for a longer time.

**Comment by gertmenke** [comment]
Hi, just to make sure I'm not doin anything wrong here: Is there any kind of protocol I should adhere to, to get my PR merged? Or should I just wait more patiently? :slightly_smiling_face:

**Comment by ascillato** [comment]
Please, be patient :+1:

**Comment by gertmenke** [comment]
Okay! :slightly_smiling_face:

**Comment by arendst** [comment]
Why are you so eager to add this device to Tasmota?
 
The proposed changes can be implemented by using the Generic device easily...

**Comment by gertmenke** [comment]
Of course that's possible - which is true for most of the over 40 devices already in there, I suppose.

It just would be nice not having to look up the correct settings for 7 different GPIOs every time I set up one of these devices. In fact, I do have this patch in my custom builds, but every time you add a device upstream, I get conflicting device id numbers, which can lead to problems...

One time I had to reflash a power strip because the ids changed and the device would not boot properly with the new settings (the same id now being used to indicate another device). Maybe it expected some sensor that was not present? I don't know. It just wouldn't connect to my WLAN any more and I couldn't make it go into setup mode either. Since these things need to be soldered apart for flashing (see above) that was rather annoying.

Now, these are by no means unsolvable problems, but it would still be nice if I wouldn't need to worry about it any more. And, I imagine, others would also benefit from the added convenience of not having to figure out the GPIO settings themselves (or at least not having to google them every time).

I take it you are reluctant to merge this because you don't want to clutter the list of devices too much?

**Comment by arendst** [comment]
It's your last sentence and the fact how many people are using these devices.

Feel free to initiate a poll to find out how many users are using what device.

**Comment by gertmenke** [comment]
I see. Thank you for the feedback.

**Comment by ascillato2** [comment]
Thanks for sharing your ideas. By now, This PR is not going to be merged in order to mantain the device list in the firmware as short as possible. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

**Comment by fnordsh** [comment]
This is actually the same device as the "MANZUKO smart power strip" which was merged in #4590 on Dec. 11, 2018. I'm not sure what made you change your mind, but happy to see it got integrated after all.

**Pull request closed without merging**
