### PR TITLE
Berry preliminary support for OneWire

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Preliminary support for OneWire. This maps the `OneWire`C++ class.

Requires either `#define USE_ONEWIRE` or `#define USE_DS18x20`

Example (random commands since I don't have a device):
```
ow = OneWire(20)   #- GPIO 20 -#
ow.reset()
ow.search()
ow.write(64)
ow.write(bytes('40'))
ow.depower()
```

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.1.0.7.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by TomsTek** [comment]
I have tested the Berry support for OneWire with an DS18b20 temperature sensor. Signals on bus are checked with an Oscilloscope. All tested commands work fine.

open OneWire-instance
```
ow = OneWire(14)            # init onewire on Pin 14
```

search device commands
```
ow.reset_search()           # reset found devices
ow.search()                 # search devices
```

transfer data commands
```
ow.reset()                              # send reset pulse, return true if presense received
ow.skip()                               # send skip command, to address all devices on bus
ow.select(bytes('28FF1908A1150377'))    # select specific device on bus
ow.write(68)                            # write (one byte) decimal value 68
ow.write(bytes('28'))                   # write (one byte) hexadecimal value 0x28
ow.write(bytes('28'), 1)                # write (one byte) hexadecimal value 0x28, drive data-line active high after sending data
ow.write(bytes('28'), 0)                # write (one byte) hexadecimal value 0x28, do not drive data-line active high after sending data
ow.depower()                            # reset drive data-line high after sending

ow.read()                   # read one byte
```

**Comment by s-hadinger** [comment]
Thanks for reporting

**Comment by TomsTek** [comment]
Read and write more bytes would improve the functionality of this great implementation.

### wite one or more bytes (detect data length similar as in ow.select()-function)
```
ow.write(68)                    # one byte, power false
ow.write(bytes('2b'))           # tree bytes, power false
ow.write(bytes('15b8c7'))       # tree bytes, power false
ow.write(bytes('15b8c7'), 1)    # tree bytes, power true
```
set power true (if selected) only after last byte

### read more bytes
```
ow.read()    # one byte
ow.read(1)   # one byte
ow.read(5)   # five bytes
```

An other idea is to implement an .read_bytes() and .write_bytes() funktion. But i think the variant above is more elegant.

**Comment by s-hadinger** [comment]
Right, but I believe that the remaining functions can be implemented in Berry on top of the existing ones. Just tell me if you need some help

**Pull request merged**
