### PR TITLE
AP MODE: Added Button to Configuration

### LINKED ISSUE #7306: Restore Configuration on first boot.
**Have you looked for this feature in other issues and in the docs?**  

yes

**Is your feature request related to a problem? Please describe.**  

I can't fast deploy/restore configuration if reset. Resetting the configuration has become very easy.

**Describe the solution you'd like**  

Add "Restore Configuration" on first boot menu.

**Describe alternatives you've considered**  

I don't know. Do recovery in two steps? Not user friendly.

**Additional context**  

It became extremely important because of the default reset after 3 power cycles. 
You may reset  besauce of poor AC/DC. For example, I added 4 relay to Sonoff 4ch,
switch on 8 relays and got reset configuration after 2-5 minuts.

**(Please, remember to close the issue when the problem has been addressed)**  

Of course.

### PR DESCRIPTION
**Pull request by ascillato**
## Description:

Added easy access to all configurations while on AP mode. This helps when the user wants to restore a previously saved configuration, config MQTT, set fixed IP by commands, etc, etc, making the initial setup faster.

**Related issue (if applicable):** fixes #7306, #2219 and #2333

BEFORE and AFTER this PR:

image

The configuration button goes to the standard configuration MENU of Tasmota, where the user can reset the actual configuration, restore a previously saved configuration, config MQTT, etc. On the Configuration MENU, if you click in MAIN MENU, it returns to the main AP menu showed in the picture above. The same goes to the console. Fixed IP and other settings can be defined by commands in the console.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by meingraham** [comment]
Console button :100: :100: :100: :100:

**Comment by arendst** [comment]
What happens if the user selects configuration then mqtt configuration then save? The wifi credentials are still empty. The mqtt save will trigger a restart. The Ap might not come up again. 

Makes this a better initial config experience?

I think you do one step too many. Config restore is fine but providing individual config pages with their save buttons will make initial config a hell.

**Comment by Jason2866** [comment]
Mhh, is there a easy way (not much code) to check if wiifi setting is done?
I agree wifi has to be set first, everything else can be corrected (if done wrong) 
without "the chance" to brick the device.
Having all the configuration options gives the possibility to set up the device with "one stop"
No more searching for IP address the device has got from DHCP to do the config in the needed second step with the actual way it is done now.

**Comment by ascillato** [comment]
I agree. Too many fixes at once.

Let's simplify.

By now, just add the Restore button asked on #7306 

Closing this PR in favour of #7329

**Pull request closed without merging**
