### PR TITLE
keep timer loop when console is scrolled up

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

Related to the Discord discussion here : https://discord.com/channels/479389167382691863/490244847568158751/813790856577286194

When web console is scrolled up to look at past log entries, the console is no more refreshed to avoid the annoying automatic scroll-down. Unfortunately, when the console is scrolled back to the last line, the log entries are no more refreshed.
This is because the timeout-loop that was used for the refresh was not relaunched.

This PR maintain a timeout-loop even if the log is scrolled up in order to restart refreshes as soon as the log is scrolled down to the last line.

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
tagging @emgecgn

**Comment by jeroenst** [comment]
Ah, this is the issue I experience when I scroll up. 
Isn't it possible to add new entries to the end of the log without scrolling down to the latest message when user has scrolled up? And when the user scrolls down again the log message are followed again?

**Comment by barbudor** [comment]
@jeroenst with the PR, as soon as the window is scrolled back to the bottom, the log will be updated with all missing lines (given you didn't stayed up longer than the log trail capacity)
So no logs will be losts

**Comment by arendst** [comment]
Thx.

The issue was introduced after implementation of the 20secs timeout from the BLE coder.

**Pull request merged**
