### PR TITLE
MS5837 console calibration options and code cleanup

### PR DESCRIPTION
**Pull request by vtHydroponics**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.8
  - [X] The code change is tested and works with Tasmota core ESP32 V.3.1.0.241030
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by vtHydroponics** [comment]
A question for the MS5837 calibration via the console... I need a value to be persistently stored for the pressure offset to be retained between resets. Automatic recalibration of the pressure offset would not be possible due to the requirement of both sensors to be at the same elevation for calibration. Thank you.

**Comment by arendst** [comment]
What's the size of the value (uint8_t, uint16_t, uint32_t, int) - keep it as small as possible?

**Comment by vtHydroponics** [comment]
the size of the value is a 4 byte float

**Comment by arendst** [comment]
Use variable `Settings->ms5837_pressure_offset`

**Pull request merged**
