### PR TITLE
Rename pio folder to pio-tools solve linux build errors

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

When vscode is ran from the Tasmota folder in Linux, build fails with message :
```Executing task: pio run <
    The terminal process failed to launch: Path to shell executable "pio" is not a file of a symlink.```
Renaming pio folder into pio-tools solve the problem.

Note: the problem can still occur if the user have a pio folder in his PATH...


Fix implemented following @Jason2866 directives following problems reported by uyser tbretz on Discord

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [X] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
@arendst , Although I made the change in http-uploader.py (and setup board's IP in platformio.ini), it runs something but doesn't OTA :
```Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Uploading .pio/build/tasmota/firmware.bin
21:53:18 [DEBUG]: Options: {'esp_ip': '192.168.168.199', 'host_ip': '0.0.0.0', 'esp_port': 8266, 'host_port': 15146, 'auth': '', 'image': '.pio/build/tasmota/firmware.bin', 'spiffs': False, 'debug': True, 'progress': True}
21:53:18 [INFO]: Starting on 0.0.0.0:15146
21:53:18 [INFO]: Upload size: 619200
21:53:18 [INFO]: Sending invitation to: 192.168.168.199
21:53:28 [ERROR]: No Answer
*** [upload] Error 1```

**Comment by arendst** [comment]
The goal of that script is to send the binary to my ota webserver. On the server a script is running to zip it and store at a known location. So it's not meant as a direct esp8266 device ota push.

**Comment by eku** [comment]
@barbudor do you have CWD (".") in the PATH?

**Comment by barbudor** [comment]
Hi @eku,
The problem originally occurred with tbretz because he launched `code` from the `Tasmota` folder which had a `pio` subfolder.
As `cwd` included `pio` subfolder, it was enough to create the problem. No need for `. ` to be in PATH.
The problem can still occur if someone has a `pio` subfolder in his PATH, but at least it won't because of Tasmota.

**Comment by eku** [comment]
> The problem originally occurred with tbretz because he launched `code` from the `Tasmota` folder which had a `pio` subfolder.

Then this is probably more a problem of VS-Code. I keep calling ```pio run -t <target>``` and my CWD is the main directory where the subdirectory pio is located. But my shell is so smart and doesn't even try to execute a directory. 

I would rather open an error report in the direction of VS-Code than rename the directory in this project. Just my 2 cents.

**Pull request merged**
