### PR TITLE
Add support for CST816S touch interface

### PR DESCRIPTION
**Pull request by ameeuw**
## Description:

This PR adds the driver for CST816S found in cheap, smartwatch like ESP32C3 "2424S012" boards ([Aliexress Search Link](https://de.aliexpress.com/w/wholesale-2424S012.html)). Touch works and gesture recognition works. 

Functionality is tested with the named model in `[env:tasmota32c3]` with `-DFIRMWARE_LVGL` and `-DUSE_CST816S`.

Code compiles for `[env:tasmota-display]` with `-DUSE_CST816S` and runs, but is untested for functionality on esp8266. 

I have attached a .autoconf to upload and test - remove the ".zip" extension before (only added due to Github's limitations). A remap `:M,240,0,240,0` is still necessary in the display.ini.

**Related issue (if applicable):** based on discussion #19487

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

[ESP32C3-2424S012.autoconf.zip](https://github.com/arendst/Tasmota/files/13644909/ESP32C3-2424S012.autoconf.zip)

### CODE REVIEW

**Comment by arendst** [comment]
OMG! Did you use a source code formatter? The current format breaks all silent Tasmota conventions. Pls undo the formatting.

Just add your code changes for us to review.

**Comment by ameeuw** [comment]
> OMG! Did you use a source code formatter? The current format breaks all silent Tasmota conventions. Pls undo the formatting.
> 
> Just add your code changes for us to review.

Yes I did 🙈 - Sorry for that - that's why I only submitted as Draft.

Is there a list of formatting rules I can feed into vscode?

**Comment by arendst** [comment]
> Is there a list of formatting rules I can feed into vscode?

No there isn't. But I prefer to use brackets like:
```
  if (test) {

  }
```
instead of 
```
  if (test)
  {

  }
```
Same for functions and every situation brackets are needed.

**Comment by arendst** [comment]
The code fails on ESP8266.

Considering the amount of code overlap between the library and xdrv_55_touch.ino I suggest to skip the library and add the needed functions into xdrv_55_touch.ino. Then also test for ESP8266 before re-submitting PR.

**Comment by ameeuw** [comment]
> The code fails on ESP8266.
> 
> Considering the amount of code overlap between the library and xdrv_55_touch.ino I suggest to skip the library and add the needed functions into xdrv_55_touch.ino. Then also test for ESP8266 before re-submitting PR.

Thank you for your comments - before starting I just want to clarify: You suggest moving the i2c communication and ISR handling into the xdrv_55_touch.ino?

**Comment by arendst** [comment]
Yes.  

Looking at the library I think most of the code is already available in Tasmota. Have a look at Tasmota's I2C support functions in ``support_a_i2c.ino`` and how they are being used by other drivers.

**Comment by ameeuw** [comment]
Thank you for the hints. I have reduced the changes and checked compilation on esp8266. Tested `tasmota-display` on a 8266-12F D1 mini for normal behaviour but can't test with hardware.

**Pull request merged**
