### PR TITLE
Expose motor-commands directly

### PR DESCRIPTION
**Pull request by Leuselator**
Hi all,
now that it's in the world I found the implementation of my A4988 - module to be not good, concerning usability.

I use ioBroker as Backend and the device reports there as expected with a property named "MOTOR" but no reasonable way to pass the commands to it.

Iv'e forked Tasmota again and changed the xdrv_25_A4988_Stepper.ino.

I expose the commands directly and changed the names so they can be found close together in the propertylist.

New CommandNames: 

motorMove 
motorRotate
motorTurn
motorMIS
motorSPR
motorRPM

if you pull it, I instantly would change the wiki.
Cheers Tim

## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Leuselator** [comment]
shall I change the wiki now?

**Comment by arendst** [comment]
Yes please and use names like ``MotorMove`` so Uppercase M with lowercase otor

**Comment by Leuselator** [comment]
oh - then I should change the line

```
const char kA4988Commands[] PROGMEM = "|" //no prefix
  "motorMove|motorRotate|motorTurn|motorMIS|motorSPR|motorRPM";
``` in xdrv_A4988_Stepper.ino and capitalize the "m"'s or can you do this directly?

**Comment by arendst** [comment]
Nope. I already did change it using the prefix Motor. Have a look at the merged code ;-)

**Pull request merged**
