### PR TITLE
Add eMylo EAI-90 support

### PR DESCRIPTION
**Pull request by Al1c3-1337**
Add support for eMylo EAI-90. WB3S Module has to be replaced by ESP-12.  Please see eMyloEAI90.txt.

## Description:

Add support for eMylo EAI-90. WB3S Module has to be replaced by ESP-12.  Please see eMyloEAI90.txt.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with core ESP32 V.1.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by shaap** [comment]
This also seems to apply to the newest ZMAi-90

**Comment by ortegafernando** [comment]
Hi, thanks @shaap 
what is this exactly?  
I have an Emylo EAI-90 with original TYWE3S. Will it work also?

**Comment by shaap** [comment]
Hi,
I don't know, as I only got this version three times via amazon. They
changed the protocol a lot compared to the previously known one. Maybe, you
can test it. If it does not work, please set "weblog 4" and do "TuyaSend8"
and send me the resulting TuyaMCU messages.

Thanks

ortegafernando ***@***.***> schrieb am Sa., 20. März 2021,
10:37:

**Comment by ortegafernando** [comment]
Thanks, TYWE3S also has the new MCU TUYA protocol. I have found information in the well known link:

[https://www.creationfactory.co/2019/12/reverse-engineering-zmai-90-din-rail.html](url)

I will check.

Do you have this problem? (I have no re-check it sinde then, but may be you could check in your emylo). Thanks:

[https://github.com/arendst/Tasmota/issues/10278](url)

**Comment by shaap** [comment]
Hi,
The protocol is different to the one you mentioned. There are apparently
two ways, TuyaMCU protocol is used to exchange thia data.

Also, this problem did not happen to me.
However, i was unable to really utilize the button at all and it looks like
tasmota resets to factory under some circumstances (at the moment unknown
to me).

ortegafernando ***@***.***> schrieb am Sa., 20. März 2021,
22:36:

**Comment by ortegafernando** [comment]
Sorry, I didnt explained well. 

In that web page, in comments, you can read posts like this:

```
My settings:
Backlog SetOption66 1; TuyaMCU 0,17; TuyaMCU 32,18; TuyaMCU 31,19; TuyaMCU 33,20; SetOption59 1

Rule1 on System#Boot do RuleTimer1 5 endon on Rules#Timer=1 do backlog SerialSend5 55aa0001000000; RuleTimer1 5 endon

It works with TuyaMCU(54) config
```

I think it is what you say, about new protocol with MCU and TUYA protocol.

My question is, what do you have find wrong with tasmota firmware to do this pull request?

Thanks.

**Comment by shaap** [comment]
Hi,
For example, the new Protocol uses Type 0 to transmit the realtime data
(voltage, current and power) and uses a different dpId for total power
consumption. It is a hugely different protocol than described in the
comments section on that page.

Regards

ortegafernando ***@***.***> schrieb am So., 21. März 2021,
07:14:

**Comment by ortegafernando** [comment]
So then, this could work with some versions and not with others. Is it risky to be merged?

**Comment by shaap** [comment]
As far as I looked at it, no. It introduces new fnIds and does not
interfere with the existing ones

ortegafernando ***@***.***> schrieb am So., 21. März 2021,
12:54:

**Comment by cmddlm** [comment]
Hi Shaap.
I have eMylo EAI-90. I have replaced WB3S Module by ESP-12 and tasmotized it.
I have used your setup:
Template TuyaMCU(54)
Backlog SetOption66 1; TuyaMCU 11,16; TuyaMCU 36,6; TuyaMCU 37,1; SetOption59 1; SetOption72 1
Rule1 on System#Boot do RuleTimer1 10 endon on Rules#Timer=1 do backlog TuyaSend8; RuleTimer1 10 endon
Rule1 1

I can only make working the switch, but I can't read any value of energy.
If I give to console command TuyaMCU 36,6 or TuyaMCU 37,1 I can read "TuyaMcu Invalid function id=36" or "TuyaMcu Invalid function id=37", I Think because 36 and 37 are note in the correct range of value.
My tasmota version:
Program Version | 9.3.1(sensors)
2021-03-09T16:13:23

Can you help me?

**Comment by shaap** [comment]
Can you send me the complete output of Weblog 4 followed by TuyaSend8 ?

cmddlm ***@***.***> schrieb am Do., 1. Apr. 2021, 16:47:

**Comment by shaap** [comment]
You have to use current development version, as the latest release does not
contain the code needed to make use of that power meter.

Am Do., 1. Apr. 2021 um 16:47 Uhr schrieb cmddlm ***@***.***>:

**Comment by cmddlm** [comment]
Thanks.
I have compiled your firmware and now it works (it was not so easy).

**Comment by chaveiro** [comment]
Could you make a native driver out of this ?
This also applies to Hiking DDS238-2 WIFI without hardware changes.
See https://github.com/arendst/Tasmota/discussions/11837

**Comment by rolsch** [comment]
> Can you send me the complete output of Weblog 4 followed by TuyaSend8 ? cmddlm ***@***.***> schrieb am Do., 1. Apr. 

ZMAi-90 with removed WB3S and replaced with ESP-12.
Firmware: 9.4.0.4 dev

I can't read any value of energy:

`10:24:41.663 CMD: weblog 4
10:24:41.666 SRC: WebConsole from 192.168.111.2
10:24:41.670 CMD: Grp 0, Cmnd 'WEBLOG', Idx 1, Len 1, Data '4'
10:24:41.676 MQT: stat/tasmota_E0B237/RESULT = {"WebLog":4}
10:24:43.405 TYA: Send "55aa001c0008011506060a182b0799"
10:24:49.425 TYA: Send "55aa00000000ff"
10:24:49.437 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
10:24:49.440 TYA: Heartbeat
10:24:49.955 {"TuyaReceived":{"Data":"55AA03070008010200040000000820","Cmnd":7,"CmndData":"0102000400000008","DpType2Id1":8,"1":{"DpId":1,"DpIdType":2,"DpIdData":"00000008"}}}
10:24:49.958 TYA: fnId=11 is set for dpId=1
10:24:49.961 TYA: RX value 8 from dpId 1 
10:24:50.311 HTP: Command
10:24:50.317 SRC: WebCommand from 192.168.0.210
10:24:50.320 CMD: Grp 0, Cmnd 'STATUS', Idx 1, Len 1, Data '8'
10:24:50.639 WIF: Checking connection...
10:24:54.955 {"TuyaReceived":{"Data":"55AA0307000C06000008092E0000000000005A","Cmnd":7,"CmndData":"06000008092E000000000000","DpType0Id6":"0x092E000000000000","6":{"DpId":6,"DpIdType":0,"DpIdData":"092E000000000000"}}}
10:24:54.958 TYA: fnId=0 is set for dpId=6
10:25:00.395 TYA: Send "55aa00000000ff"
10:25:00.408 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
10:25:00.411 TYA: Heartbeat

10:25:01.986 CMD: TuyaSend8
10:25:01.989 SRC: WebConsole from 192.168.111.2
10:25:01.992 CMD: Grp 0, Cmnd 'TUYASEND', Idx 8, Len 0, Data ''
10:25:01.996 TYA: Read MCU state
10:25:02.006 TYA: Send "55aa0001000000"
10:25:02.012 MQT: stat/tasmota_E0B237/RESULT = {"TuyaSend":"Done"}
10:25:02.330 {"TuyaReceived":{"Data":"55AA0301002A7B2270223A226E7A65786571616D3971756C616A6266222C2276223A22312E302E30222C226D223A327D78","Cmnd":1,"CmndData":"7B2270223A226E7A65786571616D3971756C616A6266222C2276223A22312E302E30222C226D223A327D"}}
10:25:02.333 TYA: MCU Product ID: {"p":"nzexeqam9qulajbf","v":"1.0.0","m":2}
10:25:02.343 TYA: Send "55aa0002000001"
10:25:02.355 {"TuyaReceived":{"Data":"55AA0302000004","Cmnd":2}}
10:25:02.358 TYA: RX MCU configuration Mode=0
10:25:02.360 TYA: Read MCU state
10:25:02.369 TYA: Send "55aa0008000007"
10:25:02.403 {"TuyaReceived":{"Data":"55AA03070008010200040000000820","Cmnd":7,"CmndData":"0102000400000008","DpType2Id1":8,"1":{"DpId":1,"DpIdType":2,"DpIdData":"00000008"}}}
10:25:02.406 TYA: fnId=11 is set for dpId=1
10:25:02.408 TYA: RX value 8 from dpId 1 
10:25:02.434 {"TuyaReceived":{"Data":"55AA0307000C06000008092B00000000000057","Cmnd":7,"CmndData":"06000008092B000000000000","DpType0Id6":"0x092B000000000000","6":{"DpId":6,"DpIdType":0,"DpIdData":"092B000000000000"}}}
10:25:02.437 TYA: fnId=0 is set for dpId=6
10:25:02.452 {"TuyaReceived":{"Data":"55AA030700050A050001001E","Cmnd":7,"CmndData":"0A05000100","DpType5Id10":"0x00","10":{"DpId":10,"DpIdType":5,"DpIdData":"00"}}}
10:25:02.455 TYA: fnId=0 is set for dpId=10
10:25:02.470 {"TuyaReceived":{"Data":"55AA030700050C010001001C","Cmnd":7,"CmndData":"0C01000100","DpType1Id12":0,"12":{"DpId":12,"DpIdType":1,"DpIdData":"00"}}}
10:25:02.473 TYA: fnId=0 is set for dpId=12
10:25:02.493 {"TuyaReceived":{"Data":"55AA030700080D0200040000000024","Cmnd":7,"CmndData":"0D02000400000000","DpType2Id13":0,"13":{"DpId":13,"DpIdType":2,"DpIdData":"00000000"}}}
10:25:02.496 TYA: fnId=0 is set for dpId=13
10:25:02.499 TYA: RX value 0 from dpId 13 
10:25:02.511 {"TuyaReceived":{"Data":"55AA03070005100100010121","Cmnd":7,"CmndData":"1001000101","DpType1Id16":1,"16":{"DpId":16,"DpIdType":1,"DpIdData":"01"}}}
10:25:02.514 TYA: fnId=0 is set for dpId=16
10:25:02.546 {"TuyaReceived":{"Data":"55AA030700101100000C0100003C030001080400009619","Cmnd":7,"CmndData":"1100000C0100003C0300010804000096","DpType0Id17":"0x0100003C0300010804000096","17":{"DpId":17,"DpIdType":0,"DpIdData":"0100003C0300010804000096"}}}
10:25:02.550 TYA: fnId=0 is set for dpId=17
10:25:02.581 {"TuyaReceived":{"Data":"55AA030700101203000C31313131313131313131313186","Cmnd":7,"CmndData":"1203000C313131313131313131313131","DpType3Id18":"111111111111","18":{"DpId":18,"DpIdType":3,"DpIdData":"313131313131313131313131","Type3Data":"111111111111"}}}
10:25:02.584 TYA: fnId=32 is set for dpId=18
10:25:05.065 {"TuyaReceived":{"Data":"55AA03070008010200040000000820","Cmnd":7,"CmndData":"0102000400000008","DpType2Id1":8,"1":{"DpId":1,"DpIdType":2,"DpIdData":"00000008"}}}
10:25:05.068 TYA: fnId=11 is set for dpId=1
10:25:05.070 TYA: RX value 8 from dpId 1 
10:25:09.953 {"TuyaReceived":{"Data":"55AA0307000C06000008092D00000000000059","Cmnd":7,"CmndData":"06000008092D000000000000","DpType0Id6":"0x092D000000000000","6":{"DpId":6,"DpIdType":0,"DpIdData":"092D000000000000"}}}
10:25:09.958 TYA: fnId=0 is set for dpId=6
10:25:11.416 TYA: Send "55aa00000000ff"
10:25:11.429 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
10:25:11.432 TYA: Heartbeat
10:25:11.894 WIF: Checking connection...
10:25:20.160 {"TuyaReceived":{"Data":"55AA03070008010200040000000820","Cmnd":7,"CmndData":"0102000400000008","DpType2Id1":8,"1":{"DpId":1,"DpIdType":2,"DpIdData":"00000008"}}}
10:25:20.163 TYA: fnId=11 is set for dpId=1
10:25:20.165 TYA: RX value 8 from dpId 1 
10:25:22.382 TYA: Send "55aa00000000ff"
10:25:22.396 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
10:25:22.399 TYA: Heartbeat
10:25:25.076 {"TuyaReceived":{"Data":"55AA0307000C06000008092600000000000052","Cmnd":7,"CmndData":"060000080926000000000000","DpType0Id6":"0x0926000000000000","6":{"DpId":6,"DpIdType":0,"DpIdData":"0926000000000000"}}}
10:25:25.080 TYA: fnId=0 is set for dpId=6
10:25:32.582 WIF: Checking connection...
10:25:33.399 TYA: Send "55aa00000000ff"
10:25:33.413 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
10:25:33.416 TYA: Heartbeat
10:25:34.956 {"TuyaReceived":{"Data":"55AA03070008010200040000000820","Cmnd":7,"CmndData":"0102000400000008","DpType2Id1":8,"1":{"DpId":1,"DpIdType":2,"DpIdData":"00000008"}}}
10:25:34.959 TYA: fnId=11 is set for dpId=1
10:25:34.961 TYA: RX value 8 from dpId 1 
10:25:38.391 MQT: tele/tasmota_E0B237/STATE = {"Time":"2021-06-06T10:25:38","Uptime":"0T00:01:55","UptimeSec":115,"Vcc":3.544,"Heap":29,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":25,"MqttCount":1,"POWER":"ON","Wifi":{"AP":2,"SSId":"namoro_de_bs_rt","BSSId":"C8:0E:14:5E:62:F7","Channel":13,"Mode":"11n","RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:03"}}
10:25:38.401 MQT: tele/tasmota_E0B237/SENSOR = {"Time":"2021-06-06T10:25:38","ENERGY":{"TotalStartTime":"2020-12-14T00:22:27","Total":84.32868,"Yesterday":0.00000,"Today":0.00000,"Period":0,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0.0,"Current":0.000}}
10:25:40.155 {"TuyaReceived":{"Data":"55AA0307000C06000008092C00000000000058","Cmnd":7,"CmndData":"06000008092C000000000000","DpType0Id6":"0x092C000000000000","6":{"DpId":6,"DpIdType":0,"DpIdData":"092C000000000000"}}}
10:25:40.159 TYA: fnId=0 is set for dpId=6
10:25:43.424 TYA: Send "55aa001c0008011506060a192b079a"
10:25:44.416 TYA: Send "55aa00000000ff"
10:25:44.429 {"TuyaReceived":{"Data":"55AA030000010104","Cmnd":0,"CmndData":"01"}}
10:25:44.432 TYA: Heartbeat`

**Comment by rolsch** [comment]
[ZMAi-90_WB3S_to_ESP-12.txt](https://github.com/arendst/Tasmota/files/6603877/ZMAi-90_WB3S_to_ESP-12.txt)

**Comment by rolsch** [comment]
[ZMAi-90_WB3S_to_ESP-12.txt](https://github.com/arendst/Tasmota/files/6603935/ZMAi-90_WB3S_to_ESP-12.txt)

**Comment by rolsch** [comment]
Ok, found the solution here: [https://templates.blakadder.com/ZMAi-90.html](url)

**Comment by TommasoPino** [comment]
hi, @rolsch the solution you found is no longer available. Could you please clarify the solution or post it again? Thanks

**Comment by barbudor** [comment]
Just go to the template site and use the search to find your device. Here it is listed under ZMAI-90
As explained in the docs....

**Comment by rolsch** [comment]
@TommasoPino 
Copy the plain text as url and don't use the link behind :-)

https://templates.blakadder.com/ZMAi-90.html

ZMAi-90 with ESP01s
Use Modul 54
Backlog SetOption66 1; TuyaMCU 0,17; TuyaMCU 32,18; TuyaMCU 31,19; TuyaMCU 33,20; SetOption59 1
Backlog Rule1 1; Rule1 on System#Boot do RuleTimer1 10 endon on Rules#Timer=1 do backlog SerialSend8; RuleTimer1 10 endon

=> my question here: TuyaMCU 0,17; was is this?

ZMAi-90 with wb32 was replaced with esp12e
Use Modul 54
Backlog SetOption66 1; TuyaMCU 11,16; TuyaMCU 36,6; TuyaMCU 37,1; SetOption59 1; SetOption72 1
Backlog Rule1 1;Rule1 on System#Boot do RuleTimer1 10 endon on Rules#Timer=1 do backlog TuyaSend8; RuleTimer1 10 endon

**Pull request merged**
