### PR TITLE
Improved MQTT connection failure troubleshooting logs

### PR DESCRIPTION
**Pull request by khcnz**
Replacement for previous incorrect PR that had the 4.0.4 commits in it

### CODE REVIEW

**Comment by arendst** [comment]
Will implement in next release

**Comment by khcnz** [comment]
In regards to VCC - good question - potentially the Sonoff SV (Safe voltage) and also wimos that could be powered directly.

**Comment by arendst** [comment]
Well I guess it's a functional feature anyway as it seems to work for all my sonoffs with regards of returning the Vcc. I'll add it to the status 10 / teleperiod message.

**Comment by arendst** [comment]
Implemented in 4.0.5. The Analog port will show up as a sensor in status 10 and teleperiod. The Vcc info will show up in status 11 and teleperiod.

Thnx for the research.

**Comment by khcnz** [comment]
Thanks Theo!

**Pull request closed without merging**
