### PR TITLE
Fix WeMo Emulation

### LINKED ISSUE #1223: Sonoff Basic, v5.9.1 when toggled off turns back on
Have a recently flashed Sonoff Basic. When I toggle the relay off either via the web UI or Alexa, the relay shuts off then turns back on a moment later.  This occurs with MQTT both enabled and disabled.

When Mqtt is enabled:

18:53:59 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
18:53:59 MQT: stat/sonoff/POWER = ON
18:54:00 MQT: stat/sonoff/RESULT = {"POWER":"OFF"} 
18:54:00 MQT: stat/sonoff/POWER = OFF
18:54:02 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
18:54:02 MQT: stat/sonoff/POWER = ON
18:54:05 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
18:54:05 MQT: stat/sonoff/POWER = ON
18:54:09 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
18:54:09 MQT: stat/sonoff/POWER = ON
18:54:12 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
18:54:12 MQT: stat/sonoff/POWER = ON

When Mqtt is disabled:

18:55:59 RSL: RESULT = {"POWER":"ON"}
18:55:59 RSL: POWER = ON
18:56:10 RSL: RESULT = {"POWER":"OFF"}
18:56:10 RSL: POWER = OFF
18:56:14 RSL: RESULT = {"POWER":"ON"}
18:56:14 RSL: POWER = ON
18:56:16 RSL: RESULT = {"POWER":"OFF"}
18:56:16 RSL: POWER = OFF
18:56:17 RSL: RESULT = {"POWER":"ON"}
18:56:17 RSL: POWER = ON

Why is the relay being commanded to turn back on after I turn it off?

### PR DESCRIPTION
**Pull request by reloxx13**
This fixes #1223 #1243 

Echo is Requesting the current state and this is powering on the device.

The Echo is asking for GetBinaryState and includes always BinaryState 1, which powered the device on.

`if (request.indexOf(F("State>1</Binary")) > 0) {`

I added Get and Set XML Response and made a differentiate between GET and SET Binary State.

Also, now the Alexa App shows the current state.

Please!!! Review the code, im new to this language.

TODO: 
I could not find out how to Response with multi channels. i also got only sonoff basics with one channel. this happens in line 352 the hardcoded 1
For SET binary state it also sets all channels on/off. i guess the hardcoded 1 is okay.

I also attach a patch file which can be applied by git for easier review for you.

[fix_wemo_emulation.zip](https://github.com/arendst/Sonoff-Tasmota/files/1557398/fix_wemo_emulation.zip)

PS: Atom is adding a new line in the langauge file, sorry :S

### CODE REVIEW

**Comment by reloxx13** [comment]
i merged set and get xml to one variable to save some bytes now.

**Comment by reloxx13** [comment]
Hey @arendst ,

what do u say to this? I think this is an important feature for many and they r waiting for it.

**Comment by arendst** [comment]
What's wrong with the below change only:
```
  if (request.indexOf(F("SetBinaryState")) > 0) { 
    if (request.indexOf(F("State>1</Binary")) > 0) {
  //    ExecuteCommandPower(1, 1);
      ExecuteCommandPower(devices_present, 1);
    }
    if (request.indexOf(F("State>0</Binary")) > 0) {
  //    ExecuteCommandPower(1, 0);
      ExecuteCommandPower(devices_present, 0);
    }
  }
```
This saves a lot of code space and apparently users never needed the GetBinaryState information.

Further the Wemo emulation always supported only one device. For more devices use the Hue emulation.

**Comment by reloxx13** [comment]
Without GetBinaryState, the alexa app does not recongnize if the modul is on or off, 
resulting in showing it as off (but its on) so u need to press on, device stays on and then u can switch it off.

i would rather suggest to let it in and delete if u r getting out of space.

its your descicion, ill stay with the getbinarystate response on my devices.

---
you cannot use more than one hue bridge in routines at the moment, thats why to use wemo. i tried a few things to fix this, but it seems to be an alexa bug, cuz i read that real devices got the same problem.

**Comment by arendst** [comment]
@reloxx13 could you be so kind to test the latest 5.10.0e version for positive Wemo functionality please.

I do not have access to Alexa so I cannot test it and as many people seem to have problems with it I hope this finally works (again).

**Comment by reloxx13** [comment]
Heya @arendst , 

attention textwall inc :D


i can offer a teamviewer connection if you like.


SHORT VERSION RESULT:
I tried it a few more times but after over 10-20 tries it coud not get found again.
i restarted the sonoff over the web interface and it got found instantly again for a few times.
And again, as longer the device is on, discovering is failing more and more till it does not get found again.


In my personal user_config i disabled all Sensors and MQTT Services since i dont use them.
Also i noticed, that while discovering my 2nd sonoff with 5.10.0c sometimes is showing as "offline" on the alexa web interfacee.
Seems it also got a timing problem while getting the MSEARCH, but much less then the other sonoff with all sensors enabled.
i tried the same with my 2nd sonoff and a longer uptime and it did got re-discovered in 9/10 tries.



LARGE VERSION RESULT:

Hardware: Echo Dot 2G, Version: 597464620
Sonoff Basic 5.10.0.e from 2017_12_28 23:20

No WEMO/Belkin Skill activated in Alexa.

Deleted one Sonoff WEMO EMU over the Alexa Web Interface ( https://alexa.amazon.de )
Removed Static IP in Fritzbox.
Removed Selfopening Ports in Fritzbox from that Sonoff.
Restarted Echo Dot
Restarted Fritzbox

Used Clean before Building (with Atom).
Only changed CFG_HOLDER in user_config.

Flashed over OTA (Web Interface)

After flash and restart, WPS was active.
If WPS is active and almost instant active after restart, its hard to launch the WIFI Manager.
Atleast in germany, wps is not often used, suggestion: use WIFI Manager as Default.

After a few tries pressing the button 4 times to launch the WIFI Manager, the Sonoff WIFI was showing up.

I connected to it and the Web Interface of Sonoff was instantly opening in my open Firefox as new Tab.

I entered the correct WIFI Setting ( SSID and PW only [A-Za-z0-9] ).
The "Device will restart in" timer was on 0 already, but the WIFI was still up.
Seems like the Timer is wrong or their is no restart if im connected to the Sonoff-WIFI.

I hitted save, device restarted now.

In the Fritzbox Interface, it showed up the newly Sonoff with a new IP (sonoff-1348, 192.168.178.201).
Static IP and Selfopening Ports still disabled.

I opened the IP in a new Tab to enable the Wemo Emulation. Device restarting.
Tried on/off switch over the web interface, had no lag, instant responsing.

Back to Alexa, i told her "Alexa, discover new smart home devices".
RESULT: **no devices found**.
Alexa Web Interface: **No devices found**.

Okay, allow "Selfopening Ports" in fritzbox now.
I allowed it and searched again: Sonoff **FOUND**


Now some users said, that HUE gets detected while WEMO gets not detected, ill try this:
Disabled Selfopening Ports again and changing to HUE Emuation.

Deleted teh Wemo Device in the Alexa Web Interface.
Restart Sonoff over Web Interface.

Research with Alexa over Voice:  **Could not find any new devices**
Tried again, no devices found.

Enabled Selfopening Ports again in fritzbox
Restarting the Sonoff Device over Web Interface.
Searching: No device found.
Searching 2 more times: no device found.

```
Sonoff log is flooding with (level 2)
23:57:21 MQT: Attempting connection...
23:57:28 MQT: Connect failed to domus1:1883, rc -2. Retry in 10 sec
23:57:28 UPP: Multicast (re)joined
23:57:38 MQT: Attempting connection...
23:57:45 MQT: Connect failed to domus1:1883, rc -2. Retry in 10 sec
23:57:45 UPP: Multicast (re)joined
23:57:56 MQT: Attempting connection...
23:58:02 MQT: Connect failed to domus1:1883, rc -2. Retry in 10 sec
23:58:02 UPP: Multicast (re)joined
```

Setting log to "4 more debug" and restarting again.
Searching: **HUE Device found.**

Deleted it again from Alexa, searched again and found again.


Result: 
Static IP is irrelevant, but Selfopening Ports HAVE to be ALLOWED.
If HUE is getting detected, WEMO must be discoverable, too.
Its the same logic behind, sending MSEARCH, waiting for response from device.
Something is making the Sonoff ignoring or passing the MSEARCH.


I also noticed a heavy lag before the "00:16:58 UPP: Multicast (re)joined" log entry while spamming the On/Off button in the Alexa App, this could be the reason for "Device does not respond" messages from Voice On/Off.

One time i got this log by switching it on over voice control and a device did not response:

```
**00:19:45 UPP: Multicast disabled**
00:19:45 MQT: Attempting connection...
00:19:51 MQT: Connect failed to domus1:1883, rc -2. Retry in 10 sec
00:19:51 HTP: Hue API (/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1)
00:19:51 HTP: Hue API (/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state)
00:19:51 HTP: Hue POST args ({"on": true})
00:19:51 RSL: stat/sonoff/RESULT = {"POWER":"ON"}
00:19:51 RSL: stat/sonoff/POWER = ON
00:19:52 CFG: Saved to flash at F4, Count 88, Bytes 1648
00:19:52 HTP: Hue API (/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1)
00:19:52 UPP: Multicast (re)joined
00:19:55 HTP: Hue API (/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1)
```


I can remember that i needed a few tries to find the Wemo Device when i first installed one Sonoff, after that i had never Problems with them.
Im also working on a Full HUE Emulation to work with scenes to integrate the Hue Motion Device over the official HUE APP and had to re-discovery the Sonoff a few times without problems.

I also sniffed the network a few days ago while discovering to check if something in the MSEARCH has changed in past weeks but could not find any diferences.


---
After i wrote that, i changed back to WEMO Emu and deleted the Hue Emu in the Alexa Web Interface, now i tried to discover a few times but it did not get discovered.

Logs:
```
00:00:03 DNS: Initialized
00:00:03 HTP: Web server active on sonoff-1348.local with IP address 192.168.178.201
00:00:03 UPP: Multicast (re)joined
00:00:03 HTP: Main Menu
00:00:03 UPP: Multicast disabled
00:00:04 UPP: Multicast (re)joined
00:00:04 APP: (UTC) Thu Dec 28 23:23:02 2017
00:00:04 APP: (DST) Sun Mar 26 02:00:00 2017
00:00:04 APP: (STD) Sun Oct 29 03:00:00 2017
00:23:03 UPP: Multicast disabled
00:23:03 MQT: Attempting connection...
00:23:10 MQT: Connect failed to domus1:1883, rc -2. Retry in 10 sec
00:23:10 UPP: Multicast (re)joined
00:23:21 UPP: Multicast disabled
00:23:21 MQT: Attempting connection...
00:23:27 MQT: Connect failed to domus1:1883, rc -2. Retry in 10 sec
00:23:27 UPP: Multicast (re)joined
00:23:33 WIF: Checking connection...
00:23:33 WIF: Connected
00:23:36 HTP: Console
00:23:38 UPP: Multicast disabled
00:23:38 MQT: Attempting connection...
00:23:44 MQT: Connect failed to domus1:1883, rc -2. Retry in 10 sec
00:23:45 UPP: Multicast (re)joined
```

After a few more times the Wemo Devices showed up again.




Now i disbale MQTT and stay on Belkin Emu. Deleted the Wemo Device and discover again, device instant found.
Try again: not found
Try again: not found
Restarting Device
Try again: not found
Try again: not found
Also no "Wemo basic event" in the logs.
Try again: found

```
00:31:36 HTP: Console
00:31:45 WIF: Checking connection...
00:31:45 WIF: Connected
00:32:05 WIF: Checking connection...
00:32:05 WIF: Connected
00:32:25 WIF: Checking connection...
00:32:25 WIF: Connected
00:32:45 WIF: Checking connection...
00:32:45 WIF: Connected
00:33:05 WIF: Checking connection...
00:33:05 WIF: Connected
00:33:14 UPP: WeMo Response sent to 192.168.178.50:50000
00:33:14 HTP: WeMo setup
00:33:25 WIF: Checking connection...
00:33:25 WIF: Connected
00:33:41 HTP: WeMo basic event
00:33:45 WIF: Checking connection...
00:33:45 WIF: Connected
```


I tried it a few more times but after over 10-20 tries it coud not get found again.
i restarted the sonoff over the web interface and it got found instantly again for a few times.
And again, as longer the device is on, discovering is failing more and more till it does not get found again.

Free memory 25kb (information page).


In my personal user_config i disabled all Sensors and MQTT Services since i dont use them.
Also i noticed, that while discovering my 2nd sonoff with 5.10.0c sometimes is showing as "offline" on the alexa web interfacee.
Seems it also got a timing problem while getting the MSEARCH, but much less then the other sonoff with all sensors enabled.

BR
Nils

**Comment by reloxx13** [comment]
Additional to say, this is not a xml response problem, since the request (MSEARCH) is not even arriving the sonoff (regarding the log entries).

**Comment by arendst** [comment]
THNX!!!

Other users also noticed that disabling MQTT made a better experience and that's why I provide the option on the Other menu.

Part of the problem is the many UDP uPnP messages being thrown at your network. In my case my Routers, Kodi and Sonos keep sending messages at tens a second. All these messages need to be scanned for M-SEARCH by tasmota leading to the situation you encounter too.

The important part for me currently is that at least initially it works so the basic code is fine but the hardware seems to be useless in a busy uPnP environment...

**Comment by Syberteck** [comment]
https://github.com/Syberteck/esp8266-Smart-Plug

**Pull request closed without merging**
