### PR TITLE
Teleinfo, add stats and more checksum controls

### PR DESCRIPTION
**Pull request by hallard**
## Description:

- added errors statistics (require libteleinfo v1.1.5)
- checksum control before sending values

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by hallard** [comment]
sorry @arendst forgot to push one file on previous PR

**Comment by barbudor** [comment]
Hello Charles @hallard 

Looks like there is some issues with lib v1.1.5 and the updated driver
```
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino: In function 'bool ResponseAppendTInfo(char, bool)':
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino:533:71: error: expected primary-expression before ')' token
             if (me->checksum==tinfo.calcChecksum(me->name, me->value))) {
                                                                       ^
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino:585:24: error: 'LOG_LEVEL_WARNING' was not declared in this scope
                 AddLog(LOG_LEVEL_WARNING, PSTR("TIC: bad checksum for %s"), me->name);
                        ^~~~~~~~~~~~~~~~~
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino:585:24: note: suggested alternative: 'LOG_LEVEL_NONE'
                 AddLog(LOG_LEVEL_WARNING, PSTR("TIC: bad checksum for %s"), me->name);
                        ^~~~~~~~~~~~~~~~~
                        LOG_LEVEL_NONE
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino: In function 'bool TInfoCmd()':
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino:912:36: error: 'statsname' was not declared in this scope
                     GetTextIndexed(statsname, MAX_TINFO_COMMAND_NAME, command_code, kTInfo_Commands);
                                    ^~~~~~~~~
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino:912:36: note: suggested alternative: 'stats_name'
                     GetTextIndexed(statsname, MAX_TINFO_COMMAND_NAME, command_code, kTInfo_Commands);
                                    ^~~~~~~~~
                                    stats_name
/tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino:922:35: error: 'class TInfo' has no member named 'clearstats'; did you mean 'clearStats'?
                             tinfo.clearstats();
                                   ^~~~~~~~~~
                                   clearStats
```

**Comment by hallard** [comment]
@barbudor I had an issue yesterday I may have commited the wrong file, I see where the error is, strange that checks did not fired any error, will fix that one in a couple of hours

**Comment by hallard** [comment]
should be fixed with #18058, thanks for reporting

**Pull request merged**
