### PR TITLE
LightFox Dual support

### PR DESCRIPTION
**Pull request by foxel**
Adding support for my open-hardware switch module. 

It's based on sonoff dual architecture with two micros but has some modifications to support RF module.

### CODE REVIEW

**Comment by arendst** [comment]
So in fact it's a sonoff dual and acting as a sonoff dual. So why not select a sonoff dual saving 32 bytes of code and shortening the already way to long device selection list?

**Comment by foxel** [comment]
@arendst that was my initial plan. But as dual has only one physical button thru Serial it's not working for me. 
Currently, the difference is in buttons threating to allow switching the second channel. I'm planning to expand functionality by allowing the user to define which RF channel is mapped to which relay channel (thru Serial also).

**Comment by foxel** [comment]
@arendst i've completed development with all the additional features:
* mapping RF buttons to relay channels
* initiating RF bind process
* initiating RF clear process

**Comment by foxel** [comment]
Hi @arendst . Any update on this?

**Comment by arendst** [comment]
Need more time to evaluate. Are the commands really needed. Can't they be fixed?

**Comment by foxel** [comment]
Hi.

This PR introduces 3 new commands. And they are needed for 2 unique features the module have:
- binding/unbinding RF remotes without taking the module from the wall or ceiling
- map RF remote control buttons to channels individually.

Commands:
- RfClear - triggers RF module clear procedure. After this, no RF remote can control the module
- RfBind - triggers RF module bind procedure. After 3 seconds user should press a button on a remote to bind it to the module. If some module channel matches the button index it will toggle.
- RfButtonMask<x> [mask] - set RF button mask for channel <x>. This assigns a 4-bit button (provided in decimal form) mask for a channel. Each bit of this mask sets whether the channel should toggle if the corresponding remote button is pressed. User can reuse bits for more than one channel to define a button to trigger more than one channel.

Hope this explains the need for these commands.

**Comment by foxel** [comment]
Any update here?

**Comment by ascillato** [comment]
More time needed, please be patient :wink:

**Comment by foxel** [comment]
Hi, @arendst !
I've rebased, recompiled and retested once again. Works fine.
What do you need for this to be merged?

**Comment by foxel** [comment]
Hi, @arendst 

Any update on this?

**Comment by foxel** [comment]
@arendst 
Updated PR again. Flashed into my hardware - works perfectly.

**Comment by ascillato2** [comment]
Thanks for sharing your ideas. By now, This PR is not going to be merged in order to mantain the device list in the firmware as short as possible. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

**Pull request closed without merging**
