### PR TITLE
Add Rule Trigger Comparison Operators for strings

### PR DESCRIPTION
**Pull request by ortegafernando**
Add Rule Trigger Comparison Operators for strings (contains and/or starts and ends with)

## Description:

Explained here: [https://github.com/arendst/Tasmota/discussions/10208](https://github.com/arendst/Tasmota/discussions/10208)

I have created also a PR for docs.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by ortegafernando** [comment]
Hi, could you merge this? Thanks a lot.

**Comment by arendst** [comment]
Merged in some way.

**Comment by ortegafernando** [comment]
Remember PR in wiki

**Comment by barbudor** [comment]
Some additions and fixes in https://github.com/arendst/Tasmota/pull/10779
Docs PR in https://github.com/tasmota/docs/pull/610

**Comment by dusan06** [comment]
Can someone help me! I am trying to use TDM (Tasmota device manager) NODEMCA ESP8266 with 32 pins, when I open the RULES program it cracks. Does anyone have an idea.

**Comment by barbudor** [comment]
Github Issues and Pull Requests are not the right place to ask for help.
Please go to https://github.com/arendst/Tasmota/discussions
Or join the Discord support group :  https://discord.gg/Ks2Kzd4

**Comment by dusan06** [comment]
Thanx

**Pull request closed without merging**
