### PR TITLE
CI for ESP32

### PR DESCRIPTION
**Pull request by Jason2866**
in a different process to see the failures for ESP8266 and ESP32

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core ESP8266 V.2.7.0
  - [ ] The code change is tested and works on core ESP32 V.1.12.0
  - [x] The code change pass CI tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

Tasmota under ESP32 is not compiling. There is an issue with the latest change on gpio assignment.

**Comment by ascillato** [comment]
What about adding the ESP32 CI to the main workflow due to the badges are just showing the main CI and not the result of ESP32 tests

**Comment by Jason2866** [comment]
Maybe adding to badges?

**Comment by ascillato** [comment]
One badge should be enough I think if all tests are in the same CI workflow

**Pull request merged**
