### PR TITLE
Use Tasmota Stage Core 2.7.3.1...

### PR DESCRIPTION
**Pull request by Jason2866**
for Tasmota Stage build. Core is based on (soon released) Arduino ESP core 2.7.3.

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota stage core ESP8266 V.2.7.3.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
There is something fishy...
```
Building in release mode
*** use provided user_config_override.h as planned ***
Compiling C:\Temp\.pioenvs\tasmota\src\StackThunk_light.cpp.o
xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'
Compiling C:\Temp\.pioenvs\tasmota\src\WiFiClientSecureLightBearSSL.cpp.o
Compiling C:\Temp\.pioenvs\tasmota\src\core_esp8266_waveform.cpp.o
*** [C:\Temp\.pioenvs\tasmota\src\StackThunk_light.cpp.o] Error 1
xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'
Compiling C:\Temp\.pioenvs\tasmota\src\core_esp8266_wiring_digital.cpp.o
*** [C:\Temp\.pioenvs\tasmota\src\WiFiClientSecureLightBearSSL.cpp.o] Error 1
xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'
xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'
*** [C:\Temp\.pioenvs\tasmota\src\core_esp8266_waveform.cpp.o] Error 1
*** [C:\Temp\.pioenvs\tasmota\src\core_esp8266_wiring_digital.cpp.o] Error 1
```

**Comment by arendst** [comment]
I guess it needs this:
```
[tasmota_stage]
; *** Esp8266 core for Arduino version Tasmota stage
platform                  = https://github.com/Jason2866/platform-espressif8266/releases/download/2.9.0/platform-espressif8266-2.9.0.tar.gz
platform_packages         = framework-arduinoespressif8266 @ https://github.com/Jason2866/Arduino/releases/download/2.7.3.1/esp8266-2.7.3.1.zip
build_unflags             = ${esp_defaults.build_unflags}
                            -Wswitch-unreachable
build_flags               = ${esp82xx_defaults.build_flags}
                            -Wno-switch-unreachable
```

**Comment by Jason2866** [comment]
No, see #8933 
I have this build flags by default in my config...

**Comment by arendst** [comment]
But I thought 2.7.3 and up were based on GCC 10.1?

**Comment by Jason2866** [comment]
NO. 2.7.3. is the bug fix release for your OTA issue you opened. Based on core 2.7.2 with some minor other changes
The new core using GCC10.1 will be released as core 3.x.x

**Pull request merged**
