### PR TITLE
New venetian blind functionality added for shutters

### PR DESCRIPTION
**Pull request by stefanbode**
## Description:
Venetian blinds have been requested for a long time. Now available for all shutters. Autodiscovery to domoticz must be enhanced in future. HASS seems to be working. Just about the new tilt functionality.

The documentation is already enhanced.
**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ x] The pull request is done against the latest development branch
  - [x ] Only relevant files were touched
  - [x ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x ] The code change is tested and works with Tasmota core ESP32 V.1.0.7.5
  - [x ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Review by ascillato — APPROVED** [review]

**Comment by stefanbode** [comment]
From my point we can push it to dev. The domoticz integration for tilt can be added anytime later if we find someone comfortable with it and help

**Comment by Funkenschuhster** [comment]
I flashed dev. 10.0.3 on a shelly 2.5 and did the calibration. MQTT control via nodered works like a charm. 

But I can't use the wall switches anymore. I can move in one direction once, and when I stop the first time the shutter "locks up".  From now the relais only switches on for a few milliseconds.

Can anybody confirm this?

**Comment by stefanbode** [comment]
Let's discuss this. The idea of the tilt is to get maintained after the movement. Except you reach the endpoints. If you open your Venetian blind with the wall switch and stop it, then after the stop the shutter should go in the opposite direction to set the tilt to the position before start. 

Ok. Does this help? Does it behave diffeeent?

**Comment by stefanbode** [comment]
If you don't have Venetian please try shuttertiltconfig 0 0 0 0 0

**Comment by stefanbode** [comment]
Can you share your shutterbuttonconfig. I will try to reproduce and fix it. A "lock" was not intended

**Comment by Funkenschuhster** [comment]
**About the discussion**
Regarding the software control I have the same idea. Move to desired position, then tilt to last set tilt position automatically. If tilt is to be changed, this can be set on the web interface. And this works very well with the commands ShutterOpen ShutterStop and ShutterClose as far as I tested.
With the wall switches I expect the behavior as with a manual control. The motor only runs when I press the switch. Tilt must be done manually by tapping the switch. Tasmota tracks the position in the background by runtime registration.
If Tilt would also be set automatically with the wall switch, there would be no possibility to set Tilt without a terminal device.

**About the bug**
I made a video of the problem:
https://www.youtube.com/watch?v=slpB9nIuXUM
To reproduce:
1. Shutter locked up or not, it does not matter
2. Shutter is opened by MQTT with topic: cmnd/devicename/ShutterOpen1 payload: "UP"
(Video starts here)
3. Shutter is moved down by hardware switch (input SW1 true)
4. Shutter is stopped by hard
I definitive have venetian.
ware switch (input SW1 false)
5. Shutter is locked up, cannot be moved ether by SW1 or SW2
6. To unlock: Fully open shutter by MQTT command


**Configuration**
Here is my status 0:
```
21:15:16.160 RSL: STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota",""],"Topic":"shutter10","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":0,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
21:15:16.188 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota-minimal.bin","RestartReason":"Software/System restart","Uptime":"0T00:04:21","StartupUTC":"2021-11-23T20:10:55","Sleep":50,"CfgHolder":4617,"BootCount":3,"BCResetTime":"2021-10-29T07:50:28","SaveCount":7,"SaveAddress":"FA000"}}
21:15:16.220 RSL: STATUS2 = {"StatusFWR":{"Version":"10.0.0.3(tasmota)","BuildDateTime":"2021-11-21T14:22:18","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"391/699"}}
21:15:16.239 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["foresureiwonttellyou",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A000000000000","40000080","00006040","00004000"]}}
21:15:16.270 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":616,"Free":384,"Heap":26,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"16301C","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","00000020"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45","Sensors":"1,2,3,4,5,6"}}
21:15:16.298 RSL: STATUS5 = {"StatusNET":{"Hostname":"kueche-ost","IPAddress":"10.0.70.186","Gateway":"10.0.70.1","Subnetmask":"255.255.255.0","DNSServer1":"10.0.70.1","DNSServer2":"0.0.0.0","Mac":"EC:FA:BC:AE:F2:F2","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
21:15:16.321 RSL: STATUS6 = {"StatusMQT":{"MqttHost":"192.168.88.251","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_AEF2F2","MqttUser":"jalousie","MqttCount":0,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
21:15:16.344 RSL: STATUS7 = {"StatusTIM":{"UTC":"2021-11-23T20:15:16","Local":"2021-11-23T21:15:16","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:11","Sunset":"17:01"}}
21:15:16.364 RSL: STATUS10 = {"StatusSNS":{"Time":"2021-11-23T21:15:16","Switch1":"OFF","Switch2":"OFF","ANALOG":{"Temperature":177.2},"Shutter1":{"Position":71,"Direction":0,"Target":71,"Tilt":90},"TempUnit":"C"}}
21:15:16.382 RSL: STATUS11 = {"StatusSTS":{"Time":"2021-11-23T21:15:16","Uptime":"0T00:04:21","UptimeSec":261,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"assaidiwonttell","BSSId":"4A:8F:5A:36:95:D6","Channel":6,"Mode":"11n","RSSI":80,"Signal":-60,"LinkCount":1,"Downtime":"0T00:00:13"}}}
21:15:16.413 RSL: STATUS13 = {"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":420,"Close":410,"50perc":50,"Delay":0,"Opt":"0000","Calib":[300,500,700,900,1000],"Mode":"1"}}}
```

Settings I change for the shutter shelly
```
MQTT
Wifi

Template {"NAME":"Shelly 2.5","GPIO":[320,0,32,0,224,193,0,0,640,192,608,225,3456,4736],"FLAG":0,"BASE":18}
SetOption80 1
ShutterMode 1
ShutterCloseDuration 410
ShutterOpenDuration 420
shuttertiltconfig1 -90 90 40 0 -90
```

**Comment by stefanbode** [comment]
Ok, I am pretty sure you directly drive the relay with the switch and have not defined shutterbuttons. In this case the behavior make sense because if you switch of the relay it means off. You have to assign short press and long press actions to the button. Then it must work. Let me search for the right buttonconfig later.

**Comment by stefanbode** [comment]
https://tasmota.github.io/docs/Blinds-and-Shutters/#button-control describe the use of the buttons quite well. I assume you need for the position:
`ShutterButton1 1 100 50 74 100 1 1 1 1 0`
`ShutterButton1 2 0 50 24 0 1 1 1 1 0 `
Currently, there is no function for the tilt. This is something for the future. I need to check if and how I can add this to the procedure.

**Comment by stefanbode** [comment]
And thanks for the video. There is definitely also a bug in the relay function with the tilt defined. At least it should go up/down in an expected way. I will check this today and submit a fix.

**Comment by stefanbode** [comment]
@Funkenschuhster : your issues should be fixed and the shutter should operate now without any more changes. forget about the shutterbuttons. The tilt position is maintained after stopping the shutter. Currently, I have no idea how to control the tilt with the buttons in the wall.

**Comment by stefanbode** [comment]
My idea for the tilt (no idea how to get this into the code :-) ) if doing short press and changing the tilt-only this is a tilt change. If you doing the press longer than just changing the tilt -> the position is changing. In this case, the tilt gets restored AFTER the movement is stopped. Does this make sense?

**Comment by Funkenschuhster** [comment]
Ok, I will flash and test later.

I have an idea for two buttons. Define one switch for tilt and one for move. And then use a dimmer like behavior on both. Inspired by Eltako EUD12NPN-UC:

1. Press and hold. Motor starts moving in one direction. May it decides to move UP first when at 75% 
2. Release. Motor stops.
3. Press and hold. Motor moves in opposite direction. 
4. Release. Motor stops again.
5. Press and hold. Opposite direction again 
6. ...

One short press toggles between open/close. It's interoperable by long press.

**Comment by stefanbode** [comment]
There is something similar already:
Setup for an "toggle" button: ShutterButton<x> <button> toggle <mqtt>
Single press will toggle shutter, double press will move it to 50%. Be aware that the toggle select direction based on the current position. If the position is between 0..50% the shutter move to 100%. If the position is 51%..100% it moves to 0%. No hold action and no other shutter control by MQTT, <mqtt> is don't care here.

I do not understand in detail how and when it stops in this configuration. Not invented here ... :-)

**Comment by Funkenschuhster** [comment]
I just updated OTA and it should be on binary 20211124 11:17. But nothing changed :/ 

I made another video. You can see the shutter working in MQTT control. 
Then explain how the shutter should work with wall switch. At the end I show, the bug again with comments.

https://www.youtube.com/watch?v=kGdJUNlh-Pk

I also noticed, the tilt is overwritten when the shutter was fully open. You can see at the beginning of the video it tilts to 90°. At 0:50 I set it to 0°. Meanwhile I moved the shutter all up, with ShutterOpen1. When I show you the bug from inside at 2:15 it is sets to 90° again.

**Comment by stefanbode** [comment]
I absolutely agree and was able to reproduce the LOCK because the shutter stayed in tilt mode when operated by the switch and not through MQTT command. After the change, it worked fine for me. Regarding "overwrite tilt". Yes, if you move the shutter to 0% or 100% the tilt changes automatically so there is no more movement if reaching this position. This is intended behavior.

**Comment by stefanbode** [comment]
In the "Info" Page you can see build date and time. If the error persist please weblog 4 and send me the logfiles after the shutter is locked and you try to move it up/down.

**Comment by stefanbode** [comment]
ok another bug found.....

**Comment by stefanbode** [comment]
submitted a new pr. #13786

**Comment by Funkenschuhster** [comment]
Hey, it works much better now. At least the shutter is not locked anymore.
https://youtu.be/bETXKhfc6gg

**New issue #1**
The tilt reset after 100% open is strange. When I start at 100% open and move to e.g. 70%, the tilt preset is always 90% which is neither <openposition> or <closeposition>. It's always the highest value of <min> and <max>
```
shuttertiltconfig1 -90 90 40 0 -90 --> 90
shuttertiltconfig1 90 -90 40 0 -90 --> 90
shuttertiltconfig1 -90 80 40 0 -90 --> 80
shuttertiltconfig1 85 -80 40 0 -80 --> 85
```
Howewer on my raffstore 90° means, the outside surface of my raffstore is facing inside.
I tried to invert <min> <max> but then the `ShutterTilt1` does not work anymore.
`shuttertiltconfig1 90 -90 40 0 90`
May add an extra parameter command or use either <openposition> or <closeposition>

** New issue #2**
I managed to mess up the local control by interrupting the tilt by wall switch.
1. Move by wall switch
2. Stop by wall switch
3. Press and release wall switch randomly while tilting
4. Shutter will move on, even when both switches are off.

**Comment by Funkenschuhster** [comment]
> My idea for the tilt (no idea how to get this into the code :-) ) if doing short press and changing the tilt-only this is a tilt change. If you doing the press longer than just changing the tilt -> the position is changing. In this case, the tilt gets restored AFTER the movement is stopped. Does this make sense?

Yes, definitely. 
I see two approaches to programming.

**No 1**
Couple switch directly to relay and track actual value using calculation like :
```
While Relay is ON {
Tilt actual value = Tilt actual value + Tilt speed of direction of motion * Cycle time.
}
```
I think this is the way to keep the delay at a minimum.

**No 2**
Increase setpoint and proceed as with the ShutterTilt<x> command.
```
While SWx is pressed {
Tilt setpoint = Tilt setpoint + tilt speed of the direction of movement * cycle time
ShutterTilt<x> = Tilt setpoint
}
```
With this method a machine gun circuit can occur when the actual value reaches the setpoint for a short time. The setpoint must therefore lead, which reduces precision.

**Comment by Funkenschuhster** [comment]
Works now.

https://youtu.be/a7SLidQ1Tek

**Comment by stefanbode** [comment]
I really like videos! regarding the preset in the beginning. the idea was that if the shutter move into the end positions it will just stop there and do nothing else. especially no more tilt changes. In your video on the FIRST movement there is a tilt change after the move. This is unexpected and does not look like you expect, but I have an idea where it comes from. My expectation when coming from one of the endpoints is, that there is NO tilt change after the movement. But maybe we also restore the tiltposition that was stored before. In your case: You like 0°. but if you move up/down to the endposition it will be -90 or 90. But after going somewhere into the middle again it is 0° again. I will work on this later.

**Comment by stefanbode** [comment]
Regarding the tiltconfig: keep in und that min must be lower than max. Therefore -90 90 is fine but 90 -90 is always invalid. Maybe a check and reject s required here.

**Comment by Funkenschuhster** [comment]
This is my current setup. It's used in my video. 
 `shuttertiltconfig1 -90 90 40 0 -90`

**Comment by davidk88** [comment]
Hello,

I'm playing with this on nodemcu.

settings: shuttertiltconfig1 -90 90 40 0 90

1. ShutterTilt responds with shutter position value
prev position:
RSL: RESULT = {"Shutter1":{"Position":32,"Direction":0,"Target":32,"Tilt":0}}

CMD: shuttertilt1 close
RESULT = {"ShutterTilt1":32}
RESULT = {"Shutter1":{"Position":32,"Direction":0,"Target":32,"Tilt":90}}

2. if tilt change is small, nothing happens

CMD: shuttertilt1 80
RSL: RESULT = {"Shutter1":{"Position":32,"Direction":0,"Target":32,"Tilt":90}}
RSL: RESULT = {"ShutterTilt1":32}

But it should move here since there are 40 steps for 180 deg range?

Best regards

**Comment by stefanbode** [comment]
yes that the result is wrong and the response to the tilt is the position is known. I have currently no idea how to fix this. Therefore RSL: RESULT = {"ShutterTilt1":32} is definitely wrong because 32 is the position. I know. 

changing tilt from 90->80 with 2sec. Operation time does not work because: 40 Steps == 90 - (-90) = 180°. Each step are 4°. TO start recognize and stop TASMOTA needs at least 0.2sec (4steps). Threrefore the minimal movement in this configuration is 4+4= 16°. There is nothing I can change here.

**Pull request merged**
