### PR TITLE
Add Check for lwIP version

### PR DESCRIPTION
**Pull request by ascillato**
Add Check for lwIP version

### CODE REVIEW

**Comment by reaper7** [comment]
I am using a esp8266 arduino git version, in this case I do not get any error 
because _core_version.h_ contains **ARDUINO_ESP8266_GIT_VER**
maybe for users like me it would be good to add something similar

**Comment by arendst** [comment]
No need as the problems are solved in the git version where I suppose you talk about the stage version.

**Comment by ascillato** [comment]
I tested Tasmota with the new **lwIP 2.4.1 release** and it works with _no problem_ :+1: . I use _lwIP v2 lower memory_ and the firmware is a bit smaller.

@arendst have you tested it?

**Comment by arendst** [comment]
Thnx for testing. Will do soon too.

**Comment by arendst** [comment]
Just provided version 2.4.1 boards.txt and platform.txt specific updates for tasmota.

**Comment by KPK75** [comment]
I did some tests with 2.4.1 and regardless of lwip it just hungs after after some time ( under minute ). Maybe this is the cause : [https://github.com/esp8266/Arduino/issues/4497](https://github.com/esp8266/Arduino/issues/4497)

**Comment by ascillato** [comment]
Interesting. I have my device working for hours without problem. Which
tasmota version did you use and with which options?

So as to try to reproduce that bug.

Also how did you make the update? Serial / OTA?
I used the serial with the arduino option to erase all the flash (just to
try it).

Did you build the firmware? Arduino / platform.io?

**Comment by KPK75** [comment]
ESP-01 devices. Latest dev version. First OTA then serial. All the same. No bugs. Just hungs - stops working. Do you use webserver ?

**Comment by ascillato** [comment]
Yes. With webserver. But on a nodemcu

**Comment by KPK75** [comment]
After downgrade to 2.4.0 (lwip 1.4) it is working fine.

**Comment by KPK75** [comment]
Found it! 2.4.1 and Sleep >0 == hung.
[https://github.com/esp8266/Arduino/issues/4485](https://github.com/esp8266/Arduino/issues/4485)

**Comment by ascillato** [comment]
Great. I was not using sleep. Thats why. Very good job. Thanks

**Pull request closed without merging**
