### PR TITLE
Update xdrv_12_home_assistant.ino

### PR DESCRIPTION
**Pull request by effelle**
## Description:
Button/switch discovery function now uses `/stat/RESULT`.

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core pre-2.6
  - [X] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
You nailed it!

**Comment by effelle** [comment]
Lesson learned!
The fatigue of the day led me to overthink it, the solution was right there in front of me, damn.

**Comment by arendst** [comment]
Well it was my fault too. Around 01:30 last night I noticed yuo were talking about bitRead. That should never had been there. Was a Copy/Paste error of me.

Anyway, on the release 6.7

**Comment by effelle** [comment]
Yeah, was puzzling, but sooner or later it would happen to find a definition or command with bitread inside. The important thing is now we have a working code. Now back to study to learn to reduce the code because is in part redundant and there are thing I can probably remove. 
Congratulations for the new release, keep going!

**Comment by DavidFW1960** [comment]
Getting a log error for this when Home Assistant starts
```
No matching payload found for entity: sonoff1-2914 Button1 with state_topic: sonoff1/stat/RESULT
Connection lost. Reconnecting…
```
Also no binary_sensor is created.
To be honest, I don't understand what the purpose of this sensor is.

**Comment by effelle** [comment]
No error on my side, if happens again please open an issue.
Buttons and switches where there as binary_sensors since version 5.13 and stop working on 6.3. The functionality was restored with this PR.
The purpose of having a separate `/RESULT` for buttons and switches is for a more granular control letting using them as a trigger event for automation inside HA when not linked to a relay. 
Since before we were using `/POWER` topic there was no way to control button and switches separately. For now they will stay as binary_sensors (then no command topic possible) in the future there will be a more complex setup.

**Comment by DavidFW1960** [comment]
@ascillato asked me on discord to post to this topic.
To be honest I don't see it as an issue - more a useless sensor that does nothing so I disable it.
If I enable it, the error is there when I restart home assistant every time.

**Comment by effelle** [comment]
For me an @ascillato is not useless. :-) 
Anyway, the log you see on HA  is a ` warning`, not an error and is relative to an issue with uppercase/lowercase. 
The payload must be uppercase but the state topic should be lowercase. No idea why, I should ask to HA team one day. I'll see if I can do something Tasmota side.

**Comment by DavidFW1960** [comment]
The sensor never has a state so can't be used for anything = useless. Toggling the switch no state change. What is the use case for this sensor (assuming it is working)? How does Tasmota set the state (or what triggers Tasmota to change the state?)

**Comment by effelle** [comment]
> The sensor never has a state so can't be used for anything = useless. Toggling the switch no state change. 

Again, here on 4 different devices tested all switches and buttons are working as expected. 
Here's an example of one of the auto generated binary_sensor:
```
{
  "name": "Sonoff Switch1",
  "stat_t": "~stat/RESULT",
  "value_template": "{{value_json.SWITCH1}}",
  "pl_on": "ON",
  "avty_t": "~tele/LWT",
  "pl_avail": "Online",
  "pl_not_avail": "Offline",
  "uniq_id": "471XXX_SW_1",
  "device": {
    "identifiers": [
      "471XXX"
    ],
    "connections": [
      [
        "mac",
        "XX:XX:E3:47:10:78"
      ]
    ]
  },
  "~": "sonoff/",
  "frc_upd": true,
  "pl_off": "OFF"
}
```
 I can clearly see turning on and off on my HA. 
> What is the use case for this sensor (assuming it is working)?

@ascillato explained to you on Discord as I have on my earlier reply: is to control button and switches separately from Relay. 

> How does Tasmota set the state (or what triggers Tasmota to change the state?)

The topic now is 
`04:00:04 MQT: sonoff/stat/RESULT = {"SWITCH1":"ON"}`
as you can see on your console when using swithces /buttons and the result change according to `switchmode` or `buttonmode` as normally Tasmota do. When `setoption19` is off this topic will be not published.

If you have any other doubt or question, ping me on Discord but if you think you found an issue please open it and I'll have a look as soon as I can.   
Have a good night.

**Pull request merged**
