### PR TITLE
c61: ignore first rx zero byte if wrong crc

### LINKED ISSUE #13815: DualR3 Power Monitoring only shows 0-Values
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I upgraded my DualR3 from 9.3.1.2 where power readings where ok to release 10.0.0 and dev 10.0.0.1-3 (as of now).
All 10.x versions show power readings, but all are zero (web, mqtt, log).
The device C61 is detected (or implied by template?), but never answers on the first (reset) command.
I discussed this on discord. It seems to be a known issue, suspecting serial does not work properly in the used esp32 framework.
Since it persists for some days now and might hit others, I thought it would be nice to track it here.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Dual R3 (ESP32)
- [x] Tasmota binary firmware version number used: 10.0.0.3
  - [x] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: OTA
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
17:47:03.344 CMD: Backlog Template; Module; GPIO 255
17:47:03.431 MQT: stat/dualr3/RESULT = {"NAME":"Sonoff Dual R3","GPIO":[32,0,0,0,0,0,0,0,0,576,225,0,0,0,0,0,0,0,0,0,0,7296,7328,224,0,0,0,0,160,161,0,0,0,0,0,0],"FLAG":0,"BASE":1}
17:47:03.646 MQT: stat/dualr3/RESULT = {"Module":{"0":"Sonoff Dual R3"}}
17:47:03.886 MQT: stat/dualr3/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"576":"LedLink_i"},"GPIO14":{"225":"Relay2"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"0":"None"},"GPIO24":{"0":"None"},"GPIO25":{"7296":"CSE7761 Tx"},"GPIO26":{"7328":"CSE7761 Rx"},"GPIO27":{"224":"Relay1"},"GPIO32":{"160":"Switch1"},"GPIO33":{"161":"Switch2"},"GPIO34":{"0":"None"},"GPIO35":{"0":"None"},"GPIO36":{"0":"None"},"GPIO37":{"0":"None"},"GPIO38":{"0":"None"},"GPIO39":{"0":"None"}}
```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:

none
```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:

17:48:05.903 CMD: Status 0
17:48:05.924 MQT: stat/dualr3/STATUS = {"Status":{"Module":0,"DeviceName":"DualR3","FriendlyName":["PowerMoni","Gefriertruhe"],"Topic":"dualr3","ButtonTopic":"0","Power":3,"PowerOnState":1,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
17:48:05.979 MQT: stat/dualr3/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/tasmota32-bluetooth.bin","RestartReason":"Software reset CPU","Uptime":"0T00:26:43","StartupUTC":"2021-11-26T16:21:22","Sleep":10,"CfgHolder":4617,"BootCount":116,"BCResetTime":"2021-04-03T18:52:24","SaveCount":4125}}
17:48:06.032 MQT: stat/dualr3/STATUS2 = {"StatusFWR":{"Version":"10.0.0.3(bluetooth)","BuildDateTime":"2021-11-26T14:01:47","Core":"2_0_1_1","SDK":"v4.4-dev-3728-g7cac8278e","CpuFrequency":80,"Hardware":"ESP32-D0WD-V3","CR":"446/699"}}
17:48:06.054 MQT: stat/dualr3/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":4,"LogHost":"192.168.1.4","LogPort":514,"SSId":["job.iot.ssid","job.fritz.ssid"],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C80001000680003C5A0A000000000000","00000480","00006000","0000C002"]}}
17:48:06.093 MQT: stat/dualr3/STATUS4 = {"StatusMEM":{"ProgramSize":1473,"Free":1984,"Heap":77,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F9AC787","00140001","000000CF","010013C0","40000981","00004080","00200000","0000082C"],"Drivers":"1,2,3,4,5,7,8,9,10,12,20,21,24,26,27,29,38,50,52,59,79","Sensors":"1,2,3,5,6,52,62,127"}}
17:48:06.147 MQT: stat/dualr3/STATUS5 = {"StatusNET":{"Hostname":"dualr3","IPAddress":"192.168.1.164","Gateway":"192.168.1.221","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.236","DNSServer2":"0.0.0.0","Mac":"94:B9:7E:68:2B:78","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
17:48:06.185 MQT: stat/dualr3/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.4","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_682B78","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
17:48:06.221 MQT: stat/dualr3/STATUS7 = {"StatusTIM":{"UTC":"2021-11-26T16:48:06","Local":"2021-11-26T17:48:06","StartDST":"2021-03-28T02:00:00","EndDST":"2021-10-31T03:00:00","Timezone":"+01:00","Sunrise":"08:16","Sunset":"16:58"}}
17:48:06.242 MQT: stat/dualr3/STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
17:48:06.274 MQT: stat/dualr3/STATUS10 = {"StatusSNS":{"Time":"2021-11-26T17:48:06","Switch1":"ON","Switch2":"ON","ENERGY":{"TotalStartTime":"2021-04-03T18:52:24","Total":[0.000,0.000],"Yesterday":[0.000,0.000],"Today":[0.000,0.000],"Power":[ 0, 0],"ApparentPower":[ 0, 0],"ReactivePower":[ 0, 0],"Factor":[0.00,0.00],"Voltage": 0,"Current":[0.000,0.000]},"ESP32":{"Temperature":56.1},"TempUnit":"C"}}
17:48:06.335 MQT: stat/dualr3/STATUS11 = {"StatusSTS":{"Time":"2021-11-26T17:48:06","Uptime":"0T00:26:44","UptimeSec":1604,"Heap":80,"SleepMode":"Normal","Sleep":10,"LoadAvg":99,"MqttCount":1,"Berry":{"HeapUsed":4,"Objects":62},"POWER1":"ON","POWER2":"ON","Wifi":{"AP":1,"SSId":"job.iot.ssid","BSSId":"28:D1:27:4E:56:75","Channel":5,"Mode":"11n","RSSI":42,"Signal":-79,"LinkCount":1,"Downtime":"0T00:00:05"}}}
```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:

2021-11-26T17:21:21.304280+01:00 dualr3 ESP-HTP: Restart
2021-11-26T17:21:21.307939+01:00 dualr3 ESP-SRC: WebGui from 192.168.1.4
2021-11-26T17:21:27+01:00 ax1 dnsmasq-dhcp[1]: DHCPACK(br-lan) 192.168.1.164 94:b9:7e:68:2b:78 dualr3
2021-11-26T17:21:28.577838+01:00 dualr3 ESP-HDW: ESP32-D0WD-V3 
2021-11-26T17:21:28.582016+01:00 dualr3 ESP-HDW: FoundPSRAM=0 CanUsePSRAM=0
2021-11-26T17:21:28.603372+01:00 dualr3 ESP-UFS: FlashFS mounted with 40 kB free
2021-11-26T17:21:28.637861+01:00 dualr3 ESP-BRY: GC from 3614 to 3036 bytes, objects freed 5/29 (in 0 ms)
2021-11-26T17:21:28.639592+01:00 dualr3 ESP-BRY: GC from 5322 to 4638 bytes, objects freed 6/61 (in 1 ms)
2021-11-26T17:21:28.644329+01:00 dualr3 ESP-BRY: Berry initialized, RAM used=4638
2021-11-26T17:21:28.647653+01:00 dualr3 ESP-BRY: no 'preinit.be'
2021-11-26T17:21:28.655182+01:00 dualr3 ESP-SRC: Restart
2021-11-26T17:21:28.657989+01:00 dualr3 ESP-Project tasmota - DualR3 Version 10.0.0.3(bluetooth)-2_0_1_1(2021-11-26T14:01:47)
2021-11-26T17:21:28.661831+01:00 dualr3 ESP-M32: init: request callbacks
2021-11-26T17:21:28.679881+01:00 dualr3 ESP-BRY: no 'autoexec.be'
2021-11-26T17:21:28.679881+01:00 dualr3 ESP-WIF: Checking connection...
2021-11-26T17:21:28.679881+01:00 dualr3 ESP-WIF: Attempting connection...
2021-11-26T17:21:28.679881+01:00 dualr3 ESP-WIF: Connecting to AP1 job.iot.ssid Channel 5 BSSId 28:D1:27:4E:56:75 in mode 11n as dualr3...
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-WIF: Checking connection...
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-WIF: Attempting connection...
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-C61: Tx A5EA96DA
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-WIF: Checking connection...
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-WIF: Attempting connection...
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-WIF: Checking connection...
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-WIF: Attempting connection...
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-C61: Tx A500
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-C61: Rx none
2021-11-26T17:21:28.680071+01:00 dualr3 ESP-C61: Tx A500
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-C61: Rx none
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-C61: Tx A500
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-C61: Rx none
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-WIF: Checking connection...
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-WIF: Connected
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-CMD: 
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-SRC: Serial
2021-11-26T17:21:28.680236+01:00 dualr3 ESP-HTP: Web server active on dualr3 with IP address 192.168.1.164
2021-11-26T17:21:29.977799+01:00 dualr3 ESP-NTP: Synch time...
2021-11-26T17:21:29.985853+01:00 dualr3 ESP-RTC: UTC 2021-11-26T16:21:28, DST 2021-03-28T02:00:00, STD 2021-10-31T03:00:00
2021-11-26T17:21:29.998093+01:00 dualr3 ESP-NTP: Synched
2021-11-26T17:21:30.000189+01:00 dualr3 ESP-BLE: MasterEnable->1
2021-11-26T17:21:30.001766+01:00 dualr3 ESP-BLE: BLETask:Starting NimBLE
2021-11-26T17:21:30.075650+01:00 dualr3 ESP-MQT: Attempting connection...
2021-11-26T17:21:30.086916+01:00 dualr3 ESP-MQT: Connected
2021-11-26T17:21:30.094242+01:00 dualr3 ESP-MQT: tele/dualr3/LWT = Online (retained)
2021-11-26T17:21:30.097387+01:00 dualr3 ESP-MQT: cmnd/dualr3/POWER = 
2021-11-26T17:21:30.099662+01:00 dualr3 ESP-MQT: Subscribe to cmnd/dualr3/#
2021-11-26T17:21:30.181225+01:00 dualr3 ESP-MQT: Subscribe to cmnd/tasmotas/#
2021-11-26T17:21:30.190661+01:00 dualr3 ESP-MQT: Subscribe to cmnd/DVES_682B78_fb/#
2021-11-26T17:21:30.196639+01:00 dualr3 ESP-MQT: tele/dualr3/INFO1 = {"Info1":{"Module":"Sonoff Dual R3","Version":"10.0.0.3(bluetooth)","FallbackTopic":"cmnd/DVES_682B78_fb/","GroupTopic":"cmnd/tasmotas/"}}
2021-11-26T17:21:30.198895+01:00 dualr3 ESP-MQT: tele/dualr3/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"dualr3","IPAddress":"192.168.1.164"}}
2021-11-26T17:21:30.203649+01:00 dualr3 ESP-MQT: tele/dualr3/INFO3 = {"Info3":{"RestartReason":"Software reset CPU"}}
2021-11-26T17:21:30.218678+01:00 dualr3 ESP-MQT: stat/dualr3/RESULT = {"POWER1":"ON"}
2021-11-26T17:21:30.283105+01:00 dualr3 ESP-MQT: stat/dualr3/POWER1 = ON
2021-11-26T17:21:30.288195+01:00 dualr3 ESP-MQT: stat/dualr3/RESULT = {"POWER2":"ON"}
2021-11-26T17:21:30.302697+01:00 dualr3 ESP-MQT: stat/dualr3/POWER2 = ON
2021-11-26T17:21:30.608682+01:00 dualr3 ESP-SRC: File
2021-11-26T17:21:30.615328+01:00 dualr3 ESP-CMD: Grp 0, Cmnd 'IBEACON', Idx 1, Len 1, Data '1'
2021-11-26T17:21:30.619526+01:00 dualr3 ESP-MQT: stat/dualr3/RESULT = {"IBEACON":1}
2021-11-26T17:21:30.621782+01:00 dualr3 ESP-SRC: MQTT
2021-11-26T17:21:30.625985+01:00 dualr3 ESP-CMD: Grp 0, Cmnd 'STATUS', Idx 1, Len 0, Data ''
2021-11-26T17:21:30.627982+01:00 dualr3 ESP-MQT: stat/dualr3/STATUS = {"Status":{"Module":0,"DeviceName":"DualR3","FriendlyName":["PowerMoni","Gefriertruhe"],"Topic":"dualr3","ButtonTopic":"0","Power":3,"PowerOnState":1,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0}}
2021-11-26T17:21:30.691124+01:00 dualr3 ESP-QPC: Reset
2021-11-26T17:21:32.163755+01:00 dualr3 ESP-HTP: Main Menu
2021-11-26T17:21:32.562327+01:00 dualr3 ESP-NRG: Energy reset by invalid data
2021-11-26T17:21:32.566865+01:00 dualr3 ESP-APP: Boot Count 116
2021-11-26T17:21:33.577760+01:00 dualr3 ESP-CFG: Saved, Count 4125, Bytes 4096
2021-11-26T17:21:35.836152+01:00 dualr3 ESP-BRY: GC from 6884 to 4557 bytes, objects freed 14/62 (in 1 ms)
2021-11-26T17:21:35.841635+01:00 dualr3 ESP-MQT: tele/dualr3/STATE = {"Time":"2021-11-26T17:21:32","Uptime":"0T00:00:10","UptimeSec":10,"Heap":86,"SleepMode":"Normal","Sleep":10,"LoadAvg":99,"MqttCount":1,"Berry":{"HeapUsed":4,"Objects":62},"POWER1":"ON","POWER2":"ON","Wifi":{"AP":1,"SSId":"job.iot.ssid","BSSId":"28:D1:27:4E:56:75","Channel":5,"Mode":"11n","RSSI":46,"Signal":-77,"LinkCount":1,"Downtime":"0T00:00:05"}}
2021-11-26T17:21:35.917444+01:00 dualr3 ESP-MQT: tele/dualr3/SENSOR = {"Time":"2021-11-26T17:21:32","Switch1":"ON","Switch2":"ON","ENERGY":{"TotalStartTime":"2021-04-03T18:52:24","Total":[0.000,0.000],"Yesterday":[0.000,0.000],"Today":[0.000,0.000],"Period":[ 0, 0],"Power":[ 0, 0],"ApparentPower":[ 0, 0],"ReactivePower":[ 0, 0],"Factor":[0.00,0.00],"Voltage": 0,"Current":[0.000,0.000]},"ESP32":{"Temperature":56.7},"TempUnit":"C"}
2021-11-26T17:21:35.922442+01:00 dualr3 ESP-MQT: tele/dualr3/BLE = {"Time":"2021-11-26T17:21:34","BLEDevices":{"total":0}}
2021-11-26T17:21:35.924197+01:00 dualr3 ESP-MQT: tele/dualr3/BLE = {"Time":"2021-11-26T17:21:34","BLE":{"scans":0,"adverts":17,"devices":0,"resets":0}}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

upgrade a dual r3 to 10.x

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

power readings not zero

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

image

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

Start of discord discussion (is-that-a-bug):
```
joba-1 — 10.11.2021
Hi, I have updated a Sonoff Dual R3 (V1) from 9.3.1.2 to 10.0.0.2 (tasmota32-bluetooth) and lost power monitoring ...
```

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by joba-1**
## Description:

On a Sonoff Dual R3 (ESP32) the power measurement chip CSE7761 sometimes sends an additional zero byte before the normal result frame (or the ESP32 "invents" it, I dont know). With this PR one more byte is read if that happens (detected by wrong crc).

Not sure this PR is worth merging, because the current code would retry the failing command and then usually the zero byte is not sent again -> similar end result. But since I anyways had this code for chasing down the source of the zero byte and stuck serial communication: here it is.

I tested the PR with tasmota32 and tasmota32-bluetooth. Both have this zero byte behaviour. 

I never had a stuck C61 serial communication with this PR, but I doubt the PR is the reason for that and the problem of issue #13815 will show up again after longer testing.

**Related issue (if applicable):** #13815

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by joba-1** [comment]
don't see how the failing CI checks relate to my changes?

btw. This is how syslog (level 4) looks now if such an extra byte is detected (the real Rx frame should be "22F223"):

```
2022-01-12T03:09:33.350761+01:00 dualr3 ESP-C61: Tx A523
2022-01-12T03:09:33.351287+01:00 dualr3 ESP-C61: Rx 0022F2
2022-01-12T03:09:33.351989+01:00 dualr3 ESP-C61: Rx 0022F2, CRC error 15
2022-01-12T03:09:33.355664+01:00 dualr3 ESP-C61: Rx extra 23
```

**Comment by arendst** [comment]
So let's wait a few days and see if this really solves your issue.

**Comment by joba-1** [comment]
Some additional observations after I added some code to measure time in microseconds for each byte read:

* checked over 1_000_000 Rx lines:
* first byte after Tx: min1 = 0, max1 = 4896, avg1 = 963 µs
* following bytes: maxx = 4736 µs (rare, usually just the normal delay for 38400bps)

-> There was no correlation between CRC errors and long delays of first or following bytes
-> 6 ms read timeout as used in the code is long enough to avoid any timeout (with 3ms they happened, but rare)
-> number of CRC errors has not decreased, the zero bytes still show up , so probably not timing related

I also added a 3 ms delay before reading/flushing the Rx buffer, just in case the C61 was still busy sending something for unknown reasons -> never lead to reading an extra 0 byte there. It only appears right after Tx

So far I did not experience a hanging C61 with the changed code, although I cannot see a reason why my changes could cause more stability.
A hanging C61 was rare before, so that still doesn't mean this is gone. Will go on checking...

**Comment by Jason2866** [comment]
@joba-1  Still no problems?

**Comment by joba-1** [comment]
no problems. Energy still updating

Uptime | 4T12:05:30

**Comment by joba-1** [comment]
Something happened...

2022-01-28T03:15:31.594386+01:00 dualr3 ESP-MQT: tele/dualr3/INFO3 = {"Info3":{"RestartReason":{"Exception":29,"Reason":"StoreProhibited","EPC":"40084ee0","EXCVADDR":"00000000","CallChain":["40084edd","40097b31","4009ca11","401d217e","401d19c7","401d1046","401d1015","4011a7b6","40119e2e","4011a0ad"]}}}

probably unrelated, the C61 is still talking to the ESP32

**Comment by joba-1** [comment]
Something else happened.

famous last words (no errors):
```
2022-01-29T15:29:01.312716+01:00 dualr3 ESP-C61: Tx A52D
2022-01-29T15:29:01.312716+01:00 dualr3 ESP-C61: Rx FFFE9D9102
2022-01-29T15:29:01.313101+01:00 dualr3 ESP-C61: F8944, U2295209, I0/7233, P0/90735
2022-01-29T19:42:38+01:00 ax1 dnsmasq-dhcp[1]: DHCPACK(br-lan) 192.168.1.164 94:b9:7e:68:2b:78 dualr3
```
since 15:30 yesterday: silence. No MQTT messages, no web interface, port scan says all ports are closed, but dhcp lease refreshs still work and ping responds.

will need to power cycle.

**Comment by joba-1** [comment]
power cycle didn‘t help. Device is dead. Dim blue led when powered on. No other reaction on (very) long button press or power toggle torture. No AP, no WLAN/DHCP requests.

**Comment by arendst** [comment]
Refresh

**Comment by joba-1** [comment]
staring at the web console for last 5 days or so, I just realized now that the c61 is stuck again, showing zeros.
This is standard dev image without bluetooth. Updating now...

**Pull request closed without merging**
