### PR TITLE
Improved parsing of accumulation data from HRG-15 rain sensor

### PR DESCRIPTION
**Pull request by blacknell**
## Description:

This PR improves the parsing of accumulation data delivered via the serial link. It's possible to receive partials strings (where data is split across 2 lines) so the code now only accepts & forwards each of the 4 measurements if they are correct and entirely within the parsed line. Prior to this change it was possible to get erroneous glitches of 0mm readings.

Rather than wait a very long time for next rain event (days even) the code requests accumulation data every minute so that JSON updates aren't misleading with respect to timestamps.

fix: more robust parsing of accumulation data
add: retrieve accumulation data every 60 seconds

**Related issue (if applicable):** fixes # N/A

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.11
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@blacknell Compile does fail with an esp8266. See https://github.com/Jason2866/Tasmota-build/actions/runs/6144927773/job/16672115960

**Comment by arendst** [comment]
OP should have used ``!isnan()`` instead of ``isfinite()``

**Comment by arendst** [comment]
Done.

**Comment by blacknell** [comment]
Firstly, sorry about this.

I can't get the 8266 to compile

```
In file included from /Users/paul/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src/FatLib/FmtNumber.h:27:0,
                 from /Users/paul/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src/FatLib/FmtNumber.cpp:25:
/Users/paul/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src/FatLib/FmtNumber.cpp: In function 'char* sdfat::fmtFloat(float, char*, uint8_t)':
/Users/paul/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/math.h:209:54: error: '__fpclassifyf' was not declared in this scope
  ((sizeof(__x) == sizeof(float))  ? __fpclassifyf(__x) : \
                                                      ^
/Users/paul/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/math.h:229:21: note: in expansion of macro 'fpclassify'
   #define isnan(y) (fpclassify(y) == FP_NAN)
                     ^
/Users/paul/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src/FatLib/FmtNumber.cpp:248:7: note: in expansion of macro 'isnan'
   if (isnan(value)) {
       ^
```

I've used a few different combinations in `platformio_tasmota_cenv.ini` with and without `lib_extra_dirs`

```
[env:tasmota-weatherstation]
extends = env:tasmota
build_flags             = ${env.build_flags} -DFIRMWARE_WEATHERSTATION
; lib_extra_dirs          = lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div
```

**Comment by blacknell** [comment]
@arendst @Jason2866 - any ideas for what I need to do to compile. All I did was pull the development fix and then compile the 8266 target.

I'd like to do this properly next time.

**Comment by blacknell** [comment]
It compiles using docker-tasmota but not in Visual Studio. I've done a `clean` and `full clean` but something is wrong as I still get these strange errors

```
Building in release mode
Compiling .pio/build/tasmota-blacknell-8266/src/tasmota.ino.cpp.o
Compiling .pio/build/tasmota-blacknell-8266/lib1dd/ESP8266SdFat/FatLib/FmtNumber.cpp.o
Compiling .pio/build/tasmota-blacknell-8266/lib1dd/ESP8266SdFat/SpiDriver/SdSpiSTM32.cpp.o
Compiling .pio/build/tasmota-blacknell-8266/lib1dd/ESP8266SdFat/SpiDriver/SdSpiTeensy3.cpp.o
Compiling .pio/build/tasmota-blacknell-8266/lib8f3/SDFS/SDFS.cpp.o
In file included from /Users/paul/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src/FatLib/FmtNumber.h:27:0,
                 from /Users/paul/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src/FatLib/FmtNumber.cpp:25:
/Users/paul/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266SdFat/src/FatLib/FmtNumber.cpp: In function 'char* sdfat::fmtFloat(float, char*, uint8_t)':
/Users/paul/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/math.h:209:54: error: '__fpclassifyf' was not declared in this scope
  ((sizeof(__x) == sizeof(float))  ? __fpclassifyf(__x) : \
                                                     
```

**Comment by Jason2866** [comment]
Can you post your `user_config_override.h` ?

**Comment by blacknell** [comment]
user_config_override.h
```
#ifndef _USER_CONFIG_OVERRIDE_H_
#define _USER_CONFIG_OVERRIDE_H_

#ifdef FIRMWARE_WEATHERSTATION

#undef CODE_IMAGE_STR
#define CODE_IMAGE_STR "weatherstation"

#undef USE_RULES
#define USE_RULES               // Add support for rules (+8k code)

#undef USE_EXPRESSION
#define USE_EXPRESSION          // Add support for expression evaluation in rules (+3k2 code, +64 bytes mem)

#undef SUPPORT_IF_STATEMENT
#define SUPPORT_IF_STATEMENT    // Add support for IF statement in rules (+4k2 code, -332 bytes mem)

#undef SUPPORT_MQTT_EVENT
#define SUPPORT_MQTT_EVENT      // Support trigger event with MQTT subscriptions (+3k5 code)

#undef USE_PING
#define USE_PING

// #undef USE_MQTT_TLS
// #define USE_MQTT_TLS

#undef USE_MAX17043
#define USE_MAX17043      // Support for LiPo fuel meter

#undef USE_BMP
#define USE_BMP      // Support for BME280 temp, humidity, pressure

#undef USE_BH1750
#define USE_BH1750      // Support for BH1750 light sensor

#undef USE_SHT3X
#define USE_SHT3X      // Support for SHT3X outdoor temp, humidity

#undef USE_HRG15
#define USE_HRG15      // Support for Hydreon RG-15 rain sensor

#endif // FIRMWARE_WEATHERSTATION

#ifdef FIRMWARE_8266DRIVERS

#undef CODE_IMAGE_STR
#define CODE_IMAGE_STR "8266drivers"

#undef USE_MAX17043
#define USE_MAX17043      // Support for LiPo fuel meter

#undef USE_HRG15
#define USE_HRG15      // Support for Hydreon RG-15 rain sensor

#endif // FIRMWARE_8266DRIVERS

#endif  // _USER_CONFIG_OVERRIDE_H_
```

**Comment by blacknell** [comment]
platformio_tasmota_cenv.ini
```
[env:tasmota32-thermostat]
extends = env:tasmota32_base
build_flags             = ${env:tasmota32_base.build_flags} -DFIRMWARE_THERMOSTAT

[env:tasmota32-winder]
extends = env:tasmota32_base
build_flags             = ${env:tasmota32_base.build_flags} -DFIRMWARE_WINDER

[env:tasmota32-blacknell]
extends = env:tasmota32_base
build_flags             = ${env:tasmota32_base.build_flags} -DFIRMWARE_BLACKNELL

[env:tasmota32-weatherstation]
extends = env:tasmota32_base
build_flags             = ${env:tasmota32_base.build_flags} -DFIRMWARE_WEATHERSTATION
platform = espressif32
board = firebeetle32
board_build.partitions  = partitions/esp32_partition_app1856k_fs1344k.csv

[env:tasmota-blacknell-8266]
extends = env:tasmota
build_flags             = ${env.build_flags} -FIRMWARE_8266DRIVERS
lib_extra_dirs          = lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div
```

**Pull request merged**
