### PR TITLE
Added support for Lyasi RGBW E27 Bulb

### LINKED ISSUE #1822: Lyasi/Meamor bulbs
So I bought a Lyasi bulb on Amazon since it also had an ESP8266 chip to try if I could get Tasmota to run on it. However when opening it I was greeted by the lack of Rx/Tx etc contact points.
[Photo album](https://photos.app.goo.gl/AA7OtqQ10U5CEupP2)
As you can see only the (gp)io0, (gp)io2 and RET (whatever that might be, Rest? Rx?) are available. Others might be as well where the green board is soldered to the blue one, but this is unlabled so I don't know. Is it possible to flash Tasmota using only those ports? And if so, how? Or does anyone know the layout of the board?
The bulbs are btw based on the Tuya protocol out of the box.

### PR DESCRIPTION
**Pull request by victorChB**
Added a new template for Lyasi bulbs
https://www.amazon.co.uk/LYASI-Multicolored-Smartphone-Controlled-Compatible/dp/B075GJGMPX

## Description:

**Related issue (if applicable):** fixes <https://github.com/arendst/Sonoff-Tasmota/issues/1822>

## Checklist:
  - [x ] The pull request is done against the latest dev branch
  - [ x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x ] Only one feature/fix was added per PR.
  - [x ] The code change is tested and works.
  - [x ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x ] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by blakadder** [comment]
All new devices that have all the features supported in the firmware should be implemented using [Templates](https://github.com/arendst/Sonoff-Tasmota/wiki/templates) and not by altering code

**Comment by Jason2866** [comment]
Please close this request, it is invalid. All new devices are added via Templates if possible.
Only if a code change is neccersary to get it working a PR is valid and welcome.
Template function is described in wiki. Your finding is highly welcome to be added (if not already there) in Template database.
THX

**Comment by arendst** [comment]
As suggested, these changes are now better served by a user template.

In this case you might base it on the AiLight module.

**Comment by ascillato2** [comment]
Closing PR as this can be added to Tasmota using templates. Anyway, thanks for sharing your ideas.

**Pull request closed without merging**
