### PR TITLE
Paired interlock, interlock bucket size and masking interlock relays

### PR DESCRIPTION
**Pull request by stefanbode**
H @arendst, I'm a git NIGHTMARE. There are only 3-4 files changed if doing an ASCII comparison to the current development branch. Because of the fork process it names 1000+ more. Please see my wiki for explanation and examples. The bucketsize defines the number of relays in interlock. for paired interlock this is 2. With the interlockmask you define a binary mask to include only specific relays in the interlock process. The current functionality for full interlock is still fully supported.. 
These are the changed files:
sonoff/language/en-GB.h (as example)
sonoff/settings.h
sonoff/sonoff.ino

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

This PR modify 1200 files of the project. So, it can't be merged.

Let's try the following. In the github webpage of arendst repository, go to one of the files you want to modify. Then click in the pencil (in the upper right). Do your modifications you want in that file. Then save it (all with the webpage). This process will make a new branch in YOUR repository called patch1 that is an exact copy of Theo's but with just your change.
Then you can make in your branch all the changes you need. And after that make the PR from that branch.

**Comment by ascillato2** [comment]
Please re do the PR. A lot of people were asking for your interlock ;)

**Comment by stefanbode** [comment]
I need your help to do the PR. Please call me on skype: stefan_bode. As mentioned above there are only three files changed. the 1000+ changes are because GITHUB does not make a ASCII comparison.

**Comment by ascillato2** [comment]
Ok. I will later when I reach home. :)

**Comment by ascillato** [comment]
Sorry I couldn’t connect earlier. I was super busy. When I was about to connect I saw your new PR. Great! :+1:

**Pull request closed without merging**
