### PR TITLE
Hard Thermostat With Web Controls

### PR DESCRIPTION
**Pull request by IceStuff**
This is the code for the hard thermostat allowing control either heating or cooling on device for Sonoff TH.  Control can be via webpage or MQTT.

### CODE REVIEW

**Review by reloxx13 — CHANGES_REQUESTED** [review]
You should add any new language keys at least in english in all other i18n files, if not, compiling will fail for other languages.

**Comment by arendst** [comment]
Apart from the user interface is it's functionality not basically the same as a rule like:
```
{"Rule":"ON","Once":"ON","Rules":"on ds18b20#temperature>24 do power off endon on ds18b20#temperature<23 do power on endon"}
```
With variations in warming/cooling or other sensor type. Once the rule is configured the unit will perform like a thermostat standalone too.

**Comment by sebfromme** [comment]
Guys, pls could I kindly ask you how to include IceStuffs code into my build or where to add arendsts rule? I'm highly interested in getting exactly this function.
Thx Seb

**Comment by ascillato2** [comment]
Thanks for sharing your ideas. It is a good one. By now, This PR is not going to be merged due to be rebased from the actual code of Tasmota. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

**Comment by gabrielklein** [comment]
I think this feature was great! What is missing to include it in the main code?

(With some define to avoid "overloading" the code)

**Pull request closed without merging**
