### PR TITLE
Webcam mutex - fixes some AIThinker webcam issues

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:

**Related issue (if applicable):** fixes [Discussion 18482](https://github.com/arendst/Tasmota/discussions/18482)

Investigation of webcam failures in AITHINKER esp32cam module indicate that the issue is likely multi-threading.
The modifications in this PR add a mutex to many webcam related functions in the webcam driver.
See discussion for the types of issues experienced.

NOTE: I have also enabled USE_I2C in webcam firmware - this is not necessary, but helps with understanding webcam hardware.

## Checklist:
  - [*] The pull request is done against the latest development branch
  - [*] Only relevant files were touched
  - [*] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [*] The code change is tested and works with Tasmota core ESP32 V.2.0.9
  - [*] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
I've just made changes a bit different to what you suggested to the I2C init code. ALso enable I2C for the webcam.

**Comment by btsimonh** [comment]
@arendst - 

hmm..  I don't see any mutex in new commits....  @Jason2866 fixed the Wc.up thing...  and I see your I2C...

do you want me to re-create the PR on top of the latest dev?

br,
Simon

**Comment by arendst** [comment]
Yes pls

**Comment by btsimonh** [comment]
Replaced with a new one on top of modified dev

**Pull request closed without merging**
