### PR TITLE
Remove whitespaces

### PR DESCRIPTION
**Pull request by yuvalabou**
## Description:

Remove all trailing whitespaces

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
Can you share the tool you used? This would allow us to automate. 

I'm not a big fan of such a huge change, there can be some hidden breaking changes

**Comment by yuvalabou** [comment]
Used this terminal command
```
git grep -I --name-only -z -e '' | xargs -0 sed -i -e 's/[ \t]\+\(\r\?\)$/\1/
```

**Comment by s-hadinger** [comment]
How do you know you didn't accidentally changed a binary file that would contain a sequence that looks like white spaces at end of file?

**Comment by s-hadinger** [comment]
Also I wouldn't change the `lib` directories that contain libraries unchanged

**Comment by barbudor** [comment]
I believe too there are less risks by doing it one by one while doing other changes

**Comment by sfromis** [comment]
Yeah, while detecting/trimming trailing whitespace is a relevant linter feature, I do not see it as worth the effort and potential risk to go through all files in a mass operation. Of course, risks could be reduced by only going for specific file types, instead of all files, but still - just not important.

**Comment by Jason2866** [comment]
Closing since to many files touched without knowing what is changed.

**Pull request closed without merging**
