### PR TITLE
Update Arduino to release 2.5.0

### PR DESCRIPTION
**Pull request by Jason2866**

### CODE REVIEW

**Comment by andrethomas** [comment]
@Jason2866 dio or dout ?

**Comment by Jason2866** [comment]
I copied the setting from original Arduino 2.5.0 file.

**Comment by Jason2866** [comment]
I copied all the Tasmotized settings from the beta3 files

**Review by andrethomas2 — APPROVED** [review]

**Comment by arendst** [comment]
Who changed a cw01 qio to dio?

cw01 should never be used and doesn't need to change 

Only dout is supported.

**Comment by arendst** [comment]
Oh, I see it's the core team that changed it.

**Pull request merged**
