### PR TITLE
Enable VL53L0X and disable TSL2561 for Tasmota-Sensors and Tasmota32

### PR DESCRIPTION
**Pull request by ascillato**
## Description:

Due to there is more usage on the distance sensor than on the light sensor, enable VL53L0X and disable TSL2561 for Tasmota-Sensors and Tasmota32. Both use the same I2C address.

**Related issue (if applicable):** NA

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with core ESP32 V.1.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by MarSysa** [comment]
Hello,
Do you have any statistics how many devices are using VL53L0X and TSL2561?
My observations are opposite and I regret it has been removed.

**Comment by ascillato** [comment]
We are sorry that you regret this change. It is impossible to let everyone happy with changes like this, where sensors are mutually exclusive because they have the same I2C address (manufacturer decision).
Some people like this change, some others not.
As Tasmota is a non-cloud firmware and as Tasmota never send to us any usage information nor statistics, we only have what users really request and ask here.
Tasmota is an open source firmware maintained by volunteers and provided as is and for free. Sorry that this was unconvenient for you. As a solution, you can always compile your own version with the features you need and excluding the ones you don't need. Compilation is fast and easy (please check Tasmota docs for that). Thanks.

**Comment by joba-1** [comment]
ok, to give you one more feedback, here is my (obviously biased) vote for TSL2561 :) If I need TOF I always use the superior vl53l1x anyways.
Otoh I don’t have a problem with self compile, so whatever suits the majority is fine with me.

**Comment by dbochicchio** [comment]
My vote for TSL2561 as well. Can't you just enable/disable this via a flag?

**Pull request merged**
