### PR TITLE
Simplified Initial WiFi Configuration

### PR DESCRIPTION
**Pull request by ascillato**
## Description:

In this PR, it is proposed a New Initial WiFi Configuration Menu and procedure.

In order to simplify the on-boarding to Tasmota, the first configuration step has been modified.

When powered up a blank device ( without any WiFi SSID stored in the firmware ), you will see in your Phone or PC a new WiFi Network named like **_tasmota_XXXXXX_**.

If you connect to it, you will see:

Clicking on any WiFi Network's name, that will be copied to the field called WiFi Network. And then, after you have completed the password, you will see:

Clicking on save, you will see the Testing Screen:

image

If the WiFi Credentials are wrong, few seconds later you will see:  

If trying again but with correct password:

image

And if all WiFi Credentials are Ok, few seconds later you will see:

image

At this stage, Tasmota will turn off its own AP mode (its own WiFi Network will disappear) and your PC or Phone will automatically reconnect to its previous WiFi Network. If you wait few more seconds, the webpage will be redirected to the new IP of Tasmota in the Network it just connected and you will see the main page of Tasmota. So, you can continue using Tasmota in the same window, without the need of searching for your device in the Network:

-----
### OPTIONALS
-----

If you do not want this **_redirecting feature_**, just define the following in your _user_config_override.h_:

```lua
#define AFTER_INITIAL_WIFI_CONFIG_GO_TO_NEW_IP    false
```

And After the successful connection, you will see:

image

-----

On the first page, if clicking on SCAN FOR ALL WiFi NETWORKS, you will see the complete list of Networks Tasmota is reaching.

image

-----

On the first page, if clicking on MORE OPTIONS, you will see the extra options:

----

The old WiFi Configuration Page that has the Alternative SSId, CORS and Hostname, is available AFTER the initial configuration has finished and from the main menu of Tasmota.

image

------

The RESTART_AFTER_INITIAL_WIFI_CONFIG option is enabled by Default. If you define it as false in **_user_config_override.h_** file, Tasmota won´t restart and will remain in both modes AP and STA, so it will stay connected to the WiFi Network and also it will be providing the AP until next restart. You can reach Tasmota from both Networks.

```lua
#define RESTART_AFTER_INITIAL_WIFI_CONFIG         false
```

This allows the user to continue the configuration.

In this mode, Tasmota shows the IP in both Networks the same as `SO53 1`

image

------

If after a successful WiFi configuration, the user wants to enter again in the AP mode by pressing **_button1_** 6 times or by `wificonfig 2` command, the user will see the normal version of the wifimanager:

image

------

### List of modifications

*On Initial AP Mode (Blank Device):*

- Module Name is not Shown so as to simplify the page.
- A new button called More Options is added, and the other config options are hidden.
- The restart counter is not active in this mode, as there is no WiFi Configuration.

*On AP Mode (Not a Blank Device):*

- The IP is shown in screen ( `SO53 1` )

*On all WiFi Configuration menus:*

- The strongest 3 WiFi Networks are shown.
- If clicking on Show All Networks, all networks are shown with their BSSId and Channel. Also Networks with the same SSId are shown.

------

Tested on ESP8266 and ESP32. In both chips, it works as expected.
Tested on FIRMWARE-MINIMAL. The behaviour of that version is not modified and working as expected.
Tested on manual WIFIMANAGER mode after SSId Configured.
This PR adds 3KB of flash usage.

**Related issue (if applicable):** NA

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with core ESP32 V.1.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Nice!. The uncomfortabel searching for the associated IP address of the new Tasmota device in the user network is solved. This was imho the last hurdle for Tasmota beginners.

**Comment by arendst** [comment]
Thx! You did a great job!!

We both know where this came from.....

**Comment by blakadder** [comment]
i love the new feature, i hate the fact i need to rewrite the getting started docs

**Comment by discip** [comment]
Very nice!
Thank you!

**Comment by MacSass** [comment]
Great Update!
From my point of view that was one of the most challeging roadblocks for new Tasmota users, that this dialogue was too "nerdy" for a non technical user. This will make it way easier for them now and should help to increase Tasmota usage in general ...

Thanks for this nice commit!

**Comment by frogale** [comment]
Possible problem with this and Sonoff Basic:
https://github.com/arendst/Tasmota/discussions/16052
Is it relevant?

**Pull request merged**
