### PR TITLE
Wich e-paper devices are supportet in tasmota ?

### PR DESCRIPTION
**Pull request by roesl**
Is there a list of supported e-paper displays for tasmota ?

I have a display

https://www.ebay.de/itm/Black-2-9-inch-e-Paper-e-Ink-Display-Module-296x128-for-Arduino-Raspberry-Pi/303248398628?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

wich does not work 

regards
Georg

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest dev branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core 2.6.1
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by meingraham** [comment]
Go to tasmota.com and read the Displays article.

**Comment by roesl** [comment]
I want to know  WHICH e-paper devices are supported !!
There is NOTHING About which BRAND AND WHICH TYPE and I my device is NOT working

**Comment by meingraham** [comment]
@roesl - Here's the roadmap:
1. https://tasmota.github.io/docs/#/Displays  

2. image  

3. https://tasmota.github.io/docs/#/Commands?id=displays  

4. https://tasmota.github.io/docs/#/Commands?id=displaymodel  

5. image  

   1. (5) https://www.waveshare.com/wiki/2.9inch_e-Paper_Module  
   2. (6) https://www.waveshare.com/wiki/4.2inch_e-Paper_Module

I hope this helps get you to the information about `Wich e-paper devices are supportet in tasmota ?`.

**Comment by roesl** [comment]
it would be useful for other users when only  the waveshare Display is supported,  this would be mentioned in the list of Displays - so I bought a Display which is not supported

**Comment by meingraham** [comment]
As shown, the documentation _**does**_ list the supported displays. The responsibility to research/inquire really falls on the user and should take place prior to making a purchase. There are occasions when certain clones also function which in your case appears to not be the case. You can return the item you purchased and purchase a supported display instead.

**Pull request closed without merging**
