### PR TITLE
Support of new Sensor SK04T

### PR DESCRIPTION
**Pull request by merlin2533**
## Description:
A new sensor support will add on the commit

## Checklist:
  - [X ] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X ] The code change is tested and works on core 2.6.1
  - [X ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato2** [comment]
Sorry, Invalid PR.

You are changing so many files and making changes to backwards versions.

Please, Re Do your PR with only the file you need to change

**Comment by Jason2866** [comment]
PR is done wrong, touching and changing files

**Comment by ascillato2** [comment]
The easiest way to perform a PR without this mistake is to go to the Tasmota Repository on dev branch ( https://github.com/arendst/Tasmota ), go to the folder you want to add your new driver and click on upload file OR new file. Add it. Then github will automatically made a new up to date branch of actual Tasmota codebase in your own fork (called patch-1) Then, if you need, you can modify files there in your branch and after you can click on **compare and make pull request** link that will be on your repository.

**Comment by ascillato2** [comment]
if you need further assistance, please, do not hesitate on asking here on in the Tasmota Support Chat.

**Comment by ascillato2** [comment]
also use the next available sensor number. there is no need to use 99

**Comment by ascillato2** [comment]
Also, you have some key that were never defined like KNX_DISTANCE. As the KNX driver don't have support to that, avoid adding that because will render to a compiling issue.

**Pull request closed without merging**
