### PR TITLE
PR2 max7219 dot matrix, less memory

### PR DESCRIPTION
**Pull request by sternegugger**
## Description:

This driver enables the display of ascii text on MAX7219 based 8x8 LED dot matrix modules (1088AS).
#define USE_DISPLAY_MAX7219_MATRIX
See also usage description in file tasmota/xdsp_19_max7219_matrix.ino

144709719-2fb4ff2c-7645-4dd8-b0a3-eccd306d63f0
144709723-833ff002-ef84-431a-b05f-8b7ef30e0072

Same functionality as PR #13917, but less memory usage.
(character table only for standard ascii, no usage of lib time.h)

tasmota_display witout USE_DISPLAY_MAX7219_MATRIX
uses 609556 bytes

tasmota_display #define USE_DISPLAY_MAX7219_MATRIX
uses 603736 bytes
(-5820 bytes, cause impicit #undef USE_DISPLAY_MAX7219 and #undef USE_DISPLAY_TM1637)

tasmota_display #define USE_DISPLAY_MAX7219_MATRIX #define USE_UTF8_LATIN1
uses 604584 bytes
(+848 bytes for additional character tables)

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.1.1
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Rushmed** [comment]
Thanks a lot for making the matrix displays work with tasmota.

I use eight 8x8 modules in a row. The first module is always on full brightnes and all LEDs are on.
In the picture the 1234567890 should be displayed and as you can see tne 1 is missing.

Any idea?

**Comment by sternegugger** [comment]
Have you set "DisplayWidth 64"? (64 pixels in a row).
It might help to power off and on the 5V for the matrix display and restart the ESP.
The display must have power when the ESP starts to get initialized.
(The first display on your photo is not initialized).

Are you shure that the orientation of the first display isn't upside down?
Try to unplug it, turn it 180° and plug it in again.

**Comment by Rushmed** [comment]
The display is powered by the ESP so how to bring power to the diplay before ESP starts.
Is ther a way to force initialisation?

**Comment by Rushmed** [comment]
I compared your driver with [this one](https://github.com/liv-in-sky/MatrixDisplayESP8266/blob/master/README.md). There is no initialisation issue.

Is there a way to provide modes in your driver?

**Comment by sternegugger** [comment]
Hi Rushmed,

there is no initialisation issue with this driver when wowering the ESP and the display at the same time. 

> Edit: Solved by changing Module type from Generic (18) to Generic (0)

Yes, chaniging the module type causes a restart of the module which resends the initalisation to the display.

> Is ther a way to force initialisation?

Yes: Restarting the ESP. E.g. use the web console command "restart"

> Is there a way to provide modes in your driver?

The driver is written memory optimized and contains only a minimum of necessary functionality.
It only scrolls when the text is longer than the display width.
It can blink using the command "displayBlinkrate".
It can show the current time using the command displayClock.

Which display modes do you miss for your project?

Regards,
Michael

**Comment by Rushmed** [comment]
Hallo Michael,

do you connect the LEDs to the power source directly? I am powering the LEDs with the ESP output.
The restart command does not help for me. The only way to get all modules initialized is to unplug and replug the ESP which sometimes leads to loss of configuration. Of course tahs just a test setup which I poweroff every evening. In real live the esp will stay powered on.
I ve just been asking for your plans of integrating any  modes, I dont miss anything.

**Comment by sternegugger** [comment]
Hi Rushmed,

> do you connect the LEDs to the power source directly?

No, I use the same USB power supply as for the ESP.
Depending on the display size , the used current could be **more than 1 A**.
Please **do not use a PC USB output to power the display.** It supports only 500 mA maximum.
Using more current decreases the Voltage, which could have bad impact to the GPIO signal quality.

**So be sure to use a 5 V source with enough power.**

**Comment by Rushmed** [comment]
OK thanks.

**Comment by Rushmed** [comment]
FYI. I was able to solve the initialisation issue by the help of another user.
My mistke was to use GPIO15 (D8).
Now it works as expected.
Thanks!

**Comment by bigtruite** [comment]
I already use 16 moduls in row. Still using another code, which is still buggy. My standard view is a clock <weekday, month, day, hh:mm:ss>. I find it really cool. Every minute i generate a mqtt post from openhab with sensor values from my smart home. After that it returns to the clock. Is it already possible with tasmota? Could it be added too?
vlcsnap-2022-01-31-15h59m46s303

**Comment by sternegugger** [comment]
> My standard view is a clock <weekday, month, day, hh:mm:ss>. I find it really cool. Every minute i generate a mqtt post from openhab with sensor values from my smart home. After that it returns to the clock. Is this clock already possible with tasmota? Could it be added too?

Using this display with Tasmota it can display any string via MQTT.
E.g.: `displayText Mon Jan 31 10:07`
You could repeat it every minute to update the minute digits 
This should be done via an MQTT client (I'm using openhab), which controlls the whole functionality.

The tasmota display driver also supports a clock display.
Please try command: `displayClock`
Depending of displayWidth it shows "HH:MM" or "HH:MM:SS".
The date is not displayed. There are too many variants depending on language and country.

To switch back from clock to text send: `displayMode 0`
Now you can use `displayText` again to display any other text.

Regards,
Michael

**Comment by bigtruite** [comment]
> > My standard view is a clock <weekday, month, day, hh:mm:ss>. I find it really cool. Every minute i generate a mqtt post from openhab with sensor values from my smart home. After that it returns to the clock. Is this clock already possible with tasmota? Could it be added too?
> 
> Using this display with Tasmota it can display any string via MQTT. E.g.: `displayText Mon Jan 31 10:07` You could repeat it every minute to update the minute digits This should be done via an MQTT client (I'm using openhab), which controlls the whole functionality.
> 
> The tasmota display driver also supports a clock display. Please try command: `displayClock` Depending of displayWidth it shows "HH:MM" or "HH:MM:SS". The date is not displayed. There are too many variants depending on language and country.
> 
> To switch back from clock to text send: `displayMode 0` Now you can use `displayText` again to display any other text.
> 
> Regards, Michael

Dear Michael,

i also use openhab with this current code to post a mqtt payload. But i already send all my values from my weatherstation every minute. So it is not possible to post a second one with my time notification withous having trouble with synchronisation. And i would loos the seconds, that are displayed now. Just see the video i added. The max 7219 are really cool and it is really easy to use more than one or two of them. The current clock with "HH:MM" or "HH:MM:SS" could be to small if you use 4 elements of max7219. Just try to put the english notification. It would be enough if this option could be set in the xdsp_19_max7219_matrix.ino itself. Could be very vool. :-)

Thank you very much. 

Regards Patrick.

https://user-images.githubusercontent.com/48525816/152198604-fef21fbf-c4f8-430a-aa86-610c064b14c3.mp4

**Comment by Rushmed** [comment]
Is this driver included in the new Tasmota V11 display.bin or do I still need to implement and compile?

**Comment by oliver-koch** [comment]
Changelog of v11 says yes:

Support for MAX7219 Dot Matrix displays #14091

**Comment by Rushmed** [comment]
I know but its not working.

**Comment by sternegugger** [comment]
> Is this driver included in the new Tasmota V11 display.bin or do I still need to implement and compile?

Yes, as described you still need to compile with:
**`#define USE_DISPLAY_MAX7219_MATRIX`**

**Resaon:**
the default supports MAX7219 driver for 7 segment displays.
The behaviour of MAX7219_MATRIX supports 8x8 matrix displays, which is different to 7 segment displays.

**`#define USE_DISPLAY_MAX7219_MATRIX`**
disables the default support of MAX7219 based 7 segment displays und supports MAX7219 based 8x8 matrix displays instead.

See also file [tasmota_template.h line 558](https://github.com/arendst/Tasmota/blob/64ea803ef11cd6d0df76ff574e16e38c2439eaf2/tasmota/tasmota_template.h#L558) on v11.0.0

**Comment by Rushmed** [comment]
ok, thanks!

**Comment by Rojer7084** [comment]
Dear frend,
I use 4 modules  the display not correct  , the charecter was saparate .  anyone found like me?

**Comment by maxduckduck** [comment]
Hi,
The TM1637, TM1638 and MAX7219 Seven-Segment Display[~](https://tasmota.github.io/docs/TM163x/#tm1637-tm1638-and-max7219-seven-segment-display) has the feature (DisplayLevel) that displays a single column bar.  Is it possible to have similar functionality for multible columns in the 8x8 Matrix?  I use this for water tank levels but I have multiple tanks and was trying to simplify things.

**Comment by IlmNaseerAhmed** [comment]
i am a beginner i only knows how to use tasmotizer with nodemcu, can any body give me a bin file, regards

**Comment by viktor6** [comment]
share the firmware for esp32

**Pull request merged**
