### PR TITLE
Add support for Shelly dimmer 1 and 2

### LINKED ISSUE #6914: Support for shelly dimmer
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

I would like to order the new "Shelly Dimmer" and currently do not see a template. Has anyone ever tested the device or even run it with a different setting from another device?

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by jamesturton**
## Description:

**Related issue (if applicable):** fixes #6914 and #9412

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR. (Adds support for both Shelly dimmer 1 and 2 using a single driver)
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
I understand that it's convenient for the Shelly Dimmer community to have their own binary but I prefer to include it like any other device; by user defines in my_user_config.h

Your solution does not make use of the many translated binaries available.

Pls reconsider and if there are any issues prohibiting this just let me know.

**Comment by arendst** [comment]
James,

many thx for your hard work.

I'll merge some of your work now to ease future changes. Pls stop working on this PR until I've merged most of it.

Once done I'll contact you here again.

My main goal is to add it as any other dimmer. I think by using one of the GPIOs needed for firmware upgrade just needs to be in the template. This will allow auto selection of the correct driver.

**Comment by jamesturton** [comment]
> I understand that it's convenient for the Shelly Dimmer community to have their own binary but I prefer to include it like any other device; by user defines in my_user_config.h
> 
> Your solution does not make use of the many translated binaries available.
> 
> Pls reconsider and if there are any issues prohibiting this just let me know.

Due to the inclusion of a firmware binary file that is flashed to the stm32 co-processor on the Shelly dimmer, the resulting Tasmota binary is rather large. Only a minimum set of other features can be included in the build if the binary is small enough to be used for over-the-air updates.

Earlier in the testing processes, the image was built against the default 'tasmota' environment, but this required users to first flash a smaller binary (such as 'tasmota-lite') before flashing the new 'tasmota-shelly-dimmer' binary. While this was ok for testing, it don't believe this is a very good solution, hence making it's own environment.

**Comment by jamesturton** [comment]
> I'll merge some of your work now to ease future changes. Pls stop working on this PR until I've merged most of it.
> 
> Once done I'll contact you here again.

Great, thanks!

**Comment by Jason2866** [comment]
Why include the stm32 firmware in the Tasmota build?
Isnt it possible to flash the firmware like the way it is done for the rfbridge and zbbridge?

**Comment by arendst** [comment]
It's now merged without the platformio driven own binary.

I made a test for configured GPIO Boot0 and reset inverted. If not in the template it does not select Shelly Dimmer.

Can you provide the Shelly dimmer templates too pls.

**Comment by jamesturton** [comment]
@arendst Templates are as follows:

**Shelly Dimmer 1**
```{"NAME":"Shelly Dimmer 1","GPIO":[0,3200,0,3232,5504,5536,0,0,192,0,193,288,0,4736],"FLAG":0,"BASE":18}```

**Shelly Dimmer 2**
```{"NAME":"Shelly Dimmer 2","GPIO":[0,3200,0,3232,5504,5536,0,0,193,0,192,0,320,4736],"FLAG":0,"BASE":18}```



@Jason2866 
> Why include the stm32 firmware in the Tasmota build?

I lot of time was spend reverse engineering the communication protocol between the ESP8266 and the STM32 but unfortunately Shelly changed the protocol between different versions. Therefore, if Tasmota didn't flash the STM32 to a known firmware version it would be a lucky guess as to whether the Tasmota protocol would match the Shelly firmware on the STM32. You can read more discussion about the reasoning in issue https://github.com/arendst/Tasmota/issues/6914#issuecomment-660666929

> Isnt it possible to flash the firmware like the way it is done for the rfbridge and zbbridge?

I'm not sure how it is done in the rfbridge or zbbridge but as far as I am aware, neither of those devices use an STM32 as the co-processor so the bitstream would be completely different I guess?

**Comment by arendst** [comment]
Thx again.

I ordered a dimmer 2 too and will have a look if stm32 flashing can be done like zigbee and rf bridge. Until then your procedure can be used.

**Comment by Jason2866** [comment]
@jamesturton  first Great Work done! 
To clearify, my idea was more general. Implementing the needed flash routines (as you did)
and uploading the needed firmware files (for stm32) via the firmware upload function.
As Theo said he will take a look at.

**Comment by arendst** [comment]
Hi James, can you provide a binary image for the stm32 pls. I need it for the upload process.

**Comment by jamesturton** [comment]
Here is the latest binary: [shelly-dimmer-stm32_v51.4.bin.gz](https://github.com/arendst/Tasmota/files/5542808/shelly-dimmer-stm32_v51.4.bin.gz)

**Comment by mgoeller** [comment]
When I flash the newest Tasmota v9.1 to my Shelly Dimmer 1 or 2, and then try to upload the STM firmware, I get either an Magic Byte is not E9 error (if it is not the *.gz version), and if I use the gz version, it never boots again until I re-flash Tasmota. What do I do wrong?

**Comment by daxy01** [comment]
@mgoeller Double-check the template you're using. I've had the same when I had the wrong template.

Correct Templates:
Shelly Dimmer: https://templates.blakadder.com/shelly_Dimmer.html
Shelly Dimmer2: https://templates.blakadder.com/shelly_Dimmer_2.html

**Comment by Jason2866** [comment]
Did you download the firmware correctly? Take a look in the file.
Do *not* use save as from browser.

**Comment by mgoeller** [comment]
I download the official Tasmota v9.1, right? Not any special version or dev version?

I downloaded the firmware file from the Link you sent @Jason2866. Using Safari and Chrome and using the Download button on the GitHub page, when clicking on the firmware file. This results me in a *.bin file. I get the Magic Byte error then. Even when I use the slightly different template from the blakadder directory.

What do I do wrong?

When I use the prepared Shelly Dimmer version of @jamesturton "tasmota_shelly_dimmer_v1.3.bin", everything works using the old template from the GitHub Thread. How would I get from this to the newest Tasmota version and the newest STM binary.

**Comment by stefxx** [comment]
I believe you need 9.1.0.2 for Shelly Dimmer support.

**Comment by mgoeller** [comment]
Thank you @stefxx, now with the Dev Version it worked. I didn't see your Edit @Jason2866!

Thanks

**Pull request closed without merging**
