### PR TITLE
Update xdrv_03_energy.ino

### PR DESCRIPTION
**Pull request by Yeti1981**
## Description:

**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest dev branch
  - [ ] Only relevant files were touched (Also remember to add to _changelog.ino_ file without updating version)
  - [ ] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works.
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [ ] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
What's the goal of sending the internal char address to domoticz? The suggested PR won't work.

**Comment by arendst** [comment]
Current implementation already sends info to Domoticz correctly:
```
16:42:16 MQT: domoticz/in = {"idx":166,"nvalue":0,"svalue":"7;2207.3","Battery":100,"RSSI":10}
16:42:16 MQT: domoticz/in = {"idx":204,"nvalue":0,"svalue":"223.4","Battery":100,"RSSI":10}
16:42:16 MQT: domoticz/in = {"idx":205,"nvalue":0,"svalue":"0.090","Battery":100,"RSSI":10}
```

**Comment by Yeti1981** [comment]
Helo. I have a problem with Domoticz Energy meter Idx 66 send Total Energy. I need value in Red circle. Can You help me?

⁣Pozdrawiam Bartosz Jędrzejczyk​

W dniu 8 lip 2019, 16:40, o 16:40, użytkownik Theo Arends <notifications@github.com> napisał:

**Comment by arendst** [comment]
This is the wrong location for asking questions. Open an issue if you encouter a bug or use discord for questions like this.

See README.md for proper links.

**Pull request closed without merging**
