### PR TITLE
Software Serial buffer to MIN_INPUT_BUFFER_SIZE

### PR DESCRIPTION
**Pull request by ortegafernando**
Increase software serial buffer to MIN_INPUT_BUFFER_SIZE.

## Description:

I have found this pull request that was accepted https://github.com/arendst/Tasmota/commit/b8752b7272495ebbc485ee4eca140aae0b4184f0

But it was revert afterwards
https://github.com/arendst/Tasmota/commit/aaa87a037a113dd7b4b006500d545a57bf85bbeb
https://github.com/arendst/Tasmota/pull/14153

The reason seems to be about: _"There is something wrong with serial config parameter, the change performs the config conversion twice resulting in a bogus config."_

Nothing about, buffer size.

I ask you for increasing the buffer of software serial connection from 130 to 200 or to MIN_INPUT_BUFFER_SIZE. May be a constant declared here is considered better option
https://github.com/arendst/Tasmota/blob/6bfb9d6aa4a8c0170581850cf5f66db909dc01f7/tasmota/include/tasmota.h#L200

It will not waste RAM if you dont use software serial.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
One thing, why?

**Comment by ortegafernando** [comment]
> One thing, why?

Because I (and probably some people) need more buffer in software serial. In this case, for me is enoght about 200 bytes, but searchin code I have found that a constant like MIN_INPUT_BUFFER_SIZE = 256; may be is better.

Also, I could change source code and make a PR to have a configurable buffer for software serial (it will need a restart after updating it). It will only "cost" a byte in flash memory like other settings (default 130, but user selectable).

This last option is better of course, but we have plenty of RAM for upgrading 130 bytes to 256.

Do you prefer the "configurable" option like "serialbuffer" ---> "sserialbuffer" command?

**Comment by Jason2866** [comment]
@arendst Whats your opinion?

**Comment by arendst** [comment]
Let's have it fixed to 256 for now.

**Comment by ortegafernando** [comment]
I will make a PR in docs. @barbudor you can reject it if you dont want to give this value in wiki, thanks.

**Comment by barbudor** [comment]
@ortegafernando 
No problems as far as you make it in docs/development 😄

**Pull request merged**
