### PR TITLE
Add favicon on browser

### LINKED ISSUE #4830: favicon in Tasmota
Hello, i am new to esp8266 and tasmota !!
i have a question can i add favicon in html of tasmota ?

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

[**Related issue (if applicable):** fixes #4830](https://github.com/arendst/Tasmota/issues/4830)

Add a favicon directly encoded in base64 in the HTML header (not served through the webserver)
May be not the most pretty tasmo'art but compact (16x16, 16 grey levels).
Only cost 256 bytes of flash due to unishox compression (🙏 @s-hadinger )

Needed a small change in html compression tool to support string with `//` inside. => @s-hadinger 
(replaced the split() with a simple state-machine parser)

@gemu2015 could you please check that I've not broken SCRIPT_FULL_WEBPAGE please ?

image

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx. As the icon is actually black and white do you see a chance to lower it's color depth from 16 gray scale to 1 gray scale?

I don't use compression so for me it adds 400+ bytes bogus information.

**Comment by s-hadinger** [comment]
Awesome!

**Comment by s-hadinger** [comment]
Black and white would make it ugly since there would be no dithering. 
What about a #ifdef?

**Comment by arendst** [comment]
I love #ifdef.

**Comment by barbudor** [comment]
Hi @arendst 
Reduced to 1 bit which move the HTML cost from 488 down to 328 (-160 bytes)
No gain on compressed, still 256 bytes.
Aliaising is not as bad as I would have expected
image
Indeed the browser or windows is doing some antialiaising on its own
image

I added `#ifdef USE_WEB_FAVICON`
But because compressor script ignore preprocessing it will work only for uncompressed.
When using unishox, favicon will always be included.

**Comment by arendst** [comment]
Thx. Will chk today

**Comment by InHi66** [comment]
i do it this way:

in xdrv_01_webserver.ino

i add at "const char HTTP_HEAD_STYLE3[]"

following 

</style>""" & vblf & "  ""<link rel='icon' type='image/gif' href='data:image/gif;base64,R0lGODlhEAAQAPABAAAAAAAAACH5BAUAAAEALAAAAAAQABAAAAIrjB8AyKjaGEwrUldlPpNv7BnPIy4ThFbdqX5JKDbZKsOvVuayyVsv6rMhCgA7'>""" & vblf & vblf

**Pull request merged**
