### PR TITLE
Need feedback: new sensors for Home Assistant discovery

### PR DESCRIPTION
**Pull request by effelle**
## Description:
This is not really a PR, but just a basic idea I had for adding some other things to HA MQTT discovery. 
Needing an example, I created a ready-to-use sensor that shows a combined SSId and RSSI value to keep on eye on low signals, issue I had in the past with core 2.5.x. 
The sensor was created directly using a `value_template`.

Screenshot_2019-09-13-15-50-11-984_com android chrome

Since is one of the sensor I use most, I thought could be interesting for others too. 
The code is not perfect and probably needs a revamp, but is good enough to explain what I'm doing. There could be other useful sensors to implement , like IP Address, a reset button or an uptime monitor. 

Now, I would like to know what you think: can we integrate this type of sensors into the firmware?

Post scriptum: the wifi sensor doesn't show up on discovery page under HA but is perfectly selectable as entity and I don't have errors in logs. No idea why. 

**Related issue (if applicable):** None

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [ ] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by effelle** [comment]
Since I fear it could be merged without a check from @arendst I prefer close it for now. Awaiting feedback from devs.

**Comment by effelle** [comment]
@arendst Theo do I have your bless? :D

**Comment by arendst** [comment]
You might know my HASS feelings ;-)

**Comment by effelle** [comment]
Indeed I know! I just need to know if it worth the time, since every sensor will add at least 20-30 lines of code.

**Comment by arendst** [comment]
It's not just the code. It's also the firmware image size.

Isn't there another possibility to get sensors in Hass?

**Comment by effelle** [comment]
Sure there is, in fact I don't understand why you merge this one since was just something to show you. 
I think I'll add some new YAML examples on our wiki.

**Comment by arendst** [comment]
I'll unmerge now ;-)

I was just in a merge flow.

**Comment by effelle** [comment]
better. I was not happy with the code format

**Pull request merged**
