### PR TITLE
Make USE_BLE_ESP32 the default for sensors.

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:

title says it all :)
## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by btsimonh** [comment]
ok, will check failure later.
looks like a genuine failure....

**Comment by arendst** [comment]
Before doing this I would like to make sure

- which file is ESP8266 only (Rename those files to ``xdrv_xx_function.ino``)
- which file is ESP32 only (Rename those files to ``xdrv_xx_ESP32_function.ino``)
- which file is both ESP8266 and ESP32 (Rename those files to ``xdrv_xx_function_ESP32.ino``)

**Comment by btsimonh** [comment]
sounds like a plan.  I'm happy to do this renaming and add to the PR?  pls confirm.

**Comment by arendst** [comment]
Yes. pls do.

pls rebase as I just changed "other" esp32 specific files including your xdrv_52 which has become xdrv_79. Use lower case naming.

**Comment by btsimonh** [comment]
never really got the hang of rebase, so new pr coming....

**Pull request closed without merging**
