### PR TITLE
enable Ethernet in all safeboot firmware (except c2)

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

Test of size increase of enabling Ethernet drivers in all safeboot firmwares except esp32-c2

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.7
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.0.4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by dkadioglu** [comment]
How is the status of this, will this be merged? As I just stumbled upon this, when I started an OTA update via LAN, and the ESP32 rebooted into safe boot and was not reachable anymore via LAN - took me some time to try it via Wifi. Would be nice to have this!

**Comment by nikito7** [comment]
https://github.com/arendst/Tasmota/discussions/14168#discussioncomment-10768987

**Comment by Jason2866** [comment]
C6 safeboot goes over the partition size limit when Ethernet is enabled

**Comment by nikito7** [comment]
> C6 safeboot goes over the partition size limit when Ethernet is enabled

Something changed. 
It worked some weeks ago.

Currently I only use S3

**Comment by Jason2866** [comment]
@nikito7 Yes, nearly every day something is changed in or around Tasmota ;-)

**Comment by nikito7** [comment]
I made a new variant. I don't know a better way too.

At least a warning it's need in ota upgrade page.

How to force factory firmware to include my safeboot?

```
[env:tasmota32s3eth-safeboot]
extends                 = env:tasmota32_base
board                   = esp32s3-qio_qspi
board_build.app_partition_name = safeboot
build_flags             = ${env:tasmota32_base.build_flags}
                         -DFIRMWARE_SAFEBOOT
                         -DHAN_S3_ETH
                         -DUSE_SPI
                         -DUSE_ETHERNET
                         -UETH_TYPE
                         -DETH_TYPE=8
lib_extra_dirs          = lib/lib_ssl, lib/libesp32
lib_ignore              = ${safeboot_flags.lib_ignore}

...

[env:tasmota32s3eth]
extends                 = env:tasmota32_base
board                   = esp32s3-qio_qspi
build_flags             = ${env:tasmota32_base.build_flags}
                         -DFIRMWARE_TASMOTA32
                         -DHAN_S3_ETH
                         -UETH_TYPE
                         -DETH_TYPE=8
lib_ignore              = ${env:tasmota32_base.lib_ignore}
                          Micro-RTSP
                          epdiy
```

This work except factory bin. 

I have to replace safeboot manually with esptool

**Comment by nikito7** [comment]
I still recommend wifi for initial setup.

Some things are dependent on wifi.

Then:

autoexec.be 
```
tasmota.cmd('Wifi 0')
```

**Comment by sfromis** [comment]
Instead of simply `Wifi 0`, you might want the extra resilience from having Wifi again in case of Ethernet not available for whatever reason.
https://tasmota.github.io/docs/Berry-Cookbook/#ethernet-network-flipper

**Comment by s-hadinger** [comment]
I will try to find some room for C6

**Comment by Jason2866** [comment]
@arendst May merge now? If we get in trouble we can disable IPv6.

**Pull request merged**
