### PR TITLE
extra char size in mqtt_host

### PR DESCRIPTION
**Pull request by fzoccara**
In case of nead of some extra char size in mqtt_host configuration. :)

### CODE REVIEW

**Comment by ascillato** [comment]
Hi, this change is backwards incompatible. Sorry. If someone updates using this, their config will be scrambled.

**Comment by ascillato2** [comment]
Sorry, it can't be merged.

Anyway, thanks for sharing your ideas.

**Comment by fzoccara** [comment]
You are 100% right! Better to generate a shorter url for mqtt broker instead!
Sorry for not having thinking about this incompatibility before.. :)
Best.
Francesco.

**Comment by andrethomas** [comment]
Another thing to consider is just using the ip address - Depending on a DNS name adds running the risk of not resolving due to DNS servers being down whereas this could have been avoided by just using the ip address... just a thought.

**Pull request closed without merging**
