### PR TITLE
added pl-PL.h, platformio.ini, Please add my device "TasSupla-RLPB",   // RL_PB_TASMOTA hardware (ESP8266)

### PR DESCRIPTION
**Pull request by roblad**

### CODE REVIEW

**Comment by roblad** [comment]
pl-PL.h updated and adding 1 more device

**Comment by roblad** [comment]
added PL to platformio.ini

**Comment by roblad** [comment]
Small correction of language errors and TasSupla-RLPB descriptions added

**Comment by roblad** [comment]
0,                 // GPIO00 Flash jumper

**Comment by arendst** [comment]
As I see no real different between your new device and the already present Supla Espablo I will not add it. It's a waste of precious code space.

**Comment by roblad** [comment]
Ok,

But language PL translation is ready I think you can marge.

**Comment by arendst** [comment]
It's merged in the latest release this morning.

**Pull request closed without merging**
