### PR TITLE
Add Zigbee web ui widget for Lights

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Display the latest known status of Zigbee lights in the web UI console.

Example: white cold/warm light and Switch
CT Light

Example: RGB light
RGB Light

Displayed parameters:
- On/off status
- Brightness (Dimmer)
- White Color temperature in *K, or in Mireds in tooltip (pass the mouse over)
- RGB color at full brightness in `#RRGGBB` hex format

The UI will either display all reported attributes, or only the relevant attributes if you used `ZbLight` to set the number of channels. Note: some devices report more attributes than they can actually handle (OSRAM switch reports a Dimmer, IKEA White bulb reports Color information unrelated to CT).

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by MattWestb** [comment]
Your devices looks nice in the web GUI !!
Is it the IKEA the old LL RGBWW you have ?
And the WS is ZB3 one ?

Good work done !!!

**Comment by s-hadinger** [comment]
The IKEA is "TRADFRI bulb E27 WS opal 980lm" white cold/warm. The RGB above is simulated to show the rendering on the UI. The sensor is a Xiaomi Temp/Humidity/Pressure sensor. The OSRAM Plug is "Plug 01" model.

**Comment by MattWestb** [comment]
Still looks great also then "simulated"  !!
I have one old RGBWW but its in "production" in deCONZ and its little expensive (for IKEA).
I like the OSRAM outdoor plug but have not buying one then its looks having much problem with rooting and end device handling so no Zigbee on balcony :-((

By the way, its looks like Adminiuga have finding the problem in bellows with ZB3 devices and working to implanting it without braking old installations.

**Comment by MattWestb** [comment]
Looks like its working well with only putting the lights in the groups and config 2 channel for the CT ones. 
Reporting is not done so then changing with the remote its not being updated then i was tooooo lazy for testing that.
Z2T06

**Comment by s-hadinger** [comment]
Normally when a remote sends a command, Z2T requests the new status to the bulb a short while after. Does it work for you?

Btw what is the ZB3 problem Adminiuga is having?

**Comment by MattWestb** [comment]
I have making zblisten to the group of the old motion sensor and 2 lights and z2t is catching the on command but not "calculating" the off command (that is understanded).
The groupe 0 have the new motion sensor and the E1743 in it and 2 lights. Then using the E1743 the status in web ui is not updated form the lights. But i have not programming anny reporting of on/off (power) and level clusters for the lights. If sending groupe power command from z2t the lights in both groups is being updated. Probably only attribute reporting is needed for the lights.

bellows is the keystable storage for install codes joined devices / "well known code" joined devices that's having problems.  I have pairing all my test devices and its working but not for normal users if deleting / rejoining devices then the keys is not easy updated in the key store and the devices is leaving (false TC-link key from obsolete key in storage then ZB3 devices requesting updating there link key).

**Comment by s-hadinger** [comment]
@MattWestb I understand. It should be possible to configure the bulbs for attribute reporting whenever there is a change. I will try with my IKEA bulb (it works already with OSRAM plug)

**Pull request merged**
