### PR TITLE
Adds driver for TC74

### PR DESCRIPTION
**Pull request by mloftis**
## Description:

Adds a driver for the TC74 I2C temperature sensor. 

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by mloftis** [comment]
Not that while I did stuff in ifdef's for Domoticz and KNX, they are untested, cribbed from the DS18x20 support.

**Comment by arendst** [comment]
Bump

**Comment by mloftis** [comment]
Bump

**Comment by jeroenst** [comment]
@arendst what must be done in order for this pull request to be merged?

**Comment by arendst** [comment]
It needs some basic changes. I'll do it now.

**Comment by jeroenst** [comment]
@arendst nice, Can I help with any other open PR?

**Comment by mloftis** [comment]
I'm also still watching. Let me know if there's anything I can do @arendst

**Comment by arendst** [comment]
Merged just now with some changes.

**Comment by jeroenst** [comment]
Thanx!

**Pull request closed without merging**
