### PR TITLE
Replace ellipsis

### PR DESCRIPTION
**Pull request by SteWers**
## Description:
Replace ellipsis in most common files
## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Without looking at the code I'm quite sure your character is not an utf-8 (ascii) character and hence will use more than one byte.

**Comment by SteWers** [comment]
Yes, you're right. In UTF-16 it is 0x2026 and in UTF-8 0xE2 0x80 0xA6. So the code isn't smaller, but it looks better in the output…

**Comment by arendst** [comment]
Code size over cosmetics ;-)

**Comment by SteWers** [comment]
OK, but the code size is the same. From 0x2E 0x2E 0x2E to 0xE2 0x80 0xA6.

**Comment by arendst** [comment]
But I don't like the cosmetics.

**Comment by arendst** [comment]
And my legacy tools (like Termite) hate it too:
```
14:20:47.049-029 MQT: Attempting connectionâ€¦
```

**Comment by SteWers** [comment]
Uhh, that's bad. In VS and Teraterm the serial output is OK.

**Comment by sfromis** [comment]
I'd say that anything which replaces standard 7-bit (or maybe 8-bit) ASCII by use of more specialized Unicode characters should be avoided, unless there is a **very** good reason. Which there is not in this case, and personally I do not even think that it looks better.

And while I agree that Unicode should be used widely when i18n is a possible issue, replacing any character codes (except for 7-bit US-ASCII giving the same UTF-8 "encoded" data), there still are lots of tools or encoding specifications needing to be upgraded to painlessly support Unicode in all weird tools relevant to a development toolchain.

**Pull request closed without merging**
