### PR TITLE
Allow non-admin user handling on web interface

### LINKED ISSUE #5719: Allow multiple roles on web interface (ex: read-only)
**Have you look for this feature in other issues and in the wiki?**

It is related to #1550, but I that ticket was closed due to inactivity, not because it was thoroughly thought through. Not knowing if opening a new issue, or appending to that closed ticket is better, I decided to open a new one. Feel free to correct me.

**Is your feature request related to a problem? Please describe.**

The web interface knows only 1 role: admin. I have 2 issues with that:
1. Vulnerability:
  * Context: We do not have SSL, so everything web server related is in the clear (on the LAN). 
  * Problem: If one wants to secure the device, one has to set a web admin password. However, once we have set that password, we can also no longer read from or interact with the device via the web interface. Therefore: we are required to use that admin password also for reading sensors and writing to actuators, which we do much more often than undertaking admin activity. Thereby, we are radically increasing opportunities to sniff the admin password. And once you have the admin password, you can do all kinds of nasty things like changing the firmware.
2. Standard practice: It is standard practice on a lot of software to allow at least 2 roles: 'admin' and 'user' and/or 'view'

**Describe the solution you'd like**

Please allow 2 or 3 roles on the web interface. 
* Admin
* Viewer: read only on status info (ex: `/cm?user=viewer&password=XXXX&cmnd=status%208`)
* User: Interaction like switch toggle etc, but no admin actions like WiFi settings or firmware updates. I personally do not need that (yet), but I imagine some do, and I see the usefulness of it.

**Describe alternatives you've considered**

Other channels than web APIs. I know that Tasmota started out with MQTT. But I like it for the other features: it has OTA, is versatile, and it has a rather nice web interface. 
Just in case someone wants to tell me to use MQTT: I do not want to use MQTT anymore. Been there, done that, ran away screaming. I use WEB API (REST) wherever possible now. And before I get comments on that, I have created, and still maintain, a large scale commercial product that uses MQTT extensively. Seen enough of it to not want that anymore.

**Additional context**

I can help coding it, it is not that complicated. It gets more difficult if you want it to work on more than 2 roles, and/or on other endpoints than `/cm?cmnd=status{....}`, but even that is doable. If you factor out the authentication and authorization to one central location, we might even be able to lower the overall code size. And it would raise the config size by only a couple of bytes (20 bytes or so per role).

### PR DESCRIPTION
**Pull request by hb020**
## Description:

**Related issue (if applicable):** fixes #5719, option iii)

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

## Impact:

* This change adds 208 bytes to "sonoff.bin".
* Added a new variable to settings, hence the minor version change from ...9 to ...10.

## How to test:
(note on "restart browser" below: that is needed to flush the user/password. ALL browser windows need to be closed. Basic Authentication is primitive.. )

* Set an admin web password (/configuration/other configuration/web admin password), but leave user password empty
* Restart browser
* Go to device main page
* TEST: the main page should be limited in functionality now, close to how "Webserver 1" behaves ( although now one can get back to full functionality via the web alone.)
* Click on the "configuration" button, or request any other valid page (/co, /cm,...)
* TEST: it should ask for a login now
* Enter "admin" and the password set for "admin"
* TEST: access should be given to full functionality now.
* Set the user password
* Restart browser
* Go to device main page
* TEST: it should ask for a password now
* Enter "user" and the password set for "user"
* TEST: the main page should be limited in functionality now, like above.
* Click on the "configuration" button, or request any other valid page (/co, /cm,...)
* TEST: it should ask for a login now. If you do that too slow, the browser may say "401", as that is the result of the home page refresh functionality intervening. Just Reload then.
* Enter "admin" and the password set for "admin"
* TEST: access should be given to full functionality now.
* Execute "webserver 1" command (MQTT or web command) and let the device reset
* Restart browser
* Go to device main page
* Enter "user" and the password set for "user"
* TEST: Only limited functionality should be available now. 
* Restart browser
* Go to device main page
* Enter "admin" and the password set for "admin"
* TEST: Only limited functionality should be available now. 
* Optional: if you want to go back to "webserver 2" mode, do so via MQTT or a full reflash.
* Do a fresh install of the device, with WiFi setup and all.
* TEST: that should be unchanged and work without problems

## Things that might need improvement:

* Translations for  D_WEB_USER_PASSWORD (especially German, not happy with that translation)
* When upgrading, the "user" password is empty. One might not want that. Should I set it the same as the admin password?
* Explanations in the wiki about how this works (I can do that, once the PR has been approved), especially 
  * the user names "admin" and "user", that are hard coded, and are mostly not hinted at in the various translations.
  * "webserver 1": that mode cannot be reversed via the web interface (nothing changed with that, but it is not noted in the Wiki, and might be confusing). 

## Other remarks:

* for this PR, I did a large cleanup of all places where authentication was done, as there were code and functionality duplications.
* There is no "UI 'Lock down' button", as was mentioned in the ticket. Not needed. Just the additional "user" profile that was mentioned.

## New functionality:

* Two users can be used and be assigned their own password:
  * admin: access to all functions.
  * user: access only to the home page, and interaction with devices. No configuration, no firmware updates.
* When upgrading from older firmware, the user password is set as empty, meaning: no authentication is needed for user (non-admin) level access. NOTE: This may not be wanted. 
* Modified home page and config screen, see below, and see explanations of the screens.
* The "UserPassword" command has been added, acting on the user password, behaving like the "WebPassword" command that acts on the admin password.
* "webserver 1"/"HTTP_USER" mode is accessible to both admin and user. 

## Screen captures:

**Home page, "admin" logged in** (as before):
Screenshot 2019-05-05 at 17 48 34

**Home page, "user" logged in**:
Screenshot 2019-05-05 at 17 49 08
The bottom button will ask for the admin password, as the "user" has no access to configuration. That button is there so that admins have an easy way to log in as "admin". Please note that the authentication method used by Tasmota (Basic Authentication) does not allow web server control over logging out; it is al controlled by the browser.

**Other Configuration screen**:
Screenshot 2019-05-05 at 19 27 41
Note the added "User password" field.

### CODE REVIEW

**Comment by phiten** [comment]
#5719

**Comment by hb020** [comment]
Since I submitted this PR, I have made an effort to keep this PR free of merge conflicts. Now the dev branch has moved on so far that I need to make a more significant effort (the config version changed, needing several code changes on my side). Hence, I would like to ask the question: "Is it worth it?". 
Is there any chance that this PR gets accepted any day soon? Or is the proposed change too much and should I make it work differently? If so, I will adapt. But if you consider this having a too low chance of getting accepted, please tell me so, and I will withdraw.

**Comment by arendst** [comment]
Thx for the effort but...

I suggest stop keeping this up-to-date as it won't be implemented soon.

**Comment by hb020** [comment]
OK, I will keep this PR open, and can update it when you are ready for it.

**Pull request closed without merging**
