### PR TITLE
Gzip firmware files...

### PR DESCRIPTION
**Pull request by Jason2866**
with PlatformIO in folder `build_output`

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1 and stage
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by claybar** [comment]
I am getting an error with this script @Jason2866 :
`
pio run -e tasmota

...

Building .pioenvs/tasmota/firmware.bin
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
DATA:    [======    ]  58.1% (used 47584 bytes from 81920 bytes)
PROGRAM: [======    ]  56.4% (used 577516 bytes from 1023984 bytes)
Creating BIN file ".pioenvs/tasmota/firmware.bin" using ".pioenvs/tasmota/firmware.elf"
bin_map_copy([".pioenvs/tasmota/firmware.bin"], [".pioenvs/tasmota/firmware.elf"])
bin_gzip([".pioenvs/tasmota/firmware.bin"], [".pioenvs/tasmota/firmware.elf"])
*** [.pioenvs/tasmota/firmware.bin] TypeError : compress() argument 1 must be string or read-only buffer, not bytearray
Traceback (most recent call last):
  File "/Users/phil/.platformio/packages/tool-scons/script/../engine/SCons/Action.py", line 1054, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/Users/phil/Documents/Home/Tasmota-arendst/pio/gzip-firmware.py", line 25, in bin_gzip
    f.write(bindata)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 240, in write
    self.fileobj.write(self.compress.compress(data))
TypeError: compress() argument 1 must be string or read-only buffer, not bytearray
============================================================ [FAILED] Took 15.99 seconds ============================================================
`

**Comment by claybar** [comment]
This is likely fixed in #7461

**Comment by s-hadinger** [comment]
It is.

**Comment by Jason2866** [comment]
@claybar  You should upgrade Python to a supported version anyway ;-)

**Pull request merged**
