### PR TITLE
Set accepted filename extensions for firmware uploads

### PR DESCRIPTION
**Pull request by scop**
## Description:

Makes it easier to locate appropriate files to upload.

https://html.spec.whatwg.org/multipage/input.html#attr-input-accept

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
Nice one, I didn't know this option. However we need to have different values for ESP32 which accepts only `.bin`.

Can you please gate with `#ifdef ESP8266` with the current value `#else` only `.bin`

**Comment by arendst** [comment]
The same upload mechanism is used by other file types like .hex (EFM8BB1 RF-bridge and TasmotaClientfiles) and .ota (Zigbee bridge).

**Comment by scop** [comment]
Ok, maybe something like e6f12ae4db0c272b3e6a45721e77e4120cd0aa68? Limited to ESP8266 and ESP32 there, didn't find `define`s to use for the other mentioned scenarios. And I don't know if this code is being used in too many different scenarios for something like this being easily feasible in the first place.

**Comment by arendst** [comment]
But both ESP8266 and ESP32 need to support .hex too and the ESP32 needs .ota.

**Comment by sfromis** [comment]
Looks like the support for Tube'z Zigbee EFR32 includes uploading a `.gbl` file. Other features might come along with further extensions....

**Comment by s-hadinger** [comment]
> Looks like the support for [Tube'z Zigbee EFR32](https://github.com/arendst/Tasmota/tree/master/tools/fw_TubeZigbee_efr32) includes uploading a `.gbl` file. Other features might come along with further extensions....

Indeed. Actually `.gbl` is the official extension. We renamed as `.ota` for Zbbridge as a convenience. We can use `.ota` for TubeZB as well and drop `.gbl`

**Comment by scop** [comment]
I don't know how the mentioned devices (EFM8BB1 RF-bridge and TasmotaClient, Zigbee bridge, Tube'z Zigbee EFR32) translate to `#define`s we could use here, but 857b3be1c733fa7fa57a637fc290b9b3230f65f5 updates to follow the note in https://github.com/arendst/Tasmota/pull/16875#issuecomment-1288076012.

If this still isn't quite right, perhaps it would be more productive if someone who actually knows what they're doing could either enumerate the complete set of defines and corresponding extensions for me to add, or go ahead and just push the fixes to my branch here (it's open for contributors), rather than me continuing with the guesswork :)

**Comment by arendst** [comment]
unstale

**Comment by arendst** [comment]
Thx!

Just merged an adapted version of your code.

**Pull request closed without merging**
