### PR TITLE
Make provision to store experimental drivers

### PR DESCRIPTION
**Pull request by andrethomas**
Create a new folder named experimental so that we can place experimental drivers used for testing or other use cases which are not included in the development codebase but may be useful to some users who like to self compile and tinker with drivers that were created for debugging purposes but will never be merged into the compiled codebase releases.

### CODE REVIEW

**Comment by arendst** [comment]
That's why I introduced the sonoff-tasmota-playground repository.

Once in sync with this repository it could be used for your drivers.

Now if we only could get that repository in sync with this one...

**Comment by andrethomas** [comment]
Hmm, good idea. Let me think about how to do that - do I have write access to it with my other userid?

**Comment by andrethomas** [comment]
It would overwrite any changes made to existing files though...

**Comment by arendst** [comment]
I did sent an inviite some minutes ago...

**Comment by arendst** [comment]
The current state is as of october so no problem updating it now once.

**Comment by andrethomas** [comment]
Updated

**Comment by andrethomas** [comment]
Now need to find a way to automate it... closing this one for now

**Comment by andrethomas** [comment]
Think I am able to sync it now - just did and it worked.

**Pull request closed without merging**
