### PR TITLE
Completed display.ini for M5Stack Dial

### PR DESCRIPTION
**Pull request by ingbenna**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ V] The pull request is done against the latest development branch
  - [ V] Only relevant files were touched
  - [ V] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ N/A] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [ V] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [ V] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Please use UniversalTouch settings for Touch section.
The dedicated drivers are in status deprecated. When changes to a display.ini are done the touch section should be migrated to the Universal driver

**Comment by Jason2866** [comment]
@ingbenna please update the display.ini using the UTouch driver.
The dedicated driver will be removed soon. The are deprecated.

**Comment by ingbenna** [comment]
Hi @Jason2866, thanks for the quick feedback.

There is any configuration guide for migration except the official Tasmota documentation? I tried it but doesn't works and the only difference is the absence of I2C ports declaration.

**Comment by ingbenna** [comment]
Hi @Jason2866, I used the example of FT5206 and with some minor modification it works.
Thanks again for your beautiful work, I'll make a new PR.

**Comment by Jason2866** [comment]
Great, you provide a PR using the actual UTouch driver

**Pull request merged**
