### PR TITLE
Add KNX Protocol support

### PR DESCRIPTION
**Pull request by ascillato**
# Sonoff-Tasmota KNX

[Sonoff-Tasmota_KNX](https://github.com/ascillato/Sonoff-Tasmota_KNX) is a modification for [Sonoff-Tasmota](https://github.com/arendst/Sonoff-Tasmota) to add a basic functionality of the [KNX IP Protocol](https://www.knx.org/knx-en/index.php).

## KNX Explanation ##

[](https://www.knx.org/knx-en/knx/association/what-is-knx/index.php)

The [KNX IP Protocol](https://www.knx.org/knx-en/knx/association/what-is-knx/index.php) is an _international open standard_ for smart homes and smart buildings automation. It is a decentralized system. Each device can talk directly to each other without the need of a central controller or server. Any panel or server is just for telesupervision and for sending requests. KNX IP Protocol uses a UDP multicast on _224.0.23.12 : 3671_, so there is no need for a KNX Router unless you want to communicate to KNX Devices that are not in the WIFI Network (Twisted Pair, RF, Powerline).

Each device has a physical address (like a fixed IP) as **1 . 1 . 0** and that address is used for configuration purposes.

Each device can be configured with group addresses as **2 / 2 / 1** and that address can be used for sending/receiving commands. So, for example, if 2 devices that are configured with the **2 / 2 / 1** for turning on/off their outputs, and other device send _Turn ON_ command to **2 / 2 / 1**, both devices will turn on their outputs.

## Integration ##

Several home automation systems have KNX support. For example, [Home Assistant](https://github.com/home-assistant/home-assistant) has a [XKNX Python Library](https://github.com/XKNX/xknx) to connect to KNX devices using a KNX Router. If you don't have a **KNX Router**, you can use a **Software KNX Router** like [KNXd](https://github.com/knxd/knxd) on the same Raspberry Pi than Home Assistant. KNXd is used by Home Assistant for reading this UDP Multicast, although KNXd has other cool features that need extra hardware like connect to KNX devices by Twister Pair, Power Line or RF.

If you use the ETS (KNX Configurator Software) you can add any Sonoff Tasmota KNX as a dummy device.

## Requirements ##

* [ESP KNX IP Library (async-udp branch)](https://github.com/envy/esp-knx-ip/tree/async-udp)
* [ESPAsyncUDP Library](https://github.com/me-no-dev/ESPAsyncUDP). This Library is used by ESP KNX IP Library. 

A copy of both libraries is available at:
* https://github.com/ascillato/Sonoff-Tasmota_KNX/tree/development/lib/esp-knx-ip-async-udp
* https://github.com/ascillato/Sonoff-Tasmota_KNX/tree/development/lib/ESPAsyncUDP-master

## Usage Examples ##

There are multiple possible configurations. Here are explained just a few as example. The options for selecting relays, buttons, sensors, etc. are only available if were configured on _Configure Module Menu_.

To configure KNX, enter on the Configuration Menu of Sonoff-Tasmota and select Configure KNX.

config_menu

knx_menu

**1) Setting Several Sonoff to be controlled as one by a Home Automation System:**

We can set one of the group address to be the same in all the devices so as to turn them on or off at the same time.
In this case, so as to inform the status of all the relays to the Automation System, just one of the devices have to be configured as the responder. If you use the same Group Address for sending and receiving, you have to take into account not to make loops.

DEVICE 1

DEVICE 2

**2) Setting 2 Sonoff to be linked as stair lights:**

We can set one device to send the status of its output and another to read that and follow. And the second device can send the status of its button and the first device will toggle. With this configuration we can avoid to make a loop.

DEVICE 1

DEVICE 2

**3) Setting a button as initiator of a scene:**

Just setting one device to send the push of a button, and the rest just use that value to turn them on. In this case, there is no toggle. Every time the button is pushed, the turn on command is sent.

DEVICE 1

DEVICE 2

**4) Setting a Temperature sensor:**

We can configure to send the value of temperature or humidity every teleperiod. This teleperiod can be configured. See Sonoff Tasmota [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands). It is recommended also to set the reply temperature address.

## Development Road Map ##

**For Sonoff-Tasmota_KNX:**
- [x] Add Web Menu
- [x] Add Feature to Receive telegrams and modify Relay Status
- [x] Add Feature to Receive telegrams from multiple Group Addresses to modify just one relay status (useful for scenes)
- [x] Add Feature to Send telegrams of relay status change
- [x] Add Feature to Send telegrams of one relay status to multiple Group Addresses (useful for scenes)
- [x] Add Feature to Send telegrams of button pressed
- [x] Add Feature to receive telegrams to toggle relay status
- [x] Add Feature to read Temperature, Humidity from Tasmota
- [x] Add Feature to send Temperature, Humidity by a set interval (tasmota teleperiod)
- [x] Add Feature to receive command to read temperature, Humidity
- [x] Add Feature to recognize Tasmota config to show the same number of relays, buttons, etc.
- [x] Add Feature to Save Config
- [x] Add Feature to Load Config
- [x] Add Log Info
- [x] Complete all the language files with keys

## Modifications to Sonoff-Tasmota ##

* Adding the file _/sonoff/xdrv_10_KNX.ino_ 
* Add the entry `#define USE_KNX` on _/sonoff/user_config.h_
* Add entries to the file _/sonoff/webserver.ino_
* Add entries to the file _/sonoff/sonoff.ino_
* Add entries to the file _/sonoff/sonoff.h_
* Add entries to the file _/sonoff/settings.h_
* Add entries to sensor files
* Add entries to language files

Up to now, enabling KNX uses +23k of code and +3k3 of memory.

There is **NO CONFLICT** with MQTT, Home Assistant, Web, etc. Tests show fast response of all features running at same time.

## Contributors ##

* Adrian Scillato @ascillato
* Sisamiwe @sisamiwe - Thanks for the guide on using KNX.
* Nico Weichbrodt @envy - Thanks for the patience and help with the modifications to ESP_KNX_IP.

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

Made some changes to this PR to update to new API version of ESP-KNX-IP.

Travis Check Fails because Travis don't have the libraries:

* [ESP KNX IP Library (async-udp branch)](https://github.com/envy/esp-knx-ip/tree/async-udp)
* [ESPAsyncUDP Library](https://github.com/me-no-dev/ESPAsyncUDP). This Library is used by ESP KNX IP Library.

**Comment by ascillato** [comment]
Great! :+1:

**Comment by MatzeJoerling** [comment]
Nice, 
i have about 80 KNX devices. at now i have nodered sitting between knx and tasmota. So this PR will save me some nodes. 
What i dont get from you PR, where do i configure my knx router or do you use multicast?
BTW, KNX Address is not like MAC, it is like IP. You can route knx (multiple lines with coupler ...).

will try this as fast as possible.

**Comment by ascillato** [comment]
Yes. It uses multicast to the knx ip default address defined on the knx ip
standard. So there is no need to configure a router.

And yes, the physical address is like a fixed IP. I just say like a MAC
because I was trying to explain that is fixed and attached to a particular
device in contrast to a group address that has nothing to do with the
physical one. I think is better explained as you say. I will update the
readme. Thanks.

**Comment by arendst** [comment]
I simply like your changes to readme.md 👍

**Comment by arendst** [comment]
Adrian,

considering all the work you have put into this I propose to keep it a separate project. This also leaves your ReadMe and contribution in place.

In that case I would like to have a link in my wiki to your environment.

**Comment by ascillato** [comment]
Hi,

I would love to see KNX in on your Tasmota. I'm using this a lot. If you see the files seems a lot but is just adding the 2 libraries, some entries on some files like settings, webserver, user config and the xdrv_11_KNX.ino

By now, I'm keeping the repo https://github.com/ascillato/Sonoff-Tasmota_KNX in sync with yours just to make it easy the integration to your repo.

Hope you consider adding this feature. I prefer helping directly to your repo than mantaining a separate repo.

**Comment by arendst** [comment]
Convinced...

**Comment by ascillato** [comment]
The intention of the readme of https://github.com/ascillato/Sonoff-Tasmota_KNX is then to be the wiki of the knx of yours

**Comment by ascillato** [comment]
thanks :+1:

**Comment by arendst** [comment]
I'm currently integrating so pls stop updating this PR for a moment.

Running against some minor issues but will resolve myself.

**Comment by arendst** [comment]
Found the Xdrv10 error (obvious) but I guess the callback KNX_CB_Action has to be defined somewhere else...

**Comment by ascillato** [comment]
Ok. No more updates.

Yes, Xdrv10 should be Xdrv11. Sorry.

The callback definition can be anywhere but needs to be defined so the
esp-knx-ip library can use it. I put it on the driver file so if the user
don't use KNX, the definition, and all the KNX is not included. If you find
better place, please  do it.

>

**Comment by arendst** [comment]
Still having errors compiling with platformIO where Arduino IDE runs just fine. 

Strange thing is that even when I comment out USE_KNX in user_config.h platformio still complains about the callback. I have to remove the file xsns_11_knx.ino to get the compile going again.

Well enough for today.

**Comment by arendst** [comment]
Been trying again to compile but keep getting the below error on different PlatformIO hardware, both PC and laptop:
```
Compiling .pioenvs\sonoff\lib065\ESP8266WiFi\WiFiClientSecure.cpp.o
R:/VisualStudio/arduino-esp8266/Tasmota/Assists/ascillato/Sonoff-Tasmota_KNX-development/sonoff/sonoff.ino:533:30: error: variable or field 'KNX_CB_Action' declared void
if (data_len > 0) {
^
R:/VisualStudio/arduino-esp8266/Tasmota/Assists/ascillato/Sonoff-Tasmota_KNX-development/sonoff/sonoff.ino:533:20: error: 'message_t' was not declared in this scope
if (data_len > 0) {
^
R:/VisualStudio/arduino-esp8266/Tasmota/Assists/ascillato/Sonoff-Tasmota_KNX-development/sonoff/sonoff.ino:533:42: error: expected primary-expression before 'void'
if (data_len > 0) {
^
Compiling .pioenvs\sonoff\lib065\ESP8266WiFi\WiFiServer.cpp.o
*** [.pioenvs\sonoff\src\sonoff.ino.cpp.o] Error 1
```
There are two things wrong here:
- With every platformio version update I loose functionility. One time when a source error existed I received an error message with the correct file name and line number. It even allowed to jump to it by clicking on the error link. Since some versions ago this seems to have gone and all I get now is an error in the accumulated sonoff.ino file with a line number in that file but the accumulated sonoff.ino file is  removed by platformio compilation so apart from a message that something is wrong in the source I get no real location information anymore. I guess it's a platformIO issue as it happens on both my PC and my laptop.
- Then there is the real compilation error in line 54 in your file xdrv_11_KNX.ino regarding function announcement. Again it fails on both my PC and laptop so I guess You must have had it too...

Any advice is welcome.

**Comment by ascillato** [comment]
I was using just Arduino. I will install platform.io to help you with this
issue. One thing to try is to put the callback definition outside the file
like in a knx.h

If doesn't work we can use the extern C { approach

I will install platform.io and test all this.

**Comment by arendst** [comment]
Right. By moving the callback to sonof_post.h, as I did for the WifiWpsStatusCallback, but outside the C { approach (inside fails) it compiles fine.
```
#ifdef USE_KNX
#include <esp-knx-ip.h>
void KNX_CB_Action(message_t const &msg, void *arg);
#endif  // USE_KNX

#define USE_DHT                               // Default DHT11 sensor needs no external library
```

But... the strange thing is that in all cases when I comment out the define USE_KNX it keeps complaining about the callback KNX_CB_Action as before. Very weird...

**Comment by arendst** [comment]
Just released most of your knx code except for the xdrv file as it prohibits compilation when present...

**Comment by ascillato** [comment]
Hi,

I'm testing on Platform.io and have the same output.

I found on http://docs.platformio.org/en/stable/librarymanager/ldf.html#ldf-mode that PIO don't check for **preprocessor conditional syntax**.

I tried the `lib_ldf_mode = chain+` on _platformio.ini_ so as to make platform.io check for that, but no luck.

This platform.io bug is explained on https://github.com/platformio/platformio-core/issues/801#issuecomment-252447178

Will continue looking for a workaround...

**Comment by ascillato** [comment]
Found a solution!!!!!

on _sonoff_post.h_ just change to:

```
//#if defined(USE_KNX)
#include <esp-knx-ip.h>
void KNX_CB_Action(message_t const &msg, void *arg);
//#endif  // USE_KNX
```

This don't use extra KB.

With `//#define USE_KNX` commented out:

Comparing the normal tasmota without any line that includes <esp-knx-ip.h> and the one with this change there is no difference.

Now compiles :+1:

**Comment by ascillato** [comment]
Tested on Arduino and Platform.io.

Now, in both systems it compile and work.

**Comment by arendst** [comment]
Well done 👍 and thnx for the kudo too ;-) You earned it just as much.

Just tested it and it seems to compile fine. Will now continue with sensor integration.

**Comment by arendst** [comment]
Released. Pls add your info to the wiki and close this one so if you have any updates to the released version it makes things easier to find.

**Comment by reloxx13** [comment]
Heya,

i get this issue with platformIO now:
```

Compiling .pioenvs\sonoff-DE\lib839\esp-knx-ip-async-udp-0.4.0.15\esp-knx-ip.cpp.o
lib\ESPAsyncUDP-0.21\src\AsyncUDP.cpp: In member function 'bool AsyncUDP::listenMulticast(ip_addr_t*, uint16_t, uint8_t)':

lib\ESPAsyncUDP-0.21\src\AsyncUDP.cpp:254:57: error: 'udp_set_multicast_netif_addr' was not declared in this scope
udp_set_multicast_netif_addr(_pcb, multicast_if_addr);
^
lib\ESPAsyncUDP-0.21\src\AsyncUDP.cpp:258:36: error: 'udp_set_multicast_ttl' was not declared in this scope
udp_set_multicast_ttl(_pcb, ttl);
^
Compiling .pioenvs\sonoff-DE\lib22b\Adafruit_SGP30-1.0.0.13\Adafruit_SGP30.cpp.o
*** [.pioenvs\sonoff-DE\lib091\ESPAsyncUDP-0.21\AsyncUDP.cpp.o] Error 1
 [ERROR] Took 13.92 seconds
```

With disabled KNX:
`//#define USE_KNX    `

**Comment by ascillato** [comment]
Made the PR #2487 to update Tasmota ReadMe with this requirement for compiling.

**Comment by ascillato** [comment]
Added KNX on the wiki

**Comment by reloxx13** [comment]
2.4.0)
- HUE Emulation still bugged
- WIFI Disconnects flooding my Router Logs
- WebUI very unresponsive
- Devices often does not to Alexa (cuz of Wifi DC ?)
=> Seems its the sleep/wifi_light_sleep, but its saves alot of money (see wiki energy saving).

coming 2.4.1)
- Devices still freeze with wifi_light_sleep (tested with latest git)

I would suggest to get 2.3.0 still working without KNX. I just commented out some lines in the lib to get it compiled, but this is a dirty fix :X

**Comment by ascillato** [comment]
Hi, I'm downgrading the esp-knx-ip library to use 2.3.0 so KNX will run on 2.3.0

I will make the PR soon

The fix will be just:

Delete ESPAsyncUDP library
Update ESP-KNX-IP library

No other change will be needed. And everything under ESP8266 v2.3.0

**Comment by reloxx13** [comment]
no way around to check if knx is commented in and only load the lib than? would w8 for theos feedback maybe he got an idea.

**Comment by ascillato** [comment]
PR #2492 to:

- Update ESP-KNX-IP library
- Delete ESPAsyncUDP library that is no longer used by ESP-KNX-IP library

Compiled and Tested under 2.3.0 with and without `#define USE_KNX`

**Comment by arendst** [comment]
Released just now.

**Comment by sisamiwe** [comment]
@ascillato 
I would like to say thank you. You have done a great job adding KNX support to tasmota.
Nevertheless I would also like to ask you, whether you see a chance to create a plugin for ESPEasy also to add KNX support?
What do you think?

**Comment by ascillato** [comment]
Hi,

Thanks :+1: 

For achiving this KNX support I have a lot of help from several persons including also you (@sisamiwe) and Nico (@envy) (https://github.com/envy/esp-knx-ip). Some features of the KNX Library were modified by Nico so as to be used like in here.

Now, with this driver, there is just a basic KNX IP support. With this KNX driver you can control relays and send buttons press, communicating device to device. It works, but there are some other needed features to be integrated and to be improved on both, Tasmota KNX Driver and ESP-KNX-IP Library that we are working on. After that, I will take a look at ESPEasy but will take me some time as I have to learn how that software work first.

Again, Thanks a lot and stay tunned for coming updates!

**Pull request closed without merging**
