### PR TITLE
update French translation

### PR DESCRIPTION
**Pull request by ThierryM**
Hi,
Thanks for your work and sharing. Here updated french file translation.
Regards,

Thierry

### CODE REVIEW

**Comment by localhost61** [comment]
@ThierryM 
Do you see accented vowels in the Webserver with French GUI? I'm using latest v5.12.0l and I don't see them under Firefox wether on Windows or Android. They are filtered to unaccented ones.

**Comment by ThierryM** [comment]
Hi,
Yes I see all the accents (even in capital letters). I'm under Firefox 59.0.2 in Ubuntu 16.04. See the attachment.
Regards
image

**Comment by localhost61** [comment]
Thank you.
It's weird, I will investigate my issue and try with default Tasmota settings.

**Comment by localhost61** [comment]
I agree with your changes but I would suggest furter more. What do you think about?
[fr-FR.zip](https://github.com/arendst/Sonoff-Tasmota/files/1914808/fr-FR.zip)

**Review by localhost61 — APPROVED** [review]

**Comment by ThierryM** [comment]
@localhost61 
Ok for your changes. As a result, I added 3-4 changes more. You can see in the new commit.

**Comment by localhost61** [comment]
Yes indeed ! I didn't see that one, but it was huge ;-) Cheers !
I was a bit worried with the current build fail, but we it's not due to fr-FR.h. <sight>

**Review by localhost61 — APPROVED** [review]

**Comment by localhost61** [comment]
@ThierryM 
Regarding my unaccented vowels it must be due to my Arduino IDE environment. I should try PlatformIO.
I cleared the device config, flashed the device and rebuilded project 5.12.0l in vanilla but  AP1 and fr-FR and got same result.
Webpage code source appears in UTF-8 with no accent. (?_?)

**Comment by localhost61** [comment]
-> [fr-FR.zip](https://github.com/arendst/Sonoff-Tasmota/files/1926499/fr-FR.zip)
This is an update for v5.012m, for new KNX strings and other cosmetics.
 I also  replaced kOhm/uF/um/us... with kΩ/µF/µm/µs. As UTF-8 is active, it shouldn't be a problem, we don't target an Arduino LCD, isn't it?

No build issue, but I couldn't test the rendering of KNX or MQTT as I don't use them. I don't know neither, how it behaves on a mobile phone with display resolution less than Full-HD. ;-)

**Comment by localhost61** [comment]
-> [fr-FR.zip](https://github.com/arendst/Sonoff-Tasmota/files/2006980/fr-FR.zip)
This is an update for v5.140a with SDM120 strings translated.

**Comment by localhost61** [comment]
I wonder why I can't upload an update for v6.01.1b as I used to do before !!?

_`Something went really wrong, and we can’t process that file. Try again.`_

**Comment by ascillato** [comment]
Sorry, not enough information provided to address your issue. Please, open a new issue with the troubleshooting template complete. Thanks.

**Comment by localhost61** [comment]
@ascillato 
Oh sorry, I was talking about fr-FR.lng that I can't upload on github.

**Comment by ascillato** [comment]
Ah, Ok.

Try this.

- Go, in this repository (https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/language/fr-FR.h), to the file _fr-FR.h_.
- Click edit (the pencil).
- Select everything and Paste your new translation (as text), OR edit just the entries needed.
- Click on preview to see if the changes are ok and if you did not delete any other entry needed.
- Click on propose file change (This will save your modifications in your own repository)
- Click on Make pull Request.

That's it. Then we can just review your work and merge to Tasmota  :+1:

**Comment by localhost61** [comment]
It's a bit overkill to fork for such a little change but I'll do that.

**Pull request closed without merging**
