### PR TITLE
LED Redux, Exposing Options through Web, Live Web Mode Switching

### PR DESCRIPTION
**Pull request by EphemeralPersistence**
Been procrastinating on this req... (while figuring bits out), so there are quite a few deviations..  
Serious apologies in advance for the bungle/bundle of work here. - or any GIT weirdness... 

Some suggestions - these coming from integrating this into home light switches..
(I'm concerned with the deviations that the switch I'm working with has from the sonoff devices.. I may get a sonoff to ref against) :

- **Module definition** and integration for the [KingArt light switch](https://github.com/EphemeralPersistence/Sonoff-Tasmota/wiki/KingArt-N1) series
- **LED blink pattern concept** (LEDRedux - the LED proved quite important for the module I was working with.. so this is where most of the work started.)
- **LED state definitions** based on use representing Activity,State and Power information
- **Global activity monitoring** through flag structure
- **Web mode switching** based on user login (and logout) - I've put the detail up [here](https://github.com/EphemeralPersistence/Sonoff-Tasmota/wiki/WebServer-Client-Mode-Switching); proof is coded with a temp user/password for 'user' 
- **Web scripting testing device 'up' state** before reloading & OTA (and some general web bits while getting a handle... translation chunks and consistency on my work def not withstanding)
- **Web MQTT en/dis-able** in the MQTT section
- Web options for : 
-- **Setting LED usecase** (Activity/Status/Power.. or none to disable) - bit masking for the LED
-- **Managing saving to flash of state** (useful.. esp for setting a default, and its a light switch - not really concerned with prev state as its managed by home integration - also just the option of reducing unnecessary flash writes.)
-- **Managing single button mode** (very useful after setup is complete to stop accidental fiddling!  instantaneous switch response is awesome, esp for a light switch :P)

Appreciate input, ideas and critique!

There's more needed to finish some of this.. def WIP

### CODE REVIEW

**Comment by ascillato** [comment]
Too many changes together. You modified a lot of files.

It is better and more readable if you make a separated pull request for every idea.

**Review by ascillato2 — CHANGES_REQUESTED** [review]
Please, separate each idea on differents Pull Requests
Please, update to latest version.

**Comment by EphemeralPersistence** [comment]
I agree.. will redo from start.

**Comment by EphemeralPersistence** [comment]
Sorry.. I've stared, fought and fought and come to the conclusion that GIT is as its name..
I'm just not up to speed enough on GIT yet to figure out how to unpick its commit system and even attempt a piece by peace merge...
Iol, I've made a right mess of it trying to figure a way.   

I did manage to update and merge with the head.. but I just am not bothered enough to create and then resplice in every change into each own branch and then submit a pull..   wasted a day figuring it out first of all even how!  and its not worth the time.  

Sorry guys, I'll maintain it separate.

**Pull request closed without merging**
