### PR TITLE
Add refresh telemetry command

### PR DESCRIPTION
**Pull request by Stevehans**
Adds a new command TelemetryRefresh which causes telemetry to refresh on the next second tick

### CODE REVIEW

**Comment by mkh595** [comment]
This is exactly what I am looking for. I can have set high teleperiod e.g. 300 but on demand generate MQTT tele/xxx/STATE message at any time from outside or by rule.

I implemented it in version 6.2.0, but why it says {"Command":"Error"} if command is known and message is raised?

```
07:44:34 CMD: TelemetryRefresh
07:44:34 MQT: stat/home236/RESULT = {"Command":"Error"}
07:44:36 MQT: tele/home236/STATE = {"Time":"2018-09-07T07:44:36","Uptime":"0T08:40:18","Vcc":3.163,"POWER":"OFF","PWM":{"PWM1":0},"Wifi":{"AP":1,"SSId":"mkh","RSSI":70,"APMac":"84:16:F9:A2:60:C8"}}
07:44:36 MQT: tele/home236/SENSOR = {"Time":"2018-09-07T07:44:36","Switch2":"OFF"}
```

**Comment by Stevehans** [comment]
Have you applied my patch as I don't believe the pull request was ever accepted?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mkh595** [comment]
I implemented changes which I see if I click on 'Update sonoff.ino' and 'Update i18n.h'.
Where can I see patch? Sorry but I am not familiar with PR on GitHub.

Thanks for help.

**Comment by ascillato2** [comment]
Thanks for sharing your ideas. It is a good one. By now, This PR is not going to be merged due to be rebased from the actual code of Tasmota. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

**Pull request closed without merging**
