### PR TITLE
Added Module for  Energy Monitoring  SP201 - Smart Plug Mini 2 in 1

### PR DESCRIPTION
**Pull request by balvant813**
Tuya based plug with energy monitoring - SP201 ([OrangeTech](https://www.amazon.com/Outlet-Compatible-Monitoring-Function-Required/dp/B079Q5W22B)) can be flashed with Tasmota-Sonoff via OTA described in [TUYA-OTA.](https://github.com/arendst/Sonoff-Tasmota/wiki/Tuya-OTA) This is  module configuration can operate both plugs (on/off, led light) and shows energy monitoring data.

### CODE REVIEW

**Comment by elzershark** [comment]
Work with this perfekt = https://amzn.to/2I2bguU
thank you very much

**Comment by Jason2866** [comment]
For supporting new devices (TUYA OTA flashing...) there will be a new general solution.
See https://github.com/arendst/Sonoff-Tasmota/issues/5177#issue-408445262

**Comment by andrethomas2** [comment]
Please see https://github.com/arendst/Sonoff-Tasmota/issues/5177#issuecomment-462439713

**Comment by DavinKD** [comment]
Thanks for figuring this one out.  I like to make the LEDs relays so I can decide what to use them for.  In my SmartThings device handler, I have a setting that lets you pick if you want the red led, blue led or both to turn on when the switch is turned on.

**Pull request closed without merging**
