### PR TITLE
add TMP112 support

### PR DESCRIPTION
**Pull request by cputoaster**
Seems to work for me with a TMP112AIDRLR, there is an offset of a few °C, should only be 0.5 °C. Don't know why.

### CODE REVIEW

**Comment by cputoaster** [comment]
Actually turns out it was just a bad test setup, with heat radiation from the flasher / power supply. Works fine.

**Comment by andrethomas** [comment]
You need to make provision for negative temperatures - see datasheet http://www.ti.com/lit/ds/symlink/tmp112.pdf - Refer to table 2 and its descriptive text below the table.

It appears to work similar to the LM75AD sensor with regard to negatives so you could borrow that method of conversion used in the LM75AD code.

Also, you need to add support for F - This is also demonstrated in the LM75AD driver using the M75ADShow function and the LM75ADGetTemp where it uses the configured temperature unit to perform the conversion automatically to either C or F depending on user config.

See https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/xsns_26_lm75ad.ino to see what I mean - perhaps a bit of restructuring and cleanup would be a good idea... just my 2 cents.

**Comment by andrethomas** [comment]
@arendst I see that - tried finding some just for testing purposes... can only find chips.

Also, I2C address conflicts with LM75AD.

**Comment by cputoaster** [comment]
FYI, I was using this for testing: http://wiki.aprbrother.com/en/ESP_Soil_Moisture_Sensor.html

I think this could help, but have to see when I have time: https://github.com/ControlEverythingCommunity/TMP112/blob/master/C/TMP112.c

**Comment by cputoaster** [comment]
How would you go about the address conflict? Just never compile with both of them? Or some elaborate detection?

**Comment by andrethomas** [comment]
How would you go about the address conflict? Just never compile with both of them? Or some elaborate detection?

The simplest would be to check if it was defined and then undefine it with a warning that it has been disabled. Its unlikely that someone would use both sensors at the same time but I am not sure how the LM75AD will respond to your detection code for the TMP112 if they are connected on the same I2C bus.

Either way, safe is to do some exception handling on #ifdef statements like what can be seen in https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/xsns_27_apds9960.ino with specific reference to this piece in the code

```
#if defined(USE_SHT) || defined(USE_VEML6070)
  #warning **** Turned off conflicting drivers SHT and VEML6070 ****
  #ifdef USE_SHT
  #undef USE_SHT          // SHT-Driver blocks gesture sensor
  #endif
  #ifdef USE_VEML6070
  #undef USE_VEML6070     // address conflict on the I2C-bus
  #endif
#endif
```

**Pull request closed without merging**
