### PR TITLE
Added feature to set all possible mode for Parity, Stop, and Data bits

### LINKED ISSUE #3837: Support for generic Rx sensor
**Describe the solution you'd like**
I would like to connect my connected energy counter (linky) to Tasmota. We can find on the web adaptative circuit to adapt signal outing from linky to a serial signal compatible with Rx of ESP2286  or Raspebery....

Here is a version you can order : https://hallard.me/pitinfov12-light/
Or here is DIY version : http://sarakha63-domotique.fr/nodemcu-teleinformation-wifi/

Is there already a way to connect such circuit to Tasmota, inside a Sonoff Basic, and configure it to the sensor input to automatically sending teleinfo TTL/UART message over MQTT ?

**Describe alternatives you've considered**
I assume we can create a specific sensor for this device, but as this is not of the shelf, it may not be accepted. A generic UART to Mqtt gateway would easily allow to get the data and perform the data functionnal parser over the home automation solution.

**Additional context**
_Add any other context or screenshots about the feature request here._

### PR DESCRIPTION
**Pull request by hallard**
## Description:

This PR add new parameter `serial_config` to 
`bool TasmotaSerial::begin(long speed, int stop_bits, int serial_config)`

Leaving parameter `stop_bits` will not break the existing and leaving `serial_config` parameter empty will work as today.
`myTasmoSerial->begin(1200, SERIAL_8E1);`

Today calling with `myTasmoSerial->begin(1200, SERIAL_7E1);` leave to 8N1 so we needed to add another parameter to avoid breaking current implementation, so to do specific configuration for example we can now use  
`myTasmoSerial->begin(1200, 0, SERIAL_7E1);`

**Related issues** fixes #3837 and #5494

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core ESP8266 V.2.7.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx for your PR but...

The current implementation of calling additional function ``SetSerial`` makes sure that the used serial config is known to Tasmota. It also sets some Tasmota persistent parameters used during power on and restart.

As a library cannot communicate easily it's config parameters back to the program without excessive code increase (which is a major Tasmota core feature) I will not implement this PR and want to keep the current functionality of calling ``SetSerial``.

**Comment by hallard** [comment]
@arendst I have no problem with that so what's the best way for my energy device to setup 7E1 serial config ? If i understand correctly and I tested that, SetSerial works on ESP8266 (I tested it) but on ESP32 with 2 serials how SetSerial know wich one to setup ? Or may be we limit to only 1 serial ? Just to be sure

**Comment by arendst** [comment]
Ah. ESP32. Good one. Let me think about it.

**Comment by s-hadinger** [comment]
Charles, I strongly advise to handle this in software.

Receiving 7E1: just drop the MSB `val & 0x7F`

Sending 7E1: compute the parity bit and add it before sending.
Ex: https://stackoverflow.com/questions/29379006/calculate-parity-bit-from-string-in-c
```
char calcParityBit (unsigned char v)
{
    return (0x6996u >> ((v ^ (v >> 4)) & 0xf)) & 1;
}
```

**Comment by hallard** [comment]
@arendst yeah ESP32 I have in mind using 2nd ESP32 Serial to drive LoRa Module :-)

image

@s-hadinger I was sure sender (teleinfo) was sending only 7bits data. So if Serial of ESP is configured to receive 8 bits data, even dropping MSB will drop a data bit and get all frame shifted 1 bits on each char received. So I just tried your solution, and guess what, it works, not sure to understand how serial is handled by hardware and how a sender can send 7 bits of data and receiver waits for 8 and both are in sync, anyway it works, still don't understand why.

**Pull request closed without merging**
