### PR TITLE
Light palette

### PR DESCRIPTION
**Pull request by pcdiem**
## Description:

Add support for a light Palette. The Palette command set the palette colors. Schemes 2, 3 and 4 use the palette instead of the full color spectrum. The Color7 command sets the color based on the palette index or next (+)/previous (-) palette color.

## Checklist:
  - [x ] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
I have to get acquanted with the idea of losing 80 bytes of Settings space without knowing what I should do with it. 

I guess I have to add colors for 16 steps but have no idea what they should look like.

**Comment by mike2nl** [comment]
Why not add the driver to the Tasmota-Playground, as an idea.

**Comment by DavinKD** [comment]
While you guys are pondering this, One issue I have with scheme 2 is that it always starts at the last color it left off on.  This makes it impossible to have 2 different devices loop in unison.  I made a custom bin that added Light.wheel = 0; in the CmndScheme() subroutine to fix this.  I didn't want to do a pull request, because I'm guessing others may want it that way which would then require a setting.  Sounds like Color7 addresses this?

**Comment by pcdiem** [comment]
Color7 in Light palette doesn't address solve the issues of schemes 
starting with the last color. Color7 just uses the palette as the set up 
colors to use instead of the full color palette.

Seems like the ability to make schemes always start with wheel at zero 
would be a good flag option in settings.

**Pull request closed without merging**
