### PR TITLE
Support for 2M and 4MB builds

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

in Platformio override.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Thx. I'll do some testing first as last night I envisoned a possible issue if moving from 1M up and all settings are gone due to large OTA image overwriting all setting duplicates and no initialized new base setting at 0x1FB or 0x3FB.

So currently this is on hold.

**Comment by gemu2015** [comment]
consider another linker file for the 4M devices: eagle.flash.4m2m.ld
in this configuration you have enough flash space for many compile options and still have a filesystem

**Comment by arendst** [comment]
I don't think the 4m2m.ld does bring anything; the extra 1M cannot be used as code space by arduino core as it needs to be mapped within the 1M memory address to become useful. See this:
```
/* Flash Split for 4M chips */
/* sketch @0x40200000 (~1019KB) (1044464B) */
/* empty  @0x402FEFF0 (~1028KB) (1052688B) */
/* spiffs @0x40400000 (~2024KB) (2072576B) */
/* eeprom @0x405FB000 (4KB) */
/* rfcal  @0x405FC000 (4KB) */
/* wifi   @0x405FD000 (12KB) */
```
So a no-go. Let's keep it simple ;-)

**Comment by arendst** [comment]
OMG!! Just tried the 4M2M version and it works too:
```
{"StatusMEM":{"ProgramSize":513,"Free":1532,"Heap":27,"ProgramFlashSize":4096,"FlashSize":4096 ...
```

Free space for OTA is 1532!!! Still but max 1000 for programsize but hey, this opens up new possibilities!!!

So Jason pls add the 4M2M version too.

**Comment by gemu2015** [comment]
i use this linker file about a year with filesystem

**Comment by arendst** [comment]
Like:
```
; Build variant 4MB = 1MB firmware, 1MB OTA, 2MB filesystem (WEMOS D1 Mini, NodeMCU, Sonoff POW)
board_build.ldscript        = eagle.flash.4m2m.ld
```

**Comment by arendst** [comment]
> i use this linker file about a year with filesystem

if so, did you ever run into problems when your filesystem was formatted or ran out of space as in that case the default settings area (which was just before the eeprom area and therfor in the filesystem area) would be corrupted? Or did you use ``SO12 1`` to keep settings fixed in eeprom area?

**Comment by gemu2015** [comment]
no problems with OTA! setoption12 default

**Comment by arendst** [comment]
Thx.

Anyway the latest changes make sure that settings are outside the filesystem area (Now at address 0xF5000 to 0xFDFFF) and are saved to eeprom area when OTA is requested (which was already in place)

**Comment by Jason2866** [comment]
added eagle.flash.4m2m.ld

**Comment by lmagyar** [comment]
As I understand esp8266_2M1M is: 1MB firmware (+OTA), 0MB extra OTA, 1MB SPIFFS.

Will that use the SPIFFS to store temporarily the OTA image during download? I haven't read anywhere, that SPIFFS is used for temporary OTA storage.

**Pull request merged**
