### PR TITLE
New Feature: BS814A-2 Touch Driver

### PR DESCRIPTION
**Pull request by vic42**
## Description:
This code implements a touch key input driver for the BS814A-2 touch controller of Holtek-Semicon.
The driver was tested on a Teekar brand three-gang touch switch with an ESP82xx module.
I don't have access to hardware including an ESP32 and the touch chip but assume it will work there, too, because all the timing is left to OS functions.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>
This PR "fixes"  #10195

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
I've now seen zillions of these PR's.... Is this the final one?

If not just update this one instead of closing/opening a new one.

**Comment by vic42** [comment]
I have to find out how change an existing one.
A bit hasty because i don't want to lose my chosen numbers again ;-)

**Comment by vic42** [comment]
This is final.

**Comment by snookyly** [comment]
Successfully tested. Thanks for implementing.
Can be closed.

**Pull request merged**
