### PR TITLE
Add Digoo SP202 Smart Socket

### PR DESCRIPTION
**Pull request by netpok**
This pull request adds support for the [Digoo DG-SP202](https://www.banggood.com/DIGOO-DG-SP202-Dual-EU-Plug-Smart-WIFI-Socket-Individual-Controllable-Energy-Monitor-Remote-Control-Timing-Smart-Home-Outlet-let-p-1375323.html) smart socket.

Here is the pinout for the flashing:
digoo-pinout

### CODE REVIEW

**Comment by andrethomas** [comment]
Just for reference - this PR also includes changes proposed by PR https://github.com/arendst/Sonoff-Tasmota/pull/4884

**Comment by arendst** [comment]
Just blew this PR by removing the button file....

I will add it myself. Sorry.

**Comment by PeggyFree** [comment]
Hello, is the energy measure working under Tasmota? Thank you

**Comment by netpok** [comment]
Yes, it does

**Comment by evaluationevaluation** [comment]
you can even make rules upon the values and switch accordingly... have placed some of my rules in wiki article for Slitinto device.

**Comment by hista** [comment]
Hi,
I've flashed my Digoo NX-SP202 into tasmota 6.4.1(basic),thanks to tuya-convert for OTA.
Which template should I apply?
By default it's seen as a Sonoff Basic Module, which is not appropriate.
Thanks for your help :)

**Comment by lippertmarkus** [comment]
@hista this change wasn't released yet so just use the latest nightly build. Under "Firmware Upgrade" set `http://thehackbox.org/tasmota/sonoff.bin` as OTA URL and then start the upgrade. Afterwards you're having the Digoo DG-SP202 module in the "configure module" section. Did the same some minutes ago and it works flawlessly.

**Comment by hista** [comment]
Oh thanks, it's wonderfull now!
May I ask what other nice settings did you set for that device?

**Comment by lippertmarkus** [comment]
@hista nothing special, I just set the MQTT server and using the socket via openHAB now.

**Comment by kotfarepra** [comment]
Hi @lippertmarkus 
I have a   Digoo NX-SP202 with Tasmota 6.5.0 and I selected the  Digoo DG-SP202 module.
But it just keeps turning on and off the 2nd input .

Have you tested both inputs ?

**Comment by kotfarepra** [comment]
@hista Does it works ok on Digoo NX-SP202  ? 
Can you control both sockets ?
Does the two buttons on the sides works ok ?

Thank you

**Comment by lippertmarkus** [comment]
@kotfarepra For me both inputs do work without a problem and also with the buttons. Maybe there was a change in the meanwhile and you could try using an older build to see if it works then.

**Comment by kotfarepra** [comment]
Hi @lippertmarkus 

got the issue solved by this 

https://github.com/arendst/Sonoff-Tasmota/issues/5623

Thank you

**Pull request closed without merging**
