### PR TITLE
Add influxdb_period variable

### PR DESCRIPTION
**Pull request by pkkrusty**
influxdb_period could be set in userconfig_override, but would not populate.

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.11
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
SET_INFLUXDB_PERIOD is never used in Tasmota. Why this change?

**Comment by arendst** [comment]
Nope. It doesn't work that way. A setting variable to be used in userconfig_override needs a code construct like user definable TELE_PERIOD at the cost of code size increase only used during initial configuration.

**Comment by sfromis** [comment]
The way to have IFXPeriod included in `user_config_override.h` would be to have it as a command in `USER_BACKLOG`, which is executed once when initializing the configuration for the first time. Not tested if that would work.

**Comment by pkkrusty** [comment]
Will try that, thanks

**Pull request closed without merging**
