### PR TITLE
add german timer translation

### PR DESCRIPTION
**Pull request by reloxx13**
grafik

### CODE REVIEW

**Comment by Jason2866** [comment]
Gerät isnt a good choice for translation of timer in my humble opinion.
There is only one device (Gerät) which is switched at different times.
Maybe to long but better translation is Schaltzeitpunkt or simple let it not translated.
Timer is a well known word in German even for non English speaker

**Comment by arendst** [comment]
Perhaps I better change "device" to "Output".

**Comment by arendst** [comment]
But now I changed it to "Ausgang"

Is that "nice" German or should it stay as "Output"?

**Comment by Jason2866** [comment]
Ausgang is ok!  It is a philosopic debatte

**Pull request closed without merging**
