### PR TITLE
Support if updated

### PR DESCRIPTION
**Pull request by laurentdong**
## Description:

**Related issue (if applicable):** update of #5388 

## Checklist:
  - [X ] The pull request is done against the latest dev branch
  - [X ] Only relevant files were touched
  - [X ] Only one feature/fix was added per PR.
  - [X ] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [X ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X ] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

Codes are already tested by me but might need more test, especially for very complex scenario.

IF statement need Expression's support that I implemented before.
Be default, Both EXPRESSION and IF support is disabled. In order to enable IF support, please un-comment these lines in my_user_config.h (or put in user_config_override.h):
  #define USE_EXPRESSION                         // Add support for expression evaluation in rules (+3k2 code, +64 bytes mem)
     #define SUPPORT_IF_STATEMENT                 // Add support for IF statement in rules (+4k2 code, -332 bytes mem)

I use backlog to execute commands in IF statement. In order to properly insert commands into backlog, I re-implement backlog with LinkedList. But I still kept the original implementation if IF statement are disabled.

The major features of IF statement are:

- Support IF, ELSEIF, ELSE
- Support not only comparison but also using logical expression as condition
- Support run multiple commands
- Support nested IF statement
- All the commands run by IF statement will go to the BACKLOG!
- No limit for logical operators, parenthesis and nested IF statement. Depends on your RAM!

Form of IF statement:
\<if-statement\> ::=
IF "(" \<logical-expression\> ")" \<statement-list\> {ELSEIF "(" \<logical-expression\> ")" \<statement-list\>} [ELSE \<statement-list\>] ENDIF
\<logical-expression\> :=
\<comparison-expression\> |
(\<comparison-expression\> | \<logical-expression\>) {(AND | OR) \<logical-expression\>} |
"(" \<logical-expression\> ")" {(AND | OR) \<logical expression\>}
\<comparison-expression\> ::=
\<math-expression\> ("=" | "<" | ">" | "|" | "==" | "<=" | ">=" | "!=") \<math-expression\>
\<statement-list\> ::=
\<statement\> {";" \<statement\>}
\<statement\> ::=
\<Sonoff-Tasmota-command\> | \<if-statement\>

In English:
If statement support 3 format:
1. IF (\<condition\>) \<statement-list\> ENDIF
2. IF (\<condition\>) \<statement-list\> ELSE \<statement-list\> ENDIF
3. IF (\<condition\>) \<statement-list\> [ELSEIF (\<condition\>) \<statement-list\> ]* ELSE \<statement-list\> ENDIF

\<condition\> is a logical expression which can be:
1. A comparison expression for example:
   VAR1 >= 10
2. Multiple comparison expression with logical operator "AND" or "OR" between them. "AND" has higher priority than "OR". Fox example:
   UPTIME > 100 AND MEM1 == 1 OR MEM2 == 1
3. Parenthesis can be used to change the priority of logical expression. For example:
   UPTIME > 100 AND (MEM1 == 1 OR MEM2 == 1)

\<statement-list\> can be:
1. A Sonoff-Tasmota command. For example:
   ledpower on
2. A IF statement ("IF .... ENDIF")
3. Multiple Sonoff-Tasmota command or IF statement split with ";". For example:
   Power1 off; Ledpower on; if (mem1 == 0) Var1 Var1+1; mem1==1 endif; Delay 10; POWER1 on
4. Do not need leading with "BACKLOG" for multiple commands.

Examples:
This rule is used to control my pressure pot with a Sonoff S31 . Once it finish cocking, shut off the power immediately.
`rule1 on system#boot do var1 0 endon on energy#power>100 do if (var1!=1) ruletimer1 0;var1 1;endif endon on tele-energy#power<50 do if (var1==1) var1 2;ruletimer1 600;endif endon on rules#timer=1 do backlog var1 0;power off endon`

### CODE REVIEW

**Comment by arendst** [comment]
Thx.

**Comment by Jason2866** [comment]
I get a warning when compiling
```
D:/Sonoff-Tasmota-development.6.6.0.11/sonoff/xdrv_10_rules.ino: In function 'void ProcessIfStatement(const char*)':
D:/Sonoff-Tasmota-development.6.6.0.11/sonoff/xdrv_10_rules.ino:1558:18: warning: NULL used in arithmetic [-Wpointer-arith]
     if (NULL == *pos) break;
                  ^

```

**Comment by Jason2866** [comment]
@arendst  Maybe enabling this feature by default and disabling mDNS?!
Many users ask for if /then in rules (in Discord). 
mDNS is not realy needed. If someone wants it, Selfcompiling is easy with gitpod....

**Comment by meingraham** [comment]
@laurentdong 

I compiled Tasmota and enabled If and Expressions. I'm trying to convert this rule:
`Backlog Rule1 0; Rule1 5`
```
Rule1 
ON ENERGY#Power>=35 DO Backlog PowerDelta 10; Status 8 BREAK 
ON ENERGY#Power>=15 DO Backlog PowerDelta 25; Status 8 BREAK 
ON ENERGY#Power>4 DO Backlog PowerDelta 35; Status 8 BREAK 
ON ENERGY#Power<=4 DO PowerDelta 100 ENDON
```
`Rule1 1`

This rule set works fine.

I tried this syntax:
`Backlog Rule1 0; Rule1 5`
```
Rule1 
ON ENERGY#Power DO 
IF (%value%>=35) PowerDelta 10; Status 8 
ELSEIF (%value%>=15) PowerDelta 25; Status 8 
ELSEIF (%value%>4) PowerDelta 35; Status 8 
ELSE PowerDelta 100 
ENDON
```
`Rule1 1`

But the rule never triggers. I tried it with and without oneshot.

What am I missing?

Are you on Discord? Ii may be better to have this dialog there so it can be more interactive.

Regards.

Mike

**Comment by laurentdong** [comment]
@meingraham 
You missed ENDIF.
`Rule1 
ON ENERGY#Power DO 
IF (%value%>=35) PowerDelta 10; Status 8 
ELSEIF (%value%>=15) PowerDelta 25; Status 8 
ELSEIF (%value%>4) PowerDelta 35; Status 8 
ELSE PowerDelta 100 ENDIF
ENDON`

**Comment by meingraham** [comment]
F*ck me!

Thanks

**Comment by effelle** [comment]
@laurentdong just to confirm, every rule still has the 511 chars limitation, right?

**Comment by meingraham** [comment]
@laurentdong 

Rookie mistake. Arrgh!

So, `Energy#Power` does not trigger, but `Energy#Power>=0` does. I turned the device on and the Power was changing but it would not trigger until I had a comparison operator. Is this expected? With "regular" rules, any change to the value triggers the rule without requiring a comparison operator.

Nevertheless... other problems.
```
MQT: /RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":329,"Rules":"ON ENERGY#Power>=0 DO IF (%value%>=35) PowerDelta 10; Status 8 ELSEIF (%value%>=15) PowerDelta 25; Status 8 ELSEIF (%value%>4) PowerDelta 35; Status 8 ELSE PowerDelta 100 ENDIF ENDON"}
RUL: ENERGY#POWER>=0 performs "IF (0.00>=35) PowerDelta 10; Status 8 ELSEIF (0.00>=15) PowerDelta 25; Status 8 ELSEIF (0.00>4) PowerDelta 35; Status 8 ELSE PowerDelta 100 ENDIF"
MQT: /RESULT = {"Command":"Unknown"}
```

So I started to debug the rule and added a way to "print" the Power values
```
MQT: /RESULT = {"Rule1":"ON","Once":"ON","StopOnError":"OFF","Free":273,"Rules":"ON ENERGY#Power>=0 DO IF (%value%>=35) Var1 %value%; PowerDelta 10; Status 8 ELSEIF (%value%>=15) Var1 %value%; PowerDelta 25; Status 8 ELSEIF (%value%>4) Var1 %value%; PowerDelta 35; Status 8 ELSE Var1 %value%; PowerDelta 100 ENDIF ENDON"}
RUL: ENERGY#POWER>=0 performs "IF (0.00>=35) Var1 0.00; PowerDelta 10; Status 8 ELSEIF (0.00>=15) Var1 0.00; PowerDelta 25; Status 8 ELSEIF (0.00>4) Var1 0.00; PowerDelta 35; Status 8 ELSE Var1 0.00; PowerDelta 100 ENDIF"
MQT: /RESULT = {"Counter1":0}
```

Neither rule execution (`{"Command":"Unknown"}` / `{"Counter1":0}`) results in the expected result. I have no idea where `Counter1` came from.

Mike

**Comment by laurentdong** [comment]
> @laurentdong just to confirm, every rule still has the 511 chars limitation, right?

Yes.

**Comment by Jason2866** [comment]
@laurentdong 
Is it possible to use (if then else) without breaking backwards compatibility or reduce the impact?

For example:
`Rule1 ON Tele-ENERGY#Power DO DisplayText [z] [x1y0]%value%W ENDON ON Tele-ENERGY#Today DO DisplayText [x8y0]%value%Wh ENDON ON Tele-ENERGY#Voltage DO DisplayText [x1y1]%value%V ENDON ON Tele-ENERGY#Current DO DisplayText [x8y1]%value%A ENDON`
needs to be changed to
`Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":255,"Rules":"ON Tele-ENERGY#Power >= 0 DO DisplayText [z] [x1y0]%value%W ENDON ON Tele-ENERGY#Today >= 0 DO DisplayText [x8y0]%value%Wh ENDON ON Tele-ENERGY#Voltage >= 0 DO DisplayText [x1y1]%value%V ENDON ON Tele-ENERGY#Current >= 0 DO DisplayText [x8y1]%value%A ENDON`

For many users (with simple rules) with a update to this (great feature!) the rules will stop working

**Comment by meingraham** [comment]
@laurentdong 

This workaround
```
ON metric<>0 DO <my set of rules> ENDON
ON metric=0 DO <my set of rules> ENDON
```
would be a kludge, extra processing load, and depending on the length of the rules, could pose a buffer space problem.

**Comment by laurentdong** [comment]
@Jason2866 
No, I don't think you need to change from "ON Tele-ENERGY#Power DO" to "ON Tele-ENERGY#Power >= 0 DO". If the first one doesn't work and the second one works, it have to be something wrong (may be a bug?).
The new IF support should not affect the event trigger.

**Comment by laurentdong** [comment]
@meingraham 
I did not test your rules. But I think you'd better try those rules without IF first. For example:
'ON ENERGY#Power>0 DO var1 = %value%; PowerDelta 100 ENDON`

**Comment by meingraham** [comment]
@laurentdong 

I've had this rule (with the "debug" output) in place on my power monitoring devices for several months  and they work. I'm just using it as my way to become familiar with your IF/ELSE. I have another rule that's more complex that I'm going to graduate to when I learn the ins and outs of the new syntax. Anyhow, this rule works (it does include Backlog for multi-command rules):

```
Rule1 
ON ENERGY#Power>=35 DO Backlog Var1 %value%; PowerDelta 10; Status 8 BREAK 
ON ENERGY#Power>=15 DO Backlog Var1 %value%; PowerDelta 25; Status 8 BREAK 
ON ENERGY#Power>4 DO Backlog Var1 %value%; PowerDelta 35; Status 8 BREAK 
ON ENERGY#Power<=4 DO Backlog Var1 %value%; PowerDelta 100 ENDON
```

**Comment by laurentdong** [comment]
@meingraham 
OK. I'm going to have a try with your rules later.

**Comment by meingraham** [comment]
@laurentdong 

I wonder if this could be related:

<https://github.com/arendst/Sonoff-Tasmota/issues/5681#issuecomment-529938102>

**Comment by qingz2004** [comment]
@meingraham Yes, it is related. You are right. The update trigger stops working with this version.

**Comment by Jason2866** [comment]
> @Jason2866
> No, I don't think you need to change from "ON Tele-ENERGY#Power DO" to "ON Tele-ENERGY#Power >= 0 DO". If the first one doesn't work and the second one works, it have to be something wrong (may be a bug?).
> The new IF support should not affect the event trigger.

The first one worked fine and stopped working with this PR

**Comment by meingraham** [comment]
@laurentdong 

Any progress on the change in trigger behavior? Is that due to any changes your IF/ELSE introduced or is this in the "base" rules code? This is the priority as this breaks existing rules for anyone that upgrades to a current version.

Also, Any clues on why the rule I am experimenting with doesn't work? Any other tests you would like me to perform?

Mike

**Comment by meingraham** [comment]
@laurentdong 

Is there anything I can do to help test? It would be great to understand why this rule doesn't work because there are likely many similar use cases which require similar logic.

Mike

**Comment by meingraham** [comment]
@laurentdong 

When using variables in the original rules syntax, the variables need to be enclosed in `%` substitution markers. A recent user (@frablaser) of your enhanced expressions feature found that for expressions to work, the variables do not require the substitution markers. Is this your intention? Perhaps your logic could accept either syntax (i.e., also accept variables in enclosed with `%`) so that the documentation and use is consistent between "regular" rules" and the enhanced expressions?

Thanks.

Mike

**Comment by meingraham** [comment]
@laurentdong can you research please? ⬆️ https://github.com/arendst/Tasmota/pull/6386#issuecomment-561782820

**Pull request merged**
