### PR TITLE
More generic Bluetooth Low Energy

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:
This PR is for COMMENT and discussion - it should not be merged in it's current state.
Logging needs to be reduced, and I believe there is room for web UI support, and scan results -> MQTT (although this could be a separate driver - that's kind of the point).

Introduces a generic ESP32 BLE 'driver' designed to be used by other device drivers so that BLE can be used by multiple 'drivers' at once.

### The issue:
There are two BLE related xSns drivers - iBeacon (xsns_52) and a Sensor driver (xsns_62) which can be built in to support native ESP32 BLE.  These two drivers conflict, and cannot be used together.
At the moment, adding a BLE sensor would involve creating additional detailed functionality inside the xsns_62 driver for each device which we wished to support, or adding an additional driver.
I believe the style of the suggested generic driver will allow people to use existing sensors (and other BLE devices requiring read/write/notify access) with Tasmota without additional development within Tasmota.
It also allows 'popular' devices to have a specific driver within Tasmota, but sharing the BLE, and not conflicting.

### xdrv_46 provides:
1/ generic BLE scanning, catching advertisments with data, and calling registered callbacks.
2/ generic BLE 'operations'.
an operation can be setup through an API call, and provide a callback on success or failure.
Operations can also be setup and executed via commands, resulting in MQTT output on success or failure.
callbacks can be registered to 'hear' all operations.
3/ callbacks can be registered to see scan results at the end of a scan.

xsns_52_ibeacon has been modified to make use of xdrv_46_BLE_ESP32, as an example of registering for advertisment callbacks.

I believe I have included all the features required for xsns_62_MI_ESP32 to be updated to use the generic BLE - happy to do this but want some feedback first.

### use:
xdrv_46 is enabled via 
USE_BLE_ESP32 and ESP32
To use it, you must 'setoption115 1'.
It currently logs all adverts with extra data at LOG_LEVEL_DEBUG
To enable xsns_52_iBeacon as well, add USE_IBEACON_ESP32
Ensure USE_MI_ESP32 is not defined.

### documentation
I have added a lot of comments at the top about usage, and some examples are at the bottom of the main file.
It's a little unusual, as have added a .h file - this may no longer be required as I moved it from an xsns file to an xdrv file (so it gets included early?).
Will be happy to add/update documentation after discussion.

### Personal motivation:
I have both temp/humidity sensors and EQ-3 BLE radiator valves spread around a house.
I wanted an ESP32 based device which could act as a WIFI to BLE bridge working with both types of device.
Using the commands on the generic driver, I can read/write/notify against the EQ3 valves, and also hear the temp/humidity (once xsns_62 is updated).
I did not want to add all the bulk of an 'EQ3 driver' to Tasmota, preferring the heavy lifting of the variety of BLE command sets to be dealt with in something like Node Red.

### Requests:
I have prepared the xdrv_46 driver based on requirements gathered from xsns62, xsns52, and from my own EQ3 BLE requirements.  
This will not be a complete set of requirements to be able to read/write any BLE device completely generically, but is probably a fairly good start.
We probably can't create a generic driver which would deal with ALL BLE devices, but it would be really good to get verification that the driver is able to talk to some other devices other than the EQ3 devices.
Scan results are currently not published - there is a lot of information in the debug loigs to work with, but I believe that scan results should be published - thoughts on this appreciated (e.g. should you have to ask for them, should they be a web UI feature, etc.).
Also thoughts on blocking devices in busy areas would be appreciated - this is a feature of xsns62 which is not in xdrv46.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by btsimonh** [comment]
should I convert this to a draft?

**Comment by arendst** [comment]
Thx.

- As the driver id 46 is already used for ccloader you are requested to change it to 47.
- For testing I recommend you add the needed defines to your user_config_override.h file and chk it is compiled for both esp8266 and esp32. If OK then only provide the files needed but do not enable them in my_user_config.h

@staars can you have a look if this makes sense to replace/add your work so far?

**Comment by btsimonh** [comment]
Hi Theo,

Renamed to xdrv_47 (sorry, was a few weeks back in my repo when I chose 47!).
Added a commented line in "my_user_config.h"

tested building with the defines
#define USE_IBEACON
#define USE_BLE_ESP32
//#define USE_MI_ESP32
fine for env:tasmota-sensors 
fine for env:tasmota32-sensors

My first visit back here in a couple of years, and things moved on so much :).  looking good as always.  Nice to find some ESP32 support, and BLE as a bonus!

This is heavily inspired by @Staars 's code.

**Comment by Staars** [comment]
The fundamental idea to allow access to a shared resource is a good one.
I also can not spot any "completely wrong" design decisions (which of course is always a matter of personal taste).

Questions are: How stable does this (added overhead) work? How much memory do we burn? Who will maintain it?

If only one driver would use this, it would make zero sense to me. We would only add overhead and an additional chance for bugs.

I do not know, if the ESP32 has enough resources to run more than one BLE-driver (=micro application) inside Tasmota sufficiently. Only real world tests would show this. 
Bluetooth is still a moving target on the ESP32 and a few month ago my answer would have been: Forget it.
But we have seen some progress in the last weeks with the never core-versions and maybe it can really work this way.

My suggestion:
@btsimonh Please add additional version of xsns_62 and(!) xsns_52 which are user selectable at compile time.
These should be provided as a build option to see, if they work for the users (including the driver maintainers). Then a reasoned decision could be made, if all drivers should be converted by default.
I would not recommend to change to the new driver model before this (open) test.

**Comment by arendst** [comment]
So pls go forward as @staars suggested allowing to test pros and cons

**Comment by btsimonh** [comment]
sounds like a plan.

I will:
- duplicate the existing xsns_52 and add #ifndef USE_BLE_ESP32
- duplicate the existing xsns_62 and add #ifndef USE_BLE_ESP32
- strip the duplicates of native BLE code for clarity (leaving only support the xdrv_47 form).
- Hide them behind USE_BLE_ESP32 and USE_BLE_EXAMPLES
- Hide them behind USE_BLE_ESP32 and USE_BLE_EXAMPLES

once stable and happy, if @Staars could do an initial checkover, then we ask for a couple more interested parties to test?

I'll also put together some form of NodeRed flow for hammering the exposed interfaces over periods of time.

br,  Simon

**Comment by btsimonh** [comment]
I'm going to close this PR and start another cleaner version.

**Comment by btsimonh** [comment]
ok, new PR ready for analysis.
Lost a day to my real work, so be kind :).

**Pull request closed without merging**
