### PR TITLE
add colorpicker to Web-UI

### PR DESCRIPTION
**Pull request by Staars**
Some users asked for the possibility to control color lights outside of a home automation system. This PR adds a small color picker/slider to the Web-GUI.

The main goal was to keep this as tiny as possible with a slight amount of responsiveness. It should show up automatically for devices configured for color lights.

This adds 756 bytes of program space.

### CODE REVIEW

**Review by ascillato — APPROVED** [review]

**Comment by ascillato** [comment]
Tested and works! :+1:

**Comment by jziolkowski** [comment]
It was tested by 2.5 and 7.5yo at our home and the verdict is "Absolutely great!"

**Comment by Staars** [comment]
It looks like that:
colorpicker

**Comment by ascillato** [comment]
On a NodeMCU with a relay and a WS2812B Led Strip, it looks like:

image

**Comment by ihavenonick** [comment]
Dies ist ein Magic Home RGBW und ich vermisse einen Slider für echte weiße Farbe. Es ist nur ein Slider für RBG und nicht für Weiß. Ich benutze IOBroker und es gibt auch Datenpunkte für Weiß und Dimmer.
Es ist nicht möglich, die Farbe Weiß mit dem Webinterface zu steuern, nur mit IOBroker über MQTT.
grafik

I uses this template for RGBW stripe:
{"NAME":"MH-RGBW","GPIO":[255,255,255,255,255,38,255,255,37,39,0,40,255],"FLAG":15,"BASE":18}

**Comment by Staars** [comment]
We are still in the process of finalizing the things.
Keep in mind, that Tasmota uses a HSB-color-model and NOT HSL internally. So the creation of white needs desaturation.
Please be patient and wait for the new WIKI entry, which will likely be delayed a bit, because the whole WIKI gets a new technical base. This will take a bit longer than usual.

**Comment by ihavenonick** [comment]
OK, it means something is coming for white?

**Pull request merged**
