### PR TITLE
Added support for TM1637 Seven-Segment Display

### PR DESCRIPTION
**Pull request by ajithvasudevan**
## Description:

Added support for TM1637 Seven-Segment Display.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by ajithvasudevan** [comment]
Hi, can someone please let me know why the sensors build is failing? It says missing header file, however, I have added the library in tasmota/lib/lib_display/.  PlatformIO found the library and compiled it fine locally.

**Comment by Jason2866** [comment]
Build Tasmota-sensors does NOT include display libs
```
[env:tasmota-sensors]
build_flags             = ${common.build_flags} -DFIRMWARE_SENSORS
lib_extra_dirs          = lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div
```
You have to decide if the TM1637 is a sensor or a display. Move the lib files accordingly.
My suggestion would be to put the lib files in lib folder `lib_div` so it can be used with build sensor an it is not classified as display only

**Comment by Jason2866** [comment]
Regarding to this comment in your code. The driver is NOT a sensor it is a display driver.
```
  To use, compile Tasmota with USE_DISPLAY_SEVENSEG and USE_TM1637 
  This adds the following
  Pins:
    * TM 1637 DIO
    * TM 1637 CLK
  ```
so please change your driver to a display driver and move the libs to folder `lib_display`. Changes needed in `tasmota_configurations.h` too.

**Comment by Jason2866** [comment]
Using display drivers in build variant "tasmota-sensors" is not possible, so the `#define USE_DISPLAY_SEVENSEG` will fail

**Comment by ajithvasudevan** [comment]
@Jason2866 I think I acted too quickly after your first suggestion. Will revert and change driver to display type.
The confusion arose due to the existing "display" driver for the TM1638 - xsns_28_tm1638.ino

**Comment by Jason2866** [comment]
TM1638 driver supports the switches and the LEDs (not the the display). So it is not a display device.

**Comment by ajithvasudevan** [comment]
> TM1638 driver supports the switches and the LEDs (not the the display). So it is not a display device.
> Can your code or the libs of the TM1637 be (re)used to enhance the TM1638 driver?

Unfortunately, the lib I depend on for  the display part doesn't deal with the sensor part. Probably some kind of merger of the two is required for unifying everything. I can look into that after getting this one up.

**Comment by ajithvasudevan** [comment]
> Regarding to this comment in your code. The driver is NOT a sensor it is a display driver.
> 
> ```
>   To use, compile Tasmota with USE_DISPLAY_SEVENSEG and USE_TM1637 
>   This adds the following
>   Pins:
>     * TM 1637 DIO
>     * TM 1637 CLK
> ```
> 
> so please change your driver to a display driver and move the libs to folder `lib_display`. Changes needed in `tasmota_configurations.h` too.

When I try to change the driver type from "sensor" to "display", I find that there is no FUNC_COMMAND callback defined for display drivers. Is there an equivalent callback I can use?  I do not need the FUNC_DISPLAY_EVERY_50_MSECOND type callbacks.

**Comment by ajithvasudevan** [comment]
> Build Tasmota-sensors does NOT include display libs
> 
> ```
> [env:tasmota-sensors]
> build_flags             = ${common.build_flags} -DFIRMWARE_SENSORS
> lib_extra_dirs          = lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div
> ```
> 
> You have to decide if the TM1637 is a sensor or a display. Move the lib files accordingly.
> My suggestion would be to put the lib files in lib folder `lib_div` so it can be used with build sensor an it is not classified as display only

Given the above fact that the TM1637, just like the TM1638, isn't an I2C device, can we use this device as a "sensor"?

**Comment by arendst** [comment]
Thx.

As this is a display only you'll need to rewrite it as a display driver like ``xdsp_11_sevenseg.ino``. A display driver uses the commands from the master display driver ``xdrv_13_display.ino``.

I suggest you do not mess with the feature file as your current implementation tries to exceed the range of a 32-bit integer.

**Comment by ajithvasudevan** [comment]
Thanks for the feedback, @arendst .
I am working on the changes you suggested.

The commands suitable for the TM1637, and implemented by its underlying library are as folllows:
`const char kTM1637_Commands[] PROGMEM   = "Clear|Number|NumberC|Float|FloatC|Brightness|Raw|Level|Text|TextC|ScrollDelay|Clock";
`
Their descriptions are as follows:

```
enum TM1637_Commands {        // commands useable in console/MQTT or rules
  CMND_TM1637_CLEAR,          // Blanks the display, command: "TM1637Clear"
  CMND_TM1637_NUMBER,         // Display integer number  (-999 to 9999). command e.g., "TM1637Number 1234"
                              // Control 'leading zeros', 'length' and 'position' with  "TM1637Number 1234, <leadingZeros>, <length>, <position>"
                              // 'leading zeros' can be 1 or 0 (default), 'length' can be 1 to 4 (default), 'position' can be 0 (left-most) to 3 (right-most)
  CMND_TM1637_NUMBERC,        // Clear first, then display integer number  (-999 to 9999). e.g., "TM1637NumberC 1234". Usage is same as above.
  CMND_TM1637_FLOAT,          // Display float (with decimal point)  (0.001 to 9999.) command e.g., "TM1637Float 12.34"
  CMND_TM1637_FLOATC,         // Clear first, then display float (with decimal point)  (0.001 to 9999.) command e.g., "TM1637FloatC 12.34"  
  CMND_TM1637_BRIGHTNESS,     // Set brightness (1 to 7) command e.g., "TM1637Brightness 2"  Note: Brightness takes effect only after a new display command is sent.
  CMND_TM1637_RAW,            // Takes 4 comma-separated integers (0-255) and displays raw segments 
                              // Each 7-segment display unit is represented by an 8-bit(8th bit for decimap point) number.
                              // For example, the command "TM1637Raw 255, 255, 255, 255" would display "[8.8.8.8.]"
  CMND_TM1637_LEVEL,          // Display a horizontal bar graph (0-100) command e.g., "TM1637Level 50" will display [||||    ]  
  CMND_TM1637_TEXT,           // Display basic text (scrolls if > 4 characters)  command e.g., "TM1637Text ajith vasudevan" 
                              // Control 'length' and 'position' with  "TM1637Text abcd, <length>, <position>"
                              // 'length' can be 1 to 4 (default), 'position' can be 0 (left-most) to 3 (right-most)
                              // Note: A caret sign '^' in the input text would be replaced by a "degrees" symbol. This is handy for displaying temperature!
                              //       Other Characters whose ASCII > 127 or ASCII < 32 would simply be blank.
  CMND_TM1637_TEXTC,          // Clear first, then display text. Usage is same as above.
  CMND_TM1637_SCROLLDELAY,     // Sets the speed of text scroll. Takes effect only after a new TEXT command is sent with 4 chars or more.     
  CMND_TM1637_CLOCK        // Displays a clock. To start clock, command "TM1637Clock 1". To turn offclock, "TM1637Clock 0" 
};

```

I find that the display driver commands in `xdrv_13_display.ino` are graphics oriented and don't map well to the commands a simple seven-segment display like the TM1637 requires.

I can see a couple of solutions - 
1. I add a few commands like the ones described above, specific to simple 7-segment displays, to  `xdrv_13_display.ino`
2. I use the FUNC_DISPLAY_DRAW_STRING with a sub-command in the input string (dsp_str) for all of the above commands

I would like to take the first option. 

What do you suggest?

**Comment by arendst** [comment]
Try to implement a basic driver first without the extended commands.

As there is already a seven segmenet display driver present I expect most command functionality should be implemented already.

**Comment by ajithvasudevan** [comment]
> Try to implement a basic driver first without the extended commands.
> 
> As there is already a seven segmenet display driver present I expect most command functionality should be implemented already.

I have, infact, implemented the basic driver first, then with the way @Jason2866 suggested.
 
The existing "seven-segment display driver" does not do display, as already noted here. There is no support for any kind of basic 7-segment displays in tasmota as of now.  And, as I already mentioned, the current seven-segment display driver doesn't do simple numbers. It seems to cater to LCDs and such for graphics.

I have been working on a proper display driver implementation like you suggested. I would like you to review it once. Can I submit a PR?


I

**Comment by ajithvasudevan** [comment]
image
Here's a TM1637 module working with Tasmota built with the new driver! 

:-)

**Comment by ajithvasudevan** [comment]
I have removed the dedicated pins I had added for this module, and now using SSPI MOSI ans SSPI SCLK  (Software SPI), greatly reducing the number of changes. Doing this eliminated a bug (I introduced, of course) where SPI pins were getting assigned automatically when TM1637 was enabled. I now know why, though :)

**Comment by stephan-8266** [comment]
> Thanks for the feedback, @arendst .
> I am working on the changes you suggested.
> 
> The commands suitable for the TM1637, and implemented by the new driver, are as folllows:
> 
> ```
>   DisplayClear
>                                Blanks the display, command: "DisplayClear"
> 
>   DisplayNumber         num [,leading_zeros {0|1} [,length {1-4} [,position {0-3} [,dot {0-4} ]]]]
>                                Clears and then displays integer number  (-999 to 9999). command e.g., "DisplayNumber 1234"
>                                Control 'leading zeros', 'length' and 'position' with  "DisplayNumber 1234, <leadingZeros>, <length>, <position>, <dot>"
>                                'leading zeros' can be 1 or 0 (default), 'length' can be 1 to 4 (default), 'position' can be 0 (left-most) to 3 (right-most),
>                                'dot' can be 0,(no dot), 1 (left-most) to 4 (right-most). See function description below for more details.
> 
>   DisplayNumberNC       num [,leading_zeros {0|1} [,length {1-4} [,position {0-3} [,dot {0-4} ]]]]
>                                Display integer number as above, but without clearing first. e.g., "DisplayNumberNC 1234". Usage is same as above.
>                         
>   DisplayFloat          num [,precision {0-4} [,length {1-4} [,position {0-3} ]]]
>                                Clears and then displays float (with decimal point)  (0.001 to 9999.) command e.g., "DisplayFloat 12.34"
>                                See function description below for more details.
> 
>   DisplayFloatNC        num [,precision {0-4} [,length {1-4} [,position {0-3} ]]]
>                                Displays float (with decimal point) as above, but without clearing first. command e.g., "DisplayFloatNC 12.34"
>                                See function description below for more details.
> 
>   DisplayBrightness     num {0-7}
>                                Set brightness (1 to 7) command e.g., "DisplayBrightness 2"  Note: Brightness takes effect only after a new display command is sent.
> 
>   DisplayRaw            num1, num2, num3, num4 [,length {1-4} [,position {0-3}] ]
>                                Takes 4 comma-separated integers (0-255) and displays raw segments 
>                                Each 7-segment display unit is represented by an 8-bit(8th bit for decimap point) number.
>                                For example, the command "DisplayRaw 255, 255, 255, 255" would display "[8.8.8.8.]"
> 
>   DisplayLevel          num {0-100}
>                                Display a horizontal bar graph (0-100) command e.g., "DisplayLevel 50" will display [||||    ]  
> 
>   DisplayText           text [, length {1-4} [, position {0-3}]]
>                                Clears and then displays basic text (scrolls if > 4 characters)  command e.g., "DisplayText ajith vasudevan" 
>                                Control 'length' and 'position' with  "DisplayText <text>, <length>, <position>"
>                                'length' can be 1 to 4 (default), 'position' can be 0 (left-most) to 3 (right-most)
>                                Note: A caret sign '^' in the input text would be replaced by a "degrees" symbol. This is handy for displaying temperature!
>                                      Other Characters whose ASCII > 127 or ASCII < 32 would simply be blank.
> 
>   DisplayTextNC         text [, length {1-4} [, position {0-3}]]
>                                Clear first, then display text. Usage is same as above.
> 
>   DisplayScrollDelay delay_in_milliseconds    // default = 200
>                                Sets the speed of text scroll. Takes effect only after a new TEXT command is sent with 4 chars or more.     
> 
>   DisplayClock  1|2|0          
>                                Displays a clock. 
>                                Commands "DisplayClock 1"     // 12 hr format
>                                         "DisplayClock 2"     // 24 hr format
>                                         "DisplayClock 0"     // turn off clock
> 
>            
> ```
> 
> I find that the display driver commands in `xdrv_13_display.ino` are mostly graphics oriented and don't map well to the commands a simple seven-segment display like the TM1637 requires (numbers with/without decimals only).
> 
> I can see a couple of solutions -
> 
> 1. I add a few commands like the ones described above, specific to simple 7-segment displays, to  `xdrv_13_display.ino`
> 2. I use the FUNC_DISPLAY_DRAW_STRING with a sub-command in the input string (dsp_str) for all of the above commands
> 
> I would like to take the first option.
> 
> What do you suggest?

can you please support more than 4 digits?

**Comment by Jason2866** [comment]
CI fails

**Comment by ajithvasudevan** [comment]
> 
> can you please support more than 4 digits?

There are no 1637 module variants with more than 4 digits. 
The TM1638 (the one with the buttons and LEDs) has 8 digits. But it uses a different library (or, at least I couldn't find one that implements both) 

And so, I built a separate Tasmota display driver for the 1638, **including support for its buttons and LEDS**. I can submit a separate PR for that.

**Comment by stephan-8266** [comment]
> > can you please support more than 4 digits?
> 
> There are no 1637 module variants with more than 4 digits.
> The TM1638 (the one with the buttons and LEDs) has 8 digits. But it uses a different library (or, at least I couldn't find one that implements both)
> 
> And so, I built a separate Tasmota display driver for the 1638, **including support for its buttons and LEDS**. I can submit a separate PR for that. The code is here: https://github.com/ajithvasudevan/Tasmota/tree/tm1638
> 
> EDIT: Just finishing up the documentation and code comments!

Hi,

there are 6 digit mudules like this one 
https://www.aliexpress.com/item/4001293690559.html?spm=a2g0o.cart.0.0.3dd63c00R2USUQ&mp=1

**Comment by ajithvasudevan** [comment]
> 
> there are 6 digit modules like this one
> https://www.aliexpress.com/item/4001293690559.html?spm=a2g0o.cart.0.0.3dd63c00R2USUQ&mp=1

Can you please provide a link from another website? aliexpress in currently blocked where I am, unfortunately.

**Comment by stephan-8266** [comment]
> > there are 6 digit modules like this one
> > https://www.aliexpress.com/item/4001293690559.html?spm=a2g0o.cart.0.0.3dd63c00R2USUQ&mp=1
> 
> Can you please provide a link from another website? aliexpress in currently blocked where I am, unfortunately.

Hi, thanks for taking care about my request, it's highly highly appreciated. 
please look here:
https://robotdyn.com/6-digit-led-display-tube-7-segments-46x14mm-tm1637.html
even with schematic
https://robotdyn.com/pub/media/0G-00005636==Mod-LED-Display-6D-TM1637-46x14mm/DOCS/Schematic==0G-00005636==Mod-LED-Display-6D-TM1637-46x14mm.pdf

**Comment by ajithvasudevan** [comment]
@stephan-8266 
Thanks for the links. I can see these are indeed TM1637 based modules. However, they are not available in my country. For e/g/, https://www.amazon.in/RobotDyn-6-Digit-7-segment-Display-76x19mm/dp/B071K8BQM9
I will see what I can do in terms of the software. I'd need your help in testing it, though.

**Comment by ajithvasudevan** [comment]
@stephan-8266
Can you point me to the Arduino lib that you have used for these 6-digit displays? I am unable to find any in the official Arduino library repo. All of them seem to work only with the 4-digit variants.

**Comment by stephan-8266** [comment]
> @stephan-8266
> Can you point me to the Arduino lib that you have used for these 6-digit displays? I am unable to find any in the official Arduino library repo. All of them seem to work only with the 4-digit variants.

yes, thats what i saw in the meantime... looks like none of the libs are supporting 6 digits... let me catch some 6 digit display to play around with

**Comment by ajithvasudevan** [comment]
@stephan-8266

> 
> yes, thats what i saw in the meantime... looks like none of the libs are supporting 6 digits... let me catch some 6 digit display to play around with

Found this one:  https://github.com/bremme/arduino-tm1637

It allows initializing the display module with "number of columns (digits)"  (and rows!!)

Maybe you can try this when you get your 6-digit display/

**Comment by ajithvasudevan** [comment]
Subsequent to the feature request from @stephan-8266, I have changed the lib to the one I mentioned above (by bremme), and added support for variable number of digits, upto 6, the maximum that the TM1637 supports.
The supported commands are as follows:

```
  DisplaySize           size {1-6}

                               Sets the number of digits to use. This is typically set to the actual number of digits available
                               in the display module. command e.g., "DisplaySize 6" 


  DisplayClear
  
                               Clears the display, command: "DisplayClear"


  DisplayNumber         num [,position {0-(NUM_DIGITS-1))} [,leading_zeros {0|1} [,length {1 to NUM_DIGITS}]]]
  
                               Clears and then displays number without decimal. command e.g., "DisplayNumber 1234"
                               Control 'leading zeros', 'length' and 'position' with  "DisplayNumber 1234, <position>, <leadingZeros>, <length>"
                               'leading zeros' can be 1 or 0 (default), 'length' can be 1 to NUM_DIGITS, 'position' can be 0 (left-most) to NUM_DIGITS (right-most).
                               See function description below for more details.

  DisplayNumberNC       num [,position {0-(NUM_DIGITS-1))} [,leading_zeros {0|1} [,length {1 to NUM_DIGITS}]]]

                               Display integer number as above, but without clearing first. e.g., "DisplayNumberNC 1234". Usage is same as above.



  DisplayFloat          num [,position {0-(NUM_DIGITS-1)} [,precision {0-NUM_DIGITS} [,length {1 to NUM_DIGITS}]]]

                               Clears and then displays float (with decimal point)  command e.g., "DisplayFloat 12.34"
                               See function description below for more details.



  DisplayFloatNC        num [,position {0-(NUM_DIGITS-1)} [,precision {0-NUM_DIGITS} [,length {1 to NUM_DIGITS}]]]

                               Displays float (with decimal point) as above, but without clearing first. command e.g., "DisplayFloatNC 12.34"
                               See function description below for more details.



  DisplayBrightness     num {0-8}

                               Set brightness (0 (off) to 8) command e.g., "DisplayBrightness 2" 



  DisplayRaw            position {0-(NUM_DIGITS-1)},length {1 to NUM_DIGITS}, num1 [, num2[, num3[, num4[, ...upto NUM_DIGITS numbers]]]]]

                               Takes upto NUM_DIGITS comma-separated integers (0-255) and displays raw segments. Each number represents a 
                               7-segment digit. Each 8-bit number represents individual segments of a digit.
                               For example, the command "DisplayRaw 0, 4, 255, 255, 255, 255" would display "[8.8.8.8.]"



  DisplayText           text [, position {0-(NUM_DIGITS-1)} [,length {1 to NUM_DIGITS}]]

                               Clears and then displays basic text.  command e.g., "DisplayText ajith vasudevan" 
                               Control 'length' and 'position' with  "DisplayText <text>, <position>, <length>"
                               'length' can be 1 to NUM_DIGITS, 'position' can be 0 (left-most) to NUM_DIGITS-1 (right-most)



  DisplayTextNC         text [, position {0-NUM_DIGITS-1} [,length {1 to NUM_DIGITS}]]

                               Clears first, then displays text. Usage is same as above.



  DisplayScrollText     text

                              Displays scrolling text. 



  DisplayScrollDelay delay {0-15}   // default = 4

                               Sets the speed of text scroll. Smaller delay = faster scrolling.



  DisplayLevel          num {0-100}

                               Display a horizontal bar graph (0-100) command e.g., "DisplayLevel 50" will display [||||    ]  



  DisplayClock  1|2|0          

                               Displays a clock. 
                               Commands "DisplayClock 1"     // 12 hr format
                                        "DisplayClock 2"     // 24 hr format
                                        "DisplayClock 0"     // turn off clock

  

```

**Comment by ajithvasudevan** [comment]
I have tested the 6-digit variety using a "home-made" module (since I can't buy these in my country):
( The schematic helped. Thanks @stephan-8266 )
image

**Comment by ajithvasudevan** [comment]
@arendst , I am happy to see my first PR merged into Tasmota :)   I'm now working on adding "full support" for the **TM1638** (buttons, LEDs and Display). A lot of the code in `xdsp_15_tm1637.ino`  can be re-used for the **TM1638** (and, also the **MAX7219** (coming soon)) So I have added the **TM1638** code into the same driver (`xdsp_15_tm1637.ino`), and I am currently allowing the user to switch between the two display modules using **DisplayMode 1|0**, which, I know is not the proper way. Can you please suggest the right way to do this?
Is there some other way I can allow the user to select and persist the selected display type - TM1637 / TM1638 / MAX7219  ?     You can see the changes done so far, here: https://github.com/arendst/Tasmota/compare/development...ajithvasudevan:tm1638

**Comment by ajithvasudevan** [comment]
After giving it some more thought, I've come to believe that adding a new `Settings.display_type` flag could solve the problem. I have implemented the same here: https://github.com/arendst/Tasmota/compare/development...ajithvasudevan:tm1638
With this, I can switch between _TM1637, 4-digit_, _TM1637, 6-digit_, and _TM1638_ by just issuing the commands **DisplayType 0**,  **DisplayType 1**, and **DisplayType 2**,  respectively. Does this sound good?

**Comment by ajithvasudevan** [comment]
This driver is enhanced with TM1638 support here: https://github.com/arendst/Tasmota/pull/11031

**Comment by usrrsr** [comment]
> 

I have configured the way said in document on lates release. I am able to control 8 7 segment display but not able to operate 8 button and and control the 8 led.
I am ising tm1638 module

Can you please help

**Comment by barbudor** [comment]
@usrrsr have you compiled your own binary as documented?
https://tasmota.github.io/docs/TM163x/#tm1638-leds-and-buttons

**Comment by usrrsr** [comment]
Yes 
Content of user override file

#define STA_SSID1         "USR1"             // [Ssid1] Wifi SSID
#define STA_PASS1         "varu@2016"     // [Password1] Wifi password

#define USE_EXPRESSION         // Add support for expression evaluation in rules (+3k2 code, +64 bytes mem)  
#define SUPPORT_IF_STATEMENT   // Add support for IF statement in rules (+4k2 code, -332 bytes mem)  

#define MQTT_TOPIC             "%12X"   // [Topic] unique MQTT device topic including (part of) device MAC address
#define MQTT_HOST              "12c34e9079c849a1b0688350df77995b.s1.eu.hivemq.cloud"                // [MqttHost]
//#define MQTT_PORT              1883              // [MqttPort] MQTT port (10123 on CloudMQTT)
#define MQTT_PORT              8883              // [MqttPort] MQTT port (10123 on CloudMQTT)
#define MQTT_USER              "usrrsr"       // [MqttUser] MQTT user
#define MQTT_PASS              "samartha"       // [MqttPassword] MQTT password
#define TELE_PERIOD            300                // [TelePeriod] Telemetry (0 = disable, 10 - 3600 seconds)
#define SUPPORT_MQTT_EVENT
#define MQTT_TELE_RETAIN       1                 // Tele messages may send retain flag (0 = off, 1 = on)

#define USE_MCP230xx_ADDR 0x20
#define USE_MCP230xx                 // Enable INPUT mode (pinmode 1 through 4)
#define USE_MCP230xx_OUTPUT          // Enable OUTPUT mode (pinmode 5)
#define USE_MCP230xx_DISPLAYOUTPUT   // Display state of OUTPUT pins on main Tasmota web interface

#define MQTT_FINGERPRINT1     "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"
// #define MQTT_FINGERPRINT1     "FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF"
// #ifndef USE_MQTT_TLS
#define USE_MQTT_TLS                             // Use TLS for MQTT connection (+34.5k code, +7.0k mem and +4.8k additional during connection handshake)
#define MQTT_TLS_ENABLED       true              // [SetOption103] Enable TLS mode (requires TLS version)
//#define USE_MQTT_TLS_CA_CERT                   // Force full CA validation instead of fingerprints, slower, but simpler to use.  (+2.2k code, +1.9k mem during connection handshake)
                                                   // This includes the LetsEncrypt CA in tasmota_ca.ino for verifying server certificates
//  #define USE_MQTT_TLS_FORCE_EC_CIPHER           // Force Elliptic Curve cipher (higher security) required by some servers (automatically enabled with USE_MQTT_AWS_IOT) (+11.4k code, +0.4k mem)
#define USE_RC_SWITCH         // Add support for RF transceiver using library RcSwitch (+2k7 code, 460 iram)

#define USE_DISPLAY
#define USE_DISPLAY_TM1637

#define USE_TM1638 // Add support for TM1638 switches copying Switch1 .. Switch8 (+1k code)
//#define TM1638_USE_AS_BUTTON // Add support for buttons
#define TM1638_USE_AS_SWITCH // Add support for switches (default)
#define TM1638_MAX_DISPLAYS 8 // Add support for power control 8 displays
#define TM1638_MAX_KEYS 8 // Add support for 8 keys
#define TM1638_MAX_LEDS 8 // Add support for 8 leds

**Comment by barbudor** [comment]
Can you please start a new Discussion and we would start from there ?
Beware that the above copy/paste may include some personnal informations that you may not want to publish publicaly, so better edit it

**Pull request merged**
