### PR TITLE
Feature: IRMP Support for Tasmota

### PR DESCRIPTION
**Pull request by eku**
## Description:

Adds support for [IRMP](https://github.com/ukw100/IRMP) to Tasmota.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

IRMP/IRSND is a library for decoding and encoding infrared signals. It supports 50+ protocols and proves to be more robust in decoding than IRremoteESP8266, which was the motivation to provide IRMP for Tasmota.

For details see
https://www.mikrocontroller.net/articles/IRMP_-_english
https://github.com/ukw100/IRMP

The functionality is completely deactivated by default (see my_user_config.h). As decoding is done in the ISR, the IRAM of the ESP8266 is not sufficient to activate all 50 protocols, so only the required protocols should be activated. The same applies to IRSND, the encoder/transmitter.

I am running the module from an ESP32 and have activated all supported protocols.

IRMP also supports a feedback LED, but I didn't know how to include it using the device profiles.

### CODE REVIEW

**Comment by s-hadinger** [comment]
Could you please be more precise with '_proves to be more robust in decoding than IRremoteESP8266_'?

Any chance we could improve IRremoteESP8266 instead?

**Comment by eku** [comment]
Unfortunately this is not so easy to answer. If you look at the way of decoding, the IRremote and IRMP tick differently, which is an explanation.

From my own observation I can say that IRremote decodes almost none of the IR codes I use, although the protocols I use are supported and activated. IIRMP on the other hand has no problems with it.

I have been using IRMP for almost as long as the project exists and have also ported it to [Ethersex](http://ethersex.de). I haven't found any other IR decocer yet that comes close to IRMP.

**Comment by Jason2866** [comment]
Will you add AC protocols?

**Comment by eku** [comment]
> Will you add AC protocols?

I am not the author of IRMP. Support for new protocols please contact the author @UKW100 directly.

Concerning the support of AC protocols, I assume that they use the common IR protocols. A closer look at the protocols supported by IRMP shows that there are already several of them.

IRMP also supports RC protocols, but I have not activated them in my PR. This would need some more work and might come in a later PR.

**Comment by Jason2866** [comment]
This is not the Tasmota approach:
>  As decoding is done in the ISR, the IRAM of the ESP8266 is not sufficient to activate all 50 protocols, so only the required protocols should be activated. The same applies to IRSND, the encoder/transmitter.

Tasmota is designed to support ALL protocols in one binary. The resources IRMP needs in general is too high. IRMP is a powerfull decoder but it is "to heavy" to include in Tasmota

**Comment by eku** [comment]
> Tasmota is designed to support ALL protocols in one binary. The resources IRMP needs is in general too high. IRMP is a powerfull decoder but it is "to heavy" to include in Tasmota

I would still include it as an option and the user who can configure and compile Tasmota himself can choose to use IRMP instead.

**Comment by xatr0z** [comment]
Sorry in advance if this is the wrong place:
But as an end user i would very much like this feature. I found out about this pull request after discovering that IRremoteESP8266 unfortunatly doesnt support the exotic protocol used by my TV STB (multiple Dutch ISPs). Thank you @eku !

Therefore I would like to try to make my own build enabling IRMP_SUPPORT_RUWIDO_PROTOCOL. I'll be able to test if neccessary. 

Quick question: what do i need to enable in user_config_override.h:
* USE_IRMP, IRMP_PROTOCOL_NAMES, both?
* And do i still need to enable USE_IR_REMOTE and USE_IR_RECEIVE, and maybe even FIRMWARE_IR? (or will enabling this cause an conflict, loading both IRremoteESP8266 and IRMP?)

**Comment by eku** [comment]
@xatr0z I build the Tasmota firmware images myself. For IRMP I use my own image configuration. Therefore, I can not give a recommendation for the adaptation of the existing configurations.

That's what I'm using for ESP8266:

platformio_env.ini:
```
[env:eku-irmp]
extends = env:tasmota
build_flags = ${common.build_flags} -DMY_LANGUAGE=de_DE -DEKU -DMODULE_IRMP
```

user_config_override.h
```
#ifdef MODULE_IRMP
#undef CODE_IMAGE_STR
#define CODE_IMAGE_STR "eku-irmp"

#define USE_IRMP
#define IRMP_SUPPORT_RUWIDO_PROTOCOL  1 // for RX
#define IRSND_SUPPORT_RUWIDO_PROTOCOL 1 // for TX 
#define IRMP_PROTOCOL_NAMES 1 // optional
#endif  // FIRMWARE_IR_CUSTOM
```

Compile:
```
pio run -v -e eku-irmp
```

**Comment by frank-f** [comment]
Hi @eku,

I've tried to build this but I'm getting the following errors

```
In file included from tasmota/i18n.h:716:0,
                 from ~/Tasmota/tasmota/tasmota.ino:48:
tasmota/language/de_DE.h:466:0: warning: "D_ZIGBEE_NOT_STARTED" redefined [enabled by default]
 #define D_ZIGBEE_NOT_STARTED "Zigbee nicht gestartet"
 ^
In file included from ~/Tasmota/tasmota/tasmota.ino:48:0:
tasmota/i18n.h:523:0: note: this is the location of the previous definition
 #define D_ZIGBEE_NOT_STARTED "Zigbee not started"
 ^
```

and

```
~/Tasmota/tasmota/xdrv_45_irmp.ino:48:24: error: redeclaration of 'IE_NO_ERROR'
 enum Xdrv45_IrErrors { IE_NO_ERROR, IE_INVALID_JSON, IE_SYNTAX_IRSND, IE_UNKNOWN };
                        ^
~/Tasmota/tasmota/xdrv_05_irremote.ino:71:17: note: previous declaration 'IrErrors IE_NO_ERROR'
 enum IrErrors { IE_NO_ERROR, IE_INVALID_RAWDATA, IE_INVALID_JSON, IE_SYNTAX_IRSEND, IE_PROTO_UNSUPPORTED };
                 ^
~/Tasmota/tasmota/xdrv_45_irmp.ino:48:37: error: redeclaration of 'IE_INVALID_JSON'
 enum Xdrv45_IrErrors { IE_NO_ERROR, IE_INVALID_JSON, IE_SYNTAX_IRSND, IE_UNKNOWN };
                                     ^
~/Tasmota/tasmota/xdrv_05_irremote.ino:71:50: note: previous declaration 'IrErrors IE_INVALID_JSON'
 enum IrErrors { IE_NO_ERROR, IE_INVALID_RAWDATA, IE_INVALID_JSON, IE_SYNTAX_IRSEND, IE_PROTO_UNSUPPORTED };
                                                  ^
~/Tasmota/tasmota/xdrv_45_irmp.ino: In function 'uint8_t Xdrv45_IrSendIrSendCmndJson()':
~/Tasmota/tasmota/xdrv_45_irmp.ino:170:70: warning: enumeral mismatch in conditional expression: 'Xdrv45_IrErrors' vs 'IrErrors' [-Wenum-compare]
   return irsnd_send_data(&irsnd_data, false) == FALSE ? IE_UNKNOWN : IE_NO_ERROR;
                                                                      ^
~/Tasmota/tasmota/xdrv_45_irmp.ino: In function 'void Xdrv45_IrSendCmndResponse(uint32_t)':
~/Tasmota/tasmota/xdrv_45_irmp.ino:180:5: error: duplicate case value
     case IE_SYNTAX_IRSND:
     ^
~/Tasmota/tasmota/xdrv_45_irmp.ino:177:5: error: previously used here
     case IE_INVALID_JSON:
     ^
~/Tasmota/tasmota/xdrv_45_shelly_dimmer.ino: In function 'bool Xdrv45(uint8_t)':
~/Tasmota/tasmota/xdrv_45_shelly_dimmer.ino:854:6: error: redefinition of 'bool Xdrv45(uint8_t)'
 bool Xdrv45(uint8_t function) {
      ^
~/Tasmota/tasmota/xdrv_45_irmp.ino:251:6: error: 'bool Xdrv45(uint8_t)' previously defined here
 bool Xdrv45(uint8_t function)
      ^
```

Any idea what I might be doing wrong? I had to modify user_config_override.h, because the IRMP defines were conflicting with the defaults.

```
#define USE_IRMP
#undef IRMP_SUPPORT_RUWIDO_PROTOCOL
#undef IRSND_SUPPORT_RUWIDO_PROTOCOL
#define IRMP_SUPPORT_RUWIDO_PROTOCOL  1
#define IRSND_SUPPORT_RUWIDO_PROTOCOL 1
#define IRMP_PROTOCOL_NAMES 1
#endif
```

**Comment by eku** [comment]
Another push does not change the state `stale`. Strange.

**Comment by eku** [comment]
> This PR was automatically closed because of being stale.

@arendst  PR updated, Please reopen.

**Pull request closed without merging**
