### PR TITLE
Added support DS1624 and DS1621 termometer sensor (multiple and hotplug)

### LINKED ISSUE #7227: DS16xx temperature sensors
**Have you looked for this feature in other issues and in the wiki?**  

Yes

**Is your feature request related to a problem? Please describe.**  
I can't use DS1624 and other DS16xx sensors.

**Describe the solution you'd like**  
I can add support for this, if no one does it and does not mind.

**Describe alternatives you've considered**  
Buy another sensors? booooo

**Additional context**  
I think to get the LM75AD as example, or give me a better example

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by BASM**
## Description:

**Related issue:**  #7227

## Checklist:
* [x]  The pull request is done against the latest dev branch
* [x]  Only relevant files were touched
* [x]  Only one feature/fix was added per PR.
* [x]  The code change is tested and works
* [x]  The code change pass travis tests. **Your PR cannot be merged unless tests pass**
* [x]  I accept the [CLA]

### CODE REVIEW

**Comment by BASM** [comment]
Other then 1624 have another interface. I rename DS16xx to DS1624.

**Comment by ascillato** [comment]
Hi, please fix the conflicting files. Thanks.

**Comment by BASM** [comment]
Ok, I fixed conflicts. Conflicts from CHANGELOG only. Additionally I added support for multiple sensors on one i2c bus and hot plug support.

**Comment by ascillato** [comment]
Great!!! Thanks!!!

**Comment by BASM** [comment]
I hurried. Made a mistake in initialization. Corrected.

**Comment by arendst** [comment]
Thx for your PR.

I have some reservations:
- Current implementation does not check if the I2C address is already reserved by another sensor.
- I hate hot-plug. It's nice for a user. It's a pain for other sensors. Current implementation will always go out on the I2C bus looking for something on one of the 8 addresses. Nice on an arduino. A pain on Tasmota.

So in order to merge
- the I2C address reservation has to be implemented.
- Get rid of hot-plug as it takes too many resources every second. Just use detection once and if nothing found make sure the other function are not called as they take up valuable time.

**Comment by BASM** [comment]
Hello.

> * Current implementation does not check if the I2C address is already reserved by another sensor.

Yes, my fault. I will add check before I2cValidRead16 on the DS1624GetTemp();

> * I hate hot-plug. It's nice for a user. It's a pain for other sensors. Current implementation will always go out on the I2C bus looking for something on one of the 8 addresses. Nice on an arduino. A pain on Tasmota.

I agree, this is additional processor time. But one read on the one second is very low costs. The missing hotplug makes really more pain for the user than for processor time and firmware. User have to reset device (or push driver manually) if his sensors change or there are any problems with cable.

Tasmota is not ideal. Tasmota already have the "one second" problems with RULES if the firmware needs to make action when some sensor value less or greater threshold. It makes it cycle every time.

> * Get rid of hot-plug as it takes too many resources every second. Just use detection once and if nothing found make sure the other function are not called as they take up valuable time.

Sorry, but my ideals do not allow me to do this. Let's find a compromise.
For example:
* HotPlug every 10 seconds, not one
* HotPlug mode on the driver switch on by options
* HotPlug Drivers off by default
* Or else?

Usual using expects the use of 0, or 1, maximum 2 temperature sensors of different models. There is no need to scan the entire bus every second. Only 8 addresses.

I thnink, that developement without a hot plug doesnt make a sense. Sorry.

**Comment by BASM** [comment]
Support for switch off hotplug

**Pull request merged**
