### PR TITLE
Sbox support

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

initial support for ESP32-S3 SBOX (lite)

display and audio, (mp3, say, time, web radio)

ILI9342 display has inverted backpanel (new descriptor entry)
audio codec needs master clock (mclk)

#define ESP32S3_BOX

template:
{"NAME":"ESP32S3-SBOX","GPIO":[6210,4704,1,1,801,769,705,737,641,1,1,1,1,1,1,1,1,1,609,1,1,1,0,0,0,0,0,1,1,608,640,1,1,1,992,1,1,1024],"FLAG":0,"BASE":1}

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Review by s-hadinger — COMMENTED** [review]
Can you please send a PR to the upstream lib with the same changes?

**Comment by Jason2866** [comment]
@gemu2015  Can you check if the build here [https://jason2866.github.io/Tasmota-specials/](https://jason2866.github.io/Tasmota-specials/) is working?
Select S3 BOX and flash. Via Autoconfig the template and display.ini should be activated
Thx!

**Comment by gemu2015** [comment]
sorry not working. could flash but does not connect. can not monitor because serial usb port is not showing  up.

**Comment by Jason2866** [comment]
@gemu2015  Mhh, in this case the boards.json manifest needs a change from `-DUSE_USB_SERIAL_CONSOLE` to `-DUSE_USB_CDC_CONSOLE` if the inbuilt USB "Modem" (=CDC) is used. I suggest to rename the boards.json to `esp32s3cdc-box.json` to be inline with the Tasmota naming scheme.

The `env` is actually defined:
```
[env:tasmota32s3-boxusb]
extends                 = env:tasmota32s3
board                   = esp32s3boxusb
board_build.f_cpu       = 240000000L
build_flags             = ${env:tasmota32_base.build_flags}
                          -UFIRMWARE_TASMOTA32
                          -DFIRMWARE_LVGL
                          -DUSE_LVGL_OPENHASP
                          -DESP32S3_BOX
lib_extra_dirs          = lib/libesp32, lib/libesp32_lvgl, lib/lib_basic, lib/lib_i2c, lib/lib_audio, lib/lib_display, lib/lib_ssl
```

**Comment by gemu2015** [comment]
i compiled with this setup and -DUSE_USB_SERIAL_CONSOLE and it is working including console.

**Comment by gemu2015** [comment]
remark: i only have the lite version.  i thought the lite version only misses some features but now comparing the schematics i realized, that the audio codecs are different.  will have to check if we can have an automatic check which version is in use or will need a #define

**Comment by Jason2866** [comment]
> i compiled with this setup and -DUSE_USB_SERIAL_CONSOLE and it is working including console.

Tbh, idk why you see nothing on serial console. Used your provided boards.json. I suggested the change because you have no activity on the serial port

**Comment by gemu2015** [comment]
since box and box lite codecs have different I2C addresses i could easily implement this for both. i can't however test the box versions audio. Shall i pr anyhow ?

btw box touch driver is FT5X which is already implemented and may easily be switched on on I2C2 in descriptor as usual.

**Comment by Jason2866** [comment]
Tried the setting i suggested (`-DUSE_USB_CDC_CONSOLE`) using GPIO 19/20 (inbuilt USB Modem) with my S3.
Get serial output.
```
restart 1
12:21:18.101 CMD: restart 1
12:21:18.104 MQT: stat/sonoff-43625C/RESULT = {"Restart":"Restarting"}
12:21:19.420 APP: Restarting
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x420ee24e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x78
load:0x403c9700,len:0x974
load:0x403cc700,len:0x272c
SHA-256 comparison failed:
Calculated: d1c53dbc585cb6acea2b41b498f876eeabcfe00d69ebbd3faf7cb74e80cc54ef
Expected: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Attempting to boot anyway...
entry 0x403c98a8

00:00:00.001 CMD: Using USB CDC
00:00:00.001 HDW: ESP32-S3 (PSRAM)
00:00:00.018 UFS: FlashFS mounted with 308 kB free
00:00:00.041 CFG: Loaded from File, Count 81
00:00:00.087 BRY: Berry initialized, RAM used=3731 bytes
00:00:00.097 Project sonoff - Tasmota Version 12.0.2.3(tasmota)-2_0_4(2022-07-09T12:16:36)
00:00:00.587 WIF: Connecting to AP1 Jason_Home_WLAN Channel 9 BSSId 00:A0:57:2A:BD:19 in mode 11n as sonoff-43625C-0604...
00:00:05.417 WIF: Connected
00:00:05.670 HTP: Web server active on sonoff-43625C-0604 with IP address 192.168.2.100
```
Double check your setup, you are overlooking something.

**Comment by gemu2015** [comment]
i get the same SHA-256 error.  however my sbox is working without problems since a week or so.
do you have a hint what may cause this ?

**Comment by Jason2866** [comment]
Dont care about the CRC error, it is generated because esptool.py patches the firmware (before flashing) to the needed flash size (defined in boards.json). This brakes the CRC checksum. The Arduino bootloaders are compiled with 4MB as default settings. Since in most cases patching is done, i disabled the CRC checksum calculation in IDF sdkconfig. So ffff... is stored and expected. Maybe i find a way to disable the check completly. The orig. core does have this behaviour too.

**Pull request merged**
