### PR TITLE
Make light commands support json

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

**Related issue: https://github.com/arendst/Tasmota/issues/14568

Make all light commands to respond to json payload by using CmndJason()

```
HSBColor  {"HSBColor": "hhh, sss, bbb"}
Scheme {"Scheme": "sss"}
CT {"CT": "ccc"}
Power {"Power<x>": "ppp"}
Dimmer {"Dimmer": "ddd"}
```

The effective changes are much lighter than what the diff highlights.
It's just encapsulating each existing command code between:
```c
void CmndXxxxx(void)
{
  if ('{' == XdrvMailbox.data[0]) {
    CmndJson();
  } else {
  .... original code ....
  }
}
```

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.2.1
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Pls pay attention to the way CmndJson operates: all commands are parsed as backlog commands.

I suggest you do some testing with this PR and chk what happens when users start using this json command line prepended with a backlog command. I expect some great fun but it may also pass unnoticed.

Pls chk.

There was a reason I introduced a new command instead of just adding JSON parsing to every command (which in addition adds to the codebase already very tight on ESP8266).

**Comment by barbudor** [comment]
@arendst 
Alternative is to change the HA discovery message to refer the JSON command instead of still refering the original one that do not support json input. That would justify the introduction of the JSON command.
As of today JSON command cannot be used.

Do you prefer I change the discovery message to use cmnd/.../json ?

**Comment by arendst** [comment]
In the past there was no issue wirh HA and the command structure; The legacy HA code provides HA with all information it needed.

Then a new approach was introduced with two retained MQTT messages at restart. The information is decoded by a HA add-on providing HA with basic information.

The Domoticz people expect the same not knowing there is a Teasmota add-on in HA providing the information. Domoticz has another tool to talk to tasmota which was mentionend here before.

Then the JSON command line option: as it stands it does nothing more than wrapping the JSON command and send it to backlog. It will behave differently then a "normal" command if there are already commands in the backlog; the backlog commands will be processed first before the intended direct JSON command is performed. 

The functionality is different and could work well as long as the user is aware.

**Comment by barbudor** [comment]
let's drop this
I don't care neither of HA or Domoticz anyhow

**Pull request closed without merging**
