### PR TITLE
Add Interval to PMS5003 sensor to extend lifetime.

### PR DESCRIPTION
**Pull request by gururise**
## Description:
User has option to take readings either continuously (current default) or at WAKEUP intervals of between 60-65535 seconds. If the sensor is set to take reading at intervals, it will be put to sleep and woken up 30 seconds prior to the reading being taken (the **WARMUP** period), then the reading will be taken and the sensor put back to sleep until 30 seconds prior to the next reading.  To use this interval feature, TX pin must be connected.  If user only sets up RX pin, the default ACTIVE sensor mode will be used.

NOTE:  I used an existing setting variable (mcp230xx_int_timer) for the PMS5003 interval period because I am not familiar enough with the settings variables to create a new variable and update the version scheme properly.  Would appreciate advice/help on creating a new uint16_t to hold the wakeup interval in seconds.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>
Enhancement #8097 

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core Tasmota_core_stage
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Current implementation will break gpio numbering.

**Comment by gururise** [comment]
> Current implementation will break gpio numbering.

Thanks for the feedback.  I'm brand new to Tasmota and am still trying to wrap my head around your gpio numbering methodology and the settings variables.

Hope you can provide a bit of guidance with two issues:

1. I need to add a TX pin for the PMS sensor.  In order to not break GPIO numbering, should the TX pin (which currently doesn't exist in the tasmota_template.h) be added to the end of the template instead?

2. I also need to add a new uint16_t in settings.h file to handle the interval time.  Doing so would appear to cause issue with the version numbering scheme.  What is the proper way to go about this?

**Comment by arendst** [comment]
1. yes
2. add uint16_t at line 508 and decrement free_f18[132] to 130

**Comment by gururise** [comment]
> 1. yes
> 2. add uint16_t at line 508 and decrement free_f18[132] to 130

Moved the [TX Pin definition](https://github.com/gururise/Tasmota/blob/54f7cf475d7ea4f0493a58ea8f543d4a2e24b5c8/tasmota/tasmota_template.h#L230) to the end of the enum in tasmota_template.h

After doing that, pin[GPIO_PMS5003_TX] is always [greater than 99](https://github.com/gururise/Tasmota/blob/54f7cf475d7ea4f0493a58ea8f543d4a2e24b5c8/tasmota/xsns_18_pms5003.ino#L260) (ie. isn't detected) even when assigned in the web configuration:
image

The previous [commit](https://github.com/arendst/Tasmota/pull/8128/commits/8d1322984c8c3be6049d63d3368c4c7c34aca5b2), which broke gpio pin numbering, worked and the pin[GPIO_PMS5003_TX] was less than 99 when assigned in the web interface.

Is there something else that needs to be done?

**Comment by gururise** [comment]
Tested code changes on core with PMS5003 sensor and everything works. The default behavior is current functionality (RX only, read data while sensor is in ACTIVE mode) of continuous sensor readings.

New functionality allows user to set a read interval to prolong the life of the sensor by putting the sensor to sleep between reads:
`Sensor18 <read interval in seconds>`

30 seconds prior to the read interval (aka the WARMUP period) the sensor will turn on to allow it to warm up and take a reading.  The read interval can vary from 60 to 65535 seconds.

Hope this is useful for people!

**Comment by barbudor** [comment]
When teleperiod is different from 10 or 300, the DeepSleep will occur at the 2nd tele period
Example with teleperiod 35 and DeepSleepTime 120 (just for the purpsose of the test).

ONe possibility could be to discard the 1st tele, leaving the time for the sensor to warmup, then measure is taken, SENSOR sent and back to sleep.
So the warm-up time would be spent awaken.

```
00:00:00 Project tasmota dev-4119 Version 8.2.0.3(bsensors)-STAGE
00:00:00 WIF: Connecting to AP1 BNETWLAN Channel 1 BSSId 50:D4:F7:C0:2E:B0 in mode 11N as dev-4119...
00:00:01 WIF: Connected
00:00:01 HTP: Web server active on dev-4119 with IP address 192.168.168.199
20:56:04 MQT: Attempting connection...
20:56:04 MQT: Connected
20:56:04 MQT: tele/dev-4119/LWT = Online (retained)
20:56:04 MQT: cmnd/dev-4119/POWER = 
20:56:04 MQT: stat/dev-4119/RESULT = {"POWER":"OFF"}
20:56:04 MQT: stat/dev-4119/POWER = OFF
20:56:08 MQT: tele/dev-4119/STATE = {"Time":"2020-04-13T20:56:08+02:00","Uptime":"0T00:00:09","UptimeSec":9,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"BNETWLAN","BSSId":"50:D4:F7:C0:2E:B0","Channel":1,"RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:03"}}
20:56:08 MQT: tele/dev-4119/SENSOR = {"Time":"2020-04-13T20:56:08+02:00","Switch1":"ON","ANALOG":{"Range":35}}
20:56:43 MQT: tele/dev-4119/STATE = {"Time":"2020-04-13T20:56:43+02:00","Uptime":"0T00:00:44","UptimeSec":44,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"BNETWLAN","BSSId":"50:D4:F7:C0:2E:B0","Channel":1,"RSSI":82,"Signal":-59,"LinkCount":1,"Downtime":"0T00:00:03"}}
20:56:43 MQT: tele/dev-4119/SENSOR = {"Time":"2020-04-13T20:56:43+02:00","Switch1":"ON","ANALOG":{"Range":35}}
20:56:43 MQT: stat/dev-4119/RESULT = {"DeepSleep":{"Time":"2020-04-13T20:58:00","Epoch":1586804280}}
20:56:46 APP: Sleeping
```

**Comment by wwiill** [comment]
> Tested code changes on core with PMS5003 sensor and everything works (should also work for the PMS3003 and PMS7003, but I don't have them to test). The default behavior is current functionality (RX only, read data while sensor is in ACTIVE mode) of continuous sensor readings and only requires the connection of the RX pin.
> 
> New functionality allows user to set a read interval to prolong the life of the sensor by putting the sensor to sleep between reads. This will require connecting both the RX & TX pins and changing the setting:
> `Sensor18 <read interval in seconds>`
> 
> 30 seconds prior to the read interval (aka the WARMUP period) the sensor will turn on to allow it to warm up and take a reading. The read interval can vary from 60 to 65535 seconds. A read interval less than 60 will default to continuous readings (ie active mode).
> 
> Hope this is useful for people!

Hi, sorry for the noob question but how do you configure the read interval from the Tasmota web interface?

**Comment by murraythegoz** [comment]
> > Tested code changes on core with PMS5003 sensor and everything works (should also work for the PMS3003 and PMS7003, but I don't have them to test). The default behavior is current functionality (RX only, read data while sensor is in ACTIVE mode) of continuous sensor readings and only requires the connection of the RX pin.
> > New functionality allows user to set a read interval to prolong the life of the sensor by putting the sensor to sleep between reads. This will require connecting both the RX & TX pins and changing the setting:
> > `Sensor18 <read interval in seconds>`
> > 30 seconds prior to the read interval (aka the WARMUP period) the sensor will turn on to allow it to warm up and take a reading. The read interval can vary from 60 to 65535 seconds. A read interval less than 60 will default to continuous readings (ie active mode).
> > Hope this is useful for people!
> 
> Hi, sorry for the noob question but how do you configure the read interval from the Tasmota web interface?

You have to open a command line from the web interface (not sure where the menu entry for command line is, look aroundf in menus) and send the command "Sensor18 <read interval in seconds>"

**Comment by gionag** [comment]
I think there's a little issue when using Sensor18 option with tasmota discovery protocol on hassio.

i have a wemos D1 with only one pms5003 connected, both rx and tx.
everything works good and i am able to integrate the sensor on hassio.

the problem arise when i set "Sensor18 120". While the wemos is kept powered on everything works. but when i restart the tasmota firmware, then the entitites on hassio became unavailable ( "entity not available" reported on the card ).

After reset, if i log back to the console of tasmota and set "SO19 off" (Setoption19 off) everything starts working again (values are reported back once again), until next reboot.

To double check, if i disable the sensor18 option (with "sensor18 off") then i am able to reboot anytime and the values are kept "available" and nothing broke...

**Comment by Lassska** [comment]
Hello, if we had only one sensor, we consider it to be correctly calibrated. Of the two adjacent sensors, the newer one shows the lower values I searched for offset at Tasmota but there are no commands. How could I correct the read values ​​in Home Assistant?
Screenshot_20240523_155940_Chrome

**Pull request merged**
