### PR TITLE
Discover Echo 2G Fix

### PR DESCRIPTION
**Pull request by reloxx13**
-add meta service xml for echo plus 2g (maybe not neccessery, needs more testing)
-add switch between belkin for type1 devices and rootdevice for type2 devices
-st and usn response change depending on the switch

#1357, #1450 

tested and working with echo dot 2g, echo 2g, echo plus 2g
waiting for test result for echo show 2g

Restart Echo Device once if nothing gets found (Alexa is blocking devices if the response was wrong in past).

pre-build firmware (all languages): 
[ALL-firmware-5.10.0g-fix-echo-type2-v4.zip](https://github.com/arendst/Sonoff-Tasmota/files/1596530/ALL-firmware-5.10.0g-fix-echo-type2-v4.zip)

### CODE REVIEW

**Comment by reloxx13** [comment]
> 22:53:52 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 22:53:52 UPP: WeMo TYPE: rootdevice
> 22:53:52 UPP: WeMo Antwort gesendet zu 192.168.178.1:42100

not working with echo show 2g :S

the echo show seems to not send an udp request.
this is a log while discovering from echo show and their are only fritzbox discovering requests inside. 


> 21:46:46 LOG: SerialLog 0, WebLog 4, SysLog 0, LogHost domus1, LogPort 514, TelePeriod 300
> 
> 21:46:46 HTP: Einstellungen
> 21:46:47 HTP: Hauptmenü
> 21:46:47 CFG: in Flash gespeichert am F9, zählen 165, Bytes 1648
> 21:46:48 RSL: ERGEBNIS = {"POWER":"OFF"}
> 21:46:48 RSL: POWER = OFF
> 21:46:50 HTP: Einstellungen
> 21:46:51 CFG: in Flash gespeichert am F8, zählen 166, Bytes 1648
> 21:46:53 HTP: Gerät konfigurieren
> 21:46:57 HTP: Einstellungen
> 21:46:59 HTP: Logging konfigurieren
> 21:47:02 HTP: Einstellungen
> 21:47:04 HTP: Sonstige Konfiguration
> 21:47:06 HTP: Einstellungen
> 21:47:09 HTP: Hauptmenü
> 21:47:11 HTP: Konsole
> 21:47:13 WIF: Prüfe Verbindung...
> 21:47:13 WIF: verbunden
> 
> 21:47:16 UDP: M-SEARCH Packet received
> 21:47:16 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:47:21 UDP: M-SEARCH Packet received
> 21:47:21 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:47:26 UDP: M-SEARCH Packet received
> 21:47:26 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:47:31 UDP: M-SEARCH Packet received
> 21:47:31 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:47:36 UDP: M-SEARCH Packet received
> 21:47:36 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:48:13 WIF: Prüfe Verbindung...
> 21:48:13 WIF: verbunden
> 21:49:14 WIF: Prüfe Verbindung...
> 
> 21:49:14 WIF: verbunden
> 
> 21:49:17 UDP: M-SEARCH Packet received
> 21:49:17 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:49:22 UDP: M-SEARCH Packet received
> 21:49:22 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:49:27 UDP: M-SEARCH Packet received
> 21:49:27 m-search*http/1.1x
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:49:32 UDP: M-SEARCH Packet received
> 21:49:32 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:49:37 UDP: M-SEARCH Packet received
> 21:49:37 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:49:58 UPP: Multicast deaktiviert
> 21:50:04 DNS: initialisiert
> 21:50:04 UPP: Multicast (wieder-)verbunden
> 
> 21:50:09 UDP: M-SEARCH Packet received
> 21:50:09 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:service:wlanconfiguration:2
> 
> 21:50:09 UDP: M-SEARCH Packet received
> 21:50:09 m-search*http/1.1x
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:service:wlanconfiguration:3
> 
> 21:50:09 UDP: M-SEARCH Packet received
> 21:50:09 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"x
> mx:5
> st:urn:dslforum-org:device:landevice:1
> 
> 21:50:09 UDP: M-SEARCH Packet received
> 21:50:09 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:mediaserver:1
> 
> 21:50:14 UDP: M-SEARCH Packet received
> 21:50:14 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:service:wlanconfiguration:2
> 
> 21:50:14 UDP: M-SEARCH Packet received
> 21:50:14 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:service:wlanconfiguration:3
> 
> 21:50:14 UDP: M-SEARCH Packet received
> 21:50:14 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:device:landevice:1
> 
> 21:50:14 UDP: M-SEARCH Packet received
> 21:50:14 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:mediaserver:1
> 
> 21:50:19 UDP: M-SEARCH Packet received
> 21:50:19 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:service:wlanconfiguration:2
> 
> 21:50:19 UDP: M-SEARCH Packet received
> 21:50:19 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:service:wlanconfiguration:3
> 
> 21:50:19 UDP: M-SEARCH Packet received
> 21:50:19 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:dslforum-org:device:landevice:1
> 
> 21:50:19 UDP: M-SEARCH Packet received
> 21:50:19 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:mediaserver:1
> 
> 21:50:23 WIF: Prüfe Verbindung...
> 21:50:23 WIF: verbunden
> 
> 21:51:17 UDP: M-SEARCH Packet received
> 21:51:17 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 
> 21:51:22 UDP: M-SEARCH Packet received
> 21:51:22 m-search*http/1.1
> host:239.255.255.250:1900
> man:"ssdp:discover"
> mx:5
> st:urn:schemas-upnp-org:device:avm-aha:1
> 21:51:23 WIF: Prüfe Verbindung...
> 21:51:23 WIF: verbunden

**Comment by arendst** [comment]
The missed echo show 2g may ne caused by a too small UDP buffer.

On line 26 the UDP buffer is defined as ``UDP_BUFFER_SIZE 200``

You might want to raise it too 300 to see if the request is in the rest of the M-SEARCH packet.

**Comment by reloxx13** [comment]
Unfortunately i dont own the device myself, so i cannot sniff the network to check what the show is sending.
the sonos and fire tv stick with alexa remote are not working, too :S

ill give feedback if i get some more infos.

**Comment by jimjimminy** [comment]
FYI this https://github.com/bwssytems/ha-bridge/issues/860 suggests a timing issue with the UPNP discovery as being a potential cause

**Comment by arendst** [comment]
Working on the timing issue. About to release soon.

**Comment by jimjimminy** [comment]
Great news thanks, I tested the 5.10.0g-fix-echo-type2-v4 build last night and it wasn't discovered by my Echo 2. Hopefully the timing issue will resolve this. Happy to test this out if it helps.

**Pull request closed without merging**
