### PR TITLE
Fix broken js introduced in #15515

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

**Related issue (if applicable):** fixes #15515 #15543

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Now the ESP32 will fail don't you think as it doesn't have a ``<script>`` start anymore....

**Comment by arendst** [comment]
Ah I see it's duplicating the ESP8266 script. In that case we need #ifdef ESP32 around both versions in webserve.

**Comment by s-hadinger** [comment]
I'm not sure to understand. Only part of the JS changes with ESP32

**Comment by arendst** [comment]
Yes. Sorry My fault. I forgot where the #ifdefs were. No problem.

**Pull request merged**
