### PR TITLE
Zigbee firmware for Sonoff-ZB-Pro v20230507

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Update Zigbee firmware for Sonoff-ZB-Pro to the latest 20230507 from Koenkk. This firmware has been patched to support the specific BSL DIO of Sonoff-ZB-Pro. DO NOT FLASH THE FIRMWARE FROM KOENKK WITHOUT THIS PATCH.

Flashing the new version may need to change PanID and repair all devices.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.10
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by darkxst** [comment]
was this meant to be updated in the zbpro firmware build? or not yet?

**Comment by Jungo495** [comment]
hi
got timeout after
import sonoff_zb_pro_flasher as cc
cc.load("SonoffZBPro_coord_20230507.hex")
cc.check()
tryed reset conf, restart
used flasher from https://github.com/arendst/Tasmota/tree/development/tasmota/berry/zigbee

**Comment by PBrunot** [comment]
Is there a way to save settings before to flash this firmware on my existing device ? to avoid reassociating all devices in my home.

**Comment by s-hadinger** [comment]
Not to my knowledge. You need to pair again

**Pull request merged**
