### PR TITLE
display ini to utouch

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

replace touch entries with universal touch code

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@arendst Can you increase patch version number when merging this (and the other related PR)?

**Comment by s-hadinger** [comment]
Awesome.
My only concern is that we don't gracefully manage the transition. If we include Universal Touch in the pre-compiled binaries, then all the previous configuration fail until the user updates the display.ini - and they can't update them unless they migrated to Universal Touch screen.

Is there a way that both changes don't need to be done at the same time?

Or maybe we need to leaves `:TS` for now until user upgrade to latest firmware?

**Comment by Jason2866** [comment]
Maybe a transition version, which has dedicated and Utouch driver enabled?
When this version is launched it modifies the Utouch part in display.ini and restarts with changed settings and does some touch tests (Berry script)?

**Comment by s-hadinger** [comment]
Now that uTouch is default, we can merge

**Pull request merged**
