### PR TITLE
Fix Windows (crlf) related compilation error

### LINKED ISSUE #144: compile error
Hi all,
  For the last several versions, I've been getting this error when trying to compile using PlatformIO on Windows 7...
```
D:/Development/GitHub/Sonoff-Tasmota/sonoff/sonoff.ino: In function 'void stateloop()':
D:/Development/GitHub/Sonoff-Tasmota/sonoff/sonoff.ino:3529:19: error: 'sl_blank' was not declared in this scope
D:/Development/GitHub/Sonoff-Tasmota/sonoff/webserver.ino: In function 'void handleUploadDone()':
D:/Development/GitHub/Sonoff-Tasmota/sonoff/webserver.ino:1963:15: error: 'sl_blank' was not declared in this scope
D:/Development/GitHub/Sonoff-Tasmota/sonoff/webserver.ino: In function 'void handleUploadLoop()':
D:/Development/GitHub/Sonoff-Tasmota/sonoff/webserver.ino:2053:15: error: 'sl_blank' was not declared in this scope
```

I've been adding `void sl_blank(byte state);` to the top of sonoff.ino in order to get it to compile, and everything seems to work fine after that. I've gone as far as to uninstall PlatformIO and delete the Tasmota code and reinstall fresh without making any changes at all and I still get the error. 

Can anyone give me any ideas as to what may be causing it? 

Thanks, in advance,
Kevin Fonda

### PR DESCRIPTION
**Pull request by ThomDietrich**
Closes #144

The issue stays unclear to me. This "style fix" solved it.

### CODE REVIEW

**Comment by arendst** [comment]
I guess changing it from this:
```
void sl_blank(byte state)
/*
 * Called by interrupt disabling routines like OTA or web upload
 * state = 0: No blank
 *         1: Blank led to solve flicker
 */
{
  if (sysCfg.module == SONOFF_LED) {
```
to this
```
void sl_blank(byte state)
{
/*
 * Called by interrupt disabling routines like OTA or web upload
 * state = 0: No blank
 *         1: Blank led to solve flicker
 */
  if (sysCfg.module == SONOFF_LED) {
```
would also solve the problem.

**Comment by ThomDietrich** [comment]
Did you see my [explanation](https://github.com/arendst/Sonoff-Tasmota/issues/144#issuecomment-284822694) over in the issue?

Yes moving the `{` above the comment also solves the issue. No the space is not to blame. You can have as many spaces as you like in your code. As I stated in the issue, the problem only occurs with a four+ line block comment. Very strange.

The PR follows [common style standards](https://google.github.io/styleguide/cppguide.html#Comments) but you can also go with the other solution, that's of course up to you ;) You have write access to this PR.

**Comment by arendst** [comment]
Already changed to this one in next release ;-)
```
void sl_blank(byte state)
{
// Called by interrupt disabling routines like OTA or web upload
// state = 0: No blank
//         1: Blank led to solve flicker
```

**Comment by ThomDietrich** [comment]
No love for PRs? :smile_cat:

**Pull request closed without merging**
