### PR TITLE
NimBLE v1.36

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

Prep BLE for S3.
EDIT: BLE does compile now for the S3
Thx @Staars  for the compile fix

@arendst  Currently for testing of stability of the new version. Should not be merged before next release
@Staars @btsimonh Please test

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.2.1
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Staars** [comment]
Seems to work here.
But I prefer to not interact with the NVS inside Tasmota in an external library and would suggest to change:
`#define CONFIG_BT_NIMBLE_NVS_PERSIST 0`
in `nimconfig.h`
(I always change this in my custom builds anyway)

**Comment by Jason2866** [comment]
Confirmed working.
unknown
 Thx @digiblur for testing

**Comment by fightforlife** [comment]
I compiled this PR in my tasmota fork yesterday. Till now I had one reboot in 24h. I will report back, if I notice anything strange. (I use BLE for the mi sensors and eq3 valves)

**Comment by fightforlife** [comment]
I had one unplanned reboot since my last post, after around 48hours. Stability seems good to me, cmparable to 9.5.0.8.

**Comment by barbudor** [comment]
4.5 days uptime since Feb 6th. Just 1 single freeze less than 2 hours after flashing but then no problems

**Comment by arendst** [comment]
Pls rebase first before I can merge.

**Comment by Jason2866** [comment]
@arendst Conflicts solved

**Pull request merged**
