### PR TITLE
Fixed typos in comments

### PR DESCRIPTION
**Pull request by Zefiro**
Fixed some typos and replaced one if/else with a ternary operator.

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

Please, split your new dragon effect into a new PR.

As the Template for Pull Request asks, please add just one feature or fix type per PR, in order to make it easier to track future issues.

PR Template:

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest dev branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

**Comment by Jason2866** [comment]
If you have splitted take care of the CI tests. Your code fails in some

**Comment by Zefiro** [comment]
Now that was unexpected :(

I had deliberately created commit 698c53f first, triggered the cross-project PR, ensured that all tests were green, and expected it would now live on independently of any further changes to my own forked project.
Of course my additions for my local Neopixel project were not intended to be merged back into the upstream project. 
I'm sorry for the confusion.

I've temporarily made a revert-commit, though now one localisation failed to start testing ("read ECONNRESET"). Is there a way to retry this test?

**Comment by ascillato2** [comment]
Thanks for splitting PRs.

> Is there a way to retry this test?

Done. I have Re-run all tests.

**Pull request merged**
