### PR TITLE
Implement ZFS version checking and create a new ZFS version with zig4 (fix #17030)

### LINKED ISSUE #17030: zbbridge - device list is broken when EEPROM storage is used
### PROBLEM DESCRIPTION
List of devices (including their pretty names) is lost when device resets. The EEPROM is formatted to have `ZIGB_NAME2` and `saveZigbeeDevices()` is looking for `ZIGB_NAME4`. This causes `saveZigbeeDevices()` to silently fall thhrough and nothing is saved. The issue was likely introduced in commit f0cf998ca417d15c5dcf95f9eb7aa67fc6088c5a.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): Sonoff Zbbridge
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
1. Set device name (eg `ZbName 0x1234,testing`)
2. restart/powercycle device
3. The device won't be shown after reboot, and once it broadcasts again, it will be again visible as 0x1234

### EXPECTED BEHAVIOUR
Device name should be retained across reboots.

### ADDITIONAL CONTEXT

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by Mrkvak**
## Description:

**Related issue (if applicable):** fixes #17030

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
I'm not sure this is the right thing to do. Since ZigV4, Tasmota does not store to EEPROM anymore and stores to file-system instead. Do you have a file-system working on your device ?

**Comment by Mrkvak** [comment]
Honestly, me neither, I'm really new to the project. The I don't have any kind of filesystem working on the device since it has only 1MB of flash (Sonoff Zigbee Bridge). 

I understand EEPROM has a lot of disadvantages, but having it as a fallback doesn't sound that bad to me. In that case, it would probably make sense to move EEPROM block in saveZigbeeDevices() at xdrv_23_zigbee_4c_devices.ino:460 to the last in the sequence. (The same applies to  hydrateDevicesData() and hibernateAllData() in xdrv_23_zigbee_4b_data.ino).

And I guess keeping the EEPROM ZigV2 *might* work as well (but honestly I don't know the codebase that much) - but that would mean at least adding back support for V2 hibernateDevice()...

**Comment by s-hadinger** [comment]
It's hard to maintain compatibility that's why I decided to move to File-system. Can you flash with the ZBBridge stock firmware. It uses 2MB and a file system.

**Comment by Mrkvak** [comment]
Okay, in that case maybe I'm doing something wrong, because I've erased the chip entirely and flashed the tasmota-zbbridge.bin firmware from http://ota.tasmota.com/tasmota/tasmota-zbbridge.bin using serial connection and the device persistence is not working at all.

**Pull request closed without merging**
