### PR TITLE
littlefs needs SPIFFS Partition 

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

change only for odroid go

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
@gemu I'm not sure if this is what you planned. I would expect that big filesystem partitions would always use ffat...

Pls let me know if I'm wrong.

**Comment by Jason2866** [comment]
@arendst  If littelfs is not the file system for all i have misunderstood the way it is planned wrong
This comment would make no sense https://github.com/arendst/Tasmota/pull/10334#issuecomment-754031542

**Comment by arendst** [comment]
> FFAT is deprecated for Tasmota and only there for backwards compability

Nice to know :-)) but I agree.

I suppose FFat is still used on SDCard to make them interchangeable with PC/Mac.

**Comment by gemu2015** [comment]
no @Jason2866  is right. since little fs assumes spiffs partitions we don't need ffat partitions any more,
for people with OTA updates and ffat partitions we have the fallback of ffat handler.
this is only for flash file system, SD driver uses FAT32 of course no change

**Comment by arendst** [comment]
Thx.

**Comment by gemu2015** [comment]
@Jason2866 
from now odroid would also work with sd card !

**Comment by Jason2866** [comment]
@gemu2015  Nice!

**Pull request merged**
