### PR TITLE
Implement capability for setting CORS to a specific website instead o…

### PR DESCRIPTION
**Pull request by shantur**
Implement capability for setting CORS to a specific website instead of just enable for all websites

## Description:

This feature makes user keep device secure by just enabling CORS for a specific website / url.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Implementation is kind of overkill.

**Comment by arendst** [comment]
Reconsidering after discussion

**Comment by shantur** [comment]
I can will it to fix the conflicts

**Comment by arendst** [comment]
Well at least remove the GUI parts. Takes too much code space and command line would do.

**Comment by shantur** [comment]
@arendst : The GUI changes only need 112 bytes and allows user to setup CORS before losing access to settings.

**Comment by shantur** [comment]
@arendst : I have updated my changes again to new version. Is it possible to get this merged in?

**Comment by shantur** [comment]
@arendst : Thanks

**Pull request merged**
