### PR TITLE
Sonoff L1

### LINKED ISSUE #4935: Sonoff L1 LED Controller
Hello,

I have succesfully automated most functions in my home using Tasmota and the 4CH PRO R2 Sonoff modules. (Thanks for all the great work programming and documenting Tasmota BTW!) 
Now, I would like to add a few LED strips.

It might be that I am overlooking but is the Sonoff L1 LED Strip Controller not in the supported devices list? (see: https://www.banggood.com/Sonoff-L1-Smart-2M-5M-SMD5050-RGB-LED-Strip-LightWiFi-ControllerPower-Supply-Work-With-Alexa-DC12V-p-1396771.html?rmmds=search&ID=4775844707&cur_warehouse=CN )

I can see in the supported devices lists, some other LED controllers are supported from other vendors, but, as I found Sonoff to be quite reliable I wanted to stick with their hardware.

thanks!

### PR DESCRIPTION
**Pull request by reef-actor**
## Description:
Add support for Sonoff L1 RGB LED controller.  Color, dimmer and power is supported.

**Related issue (if applicable):** fixes #4935
This PR supercedes PR #5618

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by reef-actor** [comment]
Home Assistant config used:
```
- platform: mqtt
  name: 'RGB strip'
  command_topic: 'cmnd/rgbstrip/POWER'
  state_topic: 'stat/rgbstrip/POWER'
  payload_on: 'ON'
  payload_off: 'OFF'

  brightness_command_topic: 'cmnd/rgbstrip/DIMMER'
  brightness_scale: 100
  brightness_state_topic: 'stat/rgbstrip/RESULT'
  brightness_value_template: '{% if value_json.Dimmer is defined %}{{ value_json.Dimmer }}{% else %}{{states.light.rgb_strip.attributes.brightness / 255 * 100 }}{% endif %}'

  rgb_command_topic: 'cmnd/rgbstrip/COLOR2'
  rgb_command_template: '{{ "%02x%02x%02x" | format(red, green, blue)}}'
  rgb_state_topic: 'stat/rgbstrip/RESULT'
  rgb_value_template: '{% if value_json.Color is defined %}{{ value_json.Color[0:2]|int(base=16) }},{{ value_json.Color[2:4]|int(base=16) }},{{ value_json.Color[4:6]|int(base=16) }}{% else %}{{ states.light.rgb_strip.attributes.rgb_color|join(",") }}{% endif %}'

  availability_topic: 'tele/rgbstrip/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
```

**Comment by arendst** [comment]
Thx for your input. A few remarks before merging is possible.

- Do not use sscanf as it increases code size drastically. It includes a floating point library I do not want to use. Verify your compiled code size with and without your changes. Find a replacement for sscanf like demonstrated in support_rtc.ino function GetBuildDateAndTime.
- Do not insert a module in the module chain SupportedModules and kModules in sonoff_template.h as it will break support of all previous module numbers. Insert them at the end of the tables.
- Do not update  _changelog.ino as the goal is to update as few files as possible.

**Comment by reef-actor** [comment]
Should "(Also remember to update changelog.ino file)" be removed from the PR template?

**Comment by arendst** [comment]
Thx again for your updates.

Regarding changelog.ino you're probably right. I will check the PR template and change it to just adding a line to changelog.ino without adding a version bump (as I prefer to select the bumps myself).

**Comment by edelmannj** [comment]
Hi all,
the code looks good. The only i miss is how to switch in flash mode if i want to flash the tasmota code to the L1? i didn't find it. :-(

**Comment by ascillato** [comment]
Hi, for general questions please use the Tasmota Support Chat. Thanks.

**Pull request merged**
