### PR TITLE
repair float int problems for MI Flora moisture and fertility

### PR DESCRIPTION
**Pull request by d0m1n1qu3**
## Description:

fix an issue with float and int converts for ESP32 MiFlora

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core ESP8266 V.2.7.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Staars** [comment]
Looks good to me.

**Comment by s-hadinger** [comment]
I thought `%f` was disabled in printf to reduce code size. It's not true anymore?

**Comment by Staars** [comment]
I could have sworn, that I tested this a few days ago in another case, but as you mention this, I start to remember.
I am not able to test it on real hardware before tomorrow afternoon.

**Comment by d0m1n1qu3** [comment]
hi. i also can change it to use only int and %d. this code is only for the ESP32 is there realy a problem with %f ? but if, good to know. :)

**Comment by Staars** [comment]
>  only for the ESP32

Ahh, I guess that is the crucial point :)

**Comment by arendst** [comment]
Indeed esp32 only

**Pull request merged**
