### PR TITLE
Open Code from https://github.com/esp8266/Arduino

### PR DESCRIPTION
**Pull request by Jason2866**
Possibility to fetch always the latest Open Code from https://github.com/esp8266/Arduino branch Master

### CODE REVIEW

**Comment by arendst** [comment]
What's the difference with 2.5.0? That is also linked to your repository?

**Comment by Jason2866** [comment]
The already included is the 2.5.0 beta version.
This PR links always to latest dev version

**Comment by arendst** [comment]
And what's the difference between latest dev and the already available stage?

**Comment by Jason2866** [comment]
At the moment none. Some time ago the platformio crew used older builds

**Pull request closed without merging**
