### PR TITLE
Moved from cross-signed X3 to cross-signed R3 Lets encrypt certificate

### PR DESCRIPTION
**Pull request by WillemJansen**
Committer: Willem Jansen <willem@jansen.xyz>

## Description:
Given the recent retirement of the Let's Encrypt X3 certificate (see https://letsencrypt.org/certificates/), no new LE-certificate can be recognized as valid by Tasmota anymore. Therefore, I upgraded the trust anchor to the cross-signed R3 certificate.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
How do you know there aren't any valid X3 signed certificates out there? Shouldn't we wait for 3 months for all previously issues certificates to expire?

**Comment by xhess** [comment]
Duplicate of #10082

**Comment by WillemJansen** [comment]
This might be a valid concern, but could easily be healed by re-requesting a LE certificate (certbot  renew). The alternative would be to have both x3 and r3 in the Code 

In my opinion, the once-and-for-all-solution should involve the EC-keys, given that would speed up Tal ops, too.

**Comment by s-hadinger** [comment]
Since PR #10086 was merged, Tasmota contains both X3 and R3 CA. We will remove X3 when all certs are renewed, which I hope will happen in 3 months max.

From my previous tests, ECDSA is much slower than ECDHE with RSA certificate. Do you have other numbers?

**Comment by arendst** [comment]
Duplicate from #10086

**Pull request closed without merging**
