### PR TITLE
Initial support for shutter button control

### PR DESCRIPTION
**Pull request by to-scho**
New command "ShutterButton<x> <a> <b> <c> <d> <e> <f> <g> <h> <i> <j>" added that allows to assign a tasmota button <x> to control shutter <a>.

Single press button shutter is set to position <b>.  Double press button shutter is set to position <c>. Tripple press button shutter is set to position <d>. Hold button shutter is set to position <e>. Disabling any button action is given by <b> ... <e> equal to "-". Any press of the button while the shutter is moving will immediately stop that shutter.

Global steering of all your shutters at home is supported by MQTT. By any button action an MQTT command can be initiated to the <grouptopic> of the device. For single press button this can be enabled by <f> equal to "1". Disabling is indicated by <f> equal to "0". Double to hold actions are given by <g> ... <i>, correspondingly. When <j> is equal to "0" only "cmnd/<grouptopic>/Shutterposition<y> ..." with <y>=<x> is fired. When <j> is equal to "1" <y>=1...4 is used to control any shutter number of a tasmota device having same <grouptopic>.

Easy setup for an "up" button:
ShutterButton<x> <a> up (same as ShutterButton<x> <a> 100 50 74 100 0 0 0 1 1)
Single press will move shutter up to 100%, double press to 50% and tripple press to 74%. Holding the button for more than the hold time (SetOption32) moves all shutters with same <grouptopic> up to 100%.

Easy setup for an "down" button:
ShutterButton<x> <a> down (same as ShutterButton<x> <a> 0 50 24 0 0 0 0 1 1)
Single press will move shutter down to 0%, double press to 50% and tripple press to 24%. Holding the button for more than the hold time (SetOption32) moves all shutters with same <grouptopic> down to 0%.

Easy setup for an "updown" button:
ShutterButton<x> <a> updown (same as ShutterButton<x> <a> 100 0 50 - 0 0 0 0 0)
Single press will move shutter up to 100%, double press down to 0% and tripple press to 50%. No hold action and no other shutter control by MQTT.

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
I wish I had a shutter....

**Comment by Jason2866** [comment]
@arendst  I have to do (this summer). My wife said. "You are playing with lights and sensors...
I still have to open and close the shutters by hand. Do something useful and change this!"

**Comment by arendst** [comment]
@Jason2866 well at least you HAVE shutters. It would take a lot of work to get shutters built-in in my house.

I guess I have to stick to the Ikea FYRTUR roller blind...

**Comment by alxnovo** [comment]
`ShutterButton1 1 toggle` doesn't work ;(

> 18:29:05 CMD: ShutterButton1 1 toggle
18:29:05 RSL: RESULT = {"ShutterButton1":"1 0 - - - - - - - -"}
18:29:13 RSL: RESULT = {"Shutter1":{"Position":0,"Direction":0,"Target":0}}
18:29:13 RSL: RESULT = {"Shutter1":{"Button1":1}}

In this example, the `Target` should be 100, not 0

**Comment by to-scho** [comment]
Are you using dev binary? Last released version does not include a toggle setup.

**Comment by alxnovo** [comment]
Yes, I used the latest version 8.2.0 and configured according to the instructions https://tasmota.github.io/docs/Commands/#shutters
I did not know that the toggle setup is not included.
Thank!

**Pull request merged**
