### PR TITLE
LVGL9 restore missing layouts

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

**Related issue (if applicable):** fixes #20697

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.6
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by xostia** [comment]
Hi,

Sorry if this is not the place to post... but set_recolor does not work in Tasmota 13.4 in the repository

 var titleLabel = lv.lv_label(titleBar)
titleLabel.set_recolor(true)

shows an error in the Berry script about the method

thanks for your work

**Comment by xostia** [comment]
OK, thank you. Do you have any example in berry about "span"? thank you

**Comment by s-hadinger** [comment]
Span is currently broken but I have a patch ready

**Comment by xostia** [comment]
ok, thank you. I am trying to move from 13.1 to the last one... I will wait.

**Comment by s-hadinger** [comment]
You can use the latest with the following PR: #20852

This should like these:
```berry
var spg = lv.spangroup(scr)
# set all attributes like x/y/w/h
spg.set_mode(lv.SPAN_MODE_BREAK);

var s1 = spg.new_span()
s1.set_text("Hello")

var st1 = s1.get_style()
st1.set_text_color(lv.color(0xFF0000))

var s2 = spg.new_span()
s2.set_text(" World")

var st2 = s2.get_style()
st2.set_text_color(lv.color(0x00FF00))

spg.refr_mode()
```

**Comment by xostia** [comment]
Hi... I solved my case (text in two colors) using something similar to the @s-hadinger proposal (I defined to styles and applied set_span_style to the different spans).

I red that the recolor (removed from 9.x) was added again in version 9.3 but in tasmota 15.1.0 it does not work. Do you know why? recolor has a  simpler syntax and its use of CPU is lower.

Thank for your support.

**Comment by s-hadinger** [comment]
Do you have a link to the lvgl documentation about this feature?

**Comment by xostia** [comment]
Hi, thank you for your message. I red in another page, that I did not found now, that it was re-introduced in 9.3, they were discussing about syntactic alternatives... but finally decided to keep the old syntax. In any case, I did found this about one bug in 9.3 and recolor.

https://github.com/lvgl/lvgl/issues/8547

**Pull request merged**
