### PR TITLE
Update Let's enctypt CA to use Intermediate R3

### PR DESCRIPTION
**Pull request by xhess**
## Description:
Recently Let's encrypt switched from using the "Let's Encrypt Authority X3" certificate for issuing new certificates to the "R3" Certificate. X3 is now retired. This uses their own certificate, not cross singed, since it valid till 2025. The cross singed would only be valid till Sept. 2021.

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
Thanks for the update. Are the previously issued certificate compatible with the new R3 authority or do we need to keep both X3 and R3 for the next 3 months?

**Comment by xhess** [comment]
with this change. No. (Didn't test but I am pretty sure)
After the request I saw that there is a variable called something like LetsEncryptX3. This should also be changed. But then other files need to be changed as well.

**Comment by s-hadinger** [comment]
Thanks for your work. I have created a new PR to add R3 instead of replacing X3 #10086

Can you please confirm it works with certificates signed by R3 CA?

**Comment by xhess** [comment]
I need to see when I have time. But I have to do it within the next two weeks because my old LE-Certificates will then expire. At the moment I am using the old certificate for mqtt.

**Comment by WillemJansen** [comment]
I can confirm - however I can only confirm this for the cross-signed certificate. It seems that by default, LE signs with the cross-signed cert, not the X1 self-signed one.

best way to check your own cert: 
openssl s_client -showcerts  -verify 7 -connect <your.mqtt.server>:8883

**Comment by arendst** [comment]
Duplicate from #10086

**Pull request closed without merging**
