### PR TITLE
Touch update

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

unified display touch interface, redundant code removed
only one touch driver
small fixes

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
CI Tests not all successful. For example Tasmota-minimal

**Comment by gemu2015** [comment]
strange bug.  the merged project (Tasmota development) compiles without errors.
my changes should not affect minimal because all changes are in ifdefed sections.
my original project also compiles the minimal version 
seems that this clone is somehow corrupted

**Comment by gemu2015** [comment]
it turns out to be a very strange compiler bug
it should never compile this Touch_Init function.
to prove insert a syntax error  
could not find a working solution yet besides Theos workaround

#ifdef USE_FT5206
#include <FT5206.h>
// touch panel controller
#undef FT5206_address
#define FT5206_address 0x38

insert some garbage in this line => no error

FT5206_Class *touchp;
TP_Point pLoc;
bool FT5206_found;

insert some garbage in this line => syntax error

bool Touch_Init(TwoWire &i2c) {
  FT5206_found = false;
  touchp = new FT5206_Class();
  if (touchp->begin(i2c, FT5206_address)) {
    I2cSetActiveFound(FT5206_address, "FT5206");
    FT5206_found = true;
  }
  return FT5206_found;
}

**Comment by arendst** [comment]
It's probably not so much of a compiler error but an arduino pre-compile error. It is known that the pre-compiler ignores defines and just builds the pragma list. This list building fails on undefined wire reference in the touch function.

One day, when we move from arduino to plain c++ this issue is solved. Will take some time though as we have to build the pragma list ourselves in that case.

**Pull request merged**
