### PR TITLE
Disable IR receive while sending

### PR DESCRIPTION
**Pull request by s-hadinger**
## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Tested. Great! No more mirror ghost commands.

**Comment by pilaGit** [comment]
If a feature (IrReceived#Data) is removed, it should be selectively removed. If nobody had this above problem for years, most likely, problem here is caused by funky IR blaster of this particular user.

It should be reversible for all other users (except for this one). This change killed my hybrid central heating / heat pump heating/cooling system.

So, it should at least be selectable, like Shutters or HVAC, by e.g.

#define ir_disable_recv

or even better with a corresponding

SetOptionXX

Pleas, not just killed after many years.

**Comment by s-hadinger** [comment]
What you call a "feature" was considered as an anomaly for many users:
- it created unnecessary MQTT messages
- it was unreliable and device dependent (some devices tended to return garbage)
- it was most certainly disturbing the timing of IR signals

Unless you explain why this "feature" is useful for many users, it will stay like this.

I'm sorry that it killed your central heating / heat pump heating/cooling system; but be very careful to rely on unreliable features.
If you absolutely want to reliably receive the IR sent, I highly suggest to add a second Tasmota device just for listening messages.

**Comment by s-hadinger** [comment]
@pilaGit I added the compile time `#define IR_RCV_WHILE_SENDING 1` so you can easily compile your own version with the feature you want.
The standard version will remain with receiving disabled.

**Comment by Jason2866** [comment]
There where open issues. If you had done a search in issues you would have found.
This PR is clearly a bug fix. 
Tasmota has breaking changes now and then. Updating a productive working setup can have always unwanted effects.

**Pull request merged**
