### PR TITLE
Teleinfo : Fix some calculation

### PR DESCRIPTION
**Pull request by hallard**
## Description:

Fixe some Teleinfo calculation

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.1.1
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
On Tasmota `long` is 32 bits like `int32_t`

Please avoid using `long` and specify explicitly the size with `uint64_t` or `int64_t` if you need 64 bits

**Comment by hallard** [comment]
Yeah correct, but since I'm using some `atol` declaring as long avoided casting on each `atol` code, was just a matter of consistency, but I can put them back to `uint32_t` no problem

**Comment by arendst** [comment]
Pls revert to uint32_t so I can merge.

**Comment by hallard** [comment]
Sorry this one got out of my head, should be fixed.

**Pull request merged**
