### PR TITLE
Update bg_BG.h

### PR DESCRIPTION
**Pull request by StoyanDimitrov**
## Description:
Translation update

### CODE REVIEW

**Comment by StoyanDimitrov** [comment]
What is the meaning of D_CURRENT_NEUTRAL and D_CT_POWER?

**Comment by arendst** [comment]
> What is the meaning of D_CURRENT_NEUTRAL and D_CT_POWER

D_CURRENT_NEUTRAL  = "Current Neutral". The current flowing to the neutral power line. Text needs to be short as it is displayed in the GUI. See below.
D_CT_POWER = "CT Power" where CT is a "Current Transformer" but do not translate this to a long text form as it will ruin the GUI display. Hence short form.

**Comment by sfromis** [comment]
Ideally, well-balanced 3-phase would have no current on the neutral wire (which then would not be needed), but the 3 phases may be in use for different purposes.

**Comment by StoyanDimitrov** [comment]
I'll keep than in mind for the next iteration.

**Pull request merged**
