### PR TITLE
Added command "wifi:on/off" to esp8266

### PR DESCRIPTION
**Pull request by Gifford47**
## Description:
i have added the wifi on/off function for the esp 8266 and run various tests. all tests (rules, ntp, mqtt) for the esp8266 were successful.
i measured the current consumption of one esp 8266 (wemos D1 mini). with wifi off, the esp consumes 24.5 mA on average (measurement time 60s). with wifi on, 43.5 mA on average (measurement time 60s).
the wifi can be switched on and off during operation. the mqtt service connects automatically on reconnect. in addition, the time is automatically synchronised once the esp has been on the internet.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with core ESP32 V.1.0.6
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Gifford47** [comment]
here is the discussion:
https://github.com/arendst/Tasmota/discussions/11459

**Comment by arendst** [comment]
Thx. I love those tiny PR's!

Let me do some tests on the esp32 with ethernet which currently restarts when switched from wifi to ethernet. This is disabled in your PR and might work indeed on the esp32.

**Comment by arendst** [comment]
I see it's failing on most envs but I will it fix this. No need to update your PR. Hold on.

**Comment by arendst** [comment]
Question, how do you plan to restart wifi once it is turned off?

**Comment by Gifford47** [comment]
In my case I want to switch it on with rules after my sensors reached a defined threshold

**Comment by arendst** [comment]
I understand. But in case a user disabled wifi while there is no rule present he/she is in jeopardy.

I'll force wifi on after a restart solving any uncontrolled situation.

**Comment by arendst** [comment]
Implemented (my way). Give it a try and report any issues you may find.

**Pull request closed without merging**
