### PR TITLE
Make module configuration web page dynamic

### PR DESCRIPTION
**Pull request by emontnemery**
Make module configuration web page dynamic (show user GPIO for selected module)
Allow setting of Option 15 from module configuration web page
Allow setting module and GPIO at the same time

### CODE REVIEW

**Comment by emontnemery** [comment]
@arendst Do you think this is too big / unnecessary?
A simpler option to make module setting page less confusing might be to split module configuration page in two: 
1. Page for changing the module, with warning message GPIO settings will be reset
2. One page for setting GPIO + Option 15
Or perhaps keep it as one page and just add the warning message about GPIO + add possibility to set Option 15

**Comment by arendst** [comment]
I've tries to use this PR but my screen stayed blank. I also noted a growth in web page size which is already to high so abandoned it for now.

In essence it's something I always wanted using the display block etc. so if you can get it working with the latest development built I will have a look at it again.

**Comment by emontnemery** [comment]
@arendst OK, I rebased to latest development and verified it works in Chrome and Edge.
Let me know what you think, what could also be done is:
- Either remove the "nicelist", (it's not used, the module list is instead sorted by js) or remove the js sorting
- Clean up HandleModuleConfiguration it became hard to read
- Fix logic to add helpful explanation for each pin (I think the explanation for wemos / generic makes more sense than the default explanation. I think default explanation only applies to standard sonoff devices?)

**Comment by eazuka** [comment]
+1

**Comment by ascillato2** [comment]
Thanks for sharing your ideas. By now, This PR is not going to be merged due to now exists a module configuration in actual Tasmota. Please, if you have further questions or ideas, do not hesitate on contacting us in the Tasmota Discord Chat. Thanks.

**Pull request closed without merging**
