### PR TITLE
RF Bridge: Add support for flashing the RF EFM8BB1 chip

### PR DESCRIPTION
**Pull request by ErikAndren**
Hi, 
This isn't a pull request per se but more of a call for review / interest.

This branch allows you to flash the RF EFM8BB1 chip on the Sonoff RF Bridge, given that you connect the C2CK pin to the GPIO4 and C2K pin to GPIO5 on the board.

Update: 
If you are running a 2.0 board (check PCB) then swap c2ck and c2k. Do not power the board via usb.

Firmware updates are performed the ordinary way and the software autodetects if the image is for the EFM8BB1. 

Is this something that would be of use to the general Tasmota project?

Thanks,
Erik

### CODE REVIEW

**Comment by Jason2866** [comment]
Great job!
Will try soon😃

**Comment by Jason2866** [comment]
Hello @ErikAndren 

i get this compile error:
`Archiving .pioenvs\sonoff\lib0de\libSPI.a
Compiling .pioenvs\sonoff\lib946\NeoPixelBus-2.2.9\internal\HtmlColor.cpp.o
Compiling .pioenvs\sonoff\lib946\NeoPixelBus-2.2.9\internal\HtmlColorNameStrings.cpp.o
D:/Sonoff-Tasmota-add-rf-flash-5.14/sonoff/webserver.ino: In function 'void HandleUploadLoop()':
D:/Sonoff-Tasmota-add-rf-flash-5.14/sonoff/webserver.ino:1356:34: error: 'UPDATE_ERROR_BOOTSTRAP' was not declared in this scope
if (Update.getError() == UPDATE_ERROR_BOOTSTRAP) {
^
Compiling .pioenvs\sonoff\lib946\NeoPixelBus-2.2.9\internal\HtmlColorNames.cpp.o
Compiling .pioenvs\sonoff\lib946\NeoPixelBus-2.2.9\internal\HtmlColorShortNames.cpp.o
Compiling .pioenvs\sonoff\lib946\NeoPixelBus-2.2.9\internal\NeoEsp8266UartMethod.cpp.o
Compiling .pioenvs\sonoff\lib946\NeoPixelBus-2.2.9\internal\NeoGamma.cpp.o
Compiling .pioenvs\sonoff\lib946\NeoPixelBus-2.2.9\internal\NeoPixelAnimator.cpp.o
*** [.pioenvs\sonoff\src\sonoff.ino.cpp.o] Error 1`

**Comment by ErikAndren** [comment]
Ah, seems like this is dependent on what version of the esp8266 library. I've pushed a workaround for now. Is there a define that one could use to see what version of the esp8266 library that is used?

**Comment by Jason2866** [comment]
Now build is successfull. But flashing is not working.
image
Now EFM8BB1 Flash is erased/corrupted -> RFBridge doesnt receive anything now

**Comment by Jason2866** [comment]
Solved. Really heavy stuff
Gpio 4 and 5 labeling is wrong (switched) AND GPIO 4 and 5 is connected to USB Power.
Solution was swapping cables and NOT Powering through USB Cable!

**Comment by ErikAndren** [comment]
Hmm, I have a 1.0 board and I did not need to swap cables and am powering the board via USB.

**Comment by Jason2866** [comment]
Yes, that is the difference from 1.0 to 2.0
Described here:
https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-RF-Bridge---Direct-Hack

**Comment by arendst** [comment]
@ErikAndren you can easily check for core version using:
```
#ifdef ARDUINO_ESP8266_RELEASE_2_3_0 
#endif

#ifdef ARDUINO_ESP8266_RELEASE_2_4_0
#endif

#ifdef ARDUINO_ESP8266_RELEASE_2_4_1
#endif
```

**Comment by arendst** [comment]
Released just now

**Pull request closed without merging**
