### PR TITLE
WIP: Tasmota Dimming MPDMv7.5 

### PR DESCRIPTION
**Pull request by daenny**
I made a first try in implementing dimming on the MPDMv7.5 with DAC:
https://github.com/daenny/Sonoff-Tasmota
The DAC dimming works, but I needed so set a range to get smooth and full range dimming https://github.com/arendst/Sonoff-Tasmota/compare/development...daenny:development#diff-9393865e3c967ebd04f7ff66eff2baa9R345

Is there a better way to be able to set the minimum and maximum dimming value?

### CODE REVIEW

**Comment by cyberelectronics** [comment]
I think, due to HW design you can not set higher voltage than 2.85V (the onboard timer circuit will be out of sync).
You need to set the DAC output value between 0=On to max. 2.85V=Off.

**Comment by epicality85** [comment]
Hi, which device/setting in the config do you use to get this working with tasmota?

**Comment by daenny** [comment]
I am using "MSDM with DAC". I added an additional custom type as this is different than all other devices. So you need to compile my branch and upload that one. I have not kept it up to date with upstream. But maybe I will take the time this weekend to clean it up and make a proper merge request.

**Comment by epicality85** [comment]
Thank you for the response. Did you make a whole new cpp file to fit it in? Maybe I'm just not sure how to add a type, but I will look for the MSDM key word.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by daenny** [comment]
It's a bit more than that. You can see the diff here: 
https://github.com/arendst/Sonoff-Tasmota/pull/3015/files
Easiest would be to checkout and compile the version from my branch. That works in my case. 
But this is only needed when using the version with the DAC, without the DAC the MSDM is basically a single PWM light. You can configure that by using the "generic device" and setting the correct pin.

**Comment by epicality85** [comment]
I added your code snippets to the latest and it works great!



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by ascillato2** [comment]
Hi,

@daenny can you uodate your PR to latest Tasmota please?

**Comment by epicality85** [comment]
I will see what I can do. The working copy is in South Africa, and I am in the UK.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by jsponz** [comment]
@daenny Excellent work!

Could you share your bin file so we can test it? I have just bought one and I want to test it. 

Thanks!

**Comment by daenny** [comment]
I made the branch upstream again.  But I switched to esphome, as I have home assistant and the integration easier for me. If someone with the device wants to test it with the latest upstream changes. please go ahead.  
If someone needs the esphome config, you can ping me as well.

**Comment by jsponz** [comment]
@daenny, thanks for your update. 

@epicality85, @koensmedts, could you share the compiled version? Thanks!

**Comment by Jason2866** [comment]
Suggest to close. @daenny has stopped working on this wip PR.

**Pull request closed without merging**
