### PR TITLE
New driver for heating controller (xdrv_39)

### PR DESCRIPTION
**Pull request by arijav**
## Description:
New driver created for heating control. I have created initially this as a LUA script running in Domoticz on a Raspberry Pi to control floor heating valves using Qubino relays. I have ported this to a Tasmota driver embedding the functionality in the relays. This driver has been successfully tested with a shelly 1PM. The controller offers 3 controlling strategies (Hybrid, Rampup and PI) as well as time planning (3 diff. temp. each weekday).

In the future the diagnostic functionality will be added and the code will be extended to multi controller in the same device. It will be tested with a Sonoff 4CH Pro to allow driving up to 4 different switching output with independently configurable controllers.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core Tasmota_core_stage
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
- Is there a way to use available timers instead of re-inventing timers?
- The amount of settings storage (70 bytes) is overwhelming. There must be a better way to store pre-defined settings (like dedicated compiles).

**Comment by arijav** [comment]
> * Is there a way to use available timers instead of re-inventing timers?
> * The amount of settings storage (70 bytes) is overwhelming. There must be a better way to store pre-defined settings (like dedicated compiles).

- Regarding settings: I could move most part of the settings to the local heating structure and initialize them there meaning that the driver should be reconfigured to a specific configuration at every restart. Do you have a rough figure of the max. setting storage that I should use?, this way I can prioritize.

- Regarding timers: All timers I have used are for controller purposes, I do not see a way to use existing ones. If you have a suggestion / example let me know and I will do my best to implement it.

**Comment by s-hadinger** [comment]
For settings, there are easy ways to reduce drastically memory. For ex, the max time in seconds you have is 57600 and the min is 60.
Just encode in 10's of seconds, and store in `uint16` from 6 to 5760.

Even better, encode in non-linear format, in `uint8` for ex:
- from 1-100, encode in 10's of seconds (so between 10 sec to 1000 sec)
- from 101-255, encode 10's of minutes (from 10 minutes / 600 secs  to 1550 minutes / 93000 seconds).

**Comment by device111** [comment]
have a look in settings.h. there most samples, that you could use. Use structs and Union to use only the Bit-Lenght you need. combine it with that was @s-hadinger wrote and you save a lot of Bytes from settings.

**Comment by arijav** [comment]
Thanks for the hints, I have started moving everything from settings to my local heating structure and will do further optimizations based on the comments. Since I am fairly new to Git, how shall I proceed?, do I have to close the Pull request, modify and create a new one?, or can I modify the current Pull request?

**Comment by s-hadinger** [comment]
It's better to close this PR.

First never do a PR from the development branch, it's a nightmare to manage.

Create a new branch in your fork: `git checkout -b new_branch_dev`
Link it to your repo: `git push --set-upstream origin new_branch_dev`
And you the classic `git commit ...` and `git push`

When you are ready for the PR, create a new branch with a clean single commit (squash).
`git checkout development`
`git pull upstream development` (make sure you did before `git remote add upstream https://github.com/arendst/Tasmota.git`)

Create the PR branch:
`git checkout -b new_branch`

Merge the other branch as a single commit:
`git merge --squash new_branch_dev`

Make sure everything is ok.
`git commit -m "<commit message"`
`git push`

Now go to github and create the PR.

**Comment by s-hadinger** [comment]
More info here: https://tasmota.github.io/docs/Sensor-API/#managing-a-forked-branch

**Comment by arijav** [comment]
Closed, I will implement optimizations and proceed as per comments

**Pull request closed without merging**
