### PR TITLE
Minor Typo in HTML

### PR DESCRIPTION
**Pull request by reloxx13**

### CODE REVIEW

**Comment by reloxx13** [comment]
Heya, i would like to add, that style="width... does also work.

in my line was a missing = , thats why i corrected it.

br
nils

**Comment by arendst** [comment]
I know it worked but this way I gain some code bytes back...

**Comment by reloxx13** [comment]
ahh okay, good to know thank you :)

**Comment by drbeat** [comment]
width attribute on table is deprecated in html5
so best practice would be
`style="width:100%"`

**Comment by arendst** [comment]
Thought so... Will revert the width change in next pre-release.

**Comment by reloxx13** [comment]
hey,

u missed the unit here:

grafik

**Comment by arendst** [comment]
I thought it would default to px but after reading this https://stackoverflow.com/questions/11274904/fallback-for-css-attributes-without-unit you're right so I'll add px to it.

To my surprise it indeed makes a difference and it looks like I envisioned so thanx for the comment!

**Comment by reloxx13** [comment]
you also have everything as % and not as px, i dont know why you made px here instead of 60% and 40% Oo

**Comment by arendst** [comment]
It's px because I want the input field of fixed length. Currently looking at the domoticz part as there it is still wrong too. Might change to % sometime...

**Pull request closed without merging**
