### PR TITLE
Power margins for all channels/phases

### PR DESCRIPTION
**Pull request by vic42**
## Description:
This patch allows PowerLow, PowerHigh, CurrentLow, CurrentHigh to be triggered based on the sum of all phases/channels. It came to my attention when a Shelly 2.5 would only evaluate channel 1 of 2.
I think that it makes more sense to act on the total device power/current instead of power/current of just the first phase or channel.

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
I think it depends o the use case. Imho one solution is not "better" than the other.

**Comment by barbudor** [comment]
Came across this one
I feel that we have 2 different use cases:
- Multi-phases, generally managed with 2 or 3x PZEM like described by TrDA
- Multi-channel, like Shelly 2.5
The current implementation that only looks at phase/channel 1 doesn't seems satisfying for any of those.
- In multi-phases case, I would expect the power/current to be monitor for a single device (or installation/house) where user mainly concerned by the total power. In that case looking only at power/current of phase 1 (out of 2..3) doesn't make any sense.
- In multi-channels, user would probably prefer to look separately at each channel as they are likely to be different pieces of equipment.
Of course, I'm sure there could be use case totally opposite.

Unless we go for a larger PR that provide the choice (SetOption) between sum of phases/channels or each of the 2..3 phases/channels separately, dealing only with the sum seems still better than dealing with only phase/channel 1.
Could this be a 1st step ?

**Comment by vic42** [comment]
I totally agree that this could be done even more elegant with a `SetOption` and having margins for each channel, however, likely at the cost of additional complexity.

The reasons why I chose exactly this design:
* It is minimally invasive
* It doesn't need extra options
* It is very unlikely to break something
  * Case 1 (single channel): no change in behavior.
  * Case 2 (multiple channels): The feature is currently useless for multiple channels so most likely very rarely used. In the rare case that someone was monitoring channel 1 only with margins it could impact the outcome.
* It will most likely meet the expectations of an unbiased user, at least for `PowerHigh`, `PowerLow`, `MaxPower`.
* Per channel values would somewhat duplicate the `PowerDelta` feature

**Comment by vic42** [comment]
No love for this one ;-)

**Pull request closed without merging**
