### PR TITLE
Driver for the Freescale MPR121 touch button controller

### PR DESCRIPTION
**Pull request by renne**
# Freescale MPR121 I2C Proximity Capacitive Touch Sensor Controller
* 12-button I2C touch controller
* Driver supports up to 4x MPR121 controllers (= 48 buttons per ESP8266)
* Electrodes can be covered with adhesive paper and adhesive plastic foil for labeling and symbols
* Break-out and touch button PCBs ~ 2,- € at [AliExpress](https://www.aliexpress.com/wholesale?catId=0&initiative_id=&SearchText=mpr121)
Touchpad front
Touchpad back
Break-out front
Breakout back

### CODE REVIEW

**Comment by renne** [comment]
@arendst @ascillato 
I'v created a [wiki page](https://github.com/arendst/Sonoff-Tasmota/wiki/MPR121).

**Comment by ascillato** [comment]
Hi,

@renne 

The wiki is intended to be an explanation on how to use and how to solve things. Not for advertising. Can you add an explanation on how to add and how to use this sensor in Tasmota with examples?

**Comment by renne** [comment]
I'll be offline for the weekend but I'm definitely going to add howtos to the wiki next week. Just wanted to get the pull-request ready for integration. The images are to see what kind of boards are available. If you want I can remove the search link to AliExpress ...

**Comment by andrethomas** [comment]
Looks like only AD0 is broken out, so I guess it will be limited to 2 boards if the one mentioned in the wiki is used...

**Comment by andrethomas** [comment]
Err, I didnt see this part in the datasheet... my bad :)

image

Weird way of doing it though!

**Comment by andrethomas** [comment]
@renne  Did you test to see if it still works with some form of a substrate over the panel? I'm thinking a graphic design printed on a photo at the local photo printing shop to create a more colourful interface and perhaps even adding custom meaning to the individual pins?

**Comment by Jason2866** [comment]
Hi @andrethomas,
2 brains same idea. I will get some of this boards too. 
Like the idea to get touch buttons with easy design possibiltys (if it works this way!)
Use case where feedback is immediatly visible and the MCP230xx for Panel with real switches (like in the first BMW minis)

**Comment by andrethomas** [comment]
@Jason2866  Yeah, I actually thought of doing that with one of my projects before... will have to wait for a response from @renne if it still picks up the touch sensing if you stick something like a printed photo over the capacitive touch surface.

**Comment by renne** [comment]
I currently don't have physical photos available. The electrodes work with sheets of copy paper AND overhead foil at the same time. A layer of printed adhesive paper and adhesive foil should work depending on the materials conductivity.

"This is kitchen control via MQTT"
img_20180706_182543

H801 with
 * RCWL-0516 motion detector
 * BME680 atmospheric sensor
 * APDS-9960 RGBC sensor
 * MPR121 touch-button PCB

**Comment by andrethomas** [comment]
> "This is kitchen control via MQTT"

You need a larger breadboard for your kitchen!

**Comment by renne** [comment]
screenshot_2018-07-06 sonoff-mainmenu

**Comment by Jason2866** [comment]
@renne 
I like your steam punk lamps! I played with this when i was child (long long time ago)😃
I have this lamps in my christmas crib. No LED, no electronic just plain old good little lamps with a transformer. I like the warm glowing.......

**Comment by renne** [comment]
@arendst @ascillato @andrethomas @Jason2866 

I updated the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/MPR121). Feel free to test the pull-request.

**Comment by Jason2866** [comment]
@renne 
I get this compiler warning:
`D:/Sonoff-Tasmota-development.6.1.1b/sonoff/xsns_30_mpr121.ino:192:2: warning: 'typedef' was ignored in this declaration [enabled by default]
};
^`
I think just a cosmetic thing but it disturbes the perfect build process ;-)

**Comment by renne** [comment]
@Jason2866 
The Tasmota 6.1.1b MPR121 code compiles fine with the Arduino IDE 1.8.5.
Which IDE do you use?

**Comment by Jason2866** [comment]
@renne THX for answering
I use Visual Studio Code (latest version)
will try later this evening...

**Comment by andrethomas** [comment]
Compiles fine under platformio in atom... must be something VS related.

**Comment by Jason2866** [comment]
I did the changes -> warning is gone :-)

**Comment by renne** [comment]
@arendst  @ascillato2 @Jason2866 @andrethomas 
New [pull request 3269](https://github.com/arendst/Sonoff-Tasmota/pull/3269) fixes the warning.

**Comment by Jason2866** [comment]
@andrethomas 
Got my touchpad. Putting a printed Photo in front of works perfect.

@renne 
THX for implementing the driver!

**Comment by andrethomas** [comment]
Damn... do you live in China or something? I never get stuff that fast.

Nice that the photo overlay works - adds a whole new dimension to what one can do with it.

**Pull request merged**
