### PR TITLE
Added StatusRetain command

### PR DESCRIPTION
**Pull request by jeroenst**
## Description:

Added statusretain https://github.com/arendst/Tasmota/discussions/11067

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by ascillato** [comment]
Hi, your change to the release notes is conflicting with the actual codebase. Please, delete it.

**Comment by jeroenst** [comment]
I changed the conflicting release notes instead, is that ok?

**Comment by arendst** [comment]
On hold for now as these "retain" changes are just marginal requests while I was able to keep Tasmota away of the HASS policy for many years. It adds code not used by any decent user except the famous MQTT retain afficionados...

I also wonder if the retain stop code works for all status messages.

**Comment by jeroenst** [comment]
Retain so stop works for all messages, retain stop is applied juist before sending to mqtt broker.

**Comment by jeroenst** [comment]
I would like to see this option to be merged so I can display status info on my dashboard.

There is now no way to send status 0 retrained.

**Comment by Jason2866** [comment]
Why using "retain" in general? Just query the devices and you get the actual real state.
I do not see any need for retain functions for Tasmota. Any status can be "asked"

**Comment by jeroenst** [comment]
1. Because it generates less traffic. 
2. Because just subscribing to the topic is enough to set the data, otherwise every client who is interested has first to send an additional request to get the data. When there are many clients (javascript) connecting and leaving the mqtt server or generates a huge amount of traffic which is prevented by retaining the messages

**Comment by jziolkowski** [comment]
And what's wrong with having a lot of MQTT traffic? It was designed exactly for that.

**Comment by Jason2866** [comment]
@jeroenst  The beauty of open source. You have made the changes you want/like.
As the project owner already wrote he does not like adding code for this.

**Comment by jeroenst** [comment]
> @jeroenst The beauty of open source. You have made the changes you want/like.
> As the project owner already wrote he does not like adding code for this.

I can do that but than I need to merge it over and over with upstream development branch. And I think this would be a good thing if it's added

**Comment by jeroenst** [comment]
@arendst any chance this can be implemented?

Again I try to make a status page, but again I bump into non retained messages of the tasmota, forcing me to create a kind of retain bridge which is not very nice and clean...

**Comment by jeroenst** [comment]
@arendst the status was changed to on-hold. What can I do to get this change into the main branch?

**Comment by jeroenst** [comment]
Statusretain is working correctly in 12.1.1.2 development branch commit e3c77331c6479fe8e84cee2ece0a8dd1ad961c2d

I tested with shelly 1, shelly dimmer 2, shelly 2.5, sonoff zbridge, athom power plug and Athom RGBWW bulb.

Everything seems to work fine. Thank you @arendst 

image

**Pull request closed without merging**
