### PR TITLE
It is recommended to use emplace_back instead of push_back.

### PR DESCRIPTION
**Pull request by monster29000**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.7
  - [ ] The code change is tested and works with Tasmota core ESP32 V.3.0.4
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
Googling around I find discussions that go in both directions
I can't seem to find real arguments

**Comment by barbudor** [comment]
Beside this PR has too many unwanted files

**Comment by s-hadinger** [comment]
If ain't broke don't fix it

**Comment by Jason2866** [comment]
Closing this PR changes files not related to the assumed?! idea of the PR.
If you still want to submit a PR please do only change the files involved and explain why the change should be done

**Comment by Jason2866** [comment]
Found an interesting article. https://andreasfertig.blog/2023/04/push_back-vs-emplace_back-when-to-use-what/
Every case has to be looked at, if a change may has an positive effect. Anyways the maybe gain is not that big to do this changes

**Comment by s-hadinger** [comment]
This is definitely the bad side of C++ std::vector and why I don’t use it. Too many traps. Our simple LinkedList does the job in a very frugal way

**Pull request closed without merging**
