### PR TITLE
Hi Theo, only Shutter driver is changed

### PR DESCRIPTION
**Pull request by stefanbode**
Sorry, still struggle with the github function....
## Description:
Update calibration Matrix to shutter
**Related issue (if applicable):** fixes #<Sonoff-Tasmota issue number goes here>

## Checklist:
  - [ x] The pull request is done against the latest dev branch
  - [ ] Only relevant files were touched
  - [x ] Only one feature/fix was added per PR.
  - [ x] The code change is tested and works on core 2.3.0, 2.4.2, 2.5.2, and pre-2.6
  - [ x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [ x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato** [comment]
Hi Stephan

This PR has 931 files changed and more than 100,000 changes. Sorry, but can't be merged.

One way of doing a PR is going by web to arendst Tasmota repository. Hit on edit on the first file you want to modify. Do some changes by web and after that, github will make a new branch in your repository that is the actual Tasmota codebase with just that change. 

After that, you can continue editing your new branch and then, you can make a PR from that branch with just the changes you want. 

If you need further assistant on this, please contact me on Discord (Tasmota support chat)

**Comment by stefanbode** [comment]
Maybe you can help me to get around. Bitwise my master branch is 100% Theo*s development, but GitHub shows 290 commits.How can I get them "removed"

**Comment by ascillato** [comment]
One way of doing a PR is going by web to arendst Tasmota repository. Hit on edit on the first file you want to modify. Do some changes by web and after that, github will make a new branch in your repository that is the actual Tasmota codebase with just that change.

After that, you can continue editing your new branch and then, you can make a PR from that branch with just the changes you want.

If you need further assistant on this, please contact me on Discord (Tasmota support chat)

**Comment by ascillato** [comment]
Also, you need to make changes and do the PRs, always against development branch, not master.

**Comment by ascillato2** [comment]
Closing in favour of PR 6598

**Comment by s-hadinger** [comment]
The way I do it is the following 

git checkout development 

git pull upstream development 

Now the local branch is synced to Theo's repo. 

git checkout -b <new_branch>

git push --set-upstream origin <new_branch>

Then merge the edits but removing the history of my local commits 

git merge --squash <my_initial_branch>

git commit -m "Message"

Now you have a clean single commit from which you can create the PR on Github.

**Comment by meingraham** [comment]
@s-hadinger 

Please review and edit - https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-API#managing-a-forked-branch

**Comment by s-hadinger** [comment]
@meingraham Thanks, I updated the wiki.

**Pull request closed without merging**
