### PR TITLE
so140 for persistent mqtt session

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

**Related issue (if applicable):** fixes [#15519](https://github.com/arendst/Tasmota/discussions/15519)

SetOption140 0 : Open clean mqtt session (default)
SetOption140 1 : Open persistent mqtt session

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.3
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by DetlefR** [comment]
Hello,
unfortunately, it doesn't work. Whatever I set for MQTT_CLEAN_SESSION during build, SetOption140 has no effect. Also not after reboot or power on/off.

**Comment by barbudor** [comment]
hum,
checking...

**Comment by barbudor** [comment]
I can confirm that with SetOption140 OFF, the connection is perform with CLEAN_SESSION as before
And with SetOption140 ON, the connection is left persistent
Are you sure that you have the latest build ?

**Comment by DetlefR** [comment]
Sorry,
my mistake. Due to my poor skills with git I had two versions off Tasmota.
Now it is working as expected. so140=>0 creates one volatile queue. And so140=>1 creates a second one which is persistent.

But keep in mind. You must add the subscription manually for the persistent queue.
Thank you.

**Comment by barbudor** [comment]
> But keep in mind. You must add the subscription manually for the persistent queue.

I beleve this is broker specific ?

**Pull request merged**
