### PR TITLE
More displays

### PR DESCRIPTION
**Pull request by gemu2015**
## Description:

adds more display drivers + universal renderer class

files modified against current development branch:

in sonoff
xdrv_13_display.ino (modified to support new renderer class AND recent method for "older" unmodified drivers like ili9341)
xdsp_02_ssd1306.ino
xdsp_05_epaper_29.ino
xdsp_06_epaper_42.ino
xdsp_07_sh1106.ino
xdsp_08_ILI9488.ino
xdsp_09_SSD1351.ino
xdsp_10_RA8876.ino

in lib
lib/Adafruit-GFX-Library-1.5.6 (original lib, only some class members declared virtual for subclassing)
lib/esp-epaper-29-ws-20171230-gemu-1.2 (support for epaper 2.9 and 4.2 inch and renderer class)
lib/Adafruit_SSD1306-1.3.0 (modified for subclass of renderer)
lib/Adafruit_SH1106 (modified for subclass of renderer)
lib/FT6236 (touch screen i2c lib for ili9488 and ra8876)
lib/ILI9488 (ili9488 driver optimized for 3 wire hardware spi)
lib/SSD1351 (ssd1351 driver optimized for 3 wire hardware spi)
lib/RA8876 (ra8876 driver for standard 4 wire hardware spi)

i will add an updated doku to the wiki later

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Review by Jason2866 — COMMENTED** [review]
Platformio.ini should be left unchangend

**Comment by arendst** [comment]
I'll merge but noticed that when both ILI9488 and RA8876 are enabled compile fails due to duplicate use of both macro and global vars.

**Comment by arendst** [comment]
Already merged and noticed some more things that shouldn't have been changed. Will need to go over the changes and see what and how to repair.

I was reluctant to merge the previous display update request. This one looks better but still need some polishing. How about the copyrights from 2018...

Busy.

**Comment by philbarclay** [comment]
Awesome stuff merging this, and thanks to @gemu2015 for authoring.  I look forward to testing it out.

**Pull request merged**
