### PR TITLE
[WebUI] WiFi Information

### PR DESCRIPTION
**Pull request by SteWers**
## Description:
Structured and further information (BSSId) on the WebUI information page about the WLAN (AP) connection

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
OMG. Another writer ruining the small column display with a line breaking reasonable width....

**Comment by SteWers** [comment]
OK, I understand. It would nice to see the BSSId on the info page. Do you have a better suggestion to realize that?

**Comment by SteWers** [comment]
@arendst Please have a look at this approach. I think it looks good. Even on a smartphone display.

**Comment by s-hadinger** [comment]
Can you send a screenshot?

**Comment by arendst** [comment]
Thx.

**Pull request merged**
