### PR TITLE
Neopixel updated to 2.6.3 branch Esp32C3

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

added preliminary support for Esp32C3. Needs to be checked for side effects since the lib is newer than the actual used.
added "ifdefs" to disable not compatible "OneWire" for C3

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with core ESP32 V.1.0.6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
Ds18x20 changes ci fail

**Comment by Jason2866** [comment]
CI error fixes

**Comment by arendst** [comment]
As was said in the movie _boys from Brazil_: "**Is it safe**" to merge?

**Comment by Jason2866** [comment]
I think it is a good idea @s-hadinger have a look at before merging.

**Comment by s-hadinger** [comment]
I'm afraid you need to redo the PR. NeoPixelBus now merged into master with some slight changes.

By the way, I propose to rename the lib directory plain "NeoPixelBus" without version number, this avoids hundreds of changes each time we update and make it easier to see differences.

**Comment by Jason2866** [comment]
As suggested will do a new PR

**Pull request closed without merging**
