### PR TITLE
Direct control other Tasmota Device

### PR DESCRIPTION
**Pull request by MarioP73**
Can you integrate the direct control of other Tasmota devices when changing the POWER1 status?
In the config could be the input of Client IP, the channel to be controlled and whether 
it should be sent inverted.
This would allow a direct link between two Tasmota devices without an MQTT-Broker.

```
HTTPClient http;
String adress  = "http://192.168.xxx.xxx/";
String command = "Power1";
String state   = Power1.state;
http.begin(adress + "cm?cmnd=" + command + "%20" + state);
int httpCode = http.GET();
```

### CODE REVIEW

**Comment by ascillato2** [comment]
@MarioP73

You have made a PULL REQUEST to merge 2 different branchs of this repository.

If you want to open an issue, go to issues.

If you want to share your code modification, do a proper PR.

If you have general questions, go to the Tasmota Discord Chat

**Comment by ascillato2** [comment]
Direct control is already implemented using commands WEBSEND and using KNX feature.

Please read the wiki

Thanks

**Comment by labastov** [comment]
Hi,
I update function for pca9685 driver.
- rename driver to sensor (xdrv_15 to xsns_33)
- added display information on webgui (function FUNC_WEB_APPEND).
- added send jonson information  (FUNC_JSON_APPEND)
- added key #defined PCA9685_DEFAULT_FREQ.
Could yuo insert files to project.

Thanks

**Comment by ascillato2** [comment]
@labastov 

Please, do a PR with your changes. Thanks.

**Pull request closed without merging**
