### PR TITLE
Add Switchmode Ignore 15

### PR DESCRIPTION
**Pull request by boaschti**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.3
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
??????

Why not unconfiguring the switch?

**Comment by boaschti** [comment]
Classic example is a pir sensor which is on switch1 and the coupled relais1 which controlls the lamp. If i want to open the connection at daytime and use the pir also for a trigger to get a picture from a camera then i need the new switchmode and a immideatelly report from the sensor change via mqtt.
Another example:
If you have switch1..4 and relais1 and relais2. Then switch 3 and 4 will be coupled with relais1. With the new switchmode you can open the coupling and have just the input reported via mqtt.

**Comment by arendst** [comment]
> then i need the new switchmode and a immideatelly report from the sensor change via mqtt.

That's a major change as it is reporting for EVERY switchmode flooding MQTT with mostly useless data.

It's better to send ONLY for this new switchmode.

**Comment by boaschti** [comment]
Hm. Does that matter? Another Advantage is to get the switch state if you have switchmode = toggle. Actually you never know the switch state. (immidiatelly)

For example you have two or more tasmotas and linked via homeautomation. And you want to trigger a timer if the switch of tasmota1 is toggled. The tasmota2 an others does not trigger the timer or perhaps another timer.

**Comment by arendst** [comment]
Implemented my way.

**Pull request closed without merging**
