### PR TITLE
Added option to configure ledlink to show a heartbeat

### PR DESCRIPTION
**Pull request by jeroenst**
## Description:
The link led is a status led which is often off or on when connections (wifi and mqtt) are established. This option enables the user to use the command "ledlinkheartbeat" with payload 0 or 1 to enable or to disable this feature which is disabled by default to prevent changing default behaviour of the led.

When enabled the linkled will be (depending on the inverted flag) on for 3750ms and off for 250ms continuously when connections are established.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
Thanks for the PR. However I'm not convinced by the usefulness of this feature. Who wants a device that blinks endlessly? Blinking should denote a temporary action or an anomaly

**Comment by jeroenst** [comment]
> Thanks for the PR. However I'm not convinced by the usefulness of this feature. Who wants a device that blinks endlessly? Blinking should denote a temporary action or an anomaly

Blinking also gives the impression the device is on and working (not stalled) which in some cases is very useful imo.

**Comment by s-hadinger** [comment]
Did you try rules to achieve the same result?

**Comment by jeroenst** [comment]
I didn't try to make a rule for this.

**Comment by Jason2866** [comment]
I like that the user can decide if she/he wants blinking as a sign of "life"
This is not uncommon for electronic devices. All my APs have this. AND all have the feature to switch this off. I use this option
because i dont like "Disco" in my living and sleeping rooms (especially at night).

**Comment by jeroenst** [comment]
An additional benefit of this change is that it also works with sonoff zbbridge, where the configuration of ledlink in the template configuration doesn't work at this moment. (i have to create a bugreport for that).

**Comment by s-hadinger** [comment]
What do you mean it doesn't work with zbbridge?
Be aware that this led is also used as a pulsating indicator for permit join. What happens if both modes are on simultaneously?

**Comment by jeroenst** [comment]
> What do you mean it doesn't work with zbbridge?
> Be aware that this led is also used as a pulsating indicator for permit join. What happens if both modes are on simultaneously?

The pulse when permit join differs from the heartbeat pattern so it's easy to see that it's in join state.

**Comment by ascillato** [comment]
Hi, thanks a lot for your idea. It is well programmed but this change is not going to be added, sorry. It uses the blink as ok while in Tasmota a blink is something that needs attention.

**Comment by jeroenst** [comment]
> I like that the user can decide if she/he wants blinking as a sign of "life"
> This is not uncommon for electronic devices. All my APs have this. AND all have the feature to switch this off. I use this option
> because i dont like "Disco" in my living and sleeping rooms (especially at night).

True, in my bedroom the

> Hi, thanks a lot for your idea. It is well programmed but this change is not going to be added, sorry. It uses the blink as ok while in Tasmota a blink is something that needs attention.

Well, it's optional, not default..

**Comment by arendst** [comment]
Sorry, another waste of code space currently on hold.

**Comment by ascillato2** [comment]
Thanks for sharing your work but it is not going to be merged. Sorry.

**Pull request closed without merging**
