### PR TITLE
[Proof on Concept] Add initial support to export metrics for Prometheus

### PR DESCRIPTION
**Pull request by marius**
## Description:
See https://prometheus.io/ for project information.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by marius** [comment]
Hi everybody,

this is my first PR for embedded software. I have no idea what I'm doing.
Please review and let me know if this is something people are generally
interested in.

Regarding the checklist: I don't know what core 2.6.1 is.

**Review by s-hadinger — COMMENTED** [review]
Please be frugal in flash size. Remove all help text and keep it utra-minimal.

**Comment by Jason2866** [comment]
Thx for the PR, but adding probitary enhancements have to be well considered.
How many users of Tasmota do have a benefit of this?
What is in general the benefit?

**Comment by ascillato** [comment]
It is missing a define key in order to disable this and not adding more flash usage if this feature is not needed

**Comment by marius** [comment]
@s-hadinger: Sure, will do.

@Jason2866: The Prometheus protocol is not proprietary, and it is not a small project either.
As usual in open source, there is very little information about the number of users. I'd say it
is one of the most used monitoring systems available.

@ascillato: Yes, will do.

General question: I don't understand the code structure, esp. how .ino files work.
Is there a way for me to access the Energy struct defined in tasmota/xdrv_03_energy.ino?

**Comment by jziolkowski** [comment]
I agree with @Jason2866 re: gains for users. Prometheus is a pull-based metrics collector, which needs code like this to continuously push data to prometheus. The same result can be obtained by simply configuring influxdb (which using the prometheus authors own words is better for event storage) with telegram's mqtt_consumer, without a single byte of code added to Tasmota.

**Comment by marius** [comment]
jziolkowski: The thing is, I have Prometheus running, and I'm not interested in setting up Influxdb. 
I could create/use an MQTT to Prometheus exporter, but that adds another component to my setup,
whereas this supports the usual Prometheus polls devices directly.

**Comment by s-hadinger** [comment]
Can you measure the code increase with your PR. I'm surprised that %f works in printf, float is normally disabled to save a lot of code.

**Comment by marius** [comment]
Actually, it doesn't work, I need to rework that too.
I'll measure the difference once I have the #defines.

**Comment by ascillato2** [comment]
@marius 

Hi, any news on this PR?

**Comment by marius** [comment]
Hi Adrian,

sorry I didn't have time to work on this.
Can I change this PR back to draft?

**Comment by ascillato** [comment]
No need for that. We wait for you.

**Comment by marius** [comment]
I added #defines and switched from printing floats to printing unsigned integers.

I would like to access the _Energy_ struct, but I can't because it is defined in a later .ino file.
What do people think about creating an energy.h header file and moving the struct definition
and variable there? That way I can access it in xdrv_01_webserver.ino.

**Comment by arendst** [comment]
Don't  change any core items. Energy is conditional anyway so it might not veen be there in some compiles.

I'll scan over your implementation and see how it currently integrates.

**Comment by arendst** [comment]
Implemented basic prometheus support using single file xsns_91_prometheus.ino

As long as define USE_PROMETHEUS is disabled nothing is reported.

**Comment by lomik** [comment]
Prometheus can't fetch metrics with error  ```invalid metric type "guage"```

My current /metrics:
```
# TYPE global_temperature gauge
global_temperature 43.1
# TYPE voltage gauge
voltage 0
# TYPE current gauge
current 0.000
# TYPE active_power guage
active_power 0
# TYPE energy_daily gauge
energy_daily 0.000
# TYPE energy_total counter
energy_total 0.000

**Comment by joba-1** [comment]
gauge, not guage for active_power?

**Pull request closed without merging**
