### PR TITLE
JSMN phase 2

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Adapted the following modules from ArduinoJson to JSMN:
- 17. Rcswitch
- 39. Thermostat
- 40. Telegram

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
@arijav I moved `xdrv_39_thermostat.ino` from ArduinoJson to the new JSMN module.
Documentation is here: https://github.com/arendst/Tasmota/tree/development/lib/jsmn-shadinger-1.0

I believe I didn't break anything. Would you be kind enough to confirm that the module is still working as expected and parsing correctly the input JSON?

**Comment by arijav** [comment]
Hello, sure, I will do hopefully this weekend

**Comment by meingraham** [comment]
@s-hadinger 

from Documentation: https://github.com/arendst/Tasmota/tree/development/lib/jsmn-shadinger-1.0
> These limits shouldn't be a problem since buffers in Tasmota are limited to 1.2KB

https://github.com/arendst/Tasmota/issues/9305#issuecomment-696597594
Does this buffer minimum increase to ~4KB affect this?

**Comment by arendst** [comment]
Nope. That's the logging buffer.

**Comment by s-hadinger** [comment]
Incredible, people do read the documentation!

**Pull request merged**
