### PR TITLE
Error in PIO dev version is fixed

### PR DESCRIPTION
**Pull request by Jason2866**
with commit https://github.com/platformio/platformio-core/commit/2459e85c1dc9a1ecfe632c611594c6c302c8af6b

and switch off deprecated warning for SPIFFS

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [x] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Are you sure this is correct???

I get pio error:
```
> Executing task: C:\Users\Theo\.platformio\penv\Scripts\platformio.exe run --target upload <

Processing tasmota (platform: espressif8266@2.6.2; framework: arduino; board: esp01_1m)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Tool Manager: Installing framework-arduinoespressif8266 @ https://github.com/tasmota/Arduino/releases/download/2.7.4.1/esp8266-2.7.4.1.zip
Error: VCS: Unknown repository type framework-arduinoespressif8266 @ https://github.com/tasmota/Arduino/releases/download/2.7.4.1/esp8266-2.7.4.1.zip
The terminal process "C:\Users\Theo\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1.
```

**Comment by arendst** [comment]
Fixed after restart VSC ?!?!

**Comment by Jason2866** [comment]
Works on my PC. Gitpod works. Github Actions builds are all successfull 
Have you updated to latest pio dev version? Only the latest dev version has the fix.
Or you can use the release PIO version

**Comment by arendst** [comment]
See above. I had updated PIO AND did a restart of VSC before. Anyway. Solved.

**Comment by Jason2866** [comment]
Newest PIO version is only activated after a restart of VSC ;-)

**Comment by Jason2866** [comment]
Cosmic rays....

**Comment by Jason2866** [comment]
Just did a package and publish of the core 2.7.4.1. to Platformio
If this is beeing accepted (after Moderation) the Tasmota core 2.7.4.1 can be downloaded direct from PlatformIO CDN.

**Pull request merged**
