### PR TITLE
Support for I2C sensor DHT12

### LINKED ISSUE #7229: I2C DHT12 Support (Contribution)
**Have you looked for this feature in other issues and in the wiki?**  
Yes
**Is your feature request related to a problem? Please describe.**  
Support for <https://wiki.wemos.cc/products:retired:dht_shield_v2.0.0>

**Describe the solution you'd like**  
Review and include driver code that I can contribute.

**Describe alternatives you've considered**  
Compile my own Tasmota version

**Additional context**  
I have compiled my own version of Tasmota 6.4.1 with code for the DHT12 shield in xsns_10_*.ino
It works fine, but updating Tasmota would be difficult, because the driver is not properly integrated.
So, therefore, I would like to contribute the attached source code for your review and inclusion in Tasmota.

**(Please, remember to close the issue when the problem has been addressed)**  
Sure.

Regards,
Stefan

[xsns_10_dht12.ino.txt](https://github.com/arendst/Tasmota/files/3965240/xsns_10_dht12.ino.txt)

### PR DESCRIPTION
**Pull request by stefan-oskamp**
## Description:

**Related issue (if applicable):** fixes #7229

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on core 2.6.1
  - [X] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato2** [comment]
Great! 

I saw that you have added DHT12 to be included as default on Tasmota_sensors.bin :+1:

Please, can you also add the commented key in _my_user_config.h_ file, so to be available for other users that would use this sensor with their own custom builds? 

```yaml
//#define USE_DHT12
```

Thanks. 

When you compile this sensor, have you checked how much extra flash and ram it uses? You can easily check this compiling without the sensor, check the output console of platfomio and then recompiling with this sensor enabled and do the difference in KBytes.

**Comment by stefan-oskamp** [comment]
Before:
DATA:    [======    ]  60.2% (used 49292 bytes from 81920 bytes)
PROGRAM: [======    ]  58.0% (used 594044 bytes from 1023984 bytes)

After:
DATA:    [======    ]  60.2% (used 49312 bytes from 81920 bytes)   
PROGRAM: [======    ]  58.1% (used 594736 bytes from 1023984 bytes)

Diff:
DATA: 20 bytes
PROGRAM: 692 bytes

**Comment by ascillato** [comment]
Thanks :+1:

**Review by ascillato — APPROVED** [review]

**Comment by mike2nl** [comment]
Funny because today i found 2 spare DHT12 in my stock. I was cleaning up and write the inventory new. So i can test it now. Ver well done @stefan-oskamp

**Comment by Sofianov** [comment]
Dear Theo Mike, and ascillato.

I am stuck with my DHT12 and Tasmota. SDA SLC both 10K pullup resistor to 3v3  is given **BH1750 Illuminance   54612 lx**  instead of temp and humidity.  Using Tasmota 820 sensors version.

Please help!!!!

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by dkebler** [comment]
for any getting here with the BH1750 Illuminance 54612 lx to solve this just start a console session and send `I2CDriver11 0` which will turn off that BH1750 driver and allow DHT12 work properly.

**Comment by tcsi-github** [comment]
Thank you for documenting this, it worked for me.

**Pull request merged**
