### PR TITLE
Add latest portisch firmware.

### LINKED ISSUE #48: Is it possible to sniff codes out of an AC123-01 transmitter ?
Hi, 

First of all I'd like to thank for the great work you've been doing with this alternative firmware.
I have 3 RF controlled blinds here at home and I'm trying to control
 them via my Sonoff RF bridge (flashed with the latest tasmota and portisch firmwares).

The problem is that I can't sniff the transmitted codes. I tried standard, advanced and bucket sniffing but nothing is logged in the console.

The transmitters are labeled **AC123-01** (more details [here](http://www.cn-allbest.com/e_productshow/?87-AC123-01-roller-shutter-window-Channel-Insertion-Transmitter-87.html) and in the pictures below). 

img_20181106_151212384

img_20181106_151240838

Does anyone know how can I find out whether these type of transmitters are compatible with the bridge 
 or not ? Is it just a matter of [adding a new protocol](https://github.com/Portisch/RF-Bridge-EFM8BB1/wiki/Define-new-protocol-in-RF_Protocols.h) ? 

Any help is appreciated  (you might have noticed that I'm a total newbie on the subject!!)

### PR DESCRIPTION
**Pull request by reesericci**
Includes support for zemismart roller shades

## Description:

**Related issue (if applicable):** fixes [https://github.com/Portisch/RF-Bridge-EFM8BB1/issues/48](https://github.com/Portisch/RF-Bridge-EFM8BB1/issues/48) on Portisch github

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.3.2
  - [X] The code change is tested and works on core ESP32 V.1.12.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by reesericci** [comment]
It would probably be better if we used git submodules for it but it's a release so I don't know how that would work. I also don't know if you'd want to use them

**Comment by ascillato** [comment]
> It would probably be better if we used git submodules for it but...

Good idea, but I think is better this way due to in the past some firmwares had bugs and we needed to roll back to previous versions and deleting the problematic ones.

Adding the new releases as you did now, leave us in control of which firmwares are tested and known to work well in order to offer them with Tasmota files. The last firmware for portisch in Tasmota repository is known to work really good, so we can test this new one and add it as a new option.

Thanks for making this PR :+1:

**Comment by reesericci** [comment]
Ok cool

**Comment by reesericci** [comment]
Thing is, @Snipercaine couldn't use his new Zemismart roller shades, but when we tried the newest portisch it worked beautifully!

**Comment by reesericci** [comment]
can someone test the portisch and merge?

**Comment by reesericci** [comment]
yay!

**Comment by ascillato2** [comment]
Added the _**.hex**_ extension to your file in order to make it work by Tasmota OTA.

The faulty firmwares I was refering to, are:

```
RF-Bridge-EFM8BB1-20191006.hex
RF-Bridge-EFM8BB1-20190326.hex
```

As reported in #7064 those versions hungs when using rfraw. Using previous ones works fine.

**Comment by reesericci** [comment]
Whoops! sry, thx for those links

**Comment by arendst** [comment]
Guys, are you sure the date is 20190220? Shouldn't it be 20200220?

**Comment by arendst** [comment]
Ah. Self answered. It's indeed 20190220.

**Comment by Jason2866** [comment]
I did a build with more protocols enabled. Give this version a try. https://github.com/Jason2866/RF-Bridge-EFM8BB1/tree/new_protocols

i am using for my needs configured version (stable with rfraw since 5 days) this version:
https://github.com/Jason2866/RF-Bridge-EFM8BB1/tree/Wt0124

The enabled and supported protocols are listed in `/inc/RF_Config.h`

**Comment by adamrhoades** [comment]
> I did a build with more protocols enabled. Give this version a try. https://github.com/Jason2866/RF-Bridge-EFM8BB1/tree/new_protocols
> 
> i am using for my needs configured version (stable with rfraw since 5 days) :
> https://github.com/Jason2866/RF-Bridge-EFM8BB1/tree/Wt0124
> 
> The enabled and supported protocols are listed in `/inc/RF_Config.h`

Hi Jason 2866,

I'm struggling to compile your new_protocols fork. Can i just flash the '/Keil 8051 v9.53 - Release/RF-Bridge-EFM8BB1.hex' ?

If not, would you please consider sharing your compiled hex file??

Thanks in advance!

**Comment by Jason2866** [comment]
Yes, the hex file is the one to flash

**Pull request merged**
