### PR TITLE
Added support for MAX7219 Seven-Segment Display

### PR DESCRIPTION
**Pull request by ajithvasudevan**
## Description:
~~This is a new Display driver which adds support for the MAX7219 seven-segment display~~
This adds support for the MAX7219 seven-segment display module to the existing TM163x driver ( https://github.com/arendst/Tasmota/pull/11031 )

**Related issue (if applicable):** NA

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with core ESP32 V.1.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Without diving too deep in I see a lot of redundancy with TM163x driver.

Perhaps it is better indeed to incorporate this driver in the TM163x code.

While doing this pay attention to the removed command ``DisplayBrightness 1..8`` which has been replaced by the already present command ``DisplayDimmer 0..100``.

**Comment by ajithvasudevan** [comment]
> Without diving too deep in I see a lot of redundancy with TM163x driver.
> 
> Perhaps it is better indeed to incorporate this driver in the TM163x code.
> 
> While doing this pay attention to the removed command `DisplayBrightness 1..8` which has been replaced by the already present command `DisplayDimmer 0..100`.

Alright. Will do.

**Comment by ajithvasudevan** [comment]
> > Without diving too deep in I see a lot of redundancy with TM163x driver.
> > Perhaps it is better indeed to incorporate this driver in the TM163x code.
> > While doing this pay attention to the removed command `DisplayBrightness 1..8` which has been replaced by the already present command `DisplayDimmer 0..100`.
> 
> Alright. Will do.

@arendst ,

The current development branch changes for the TM1637/8 driver seems to have broken it. 

I find that none of the commands ```DisplayClock```, ```DisplayText```, ```DisplayNumber```, ```DisplayFloat```, etc.,  are working for the TM1637 or TM1638.

Looking into it ...

**Comment by arendst** [comment]
They only work if you select ``DisplayMode 0`` first.

**Comment by arendst** [comment]
And make sure ``Power 1``

**Comment by arendst** [comment]
And ``DisplayDimmer 50`` ;-)

**Comment by ajithvasudevan** [comment]
> And `DisplayDimmer 50` ;-)

```DisplayDimmer``` default value was the issue!   I was counting on it being set to a sane default as I did earlier  :)

**Comment by ajithvasudevan** [comment]
@arendst ,
Its done. I've moved the **MAX7219** code to `xdsp_15_tm1637.ino`  and deleted `xdsp_16_max7219.ino`
Tested the Display build on all 3 displays - TM1637, TM1638 and MAX7219.
DisplayModes 1,2,3 work great. Thanks for that. I'd have done it anyways ...  ;-)

**Pull request merged**
