### PR TITLE
correct inverted behaviour of switch in Switchmode 0 & 1 in (follow)

### PR DESCRIPTION
**Pull request by vic42**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works on Tasmota core ESP32 V.1.0.4.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by vic42** [comment]
change the docs, not the code

**Comment by ascillato2** [comment]
Switchmode 0 and 1 are features availables from the beginning of Tasmota, so a change like this is a huge breaking change. Sorry, this is not going to be modified due to is going to break the setups of a huge amount of users and devices templates.

**Comment by ascillato2** [comment]
As explained in https://github.com/arendst/Tasmota/issues/10099#issuecomment-741817295 you already have the options to choose the switchmode that fit your need. Normal or inverted.

**Comment by vic42** [comment]
Yeah the code change was not a good idea that's why i closed the PR myself only seconds after submission.
But the documentation does not reflect the actual behavior of the software. Try it!

**Pull request closed without merging**
