### PR TITLE
Update tools/fw_SonoffZigbeeBridge_ezsp/readme.txt

### PR DESCRIPTION
**Pull request by MattWestb**
Adding Silabs Reference Collection of Ember ZNet and AFV2 Release Notes

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [ ] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by s-hadinger** [comment]
Thanks but I'm not sure we need to place here a link to a Dropbox with a lot of documentation that is only needed for developers.

**Comment by MattWestb** [comment]
Sorry i was coping the wrong link then you is not needing the old EZSP versions.
The link i was intended is [Zigbee & Thread Knowledge Base Articles List](https://silabs-prod.adobecqms.net/community/wireless/zigbee-and-thread/knowledge-base.entry.html/2020/04/01/zigbee_thread_knowledgebasearticleslist-ih5r)

Its little deep for normal users but can helping users and also ad reference if you is needing some Silabs documents that is not alway so easy to finding.

**Comment by arendst** [comment]
Thx. Kind of merged with correct link.

**Comment by MattWestb** [comment]
Thanks sorry for the wrong link and hope you getting the new fixed firmware on you Zigbee Bridge up and running.

**Pull request closed without merging**
