### PR TITLE
Only do eveluate for expression while Var/Mem command follow a '='

### PR DESCRIPTION
**Pull request by laurentdong**
## Description:
Related issue: [issue #5369] USE_EXPRESSION breaks string variable support 

A "=" is required to do expression evaluate in command Var/Mem:
**Var1 = (Mem1 - 2) / 100**

Command:
**Var1 Mem1**
will do the exactly same thing like previous version - assign string "Mem1" to Var1

## Checklist:
  - [X ] The pull request is done against the dev branch
  - [X ] Only relevant files were touched (Also beware if your editor has auto-formatting feature enabled)
  - [X ] Only one feature/fix was added per PR.
  - [X ] The code change is tested and works.
  - [X ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**

### CODE REVIEW

**Comment by netpok** [comment]
Maybe it would be better to introduce a new command for this like `VarE` (var expression) or something in code size it wouldn't really matter but it would allow the use of full character range in the value.

**Comment by laurentdong** [comment]
@netpok 
Require a "=" actually is basically same idea like "VarE" but looks much better and easy to understand, isn't it? For example
**Var1=Mem1 * 2**
vs
**VarE1 Mem1 * 2**

If we really want to introduce new command, I would prefer to have a "Let" command. For example:
**Let Var1 = Mem1 * Var2 + 1**

**Comment by netpok** [comment]
The difference is that in case of var1 =something, the = sign is part of the argument so you can't start the string with = sign (probably would't matter for anyone), on the other hand in case of the E is part of the command and leaves the argument constraint free.

Also I have a new idea: Currently only doubles are returned from expressions, so maybe we should make a new command for it and store them as doubles this would allow the usage of more variables. Like: Var1...5 and DVar1...40 would take up the same memory space allowing 8 times of variables and 2 times of memory spaces. The only constraint is that VAR1 must not be used with DVAR1...8 as they are pointing the same memory space. I will try this out (probably I won't have time till the weekend) and report back.

**Review by ascillato — APPROVED** [review]

**Comment by windischb** [comment]
Is there a chance to merge this in near future?

**Comment by arendst** [comment]
I'll check it now...

**Comment by arendst** [comment]
Merged just now.

**Pull request closed without merging**
