### PR TITLE
Tasmota: Execute poweronstate after all modules are initialized.

### LINKED ISSUE #7412: poweronstate 3 doesn't work in Tuya Dimmer
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

ERC309 zemismart receiver, flashed with tasmota 8.1.0 as shown in the wiki. Everything works as expected, but the poweronstate 3 doesn't work. If the switch is ON, restarting the device the switch remains ON, but after a power loose, the switch stays OFF.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/#/help/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ERC309
- [ ] Tasmota binary firmware version number used: tasmota.bin 8.1.0
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: espeasy
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
{"NAME":"Generic","GPIO":[255,255,255,255,255,255,255,255,255,255,255,255,255],"FLAG":15,"BASE":18}
stat/tasmotazemi/RESULT = {"Module":{"54":"Tuya MCU"}}
stat/tasmotazemi/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"107":"Tuya Tx"},"GPIO2":{"0":"None"},"GPIO3":{"108":"Tuya Rx"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
stat/tasmotazemi/STATUS = {"Status":{"Module":54,"FriendlyName":["Tasmota"],"Topic":"tasmotazemi","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
17:46:57 MQT: stat/tasmotazemi/STATUS1 = {"StatusPRM":{"Baudrate":9600,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:07:39","StartupUTC":"2020-01-02T16:39:18","Sleep":50,"CfgHolder":4617,"BootCount":2,"SaveCount":13,"SaveAddress":"F7000"}}
17:46:57 MQT: stat/tasmotazemi/STATUS2 = {"StatusFWR":{"Version":"8.1.0(lite)","BuildDateTime":"2019-12-25T12:36:09","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"336/699"}}
17:46:57 MQT: stat/tasmotazemi/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["VillaTorreZisa",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]}}
17:46:57 MQT: stat/tasmotazemi/STATUS4 = {"StatusMEM":{"ProgramSize":462,"Free":540,"Heap":26,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540C8","FlashMode":3,"Features":["00000809","8F082383","041083A0","20021706","010001C0","00000000"],"Drivers":"1,2,3,4,9,10,16,20,21","Sensors":"3"}}
17:46:57 MQT: stat/tasmotazemi/STATUS5 = {"StatusNET":{"Hostname":"tasmotazemi-1244","IPAddress":"192.168.178.21","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"EC:FA:BC:4B:84:DC","Webserver":2,"WifiConfig":4}}
17:46:57 MQT: stat/tasmotazemi/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.26","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4B84DC","MqttUser":"Felice","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
17:46:57 MQT: stat/tasmotazemi/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 02 16:46:57 2020","Local":"Thu Jan 02 17:46:57 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":"+01:00","Sunrise":"08:43","Sunset":"17:04"}}
17:46:57 MQT: stat/tasmotazemi/STATUS10 = {"StatusSNS":{"Time":"2020-01-02T17:46:57"}}
17:46:57 MQT: stat/tasmotazemi/STATUS11 = {"StatusSTS":{"Time":"2020-01-02T17:46:57","Uptime":"0T00:07:39","UptimeSec":459,"Vcc":3.386,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"VillaTorreZisa","BSSId":"E0:28:6D:80:9A:CD","Channel":1,"RSSI":52,"Signal":-74,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
turn ON the relay, unplug it from the electricity, plug in again. The relay stays off

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
It should turn on

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by shantur**
Fixes #7412

## Description:

Execute poweronstate after all modules are initialized.
TuyaMCU module isn't setup before poweronstate is executed in boot process. 

**Related issue (if applicable):** fixes #7412 

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by shantur** [comment]
PR is ready to merge once reporter confirms the fix is working.
https://github.com/arendst/Tasmota/issues/7412#issuecomment-573225782

**Comment by arendst** [comment]
There must be a better way to let tuya do poweron state. This way users will experience serious delay in power on restore time.

Pls let tuya do it's poweron state during INIT function call.

**Comment by shantur** [comment]
@arendst : Its not only Tuya but any module that manages power states. That would mean all these modules will need to implement poweronstate handling.

When you say serious delay how much delay are we talking? and which of these below would take the most?

```  
RtcInit();
XdrvCall(FUNC_INIT);
  XsnsCall(FUNC_INIT);```

I believe XsnsCall can be moved after poweronstate execution to save time.

**Comment by shantur** [comment]
@arendst  On the other hand poweronstate is only working for people without any module dependency so for them `XdrvCall` should return almost immediately and `XsnsCall` can be moved after poweronstate.
For people with module its anyways going to be slow.
So it all is how long is `RtcInit` going to take

**Comment by arendst** [comment]
Let's assume only Tuya is in trouble. What about you change from FUNC_INIT to FUNC_PRE_INIT and see if that solves your issue.

**Comment by arendst** [comment]
Just released as fix in development. Closing this one.

**Pull request closed without merging**
