### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by andrethomas**
Updated readme

The development branch is checked hourly for changes and if new commits were made it will be rebuilt on the server.

### CODE REVIEW

**Comment by ascillato** [comment]
Cool!

**Comment by andrethomas** [comment]
I was bored... sometimes when bored cool things may happen.

It works! :)

image

**Comment by arendst** [comment]
@andrethomas That looks very good!

But...

Would it be possible to rename the 1m0 files to their default names? The current naming makes OTA-Magic unusable. OTA-Magic uses the minimal version if the requested image does not fit in free space. The mechanism used is as follows:
- It copies OTAUrl and from the back of the OTAUrl it searches the name for a dash (-) and if present it removes the text after the dash.
- It then inserts the text **minimal** and tries to load the minimal version.
- Once the minimal version is loaded it will use the saved OTAUrl to load the requested image.

As you renamed the files using the postfix 1m0 this mechanism will fail.

My suggestions are one of the below where the first probably is most useful:
- remove the 1m0 from the 1M images but leave the 4m0 in place as they will never need OTAMagic
- place the binaries in a separate folder for either 1m0 and 4m0
- do nothing but tell users that OTAMagic will fail as long as the 1m0 versions have a 1m0 postfix.

**Comment by andrethomas** [comment]
@arendst 

> remove the 1m0 from the 1M images but leave the 4m0 in place as they will never need OTAMagic

That sounds like the best plan overall, so I've made the code changes and its currently building the last commit so you can confirm in 10mins or so if the file naming is correct :)

**Comment by andrethomas** [comment]
```
xplg_wemohue.ino: In function 'void HandleUpnpEvent()':
xplg_wemohue:392:5: error: expected ';' before '}' token
     }
     ^
```

There is a bug in the current codebase :|

**Comment by arendst** [comment]
You're right. I failed to compile. Will update.

**Comment by arendst** [comment]
Fixed.

**Comment by andrethomas** [comment]
Forcing rebuild :)

**Comment by arendst** [comment]
Great work did regarding the provision for development releases.

**Comment by andrethomas** [comment]
I hope it will reduce the number of issues opened by people who cannot install a dev environment but want something from the development codebase :)

**Comment by arendst** [comment]
Did you manage to alignment issue?

**Comment by andrethomas** [comment]
The alignment issue seems to be related to platformio and not Linux - compiling with Arduino on Linux the file size is still different to that on Windows but I saw at least one confirm of someone failing with platformio on exact same release where the binaries from the development binaries compiled by Arduino on Linux seem to work - so not totally ruled out but looks like it may be a step in the right direction

**Comment by andrethomas** [comment]
Build complete - please check if filenames conform to requirements?

**Comment by arendst** [comment]
Great. Looks OK.

**Comment by andrethomas** [comment]
Updated table output so that it is more clear to understand which binaries to use

image

**Comment by arendst** [comment]
Or make two table....

**Comment by andrethomas** [comment]
You mean one for 4M's and one for 1M's ?

**Comment by arendst** [comment]
Yep.

**Comment by andrethomas** [comment]
Makes sense... the sorting was confusing me also

**Comment by andrethomas** [comment]
Done

**Comment by arendst** [comment]
Checked. OK!

**Pull request merged**
