### PR TITLE
Adding Lat/Long IP-based detection

### PR DESCRIPTION
**Pull request by tichris0**
This patch adds the ability for Tasmota to detect the user's latitude & longitude based on their IP

This is triggered by setting the latitude/longitude to 0.0 (nowhere in the Ocean)

This is done through 2 web services (one is a backup) that are both free and don't require keys.

Tested:
* Each site individually
* Failure case

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.1
  - [ ] The code change is tested and works on core ESP32 V.1.12.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by tichris0** [comment]
I don't have an ESP32 to test this against.

**Comment by arendst** [comment]
Thx. Nice idea but as it is used only once and takes code space which could be used for more "urgent" features I can only merge if this feature will be disabled by default using a define.

**Comment by stefanbode** [comment]
I agree to let it undefine in default and maybe default on ESP32 where space is less an issue. This capability is more for a manufacturer, who want to sell 1000s of devices with tasmota. great idea, but haven't heard so far.

**Comment by tichris0** [comment]
Alright I'll send another revision tomorrow to hide it by default with the appropriate documentation.  It would be nice to have on-boot, but I agree that it's fighting against basic functionality.

Let me know if you'd like it on for the ESP32.

**Comment by arendst** [comment]
Pls off on both

**Comment by tichris0** [comment]
I've updated the change.  It will only be enable if **USE_AUTOLATLONG** is defined.

**Comment by stefanbode** [comment]
@tichris0 : there is something wrong with your build. All esp32 do not work. If this is correct disabled the error should not happen.

**Comment by tichris0** [comment]
I'm not sure why it failed on ESP32.  It compiled on my side.  Regardless, I've addressed your cnocerns @stefanbode and also fixed a bug I noticed along the way.  Everything has compiled this time around & tested everything again except ESP32 (which I don't own).

I'm curious however as to your request to keep the LAT/LONG to the weird number it was set to.  <0, 0> seems like a safer number given that it's in the middle of the ocean whereas the currently set number seems like it could be valid for someone.

**Comment by tichris0** [comment]
!ping.  This commit is ready to submit.  I'm not sure if I'm expected to do anything else here?

**Comment by arendst** [comment]
Thx. Just did a test on both sites and they were able to locate me over 300km away from where I am. It seems they use the providers presence location.

I don't think this is a viable option to be merged soon.

**Comment by Jason2866** [comment]
Did a test too. 
IPWHOIS.IO -> 300 km off 
ip-api.com -> **got me! Just 1km off**

**Comment by tichris0** [comment]
Yah sounds good.  I'll close it for now.  Thanks

**Pull request closed without merging**
