### PR TITLE
Support for different wattmeter implementations

### PR DESCRIPTION
**Pull request by vicfergar**
Multiple wattmeter implementations using single wattmtr_ functions and vars. User can select which wattmeter implementation will be included in the firmware. Only one or none can be activated within the same firmware.

- Add support to CS5460A sniffer wattmeter
- Add support to PZEM004T wattmeter

### CODE REVIEW

**Comment by gajotnt** [comment]
Hello there, i ordered a pzem004, how can i use this project?

**Comment by vicfergar** [comment]
Hi, I would like to do a walk through of how I did it... Basically follows the wire connections indicated in the sonoff_template.h and enable USE_PZEM004T in the user_config.h file

If you need help just ask ;)

Hope it works for you!

**Comment by gajotnt** [comment]
Im sorry, im feeling very stupid right now, i went to your repository and downloaded the tasmota version you have there and i dont see anything related to PZEM004.
Nevermind -.- had to go the develop branch... feeling very stupid xD

**Comment by gajotnt** [comment]
So i will have to connect the TX of the sonoff to the RX of the PZEM and the RX of the Sonoff to the TX of the PZEM and of course vcc and ground.

```
 { "PZEM004T",        // Board with PZEM004T (ESP8266)
     GPIO_USER,        // GPIO00
     GPIO_USER,        // GPIO01 TX Serial RXD and Optional sensor
     0,                // GPIO02
     GPIO_USER,        // GPIO03 RX Serial TXD and Optional sensor
     GPIO_PZEM_RX,     // GPIO04 PZEM004T RX
     GPIO_PZEM_TX,     // GPIO05 PZEM004T TX
     0, 0, 0, 0, 0, 0, // Flash connection
     GPIO_USER,        // GPIO12
     GPIO_LED1_INV,    // GPIO13 BLUE LED
     GPIO_USER,        // GPIO14 Optional sensor
     0, 0, 0
  },

```

**Comment by gajotnt** [comment]
Hello, can you give some more insight? Flashed the sonoff
Module Type set to: 32 PZEM004T
Dont know if i have to set anything else? IC2?

**Comment by gajotnt** [comment]
Ok, think im starting to understand
changed GPIO_PZEM_RX and GPIO_PZEM_TX to use GPIO 01 and 03 of a sonoff basic. Flash goes well, but still i get no readings -.-

**Comment by gajotnt** [comment]
Got it working finally :)
Just one problem its not publishing to mqtt
```
22:21:42 MQTT: tele/sonoff/STATE = {"Time":"2017-12-11T22:21:42", "Uptime":0, "Vcc":3.451, "Wifi":{"AP":1, "SSID":"TNT", "RSSI":48, "APMac":"9C:97:26:9F:A5:0F"}}
22:21:42 MQTT: tele/sonoff/ENERGY = {"Time":"2017-12-11T22:21:42", "Yesterday":0.000, "Today":0.488, "Period":4, "Power":443.0, "Voltage":234.3, "Current":2.100}
22:22:12 MQTT: tele/sonoff/STATE = {"Time":"2017-12-11T22:22:12", "Uptime":0, "Vcc":3.448, "Wifi":{"AP":1, "SSID":"TNT", "RSSI":48, "APMac":"9C:97:26:9F:A5:0F"}}
22:22:12 MQTT: tele/sonoff/ENERGY = {"Time":"2017-12-11T22:22:12", "Yesterday":0.000, "Today":0.492, "Period":4, "Power":444.0, "Voltage":234.7, "Current":2.130}
```

IDX is properly set in the domoticz menu

**Comment by gajotnt** [comment]
My guess is that the **ixsns_pzem004t.ino** file doesnt have any reference to domoticz.

the **xsns_hlw8012.ino** file has this:

```
#ifdef USE_DOMOTICZ
  if (option) {  // Only send if telemetry
    dtostrf(pet * 1000, 1, 1, stemp1);
    domoticz_sensor4(pw, stemp1);
  }
#endif  // USE_DOMOTICZ
```
That sends the power to the defined idx in **domoticz_sensor4**

i just dont have the knowhow to do this "minor" change :(

**Comment by vicfergar** [comment]
Hi gajotnt, 

as you said I didn't add support to Domoticz because I'm not familiarized with this platform. But I suppose that you can include these lines at the end of the **pzem_mqttStat** function:

```
#ifdef USE_DOMOTICZ
  if (withPeriod) {  // Only send if telemetry
    dtostrf((float)pzem_kWhtoday / 100000, 1, 1, sKWHT);
    domoticz_sensor4(pzem_truePower, sKWHT);
  }
#endif  // USE_DOMOTICZ
```

In this case we are sending the Today value instead of the total one. I haven't tested it, I hope it works!

**Comment by gajotnt** [comment]
Hello Victor, thanks will try that method as soon has I get home, looks more complete than the "patch" I did:

Got it working, after very long trial and error, in case anyone wants to use this here its goes:
add:
```
#ifdef USE_DOMOTICZ
    domoticz_sensor4(power, sTruePower);
#endif  // USE_DOMOTICZ
```
right after: 
```
  snprintf_P(svalue, ssvalue, PSTR("%s\"Yesterday\":%s, \"Today\":%s%s, \"Power\":%s, \"Voltage\":%s, \"Current\":%s}"),
             svalue, sKWHY, sKWHT, (withPeriod) ? sPeriod : "", sTruePower, sVoltage, sCurrent);
```
in **ixsns_pzem004t.ino** file

**Comment by gajotnt** [comment]
Your code works like a charm :D thank you so mutch :D 
You think theres any easy way to push to domoticz the voltage values?

**Comment by arendst** [comment]
I have a PZEM004T lying around and will in time provide support for it. Thnx @vicfergar for your work already done. Glad this works for you all already.

**Comment by vicfergar** [comment]
Great to know it @arendst, the work already done in this PR allow to easily integrate other wattmeter platforms, and activate only once at a time from the firmware side. Hope you can use part of this code for the integration, so other wattmeters can be included in the future. Thanks!

**Comment by arendst** [comment]
I like your approach of having a separate module to choose from. Initially I wanted to integrate with HLW8012 but now I have your PR running I think I just add another file with hooks to the core as you did.

To be continued...

BTW I like your serial stream approach. I have to dive into this to see if it makes code smaller. I also want to abandon the SoftwareSerial library as it takes too much iram. I already did a rewrite for the MHZ19 sensor and want to use this too for this sensor. I could still use HardwareSerial too (GPIO1/3) and switch the device to 9600 bps...  Choices, choices, choices.

**Comment by gajotnt** [comment]
Sorry to bother you again, but it seams its sending the **kWhtoday** instead of **KWhTotal**. Messes Domoticz, every day it resets the KWh totals

Tried to replace the code, but of course, gives me errors all over the place -.- i suck at this

**Comment by vicfergar** [comment]
You are right the code above sends **kWhtoday**, It can be changed to **KWhTotal** just replacing this line:

`dtostrf(pzem_KWhTotal, 1, 1, sKWHT);`

**kWhtoday** and **KWhTotal** are in different magnitudes.

I haven't test it. Hope it works!

**Comment by arendst** [comment]
This now works too:

image

Allowing Energy management on every Sonoff!

**Comment by gajotnt** [comment]
I love you! xD

**Comment by htcheroportugal** [comment]
@vicfergar where i can find your tasmota  with configurations for  pzem?

**Pull request closed without merging**
