### PR TITLE
Support for color and colortone in Philips Hue emulation via Alexa

### LINKED ISSUE #5600: Unsupported "xy" color encoding from Alexa App in Philips Hue emulation
I'm using the Arilux LC01 module with Tasmota 6.5 to control LED, through Philips Hue emulation. When using the Alexa app on iOS: brightness works well but color selection has no effect.

Looking at the logs, I realized that the Alexa app (iOS) sens HSI (xy) color information instead of bri/hue/sat. Looking in the source, it appears that "xy" color space is currently not supported.

Ex (blue):
	`20:05:24 HTP: Hue POST args ({ "on": true, "xy": [0.13550301400290363,0.03987867049354716] })`

I found here how to convert xy to rgb: http://blog.saikoled.com/post/44677718712/how-to-convert-from-hsi-to-rgb-white

It would be great to add "xy" color space to Philips Hue emulation.

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

This provides full support for colors and white color-tone to the Philips Hue emulation via Alexa devices or Alexa smartphone app.

Specifically the Alexa app is very picky about receiving the exact same value that it sent initially. For ex, if it sends Brightness of '43', sometimes due to rounding errors it would send back '42'. The new version sends exactly the same value to the app.

 - to avoid receiving XY colors, don't send any XY colors in HUE lights status
 - adding rounding when converting from float to uint8 to minimise rounding errors when converting from RGB to HSB and back
 - memorize value sent by the app and send back the exact same value if the computed value is within 1%
 - store colors with full brightness in Settings.light_color, and use the Dimmer to adjust brightness. This avoids big conversion errors when converting from RGB to Hue/Sat
 - size code increase is less than 800 bytes

**Related issue (if applicable):** fixes #5600 #4809

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by Jason2866** [comment]
Great! Will try this weekend.
Have you seen PR #5207 too?

**Comment by s-hadinger** [comment]
Yes I've seen #5207 afterwards. I started refactoring part of 'xdrv_04_light.ino' to have a cleaner class-based definition of lights (r/g/b, hue/sat, bri/dimmer), and include both dimmer (0..100) and brightness (0..255). I also plan to move to integer instead of float, I hope to reduce also code size.

**Comment by arendst** [comment]
Wait for @Jason2866 tests and/or @s-hadinger code reducing action.

**Comment by Jason2866** [comment]
@s-hadinger  Bad news, my first test failed. Change did break compatibility with devices with just a relais.
Device switches but there is the error feedback from Alexa.  -> "Device is not responding...." (i did translate from German)
My tests where made with a German Amazon account and a Echo Dot 2nd. Gen.

**Comment by s-hadinger** [comment]
Thanks for the feedback. I tested with AriLux AL-LC01 for color control and with Sonoff B1 to test both color and colortone. I missed the simple relay. Let me check.
Any chance you can grab the logs after enabling Debug_More, there should be the JSON sent back to Alexa?

**Comment by Jason2866** [comment]
Working actual dev (on)
```
13:26:43 WIF: Checking connection...
13:26:43 WIF: Connected
13:26:49 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
13:26:49 HTP: Hue POST args ()
13:26:49 HTP: Hue POST args ({"on": true})
13:26:49 SRC: Hue
13:26:49 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"ON"}
13:26:49 MQT: stat/sonoff-53CF5F/POWER = ON
13:26:49 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
13:26:49 CFG: Saved to flash at F5, Count 57, Bytes 3584
13:27:03 WIF: Checking connection...
13:27:03 WIF: Connected
```
Off
```
13:28:31 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
13:28:31 HTP: Hue POST args ()
13:28:31 HTP: Hue POST args ({"on": false})
13:28:31 SRC: Hue
13:28:31 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"OFF"}
13:28:31 MQT: stat/sonoff-53CF5F/POWER = OFF
13:28:31 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
13:28:31 CFG: Saved to flash at F4, Count 58, Bytes 3584
```
This PR (On):
```
13:44:56 UPP: Multicast (re)joined
13:44:58 HTP: Console
13:44:59 APP: Boot Count 23
13:44:59 CFG: Saved to flash at FA, Count 62, Bytes 3584
13:45:04 MQT: tele/sonoff-53CF5F/STATE = {"Time":"2019-04-18T13:45:04","Uptime":"0T00:00:15","Vcc":2.961,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Jason_Home_WLAN","BSSId":"00:A0:57:2A:BD:19","Channel":9,"RSSI":90,"LinkCount":1,"Downtime":"0T00:00:05"}}
13:45:06 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
13:45:06 HTP: Hue POST args ()
13:45:06 HTP: Hue POST args ({"on": true})
13:45:06 SRC: Hue
13:45:06 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"ON"}
13:45:06 MQT: stat/sonoff-53CF5F/POWER = ON
13:45:06 HTP: Hue Result ([{"success":{"/lights/1/state/on":true}}])
13:45:06 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
13:45:06 HTP: Hue LightResult ({"state":{"on":true,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"154","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
13:45:07 CFG: Saved to flash at F9, Count 63, Bytes 3584
```
OFF:
```
13:47:48 UDP: Packet (199)
13:47:54 WIF: Checking connection...
13:47:54 WIF: Connected
13:48:01 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
13:48:01 HTP: Hue POST args ()
13:48:01 HTP: Hue POST args ({"on": false})
13:48:01 SRC: Hue
13:48:01 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"OFF"}
13:48:01 MQT: stat/sonoff-53CF5F/POWER = OFF
13:48:01 HTP: Hue Result ([{"success":{"/lights/1/state/on":false}}])
13:48:01 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
13:48:01 HTP: Hue LightResult ({"state":{"on":false,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"154","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
13:48:01 CFG: Saved to flash at F8, Count 64, Bytes 3584

```

**Comment by Jason2866** [comment]
Maybe #4712 helps?

**Comment by s-hadinger** [comment]
Yes it helps, thanks. It seems that Alexa app expects a "bri"=0 or "bri"=254 in the response, in addition to the "on":false or "on":true. I mistakenly removed the "bri" attribute in the response for simple on/off relays, we probably need it after all.

**Comment by s-hadinger** [comment]
@Jason2866 In between if you want to try it, remove lines 589 and 591 in sonoff/xplg_wemohue.ino
This will force the response to always include "bri" status

From: 
```
  if (LST_SINGLE <= light_subtype) {
    light_status += "\"bri\":" + String((uint8_t)(254.0f * bri + 0.5f)) + ",";
  }
```

to:
```
light_status += "\"bri\":" + String((uint8_t)(254.0f * bri + 0.5f)) + ",";
```

**Comment by Jason2866** [comment]
@s-hadinger  Relais is switching fine with the suggested change from you (line 589-591). 
No error message from Alexa. :-)

**Comment by Jason2866** [comment]
Configured
image
I cant control device via Alex with color commands.
"Device doesnt support this" Controlling dimmer function does work "Alexa <device> 50%" does work.
Alexa App just shows Lamp symbol and slider for brightness. No color select "things" menus buttons or such stuff

**Comment by Jason2866** [comment]
Have to resolder and reflash my AiLight lamp via serial because OTA update did fail....
So just test possibilities at the moment with device with no "light" feedback

**Comment by s-hadinger** [comment]
@Jason2866 Color detection is based on LightSubtypes (sonoff.h) and will display color selection only for LST_RGB, LST_RGBW and LST_RGBWC.
I don't know how this subtype is configured or how you can force it.

**Comment by Jason2866** [comment]
Ahh, understand!

**Comment by Jason2866** [comment]
Mhhh, i selected Sonoff B1 it should work with. Do i overlook something?
With which device you have tried?

**Comment by s-hadinger** [comment]
Yes I tested Sonoff B1 (not with the real device unfortunately) and the Alexa app should display both White with Color Temperature, and Color selector.
Is the problem in the Alexa app or in the bulb?

I tested with an actual Arilux LC01 and it works with colors only (no white color temperature)

**Comment by Jason2866** [comment]
Thx, for feedback. I will erase flash of wemos and start from a clean device with a sonoff B1 (module)
Power cycle Echo Dot and delete (as always) device in APP
I dont had any color stuff in Alexa APP

**Comment by Jason2866** [comment]
Which core do you use? Tried 2.4.2. and 2.5.x (feature/stage).
Never get color stuff in Alexa App

**Comment by s-hadinger** [comment]
I use core 2.4.2, but it shouldn't have any impact, it only depends on the JSON returned back to Alexa.

I just re-flashed, erased configuration, set to Sonoff B1 (26). There is indeed an issue the first time after device discovery, the app complains about "Value not supported on this app". After turning on and moving the slider, color and colortone can be changed.

So there is definitely an issue after configuration reset. I will dig into it.

**Comment by Jason2866** [comment]
If i use the dev version (without your changes) i get a color selector in Alexa APP.
Not working for sure, but it is there. With your changes it is 100% disappering

**Comment by s-hadinger** [comment]
Thanks. I found the initialization issue, "ct":0 is not a valid value, it should be at least "ct":500. Will correct it.

Still I do get both selectors, first the color-tone selector and when I scroll down the color selector.

Could you please send the log line with the JSON response from the device?

Here is what it looks for me:
```
19:20:46 HTP: Hue LightResult ({"state":{"on":true,"bri":119,"hue":0,"sat":0,"ct":383,"alert":"none","effect":"none","colormode":"ct","reachable":true},"type":"Extended color light","name":"Led","modelid":"LCT007","uniqueid":"dc:4f:22:fd:b1:fe:00:11-1","swversion":"5.50.1.19085"})
```

**Comment by Jason2866** [comment]
```
20:37:10 HTP: Configuration
20:37:10 CFG: Saved to flash at F7, Count 58, Bytes 3584
20:37:12 HTP: Main Menu
20:37:15 HTP: Configuration
20:37:16 HTP: Main Menu
20:37:19 HTP: Console
20:37:25 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
20:37:25 HTP: Hue POST args ()
20:37:25 HTP: Hue POST args ({"on": false})
20:37:25 SRC: Hue
20:37:25 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"OFF"}
20:37:25 MQT: stat/sonoff-53CF5F/POWER = OFF
20:37:25 HTP: Hue Result ([{"success":{"/lights/1/state/on":false}}])
20:37:25 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
20:37:25 HTP: Hue LightResult ({"state":{"on":false,"bri":104,"hue":0,"sat":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
20:37:25 CFG: Saved to flash at F6, Count 59, Bytes 3584
20:37:25 WIF: Checking connection...
20:37:25 WIF: Connected
20:37:30 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
20:37:30 HTP: Hue POST args ()
20:37:30 HTP: Hue POST args ({"on": true})
20:37:30 SRC: Hue
20:37:30 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"ON"}
20:37:30 MQT: stat/sonoff-53CF5F/POWER = ON
20:37:30 HTP: Hue Result ([{"success":{"/lights/1/state/on":true}}])
20:37:30 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
20:37:30 HTP: Hue LightResult ({"state":{"on":true,"bri":104,"hue":0,"sat":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
20:37:31 CFG: Saved to flash at F5, Count 60, Bytes 3584
20:37:39 UDP: Packet (199)
```

**Comment by s-hadinger** [comment]
Just pushed a correction to enforce correct "ct" after initialization.

Your log shows no "ct" parameter which means that the device is recognized as LST_RGB or LST_RGBW, not as LST_RGBWC. With the log you just posted, you should have only the color selector, not the white-tone selector.

Could you just try sending "Color 3" command in the Console to force a non-white color, before launching the Alexa device discovery?

**Comment by Jason2866** [comment]
Doesnt help, did this (color 1) already before.
```

21:18:11 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:18:11 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":43690,"sat":254,"ct":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:18:26 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:18:26 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":43690,"sat":254,"ct":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:18:27 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
21:18:27 HTP: Hue POST args ()
21:18:27 HTP: Hue POST args ({"on": false})
21:18:27 SRC: Hue
21:18:27 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"OFF"}
21:18:27 MQT: stat/sonoff-53CF5F/POWER = OFF
21:18:27 HTP: Hue Result ([{"success":{"/lights/1/state/on":false}}])
21:18:28 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:18:28 HTP: Hue LightResult ({"state":{"on":false,"bri":254,"hue":43690,"sat":254,"ct":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:18:28 CFG: Saved to flash at F6, Count 67, Bytes 3584
21:18:28 WIF: Checking connection...
21:18:28 WIF: Connected
21:18:31 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
21:18:31 HTP: Hue POST args ()
21:18:31 HTP: Hue POST args ({"on": true})
21:18:31 SRC: Hue
21:18:31 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"ON"}
21:18:31 MQT: stat/sonoff-53CF5F/POWER = ON
21:18:31 HTP: Hue Result ([{"success":{"/lights/1/state/on":true}}])
21:18:31 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:18:31 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":43690,"sat":254,"ct":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:20:39 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:20:39 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":43690,"sat":254,"ct":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:20:41 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
21:20:41 HTP: Hue POST args ()
21:20:41 HTP: Hue POST args ({"on": false})
21:20:41 SRC: Hue
21:20:41 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"OFF"}
21:20:41 MQT: stat/sonoff-53CF5F/POWER = OFF
21:20:41 HTP: Hue Result ([{"success":{"/lights/1/state/on":false}}])
21:20:41 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:20:41 HTP: Hue LightResult ({"state":{"on":false,"bri":254,"hue":43690,"sat":254,"ct":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:20:41 CFG: Saved to flash at FA, Count 71, Bytes 3584
21:20:42 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
21:20:42 HTP: Hue POST args ()
21:20:42 HTP: Hue POST args ({"on": true})
```

**Comment by s-hadinger** [comment]
Sorry, you need to include the last two commits. The response with "ct":0 is the cause of the Alexa app going wrong. Commit 599306a corrects it.

**Comment by Jason2866** [comment]
I dont get for ct no other values than 0.

**Comment by s-hadinger** [comment]
The log below is the json sent back to the Alexa app:

```
21:20:41 HTP: Hue LightResult ({"state":{"on":false,"bri":254,"hue":43690,"sat":254,"ct":0,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
```

Unfortunately the attribute "ct":0 is an invalid value for the Alexa app. "ct" contains the white-color temperature (ie. warm white, cold white), also known as "colortone". The "ct" value should be between 150 and 500 (roughly). When the Alexa app receive a "ct":0 value, it considers the entire response as invalid and starts behaving weirdly.

Commit 599306a enforces that "ct" value is never zero, and defaults to 284 (medium-white)

**Comment by Jason2866** [comment]
No success. Still only dimmer slider in ALEXA App
```

21:52:40 WIF: Checking connection...
21:52:40 WIF: Connected
21:52:58 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:52:58 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:00 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:00 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:00 WIF: Checking connection...
21:53:00 WIF: Connected
21:53:02 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
21:53:02 HTP: Hue POST args ()
21:53:02 HTP: Hue POST args ({"on": false})
21:53:02 SRC: Hue
21:53:02 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"OFF"}
21:53:02 MQT: stat/sonoff-53CF5F/POWER = OFF
21:53:02 HTP: Hue Result ([{"success":{"/lights/1/state/on":false}}])
21:53:02 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:02 HTP: Hue LightResult ({"state":{"on":false,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:03 CFG: Saved to flash at F7, Count 79, Bytes 3584
21:53:03 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
21:53:03 HTP: Hue POST args ()
21:53:03 HTP: Hue POST args ({"on": true})
21:53:03 SRC: Hue
21:53:03 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"ON"}
21:53:03 MQT: stat/sonoff-53CF5F/POWER = ON
21:53:03 HTP: Hue Result ([{"success":{"/lights/1/state/on":true}}])
21:53:03 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:03 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:04 CFG: Saved to flash at F6, Count 80, Bytes 3584
21:53:07 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:07 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:10 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:10 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:13 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:13 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:16 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:16 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:19 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:19 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:20 WIF: Checking connection...
21:53:20 WIF: Connected
21:53:22 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:22 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:25 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:25 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:28 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:28 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:31 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:31 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:33 UDP: Packet (199)
21:53:33 UDP: Packet (199)
21:53:33 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:34 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:34 HTP: Hue LightResult ({"state":{"on":true,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:34 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:34 UDP: Packet (199)
21:53:35 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1/state)
21:53:35 HTP: Hue POST args ()
21:53:35 HTP: Hue POST args ({"on": false})
21:53:35 SRC: Hue
21:53:35 MQT: stat/sonoff-53CF5F/RESULT = {"POWER":"OFF"}
21:53:35 MQT: stat/sonoff-53CF5F/POWER = OFF
21:53:35 HTP: Hue Result ([{"success":{"/lights/1/state/on":false}}])
21:53:35 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:35 HTP: Hue LightResult ({"state":{"on":false,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:35 CFG: Saved to flash at F5, Count 81, Bytes 3584
21:53:38 HTP: Hue API (/vr0cFpv41CwnP3PpmyLwZaX0BtBARCMSNr6fkZc9/lights/1)
21:53:38 HTP: Hue LightResult ({"state":{"on":false,"bri":254,"hue":21845,"sat":254,"ct":284,"alert":"none","effect":"none","colormode":"hs","reachable":true},"type":"Extended color light","name":"Lampe","modelid":"LCT007","uniqueid":"b4:e6:2d:53:cf:5f:00:11-1","swversion":"5.50.1.19085"})
21:53:40 WIF: Checking connection...
21:53:40 WIF: Connected
```

**Comment by s-hadinger** [comment]
This is weird, I have no clue why it is not detected as color-enabled. It works fine on the French version of Alexa app on iOS. I hope we don't need to get back "xy" colors which would require a lot of additional code.

**Comment by s-hadinger** [comment]
@Jason2866 I just pushed commit 5732efa to add the 'xy' color space response in to the Alexa app. I hope this will trigger the color selector in the Alexa app.

Can you please try with this one?

**Comment by Jason2866** [comment]
@s-hadinger  commit https://github.com/arendst/Sonoff-Tasmota/commit/5732efa27c20e01801fff4c07ea30d68ecb6eee3 does trigger color selector in Alexa App.
Commands like Alexa "lamp green" does work

**Comment by Jason2866** [comment]
@s-hadinger  Your branch https://github.com/s-hadinger/Sonoff-Tasmota/tree/feature/light_refactor
does work for switching and dimming (no color selector) and for devices with a relais

**Comment by Jason2866** [comment]
Mhh, maybe xy color space can be tricked (not used for real values) to get sliders in Alexa App?
Color support done via RGB.

**Comment by s-hadinger** [comment]
My bad, I forgot to display 'xy' only for color devices, and not for all devices (don't code late at night).
With this new commit it should work.

Branch https://github.com/s-hadinger/Sonoff-Tasmota/tree/feature/light_refactor is only work in progress for now, but behaves identically for now.

**Comment by Jason2866** [comment]
Seems to work. Still have to bring back my Arilux lamp to life to see if it is really changing colors
But Alexa is still wired
Defined color "ticked" dissapear after a second. Lamp appears always in white shape

**Comment by s-hadinger** [comment]
Ok, now I understand better how the Alexa app reacts. I completely reviewed what parameters to send back depending on the light type. I hope that commit b5860b9 finally solves this all.

Tested with the following profiles:
 - Sonoff basic - on/of
 - Sonoff BN-NZ - on/off, slider
 - Sonoff LED - on/off, slider, white temp
 - Sonoff B1 - on/off, slider, white temp, color chooser
 - AriLux AL-LC01 - on/off, slider, color chooser

**Comment by Jason2866** [comment]
Looks good :-). Alexa discovery works as it should and commands are working without a error from ALEXA.
Hope i find time to solder and flash my AiLight....

**Comment by s-hadinger** [comment]
@arendst It will take more time to finish the refactoring of light control than I thought. I'm still working on it, but it may be good to merge this one in between.

**Comment by Jason2866** [comment]
@s-hadinger  Theo has little / no time to work on Tasmota the next weeks. See https://github.com/arendst/Sonoff-Tasmota/issues/5671#issuecomment-484935427

@arendst  Tested this PR. It solves not exact dimmer values. It is better than the current implementation!
I recommend to merge. If problems occur (i dont think so) it could easily reverted.
Maybe it solves strange problems like #5672

**Comment by s-hadinger** [comment]
I doubt it solves #5672, this portion of code was unchanged. I did all my tests with static IP address through the DHCP of my router.

**Pull request merged**
