### PR TITLE
Ble esp32 iBeacon cleanup & update 

### PR DESCRIPTION
**Pull request by btsimonh**
## Description:
1/ Starts BLE scanning as soon as we have connected to a device (or failed).  This allows us to catch a few extra adverts compared to the initial version.
2/ includes a small change in MI BLE_ESP32 based driver.
3/ Cleans up the iBeacon driver:

Includes the driver whenever BLE_ESP32 is enabled.
Removes serial code from BLE_ESP32 version (so simplifying code).
iBeacon is not enabled unless you issue 'iBeacon 1'.   You may disable it with 'iBeacon 0'.
NAME is fixed.
Timeout and Period (interval) are tested.
Adds ability to use BLEAlias to name devices.
Adds ability to filter based on BLEAlias prefix.
Adds a 'PERSEC' value to the MQTT message - allows the button press to be sensed in a basic way for the iTag style beacons.

Additional simplified commands:
```
////////////////////////////////////////
// Commands:
// iBeacon 0/1 - Enable 
// iBeaconOnlyAliased 0/1/2 - 
//   0 = all BLE devices, 
//   1 = only devices with any BLEAlias
//   2 = only devices which have BLEAlias starting "iB" 
// iBeaconClear - clear list NOW
// iBeaconPeriod (sec) - update period - default 10s
// iBeaconTimeout (sec) - timeout period - default 30s
//
// posts MQTT about each beacon every iBeaconPeriod (default 10s)
// MQTT like
// tele/tasmota_E89E98/SENSOR = {"Time":"2021-02-04T23:20:22","IBEACON":{"MAC":"FFFFA0003B19","NAME":"iB1","RSSI":-81,"STATE":"ON","PERSEC":10}}
//  Always present:
//   Time: time of MQTT send
//   IBEACON.MAC
//   IBEACON.RSSI
//   IBEACON.STATE - ON - present, OFF - last MQTT you will get for now (device removed)
//  Optional:
//   IBEACON.NAME - name if in scan, or BLEAlias if set - only present if NAME present
//   IBEACON.PERSEC - count of adverts per sec.  USeful for detecting button press?
//   IBEACON.MAJOR - some iBeacon related term? - only present for some
//   IBEACON.MINOR - some iBeacon related term? - only present for some
////////////////////////////////////////
```

This is tested on iTag (basic keychain beacon) plus other non-beacon BLE devices.
I invite testing from someone with 'real' iBeacons.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc6
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by btsimonh** [comment]
Note that this could be enhanced quite easily with:
battery read (an active read - it's not in the adverts, iTag should support the 'standard' battery read - not tried it).
Causing the beacon to beep - I have had one of mine beep on command with a manual bleop.
In fact, battery read could be added as a 'standard' BLE command BLEBatt alias|mac - as a lot of devices do support the 'normal' battery command.

**Comment by SHA-NDY** [comment]
Hi,

is there a full command list available? I played around with internal bluetooth using MI32Beacon functionality but stumbled upon this and am trying now.
A BLEscan doesn't return my advertising Gatt-Server anymore. How can I add a beacon with specific MAC address and perform actions upon its detection?
My problem with the MI32Beacon command was that the beacons never disappeared after first detection even if they were not present any more. I try to scan my bike's BLE tachometer to open my garage door.

**Comment by btsimonh** [comment]
hi @SHA-NDY,
funny, just did the docs yesterday :).
Until the docs PR goes public, you can see them here:
https://btsimonh.github.io/docs/ble/Bluetooth-Esp32/

Also, I'd recommend the discord server - we have an active friendly BLE group on there.
"my advertising Gatt-Server" - most likely it's using a 'static random' address.  We specifically default to only showing 'Public static' addresses, mainly so that mobiles did not blow us away with covid adverts on random changing addresses.
Look up 'BLEAddrFilter' in the above docs - basically if you 'BLEAddrFilter 1', it will probably pop up.  Then use BLEAlias to name your beacon's mac , and then 'iBeaconOnlyAliased 2' to only recognise aliases starting with 'iB'.

Be aware that BLE is now in it's own -bluetooth firmware for the moment.  If you want it with sensors, for example, it's a self build.

br, simon

**Comment by SHA-NDY** [comment]
Thanks for your quick response, I'll try!

**Comment by SHA-NDY** [comment]
One more question on command "BLEMode". What does "scan regularly" in this context mean? This is important to me as this defines the maximum time I have to expose my bike's BLE function before it gets recognized. It has auto-off about 30s then I have to re-enable BLE on my bike.

**Comment by btsimonh** [comment]
'scan regularly' means keep it scanning all the time unless actively trying to connect to something (as soon as it IS connected, it starts the scan again, but the act of connecting stalls the scan until it succeeds or fails - that's just BLE :( ).
So, it should see your bike as soon as you activate it unless you are controlling 5 EQ3 valves at the same moment!

**Comment by SHA-NDY** [comment]
Alright! I just wonder how you got it working because I deeply struggled to implement Wifi connection and simultaneously using BLE functionality on ESP32 with Arduino IDE. Deep respect for investing time and effort on this!

**Comment by btsimonh** [comment]
about 6 weeks of hell!
But...  there were improvements in the IDE & SDKs in that time.  I too tried about 18 months ago, and failed;   Late last year I found the ESP32s I had bought, found that Theo had added formal ESP32 support in TAS!, found that there was some BLE already (but not quite enough for my EQ3 control), and decided to take it on.  Have fun :)

**Comment by SHA-NDY** [comment]
Thanks a lot!

**Comment by leranp** [comment]
@btsimonh 
Thanks for this Ibeacon option , it work great,
but now I am trying to figure out how to add this to HA as sensor , my problem is that when the scan started and he doesn't found one of the ibeacon ( that is in the BLEAlias list) he doesn't send MQTT message with "STATE":"OFF" , this is the only option for me to make the sensor in Home Assistant .

**Comment by btsimonh** [comment]
hmm..  yes I see what you mean.  Once it has seen the sensor, it will send "STATE":"OFF" to indicate it's gone away.
However, this does not protect from TAS losing power and then the iBeacon moving away.

In HA, you can specify a timeout for data - I don't know if you can specify an initial value of OFF for when HA restarts.

The trouble is, the iBeacon driver does not currently 'know' about the BLEAlias except when data is received.
I could imaging some option where it looks through all aliases starting with "iB", and if not present sends the OFF at teleperiod, but it's new functionality.

What I've not got my head around yet is how to design proximity for HA.  Imagine a TAS in each room, and we want HA to know if the iBeacon is in a room, and if so which one (or even better, to have a prediction of position inside the rooms when multiple TAS 'hear' the iBeacon).  Any examples of how this could be done would really help in adapting the iBeacon code to work better.

**Comment by SHA-NDY** [comment]
Do you know, by coincidence, if the ESP32 builtin Hall sensor is implemented somehow?
Sorry for being off-topic here...

**Comment by ascillato2** [comment]
@SHA-NDY 

OFFTOPIC: The hall sensor is not implemented.

**Comment by SHA-NDY** [comment]
> @SHA-NDY 
> 
> OFFTOPIC: The hall sensor is not implemented.

Thanks for quick response

**Pull request merged**
