### PR TITLE
prepare changes for ESP-idf > 4.0

### PR DESCRIPTION
**Pull request by Staars**
## Description:

Add compile options to build for current and coming ESP-idf.
Should not change anything else.

@Jason2866 Please check.
@arendst I have no ethernet equipped ESP32 for testing.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.7
  - [x] The code change is tested and works on core ESP32 V.1.12.4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Review by Jason2866 — APPROVED** [review]

**Comment by Jason2866** [comment]
@arendst  Would suggest to build the development Tasmota32 on the current Arduuno ESP32 commit. I could make a Arduino Tasmota32 core. Faster setup in Platformio

**Comment by Staars** [comment]
Not so quick ;)
I would rather suggest an additional build environment, like tasmota-idf4.2. This is less dangerous but enables easier testing.
I am pretty sure, we will see problems with the latest core.

**Comment by Jason2866** [comment]
@Staars  there is a missunderstanding the Esp32 Arduino master branch is still based on IDF3.3
The new IDF4.x are extra branches NOT the master branch. So we are NOT using a new release.
Still the same IDF version as we use now. "Just" with enhancements and fixes

**Comment by Jason2866** [comment]
I like the idea to try Arduino ESP32 IDF4.2 with Tasmota32.
Will provide a setup and make the needed toolchain-xtensa packages for platformio
Stay tuned...

**Comment by arendst** [comment]
@Jason2866 yes let's try your suggestion and add a tasmota32 core like you did for esp8266.

COnsidering the changes in here I guess they are transparent for the current version. I will test them now with regards to ethernet and if works well I'll merge ASAP.

**Comment by kugelkopf123** [comment]
ESP32 with idf4 should fix the double hitter with connecting to Fritz box routers. 
It would be great if this works with Tasmota, too.

**Pull request merged**
