### PR TITLE
Switches: MQTT decoupling and regression fix

### LINKED ISSUE #9715: 9.0.0.3 Breaks Sonoff Slampher(9)
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
On OTA upgrade from 8.4.0 or 8.5.0 to 9.0.0.3 the Sonoff Slampher will not take input from the gpio1 button or from the RF input.  I saw the problem with installed systems and a custom Template, so I flashed a factory fresh Slampher with 8.4.0, paired it and it worked fine.  I then ota updated it to 9.00.3 and neither the button or the rf signal willl turn it on.  SO73 on or off, it doesn't matter.  The button on the web console and from MQTT still function normally.  Just the RF and the onboard button do not function.
Only tested with OTA from 8.4.0 and 8.5.0 to 9.0.0.3.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4) possible related: https://discordapp.com/channels/479389167382691863/479389167382691865/772846026196910122 
- [x] Device used (e.g., Sonoff Basic): __slampher(9)___
- [x] Tasmota binary firmware version number used: __9.0.0.3___
  - [x] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [x] Flashing tools used: __factory webui OTA___
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
00:00:00 CFG: Loaded from flash at F7, Count 55
00:00:00 Project tasmota Tasmota Version 9.0.0.3(tasmota)-2_7_4_5
00:00:04 WIF: Connecting to AP1 Creative Touch Channel 3 BSSId 08:62:66:91:70:30 in mode 11N as StairTopLight...
00:00:05 WIF: Connected
11:06:37 HTP: Web server active on StairTopLight with IP address 192.168.110.37
11:06:38 MQT: Attempting connection...
11:06:40 MQT: Connected
11:06:41 MQT: tasmota_AA1403/tele/LWT = Online (retained)
11:06:41 MQT: tasmota_AA1403/cmnd/POWER = 
11:06:41 MQT: tasmota_AA1403/tele/INFO1 = {"Module":"Slampher","Version":"9.0.0.3(tasmota)","FallbackTopic":"cmnd/DVES_AA1403_fb/","GroupTopic":"tasmotas/cmnd/"}
11:06:41 MQT: tasmota_AA1403/tele/INFO2 = {"WebServerMode":"Admin","Hostname":"StairTopLight","IPAddress":"192.168.110.37"}
11:06:41 MQT: tasmota_AA1403/tele/INFO3 = {"RestartReason":"Power On"}
11:06:41 MQT: tasmota_AA1403/stat/RESULT = {"POWER":"OFF"}
11:06:41 MQT: tasmota_AA1403/stat/POWER = OFF
11:06:43 MQT: tasmota_AA1403/stat/RESULT = {"Timezone":99}
11:06:43 MQT: tasmota_AA1403/stat/RESULT = {"TimeDst":{"Hemisphere":0,"Week":2,"Month":3,"Day":1,"Hour":2,"Offset":-300}}
11:06:43 MQT: tasmota_AA1403/stat/RESULT = {"TimeStd":{"Hemisphere":0,"Week":1,"Month":11,"Day":1,"Hour":2,"Offset":-360}}
11:06:43 MQT: tasmota_AA1403/stat/RESULT = {"NtpServer1":"10.10.100.1"}
11:06:44 MQT: tasmota_AA1403/stat/RESULT = {"Latitude":43}
11:06:44 MQT: tasmota_AA1403/stat/RESULT = {"Longitude":-88}
11:06:44 MQT: tasmota_AA1403/stat/RESULT = {"Altitude":262}
11:06:45 MQT: tasmota_AA1403/tele/STATE = {"Time":"2020-11-02T11:06:45","Uptime":"0T00:00:16","UptimeSec":16,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":24,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Creative Touch","BSSId":"08:62:66:91:70:30","Channel":3,"RSSI":100,"Signal":-39,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:11:45 MQT: tasmota_AA1403/tele/STATE = {"Time":"2020-11-02T11:11:45","Uptime":"0T00:05:16","UptimeSec":316,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Creative Touch","BSSId":"08:62:66:91:70:30","Channel":3,"RSSI":100,"Signal":-42,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:15:44 CMD: so70
11:15:44 MQT: tasmota_AA1403/stat/RESULT = {"SetOption70":"OFF"}
11:16:45 MQT: tasmota_AA1403/tele/STATE = {"Time":"2020-11-02T11:16:45","Uptime":"0T00:10:16","UptimeSec":616,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Creative Touch","BSSId":"08:62:66:91:70:30","Channel":3,"RSSI":100,"Signal":-42,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:21:45 MQT: tasmota_AA1403/tele/STATE = {"Time":"2020-11-02T11:21:45","Uptime":"0T00:15:16","UptimeSec":916,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Creative Touch","BSSId":"08:62:66:91:70:30","Channel":3,"RSSI":100,"Signal":-42,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:26:45 MQT: tasmota_AA1403/tele/STATE = {"Time":"2020-11-02T11:26:45","Uptime":"0T00:20:16","UptimeSec":1216,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Creative Touch","BSSId":"08:62:66:91:70:30","Channel":3,"RSSI":100,"Signal":-50,"LinkCount":1,"Downtime":"0T00:00:07"}}
11:30:49 CMD: Backlog Template; Module; GPIO 255
11:30:49 MQT: tasmota_AA1403/stat/RESULT = {"NAME":"Generic","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":18}
11:30:49 MQT: tasmota_AA1403/stat/RESULT = {"Module":{"9":"Slampher"}}
11:30:50 MQT: tasmota_AA1403/stat/RESULT = {"GPIO0":{"32":"Button1"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"224":"Relay1"},"GPIO13":{"320":"Led_i1"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

  Configuration output here:
scratch slampher.  no template changes from factory Tasmota 9.0.0.3 Slampher(9) module

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:

11:57:30 CMD: rule0
11:57:30 MQT: tasmota_AA1403/stat/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
11:57:30 MQT: tasmota_AA1403/stat/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
11:57:30 MQT: tasmota_AA1403/stat/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
```
- [x] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
11:52:55 CMD: status 0
11:52:55 MQT: tasmota_AA1403/stat/STATUS = {"Status":{"Module":9,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_AA1403","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:52:55 MQT: tasmota_AA1403/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota.bin.gz","RestartReason":"Power On","Uptime":"0T00:46:26","StartupUTC":"2020-11-02T17:06:29","Sleep":50,"CfgHolder":4617,"BootCount":9,"BCResetTime":"2020-11-02T17:28:10","SaveCount":56,"SaveAddress":"F6000"}}
11:52:55 MQT: tasmota_AA1403/stat/STATUS2 = {"StatusFWR":{"Version":"9.0.0.3(tasmota)","BuildDateTime":"2020-11-02T15:13:49","Boot":31,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"457/699"}}
11:52:55 MQT: tasmota_AA1403/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":2,"SysLog":2,"LogHost":"10.10.100.10","LogPort":2554,"SSId":["ct Touch","ct Touch"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","000080C8","00006000","00000000"]}}
11:52:56 MQT: tasmota_AA1403/stat/STATUS4 = {"StatusMEM":{"ProgramSize":599,"Free":404,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
11:52:56 MQT: tasmota_AA1403/stat/STATUS5 = {"StatusNET":{"Hostname":"StairTopLight","IPAddress":"192.168.110.37","Gateway":"192.168.108.1","Subnetmask":"255.255.252.0","DNSServer":"192.168.108.1","Mac":"DC:4F:22:AA:14:03","Webserver":2,"WifiConfig":4,"WifiPower":17.0}}
11:52:56 MQT: tasmota_AA1403/stat/STATUS6 = {"StatusMQT":{"MqttHost":"10.10.100.10","MqttPort":1833,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_AA1403","MqttUser":"HassSmartbed","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
11:52:56 MQT: tasmota_AA1403/stat/STATUS7 = {"StatusTIM":{"UTC":"2020-11-02T17:52:56","Local":"2020-11-02T11:52:56","StartDST":"2020-03-08T02:00:00","EndDST":"2020-11-01T02:00:00","Timezone":99,"Sunrise":"06:28","Sunset":"16:42"}}
11:52:56 MQT: tasmota_AA1403/stat/STATUS10 = {"StatusSNS":{"Time":"2020-11-02T11:52:56"}}
11:52:56 MQT: tasmota_AA1403/stat/STATUS11 = {"StatusSTS":{"Time":"2020-11-02T11:52:56","Uptime":"0T00:46:27","UptimeSec":2787,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"ct Touch","BSSId":"08:62:66:91:70:3a","Channel":3,"RSSI":100,"Signal":-38,"LinkCount":1,"Downtime":"0T00:00:07"}}}

```
- [x] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
```
The button press and the RF trigger (red light) do not show in the console. (bad)
Webui control of the screen button works to toggle the light. (normal)
MQTT control of the (button)relay works to toggle the light. (normal)
Nothing to capture here on the bad behavior.
```

### TO REPRODUCE
_Steps to reproduce the behavior:_
OTA Flash a working (and RF paired) Slampher to 9.0.0.3
I am assuming it is paired with the HA Tasmota release 0.117.1 integration as that is running on my network, this device should have been spotted.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
Onboard button should toggle the relay.
Paired RF Signal should trigger the red light and the relay.  Only red light is triggered.
video below shows expected behavior and behavior after 9.0.0.3

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
8.4.0 behavior:  https://imgur.com/a/MMcuOt4
9.0.0.3 behavior: https://imgur.com/a/FZAKoF2

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

Possible related issue on Discord with a 4 channel relay:   https://discordapp.com/channels/479389167382691863/479389167382691865/772846026196910122

**(Please, remember to close the issue when the problem has been addressed)**

### LINKED ISSUE #9719: 9.0.0.3 breaks button on Athom plugs
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
Athom plug as: https://templates.blakadder.com/athom_PG01EU16A.html
button working on 9.0.0.2, upgraded to 9.0.0.3 and now it does not, while relay trigger is fine via mqtt or web gui

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [X] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): Athom PG01EU16A
- [X] Tasmota binary firmware version number used: 9.0.0.3 as per today's "ota.tasmota.com" build
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:
21:05:56 CMD: Backlog Template; Module; GPIO 255
21:05:56 SRC: WebConsole from 192.168.1.121
21:05:56 CMD: Group 0, Index 1, Command "BACKLOG", Data "Template; Module; GPIO 255"
21:05:56 SRC: Backlog
21:05:56 CMD: Group 0, Index 1, Command "TEMPLATE", Data ""
21:05:56 MQT: stat/Athom1/RESULT = {"NAME":"Athom PG01EU16A","GPIO":[0,0,0,32,2720,2656,0,0,2624,544,224,0,0,0],"FLAG":0,"BASE":1}
21:05:57 SRC: Backlog
21:05:57 CMD: Group 0, Index 1, Command "MODULE", Data ""
21:05:57 MQT: stat/Athom1/RESULT = {"Module":{"0":"Athom PG01EU16A"}}
21:05:57 SRC: Backlog
21:05:57 CMD: Group 0, Index 1, Command "GPIO", Data "255"
21:05:57 MQT: stat/Athom1/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"32":"Button1"},"GPIO4":{"2720":"BL0937 CF"},"GPIO5":{"2656":"HLWBL CF1"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"2624":"HLWBL SEL_i"},"GPIO13":{"544":"LedLink"},"GPIO14":{"224":"Relay1"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:
21:06:34 CMD: Backlog Rule1; Rule2; Rule3
21:06:34 SRC: WebConsole from 192.168.1.121
21:06:34 CMD: Group 0, Index 1, Command "BACKLOG", Data "Rule1; Rule2; Rule3"
21:06:34 SRC: Backlog
21:06:34 CMD: Group 0, Index 1, Command "RULE", Data ""
21:06:34 MQT: stat/Athom1/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
21:06:34 SRC: Backlog
21:06:34 CMD: Group 0, Index 2, Command "RULE", Data ""
21:06:34 MQT: stat/Athom1/RESULT = {"Rule2":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}
21:06:35 SRC: Backlog
21:06:35 CMD: Group 0, Index 3, Command "RULE", Data ""
21:06:35 MQT: stat/Athom1/RESULT = {"Rule3":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}

```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:
21:07:00 CMD: Group 0, Index 1, Command "STATUS", Data "0"
21:07:00 MQT: stat/Athom1/STATUS = {"Status":{"Module":0,"DeviceName":"Athom1","FriendlyName":["Athom1"],"Topic":"Athom1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
21:07:00 MQT: stat/Athom1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota/tasmota.bin.gz","RestartReason":"Power On","Uptime":"0T00:05:03","StartupUTC":"2020-11-02T20:01:57","Sleep":50,"CfgHolder":4617,"BootCount":16,"BCResetTime":"2020-10-17T18:33:07","SaveCount":60,"SaveAddress":"F9000"}}
21:07:00 MQT: stat/Athom1/STATUS2 = {"StatusFWR":{"Version":"9.0.0.3(tasmota)","BuildDateTime":"2020-11-02T15:13:49","Boot":31,"Core":"2_7_4_5","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"406/699"}}
21:07:00 MQT: stat/Athom1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SharkIOT","Shark-HOME2"],"TelePeriod":300,"Resolution":"55A180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00006000","00000000"]}}
21:07:00 MQT: stat/Athom1/STATUS4 = {"StatusMEM":{"ProgramSize":599,"Free":404,"Heap":24,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540A1","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8FDAE797","04368001","000000CF","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"}}
21:07:00 MQT: stat/Athom1/STATUS5 = {"StatusNET":{"Hostname":"Athom1-0158","IPAddress":"192.168.1.107","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"10:52:1C:DA:60:9E","Webserver":2,"WifiConfig":2,"WifiPower":17.0}}
21:07:00 MQT: stat/Athom1/STATUS6 = {"StatusMQT":{"MqttHost":"mrshark.ddns.net","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_DA609E","MqttUser":"admin","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
21:07:00 MQT: stat/Athom1/STATUS7 = {"StatusTIM":{"UTC":"2020-11-02T20:07:00","Local":"2020-11-02T21:07:00","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"07:39","Sunset":"17:27"}}
21:07:00 MQT: stat/Athom1/STATUS9 = {"StatusPTH":{"PowerDelta":[0,0,0],"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
21:07:00 MQT: stat/Athom1/STATUS10 = {"StatusSNS":{"Time":"2020-11-02T21:07:00","ENERGY":{"TotalStartTime":"2020-10-17T18:33:07","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
21:07:00 MQT: stat/Athom1/STATUS11 = {"StatusSTS":{"Time":"2020-11-02T21:07:00","Uptime":"0T00:05:03","UptimeSec":303,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":22,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SharkIOT","BSSId":"20:28:18:A0:F0:42","Channel":11,"RSSI":84,"Signal":-58,"LinkCount":1,"Downtime":"0T00:00:07"}}}

```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:
21:07:31 SRC: WebConsole from 192.168.1.121
21:07:31 CMD: Group 0, Index 1, Command "WEBLOG", Data "4"
21:07:31 MQT: stat/Athom1/RESULT = {"WebLog":4}
21:07:32 UDP: Packet (94)
21:07:32 UDP: Packet (101)
21:07:33 APP: Button1 multi-press 1
21:07:35 UPP: WeMo Type 2, Response sent to 192.168.1.109:47348
21:07:35 APP: Button1 multi-press 1
21:07:37 APP: Button1 multi-press 1

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

pushing the button does not trigger the relay, but just shows "Button1 multi-press 1" in console with weblog 4

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

a relay toggling

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by effelle**
## Description:
Adds `SetOption114` (default to `0`) to decouple the switches from the POWER devices similar to what I did with `SetOption73` for the buttons.
All the switchmodes are supported.
@arendst is a bit different from `PUSH_IGNORE` (SwitchMode15) because with this PR all the payloads are mapped. 
I left it there, up to you to remove it or not, but I think is not necessary anymore.
A few examples:
```py
00:52:17 CMD: switchmode 0
00:52:17 MQT: tasmota_49A3BC/stat/RESULT = {"SwitchMode1":0}
00:52:20 MQT: tasmota_49A3BC/stat/SWITCH1 = {"ACTION":"TOGGLE"}

00:52:26 CMD: switchmode 1
00:52:26 MQT: tasmota_49A3BC/stat/RESULT = {"SwitchMode1":1}
00:52:28 MQT: tasmota_49A3BC/stat/SWITCH1 = {"ACTION":"OFF"}
00:52:31 MQT: tasmota_49A3BC/stat/SWITCH1 = {"ACTION":"ON"}

00:52:41 CMD: switchmode 5
00:52:41 MQT: tasmota_49A3BC/stat/RESULT = {"SwitchMode1":5}
00:52:45 MQT: tasmota_49A3BC/stat/SWITCH1 = {"ACTION":"HOLD"}

00:52:56 CMD: switchmode 11
00:52:56 MQT: tasmota_49A3BC/stat/RESULT = {"SwitchMode1":11}
00:52:58 MQT: tasmota_49A3BC/stat/SWITCH1 = {"ACTION":"POWER_RELEASE"}
00:52:59 MQT: tasmota_49A3BC/stat/SWITCH1 = {"ACTION":"POWER_CLEAR"}
00:53:03 MQT: tasmota_49A3BC/stat/SWITCH1 = {"ACTION":"POWER_INCREMENT"}
```

Also fixes a regression introduced on #9589 that was blocking the communication between switches/buttons and relays. 
@emontnemery fixed `HAssAnyKey` on #9700 , regression generated by the same PR, but after a bisect we realized there was another problem too: the relays were not responding after a button/switch press.
 
**Related issue (if applicable):** fixes #9719 and #9715

## Checklist:
  - [X] The pull request is done against the latest dev branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR.
  - [X] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.5
  - [X] The code change is tested and works on core ESP32 V.1.12.2
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by meingraham** [comment]
You can't use SO73 for either decoupling buttons or switches? Why is a separate SO needed for or or the other?

**Comment by effelle** [comment]
I think is better have them separated but yes, eventually so73 can manage both.

**Comment by Jason2866** [comment]
m2c Remove Switchmode 15 (it is introduced not long ago). 
Since Button decoupling is a SO it is more logic to use a SO for Switch decoupling too.
I prefer 2 SO for button and switches decoupling. Doing this you can easily mix couple and decoupling

**Comment by arendst** [comment]
Thx for the regression solve too. Looks like we are working in follow the sun mode!

**Comment by arendst** [comment]
Woldn't it be better to return a JSON message with the switch name in it? This way rules can pick it up. 

Like:
```
11:53:39 CFG: Saved to flash at FA, Count 423, Bytes 4096
11:53:42 MQT: stat/wemos4/SWITCH1 = {"Switch1":"ON"}
11:53:44 MQT: stat/wemos4/SWITCH1 = {"Switch1":"OFF"}
```

**Comment by effelle** [comment]
Yesterday night when me and Erik were working under HaTasmota we realized PR #9691 was merged and switches have names now. That's why the new switch topic uses the same format of button one. 
I'll change it adding the new names , but I think should be 
```py
stat/wemos4/SWITCH1 = {"Name":"SwitchName","Action":"POWER_INCREMENT"}
``` 
I use switches with rules a lot for decoupling, I think is just a natural evolution following the route opened by the new buttons. 
We will also benefit of So114 under Home Assistant to manage them remotely without user interaction in console.
Should I remove Switchmode15?
@pcdiem Paul since we reverted a couple of things in your PR would you gently check if `PWM Dimmer` works as expected after this last merge? Thanks.

**Comment by arendst** [comment]
Pls leave switchmode 15 for now.

How do you rule trigger on a json message like you propose?

**Comment by emontnemery** [comment]
@arendst in your example you say this would be a better format:
```
11:53:42 MQT: stat/wemos4/SWITCH1 = {"Switch1":{"Action":"POWER_INCREMENT"}}
```
In that case, is the index needed on the topic, or can it be simplified to:
```
11:53:42 MQT: stat/wemos4/SWITCH = {"Switch1":{"Action":"POWER_INCREMENT"}}
```

**Comment by arendst** [comment]
It can be simplified but may have an index too. I prefer the index.

You can also use function ``MqttPublishPrefixTopicRulesProcess_P()`` to publish the json and trigger a rule test too.

**Comment by arendst** [comment]
OK. forget the switch index and try to represent this:
```
00:00:16 MQT: tele/wemos4/SWITCH = {"Switch1":{"Action":"ON"}}
00:00:21 MQT: tele/wemos4/SWITCH = {"Switch1":{"Action":"OFF"}}
```

I think the below code will do just fine:
```
void MqttSwitchTopic(uint32_t switch_id, uint32_t MqttAction) {
  if (!Settings.flag.hass_discovery) {  // SetOption19 - Control Home Assistantautomatic discovery (See SetOption59)
    char mqttstate_str[16];
    char *mqttstate = mqttstate_str;
    if (MqttAction <= 3) {
      if (MqttAction != 3) { SendKey(KEY_SWITCH, switch_id, MqttAction); }
      mqttstate = SettingsText(SET_STATE_TXT1 + MqttAction);
    } else {
      GetTextIndexed(mqttstate_str, sizeof(mqttstate_str), MqttAction, kSwitchPressStates);
    }
    Response_P(PSTR("{\"%s\":{\"Action\":\"%s\"}}"), GetSwitchText(switch_id -1).c_str(), mqttstate);
    MqttPublishPrefixTopicRulesProcess_P(RESULT_OR_TELE, PSTR(D_JSON_SWITCH));
  }
}
```

**Comment by effelle** [comment]
OK then. Incoming.

**Comment by arendst** [comment]
Correct and if SO4 is 1 it will be 
```
14:03:11 MQT: tasmota_49A3BC/tele/SWITCH = {"Switch3":{"Action":"OFF"}}
```

BTW I tried to contact you in Discord but I receive this:

> Clyde
> BOT
> Today at 2:04 PM
> Your message could not be delivered because you don't share a server with the recipient or you disabled direct messages on your shared server, recipient is only accepting direct messages from friends, or you were blocked by the recipient.
>

**Comment by arendst** [comment]
Bugger it might have been stat/RESULT too.

I think stat/RESULT is better.

Problem is I lost my internal decisions when to use tele and when to use stat. I think stat is better so let's use:

```
 MqttPublishPrefixTopicRulesProcess_P(RESULT_OR_STAT, PSTR(D_JSON_SWITCH));
```

**Comment by effelle** [comment]
I'm not on Tasmota discord anymore.

**Comment by arendst** [comment]
Shall I make the changes permant by pushing this solution?

**Pull request merged**
