### PR TITLE
make IRHVAC send incremental changes.

### PR DESCRIPTION
**Pull request by TMaYaD**
## Description:

This change will allow mqtt messages simpler by allowing something like `publish cmnd/ir-bridge/IRHVAC {"Power": "On", "Incremental": true}`.
The simpler format is required for working with mqtt clients like iotMQTTPanel or similar on android.

Limitations:
- Requires full message be sent at-least once. I work around this with a `system#boot` rule
- Gets messy with multiple devices. I have only one AC per room, and this doesn't doesn't interfere with other IR devices.

TODO:
- [ ] Persist `irac_prev_state` across reboots.
- [ ] Support multiple devices.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by TMaYaD** [comment]
I do not have an ESP32 IR Blaster to test.

**Comment by s-hadinger** [comment]
Thanks. I would rather have this in the standard build rather than a compile option. Can we think of a distinct command syntax for incremental? For ex adding a json field like "incremental":true?

**Comment by TMaYaD** [comment]
My original idea was to leverage `Mem<x>` (or similar) as stores. 

`{..., "Storage": "Mem1"}` would store and/or retrieve from `Mem1`. This will allow incremental operations for multiple devices, if desired.

However, I have a lot of learning to do before I understand the code base enough to do that.

**Comment by s-hadinger** [comment]
Relying on Mem1 sounds overly complicated to me. Why not go back to your original idea, but as a runtime option, not a compile-time option?

**Comment by Jason2866** [comment]
@TMaYaD  Will you do the changes?

**Comment by TMaYaD** [comment]
Yes. I'm away on vacation right now. Will get back to it after 14th.

**Comment by TMaYaD** [comment]
@Jason2866 Updated and tested on my IR blaster. It turned out to be simpler than I expected.

**Comment by s-hadinger** [comment]
bump

**Comment by pkkrusty** [comment]
Nice improvement. Looking forward to testing this. Will make node-red flows simpler too.

**Pull request merged**
