### PR TITLE
Use new syntax for providing ldscript

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core feature stage
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Should this change not be implemented foor all current environments?

**Comment by Jason2866** [comment]
It is implemented since Arduino commit https://github.com/esp8266/Arduino/commit/5efdc7762aed5b759fdf347952420d8cb211a55a

It is not supported earlier

**Comment by arendst** [comment]
Isn't it platformio version dependant?

**Comment by Jason2866** [comment]
No, the platformio-build.py (arduino file) does generate the support for.

**Comment by arendst** [comment]
And in a test it just blowed my memory model leaving me with only 248k RAM. NOT GOOD.

```
14:43:02 CMD: upload 1
14:43:02 SRC: Serial
14:43:02 CMD: Group 0, Index 1, Command "UPLOAD", Data "1"
14:43:02 MQT: stat/wemos6/RESULT = {"Upload":"Version 8.1.0.8 from http://domus1:80/api/arduino/tasmota.bin.gz"}
14:43:02 CFG: Saved to flash at FB, Count 1617, Bytes 4096
14:43:04 HTP: Web server stopped
14:43:04 UPL: http://domus1:80/api/arduino/tasmota.bin.gz
14:43:04 HTP: Web server active on wemos6 with IP address 192.168.2.153
14:43:06 HTP: Web server stopped
14:43:06 UPL: http://domus1:80/api/arduino/tasmota-minimal.bin.gz
14:43:06 HTP: Web server active on wemos6 with IP address 192.168.2.153
14:43:08 HTP: Web server stopped
14:43:08 UPL: http://domus1:80/api/arduino/tasmota-minimal.bin.gz
14:43:08 HTP: Web server active on wemos6 with IP address 192.168.2.153
14:43:10 HTP: Web server stopped
14:43:10 UPL: http://domus1:80/api/arduino/tasmota-minimal.bin.gz
14:43:10 HTP: Web server active on wemos6 with IP address 192.168.2.153
14:43:12 HTP: Web server stopped
14:43:12 HTP: Web server active on wemos6 with IP address 192.168.2.153
14:43:14 MQT: stat/wemos6/UPGRADE = {"Upgrade":"Failed Not Enough space"}
14:46:50 CMD: status 0
14:46:50 SRC: Serial
14:46:50 CMD: Group 0, Index 1, Command "STATUS", Data "0"
14:46:50 MQT: stat/wemos6/STATUS = {"Status":{"Module":18,"FriendlyName":["Wemos6"],"Topic":"wemos6","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
14:46:50 MQT: stat/wemos6/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"displays","OtaUrl":"http://domus1:80/api/arduino/tasmota.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:18:17","StartupUTC":"2020-02-19T13:28:33","Sleep":0,"CfgHolder":4617,"BootCount":390,"BCResetTime":"2020-02-08T12:46:21","SaveCount":1617,"SaveAddress":"FB000"}}
14:46:50 MQT: stat/wemos6/STATUS2 = {"StatusFWR":{"Version":"8.1.0.8(tasmota)","BuildDateTime":"2020-02-19T14:27:34","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"325/699"}}
14:46:50 MQT: stat/wemos6/STATUS3 = {"StatusLOG":{"SerialLog":3,"WebLog":2,"MqttLog":0,"SysLog":2,"LogHost":"domus1","LogPort":514,"SSId":["indebuurt","indebuurt2"],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00020009","2805C8000100060000005A00000000170700","001000C1","00000000"]}}
14:46:50 MQT: stat/wemos6/STATUS4 = {"StatusMEM":{"ProgramSize":498,"Free":248,"Heap":29,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640C8","FlashMode":3,"Features":["00000809","0F1AA186","042403A1","04001ECC","01000BC0","00006081","00000000"],"Drivers":"1,2,3,4,5,6,7,9,10,22,24","Sensors":"2,3,5,6,8,9,10,34"}}
14:46:50 MQT: stat/wemos6/STATUS5 = {"StatusNET":{"Hostname":"wemos6","IPAddress":"192.168.2.153","Gateway":"192.168.2.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.27","Mac":"EC:FA:BC:08:01:9B","Webserver":2,"WifiConfig":5,"WifiPower":17.0}}
14:46:50 MQT: stat/wemos6/STATUS6 = {"StatusMQT":{"MqttHost":"domus1","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_08019B","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30}}
14:46:50 MQT: stat/wemos6/STATUS7 = {"StatusTIM":{"UTC":"2020-02-19T14:46:50","Local":"2020-03-29T02:00:00","StartDST":"2020-10-25T03:00:00","EndDST":"2020-02-19T14:46:50","Timezone":99,"Sunrise":"07:52","Sunset":"18:16"}}
14:46:50 MQT: stat/wemos6/STATUS10 = {"StatusSNS":{"Time":"2020-02-19T14:46:50","DS18B20":{"Id":"0000048EC44C","Temperature":24.4},"TempUnit":"C"}}
14:46:50 MQT: stat/wemos6/STATUS11 = {"StatusSTS":{"Time":"2020-02-19T14:46:50","Uptime":"0T00:18:17","UptimeSec":1097,"Heap":29,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":771,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"indebuurt","BSSId":"18:E8:29:CA:17:C1","Channel":11,"RSSI":100,"Signal":-32,"LinkCount":1,"Downtime":"0T00:00:07"}}}

**Comment by Jason2866** [comment]
Try for Tasmota stage core
`platform_packages         = framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git#5efdc7762aed5b759fdf347952420d8cb211a55a `

Some commits later the Arduino guys seems to screw up something

**Comment by arendst** [comment]
Ah my fault I think. I patched the [tasmota_core_stage] version and you just said the fix is only in the latest stage.

So in my case it used the default linker which apparently adds a SPIFFS area of over 200k.

**Pull request merged**
