### PR TITLE
Add support for LM75AD I2C Temperature Sensor

### PR DESCRIPTION
**Pull request by andrethomas**
Add support for LM75AD I2C Temperature Sensor

### CODE REVIEW

**Comment by arendst** [comment]
Will be implemented but...

Needs Celsius/Fahrenheit as others do. Simple call but not in the current PR. See other temperature drivers for implementations.

**Comment by andrethomas** [comment]
Damn, can't believe I forgot about the Fahrenheit conversion :|

**Comment by andrethomas** [comment]
Tested update... let me know :)

**Comment by andrethomas** [comment]
Added to Wiki https://github.com/arendst/Sonoff-Tasmota/wiki/LM75AD

**Pull request merged**
