### PR TITLE
Add support for I2C MCP23008/MCP23017 for GP INPUT

### PR DESCRIPTION
**Pull request by andrethomas**
Add support for I2C MCP23008/MCP23017 for GP INPUT

Previous PR #3107  has reference to this.

Cleaned up the commit and modified the way in which MCP23008 vs MCP23017 is detected.

Wiki posted here https://github.com/arendst/Sonoff-Tasmota/wiki/MCP23008-MCP23017

### CODE REVIEW

**Comment by andrethomas** [comment]
@arenst I would like to make the webconfig option "optional" with as follows

```
#define USE_MCP230xx
#define USE_MCP230xx_webconfig
```

This will provide the option to include or exclude the web configuration option during compilation and would obviously have to be disabled by default for code space reasons (yes, web config side takes up about 2k2 of the overall 4k of the driver...

If I make this optional I would have to make available the sensor29 option and I see you do this in one of the other drivers but I cannot find an example of your best practice method to implement two parameters as I need two parameters per pin for example

`sensor29 pin pinmode`

could be like

`sensor29 0 1`

i.e. set D0 to INPUT mode

Any recommendation on the implementation of this?

**Comment by andrethomas** [comment]
I also need to work into this a way of setting pull-up resistor, so perhaps 3 parameters

so 
sensor29 pin pinmode pullup

`sensor29 0 1 1`
would enable pull-up on pin D0 while
`sensor29 0 1 0`
would disable pull-up on pin D0

**Comment by andrethomas** [comment]
Something like

```
bool MCP230xx_Command(void) {
  boolean serviced = true;
  uint8_t _a,_b = 0;
  uint8_t pin,pinmode,pullup = 0;
  String data = XdrvMailbox.data;
  _a=data.indexOf(" ");
  _b=data.indexOf(" ",_a+1);
  if (_a < XdrvMailbox.data_len) {
    if (_b < XdrvMailbox.data_len) {
      pin=data.substring(0,_a).toInt();
      pinmode=data.substring(_a,_b).toInt();
      pullup=data.substring(_b,XdrvMailbox.data_len).toInt();
      data="MCP D" + String(pin) + " mode=" + String(pinmode) + " pullup=" + String(pullup);

      // do all the fancy stuff to calculate which bits go where in mcp_config[]
      
      snprintf_P(mqtt_data, sizeof(mqtt_data), S_JSON_SENSOR_INDEX_SVALUE, XSNS_29, data.c_str());
    } else {
      serviced=false;
    }
  } else {
    serviced=false;
  }
  return serviced;
}

```

```
20:33:40 CMD: sensor29 0 1 1
20:33:40 MQT: stat/sonoff/RESULT = {"Sensor29":"MCP D0 mode=1 pullup=1"}
20:33:53 CMD: sensor29 1 2 1
20:33:53 MQT: stat/sonoff/RESULT = {"Sensor29":"MCP D1 mode=2 pullup=1"}

```
?

**Comment by arendst** [comment]
Fine. I prefer commas instead  of spaces inline with other commands.

**Comment by andrethomas** [comment]
> Fine. I prefer commas instead of spaces inline with other commands.

Will do :)

**Comment by andrethomas** [comment]
Works now with

`sensor29 pin,pinmode,pullup`

For example, to set D0 to INPUT and PULL-UP:
`sensor29 0,1,1`

pinmode:
0 = Disabled
1 = Input
2 = Interrupt on Change
3 = Interrupt on LOW
4 = Interrupt on HIGH

Pull-up can be enabled in any of the modes, except disabled.

```
#define USE_MCP230xx             // Add 2260 bytes
#define USE_MCP230xx_webconfig   // Add 2444 bytes
#define USE_MCP230xx_displaymain // Add 188 bytes
```

USE_MCP230xx_displaymain can be set if the user requires the outputs displayed on the Tasmota module's main page like this:

image

If not included in compile, the pin status will not be displayed there.

**Comment by andrethomas** [comment]
@arendst I'm done!

**Comment by andrethomas** [comment]
@renne 

It should open web server on http://xxx.xxx.xxx.xxx/mcp230xx which is defined inhttps://github.com/andrethomas/Sonoff-Tasmota/blob/development/sonoff/xdrv_02_webserver.ino on line 387 through 394 which should call handleMCP230xx() from https://github.com/andrethomas/Sonoff-Tasmota/blob/development/sonoff/xsns_29_mcp230xx.ino on line 85

Can you add some Serial.println in there and see if it reaches the function? 

Obviously, it works on my end but that doesn't mean that it must on your end...

At that point, there is actually no interaction with the chip itself yet.. just reading config from already loaded variables

Let me know what happens

Also, just to confirm did you grab the files from the fork or from the commits in this?

**Comment by andrethomas** [comment]
> Also, just to confirm did you grab the files from the fork or from the commits in this?

The reason I ask this is that I temporarily had a debug branch as default earlier this evening so a pull from there would have resulted in debug codebase instead of development which is what is in this commit and is also now the default branch again :)

**Comment by renne** [comment]
I did a `git clone https://github.com/andrethomas/Sonoff-Tasmota.git` and edited `user_config.h`. To make sure it's your development branch I just did a `git clone https://github.com/andrethomas/Sonoff-Tasmota.git` again. The browser still doesn't react and serial logging shows:
```
22:27:49 MQT: tele/sonoff/SENSOR = {"Time":"2018-07-13T22:27:49","MCP23017":{"D0":0,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":0,"D8":0,"D9":0,"D10":0,"D11":0,"D12":0,"D13":0,"D14":0,"D15":0}}
22:27:54 HTP: Configure MCP230xx

Exception (3):
epc1=0x40231180 epc2=0x00000000 epc3=0x00000000 excvaddr=0x402717ee depc=0x00000000

ctx: cont 
sp: 3fff5240 end: 3fff55a0 offset: 01a0

>>>stack>>>
3fff53e0:  402717f8 00000003 3fff542c 4022eaa9  
3fff53f0:  00000001 3fff2a44 3fff542c 4022eaf6  
3fff5400:  402717ee 3fff2a44 00000000 4022ed38  
3fff5410:  00000001 00000001 00000000 4020fc6d  
3fff5420:  3fff7d74 0000000f 00000003 3fff812c  
3fff5430:  0000000f 00000009 00000000 00000000  
3fff5440:  00000000 3fff8334 000009bf 000009b0  
3fff5450:  3fff447c 00000001 3fff63a4 40220eed  
3fff5460:  00000001 00000001 3fff5490 4022fb0e  
3fff5470:  40000f83 00000030 3fff63a4 40225972  
3fff5480:  3fff63a4 3fff75a0 3fff63a4 402259ae  
3fff5490:  00000000 00000000 00000000 4022ebd4  
3fff54a0:  3fff63a4 3fff75a0 3fff755c 40225a35  
3fff54b0:  3fff713c 0000000f 00000009 00000000  
3fff54c0:  00000000 3fffc6fc 3fff7560 402234e0  
3fff54d0:  3fff75a0 00000001 3fff7560 40223c50  
3fff54e0:  00000001 00000000 402243e8 00000019  
3fff54f0:  00000000 3fff7d1c 3fff755c 3fff4578  
3fff5500:  00000001 3fff7584 3fff755c 40225c84  
3fff5510:  40107480 00000000 00001388 4020b26d  
3fff5520:  00000000 3fff7d1c 3fff4571 4021e38a  
3fff5530:  00000002 0000002c 00000004 40205146  
3fff5540:  00000002 0000002c 00000000 40221a9e  
3fff5550:  3fffdad0 3fff4578 4022f6ac 40218183  
3fff5560:  feefeffe 0000002c 00000000 402092e9  
3fff5570:  3fffdad0 00000000 3fff4571 4021e773  
3fff5580:  3fffdad0 00000000 3fff4571 4022f6f8  
3fff5590:  feefeffe feefeffe 3fff4580 40100710  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld
```
Could be a pointer issue. Tomorrow I'll add some `Serial.println` to see where it fails.

**Comment by andrethomas** [comment]
Could be - which development environment are you using?

Can you give a status 0 output?

**Comment by andrethomas** [comment]
@renne 

May have been this unwanted %s

image

Try again ?

Thanks!

**Comment by renne** [comment]
The IDE is Arduino IDE V1.8.5 (Manjaro/Arch package).

You reverted the `%s`. Does it mean it should be there?

`status 0` output:
```
08:46:39 CMD: status 0
08:46:39 SRC: WebConsole from 192.168.100.30
08:46:39 RSL: Received Topic /status, Data Size 1, Data 0
08:46:39 RSL: Group 0, Index 1, Command STATUS, Data 0
08:46:39 MQT: stat/sonoff/STATUS = {"Status":{"Module":18,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
08:46:39 MQT: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"External System","Uptime":"0T00:03:52","StartupUTC":"2018-07-14T07:42:47","Sleep":0,"BootCount":8,"SaveCount":12,"SaveAddress":"F8000"}}
08:46:39 MQT: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.1.0a","BuildDateTime":"2018-07-13T23:19:22","Boot":31,"Core":"2_4_1","SDK":"2.2.1(cfd48f3)"}}
08:46:39 MQT: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":4,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["BartschNet",""],"TelePeriod":10,"SetOption":["00008009","55818000"]}}
08:46:39 MQT: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":550,"Free":452,"Heap":12,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000809","0FDAC794","00000000","37B6179E","00000000"]}}
08:46:39 MQT: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-6300","IPAddress":"192.168.100.42","Gateway":"192.168.100.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.100.1","Mac":"B4:E6:2D:0B:F8:9C","Webserver":2,"WifiConfig":3}}
08:46:39 MQT: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.100.3","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0BF89C","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
08:46:39 MQT: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Sat Jul 14 07:46:39 2018","Local":"Sat Jul 14 08:46:39 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:02","Sunset":"20:50"}}
08:46:39 MQT: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-07-14T08:46:39","MCP23017":{"D0":0,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":1,"D8":1,"D9":0,"D10":0,"D11":0,"D12":0,"D13":0,"D14":0,"D15":0}}}
08:46:39 MQT: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-07-14T08:46:39","Uptime":"0T00:03:52","Vcc":3.013,"Wifi":{"AP":1,"SSId":"<removed>","RSSI":100,"APMac":"<removed>"}}}
08:46:43 MQT: tele/sonoff/STATE = {"Time":"2018-07-14T08:46:43","Uptime":"0T00:03:56","Vcc":3.013,"Wifi":{"AP":1,"SSId":"<removed>","RSSI":100,"APMac":"<removed>"}}
08:46:43 MQT: tele/sonoff/SENSOR = {"Time":"2018-07-14T08:46:43","MCP23017":{"D0":0,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":0,"D8":0,"D9":0,"D10":0,"D11":0,"D12":0,"D13":0,"D14":0,"D15":0}}
```

**Comment by renne** [comment]
If the `page.replace()` calls in line 123 - 139 of `xsns_29_mcp230xx.ino` are commented out the ESP8266 does not crash and the web-configuration page is shown.

**Comment by andrethomas** [comment]
@renne 

> You reverted the %s. Does it mean it should be there?

Yup, it builds the list of <td>'s so it should be there

> f the page.replace() calls in line 123 - 139 of xsns_29_mcp230xx.ino are commented out the ESP8266 does not crash and the web-configuration page is shown.

Looks like your compiler/linker doesn't like the F()'s I used.. removed them. Do a pull and try again?

Thanks, much appreciated!

**Comment by andrethomas** [comment]
@renne 

Changed them to this:
```
    switch (bitsetting) {
      case 0 : page.replace("{s0", FPSTR(MCP230XX_OPTION_SELECTED)); break;
      case 1 : page.replace("{s1", FPSTR(MCP230XX_OPTION_SELECTED)); break;
      case 2 : page.replace("{s2", FPSTR(MCP230XX_OPTION_SELECTED)); break;
      case 3 : page.replace("{s3", FPSTR(MCP230XX_OPTION_SELECTED)); break;
      case 4 : page.replace("{s4", FPSTR(MCP230XX_OPTION_SELECTED)); break;
    }

```

**Comment by renne** [comment]
@andrethomas @arendst @ascillato2 @Jason2866 

Tests with MCP23017 PDIP:
- [x] MCP23017 detected
- [x] MCP23017 GPIOs listed on Tasmota main web page
- [x] Sensor29 command working
- [x] GPIOs working
- [x] Web-interface configuration

**Comment by andrethomas** [comment]
@renne Awesome! Thank you so much for testing :)

Another thing thats awesome is the changes made decreased the code space required

```
#define USE_MCP230xx               // +2200 bytes
#define USE_MCP230xx_displaymain   //  +156 bytes
#define USE_MCP230xx_webconfig     // +2260 bytes

```
Shimmed off another 5.6% (276 bytes of flash) !

**Comment by andrethomas** [comment]
Wiki at https://github.com/arendst/Sonoff-Tasmota/wiki/MCP23008-MCP23017 updated to include information in the usage of the 3 defines and how to use the sensor27 command

**Comment by renne** [comment]
@andrethomas 
Please add your knowledge about sensor implementation in Tasmota to the [Sensor API wiki page](https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-API). :-)

**Comment by andrethomas** [comment]
@arendst @ascillato2 @Jason2866 @renne All done, I think... unless you want me to add output support using `sensor29 pin,ON` & `sensor29 pin,OFF` commands (+580 bytes) and (+132 bytes flash if output is configurable using web interface)

**Comment by Jason2866** [comment]
@andrethomas 
My hardware is still on the way from china 🙁

**Comment by renne** [comment]
@Jason2866 
You can get a MCP23017 for ~ 1,50 € at [Conrad](https://www.conrad.com/ce/Search.html?search=mcp23017&searchType=mainSearchBar).

@andrethomas 
If you already have working output code it should be integrated! :+1:

**Comment by andrethomas** [comment]
@renne Output not integrated into commit - you may test on the output branch if you wish... not sure if arendst wants output functionality in the main development branch... I was actually just toying with it... do not have an immediate use for it.

Find it here https://github.com/andrethomas/Sonoff-Tasmota/tree/mcp230xx_output

**Comment by andrethomas** [comment]
@renne Its just the xsns_29_mcp230xx.ino file that changes so you could just copy that single file if you like.

**Comment by renne** [comment]
@andrethomas 

I copied `xsns_29_mcp230xx.ino` of output branch into Tasmota 6.1.1c
```
18:15:43 MQT: tele/sonoff/INFO3 = {"RestartReason":"Fatal exception:3 flag:2 (EXCEPTION) epc1:0x402325ec epc2:0x00000000 epc3:0x00000000 excvaddr:0x40266773 depc:0x00000000"}
```
I also removed the `F()` in line 147. It still segfaults. Where should I start debugging?

**Comment by andrethomas** [comment]
Line 147
`page.replace(F("{b2"), PSTR(""));`
to
`page.replace("{b2", FPSTR(MCP230XX_OPTION_BLANK));`
Should do the trick

**Comment by renne** [comment]
GPA0-7 work in output mode, GPB0-7 do not work. Where should I start debugging?

Is it possible to set output mode for a pin via SENSOR29 command?

**Comment by andrethomas** [comment]
@renne 
sensor29 pin,pinmode,pullup

So for outputs this will be

sensor29 0-15,5,0 for output

Turn GPB0 on with sensor29 8,ON

Let me know

**Comment by andrethomas** [comment]
@renne I see 8-15 has problem with output - let me debug

**Comment by renne** [comment]
I can set output mode via web-interface successfully but not via MQTT command:
```
21:00:58 CMD: backlog sensor29 0,5,0; sensor29 1,5,0; sensor29 2,5,0; sensor29 3,5,0; sensor29 4,5,0; sensor29 5,5,0; sensor29 6,5,0; sensor29 7,5,0; sensor29 8,5,0; sensor29 9,5,0; sensor29 10,5,0; sensor29 11,5,0; sensor29 12,5,0; sensor29 13,5,0; sensor29 14,5,0; sensor29 0,ON; sensor29 1,ON; sensor29 2,ON; sensor29 3,ON; sensor29 4,ON; sensor29 5,ON; sensor29 6,ON; sensor29 7,ON; sensor29 8,ON; sensor29 9,ON; sensor29 10,ON; sensor29 11,ON; sensor29 12,ON; sensor29 13,ON; sensor29 14,ON; sensor29 15,ON;
21:00:58 SRC: WebConsole from 192.168.100.30
21:00:58 RSL: Received Topic /backlog, Data Size 490, Data sensor29 0,5,0; sensor29 1,5,0; sensor29 2,5,0; sensor29 3,5,0; sensor29 4,5,0; sensor29 5,5,0; sensor29 6,5,0; sensor29 7,5,0; sensor29 8,5,0; sensor29 9,5,0; sensor29 10,5,0; sensor29 11,5,0; sensor29 12,5,0; sensor29 13,5,0; sensor29 14,5,0; sensor29 0,ON; sensor29 1,ON; sensor29 2,ON; sensor29 3,ON; sensor29 4,ON; sensor29 5,ON; sensor29 6,ON; sensor29 7,ON; sensor29 8,ON; sensor29 9,ON; sensor29 10,ON; sensor29 11,ON; sensor29 12,ON; sensor29 13,ON; se
21:00:58 RSL: Group 0, Index 1, Command BACKLOG, Data sensor29 0,5,0; sensor29 1,5,0; sensor29 2,5,0; sensor29 3,5,0; sensor29 4,5,0; sensor29 5,5,0; sensor29 6,5,0; sensor29 7,5,0; sensor29 8,5,0; sensor29 9,5,0; sensor29 10,5,0; sensor29 11,5,0; sensor29 12,5,0; sensor29 13,5,0; sensor29 14,5,0; sensor29 0,ON; sensor29 1,ON; sensor29 2,ON; sensor29 3,ON; sensor29 4,ON; sensor29 5,ON; sensor29 6,ON; sensor29 7,ON; sensor29 8,ON; sensor29 9,ON; sensor29 10,ON; sensor29 11,ON; sensor29 12,ON; sensor29 13,ON; sensor2
21:00:58 SRC: Backlog
21:00:58 RSL: Received Topic /sensor29, Data Size 5, Data 0,5,0
21:00:58 RSL: Group 0, Index 29, Command SENSOR, Data 0,5,0
21:00:58 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":0,"MODE":5,"PULL-UP":0}}
21:00:59 SRC: Backlog
21:00:59 RSL: Received Topic /sensor29, Data Size 5, Data 1,5,0
21:00:59 RSL: Group 0, Index 29, Command SENSOR, Data 1,5,0
21:00:59 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":1,"MODE":5,"PULL-UP":0}}
21:00:59 SRC: Backlog
21:00:59 RSL: Received Topic /sensor29, Data Size 5, Data 2,5,0
21:00:59 RSL: Group 0, Index 29, Command SENSOR, Data 2,5,0
21:00:59 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":2,"MODE":5,"PULL-UP":0}}
21:00:59 SRC: Backlog
21:00:59 RSL: Received Topic /sensor29, Data Size 5, Data 3,5,0
21:00:59 RSL: Group 0, Index 29, Command SENSOR, Data 3,5,0
21:00:59 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":3,"MODE":5,"PULL-UP":0}}
21:00:59 SRC: Backlog
21:00:59 RSL: Received Topic /sensor29, Data Size 5, Data 4,5,0
21:00:59 RSL: Group 0, Index 29, Command SENSOR, Data 4,5,0
21:00:59 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":4,"MODE":5,"PULL-UP":0}}
21:00:59 SRC: Backlog
21:00:59 RSL: Received Topic /sensor29, Data Size 5, Data 5,5,0
21:00:59 RSL: Group 0, Index 29, Command SENSOR, Data 5,5,0
21:00:59 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":5,"MODE":5,"PULL-UP":0}}
21:01:00 SRC: Backlog
21:01:00 RSL: Received Topic /sensor29, Data Size 5, Data 6,5,0
21:01:00 RSL: Group 0, Index 29, Command SENSOR, Data 6,5,0
21:01:00 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":6,"MODE":5,"PULL-UP":0}}
21:01:00 SRC: Backlog
21:01:00 RSL: Received Topic /sensor29, Data Size 5, Data 7,5,0
21:01:00 RSL: Group 0, Index 29, Command SENSOR, Data 7,5,0
21:01:00 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":7,"MODE":5,"PULL-UP":0}}
21:01:00 SRC: Backlog
21:01:00 RSL: Received Topic /sensor29, Data Size 5, Data 8,5,0
21:01:00 RSL: Group 0, Index 29, Command SENSOR, Data 8,5,0
21:01:00 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":8,"MODE":5,"PULL-UP":0}}
21:01:00 SRC: Backlog
21:01:00 RSL: Received Topic /sensor29, Data Size 5, Data 9,5,0
21:01:00 RSL: Group 0, Index 29, Command SENSOR, Data 9,5,0
21:01:00 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":9,"MODE":5,"PULL-UP":0}}
21:01:00 SRC: Backlog
21:01:00 RSL: Received Topic /sensor29, Data Size 6, Data 10,5,0
21:01:00 RSL: Group 0, Index 29, Command SENSOR, Data 10,5,0
21:01:00 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":10,"MODE":5,"PULL-UP":0}}
21:01:01 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":14,"MODE":5,"PULL-UP":0}}
21:01:01 SRC: Backlog
21:01:01 RSL: Received Topic /sensor29, Data Size 4, Data 0,ON
21:01:01 RSL: Group 0, Index 29, Command SENSOR, Data 0,ON
21:01:01 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":0,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:02 SRC: Backlog
21:01:02 RSL: Received Topic /sensor29, Data Size 4, Data 1,ON
21:01:02 RSL: Group 0, Index 29, Command SENSOR, Data 1,ON
21:01:02 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":1,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:02 SRC: Backlog
21:01:02 RSL: Received Topic /sensor29, Data Size 4, Data 2,ON
21:01:02 RSL: Group 0, Index 29, Command SENSOR, Data 2,ON
21:01:02 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":2,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:02 SRC: Backlog
21:01:02 RSL: Received Topic /sensor29, Data Size 4, Data 3,ON
21:01:02 RSL: Group 0, Index 29, Command SENSOR, Data 3,ON
21:01:02 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":3,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:02 SRC: Backlog
21:01:02 RSL: Received Topic /sensor29, Data Size 4, Data 4,ON
21:01:02 RSL: Group 0, Index 29, Command SENSOR, Data 4,ON
21:01:02 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":4,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:02 SRC: Backlog
21:01:02 RSL: Received Topic /sensor29, Data Size 4, Data 5,ON
21:01:02 RSL: Group 0, Index 29, Command SENSOR, Data 5,ON
21:01:02 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":5,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:03 SRC: Backlog
21:01:03 RSL: Received Topic /sensor29, Data Size 4, Data 6,ON
21:01:03 RSL: Group 0, Index 29, Command SENSOR, Data 6,ON
21:01:03 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":6,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:03 SRC: Backlog
21:01:03 RSL: Received Topic /sensor29, Data Size 4, Data 7,ON
21:01:03 RSL: Group 0, Index 29, Command SENSOR, Data 7,ON
21:01:03 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":7,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:03 SRC: Backlog
21:01:03 RSL: Received Topic /sensor29, Data Size 4, Data 8,ON
21:01:03 RSL: Group 0, Index 29, Command SENSOR, Data 8,ON
21:01:03 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":8,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:03 SRC: Backlog
21:01:03 RSL: Received Topic /sensor29, Data Size 4, Data 9,ON
21:01:03 RSL: Group 0, Index 29, Command SENSOR, Data 9,ON
21:01:03 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":9,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:03 SRC: Backlog
21:01:03 RSL: Received Topic /sensor29, Data Size 5, Data 10,ON
21:01:03 RSL: Group 0, Index 29, Command SENSOR, Data 10,ON
21:01:03 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":10,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:04 SRC: Backlog
21:01:04 RSL: Received Topic /sensor29, Data Size 5, Data 11,ON
21:01:04 RSL: Group 0, Index 29, Command SENSOR, Data 11,ON
21:01:04 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":11,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:04 SRC: Backlog
21:01:04 RSL: Received Topic /sensor29, Data Size 5, Data 12,ON
21:01:04 RSL: Group 0, Index 29, Command SENSOR, Data 12,ON
21:01:04 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":12,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:04 SRC: Backlog
21:01:04 RSL: Received Topic /sensor29, Data Size 5, Data 13,ON
21:01:04 RSL: Group 0, Index 29, Command SENSOR, Data 13,ON
21:01:04 MQT: stat/sonoff/RESULT = {"Sensor29CMND":{"D":13,"CMND":"ON","RESULT":"ERROR - PIN IS INPUT"}}
21:01:07 MQT: tele/sonoff/STATE = {"Time":"2018-07-20T21:01:07","Uptime":"0T00:59:20","Vcc":3.002,"Wifi":{"AP":1,"SSId":"BartschNet","RSSI":100,"APMac":"34:81:C4:2A:17:F3"}}
21:01:07 MQT: tele/sonoff/SENSOR = {"Time":"2018-07-20T21:01:07","MCP23017":{"D0":0,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":0,"D8":0,"D9":0,"D10":0,"D11":0,"D12":0,"D13":0,"D14":0,"D15":0}}
```

The web-interface shows `Input (Int when High)`.

**Comment by andrethomas** [comment]
@renne Settings seem to be OK now but pin D8-15 still not going ON/OFF - Will debug and revert back to you.

**Comment by andrethomas** [comment]
@renne Should be fine now... bit shifting for portb was incorrectly shifting more than 8 bits

`portb &= ~(1 << pin); // wrong`
instead of
`portb &= ~(1 << pin-8); // correct`

Fixed for both ON and OFF in `MCP230xx_Command_SetGPIO()`

**Comment by renne** [comment]
Got a nice chaser light with 16 LEDs working! :+1: 
```
for ((i=0; i<160; i++)); do mosquitto_pub -t cmnd/sonoff/sensor29 -m $((i%16)),ON; sleep 0.1s; mosquitto_pub -t cmnd/sonoff/sensor29 -m $((i%16)),OFF; done
```

I suggest you add a `#define` to `user_config.h` for outputs and some `#ifdefs`, prep a pull request and I'll do a thorough test tomorrow. ;-)

**Comment by renne** [comment]
@andrethomas 
Maybe you can save a few bytes by converting repetitive strings to loops like:
```
"<option value='0'{s0>Disabled</option>"
"<option value='1'{s1>Input</option>"
"<option value='2'{s2>Input (Int on Change)</option>"
"<option value='3'{s3>Input (Int when Low)</option>"
"<option value='4'{s4>Input (Int when High)</option>"
"<option value='5'{s5>Output</option>"
```
to
```
for(uint8_t i=0; i<6; i++) {
    snprintf_P(mqtt_data, sizeof(mqtt_data), PSTR("<option value='%d'{s%d>%s</option>"), i, i, ArrayOfStrings[i]);
}
```

**Comment by andrethomas** [comment]
@renne That's all in progmem anyway and gets pushed to ram in page += FPSTR(HTTP_FORM_MCP230XX);

**Comment by renne** [comment]
@andrethomas 
I'm going to drive all shutter SSRs in the house via MCP23017. What is the current state of output support in Tasmota?

**Comment by andrethomas** [comment]
@renne 
Stable from testing so far...

It may be conditionally included using #define USE_MCP230xx_OUTPUT

I'll make a PR for it

**Comment by andrethomas** [comment]
@renne PR proposed https://github.com/arendst/Sonoff-Tasmota/pull/3436

**Comment by benzino77** [comment]
@andrethomas great, great,great job! Finally I could use Tasmota for my garden project (MCP INPUT to know the well level and MCP OUTPUT tocontrol relays for my 10 valves)

I thing there is a mistake in wiki page
There is:
```
sensor29 0,5,0  // Configure pin 0 as OUTPUT and default to OFF on reset/power-up
sensor29 0,5,1  // Configure pin 0 as OUTPUT and default to ON on reset/power-up
sensor29 0,6,0  // Configure pin 0 as INVERTED OUTPUT and default to OFF on reset/power-up
sensor29 0,6,1  // Configure pin 0 as INVERTED OUTPUT and default to ON on reset/power-up
```

from my observation it should be:
```
sensor29 0,5,0  // Configure pin 0 as OUTPUT and default to OFF on reset/power-up
sensor29 0,5,1  // Configure pin 0 as OUTPUT and default to ON on reset/power-up
sensor29 0,6,0  // Configure pin 0 as INVERTED OUTPUT and default to **ON** on reset/power-up
sensor29 0,6,1  // Configure pin 0 as INVERTED OUTPUT and default to **OFF** on reset/power-up
```
at least it behave like this

**Comment by andrethomas** [comment]
Also for your configuration you probably want setoption0 = 0, otherwise it will not use pull-up state on power-up/reset but will restore the last known state. This is also defined in the user_config.h as

`#define SAVE_STATE`

**Comment by benzino77** [comment]
Sure, setoption0 is set to off. I will be testing this for my needs. Now there is a possibility to control 16 relays (or more). I hope I will be able to control this:
img_20180822_203840
and read status of this:
img_20180516_183332

Anyway great job!

**Comment by andrethomas** [comment]
Only one MCP chip is supported, but you can have 8 as output and 8 as input (or any combination of input/output) - That board looks interesting... I know the relay board at the bottom because I use them also with MCP23008 (8 GPIO version) - Where did you get that board that plugs into it? The one with the ESP8266 and the MCP on it?

**Comment by benzino77** [comment]
That is my design of "hat" for 8 channel relay, or rather universal board with wemos and mcp23017 on it. There are also (at the top of the board) pinouts for the second 8 channel relay, but the second one has to be connected with the dupoint ribbon wires (or you can do a "sandwich" with the hat between two 8 channels relay):
img_20180822_210317

**Comment by andrethomas** [comment]
Looks really cool 👍

**Pull request merged**
