### PR TITLE
fix degree symbol

### PR DESCRIPTION
**Pull request by reloxx13**
&deg; did not get exchange in web interface

wemos

### CODE REVIEW

**Comment by arendst** [comment]
Strange. My browsers (Edge, Firefox and Chrome) all show

image

**Comment by drbeat** [comment]
this should be a bug in his browser and not on tasmota side
or even a bug on the 5.10 version of tasmota

should only happens if his browser messes up html parsing

**Comment by domdomegg** [comment]
@reloxx13 

What browser and version of that browser are you using? If you view source, what is the raw HTML as it might have been escaped weirdly - possibly specific to German translation?

**Comment by reloxx13** [comment]
just tested this again with the latest 6.1.1 without the pullrequest changes and the degree char is correct now.

grafik

**Pull request closed without merging**
