### PR TITLE
Tariff command variant to force tariff

### PR DESCRIPTION
**Pull request by barbudor**
## Description:

**Related issue (if applicable):** fixes #18080

There are cases where Tasmota tariff changes based on time is not optimal:
- If you have more than 1 off-peak period within the day (I have an off-peak in the day and another one at night)
- If you have an external signal from your provider's counter which tells you the current tariff (not necesseraly time based)
- if you want to change tariff based on home-produced vs network-provided
...

This PR introduce a variant of the `Tariff<x>` command to manually force the current Tariff
`Tariff<x> ON` force Tariff<x> as the current tariff independently of configured -or not configured- tariff times
`Tariff<x> OFF` disable forced mode and resume time-based switching if configured (or disable tariff if not configured)

To switch between a tariff and another, it is not required (nor recommended) to change to OFF. Directly issue the other `Tariff<y>` command.

`Tariff` command response JSON is extended with a "Forced" key
```
{"Tariff":{"Off-Peak":{"STD":"00:00","DST":"00:00"},"Standard":{"STD":"00:00","DST":"00:00"},"Weekend":"OFF","Forced":"1"}}
```

No change in the Energy JSON
Tested both on ESP32 and ESP8266 with EnergyDummy driver

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only relevant files were touched
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [X] The code change is tested and works with Tasmota core ESP32 V.2.0.7
  - [X] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by barbudor** [comment]
That was fast
Thanks @arendst

**Comment by arendst** [comment]
Can you do the change on xdrv_03_energy.ino too pls?

**Comment by barbudor** [comment]
Strange. I also did it on esp8266
PR didn't went correctly as it is not my latest code
I'll update tonight

**Comment by barbudor** [comment]
Definitely not my latest version as I moved the field from Energy to settings into bitfield
Sorry for that

**Pull request merged**
