### PR TITLE
Utilize SDS0X1 'Working Period' command

### PR DESCRIPTION
**Pull request by edelstahlratte**
It has the advantage of offloading the sleep/wake/read-cycle management to the SDS0X1 sensor.

The sensor will wake up every x minutes and take a reading by itself.
On request the sensor reports the last valid reading without waking up...

### CODE REVIEW

**Comment by FabianHM** [comment]
Helo,
thanks for the good Idea with 5 Minutes Sleep.
I would like to change the interval of default 5 minutes. Unfortunately, the comand "WORKING_PERIOD" does not work. (MQT: stat/sonoff/RESULT = {"Command":"Unknown"})
How can I change the interval without recompiling?
Thanks for help,
Greetings Fabian

**Comment by arendst** [comment]
Only by re-compiling. To what value would you like it to be set?

**Comment by edelstahlratte** [comment]
Like @arendst said: you have to compile again...

**Comment by FabianHM** [comment]
Okay, thanks for fast feedback.
I think for my needs it's about every 15 minutes. I'll try compiling it the next time.

**Comment by tobox** [comment]
Whats the current status of this? I have just compiled the development branch (Sonoff-Tasmota 6.3.0.17) and connected a SDS011, and the sensor seems to send readings continuously:
```

23:34:03 HTP: Main Menu
23:34:06 SER: Received AA C0 2D 00 57 00 1D 76 17 AB
23:34:09 SER: Received AA C0 2D 00 57 00 1D 76 17 AB
23:34:12 SER: Received AA C0 2D 00 57 00 1D 76 17 AB
23:34:15 SER: Received AA C0 2D 00 57 00 1D 76 17 AB
23:34:18 SER: Received AA C0 2D 00 57 00 1D 76 17 AB
23:34:21 SER: Received AA C0 2D 00 57 00 1D 76 17 AB
```

The values are plausible, but I am worried about the sensor lifetime. My other dust sensor (running luftdaten.info firmware) seems to be blinking only every few minutes, while it is blinking every few seconds with tasmota.

**Comment by tobox** [comment]
Well... Maybe it is working correctly, and the LED is just blinking for serial activity. The sensor seems to shut down properly, the fan is off most of the time. Maybe I was just to impatient after startup.

**Comment by ascillato** [comment]
> Whats the current status of this?

The status is that this feature is merged into Tasmota since 10 sep 2018 and working fine.

You can "tune" the working period from _my_user_config.h_ file in the line:

`#define WORKING_PERIOD       5                 // Working period of the SDS Sensor, Takes a reading every X Minutes`

**Pull request merged**
