### PR TITLE
Add command Sensor35 (Tx2x sensor)

### PR DESCRIPTION
**Pull request by curzon01**
## Description:
- Sensor Tx2X - set/get windspeed unit
0 = km/h (kilometer per hour)
1 = m/s (meter per second)
2 = kn (knot)
3 = mph (miles per hour)
4 = ft/s (foot per second)
5 = yd/h (yard per second)
for permanent storage compile own binary or use rules, e.g. `ON System#Boot DO Sensor35 1 ENDON`
- TX2x standardize units
- TX2x localized global names

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
My my my what an interesting sensor ;-)

To make you a little mad what if I set aside 3 bits in SysBitfield2 (Settings.flag2.speed_conversion) and add a command ``SpeedConversion`` to do what your Sensor35 command does?

Shall I do this?

**Comment by curzon01** [comment]
;-) yes I'm currently replacing my unreliable 433MHz 12 year old WS3000 windsensor (and I waited for a process this morning and killed myself with Tasmota :-) )

I didn't want to "waste" additional flash, so I'll be happy if you do "SpeedConversion"

**Comment by arendst** [comment]
OK. Hold on.

**Comment by curzon01** [comment]
suggestion: to stay general, what do you think of "SpeedUnit" instead "SpeedConversion"

**Comment by arendst** [comment]
Agree as command ``SpeedUnit``

**Comment by arendst** [comment]
I'll do the command part too. I'll provide the same functionality as temperature and pressure conversions.

So in the end all you must do is call a yet to be defined function which will return the correct text string (like hPa or mmHg)

**Comment by arendst** [comment]
Latest commit already contains these changes.

Can you please test if things do what you expect. The new command ``SpeedUnit`` accepts a number from 0 to 6 representing: ``0 = none, 1 = m/s, 2 = km/h, 3 = kn, 4 = mph, 5 = ft/s, 6 = yd/s``.

I had to add a 0 to make sure SpeedUnit would not be added to the light information.

This driver defaults to km/h.

Give it a go!

**Comment by curzon01** [comment]
Last commit [71d810a](https://github.com/arendst/Tasmota/commit/71d810aac451f6f88591dbc69b51f081efcc5181) works, great!

(sorry for the Merge above, I'm new on VCS since 5 weeks and I didn't realy understand what was wrong with me :-) ).

**Pull request closed without merging**
