### PR TITLE
Add command ``GpioRead``

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Add command `GpioRead` which is used to quickly debug digital inputs giving their current values. `digitalRead()` is called on all configured GPIO although the static value may not be of any sense for many protocols (I2C...).

Examples:
```
GpioRead

14:45:08.240 RSL: RESULT = {"GPIORead":{"GPIO32":0,"GPIO33":0}}
```
 
**Related issue (if applicable):** fixes #19810

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
This only works for configured gpios in templates. It shows no user configured gpios. Let me chk how to fix this.

**Comment by s-hadinger** [comment]
Ah Yes, I'm not familiar with that part

**Comment by sfromis** [comment]
If would make sense to also get a peek at pins not (yet) configured, like when hunting for where inputs are, maybe as an option. Including analog too of course :wink:

**Comment by s-hadinger** [comment]
I'm concerned about potential side effect of reading "forbidden" GPOIs. Also the output would be more or less unreadable. Just configure every gpio as INPUT 😉

**Pull request merged**
