### PR TITLE
Zigbee Koenkk firmware 20240710 for Sonoff Zigbee ZBPro

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Zigbee, latest firmware for CC2652P customized for the Sonoff ZBPro - especially the BSL pin is changed because it is non-standard compared to Launchpad CC2652P.

Berry code patched to accept this firmware.

It is untested yet, I can't find my device right now. Any feedback to confirm it's working is welcome.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.7
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.0.4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Joylancer** [comment]
Hab es mal ausprobiert.
Berry Updates (.be) und neue FW geladen.
es kommt folgende Fehlermeldung:

Welcome to the Berry Scripting console. Check the [documentation](https://tasmota.github.io/docs/Berry/).
import sonoff_zb_pro_flasher as cc
cc.load("SonoffZBPro_coord_20240710.hex")
cc.check()
FLH: Starting verification of HEX file
BRY: Exception> 'value_error' - size of payload is not a mutliple of 4: 0x02BAD8
stack traceback:
	<unknown source>: in function `parse`
	<unknown source>: in function `check`
	<unknown source>: in function `main`

**Comment by Joylancer** [comment]
kleiner Fehler meinerseits, nach Update der xxx.be hatte ein reboot  gefehlt, momentan flasht das Gerät gerade, gebe Feedback.

**Comment by Joylancer** [comment]
19:58:20.338 FLH: Starting verification of HEX file
19:58:39.820 FLH: Verification of HEX file OK
19:58:47.875 MQT: tele/TCPZBBridgePro/STATE = {"Time":"2024-09-05T19:58:47","Uptime":"0T00:01:04","UptimeSec":64,"Heap":148,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Berry":{"HeapUsed":9,"Objects":155},"Wifi":{"AP":1,"SSId":"kein_Internet_","BSSId":"B0:F2:08:A8:F3:D5","Channel":1,"Mode":"HT40","RSSI":100,"Signal":-33,"LinkCount":1,"Downtime":"0T00:00:08"}}
19:58:47.880 MQT: tele/TCPZBBridgePro/SENSOR = {"Time":"2024-09-05T19:58:47","ESP32":{"Temperature":33.9},"TempUnit":"C"}
19:58:56.703 FLH: cc2652_flasher rx=23 tx=19 rst=15 bsl=22
19:58:56.729 FLH: Flashing started (takes 5-8 minutes during which Tasmota is unresponsive)
20:06:42.176 BRY: Exception> 'value_error' - len must be a multiple of 4
20:06:42.177 stack traceback:
20:06:42.178 	<unknown source>: in function `flash`
20:06:42.179 	<unknown source>: in function `main`

**Comment by s-hadinger** [comment]
Can you please confirm that the new Zigbee firmware works fine? I couldn't test on my side 

@Joylancer

**Comment by Joylancer** [comment]
@s-hadinger 
i can´t test, flash fails with error, or can i ignore this message
after this message i re-flashed the 20221019 firmware, not testing

19:58:56.729 FLH: Flashing started (takes 5-8 minutes during which Tasmota is unresponsive)
20:06:42.176 BRY: Exception> 'value_error' - len must be a multiple of 4
20:06:42.177 stack traceback:
20:06:42.178 : in function flash
20:06:42.179 : in function main

**Comment by sfromis** [comment]
Looks like line 11186 of `SonoffZBPro_coord_20240710.hex` is not for a multiple of 4 bytes.
> `:0DBAD8000CFF0400014503011E483033003F`

**Comment by FoX2V** [comment]
> @s-hadinger i can´t test, flash fails with error, or can i ignore this message after this message i re-flashed the 20220219 firmware, not testing
> 
> 19:58:56.729 FLH: Flashing started (takes 5-8 minutes during which Tasmota is unresponsive) 20:06:42.176 BRY: Exception> 'value_error' - len must be a multiple of 4 20:06:42.177 stack traceback: 20:06:42.178 : in function flash 20:06:42.179 : in function main

have same error.

**Comment by thogitnet** [comment]
For a workaround you can remove all lines with `if (len % 4 != 0) raise "value_error", "len must be a multiple of 4" end` oe apply the follow patch.

for me it worked fine. note that there is no message and it can take a good 8 minutes until something visible happens again...

patch cc2652_flasher.be < cc2652_flasher.be_patch

File: cc2652_flasher.be_patch
```
--- cc2652_flasher.be	2024-09-06 09:51:40.939854966 +0200
+++ patch/cc2652_flasher.be	2024-09-06 12:12:40.614491705 +0200
@@ -248,7 +248,6 @@
   end
 
   def cmd_memory_read(addr, len)
-    if (len % 4 != 0) raise "value_error", "len must be a multiple of 4" end
     if len > 128      raise "value_error", "len is bigger than 128" end
     var b = bytes("2A")
     b.add(addr, -4)
@@ -273,7 +272,6 @@
   # end
 
   def cmd_download(addr, sz)
-    if (sz % 4 != 0) raise "value_error", "len must be a multiple of 4" end
     if sz > 128      raise "value_error", "len is bigger than 128" end
     var b = bytes("21")
     b.add(addr, -4)
@@ -285,7 +283,6 @@
 
   def cmd_send_data(data)
     var sz = size(data)
-    if (sz % 4 != 0) raise "value_error", "len must be a multiple of 4" end
     if sz > 128      raise "value_error", "len is bigger than 128" end
     var b = bytes("24")
     b += data
@@ -336,7 +333,6 @@
   # higher level
   def flash_write(addr, data)
     var sz = size(data)
-    if (sz % 4 != 0) raise "value_error", "len must be a multiple of 4" end
     if sz > 128      raise "value_error", "len is bigger than 128" end
 
     var ret
```

**Comment by s-hadinger** [comment]
Thanks I will do the patch accordingly

**Comment by s-hadinger** [comment]
It is fixed now

**Comment by timurlan75** [comment]
No work.
FLH: Starting verification of HEX file
BRY: Exception> 'index_error' - string index out of range
stack traceback:

<unknown source>: in function `parse`

<unknown source>: in function 'check`

<unknown source>: in function `main`

**Comment by s-hadinger** [comment]
This pr is closed. Please open a new discussion with details about what you tried

**Comment by timurlan75** [comment]
I'm a regular user. I wanted to update. I replaced all the files. Unfortunately, it doesn't work.

**Comment by s-hadinger** [comment]
I already told you to open a new thread with the details. You have provided no details.

**Comment by timurlan75** [comment]
https://github.com/arendst/Tasmota/discussions/22257

**Comment by mox1** [comment]
I can confirm that so far this firmware works. I have not rigorously checked my ~10 or so Zigbee devices, but Zigbee2mqtt is looking normal after flashing. 

There is a lot of steps , tips, tricks that I have pieced together in order to get this to work, in no particular order:

1. The filesystem does not have enough space to have two coordinator files. In the tasmota file manager,  I click the "edit" button on the old firmware and just delete all the data (creating a 0 byte file). I have not found an easy way to delete a file.
2. You need to Tasmota AutoConf back to the NON TCP version. This version is required for the flasher (pins are setup differently.) 
3. I never actually got a confirmation on the Berry scripting console. I let it site for ~20 minutes (0 errors), Then I went to the regular Tasmota console and saw a "FLASH OK" type message (not exact wording). 
4. From there I needed to reboot Tasmota and let it come up in NON TCP mode. Check the console and you will see messages about "Coordinator configured" (Again not exact message).
5. Once it comes up correctly in non TCP mode, you can then use AutoConf to go to TCP mode and then Zigbee2mqtt will start working.

**Comment by sfromis** [comment]
The easy way to delete a file is to click on the :fire: icon.

**Comment by forty76** [comment]
I have new Sonoff Zigbee ZBPro. I have installed tasmota32-zbbrdgpro.bin (ver. 14.3.0)
What is next step ?

Can you explain difference between
fw_SonoffZigbeeBridgePro_cc2652      ---->  (this send mqtt sentence?)
fw_SonoffZigbeeBridgePro_router_only_cc2652
fw_SonoffZigbeeBridge_ezsp

**Comment by sfromis** [comment]
EZSP is for the EFR32MG21-based non-"pro" Sonoff ZbBridge (or other devices using this chip), and `_router` is to downgrade the device to act as a Zigbee mesh router, instead of a coordinator you can use for home automation etc.

**Pull request merged**
