### PR TITLE
Attempt to solve issue #4754

### PR DESCRIPTION
**Pull request by localhost61**
Increase maximum mqtt username and password length from 32 to 40 chars.

### CODE REVIEW

**Comment by localhost61** [comment]
Yes Theo, I agree and don't mind if you don't merge it. That was just an easy workaround I could provide.
Now @deshark has a solution for testing.

**Comment by arendst** [comment]
Thx. Appreciated your suggestion.

Been looking over old issues and found a nice Azure IoT one: at least 150 characters… In the end all flash is user name and password and no functionality.

**Comment by ascillato2** [comment]
Hi,

Closing this PR as it is not going to be added soon. Added the label Feature Request (hold over) for future reference.

Thanks everyone for sharing their ideas and testings :+1:

**Comment by localhost61** [comment]
Hi @WiebKastanje,
Do you go ahead with the QIoT and Tasmota combo?
FYI, now that I'm a bit more comfortable with git, I've moved the main `development` branch of my repository to a new one named [`PR#4755`](https://github.com/localhost61/Sonoff-Tasmota/tree/PR%234755)  and it's now synced with current v6.4.1.17.

**Comment by WiebKastanje** [comment]
Hi Xavier @localhost61 
QIoT works now for me with your Tasmota fix. Not sure if I stick to it.
Looking into running HA in a docker container on my QNAP.
Thanks for updating me on the new name PR#4755 of your repository.

**Comment by WiebKastanje** [comment]
Hi Xavier @localhost61 
I've moved to running HA in a docker container on my QNAP.

Moreover I also quitted using MQTT and Tasmota. 
I'm using ESPHome (https://esphome.io/index.html) which integrates natively with Home Assistant.

Thanks again for your help relating to QNAP's QIot.

**Pull request closed without merging**
