### PR TITLE
Fix alexa discovery problem in hue emulation

### PR DESCRIPTION
**Pull request by oponyx**
## Description:
searching for new devices on Alexa echo dot 3th generation was giving no result.
the answer to the HUE light list api (http://tasmota/api/<username>/lights) before this fix was:
{
   "128946497":{
      "state":{
         "on":false,
         "alert":"none",
         "effect":"none",
         "reachable":true
      },
      "type":"Extended color light",
      "name":"Tapp",
      "modelid":"MHCHOZY4CH",
      "manufacturername":"Tasmota",
      **"uniqueid":"xx:xx:xx:xx:xx:xx:00:11-1"**
   }
}
the answer now is:
{
   "128946497":{
      "state":{
         "on":false,
         "alert":"none",
         "effect":"none",
         "reachable":true
      },
      "type":"Extended color light",
      "name":"Tapp",
      "modelid":"MHCHOZY4CH",
      "manufacturername":"Tasmota",
      **"uniqueid":"xx:xx:xx:xx:xx:xx:00:11-01"**
   }
}
this works. now searching for new devices works on the Alexa app, alexa.amazon.com, and asking to the echo dot without issues.
**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x ] The pull request is done against the latest development branch
  - [ x] Only relevant files were touched
  - [x ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ x] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with core ESP32 V.1.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by oponyx** [comment]
searching for new devices on Alexa echo dot 3th generation was giving no result.
the answer to the HUE light list api (http://tasmota/api/<username>/lights) before this fix was:
{
   "128946497":{
      "state":{
         "on":false,
         "alert":"none",
         "effect":"none",
         "reachable":true
      },
      "type":"Extended color light",
      "name":"Tapp",
      "modelid":"MHCHOZY4CH",
      "manufacturername":"Tasmota",
      **"uniqueid":"bc:dd:c2:7a:f9:14:00:11-1"**
   }
}
the answer now is:
{
   "128946497":{
      "state":{
         "on":false,
         "alert":"none",
         "effect":"none",
         "reachable":true
      },
      "type":"Extended color light",
      "name":"Tapp",
      "modelid":"MHCHOZY4CH",
      "manufacturername":"Tasmota",
      **"uniqueid":"bc:dd:c2:7a:f9:14:00:11-01"**
   }
}
this works. now searching for new devices works on the Alexa app, alexa.amazon.com, and asking to the echo dot without issues.
Tested on  echo dot 3th gen SW version 4799027076

**Comment by s-hadinger** [comment]
Thanks. I need to do some testing before merging

**Comment by s-hadinger** [comment]
Thanks for the PR. It is good for me.

@arendst you can merge.

**Comment by bwims** [comment]
Is this likely to fix the problem with Zigbee bridges?  If so, could you tell me how to obtain it, please?

**Comment by s-hadinger** [comment]
If you are referring to an Alexa discovery issue, most certainly yes.
Firmwares from the development branch can be found here: http://ota.tasmota.com/tasmota/

**Comment by RolfWojtech** [comment]
Just to give some feedback, I also had trouble getting a Tasmota 9.3.1 to get discovered by an echo show 2nd gen and echo 1st gen, by upgrading to 9.3.1.2 which includes this merge, it works again. So thanks a lot for this fix!

**Pull request merged**
