### PR TITLE
Bugfix multiple zero-cross dimmer + speed optimization

### PR DESCRIPTION
**Pull request by stefanbode**
- move sync from FUNC_LOOP to FUNC_EVERY_50MS
- Added documentation
- bugfix dimmer2 get off when dimmer1 get off
- automatic phase correction per channel

## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.2.3
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by stefanbode** [comment]
@Jason2866 : Di you know if there is a function for ESP32 like pwmfrequency where I can set the frequency to a float value like 50.008 (50Hz+a bit)? The driver currently only works on ESP8266 because I can use the internal startWaveformClockCycles that gives super granular access to the frequency.

**Comment by stefanbode** [comment]
This sounds interesting, but currently exceed my knowledge:
[LowSpeed PWM](https://forum.arduino.cc/t/esp32-what-is-the-minimum-pwm-frequency/671077/2)

**Comment by Jason2866** [comment]
@stefanbode  A actual library (IDF) https://github.com/vortigont/ESP32-LightManager/tree/master/src which shows actual possibilities for "PWM"

**Comment by stefanbode** [comment]
Thanks, and it looks like the light library has always INTEGER as input for frequencies. There is no direct way to set the frequency to 50.2Hz for example. I checked the motor driver I mentioned. This looks more flexible but the libraries seem not to be part of TASMOTA right now. I need to do more investigations on how to get this up and running. Current Error:
```
C:/Users/stbode/Documents/GitHub/arendst-Tasmota/tasmota/xsns_01_counter.ino:301:27: error: 'MCPWM_UNIT_0' was not declared in this scope
           mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM0A, Pin(GPIO_PWM1, i));     // Initialise channel MCPWM0A on GPIO pin 27
                           ^~~~~~~~~~~~
Retrieved `.pio\build\tasmota32\liba2c\lvgl\gpu\sdl\lv_gpu_sdl_draw_rect.c.o' from cache
C:/Users/stbode/Documents/GitHub/arendst-Tasmota/tasmota/xsns_01_counter.ino:301:27: note: suggested alternative: 'ADC_UNIT_2'
```

**Comment by arendst** [comment]
When you're going the MCPWM road you'll miss ESP32C3 and possibly others as it is only supported on ESP32.

**Comment by stefanbode** [comment]
@s-hadinger : I know you were one of the brains behind the waveform programming at esp8266. For me the situation is that all current available functions only allow INT as an input for the pulse duration. The ledc_timer_set has a frequency and a divider. Do you know what this frequency is? is it 80Mhz?

**Comment by s-hadinger** [comment]
You are giving me too much credit. No I don't know the détails of the frequency and dividers. Best option is too look at esp-idf source code

**Comment by s-hadinger** [comment]
Its here 
https://github.com/espressif/esp-idf/blob/2522277dfe51827575ea4724a1e54d1103aafd6f/components/driver/ledc.c#L464

**Comment by Jason2866** [comment]
ledc is documented for idf https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32/api-reference/peripherals/ledc.html

**Pull request merged**
