### PR TITLE
tuyamcu: allow sending arbitrary commands

### PR DESCRIPTION
**Pull request by danielkucera**
## Description:

**Related issue (if applicable):** fixes #<Tasmota issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Jason2866** [comment]
@blakadder Can you have a look?

**Comment by blakadder** [comment]
what's the application here?

**Comment by danielkucera** [comment]
Hello, this is the context: https://discord.com/channels/479389167382691863/479389167382691865/1172714100636258387

It allows sending the mesages for controlling the dimmer like this:
- full power `TuyaSend7 0x30,0003e4`
- off `TuyaSend7 0x30,000000`

**Comment by blakadder** [comment]
ok then, code just adds the new feature so I'm ok with it

**Pull request merged**
