### PR TITLE
improve http uploader for platformio upload comand

### PR DESCRIPTION
**Pull request by pgollor**
## Description:

- Add additional script to `pio-tools` to upload gzip firmware files via platformio upload command
- Removed dublicate of `espupload.py`
- modify `http-uploader.py` to work with other `espupload.py` script

To work it is needed to modify the `[env]` section like:
```
[env]
upload_port              = -i domus1 -p 80 -u /tasmota/uploader.php
extra_scripts            = ${esp_defaults.extra_scripts}
                           pio-tools/http-gz-uploader.py

[env:tasmota32_base]
upload_port             = -i domus1 -p 80 -u /tasmota/uploader.php
extra_scripts           = ${esp32_defaults.extra_scripts}
                          pio-tools/http-uploader.py
```

PR for documentation will comming soon.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works with Tasmota core ESP32 V.2.0.5
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
Oh my.

I'm just in the process of rewriting this stuff. I'm doing the gz stuff on the server side using a php script like:

```
<?php
// mkdir and chmod arduino folder to 777
//
//var_dump($_FILES);

/**
 * GZIPs a file on disk (appending .gz to the name)
 *
 * From http://stackoverflow.com/questions/6073397/how-do-you-create-a-gz-file-using-php
 * Based on function by Kioob at:
 * http://www.php.net/manual/en/function.gzwrite.php#34955
 *
 * @param string $source Path to file that should be compressed
 * @param integer $level GZIP compression level (default: 9)
 * @return string New filename (with .gz appended) if success, or false if operation fails
 */
function gzCompressFile($source, $level = 9){
    $dest = $source . '.gz';
    $mode = 'wb' . $level;
    $error = false;
    if ($fp_out = gzopen($dest, $mode)) {
        if ($fp_in = fopen($source,'rb')) {
            while (!feof($fp_in))
                gzwrite($fp_out, fread($fp_in, 1024 * 512));
            fclose($fp_in);
        } else {
            $error = true;
        }
        gzclose($fp_out);
    } else {
        $error = true;
    }
    if ($error)
        return false;
    else
        return $dest;
}

$image = basename($_FILES["file"]["name"]);
//$image = $_FILES["file"]["name"];  // Solves an issue where basename returns Array
$target_file = "tasmota/".$image;
$hostname = $_SERVER['SERVER_NAME'];

if (move_uploaded_file($_FILES["file"]["tmp_name"], $target_file)) {
  if (strpos($target_file, "tasmota32")) {
    echo "The file $image has been uploaded to OTA server $hostname. \n";
  } else {
    gzCompressFile($target_file);
    echo "The files $image and $image.gz have been uploaded to OTA server $hostname. \n";
  }
} else {
  echo "Sorry, there was an error uploading your file $image to OTA server $hostname. \n";
}
?>
```

I also wonder how on earth the espupload.py ever got in the tools folder. It should have been in the pio-tools folder

**Comment by arendst** [comment]
Agree. It has to be in the platform_override.ini file. This is a snapshot of mine:

```
; *** Serial port used for erasing/flashing the ESP82xx
;upload_port             = ${common.upload_port}
;upload_port             = COM21
;upload_resetmethod      = ${common.upload_resetmethod}
;extra_scripts           = ${esp_defaults.extra_scripts}
;                          pio-tools/obj-dump.py

; *** Upload file to OTA server in folder api/arduino using HTTP
;upload_port             = domus1:80/api/upload-arduino.php
upload_port             = otaserver/ota/upload-tasmota.php
extra_scripts           = ${esp_defaults.extra_scripts}
;                          pio-tools/obj-dump.py
                          pio-tools/http-uploader.py
```

**Comment by pgollor** [comment]
Okay sorry. I used it only in the `platformio_override.ini` file but there in the `[env]` section to define the main destination and in some user sections to upload some custom targets into a subfolder.

**Comment by Jason2866** [comment]
@arendst
>  I also wonder how on earth the espupload.py ever got in the tools folder. It should have been in the pio-tools folder

Never used and tbh not knowing how it is working, i didnt touch, when doing all the platformio rework. Dont touch stuff from "Master" :-)

**Comment by arendst** [comment]
That 's the best approach LoL.

Anyway, @pgoller let me do some tweaking first before continuing with this PR.

**Comment by pgollor** [comment]
> That 's the best approach LoL.
> 
> Anyway, @pgoller let me do some tweaking first before continuing with this PR.

okay thanks. Maybe the PR https://github.com/tasmota/docs/pull/1128 in the documentation should also be adjusted

**Comment by pgollor** [comment]
> I also wonder how on earth the espupload.py ever got in the tools folder. It should have been in the pio-tools folder

thre was a 50% 50% chance to do the right one fpr me. Maybe we can move the script from tools to pio-tools. I used the script at my jenkins server and not only from platformio. But I don't really care in which subfolder it is.

**Comment by Jason2866** [comment]
This is very intrusive since used for all env.
```
[env]
upload_port             = -i <privacy placeholder> -u /tasmota/upload.php
extra_scripts           = ${esp_defaults.extra_scripts}
                          pio-tools/http-gz-uploader.py
```
so no local upload (flash) via esptool.py possible anymore for every! env

**Comment by pgollor** [comment]
Oh okay sorry.
Okay im a little bit confused about all the different versions of _espupload.py_ ;-)

**Comment by pgollor** [comment]
Whether it's a complete URL or individual parameters, I think that's a personal preference. You decide what you think makes more sense.

**Comment by pgollor** [comment]
And i think repleacing the curl stuff with the requests library is a good idea.

**Comment by arendst** [comment]
What I'll do is renaming the current espupload.py into espupload_legacy.py and keep it in pio-tools removing the one from tools.

I'll then add my new espupload.py with the requests library. This way you can still select from one of the two.

I'll have a look at your gz implementation too.

**Comment by pgollor** [comment]
> This is very intrusive since used for all env.
> 
> ```
> [env]
> upload_port             = -i <privacy placeholder> -u /tasmota/upload.php
> extra_scripts           = ${esp_defaults.extra_scripts}
>                           pio-tools/http-gz-uploader.py
> ```
> 
> so no local upload (flash) via esptool.py possible anymore for every! env
> 
> If you do overrides on more places, this will generate "fun". Been there, and wasted some time with such and similar stuff. Platformio will behave at some point eratic when to many overrides, on different places, are done. Result are strange compile errors which does not give a clue what the real reason is. I spent many hours to get a nice, easy, flexible, stable predictable Tasmota Platformio setup done. Platformio has some "nice" bugs...

Okay sorry for that and thanks for your hint.

**Comment by pgollor** [comment]
> What I'll do is renaming the current espupload.py into espupload_legacy.py and keep it in pio-tools removing the one from tools.
> 
> I'll then add my new espupload.py with the requests library. This way you can still select from one of the two.
> 
> I'll have a look at your gz implementation too.

Thanks for your great work.

**Comment by arendst** [comment]
My latest PR builds on your groundwork and updates the following files:

- espupload.py and http-uploader.py in pio-tools
- upload-tasmota.php in your OTA server

The default behaviour now is that if a .bin.gz file is present it is uploaded to the OTA server. If not found it tries to upload the .bin file and generates a .bin.gz on the OTA server using the php script. 

Give it a try.

I hope we do not need to add some kind of override to enforce .bin over .bin.gz ;-)

**Pull request closed without merging**
