### PR TITLE
Initial DALI bus support

### PR DESCRIPTION
**Pull request by agners**
Initial support for DALI (Digital Addressable Lighting Interface) bus
support. Currently only two commands are implemented which send out
commands using bus broadcasts. This is sufficient to control a single
DALI capable device.

The DALI library has been borrowed from the Simple DALI Controller
project:
https://create.arduino.cc/projecthub/NabiyevTR/simple-dali-controller-506e44

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [ ] The code change is tested and works on core 2.3.0, 2.4.2 and 2.5.2
  - [ ] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

These routines uses delay function that can interfere with other Tasmota routines. 

Have you experienced any problem with wifi or mqtt stability?

**Comment by ascillato2** [comment]
Travis tests fail due to missing key in all language files.

**Comment by arendst** [comment]
In addition adding a GPIO in the middle of the GPIO list will break backwards compatibility too

**Comment by agners** [comment]
> Hi,
> 
> These routines uses delay function that can interfere with other Tasmota routines. Some delays are greater than half second.
> 
> Have you experienced any problem with wifi or mqtt stability?

So far I have not, but also only used it for 2 hours or so.

> 
> I think the library should be rewritted to a non-blocking routine.

Since the protocol is using a fixed data rate (1200 bit/s) and we use bit banging, timing is somewhat crucial... Maybe we could buffer and bitbang using a timer or similar?

**Comment by agners** [comment]
Will address the other comments sometime next week.

**Pull request closed without merging**
