### PR TITLE
Odroid_go flash files

### PR DESCRIPTION
**Pull request by Jason2866**
## Description:

since Odroid_go partition table is different

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works on Tasmota core ESP8266 V.2.7.4.9
  - [x] The code change is tested and works on Tasmota core ESP32 V.1.0.5-rc4
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by arendst** [comment]
Oops we crossed on the workflow files. I added tasmota32-AF and tasmota-odroidgo file copy.

Let's see what the Actions check comes uo with

**Comment by Jason2866** [comment]
Added your changes. Should now work to Merge

**Comment by arendst** [comment]
Why is this needed?

The M5Stack-core2 also will have a different partition table. 

In platformio_tasmota_env32.ino is a dedicated entry for odroid-go:
```
[env:tasmota32-odroidgo]
extends                 = env:tasmota32
board                   = odroid_esp32
board_build.f_cpu       = 240000000L
board_build.partitions  = esp32_partition_app1984k_ffat12M.csv
build_flags             = ${common32.build_flags} -DFIRMWARE_ODROID_GO
lib_extra_dirs          = lib/libesp32, lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div, lib/lib_ssl, lib/lib_display
```
PlatformIO does generate the partition table in .pioenvs during compilation and I supposed esptool will use it when flashing.

**Comment by Jason2866** [comment]
It is needed for the people who uses the precompiled binaries. The do not have a valid partition file.
You are right everyone who does self compile with PlatformIO have to think about nothing.
And yes the M5Stack core will have a different partition table too.

**Pull request merged**
